### ISSUE TITLE
Change Filename during upload

### ISSUE THREAD

**Issue by manusharma1** [VeliovGroup/Meteor-Files#100]
Hi @dr-dimitru 

I was trying to give fileName:'manutest.jpg', , Its not working
```
      var file = template.find('.image-upload-class').files[0];
      if (file) {
        var uploadInstance = Images.insert({
          file: file,
		  fileName:'manutest.jpg',
          streams: 'dynamic',
          chunkSize: 'dynamic'
        }, false);
```

How can I specify the file name during insert?, Is there is any way out? I want to change the filename to different name and don't want to keep default name.

Any Possibility?

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
Implemented in `dev` branch, please test it on your end

**Comment by manusharma1** [comment]
Wow!, That's Great, Please allow me sometime, I will get back on this soon.

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

How to check dev version actually I have never done it, Can you let me know the steps

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
In meteor's project dir (*btw it's better to Google it*):
```shell
mkdir packages
cd packages
git clone https://github.com/VeliovGroup/Meteor-Files.git
cd ../
meteor update && meteor
```

**Comment by manusharma1** [comment]
Thanks, I will check it and get back with my update,

**Comment by dr-dimitru** [comment]
@manusharma1 any news from your end?

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

I have tested it and found that it is working but I was expecting the filename to be saved as the given filename on the disk, Right now it is saving as the ID and extension, It is possible that filename if given as : fileName: 'manutest.jpg' , then on the disk aslo it will be saved as the same name.

Thanks for your quick replies and I really appreciate your nature of reminding for the issues, Keep it up!

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
Hi @manusharma1 ,

*I wouldn't recommend to change the way lib naming files in FS*, but this is possible via [`config.namingFunction`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) in [Constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

> Thanks for your quick replies and I really appreciate your nature of reminding for the issues, Keep it up!

Appreciated, thank you for using this package and your contribution.
