### ISSUE TITLE
[SOLVED] Autoform Integration

### ISSUE THREAD

**Issue by Neobii** [VeliovGroup/Meteor-Files#101]
Since collectionFS has been deprecated, there is no good solution for file uploads integrating with autoform.  The last good solution was https://github.com/yogiben/meteor-autoform-file .

**Comment by Neobii** [comment]
If you can start a new repo and add me as a contributor, I can get the initial files etc in place for you and do as much as I can.

**Comment by dr-dimitru** [comment]
@Neobii I thought to clone the [autoform-file](https://github.com/yogiben/meteor-autoform-file) and simply adapt to this package, what do you think?

**Comment by Neobii** [comment]
Sure, I was going to do most of the beginning of the adaptation for you if
you'd like.  I just want to make sure you own the repo, that's why I didn't
clone myself.  Just paste a message with the new repo and I'll start the
adaptation.

**Comment by dr-dimitru** [comment]
https://github.com/VeliovGroup/meteor-autoform-file/invitations

**Comment by dr-dimitru** [comment]
No CoffeeScript in docs please (*if you will do docs*)

**Comment by Neobii** [comment]
Okay, I got package.js started and changed readme from coffeescript to javascript.  I'll try to get more of the code set up for you in a few hours.

**Comment by dr-dimitru** [comment]
Hi @Neobii ,

I'm about to publish new release and would like to close all current issues, will we introduce *Autoform Integration*? Or skip to the next release?

**Comment by Neobii** [comment]
I think we should start managing issues on that repository instead of here.  I think with the previous autoform-file with 23,520 downloads, the repo will have enough attention to standalone.

**Comment by dr-dimitru** [comment]
Moved to https://github.com/VeliovGroup/meteor-autoform-file/issues

**Comment by dr-dimitru** [comment]
For every one who looking for autoform integration, see: [meteor-autoform-file](https://github.com/VeliovGroup/meteor-autoform-file), *already stable release*

**Comment by dr-dimitru** [comment]
Closing in favour of docs and https://github.com/VeliovGroup/meteor-autoform-file
