### ISSUE TITLE
Need control over onAfterUpload events

### ISSUE THREAD

**Issue by newsiberian** [VeliovGroup/Meteor-Files#105]
Hello, thanks for efforts on this project.
I need to run a callback after an image will be successfully uploaded to 3rd party storage. I'm not sure how this could be done. Is there a way to pass arguments from client side (insert method) to `onAfterUpload`?

Is it make sense to you to add something like `onAfterUploadEnd` event to insert method?

**Comment by dr-dimitru** [comment]
Hi @newsiberian ,

1. No, `onAfterUpload` is server-only callback
2. You need to implement callback yourself. I mean there is should be a way to define callback on method which sends data to 3rd party storage
3. `onAfterUploadEnd` can't implement it as it will be unique for each case
4. In Demo-app we wait for changes in MongoDB (*which automatically is sent to client*), we change record as file sent to DropBox. For example you can use `meta.sentTo3rd` property

**Comment by dr-dimitru** [comment]
HI @newsiberian ,
Any news on your end? I'm about to publish new release and would like to close all current issues, let me know if this one is solved.

**Comment by newsiberian** [comment]
Thanks for asking. I'm understand that you are suggest to me, but I'm temporary switched to another task, so we could close this. I'll reopen issue if the question comes up again.
