### ISSUE TITLE
Load API error handling

### ISSUE THREAD

**Issue by Sabst** [VeliovGroup/Meteor-Files#106]
Hi,
I'm using ostrio:files@1.5.6 I see the following behavior on a production deployment:
- initial load calls fail without any visible error
- the files in `assets/app/uploads/files` all contain the following text:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
This looks like the error I should have received in the callback and the file should not exist, no?

Note1: That still does not explain why I get an error: the file url given to load is exactly the same that I use successfully using a browser (it's using https): I'm trying to look into that... any idea?

Note2: All this works perfectly well using dev environment (not using https). I applied with success the trick from a gitter discussion to put the ostrio:files package before flow-router.

Update1: I tested in dev environment using the same files as the production env (https URIs). It worked without any problem. So the issue is somewhere else.

**Comment by dr-dimitru** [comment]
1. Could you post your Server configuration (*nginx*, *mup*, *passenger*, *node,js*, or what you're using on server)?
2. What if you run server without proxy? Just `node main.js`?

**Comment by Sabst** [comment]
I will gather this information and come back to you.
In case this can be helpful, upload works as expected.

**Comment by dr-dimitru** [comment]
I'm running apps behind Load-Balancer, Nginx and Phusion Passenger, and everything is works.
I can help you with configs.

**Comment by Sabst** [comment]
Ok, I saw a number of references to a similar issue but failed to find the exact settings.

Here are my current config files for nginx and my server (not using any LB, mup* or Phusion Passenger for now).
Just running the server with forever:
`forever start --uid myapp -a main.js`

Now, I turned nginx and firewall off and used a plain http address... I get in the traces:
```
Exception in callback of async function: Error: Error on [load(http://myserver.tld:54274/3.jpg)]:{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"myipaddress","port":54274} [500]
    at packages/ostrio_files/files.coffee:742:17
    at packages/ostrio_files/files.coffee:17:55
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

Which is weird as curl has no problem (from another system) using the same URI as in the error above:
```
 Connected to myserver.tld (myipaddress) port 54274 (#0)
> GET /4.jpg HTTP/1.1
> User-Agent: curl/7.35.0
> Host: myserver.tld:54274
> Accept: */*
> 
< HTTP/1.1 200 OK
< ETag: "decff1090f21decada972b9c08db15d403827c6f"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=0
< Content-Type: image/jpeg
< Content-Length: 306766
< Date: Mon, 20 Jun 2016 16:24:44 GMT
< Connection: keep-alive
```

I must be doing something really silly ;)

Thank you advance for your help.
```
################################################
# nginx.conf
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 300; # S2w - was 65
	types_hash_max_size 2048;
	server_tokens off; # s2w

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	##
	# nginx-naxsi config
	##
	# Uncomment it if you installed nginx-naxsi
	##

	#include /etc/nginx/naxsi_core.rules;

        fastcgi_buffers 8 16k; # S2w
        fastcgi_buffer_size 32k; # S2w

	##
	# nginx-passenger config
	##
	# Uncomment it if you installed nginx-passenger
	##
	
	#passenger_root /usr;
	#passenger_ruby /usr/bin/ruby;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

```
################################################
# my server configuration
# we're in the http context here
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
    listen 443 ssl;

    server_name mydomain.tld;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_certificate /etc/letsencrypt/live/mydomain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.tld/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    error_page 401 403 404 /404.html;

    location / {
        proxy_pass  http://127.0.0.1:54274/;
        # http://stackoverflow.com/questions/17014969/meteor-websocket-handshake-error-400-with-nginx
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;  # pass the host header - http://wiki.nginx.org/HttpProxyModule#proxy_pass
        proxy_http_version 1.1;  # recommended with keepalive connections - http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version

        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X_FORWARDED_PROTO https;
        proxy_buffering     off;
        proxy_redirect      off;
    }

    location /robots.txt {
        alias /home/s2w/nginx/robots.txt;
    }

    # http://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/
    client_max_body_size 40M;
}

server {
    listen 80;
    server_name mydomain.tld;
    return 301 https://$host$request_uri;
}

```

**Comment by dr-dimitru** [comment]
If you trying to `.load()` file from outside of server you need to omit the `54274` port and use `https` protocol, as `.load()` don't like the redirects `return 301 https://$host$request_uri;`

**Comment by Sabst** [comment]
Yeap, that's what I do: I use Meteor.absoluteUrl to get the server name (which is https://myserver.tld when nginx is active).
But that's when nginx is on. 

Currently I turned it off (so no redirection takes place and no https is involved).
In this context I still get the ECONNREFUSED error.

Sorry for adding confusion with the nginx conf files but I do not think they are helpful at that stage as nginx is not used!.

Apart from redirections, do you see another reason for getting ECONNREFUSED from Load API when direct download with curl is ok?

**Comment by dr-dimitru** [comment]
You can not access same machine by public address (*At least any unix**). Use 127.0.0.1

**Comment by dr-dimitru** [comment]
> Apart from redirections, do you see another reason for getting ECONNREFUSED from Load API when direct download with curl is ok?

You've said you've used another machine:
> Which is weird as curl has no problem (__from another system__) using the same URI as in the error above:

**Comment by Sabst** [comment]
Still stuck with this configuration:
- nginx off
- firewall is off
- server url is http://myserver.tld:54274
- load url is http://127.0.0.1:54274/somefile.jpg

Here is the server trace:
```
Exception in callback of async function: Error: Error on [load(http://127.0.0.1:54274/3.jpg)]:{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":54274} [500]
    at packages/ostrio_files/files.coffee:742:17
    at packages/ostrio_files/files.coffee:17:55
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

Curl is ok from the server system itself using the same URI as above:
 ```
curl -vvv http://127.0.0.1:54274/3.jpg
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 54274 (#0)
> GET /3.jpg HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:54274
> Accept: */*
> 
< HTTP/1.1 200 OK
< ETag: "fc4dd29e3251f321c6ece3969028503efff02f9e"
< Accept-Ranges: bytes
< Cache-Control: public, max-age=0
< Content-Type: image/jpeg
< Content-Length: 128733
< Date: Mon, 20 Jun 2016 19:53:11 GMT
< Connection: keep-alive
```

Can it still be a conflict with flow-router (only visible in prod)?
Do you know if other users mixing Meteor-Files and flow-router managed to make is work (including load API)?

**Comment by dr-dimitru** [comment]
1. What if you try to load `https://raw.githubusercontent.com/VeliovGroup/Meteor-Files/master/logo.png`?
2. Could you try v1.6.0 from `dev` branch?
3. Can you get this file in a browser?
4. If you can open file in a browser (*and via CURL*) - there is no conflict between Router and MF (*Have you put MF above FR in .meteor/packages, right?*)

**Comment by dr-dimitru** [comment]
BTW what size of the `3.jpg`? `128733` bytes?

**Comment by Sabst** [comment]
>BTW what size of the 3.jpg? 128733 bytes?
Yes
About previous questions:
1. It works perfectly (dev and prod)
2. This is in progress but this requires a more recent meteor version and upgrade (esp. dependency on accounts base package) is not currently so obvious (I get module dependency errors)... will let you know
3. This depends on the previous point
4. Yes, in the initial version the conflict issue appeared to be solved when I moved MF first in the packages list. Will need to check with v1.6.0

**Comment by Sabst** [comment]
(I managed to run using 1.3.3.1 version... just had to get rid of the .babelrc file)
I have exactly the same behavior using v1.6.0 (works with your logo file, fails with my local files).
Notes: 
- The error is now correctly caught and the error callback of Load API is being called (I mean the callback with an error parameter).
- Files with errors are still created in the uploads directory with a 0 size

**Comment by Sabst** [comment]
I finally switched to addFile instead of load.
All is working now, including using https.
The initial issue remains but I have no idea where it's coming from.

**Comment by dr-dimitru** [comment]
Hi @Sabst ,
Could you test *initial issue* within v1.6.0 from `dev` branch?

**Comment by Sabst** [comment]
@dr-dimitru, I tested with the version available 3 days ago (on 21st). This is now a bit tricky to test the issue again... I will see if I can do it as part of the next deployment (I will probably include some specific testing route).
I will let you know.
Thanks for the follow-up.

**Comment by Sabst** [comment]
This is working fine now, thanks!
The only thing to keep in mind is that error handling is not really useful (I don't think this is related to MF): even non existing URI return success (and the file contains the empty page source code!).
See for example, http://127.0.0.1:3000/doesNotExist.jpg

Note also that this also works well with nginx and firewall running: they will not be involved anyway as the request is done locally.

Feel free to close if you agree with my point about error handling (is that an issue against meteor or maybe I did something wrong?).

**Comment by dr-dimitru** [comment]
@Sabst ,

> The only thing to keep in mind is that error handling is not really useful (I don't think this is related to MF): even non existing URI return success (and the file contains the empty page source code!).

It's expected behaviour, as Mf listen for route, like: `#{self.downloadRoute}/#{self.collectionName}`

**Comment by dr-dimitru** [comment]
@Sabst 
I'm glad it works now on your end, please support this project by starring it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). 
Also you may like to [Tweet](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files&text=File%20upload%20and%20delivery%20in%20Meteorjs%20-%20now%20it's%20easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
