### ISSUE TITLE
Get Exif of image after upload and show error to user.

### ISSUE THREAD

**Issue by felipesmendes** [VeliovGroup/Meteor-Files#107]
I'm trying to get GPS information from image in afterUpload and if the imagem doesn't have GPS information I need to show one alert to user.

How can I do that?

I'm trying something like this, but in 'end' event fileObj don't have latitude and longitude information like I set.
```js
onAfterUpload: function(fileRef) {
    try {
      new ExifImage({
        image: fileRef.path
      }, function(error, exifData) {
        if (error) {
          return 'Imagem without Information';
        } else {
          var latitude, longitude, infoGps ;
          infoGps = exifData.gps;
          if (infoGps ['GPSLatitudeRef'] == 'S') {
            latitude = parseFloat(infoGps ['GPSLatitude'][0]) *
              -1;
          }
          if (infoGps ['GPSLongitudeRef'] == 'W') {
            longitude = parseFloat(infoGps ['GPSLongitude'][0]) *
              -1;
          }
          if ((latitude === '' || latitude === undefined) && (
              longitude ==='' || longitude === undefined)) {
            return 'Imagem without Information of GPS';
          }
          fileRef.latitude = latitude;
          fileRef.longitude = longitude;
        }
      });
    } catch (error) {
      return 'Image without Information';
    }
    return fileRef;
  }
```

**Comment by dr-dimitru** [comment]
I recommend to move into Method (*and use* `meta` *to store meta-data as lat;lon;*):
```js
// From basic example
Template.uploadForm.onCreated(function () {
  this.error = new ReactiveVar(false); // This will show Error as text to User
  this.processing = new ReactiveVar(false); // This will show to User what file is uploaded and further processing is in progress
  this.currentFile = new ReactiveVar(false);
});

Template.uploadForm.events({
  'change #fileInput': function (e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
      uploader = Images.insert({
        file: e.currentTarget.files[0],
        streams: 'dynamic',
        chunkSize: 'dynamic'
      }, false);

      uploader.on('start', function () {
        template.error.set(false);
        template.currentFile.set(this);
      });

      uploader.on('end', function (error, fileObj) {
        if (!error) {
          template.processing.set(true);
          Meteor.call('getEXIF', fileObj, function (error, result) {
            if (error) {
              template.error.set(error.reason || error);
            }
            template.processing.set(false);
            template.currentFile.set(false);
          });
        } else {
          template.currentFile.set(false);
          template.error.set(error.reason || error);
        }
      });

      uploader.on('uploaded', function (error, fileObj) {
        if (!error) {
          alert('File "' + fileObj.name + '" successfully uploaded');
        }
      });

      uploader.on('error', function (error, fileObj) {
        alert('Error during upload: ' + error);
      });

      uploader.start();
    }
  }
});
```

Method:
```js
Meteor.methods({
  getEXIF: function (fileRef) {
    check(fileRef, Object);
    try {
      new ExifImage({
        image: fileRef.path
      }, function(error, exifData) {
        if (error) {
          return 'Imagem without Information';
        } else {
          var latitude, longitude, infoGps ;
          infoGps = exifData.gps;
          if (infoGps ['GPSLatitudeRef'] == 'S') {
            latitude = parseFloat(infoGps ['GPSLatitude'][0]) *
              -1;
          }
          if (infoGps ['GPSLongitudeRef'] == 'W') {
            longitude = parseFloat(infoGps ['GPSLongitude'][0]) *
              -1;
          }
          if ((latitude === '' || latitude === undefined) && (
              longitude ==='' || longitude === undefined)) {
            throw new Meteor.Error(400, 'Image without Information');
          }
          // Store lat;log; in meta:
          Images.collection.update(fileRef._id, {
            '$set': {
              'meta.latitude': latitude
              'meta.longitude': longitude
            }
          });
        }
      });
    } catch (error) {
      throw new Meteor.Error(400, 'Image without Information');
    }
    return true;
  }
});
```

**Comment by dr-dimitru** [comment]
@felipesmendes Updated answer above to wait for end of async task

**Comment by felipesmendes** [comment]
@dr-dimitru Thank you so much! I tried to test the code and got this error:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\felipe\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe" "C:\\Users\\felipe\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.3_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "fibers"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by dr-dimitru** [comment]
~~Awk Windows...~~

Then try to install Fibers:
 - `meteor npm install fibers@1.0.13`, if this won't work see next step
 - `npm install -g fibers@1.0.13`, if this won't work see next step
 - Try to switch to `Meteor.wrapAsync()`, [read more](https://themeteorchef.com/snippets/synchronous-methods/)

**Comment by felipesmendes** [comment]
@dr-dimitru Fuck Windows man! 1 and 2 Steps doens't work.

I need to move to Meteor.wrapAsync()...please, could you change the example code ?

**Comment by dr-dimitru** [comment]
Sorry, nope, for this I need to know API of ExifImage.
I gave you a link to good tutorial, use it please.

**Comment by nicooprat** [comment]
Not sure if it can help, but I had to do the same thing lately, and used this library https://github.com/blueimp/JavaScript-Load-Image to get Exif datas client-side before uploading. Works quite well (I also used it to resize/compress images). Just use it and then call the upload method in its callback.

**Comment by dr-dimitru** [comment]
Hi @felipesmendes , any news on your end? Do you found a way to use `wrapAsync`?

**Comment by felipesmendes** [comment]
Hi @dr-dimitru, yes man! I moved to solution from @nicooprat and it worked very well!

Thank you all!

**Comment by dr-dimitru** [comment]
@felipesmendes 
Glad you make it work, please support this project by starring it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). 
Also you may like to [Tweet](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files&text=File%20upload%20and%20delivery%20in%20Meteorjs%20-%20now%20it's%20easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
