### ISSUE TITLE
Dropbox integration error

### ISSUE THREAD

**Issue by LeG3nDz** [VeliovGroup/Meteor-Files#111]
Hi,

I would like test [dropbox integration](https://github.com/VeliovGroup/Meteor-Files/wiki/DropBox-Integration), but i've error :

`W20160627-11:44:47.796(2)? (STDERR)
W20160627-11:44:47.796(2)? (STDERR) C:\Users\str\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160627-11:44:47.797(2)? (STDERR)
throw(ex);
W20160627-11:44:47.797(2)? (STDERR)                                                   ^
W20160627-11:44:47.797(2)? (STDERR) TypeError: undefined is not a function
W20160627-11:44:47.797(2)? (STDERR)     at meteorInstall.lib.images.collection.js (lib/images.collection.js:36:14)
W20160627-11:44:47.797(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160627-11:44:47.797(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160627-11:44:47.797(2)? (STDERR)     at C:\wamp\www\Meteor-Files\demo-simplest-upload\.meteor\local\build\programs\server\app\app.js:242:1
W20160627-11:44:47.797(2)? (STDERR)     at C:\wamp\www\Meteor-Files\demo-simplest-upload\.meteor\local\build\programs\server\boot.js:283:10
W20160627-11:44:47.797(2)? (STDERR)     at Array.forEach (native)
W20160627-11:44:47.797(2)? (STDERR)     at Function._.each._.forEach (C:\Users\str\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160627-11:44:47.798(2)? (STDERR)     at C:\wamp\www\Meteor-Files\demo-simplest-upload\.meteor\local\build\programs\server\boot.js:133:5`

I've test with local upload, and it work nice.

Do you have any idea why i've this error ?

Thak you !

**Comment by dr-dimitru** [comment]
Hi @LeG3nDz ,
what is here: `lib/images.collection.js:36` ?

**Comment by LeG3nDz** [comment]
Hi @dr-dimitru 

`images.collection.js` isn't part of my files.

**Comment by dr-dimitru** [comment]
And nor part of Meteor-Files package
What code related to MF package do you have?

**Comment by LeG3nDz** [comment]
I've cloned `Meteor-Files` repo and test with `demo-simplest-upload`, no other package :)

**Comment by dr-dimitru** [comment]
1. What version of Meteor are you using?
2. What platform you're build app? With which flags?
3. Have you seen [this thread](https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460)

**Comment by LeG3nDz** [comment]
Hi,

I'm using `meteor v1.3.2.4` (default version on `demo-simplest-upload` folder) and build on Windows 7.

**Comment by tab00** [comment]
I think the problem is that the example dropbox integration code is using https://github.com/dropbox/dropbox-js which is no longer maintained.

Please update the example code so that it uses https://github.com/dropbox/dropbox-sdk-js.

**Comment by dr-dimitru** [comment]
@tab00 this lib used daily, primary on http://meteor-files.herokuapp.com
Everything is fine

**Comment by tab00** [comment]
Which is the correct repository?:
https://github.com/dropbox/dropbox-sdk-js
https://github.com/dropbox/dropbox-js

dropbox-sdk-js states:
> This SDK will be taking the dropbox package name on npm from the [legacy SDK](https://github.com/dropbox/dropbox-js), that uses the old version of the Dropbox API. 

So dropbox-js seems like it has become obsolete. Its README.md says "This repository is no longer maintained". The getting started guide in that repository has `new Dropbox.Client()` as in the meteor-files dropbox example code.

Whereas dropbox-sdk-js does not have `new Dropbox.Client()`. It has `new Dropbox()`. So they are two different versions. The meteor-files example has code that uses the old unmaintained version.

When you run `npm install --save dropbox` the newer package (dropbox-sdk-js) is installed, not dropbox-js.

**Comment by dr-dimitru** [comment]
So, you can use dropbox-dk-js and share your experience with it. Then I'll update wiki and demo app(s)
Or you can install `npm install dropbox-js@=0.10.3`

**Comment by dr-dimitru** [comment]
I assume this ticket as solved.
DropBox API v1 will work during next 12 month.
For more info see: https://github.com/VeliovGroup/Meteor-Files/issues/112

**Comment by mibcadet** [comment]
Now it is deprecated, we need use v2, is it possible to still use VelioVGroup meteor files with dropbox?

**Comment by dr-dimitru** [comment]
Hello @mibcadet ,

Yes, you just need to switch to the new DropBox API.
Have you seen #112 ?

**Comment by mibcadet** [comment]
Hi, yes I seen but still I couldnt solve my issue. I use dropbox exactly as
in https://github.com/VeliovGroup/Meteor-Files/wiki/DropBox-Integration guide.
How to switch to new api?

pt., 10 lis 2017 o 13:18 użytkownik dr.dimitru <notifications@github.com>
napisał:

**Comment by dr-dimitru** [comment]
@mibcadet basing on existing docs -> https://www.dropbox.com/developers/reference/migration-guide

**Comment by dr-dimitru** [comment]
@mibcadet do not heistate to update our wiki docs with v2 API.
Also code in [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/435#issuecomment-305363734) is using APIv2
