### ISSUE TITLE
GridFS example

### ISSUE THREAD

**Issue by epaminond** [VeliovGroup/Meteor-Files#114]
I couldn't find an example of GridFS integration and I spent some time making it work correctly. Just thought it could be useful for someone else, so I created a [PR](https://github.com/VeliovGroup/Meteor-Files/pull/113) that adds example to docs.

It would be also great to add link to this example to wiki.

By the way, is it planned to add something like `onAfterRemove` hook? I also tried to use `onBeforeRemove` instead of rewriting `remove` method but it doesn't fire for some reason. But having `onAfterRemove` hook, that has access to removed documents would be even better. :smile:

**Comment by dr-dimitru** [comment]
Hi @epaminond ,
every `.remove()` method has a callback. Why this doesn't work for you?

Thank you for PR, I'll add to wiki after testing

**Comment by epaminond** [comment]
> every .remove() method has a callback. Why this doesn't work for you?

@dr-dimitru, it does, but inside callback I only get number of removed documents. I mean it would be more convenient to have at least their _id's or even content inside hook.

**Comment by dr-dimitru** [comment]
Sure, I'll add it to v1.6.0

**Comment by dr-dimitru** [comment]
Implemente in https://github.com/VeliovGroup/Meteor-Files/commit/696671a2a67e9cef4d1d06d067be3aef526d6910
Could you please test it from `dev` branch on your end?

**Comment by epaminond** [comment]
@dr-dimitru, tested it and updated example in PR to use `onAfterRemove` hook. Thanks for quick response.

I got an error in client console on dev branch, but this seems to be irrelevant to the topic:
`files.coffee:501 Uncaught TypeError: Accounts.onLogout is not a function`

**Comment by dr-dimitru** [comment]
@epaminond Thank you.
This bug also appeared in [this thread](https://github.com/VeliovGroup/Meteor-Files/issues/99) see last 3 messages. But, I can't reproduce it. Any help will be appreciated.

**Comment by epaminond** [comment]
OK, I'll check it later today.

**Comment by epaminond** [comment]
Here's my `.meteor/packages`:

```
# Meteor packages used by this project one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you
# but you can also edit it by hand.

# meteor libraries
meteor-base
ecmascript
es5-shim
check
tracker
reactive-dict
email
# standard libraries
jquery
underscore

# ui
static-html
react-meteor-data

# data
mongo
aldeed:simple-schema
aldeed:collection2
dburles:collection-helpers
mdg:validated-method
random
meteorhacks:aggregate

# routing
kadira:flow-router

# i18n
tap:i18n

# time and dates
momentjs:moment

# accounts
accounts-password
accounts-facebook
accounts-google
service-configuration

# mobile
#crosswalk
mobile-experience
#chriswessels:hammer

# production
standard-minifier-js
ddp-rate-limiter
seba:minifiers-autoprefixer
fourseven:scss

# files

#dev
anti:fake

#maps
dburles:google-maps
mizzao:user-status
ostrio:files
```

**Comment by dr-dimitru** [comment]
Add `accounts-base` package explicitly to `.meteor/packages`

**Comment by epaminond** [comment]
> 1. What do you get on: console.log(Accounts.onLogin, Accounts.onLogout)
> 2. What if you move accounts-base package above ostrio:files in .meteor/packages?
> 3. Which Meteor version you're on?

1. I get this if I set break point at `files.coffee:501`:
```
console.log(Accounts.onLogin, Accounts.onLogout)
VM64911:1 onLogin(func) {                                                                                         //
      return this._onLoginHook.register(func);                                      … undefined
```
2. I tried to add it explicitly, but it doesn't help
3. Meteor version is 1.3.2.4

**Comment by dr-dimitru** [comment]
I guess it's introduced in `Meteor@1.3.4` or `Meteor@1.3.3`

**Comment by dr-dimitru** [comment]
@epaminond If upgrade will help you - I'll update `versionsFrom`

**Comment by epaminond** [comment]
@dr-dimitru, it works starting with 1.3.3.1 version.
