### ISSUE TITLE
Check image dimension after upload

### ISSUE THREAD

**Issue by gesanchez** [VeliovGroup/Meteor-Files#115]
Hi,

I'm trying to get dimension of image after upload with gm, but how i could do to return error to client if image has not the correct dimension.

Thanks,

**Comment by dr-dimitru** [comment]
Hi @gesanchez ,

You need to implement blocking flow.
Use `Meteor.wrapAsync` or `Fibers/Future` - read its docs to find more

**Comment by gesanchez** [comment]
@dr-dimitru sorry,

How i could implement that method in the afterupload?, you could show me an example, please?

Thanks,

**Comment by dr-dimitru** [comment]
WrapAsync: http://stackoverflow.com/questions/22668718/how-to-make-meteor-methods-synchronous
Fibers/Future: https://www.discovermeteor.com/patterns/5828399
Google: https://www.google.ru/search?num=40&newwindow=1&q=meteor+sync+methods&oq=meteor+sync+methods&gs_l=serp.3..0i22i30.39006.39006.0.39797.1.1.0.0.0.0.221.221.2-1.1.0....0...1c.1.64.serp..0.1.220.Kwb1yWGa85A

**Comment by dr-dimitru** [comment]
Hi @gesanchez , any news on your end?

**Comment by dr-dimitru** [comment]
@gesanchez see [this thread](https://github.com/VeliovGroup/Meteor-Files/issues/107), hope this will help

**Comment by gesanchez** [comment]
Hi @dr-dimitru 

I have made this simple solution:

In the server
I have changed fileRef var and i added a field error with value true
`
ProfileInformationImages = new FilesCollection({
  collectionName: 'ProfileInformationImages',
  allowClientCode: true,
	storagePath: process.env.PWD + '/.uploads/profile_information/',
	downloadRoute: '/files/images',
	permissions: 0755,
  debug: false,
	cacheControl: 'public, max-age=31536000',
  onAfterUpload: function(fileRef){
    var gm = Meteor.npmRequire('gm'),
        self = this,
        Future = Meteor.npmRequire('fibers/future'),
        Fiber = Meteor.npmRequire('fibers'),
        myFuture = new Future();
       
           gm(fileRef.path).size(function(err, value){
      if (value !== undefined){
        if (value.width < 800 && value.height < 600){
          fileRef.error = true;
          Fiber(function(){
            self.remove({"_id" : fileRef._id});
          }).run();
          // myFuture.return(fileRef);
        }
}
      myFuture.return(fileRef);
    });
       return myFuture.wait();
}
});
`

In the client
`
  var upload = ProfileInformationImages.insert({
    file: file,
    streams: 'dynamic',
    chunkSize: 'dynamic'
  }, false);
  upload.on('start', function () {
  });

  upload.on('uploaded', function (err, fileObj){
    if (err){
      console.log(err);
    }else{
      if (fileObj.hasOwnProperty('error')){
       console.log('Error here's the trick');
      }
    }
  });

  upload.on('end', function (error, fileObj) {
    if (error) {
      cosole.log(error);
    } else {
    }
  });

  upload.start();
`

What do you think @dr-dimitru ?

Thank for you help

**Comment by dr-dimitru** [comment]
you can change:
`fileObj.hasOwnProperty("error")`
to:
`fileObj.error === true`

And no need to use `Fiber` here, as all callback of MF package already bounded to Fiber (*just remove it*):
```js
Fiber(function(){
  self.remove({"_id" : fileRef._id});
}).run();
```
But you need to wrap into __current__ Fiber all code in callback of `gm`:
```js
var bound = Meteor.bindEnvironment(function(callback) {
  return callback();
});

gm(fileRef.path).size(function(err, value){ 
  bound(function(){
    if (value !== undefined){
      if (value.width < 800 && value.height < 600){
        fileRef.error = true;
        self.remove({"_id" : fileRef._id});
      }
    }
    myFuture.return(fileRef);
  });
});
```

**Comment by gesanchez** [comment]
Great @dr-dimitru thanks for your recomandation

**Comment by dr-dimitru** [comment]
Glad we solved it.
Please support this project by starring it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). 
Also you may like to [Tweet](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files&text=File%20upload%20and%20delivery%20in%20Meteorjs%20-%20now%20it's%20easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)

**Comment by msio777** [comment]
HI @dr-dimitru . Is there any possibility to throw new Meteor.Error() instead of set a flag ?
Thanks

**Comment by dr-dimitru** [comment]
Hi @msio777 ,

It's possible only from method, otherwise it will break node.js process.
As async functions is discussed here the only way to tell the Client about error is additional property on Mongo doc.

**Comment by msio777** [comment]
@dr-dimitru thank you
