### ISSUE TITLE
how to add the file name to the namingFunction

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#117]
I want the file name saved in the server to have the "real name" too, but it seems that I cannot make it work, any suggestion? The following is my code:

namingFunction: function(){
        return Random.id() + '_' + this.name;
    },

**Comment by dr-dimitru** [comment]
Yes, currently it's not possible.
Moreover it protects you from mistake, if you have two or more files with same name.

I wouldn't recommend to change this behaviour.

**Comment by FrancoisYu** [comment]
Got it. Then I will just leave the file name as it its.
