### ISSUE TITLE
Insert MongoDb record then uploading, then update the status

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#118]
Is it possible that we can insert the mongoldb record first, then after the uploading is finished, update the record's status. The following is my scenario, don't if I can make it with your package:
1. User drops 10 files.
2. Create 10 records first while uploading the files.
3. User input some metadata for each file
4. User click Submit => save file.

The reason I want to have the mongoldb record before the uploading started is that I can use the "reactive" from the Meteor.

**Comment by dr-dimitru** [comment]
I've implemented this in v1.6.0
But a bit in different way.
This won't work if user will hang up the current session and wouldn't continue upload. You still will have a record in DB and file chunks on FS, which won't be ever removed.

In v1.6.0 there is special collection with pre-upload records. So We don't need to transfer meta and other data back and forward. And it has Session TTL, when record is removed from this collection and upload is undone - package frees memory dedicated for this upload, removes already uploaded chunks and etc.

Check `meteor mongo` with `show collections` and you will see "*that spacial collection*", I think you can use it, but I wouldn't recommend it.

If I understood you wrong, tell me more what you want to use "*reactivity*" for.

**Comment by FrancoisYu** [comment]
Yes, that' exactly what I want. I'll take a look for the pre-upload records. Thanks.
