### ISSUE TITLE
Where do you save the uploaded files before steam to s3 store

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#125]
I've my app hosting in the Modulus, and have the S3 as my file storage. In my apps, the client may upload more than 200 MB files to server. I am wondering the files are all saved in a temp directory or in the memory  or in the db before transfer to the S3 server.  If it's in the memory, then I may have to upgrade my servo's memory to 2048MB...

**Comment by dr-dimitru** [comment]
It's written to FS first. Then sent to S3. 
Library uses writableStreams, so memory usage is minimal. The max is chunkSize*streams

**Comment by FrancoisYu** [comment]
got it thx.
