### ISSUE TITLE
#-1/21 chunks?

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#126]
I've enabled the debug and can find the #-1 chunks..does this mean a retry sending or it's just the design:

I20160704-18:54:50.300(8)? [FilesCollection] [Write Method] [DDP] Got #21/23 chunks, dst: 20160602_101306.jpg
I20160704-18:54:50.462(8)? [FilesCollection] [Write Method] [DDP] Got #22/23 chunks, dst: 20160602_101306.jpg
I20160704-18:54:50.487(8)? [FilesCollection] [Write Method] [DDP] Got #23/23 chunks, dst: 20160602_101306.jpg
I20160704-18:54:50.496(8)? [FilesCollection] [Write Method] [DDP] Got #-1/21 chunks, dst: 484186 (1).zip
I20160704-18:54:50.497(8)? [FilesCollection] [Write Method] [finishUpload] -> assets\app\uploads\SourceZips1/bz4qQrCnQZMTvagZa.zip
I20160704-18:54:50.516(8)? sourcezips uploaded ok: 484186 (1).zip
I20160704-18:54:50.532(8)? [FilesCollection] [Write Method] [DDP] Got #-1/21 chunks, dst: 484186.zip
I20160704-18:54:50.539(8)? [FilesCollection] [Write Method] [finishUpload] -> assets\app\uploads\SourceZips1/TjAnTNSJQyQzhrAzT.zip
I20160704-18:54:50.545(8)? sourcezips uploaded ok: 484186.zip
I20160704-18:54:50.551(8)? [FilesCollection] [Write Method] [DDP] Got #-1/23 chunks, dst: 20160602_101306.jpg

**Comment by Dubbedge** [comment]
I may be having a simular issue:

**Versions:**
WIndows 10, Meteor v1.3.4.1, Chrome v51.0.2704.106 m, astrio:files v1.6.1

**Server Side Error:**

    [FilesCollection] [File Start Method] added_packages_v1.PNG - PCZxJKSEamAiWSFyw
    [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: added_packages_v1.PNG
    [FilesCollection] [Aport Method]: PCZxJKSEamAiWSFyw - undefined

**Console Side Error:**

![console_info](https://cloud.githubusercontent.com/assets/17178765/16564862/111857ca-41c7-11e6-9b74-d8aa18d7a8d9.PNG)

More Info about my folder structure, files, and code found on _stackoverflow.com_:
[http://stackoverflow.com/questions/37958542/meteor-files-error-please-upload-image-with-size-equal-or-less-than-10mb-40](url)

**Comment by dr-dimitru** [comment]
This is expected behaviour (from the [docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)):
> first chunk (chunkId=1 or chunkId=-1) and on eof (eof=true or chunkId=-1)

chunk has id `-1` on first and last chunk, and file-data isn't sent with it

**Comment by dr-dimitru** [comment]
@Dubbedge Issue described here is clearly says you're trying to upload file with unsupported extension (not an image) or with size larger than 10MB. Or it's caused by deprecation of `ext` property since `1.6.0` in `onBeforeUpload` hook.

Issue described on SO is Windows related, I guess caused by wrong slashes, going to check it now.

**Comment by dr-dimitru** [comment]
@Dubbedge please try version `1.6.2` from `dev` branch

**Comment by Dubbedge** [comment]
@dr-dimitru I gave up and removed all implementation of using Meteor-Files earlier today and I'm in the middle of implementing my own way which seems to be working. Still doing some testing. Once I finish, I'll give Meteor-Files a try again. I hope to give your new version a try sometime tomorrow.

**Comment by dr-dimitru** [comment]
@Dubbedge
 1. Have you tried `1.6.2`?
 2. Are you getting same error?

**Comment by Dubbedge** [comment]
Thanks! It works now :) Great job!
