### ISSUE TITLE
[FileCollection][insert] [Tracker][pause]

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#129]
Sometimes  I will encounter the "stop uploading" situation, and I can the the error msg. above from the Chrome console. I wait for more than 10 minutes but still cannot see the progress of the uploading. Any suggest that if I should detect the pause state and re-coninue again? or the codes will auto-continue by itself.

**Comment by dr-dimitru** [comment]
Should be auto-continiue
 1. In which case its set to pause? `Meteor.disconnect()`?
 2. This happened on `http` or `ddp` upload?

**Comment by FrancoisYu** [comment]
1. I cannot find why its set to pause. I just upload 10 files and find the progress is pause. The network is still connected.

2. ddp

Right now, I setup the instance to cotinue after 3 seconds if pause with the following codes:

sourcezips.on('pause', function (error, fileObj) {
                console.log('Pause during upload: ' + fileObj.name);
                Meteor.setTimeout(this.continue(), 3000);
            });

**Comment by dr-dimitru** [comment]
Post all debug messages you have in debug mode.
I guess when you try to upload you browser or meteor process is freezes. Try to set set `streams` option to `1` or `2` and/or set smaller `chunkSize`

**Comment by FrancoisYu** [comment]
I'll set the steam/chunkSize and test again. This problem only happens in 1 of my 5 notebooks.
