### ISSUE TITLE
Javascript download multiple files with the original file name

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#130]
The demo codes for downloading the files are all in the html page. Is there anyway I can use javascript to download 10 files all with their original file name.  I have the users to select 10 files and click one d/l button and will auto-download the 10 files.  I've tried to use the following codes, but it works on Chrome/Firefox, but not Edge;

console.log(zip.name);
                    $('<a></a>', {
                        "download": zip.name,
                        "href": url,
                        "id": id,
                        "target": "_parent"
                    }).appendTo("body")[0].click();

**Comment by dr-dimitru** [comment]
```html
<a id="download" href="http://url..." download="file1.png" target="_parent">
   File1
</a>
<a id="download" href="http://url..." download="file2.png" target="_parent">
   File2
</a>
<a id="download" href="http://url..." download="file3.png" target="_parent">
   File3
</a>
<a id="download" href="http://url..." download="file4.png" target="_parent">
   File4
</a>
```

```js
$('#download').click();
```

Filename specified in `download` attribute of `a` (anchor) element will be used as filename of downloaded file.

About Edge - sorry I have no possibility to test it.
Anyways this question is not related to this package, you should ask it on stackoverflow

**Comment by FrancoisYu** [comment]
thx for your gentil reply.
