### ISSUE TITLE
using http encounting socket hang up, the sever will restart

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#132]
I set the stream to 6, with 256000chunksize, sometimes, it will crash the server with the following error msg. Anything I should take a look:

I20160706-09:39:52.292(8)? [FilesCollection] [Write Method] [finishUpload] -> assets\app\uploads\SourceZips1/E3K4Xm3zPxrpXCBHY.zip
I20160706-09:40:02.767(8)? { '$set':
I20160706-09:40:02.767(8)?    { 'versions.original.meta.pipeFrom': 'https://dl8rnph9rxsql.cloudfront.net/sourcezips/tAnLKx3zgqkEEW7Dy/archive (1).zip',
I20160706-09:40:02.768(8)?      'versions.original.meta.pipePath': 'sourcezips/tAnLKx3zgqkEEW7Dy/archive (1).zip',
I20160706-09:40:02.769(8)?      'meta.storedat': Wed Jul 06 2016 09:40:02 GMT+0800 (China Standard Time),
I20160706-09:40:02.769(8)?      'meta.storfinished': true } }
I20160706-09:40:02.814(8)? sourcezips stored ok: archive (1).zip
I20160706-09:40:02.815(8)? [FilesCollection] [unlink(E3K4Xm3zPxrpXCBHY, original)]
W20160706-09:40:08.408(8)? (STDERR)
W20160706-09:40:08.410(8)? (STDERR) events.js:72
W20160706-09:40:08.410(8)? (STDERR)         throw er; // Unhandled 'error' event
W20160706-09:40:08.411(8)? (STDERR)               ^
W20160706-09:40:08.411(8)? (STDERR) Error: socket hang up
W20160706-09:40:08.412(8)? (STDERR)     at createHangUpError (http.js:1528:15)
W20160706-09:40:08.412(8)? (STDERR)     at CleartextStream.socketCloseListener (http.js:1578:23)
W20160706-09:40:08.413(8)? (STDERR)     at CleartextStream.emit (events.js:95:17)
W20160706-09:40:08.414(8)? (STDERR)     at tls.js:694:10
W20160706-09:40:08.414(8)? (STDERR)     at process._tickDomainCallback (node.js:502:13)
=> Exited with code: 8
=> Meteor server restarted

**Comment by dr-dimitru** [comment]
1. Is this error can be solved by changing 'stream' and 'chunkSize' to different values?
2. What if you temporary exclude 'unlink()' method? Will the error gone?

**Comment by FrancoisYu** [comment]
I think the problem is coming from the deletion of the upload instance during uploading. I've put my codes into different files with different templates, that means I cannot use reactive-var  but Session to store the upload instances.  

The following is the codes I use for store/remove the  uploading instances, any suggestion will be great.


let sourcezips = SourceZips1.insert({  // insert后面帶start時不能加collection ?? 原因不詳
                file: zipfile,
                meta: metadata,
                streams: 2,
                chunkSize: 256000,
                transport: 'ddp' //Note: upload via http is at least twice faster. HTTP will properly work only with "sticky sessions"      Default: ddp
            }, false);

            sourcezips.on('start', function(err, fileObj){
                uploads.push(this);
                Session.set('uploadsourcefiles', uploads); 

...

let fileId = this.config.fileId;
        let uploads = Session.get('uploadsourcefiles');
        let index = uploads.findIndex(function(ele, index, arr){ if (ele.config.fileId === fileId) return true});
        uploads.splice(index, 1);
        Session.set('uploadsourcefiles', uploads);

**Comment by dr-dimitru** [comment]
Why not use top-level variable to host `ReactiveVar`? Like:
```js
// lib/_start.js
this._app = {}; // <-- Attached to top-level object
Meteor.startUp(function () {
  _app.uploadsourcefiles = new ReactiveVar(false);
});

// client/template1.js
Template.one.helpers({
  uploadsourcefiles: function () {
    return _app.uploadsourcefiles.get()
  }
})

// client/template2.js
Template.two.helpers({
  uploadsourcefiles: function () {
    return _app.uploadsourcefiles.get()
  }
})
```

*Anyways this question is not related to this package, it's general Meteor question.*

*You've asked so many question last few days. Maybe it's better to publish your code somewhere, so I can take a look? Difficult to help, when I can't see full picture.*

**Comment by dr-dimitru** [comment]
Hi @FrancoisYu , any news on your end?

**Comment by dr-dimitru** [comment]
@FrancoisYu ?

**Comment by dr-dimitru** [comment]
@FrancoisYu this issue will be closed in 2 days due to silence on your end
