### ISSUE TITLE
record has been deleted before unlink

### ISSUE THREAD

**Issue by FrancoisYu** [VeliovGroup/Meteor-Files#133]
I've encountered the unlink Exception error, it happens with the following scenario:

1. User drops file -> 2.create db record-> 3.upload finished -> 4.storing to s3 -> 5.unlink the record

If user delete the file betweet step 3 and step 5, the unlink will not be able to find the fileRef, because it has been deleted.

The following is the error logs: 

sourcezips stored ok: 1250_309374_A3.5_BRX_Z7100.zip
I20160706-11:56:37.241(8)? Exception in callback of async function: TypeError: Cannot read property '_id' of undefined
I20160706-11:56:37.242(8)?     at FilesCollection.unlink (packages/ostrio_files/files.coffee:1421:54)
I20160706-11:56:37.242(8)?     at lib/collections.js:209:42
I20160706-11:56:37.242(8)?     at packages/mongo/collection.js:630:5
I20160706-11:56:37.243(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160706-11:56:37.243(8)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160706-11:56:37.244(8)?     at packages/mongo/mongo_driver.js:322:7
I20160706-11:56:37.244(8)?     at packages/mongo/mongo_driver.js:568:11
I20160706-11:56:37.246(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160706-11:56:49.865(8)? design stored ok: 1250_309374_A3.5_BRX_Z7100.zip
I20160706-11:56:49.868(8)? Exception in callback of async function: TypeError: Cannot read property '_id' of undefined
I20160706-11:56:49.868(8)?     at FilesCollection.unlink (packages/ostrio_files/files.coffee:1421:54)
I20160706-11:56:49.869(8)?     at lib/collections.js:349:42
I20160706-11:56:49.869(8)?     at packages/mongo/collection.js:630:5
I20160706-11:56:49.869(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160706-11:56:49.869(8)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160706-11:56:49.870(8)?     at packages/mongo/mongo_driver.js:322:7
I20160706-11:56:49.870(8)?     at packages/mongo/mongo_driver.js:568:11
I20160706-11:56:49.870(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**Comment by dr-dimitru** [comment]
You shouldn't let user to delete file unless it's fully processed (uploaded and transferred to storage). Add some flag to meta object, like 'uploadedToS3'. And unless it's false you can display something like 'processing file... Please wait...'

**Comment by FrancoisYu** [comment]
That's exactly what I'm doing now. I just setup a delete flag to the record and do a housekeeping for every 24 hours. Thanks.
