### ISSUE TITLE
Make CORS headers configurable

### ISSUE THREAD

**Issue by martunta** [VeliovGroup/Meteor-Files#141]
I could do it by entering line 
`  http.response.setHeader 'Access-Control-Allow-Origin', '*'`
next to the lines, but I guess it would better be configurable when constructing new files instance
```javascript
http.response.setHeader 'Content-Type', vRef.type
http.response.setHeader 'Content-Disposition', dispositionType + dispositionName + dispositionEncoding
http.response.setHeader 'Accept-Ranges', 'bytes'
http.response.setHeader 'Last-Modified', fileRef?.updatedAt?.toUTCString() if fileRef?.updatedAt?.toUTCString()
http.response.setHeader 'Connection', 'keep-alive'
```

**Comment by dr-dimitru** [comment]
Hi @martunta ,
This feature is implemented in [v1.6.3](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.6.3), as `config.responseHeaders` passed into `Constructor`.
See docs [here](https://github.com/VeliovGroup/Meteor-Files/wiki/Custom-Responce-Headers) and [here](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

Please, test it on your end.

**Comment by dr-dimitru** [comment]
@martunta have you tested it on your end?

**Comment by martunta** [comment]
yes, it works
