### ISSUE TITLE
where are the files stored?

### ISSUE THREAD

**Issue by jdmswong** [VeliovGroup/Meteor-Files#143]
Playing around with settings I set the storage path to `assets/app/uploads/uploadedFiles`, but I cannot find this directory anywhere.  Where are the files stored?

**Comment by dr-dimitru** [comment]
Hi @jdmswong ,

If you didn't start `storagePath` with leading slash, it's mean you're store file in relative path to running process. And it should be somewhere under `.meteor/build/server/` (*unltil Meteor@1.3.4.3*)

Since Meteor@1.3.4.4 it's changed *and currently I can't tell you where it's stored*.
I always recommend to use absolute path and store files under `/data` directory, you can try it.

**Comment by mking200** [comment]
Hi @dr-dimitru, If I use the default `storagePath` how can I backup the files from storage?

**Comment by dr-dimitru** [comment]
@mking200 @jdmswong 
You can check path to file in MongoDB records there is `path` field.
On production it is relative to `main.js` file (*the running script*)

**Comment by dr-dimitru** [comment]
@mking200 @jdmswong is this issue still persists?

**Comment by mking200** [comment]
Hi @dr-dimitru, can I ask how the `FileCursor.link()` generates the link to images?  And is it possible to override this, and create a custom link?  

I'm thinking of pointing the link to images in public folder, so I don't have to reset and insert the Images collection each time the app is run, or each time an update is pushed on the server.

**Comment by dr-dimitru** [comment]
@mking200 take a look on the `public` option of the [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by mking200** [comment]
Ok, but this will affect all uploads to the `FilesCollection` right?  Am just thinking of modifying some image upoads, but not for all uploads.

Are there any values I can change using `Images.collection.update( )`, so that the  `.link( )`  function will generate the custom link?

**Comment by dr-dimitru** [comment]
> Are there any values I can change using Images.collection.update( ), so that the .link( ) function will generate the custom link?

Link will be always the same.

> but this will affect all uploads to the FilesCollection right?

No, you will upload files as you did before

> Am just thinking of modifying some image upoads, but not for all uploads.

Create two collections, public and private

**Comment by Tbutnyakov** [comment]
Now files are stored in '.meteor/local/build/programs/server/assets/*collectionName' by default. 
So, in this case we have "server" folder as root directory. 
But, this is a problem, cause if we will  rebuild  the project, meteor will clean up 'build' directory and all  included files.

Can you explain, what can we do in this case?
Dima, ty for package.

**Comment by dr-dimitru** [comment]
@Tbutnyakov 

> I always recommend to use absolute path and store files under `/data` directory, you can try it.

I guess I should ad it to the docs somewhere, and give a notice about app rebuilds, and possible data loss.

@Tbutnyakov thank you for using this package

**Comment by dr-dimitru** [comment]
Hi @jdmswong , @mking200  and @Tbutnyakov 
I've added default storage path explanation into [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq)
Can we close this issue?

**Comment by Tbutnyakov** [comment]
I think yes, the other guys may forgot about this issue. 
By the way, im just create folder _inside_ a project with **Meteor.absolutePath**.
Dima, package is a very good, but i think you need create a more structured DOCs?
For example, i love the Astronomy package doc. It created with help of github tools.

Look at this: http://jagi.github.io/meteor-astronomy/v2

**Comment by dr-dimitru** [comment]
I thought about it, but separate website only for docs is overhead. I would like to keep everything in wiki, but I'm agree what now it's a bit difficult to read. So, I'm still looking for better solution for docs. May be jsdoc on GitHub Pages will be good solution.

**Comment by mking200** [comment]
@dr-dimitru No more issues for me on this one.

**Comment by BananaCloud** [comment]
hi there, if I provide storagePath: '/data' or some other names will give me a not writable error:

throw new Meteor.Error(401, "[FilesCollection." + self.collectionName + "] Path \"" + self.storagePath + "\" is not writable!", error);

where exactly this \data should be created? What permissions I should give?

**Comment by dr-dimitru** [comment]
Hi @BananaCloud ,

Try to start with with:
```shell
mkdir /data
chmod 777 /data
```

**Comment by BananaCloud** [comment]
Thanks for your fast response, I just figured it's actually the root folder of the server.

**Comment by janjackson** [comment]
Are we talking about the production server or localhost? I can't find my images on production and occasionally they disappear. What is the full path to  the image dir?

**Comment by dr-dimitru** [comment]
@janjackson whatever you set to `storagePath` is a full path to storage, make sure it starts with leading forward slash
