### ISSUE TITLE
After upgrading i got error message 

### ISSUE THREAD

**Issue by justinFather** [VeliovGroup/Meteor-Files#149]
``` Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.```

I use Schema and it contains userId field.

I think the problem is caused by below field definition.
```
  userId: {
    type: String,
    autoValue: function() {
      return Meteor.userId()
    }
  },
```

'userId' field should be set in my app by 'autoValue' becauseof security matters.

I guess new version of 'ostrio:files' use this schema in publish functions though I am not sure.

**Comment by dr-dimitru** [comment]
Here is [schema](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L621) (*which is not attached, and only given as default suggestion*) provided by package.

You should change your schema to:
```js
  userId: {
    type: String,
    autoValue: function() {
      if (Meteor.isServer) {
        return this.userId; // or Meteor.userId, I'm not sure
      } else {
         return Meteor.userId()
      }
    }
  },
```

**Comment by dr-dimitru** [comment]
But wait... `userId` is always set for logged-in users, just remove `autoValue`, and you will be fine.
Since `v1.6.*` there was major security updates to make sure `userId` is always set, and passed to security functions like `protected`, and `onBeforeUpload`

**Comment by justinFather** [comment]
I tried to remove autoValue as you said and i got new error.
```
I20160715-15:01:04.950(0)? Exception while invoking method '_FilesCollectionWrite_Images' Error: Prefix is required
I20160715-15:01:05.136(0)?     at Object.Future.wait (/home/vagrant/.meteor/packages/meteor-tool/.1.3.4_4.p9p1gg++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20160715-15:01:05.137(0)?     at packages/meteor/helpers.js:119:1
I20160715-15:01:05.138(0)?     at [object Object].FilesCollection._methods.(anonymous function) (/home/vagrant/meteor_project/ga/.meteor/local/build/programs/server/packages/ostrio_files.js:1245:81)
I20160715-15:01:05.139(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160715-15:01:05.140(0)?     at packages/ddp-server/livedata_server.js:711:19
I20160715-15:01:05.140(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160715-15:01:05.141(0)?     at packages/ddp-server/livedata_server.js:709:40
I20160715-15:01:05.142(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160715-15:01:05.143(0)?     at packages/ddp-server/livedata_server.js:707:46
I20160715-15:01:05.144(0)?     at tryCallTwo (/home/vagrant/.meteor/packages/promise/.0.7.3.kavkya++os+web.browser+web.cordova/npm/node_modules/promise/lib/core.js:45:5)
I20160715-15:01:05.146(0)?     - - - - -
I20160715-15:01:05.147(0)?     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:437:1)
I20160715-15:01:05.148(0)?     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:420:1)
I20160715-15:01:05.148(0)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
I20160715-15:01:05.149(0)?     at FilesCollection.exports.FilesCollection.FilesCollection._finishUpload (/home/vagrant/meteor_project/ga/.meteor/local/build/programs/server/packages/ostrio_files.js:1370:21)
I20160715-15:01:05.150(0)?     at FilesCollection.emit (events.js:106:17)
I20160715-15:01:05.152(0)?     at /home/vagrant/meteor_project/ga/.meteor/local/build/programs/server/packages/ostrio_files.js:1414:18
I20160715-15:01:05.152(0)?     at /home/vagrant/meteor_project/ga/.meteor/local/build/programs/server/packages/ostrio_files.js:58:12
I20160715-15:01:05.153(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160715-15:01:05.159(0)? Sanitized and reported to the client as: Prefix is required [400]
```

**Comment by dr-dimitru** [comment]
Could you post your full schema? `prefix` filed was deprecated

**Comment by justinFather** [comment]
```
export default defaultSchema = {
  size: {
    type: Number
  },
  name: {
    type: String
  },
  type: {
    type: String
  },
  path: {
    type: String
  },
  isVideo: {
    type: Boolean
  },
  isAudio: {
    type: Boolean
  },
  isImage: {
    type: Boolean
  },
  isText: {
    type: Boolean
  },
  _prefix: {
    type: String
  },
  extension: {
    type: String,
    optional: true
  },
  _storagePath: {
    type: String
  },
  _downloadRoute: {
    type: String
  },
  _collectionName: {
    type: String
  },
  public: {
    type: Boolean,
    optional: true
  },
  meta: {
    type: Object,
    blackbox: true,
    optional: true
  },
  userId: {
    type: String,
  },
  updatedAt: {
    type: Date,
    autoValue: function() {
      return new Date();
    }
  },
  versions: {
    type: Object,
    blackbox: true
  }
};
```

**Comment by dr-dimitru** [comment]
Your schema is outdated, see latest default schema in [docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)

**Comment by justinFather** [comment]
Thanks for updating.

I changed my schema with brand new one.

But another problem still exist now.

In 'onAfterUpload', I make a crop image for thumbnail image of uploaded file. and i call Images.update and try to delete previous image.

To delete previous image, i call a method. In the method i used this.userId. but in this case, this.userId is not set.

**Comment by justinFather** [comment]
It's possible to inject when i call the method with file.userId as a parameter.

but the method can be called by anyone so it can cause other security problem.

**Comment by dr-dimitru** [comment]
> To delete previous image, i call a method. In the method i used this.userId to check logined user. but in this case, this.userId is not set.

 1. You can pass uploaded file data into method and make sure this user can call it
 2. You can ged rid of you insecure method and use server-only function called from `onAfterUpload`. As I do in demo app, - [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L105) and [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L207), the [`createThumbnails` function itself](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/server/image-processing.coffee#L4)

**Comment by justinFather** [comment]
In 'onBeforeUpload', I found something that on client side 'file' object parameter doesn't have 'userId' field. My intention is that I want to prevent unlogined user can't do uploading.

To solve this matter, I add a little codes in 'onBeforeUpload' as below
```
  const userId = ( Meteor.isServer )? file.userId : Meteor.userId()
  if ( !userId ) {
    return 'login-first'
  }
```
And now It works perfect!

Thank you very much.
