### ISSUE TITLE
onAfterUpload removing. 

### ISSUE THREAD

**Issue by Tbutnyakov** [VeliovGroup/Meteor-Files#150]
Hey Dima!
Its looks like '_remove_' in '_onAfterUpload_'  dont work normally. 

Let's take a look in code:
In _Avatars_ collection. 
> onAfterUpload:function(fileRef){
Avatars.remove({'meta.ownerId':this.userId},function(err){
      if(err){
        console.log(err);
      } else {
        console.log('Got this!');
      }
    });
}

Server console tell me "Got this!". But files still alive in folder. 

But, when i use just _Avatars.remove();_  It work normally. 
Is it a package bug, or my mistake?

**Comment by dr-dimitru** [comment]
Could you log  this.userId, it should be undefined

onAfterUpload is asynchronous and from main Fiber, other words - we can't say which user is initiated this upload.

But, on the other hand (specially for such cases) you can use fileRef.userId.

**Comment by Tbutnyakov** [comment]
Yes!XD You are absolutely right!
I attentively read the documentationXD
I remember that I was surprised, "really is the user once the context is passed? Waaat!?"

Ty, Dima, for awesome package!

**Comment by dr-dimitru** [comment]
@Tbutnyakov glad you've solved it. Thank you for using this package 👍 

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Stat on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by Tbutnyakov** [comment]
@dr-dimitru of course!
