### ISSUE TITLE
GridFS example not working

### ISSUE THREAD

**Issue by martunta** [VeliovGroup/Meteor-Files#152]
when trying out GridFS example code, following line crashes the app
```
gfs = Grid(Meteor.users.rawDatabase(), mongo);
```
users object is not defined in empty Meteor app
I could make it work by applying workaround:
```
const Dummy = new Mongo.Collection('dummy');
...
gfs = Grid(Dummy.rawDatabase(), mongo);
```

feels silly, but not sure how else to approach this

**Comment by dr-dimitru** [comment]
Hi @epaminond ,
Could you please take a look on this one?

**Comment by epaminond** [comment]
@martunta, will initializing gfs this way work for you?

```js
import { MongoInternals } from 'meteor/mongo';

let gfs;
if (Meteor.isServer) {
  gfs = Grid(MongoInternals.defaultRemoteCollectionDriver().mongo.db, MongoInternals.NpmModule);
}
```

**Comment by martunta** [comment]
yes, it works. Thanks!

**Comment by dr-dimitru** [comment]
Thank you @epaminond 
I guess we can close this one now?
