### ISSUE TITLE
GridFS insert file

### ISSUE THREAD

**Issue by martunta** [VeliovGroup/Meteor-Files#153]
I tried to use GridFS integration example, but looks like onAfterUpload is not triggered by addFile. Is there any other way how to insert file in GridFS? 
I don't even want to insert it from filesystem, in fact I need to generate it in memory and insert directly into db, so it can be later downloaded by clients.

**Comment by dr-dimitru** [comment]
This was a bug. Fixed in #148 
use fourth argument `proceedAfterUpload`, see in docs: https://github.com/VeliovGroup/Meteor-Files/blob/caf229ba817c30bc26a693e432a77bc084e810cc/docs/addFile.md

**Comment by martunta** [comment]
thanks, understood.

**Comment by dr-dimitru** [comment]
Please check if it is working on your end (*this is new feature, released yesterday*).
Let me know then.

**Comment by martunta** [comment]
It is working, I updated to 1.6.5 and it started working

**Comment by dr-dimitru** [comment]
Great. Closing this one
