### ISSUE TITLE
"This" context in each-block in template

### ISSUE THREAD

**Issue by Tbutnyakov** [VeliovGroup/Meteor-Files#155]
Hey, Dima!

I have a question about "this" context in template helpers and events. 
For example; 

> Template.add_post.helpers({
        uploads: function () {
          return Images.find({_id: {"$in": imagesIds.array()}});
        }
    });

Ok, i got an array of objects, and now i can each it on a template. 
I use method i found in doc. It is seems to me strange, but ok) 

```html
{{#each file in uploads.each}}
  <div class="image_item">
    <img src="{{file.link}}" class="img-responsive" />
    <a href='#' class="deleteImage"><i class="fa fa-times" aria-hidden="true"></i></a>
  </div>
{{/each}}
```

And now, when user click on 'deleteImage' link, we go to in event-block. 

> "click .deleteImage": function (e,t) {
            console.log(this);
         }

And as expected, we have empty object, without context. 
How can we eaching documents with context?

**Comment by dr-dimitru** [comment]
To get `file` as context you need to bind it:
```html
{{#each uploads.each}}
  <div class="image_item">
    <img src="{{this.link}}" class="img-responsive" />
    <a href='#' class="deleteImage">
      <i class="fa fa-times" aria-hidden="true"></i>
    </a>
  </div>
{{/each}}
```

Then in the event:
```js
"click .deleteImage": function (e,t) {
   console.log(this);
   return;
}
```

**Comment by Tbutnyakov** [comment]
Yep, i got this already:)
Thank  you, @dr-dimitru
