### ISSUE TITLE
Can this work with non-js DDP client?

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#160]
Hi,
This seems great and exactly what I want, but the question is, can this FilesCollection work with a non-js DDP client? Specifically, we want to use it as a tool to transfer files between browser based client and another client runs with DDP protocol, we used https://github.com/hharnisc/python-meteor . I am wondering can this work normally as the regular collection in meteor or not?

Thanks in advance.

**Comment by dr-dimitru** [comment]
Hi @oeway ,

Unfortunately nope.
This lib relies on backend code where chunks is received. And currently it's only has node.js implementation

**Comment by oeway** [comment]
Just make sure that I understand, in my case, I still have a node.js server, can the python DDP client interact(upload and donwload) with node.js server which receives the chunks?

**Comment by dr-dimitru** [comment]
I guess... never faced this solution.
As long as you have Server part of this package - should work.
There is a code responsible for writing incoming chunks to FS. BTW if DDP won't work for you try upload via HTTP

**Comment by oeway** [comment]
OK, thanks, I will try.

**Comment by oeway** [comment]
Hi @dr-dimitru
Just another quick question, do you think it's possible or feasible to transfer data from one client to another client. You have download and upload examples, but what if I want to implement something like, one client ask for a file from another client, can the server setup this transmission with your package?

**Comment by dr-dimitru** [comment]
Hi @oeway ,
Good question. But no, first file must be transferred to server when downloaded by another user.
Actually p2p is complex solutions, that's why there is nothing much but Torrent, Magnet and few other solutions.

But this is good idea for another package...

**Comment by oeway** [comment]
Thanks for your quick response.
There are webRTC as well, but here I just want to implement something simple, I don't mind there is a server in the middle to transfer the files, I mean first the file is transferred to the server, then other users downloaded. But my question is, if I want to make this kind of streaming happened at the same time, initialed by one client and the uploading and downloading happening at the same time. In this case, can your package help? I am trying it, but perhaps, you can give me a quicker answer.

Thanks.

**Comment by dr-dimitru** [comment]
Unfortunately there is no easy way to concatenate binary data in Browser's memory, the let user download it

**Comment by oeway** [comment]
@dr-dimitru 

Thanks for the reply again, so now I am using your library now, tried some demo and it's great.

And also I am now trying to play with a ddp client in python, I checked your code, there are three meteor methods:
```
      _Abort: "_FilesCollectionAbort_" + this.collectionName,
      _Write: "_FilesCollectionWrite_" + this.collectionName,
      _Start: "_FilesCollectionStart_" + this.collectionName,
      _Remove: "_FilesCollectionRemove_" + this.collectionName
```
in order to write a streaming upload function with ddp in python, I should do the following:
(1). call _Start function with the following options:
```
opts = {
        file: this.fileData,
        fileId: this.fileId,
        chunkSize: this.config.chunkSize,
        fileLength: this.fileLength
      };
```

(2). call _Write to send all chunks with:
```
opts = {
  fileId: this.fileId,
  binData: evt.data.bin,
  chunkId: evt.data.chunkId
};
```

(3). send EOF with _Write:
```
opts = {
   eof: true,
   fileId: this.fileId
};
```

Is that correct? If I want to use 'http' POST method to upload, what should I do? do you have an example? Can http transport handle streaming or large files such as 2GB files? 

Compare ddp with http, is there any advantage? with ddp, are you sending binary data(ejson) directly or encoded as base64? 

 Thanks.

**Comment by dr-dimitru** [comment]
1. Yes, described steps is correct
 2. As you see [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1609) and [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L711) [upload middleware](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L710) listens for `POST` request
 3. About difference between `http` and `ddp` you can read [here](https://themeteorchef.com/blog/interview-files-for-meteor/)
 4. Same data as base64 sent over both `ddp` and `http` transports. Sending data as formData in future plans

**Comment by oeway** [comment]
Hi,
Thanks, I have just made the ddp uploading with python-meteor work, in case someone else need it, here is the gist:
https://gist.github.com/oeway/f4b5b96abe162fb06439021d708b0ca7.js

But for the http post method, I haven't make it work. I replaced the meteor.call with requests.post like this:
``` python
opts = {
      "eof": False,
      "fileId": self.fileId,
      "binData": encoded_string,
      "chunkId": i+1,
 }
requests.post('http://localhost:3000/cdn/storage/Images/__upload', data= {'data':opts})
```
and then
``` python
opts = {
     "eof": True,
     "fileId": self.fileId,
 }
requests.post('http://localhost:3000/cdn/storage/Images/__upload', data= {'data':opts})
```
But I got some error instead from [this line](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L715):
```
W20160801-01:14:32.530(2)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: [SyntaxError: Unexpected token d]
```
Any idea?

**Comment by dr-dimitru** [comment]
How do you create chunks?

**Comment by dr-dimitru** [comment]
Okay, never mind previous question.
This mens something wrong with JSON sent over the wire.
Could you check what you're actually sending?

**Comment by dr-dimitru** [comment]
@oeway About the py-snippet.
what about if I'll create official fork for python, and let you push/merge/manage it?

**Comment by oeway** [comment]
@dr-dimitru  Sure, I think can do that.

About my http post problem, so you are saying that I can't use the same json as I do with ddp? What should I send?

**Comment by dr-dimitru** [comment]
JSON should be same, show me headers and body to your POST request. something just wrong...

**Comment by oeway** [comment]
So this is what I get when I do

``` text
HEADER:

127.0.0.1 - - [01/Aug/2016 16:38:06] "POST /cdn/storage/Images/__upload HTTP/1.1" 200 -
Host: localhost:3000
Content-Length: 81
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.9.1
Connection: keep-alive
Content-Type: application/json

POST_BODY:

{"data": {"chunkId": 1, "binData": "fake base64", "eof": false, "fileId": "124"}}
```

``` python
opts = { "eof":False, "fileId":'124', "binData":'fake base64', "chunkId":1}
requests.post('http://localhost:3000/cdn/storage/Images/__upload', json={'data':opts})
```
See if you have any idea.

**Comment by dr-dimitru** [comment]
no need for `data` key, just send the `opts` object

**Comment by dr-dimitru** [comment]
Also you need to pass `meta` object through [`fixJSONStringify`](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L397), like [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1577)

**Comment by oeway** [comment]
Great, it works after remove the data key.

So now I am trying to remove the hard coded link "http://localhost:3100/cdn/storage/Images/__upload", is there a way to get this link, base url + downloadRoute + collection name? The ideal case is after I Meteor.call( '_FilesCollectionStart_Images'), I should get the upload url as a call back result.

Thanks.

**Comment by dr-dimitru** [comment]
It requires changes in a package, could you create separate ticket for this, please?

**Comment by dr-dimitru** [comment]
@oeway [get invited](https://github.com/VeliovGroup/meteor-python-files/invitations) to [meteor-pyfiles](https://github.com/VeliovGroup/meteor-python-files)

**Comment by dr-dimitru** [comment]
@oeway 
 1. I guess we can close this one?
 2. Any ideas around meteor-pyfiles package?

**Comment by oeway** [comment]
Sure, we can close now, thanks very much for your help.

I am sorry that I was on vacation, I will update the meteor-pyfiles package with your updated meteor method.

**Comment by dr-dimitru** [comment]
@oeway no worries, let me know if you will have any further questions
