### ISSUE TITLE
After Upgrading Meteor 1.4 with ostrio:files 1.6.6

### ISSUE THREAD

**Issue by justinFather** [VeliovGroup/Meteor-Files#163]
I have a prouction vps with Meteor 1.3.4.4 and ostrio:files 1.6.5

This afternoon i tried to upgrade Meteor 1.4, which is brand new version. Your package ostrio:files was upgraded automatically as 1.6.6 while upgrading Meteor 1.4

After upgrade I got a error as below

```
TypeError: FilesCollection is not a function
    at meteorInstall.imports.api.Images.lists.js (imports/api/Images/lists.js:38:14)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at Module.Mp.import (/MY_HOME_DIR/product/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.imports.api.Lib.accountsLib.js (/MY_HOME_DIR/product/programs/server/app/app.js:15098:217)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at Module.Mp.import (/MY_HOME_DIR/mapp/product/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.imports.api.Lib.index.js (/MY_HOME_DIR/product/programs/server/app/app.js:15166:287)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
/MY_HOME_DIR/product/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^
```

Now I degrade Meteor 1.3.4.4 and set version constrain ostrio:files '1.6.5'. Then my production vps is now working correctly.

**Comment by dr-dimitru** [comment]
What previous version of `ostrio:files` was installed in your app? v1.6.6 has no codebase difference with 1.6.5, only dependencies update

Could you post content of `lists.js`, where is `FilesCollection` called?
If you use ES6 you need to import `FilesCollection`:
```jsx
import { FilesCollection } from 'meteor/ostrio:files';
```

**Comment by justinFather** [comment]
import { Meteor } from 'meteor/meteor'

import defaultSchema from './Schema.js'

// console.log( _.extend( defaultSchema, Extension ))
function checkFile( file ) {
  const userId = ( Meteor.isServer )? file.userId : Meteor.userId()
  if ( !userId ) {
    return 'not-authorized'
  }
  // Allow upload files under ..., and only in png/jpg/jpeg formats
  const { maxNum, maxSize } = Meteor.settings.public.uploadConf
  if ( !( file.size <= maxSize && /png|jpg|jpeg/i.test(file.extension) ) ) {
    return 'Please upload image, with size equal or less than ' + maxSize + 'bytes';
  }

  // meta.kind : logo, avatar, businesss
  if ( file.meta && file.meta.kind === 'logo' ) {
    // Meteor.call( 'images.mine.logo.delete' )
  } else if( file.meta && file.meta.kind === 'avatar' ) {
    //Meteor.call( 'images.mine.avatar.delete' )
  } else if ( file.meta && file.meta.kind === 'business' ) {
    const count = Images.collection.find({ userId: userId, "meta.kind" : "business" }).count()
    // console.log( count)
    if ( count >= maxNum ) {
      return 'maxNumImg'
    }
  } else {
    console.log( file )
    return 'Invalid kind of image'
  }

  return true;
}

const { downloadRoute, storagePath } = Meteor.settings.public.imageFileCollection

export const Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    return checkFile( file )
  },
  schema: defaultSchema,
  onAfterUpload: function( fileRef ) {
    const { width, height, rate } = Meteor.settings.public.uploadConf.thumbOpt
    const lidx = fileRef.path.lastIndexOf('.')
    const cropName = fileRef.path.substring(0, lidx) + '_th' + fileRef.path.substring(lidx)
    Meteor.wrapAsync( Imagemagick.crop({
      srcPath: fileRef.path,
      dstPath: cropName,
      width: width,
      height: height,
      quality: rate, // 0.8,
      gravity: "Center"
    }))
    const upd = {
      $set: {
        "versions.thumbnail" : {
          path: cropName,
          type: "image/jpeg",
          extension: "jpg"
        } 
      }
    }
    const ret = Images.update( fileRef._id, upd )   
    if( fileRef.meta ) {
      if( fileRef.meta.kind === "avatar" ) {
        Meteor.users.update({ _id: fileRef.userId}, {$set:{"profile.avatarImage":fileRef._id}})
        Images.remove({ userId: fileRef.userId, "meta.kind": "avatar", _id :{$ne: fileRef._id}})
      } else if ( fileRef.meta.kind === "logo" ) {
        Images.remove({ userId: fileRef.userId, "meta.kind": "logo", _id:{$ne: fileRef._id}})
      }
    }
    return ret
  },
  public: true,
  downloadRoute: downloadRoute,
  storagePath: storagePath
})

Images.collection.attachSchema( Images.schema )

**Comment by Torsten85** [comment]
@justinFather @dr-dimitru I had the same issue today. Turns out the problem is the coffeescript compiler!

Try this:
`meteor add coffeescript@=1.1.4`

**Comment by justinFather** [comment]
Thank you @Torsten85
I will try it within today and leave the result here.

**Comment by dr-dimitru** [comment]
Reproduced on METEOR@1.4
Looking for solution

**Comment by dr-dimitru** [comment]
__HOT FIX__:
Use `Meteor.Files` instead of `FilesCollection`.
`Meteor.Files` was left for compatibility a long time ago.
Currently somewhy `api.export('FilesCollection');` not exporting `FilesCollection`

**Comment by justinFather** [comment]
@dr-dimitru, take a time. Now my production vps is working well on Meteor 1.3.4.4 + ostrio:files 1.6.5. I will just wait for ostrio:files new version fits to Meteor 1.4.

Thank you.

**Comment by dr-dimitru** [comment]
@justinFather fixed, please check on your end

**Comment by justinFather** [comment]
I upgraded my production vps to Meteor 1.4 with ostrio:ffiles 1.6.7 successfully.

My vps is working fine now!

Thank you

**Comment by dr-dimitru** [comment]
Great news @justinFather 
Thank you for reporting about this issue
