### ISSUE TITLE
What template language do you use?

### ISSUE THREAD

**Issue by sschuchlenz** [VeliovGroup/Meteor-Files#17]
Hi,

can you tell me what template language / system you use in the examples in the README? Looks a lot like HAML and I'd love to try that out ;)

Thanks in advance

**Comment by dr-dimitru** [comment]
Hello @sschuchlenz,
It is `JADE`.
BTW my front-end stack is: `jade`, `sass` and `coffeescript`.

**Comment by sschuchlenz** [comment]
Great, thanks - I'm using SASS and Coffee at the moment but - coming from the Ruby on Rails world - I dearly missed something like HAML ;)
