### ISSUE TITLE
Uncaught ReferenceError: Accounts is not defined

### ISSUE THREAD

**Issue by Torsten85** [VeliovGroup/Meteor-Files#172]
Hi there,
I'm using "ostrio:files" with accounts-base and after upgrading to 1.4 I'm getting "Accounts is not defined" here:
https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L507

My whole project code is inside the /imports folder, maybe thats why the package has no direct access to the formerly globals variable?

This could be easily fixed by adding:
`const Accounts = Package['accounts-base'].Accounts;`
on line 497.

**Comment by dr-dimitru** [comment]
Hi @Torsten85 ,

Fixed on `dev` branch, could you please check on your end?

**Comment by dr-dimitru** [comment]
Although this fix is merged to `prod` and published, please check it on your end.

**Comment by Torsten85** [comment]
@dr-dimitru Sorry for the late response. That fixed my problem. Thanks for your great support!

**Comment by dr-dimitru** [comment]
@Torsten85 great, thank you for response and contribution, appreciated.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Stat on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
