### ISSUE TITLE
[Suggestion for docs] Available regions for S3. 

### ISSUE THREAD

**Issue by TSDrrodriguez** [VeliovGroup/Meteor-Files#174]
Hi,

this has driven me crazy for hours. In your current implementation of S3 file upload, you are using Knox.

From Knox docs:

https://github.com/Automattic/knox#region

I think you should put this as a warning in the given example, as I've almost gone crazy. Knox.putFile was returning no error, but when fetched the res object, status code was 400 (bad request). After some investigations I came to the knox documentations. I was using eu-central-1 and file can't be uploaded to that region wit hthe current knox implementation.

**Comment by dr-dimitru** [comment]
@TSDrrodriguez 
Thank you for reporting about this. I'm really sorry for your inconvenience.

And thank you for using this package! 👍 

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Stat on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
