### ISSUE TITLE
Support binary upload

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#176]
Hi,
Would be great to directly upload without encode it into base64, it can save the bandwidth and avoid the encoding and decoding steps, perhaps https://stuk.github.io/jszip/  can be added as an option to reduce the file size. Thanks.

**Comment by dr-dimitru** [comment]
Working on it, requires a lot of breaking changes, will be published as v1.7.0
For zip you can use `.pipe()`, docs: https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#piping

**Comment by dr-dimitru** [comment]
Hi @oeway ,

I've tried to do my best to implement pure binary uploads and failed.

1. WebSockets supports binary data transfers in it's nature, but version of sock.js and DDP does not. More over if I'm trying to send uint arrays the DDP encode / parse takes a lot of resources
2. Binary uploads via HTTP is working, but it's far away form what I can call stable, or production ready. I guess Meteor's `WebApp.connectHandlers` has some magic inside, 80% of transferred data was corrupted, encoding to binary strings not helped too

But somehow minor changes made to the package during this investigation made uploads at least 1.5x faster.

Thank you for ideas, I'll wait for update of sock.js and try again.

Btw have you tried the `.pipe()` method for zipping?

**Comment by oeway** [comment]
@dr-dimitru Thanks very much for your work. let's wait then, at least we can make upload work.

I haven't try pipe(), will update your when I tried, thanks.

**Comment by oeway** [comment]
@dr-dimitru do you have any idea on that why http is much faster than ddp? it's like 4 times faster. 

https://github.com/VeliovGroup/meteor-python-files

**Comment by dr-dimitru** [comment]
Yes, I wrote about it [here](https://github.com/VeliovGroup/Meteor-Files/wiki/About-Upload-Transports), and talked about it [here](https://themeteorchef.com/blog/interview-files-for-meteor/)

### TL;TR;
All non-pure socket solutions has huge overhead in parsing/structuring/unifying [out|in]coming data

Currently I'm playing with pure and native RTC/DC (WebRTC and UDP) solution. It is so blazing fast, what we need to find a new way to write files to FS. Now FS is bottleneck.
