### ISSUE TITLE
Return upload url for http post after calling _FilesCollectionStart_

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#177]
As mentioned in #160, would be better if the upload url can be returned after calling '_FilesCollectionStart_Images' method, so http post method can use it directly.
For example, return an url like this: "http://localhost:3100/cdn/storage/Images/__upload" which can be sued by http post.

**Comment by dr-dimitru** [comment]
What if there is will be separate method like `FilesCollection#http.url()`, which will return upload URL?

**Comment by oeway** [comment]
I think it will still work, but less straight forward, because I would need another layer of callback (with Meteor.call in the callback of _FilesCollectionStart_), would be good if each meteor call can return some object about the file, for example, something about the document created in the  __pre_Images collection.

**Comment by dr-dimitru** [comment]
It will be JS method, not Meteor's.
like: 
```js
var url = FilesCollection#http.url();
requests.post(url, json={'data':opts});
```

About returning additional data - which data you need? Will it be secure?

**Comment by oeway** [comment]
But in python, I can't access JS method at all. What I can do with python-meteor is to subscribe collections, find/find_one with selector, or call meteor methods, nothing else.

**Comment by dr-dimitru** [comment]
@oeway implemented, please check on your end

 - See commit: https://github.com/VeliovGroup/Meteor-Files/commit/59d429778dbcb6390cc8123c2b2be9d60cab2a1c

 - Passing second argument `true` to the Meteor’s method
`_FilesCollectionStart_{CollectionName}` will return object:
```js
{
   uploadRoute: “Upload Path Relative to the domain”,
   file: fileRef
}
```

**Comment by oeway** [comment]
@dr-dimitru great, thanks, I will check it out.
