### ISSUE TITLE
How can I create a thumbnail (using gridFS) & return just them

### ISSUE THREAD

**Issue by jbg77** [VeliovGroup/Meteor-Files#180]
Hello, I'm using the code on [ wiki GridFS](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration).
How can I using this code : [Image processing](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/server/image-processing.coffee) to create a thumbnail ?

I try to do this with cfs:graphicsmagick
```
createThumbnails = function(collection, fileRef){
  const cropName = fileRef.path + "__thumbnail__.png"
  var image = gm(fileRef.path);
  writeStream = fs.createWriteStream(cropName);
  image.resize('25','25').stream().pipe(writeStream);
  const upd = {
       $set: {
        "versions.thumbnail" : {
           path: cropName,
           type: "image/png",
           extension: "png"
          } 
     } ;

  console.log("thumb generated");
  return collection.update( fileRef._id, upd );
}
```

**Comment by dr-dimitru** [comment]
1. Create a thumb: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/server/image-processing.coffee#L113
 2. Use callback to update the record: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/server/image-processing.coffee#L65

**Comment by jbg77** [comment]
I tried this: 

```
const cropName = fileRef.path + "__thumbnail__";
console.log(cropName);
var image = gm(fileRef.path);

var Future = Npm.require('fibers/future');
var fut = new Future();

var updateAndSave = function(){
    return bound(function(error){
      if (error)
      console.error( "[_app.createThumbnails] [_.each sizes] [img.resize]"+error)
      const upd = {
        $set: {
          "versions.thumbnail" : {
            path: cropName,
            type: fileRef.type,
            extension: fileRef.extension
           } 
          }
        };
        console.log("thumb generated");
        fut.return(ImagesProfile.update( fileRef._id, upd ));
    });
};
image.resize(250, 250).write(fileRef.path+fileRef.extension, updateAndSave);
    
return fut.wait();
```
But the filesize is equal to 0ko

**Comment by dr-dimitru** [comment]
Don't you overwrite original file here?:
```js
image.resize(250, 250).write(fileRef.path+fileRef.extension, updateAndSave);
// Should be changed to:
image.resize(250, 250).write(cropName + fileRef.extension, updateAndSave);
```

And:

```js
var updateAndSave = function(){
    return bound(function(error){ ... });
}

// Should be changed to:

var updateAndSave = function(error){
    bound(function(){ ... });
}
```

**Comment by jbg77** [comment]
Thank you, I know the problem now: 
```
{ [Error: Command failed: invalid parameter - "-resize"
W20160806-22:43:33.517(2)? (STDERR) ] code: 4, signal: null }
```

**Comment by dr-dimitru** [comment]
1. You shouldn't ever show original image, as user may upload something insanely big
 2. I've never used NPM wrapper for `gm`, but you should get into the docs to find out, sorry can't help you on this

**Comment by jbg77** [comment]
Thank you for your help that working ! I don't know why but I thought I'd installed imagemagick : 
`var gm = require('gm').subClass({imageMagick: true});`

But I use gm..

A last question, can I return only the thumb as : 
```
return ImagesProfile.find({userId: this.userId}, {fields: {
      'versions.thumbnail':1,
      _id: 1,
      name: 1,
      size: 1,
      meta: 1,
      type: 1,
      isPDF: 1,
      isText: 1,
      isJSON: 1,
      isVideo: 1,
      isAudio: 1,
      isImage: 1,
      userId: 1,
      extension: 1,
      _collectionName: 1,
      _downloadRoute: 1,
    }}).cursor;
```
With this code the thumbnail doesn't appear but the original yes

**Comment by dr-dimitru** [comment]
Should work, or you can change to more specific fields (*not whole object*), like here: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L289

**Comment by jbg77** [comment]
In fact it's alway returning all versions even if versions is not in the fields
Meteor.publish('files.imagesProfile.thumb', function () {
    return ImagesProfile.find({userId: this.userId}, {fields: {
      'version.thumbnail.type': 1,
      _id: 1,
      name: 1,
      size: 1,
      meta: 1,
      type: 1,
      isPDF: 1,
      isText: 1,
      isJSON: 1,
      isVideo: 1,
      isAudio: 1,
      isImage: 1,
      userId: 1,
      extension: 1,
      _collectionName: 1,
      _downloadRoute: 1,
      selected: 1
    }}).cursor;
  });
Example of mongodb object:
`{ "_id" : "w8FzRmFhHBPCWxrCG", "name" : "Capture.PNG", "extension" : "PNG", "path" : "assets\\app\\uploads\\imagesProfile\\w8FzRmFhHBPCWxrCG.PNG", "meta" : {  }, "type" : "image/png", "size" : 1736, "versions" : { "original" : { "path" : "assets\\app\\uploads\\imagesProfile\\w8FzRmFhHBPCWxrCG.PNG", "size" : 1736, "type" : "image/png", "extension" : "PNG", "meta" : { "gridFsFileId" : "57a77b53ca0f3df81ebe0c87" } }, "thumbnail" : { "path" : "assets\\app\\uploads\\imagesProfile\\w8FzRmFhHBPCWxrCG.PNG__thumbnail__.PNG", "type" : "image/png", "extension" : "PNG", "meta" : { "gridFsFileId" : "57a77b53ca0f3df81ebe0c88" } } }, "isVideo" : false, "isAudio" : false, "isImage" : true, "isText" : false, "isJSON" : false, "isPDF" : false, "_storagePath" : "assets\\app\\uploads\\imagesProfile", "_downloadRoute" : "/cdn/storage", "_collectionName" : "imagesProfile", "userId" : "RSSojJgTj92zcwmEL", "public" : false, "selected" : true }`

**Comment by dr-dimitru** [comment]
Force to not return `versions` object:
```js
{versions: 0}
```

**Comment by jbg77** [comment]
That doen't work too, I'm using meteor 1.3.5.1 and mongo 2.6, it's very strange:
server/publish.js
`Meteor.publish('files.imagesProfile.thumb', function () {
    return ImagesProfile.find({userId: this.userId},  {versions: 0}).cursor;
});

Meteor.publish('files.imagesProfile.id', function (_id) {
    return ImagesProfile.find({userId: _id, selected: true}, {fields: {'versions.thumbnail':1}}).cursor;
});`

lib.uploadGridFS.js
```
import { Meteor } from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';
import Grid from 'gridfs-stream';
import { MongoInternals } from 'meteor/mongo';
import fs from 'fs';

let gfs;
if (Meteor.isServer) {
  gfs = Grid(
    MongoInternals.defaultRemoteCollectionDriver().mongo.db,
    MongoInternals.NpmModule
  );
}

ImagesProfile = new FilesCollection({
  collectionName: 'imagesProfile',
  allowClientCode: false,
  debug: Meteor.isServer && process.env.NODE_ENV === 'development',
  onBeforeUpload(file) {
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) return true;
    return 'Please upload image, with size equal or less than 10MB';
  },
  onAfterUpload(image) {
    // Move file to GridFS

    
    createThumbnails(this.collection, image);

    image = this.collection.findOne({_id: image._id});
    Object.keys(image.versions).forEach(versionName => {
      console.log(versionName);
      const metadata = { versionName, imageId: image._id, storedAt: new Date()}; // Optional
      const writeStream = gfs.createWriteStream({ filename: image.name, metadata });

      fs.createReadStream(image.versions[versionName].path).pipe(writeStream);

      writeStream.on('close', Meteor.bindEnvironment(file => {
        const property = `versions.${versionName}.meta.gridFsFileId`;

        // If we store the ObjectID itself, Meteor (EJSON?) seems to convert it to a
        // LocalCollection.ObjectID, which GFS doesn't understand.

        this.collection.update(image._id, { $set: { [property]: file._id.toString()} });
        this.unlink(this.collection.findOne(image._id), versionName); // Unlink files from FS
      }));
    });
  },
  interceptDownload(http, image, versionName) {
    // Serve file from GridFS
    const _id = (image.versions[versionName].meta || {}).gridFsFileId;
    if (_id) {
      const readStream = gfs.createReadStream({ _id });
      readStream.on('error', err => { throw err; });
      readStream.pipe(http.response);
    }
    return Boolean(_id); // Serve file from either GridFS or FS if it wasn't uploaded yet
  },
  onAfterRemove(images) {
    // Remove corresponding file from GridFS
    images.forEach(image => {
      Object.keys(image.versions).forEach(versionName => {
        const _id = (image.versions[versionName].meta || {}).gridFsFileId;
        if (_id) gfs.remove({ _id }, err => { if (err) throw err; });
      });
    });
  }
});

if (Meteor.isServer) {
  ImagesProfile.denyClient();
}

```
server/createThumbnails.js
```
var bound;

bound = Meteor.bindEnvironment(function(callback) {
  return callback();
});

var gm = require('gm')

createThumbnails = function(collection, fileRef) {
  const cropName = fileRef.path + "__thumbnail__." + fileRef.extension;
  console.log(fileRef.extension);
  var image = gm(fileRef.path);

  var Future = Npm.require('fibers/future');
	var fut = new Future();
  var updateAndSave = function(error){
    return bound(function(){
      if (error)
      console.error( error);
      const upd = {
        $set: {
          "versions.thumbnail" : {
            path: cropName,
            type: fileRef.type,
            extension: fileRef.extension
           } 
          }
        };
        console.log("thumb generated");
        fut.return(collection.update( fileRef._id, upd ));
    });
  };
  image.resize(250, 250).write(cropName, updateAndSave);
    
  return fut.wait();
};
```
client/templates/userProfile/userProfile.html
```
<img src="{{imageProfile.link 'thumbnail'}}" alt="{{imageProfile}}" class='img-circle' style='width: 100px;'/>
{{#with currentUpload}}
  Uploading <b>{{file.name}}</b>: 
  <span id="progress">{{progress.get}}%</span>
{{else}}
  <input id="fileInput" type="file" />
{{/with}}
{{#each imageProfileList.each}}
  {{selected}}
  <img  alt="{{name}}" src="{{link}}" class='img-circle thumb' style='width: 100px;'/>
{{/each}}
```
client/templates/userProfile/userProfile.js
```
Template.userProfile.onCreated(function(){
    this.currentUpload = new ReactiveVar(false);
    this.subscribe('files.imagesProfile.thumb');
});

Template.userProfile.helpers({
    currentUpload: function () {
    return Template.instance().currentUpload.get();
  },
  imageProfile: function () {
    return ImagesProfile.findOne({userId: Meteor.userId(), selected:true});
  },
  imageProfileList: function () {
    return ImagesProfile.find({userId: Meteor.userId()});
  }
});

Template.userProfile.events({ 
    'change #fileInput': function (e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
      // We upload only one file, in case 
      // multiple files were selected
      var upload = ImagesProfile.insert({
        file: e.currentTarget.files[0],
        streams: 'dynamic',
        chunkSize: 'dynamic'
      }, false);

      upload.on('start', function () {
        template.currentUpload.set(this);
      });

      upload.on('end', function (error, fileObj) {
        if (error) {
          alert('Error during upload: ' + error);
        } else {
          alert('File "' + fileObj.name + '" successfully uploaded');
        }
        template.currentUpload.set(false);
      });

      upload.start();
    }
  },
    'click .thumb': function(e, template){
        var dataObject = {
          _id: this._id
        };

        Meteor.call('updateProfileImage', dataObject, function(error, success) { 
          if (error) { 
            console.log('error', error); 
          } 
          if (success) { 
             
          } 
        });

    }
});
```
server/methods/user/mds_image.js
```
Meteor.methods({ 
    updateProfileImage: function(sendData) { 
        console.log(sendData._id);

        var finded = 1;
         
        finded = ImagesProfile.find({userId: Meteor.userId(), selected: true}).count();
        for(var i=0;i<finded;i++)
            ImagesProfile.update({userId: Meteor.userId(), selected: true}, { $set:{selected: false} });
         
         ImagesProfile.update({_id: sendData._id}, { $set:{selected: true} });
    } 
});
```

**Comment by dr-dimitru** [comment]
> That doen't work too, I'm using meteor 1.3.5.1 and mongo 2.6

I'm highly recommend to update to meteor @1.4.*

As *FilesCollection* [requires Meteor@1.4](https://github.com/VeliovGroup/Meteor-Files/blob/master/package.js#L10)

**Comment by dr-dimitru** [comment]
1. In your collection, `thumbnail.path` has wrong naming
 2. In callback of `writeStream.on('close', /*...*/)` you're using function context, please check what it really have `this.collection` (*looks wrong to me*). I know you're using "*double arrow*", but just tech to make sure, [imho](https://rainsoft.io/when-not-to-use-arrow-functions-in-javascript/)
 3. And as I said previously, - please update.

**Comment by jbg77** [comment]
I'm sorry but it doesn't work:

1. I updated meteor to  1.4.1
2. I changed the tumbnail path to:
`const cropName = (fileRef.path).substr(0,fileRef.path.lastIndexOf(".")) + "__thumbnail__." + fileRef.extension;`
Anyway the file is deleted when send to gridfs, so I think it's not the problem.
3. And I try to use the syntax function(versionName) instead of versionName () =>, but it's the code of wiki, I just add:  `image=this.collection.findOne({_id: image._id});` because I need to update image as it was updated on create thumbnail.

**Comment by dr-dimitru** [comment]
I lost the point of this thread... What is not working *related to Meteor-Files package*?

**Comment by jbg77** [comment]
Sorry the subject is solve, i know how to create thumbnail.
What I want to do is just return the thumbnails, all versions are alway returned even if I write {fields:{versions: 0}}

**Comment by dr-dimitru** [comment]
Check your code passed into `.find()` in mongo console (`meteor mongo`), to make sure you have no typo or other issues

**Comment by jbg77** [comment]
Already did many times :/ 
`{ "_id" : "uxXYMgWPuYKdgY7FE", "name" : "banderole.png", "extension" : "png", "path" : "assets\\app\\uploads\\imagesProfile\\uxXYMgWPuYKdgY7FE.png", "meta" : {  }, "type" : "image/png", "size" : 786237, "versions" : { "original" : { "path" : "assets\\app\\uploads\\imagesProfile\\uxXYMgWPuYKdgY7FE.png", "size" : 786237, "type" : "image/png", "extension" : "png", "meta" : { "gridFsFileId" : "57a89cf36e196a1620331943" } }, "thumbnail" : { "path" : "assets\\app\\uploads\\imagesProfile\\uxXYMgWPuYKdgY7FE__thumbnail__.png", "type" : "image/png", "extension" : "png", "meta" : { "gridFsFileId" : "57a89cf36e196a1620331944" } } }, "isVideo" : false, "isAudio" : false, "isImage" : true, "isText" : false, "isJSON" : false, "isPDF" : false, "_storagePath" : "assets\\app\\uploads\\imagesProfile", "_downloadRoute" : "/cdn/storage", "_collectionName" : "imagesProfile", "userId" : "EGSAaznAsTmQudiBo", "public" : false, "selected" : true }`

**Comment by dr-dimitru** [comment]
1. So, it works in logo console?
 2. What if you will use `ImagesProfile.collection.find()`, instead of `ImagesProfile.find().cursor`

**Comment by jbg77** [comment]
1. Yes with this command : {version : 0} instead {field: {version: 0 }, I use mongodb 3.2
If i use fields option I have this error: 
```
Error: error: {
        "waitedMS" : NumberLong(0),
        "ok" : 0,
        "errmsg" : "Unsupported projection option: fields: { versions.thumbnail: 0.0 }",
        "code" : 2
}
```
2. Same unfortunately

**Comment by dr-dimitru** [comment]
its __`fields`__ not `field`!

**Comment by dr-dimitru** [comment]
https://docs.meteor.com/api/collections.html#fieldspecifiers

**Comment by jbg77** [comment]
I write field**s** it's a typo error on my message sorry

**Comment by dr-dimitru** [comment]
Okay, try to publish only one field, and deny all others, to make sure there is no typo in filed names

**Comment by dr-dimitru** [comment]
From the docs (*link above*): 

> However, such field specifiers can not be used with observeChanges, observe, cursors returned from a publish function, or cursors used in {{#each}} in a template. They may be used with fetch, findOne, forEach, and map

**Comment by dr-dimitru** [comment]
Anyways I think you should [make sure it's working in mongo console](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#return-specified-fields-only) first. Then in Meteor

**Comment by jbg77** [comment]
db.imagesProfile.findOne({}, {'name': true});
{ "_id" : "6RytNWxLGKvQJ9omF", "name" : "background.png" }
That work well in mongoshell 
And in meteor, I have just the name displayed using : 
`return ImagesProfile.find({},  {fields:{'name':1, 'userId':1} }).cursor;`
This : 
` return ImagesProfile.find({},  {fields:{'name':1, 'userId':1, 'selected':1, '_downloadRoute':1, 'versions.thumbnail.extension':1, 'versions.thumbnail.type':1, 'versions.thumbnail.path':1, '_collectionName':1}}).cursor;`
returning all versions 
And this too:
`return ImagesProfile.find({},  {fields:{'name':1, 'userId':1, 'selected':1, '_downloadRoute':1,  'versions.thumbnail.type':1, 'versions.thumbnail.path':1, '_collectionName':1}}).cursor;`
And: 
But if I returning to the first `find({}, {fields:{'name':1, 'userId':1} }).cursor;`
Look a the dom
src="http://localhost:3000undefined/undefined/SbArDfQxKswPHhFBY/original/SbArDfQxKswPHhFBY"
So what I think, it's not a matter of versions, is just a matter of _downloadRoute_ 

I'm so sorry to have lost your time (and mine ahah)

**Comment by dr-dimitru** [comment]
No worries. It's always good to dig and investigate.
I assume this thread as closed.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Stat on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
