### ISSUE TITLE
file types are incorrectly determined from mime types

### ISSUE THREAD

**Issue by s-ol** [VeliovGroup/Meteor-Files#183]
`isImage`, `isVideo`... checks are not strict enough (line [1114](https://github.com/VeliovGroup/Meteor-Files/blob/d534cf9a6219821a82c469927f580c787a175cee/files.coffee#L1114)):

      isVideo: !!~data.type.toLowerCase().indexOf('video')
      isAudio: !!~data.type.toLowerCase().indexOf('audio')
      isImage: !!~data.type.toLowerCase().indexOf('image')
      isText:  !!~data.type.toLowerCase().indexOf('text')
      isJSON:  !!~data.type.toLowerCase().indexOf('json')
      isPDF:   !!~data.type.toLowerCase().indexOf('pdf')

for example the file type for .iso images is `application/iso-image`, `application/x-iso-image` or `application/x-iso9660-image`, all of which trigger `isImage` (wrongly).
At least for `image`, it should be checked with something along the lines of `data.type.toLowerCase().startsWith("image/")` IMO.

**Comment by dr-dimitru** [comment]
Agree, will take a look on it

**Comment by dr-dimitru** [comment]
Hi @s-ol ,

Is this update solved issue on your end?

**Comment by s-ol** [comment]
yes.

**Comment by dr-dimitru** [comment]
Great, thank you for contribution
