### ISSUE TITLE
Not able to use load Function on Windows, it works perfectly fine on Ubuntu LTS 14

### ISSUE THREAD

**Issue by salmanhasni** [VeliovGroup/Meteor-Files#184]
This is the error
W20160813-01:37:37.669(5)? (STDERR) stream.js:74
W20160813-01:37:37.724(5)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20160813-01:37:37.724(5)? (STDERR)       ^
W20160813-01:37:37.724(5)? (STDERR) 
W20160813-01:37:37.724(5)? (STDERR) Error: ENOENT: no such file or directory, open 'E:\wcif\.meteor\local\build\programs\server\assets\app\uploads\Images\Hc42Pg6kigDj9PpSh.jpg?oh=36b427001c86a63a8b53819e99aa7000&oe=584DDFBE&\__gda\__=1478129990_b368aeadf01e50a998b8c20c9270fd0b'
W20160813-01:37:37.725(5)? (STDERR)     at Error (native)

here is my code

**Shared Code**

```
this.Images = new FilesCollection({
    collectionName: 'Images',
    allowClientCode: false, // Disallow remove files from Client
    onBeforeUpload: function (file) {
        // Allow upload files under 10MB, and only in png/jpg/jpeg formats
        if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
            file.uploadedAt = new Date();
            return true;
        } else {
            return 'Please upload image, with size equal or less than 10MB';
        }
    }
});
```

**Server Code**

```
var getQuestionImage = function(url, questionId){
    if(url){
        Images.load(url, {
            meta : {
                questionId: questionId
            }
        });
    }
};

Meteor.startup(function(){
    if(Meteor.settings.allowScrapping) {
        getQuestionImage (<dont bother this, parameters having no issues>);
    }
});
```

**Comment by dr-dimitru** [comment]
1. `?oh=36b427001c86a63a8b53819e99aa7000&oe=584DDFBE&gda=1478129990_b368aeadf01e50a998b8c20c9270fd0b` Where those parameters comes from?
2. Please, enable debug mode, and post its output along with this error, to let me see the data-flow

**Comment by salmanhasni** [comment]
@dr-dimitru I have just provided the url for for uploading which i m getting it from graph api of facebook
That is like
https://fbcdn-photos-a-a.akamaihd.net/hphotos-ak-xfa1/v/t1.0-0/s130x130/13939399_10153642261122540_9077589439512184461_n.jpg?oh=042cb22f076c824efb83776b0871ad14&oe=5819911B&__gda__=1481867333_d9fc9b43c71ecb877f8303a90c90f8a4

probably when saving the file, the default name is consider image url params too which is creating special character issue

**Comment by salmanhasni** [comment]
@dr-dimitru Alright let me show your debug data flow

**Comment by salmanhasni** [comment]
@dr-dimitru here is the debug log

I20160813-01:57:04.144(5)? [FilesCollection.storagePath] Set to: assets\app\uploads\Images
I20160813-01:57:11.345(5)? [FilesCollection] [load(https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpf1/v/t1.0-1/c0.0.320.320/p320x320/13680555_153333465094573_8546154681802574840_n.jpg?oh=b8b3bfb7ad1b9cc8580414a403170388&oe=58570DC8&__gda__=1478435866_ed4a06b161e57fd9d1b7b23c71ca2ca8, {"meta":{"userId":"6SHaQDaCXeuvTdPS6"}}, callback)]
W20160813-01:57:11.357(5)? (STDERR) stream.js:74
W20160813-01:57:11.357(5)? (STDERR)       throw er; // Unhandled stream error in pipe.
W20160813-01:57:11.357(5)? (STDERR)       ^
W20160813-01:57:11.358(5)? (STDERR) 
W20160813-01:57:11.358(5)? (STDERR) Error: ENOENT: no such file or directory, open 'E:\wcif\.meteor\local\build\programs\server\assets\app\uploads\Images\rTm8qbRRHf4jtRdXY.jpg?oh=b8b3bfb7ad1b9cc8580414a403170388&oe=58570DC8&__gda__=1478435866_ed4a06b161e57fd9d1b7b23c71ca2ca8'
W20160813-01:57:11.358(5)? (STDERR)     at Error (native)

**Comment by dr-dimitru** [comment]
Could you please try to call `.load()` method directly, and pass there exact link, but without `query` string. If it will work, I'll assume it as a bug.

> probably when saving the file, the default name is consider image url params too which is creating special character issue

And this is not happening on unix like machines? And btw it's not possible due to [this line](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1237)

**Comment by dr-dimitru** [comment]
According to your bug logs, exception happens before you call `.load()`

**Comment by salmanhasni** [comment]
@dr-dimitru Yes its not happening in Linux machine, i got the same code there.
Actually this query string is what i m getting from the graph api of facebook (to get user profile picture or any post picture)

**Comment by salmanhasni** [comment]
so without it i wont be get image, i return 403 without query params

**Comment by dr-dimitru** [comment]
Got, it lours really weird to me.
May be @Neobii can take a look, I know he uses Windows for development.

Meanwhile @salmanhasni :
 1. Could you check what actually is in `E:\wcif.meteor\local\build\programs\server\assets\app\uploads\Images\` directory?
 2. From the FAQ: `To keep you storage persistent use absolute path outside of your project folder, we recommend to use /data directory`. So can you try to use some directory placed out of the meteor project
 3. Run `meteor reset`, to make sure there is nothing coming from older unsuccessful calls

**Comment by salmanhasni** [comment]
@dr-dimitru I m getting this error even i m explicitly providing the filename

```
Images.load(url, {
            meta : {
                questionId: questionId
            },
            fileName: questionId + ".jpg";
        });
```

**Comment by dr-dimitru** [comment]
`fileName` property has no effects on how file is written to FS

**Comment by salmanhasni** [comment]
@dr-dimitru 
1-I have seen there nothing is there, Well i have tried to load an without query params, its working fine
2-Yes i have tried it
3-I have tried this too, I have even remove the local folder inside .meteor directory

**Comment by Neobii** [comment]
I actually use Ubuntu in vmware

**Comment by dr-dimitru** [comment]
@Neobii Okay, I thought you test meteor on both platforms, sorry for this.

**Comment by salmanhasni** [comment]
@dr-dimitru I dont think so its the issue of Writing to FS, its look like its a kernel issue which is actually not allowing windows to create file name with special character

**Comment by salmanhasni** [comment]
@dr-dimitru here is your culprit
https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1083
https://jsfiddle.net/890j7ma5/

**Comment by dr-dimitru** [comment]
@salmanhasni I'm agree on this one. Please wait for a next release.

**Comment by salmanhasni** [comment]
@dr-dimitru Sure thanks
