### ISSUE TITLE
web worker upload does not work when app is running in a path (e.g. ./my-app)

### ISSUE THREAD

**Issue by Torsten85** [VeliovGroup/Meteor-Files#188]
Hi there,
I've noticed that the web worker upload is not working in my production environment due to the fact that my app is running in a path. 
I think this happens because 
`@worker = new Worker '/packages/ostrio_files/worker.js'`
(https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1474)
does not respect the ROOT_URL.

Thanks in advance
Torsten

**Comment by dr-dimitru** [comment]
Hi @Torsten85 ,

Forgot to ask you, is this issue solved on your end?

**Comment by lucasvw** [comment]
+1

**Comment by dr-dimitru** [comment]
@lucasvw are you having this issue now?

**Comment by lucasvw** [comment]
Yes, setting the ROOT_URL from http://localhost:3000 to http://localhost:3000/sp breaks the client side insert statement. 

The onUploaded callback is immediately called and error and fileObj are both undefined. On server disk, nothing is uploaded.

**Comment by dr-dimitru** [comment]
@lucasvw 
 1. What version of MF package you're on?
 2. What browser/platform?
 3. Is `Blob` available at your browser? Just type `window.Blob` into browser's console
 4. Type `Meteor.absoluteUrl('packages/ostrio_files/worker.min.js')` into browser's console, what it outputs?

**Comment by lucasvw** [comment]
1. ostrio:files@1.5.6
2. Chrome / Windows 10
3. window.Blob -> function Blob(){}
4.http://localhost:3000/sp/packages/ostrio_files/worker.min.js

Hmm the output of the last point I find curious..

**Comment by dr-dimitru** [comment]
Actually it won't request worker over the wire as `Blob` is supported it will use inline worker.

turn on `debug` mode, let's see what it has to tell us

**Comment by lucasvw** [comment]
debug mode ?

**Comment by dr-dimitru** [comment]
@lucasvw yes, set `{debug:true}` in [`Constructor`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by lucasvw** [comment]
Client : "insert logo_kleiner.png: 4.732ms" Server : nothing

**Comment by dr-dimitru** [comment]
So no errors, right?

**Comment by lucasvw** [comment]
nope no errors

**Comment by dr-dimitru** [comment]
@lucasvw so issue is gone?

**Comment by lucasvw** [comment]
Uh no, issue is not gone. Just no errors are outputted

**Comment by dr-dimitru** [comment]
> The onUploaded callback is immediately called and error and fileObj are both undefined

Sound weird. Is this happens without path prefix?

**Comment by lucasvw** [comment]
When I am using ROOT_URL 

`http://sp.localhost:3000` or 
`http://localhost:3000 `

everything works fine

**Comment by dr-dimitru** [comment]
So why not set `ROOT_URL` to `http://localhost:3000/sp` ?

**Comment by dr-dimitru** [comment]
Anyways could you drop me full server and client logs? From starting app and uploading single file to the end.

**Comment by lucasvw** [comment]
> Yes, setting the ROOT_URL from http://localhost:3000 to http://localhost:3000/sp breaks the client side insert statement.

>The onUploaded callback is immediately called and error and fileObj are both undefined. On server disk, nothing is uploaded.

See above :)

**Comment by lucasvw** [comment]
[temp.txt](https://github.com/VeliovGroup/Meteor-Files/files/539159/temp.txt)

**Comment by dr-dimitru** [comment]
Does it works when WebWorker is disabled? Set [`allowWebWorkers`](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)) to `false`

**Comment by lucasvw** [comment]
Nope

**Comment by dr-dimitru** [comment]
Last thing to try is `HTTP` transport.
Set `{transport: 'http'}` at [`upload`](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)) method

If this won't help I'll assume this as bug and going to investigate it on our end
