### ISSUE TITLE
Custom path for every upload

### ISSUE THREAD

**Issue by omarwaleed** [VeliovGroup/Meteor-Files#190]
My code follows the API explained in the READ ME but i tried implementing a way to create a custom path for every upload but the constructors for the `FilesCollection` has to be initialized only once with only one storage path or else will throw an error of "Collection already exists". I am thinking of using the npm package (fs-extra) and moving every file after it is uploaded and then update the path in the object file but i felt like this was going to cause redundancy. Any help in specifying the storage path/directory for each upload?

**Comment by dr-dimitru** [comment]
> I am thinking of using the npm package (fs-extra) and moving every file after it is uploaded and then update the path in the object file

This is right way. Other question, why do you need to move files around?

**Comment by dr-dimitru** [comment]
@omarwaleed is this issue solved?

**Comment by dr-dimitru** [comment]
@omarwaleed ?

**Comment by nikhilgoswami** [comment]
I need a custom base url like aws.com instead of localhost:3000 in file upload because it doesn't seem to work in react native image component.

**Comment by dr-dimitru** [comment]
@nikhilgoswami use `ROOT_URL` env.var

**Comment by nikhilgoswami** [comment]
I customized the url in other way by adding the s3.amazonaws.com directly but it seems the uploaded files are private on bucket when i make them public on aws i can see the image being loaded in image component any idea. My bucket is public but new uploaded files are not public.

**Comment by dr-dimitru** [comment]
@nikhilgoswami have you followed [AWS:S3 tutorial](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration)?
