### ISSUE TITLE
Support DataURI (Base64) uploads

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/Meteor-Files#192]

**Comment by dr-dimitru** [comment]
This will be useful after file is changed on the client and returned as DataURI, for example image changed in canvas

**Comment by dr-dimitru** [comment]
Please vote if you need this feature

**Comment by renatomattos2912** [comment]
+1

**Comment by dr-dimitru** [comment]
Implemented in v1.7.1, [see example](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#upload-base64-string)

@renatomattos2912 could you please test it on your end, and give some feedback?

**Comment by renatomattos2912** [comment]
@dr-dimitru of course, i will do this now.

**Comment by renatomattos2912** [comment]
@dr-dimitru it works pretty well. Thanks to be so fast in this feature.

**Comment by dr-dimitru** [comment]
@renatomattos2912 , thank you for vote and for choice this package for file uploads

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by renatomattos2912** [comment]
@dr-dimitru done

**Comment by dr-dimitru** [comment]
Hi @renatomattos2912 ,

In v1.7.3 various fixes about base64 uploads. Could you test it on your end?

**Comment by renatomattos2912** [comment]
Hi @dr-dimitru of course, i will try this week and soon i tell you. Thanks

**Comment by java99** [comment]
+1

**Comment by luixal** [comment]
Hi!,

I've seen that `insert` function is only available con client side, what would be the best way to store a b64 file in server?

I'm trying to make this work with the `nimble:restivus` package for uploading files through an HTTP POST/PUT.

Thanks!

**Comment by dr-dimitru** [comment]
Hello @luixal ,

On server the is various methods like [`write`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) and [`load`](https://github.com/VeliovGroup/Meteor-Files/wiki/Load)

For upload via POST check out [this example](https://github.com/noris666/Meteor-Files-POST-Example)

**Comment by luixal** [comment]
Yep, I finally make it work using the `write` function, works like a charm :)

Another thing (unrelated to this issue): in order to show images and download link, I have to use the template helper `{{fileURL fileRef 'thumb'}}` if I try getting the `link` field it's always null. Any ideas on how to get the URL without using that helper?

Thanks!

**Comment by luixal** [comment]
Hmmm... there's another problem I'm having. According to the wiki, the `write` function returns the collection itself:
```
Returns {Files} - Current FilesCollection instance
```

Wouldn't it be better if it returns the _id of the saved file as other collections do?

If I do something like:

```javascript
let result = Images.write(
  new Buffer(base64Data, 'base64'),
  {
    fileName: 'uploaded_' + (new Date()).getTime() + '.png',
    type: 'image/png'
    }
  );
```

would it block until result gets a value?

**Comment by dr-dimitru** [comment]
@luixal document from MongoDB returned in callback

>  if I try getting the link field it's always null

How do you call it? Need to see your code

**Comment by luixal** [comment]
Just tried these two lines:

```javascript
console.log(Images.findOne()); // <--- returns a FileCursor
console.log(Images.collection.findOne()); // <--- returns and object
```

if I do:

```javascript
console.log(Images.findOne().link); // <--- undefined
console.log(Images.collection.findOne().link); // <--- undefined
```

As for the example about the [Download Button](https://github.com/VeliovGroup/Meteor-Files#download-button) which shows something like:

```html
<template name='file'>
  <a href="{{file.link}}?download=true" download="{{file.name}}" target="_parent">
    {{file.name}}
  </a>
</template>
```

i thought that `link` would be a field of the file object, but I'm not able to get it.

----
Here is the object returned by the second console.log

```javascript
{
  _id: '9v8p46u3zSmamxqYR',
  name: 'sample.png',
  extension: 'png',
  path: 'assets/app/uploads/Images/9v8p46u3zSmamxqYR.png',
  meta: {},
  type: 'image/png',
  size: 6,
  userId: null,
  versions: {
    original: {
      path: 'assets/app/uploads/Images/9v8p46u3zSmamxqYR.png',
      size: 6,
      type: 'image/png',
      extension: 'png' 
    }
  },
  isVideo: false,
  isAudio: false,
  isImage: true,
  isText: false,
  isJSON: false,
  isPDF: false,
  _downloadRoute: '/cdn/storage',
  _collectionName: 'Images',
  _storagePath: 'assets/app/uploads/Images' 
}
```

**Comment by luixal** [comment]
I finally managed to make the `link()` function work. I guess I was trying to call it on the object, not the `FileCursor`.

As for the result of the `write` function, is there any way to get the `_id` or the full object of the last written file?

With all collections I usually call them like this:

```javascript
let inserted = MyCollection.insert(object);
```

This allows me to get the inserted object and also **block** the function until I get a result (really useful in methods and API functions).

Any idea on how to make this work that way?

Thanks!

**Comment by dr-dimitru** [comment]
Hi @luixal ,

[`write`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) method is asynchronous, only way to work via callback or wrap it into [`wrapAsync`](https://docs.meteor.com/api/core.html#Meteor-wrapAsync), like:
```js
Images = new FilesCollection({/*...*/});

Images.writeSync = Meteor.wrapAsync(Images.write);
```

That's it :)

**Comment by luixal** [comment]
Hi there!

That's how I'm using it, was just wondering if it wouldn't be useful to make it work like regular collections :)

```javascript
let resultId = MyCollection.insert({...}) // <--- sync
MyCollection.insert(...); // <--- async and allows you to pass a callback or not
```

Thanks!

**Comment by dr-dimitru** [comment]
@luixal it will cost efficiency, as it will be blocking IO. Working with FS is different than DB.
