### ISSUE TITLE
google storage support email required

### ISSUE THREAD

**Issue by demiantriebl** [VeliovGroup/Meteor-Files#195]
i try to use google storage, but says this error 

 { [Error: email is required.] code: 'MISSING_CREDENTIALS' }

i put the json like download, but i need another element?

**Comment by dr-dimitru** [comment]
in docs it says: 

> Replace this with the path to your key.json

**Comment by dr-dimitru** [comment]
@demiantriebl any news on your end?

**Comment by demiantriebl** [comment]
yes, you are rigth, i  put the json in right place and run!. thanks!!

**Comment by dr-dimitru** [comment]
Glad you've solved it.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
