### ISSUE TITLE
WebWorker Error when running on Android cordova

### ISSUE THREAD

**Issue by mking200** [VeliovGroup/Meteor-Files#196]
Hi, I'm getting this error when uploading images from Android device in development mode:

`Error: Failed to construct 'Worker': Script at 'http://192.168.1.20:3000/packages/ostrio_files/worker.min.js' cannot be accessed from origin 'http://localhost:12280'`

Its working normally when running on localhost:3000 in web browser.

**Comment by mking200** [comment]
I tried deploying the web app on the server, then connected the Android app to that server.  And the same error is showing:

`Failed to construct 'Worker': Script at 'http://my-root-domain.com/packages/ostrio_files/worker.min.js' cannot be accessed from origin 'http://localhost:12280'.`

I also tried setting this on `mobile-config.js`, but the app still could not access the `worker.min.js` file:
`App.accessRule( "http://my-root-domain.com" );`

**Comment by mking200** [comment]
Is there any way to override this and just get `worker.min.js` on public folder?

**Comment by dr-dimitru** [comment]
@mking200 
Sorry, this was broken in v1.7.0
Please wait for next release. Meanwhile you can use v1.6.10 or set `settings.allowWebWorkers` to `false` in [`.insert()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)) method options

**Comment by dr-dimitru** [comment]
Btw, have tried the `App.accessRule('*')` and/or `meteor build --server http://my-root-domain.com`

**Comment by mking200** [comment]
Yes, have tried all that except for `App.accessRule('*')`

**Comment by dr-dimitru** [comment]
BTW this was broken by this fix: https://github.com/VeliovGroup/Meteor-Files/issues/188 :)

Do you have an idea how to fit both requirements?

**Comment by mking200** [comment]
Can we try to have an option to set the link to `worker.min.js` file manually?  

Am thinking of putting this in public folder, since the Android app doesn't seem to have problem with access to public folder.

**Comment by dr-dimitru** [comment]
I'll use inline worker in v1.7.1, so there is will be no need to have a request for worker over the wire

**Comment by mking200** [comment]
Ok, thanks.  Will just wait for the next update then.

**Comment by dr-dimitru** [comment]
Hi @mking200 ,

Fixed in v1.7.1, pleas update and test on your end
