### ISSUE TITLE
Correct percentage with Future

### ISSUE THREAD

**Issue by livimonte** [VeliovGroup/Meteor-Files#202]
Hi, I need to generate 4 thumbs and send to S3. It's working but the percentage of the upload goes to 100% when it finishes upload  of the first image. It is possible to measure the percentage of the thumbs and S3 process?

And when the process ends,  how do I return another object or value instead of the collection?

For example pick Future Return (And/insteadOf) FileObj on the event: "upload.on ('end', function (err, fileObj)";

```javascript
resFuture.return ({
             files: {
               original: originalS3,
               xsmall: xsmallS3,
               small: smallS3,
               medium: mediumS3,
               large: largeS3
             }
           });
```

## Code

```javascript

// Functions

var generateThumbs = function(path, size, version){
  let resFuture = new Future();
  const arrayPath = path.split('/'),
    imageName = arrayPath[arrayPath.length - 1],
    newPath = path.replace(imageName, version + '/'+imageName);

  gm(path).autoOrient().resize(size).gravity('Center')
    .write(newPath, function (err) {
      if(!err) resFuture.return(newPath);
      else resFuture.throw(err);
    });
  return resFuture.wait();
};

var uploadS3 = function(path, version = false){
  let resFuture = new Future(), newPath;
  const pathCleared = path.replace(appRootPath, ''),
    arrayPath = pathCleared.split('/'),
    fileName = arrayPath[arrayPath.length - 1];

  newPath = version ? pathCleared.replace(fileName, version + '/'+fileName) : pathCleared;
  client.putFile(path, newPath, function(err, res) {
      if(!err) resFuture.return(res.req.url);
      else resFuture.throw(err);
  });

  return resFuture.wait();
};

// Collection

HistoriesFiles = new FilesCollection({
  debug: Meteor.settings.public.debug,
  collectionName: 'historiesFiles',
  storagePath: appRootPath + '/uploads/histories',
  downloadRoute: '/images/histories',
  allowClientCode: false,
  public: true,
  onAfterUpload: function (fileRef) {
    let resFuture = new Future();
    const self = this;

    let original = fileRef.path,
      xsmall = generateThumbs(fileRef.path, 256, 'xsmall'),
      small = generateThumbs(fileRef.path, 282, 'small'),
      medium = generateThumbs(fileRef.path, 595, 'medium'),
      large = generateThumbs(fileRef.path, 1600, 'large');

    let originalS3 = uploadS3(original, 'original'),
      xsmallS3 = uploadS3(xsmall),
      smallS3 = uploadS3(small),
      mediumS3 = uploadS3(medium),
      largeS3 = uploadS3(large);

       if(originalS3 && xsmallS3 && smallS3 && mediumS3 && largeS3){

      const doc = {
        versions: {
          original: originalS3,
          xsmall:  xsmallS3,
          small:  smallS3,
          medium:  mediumS3,
          large: largeS3
        }
      };

      self.collection.update({_id: fileRef._id}, {$set: doc}, function(err, res) {
        if(!err) {
          fs.unlinkSync(original);
          fs.unlinkSync(xsmall);
          fs.unlinkSync(small);
          fs.unlinkSync(medium);
          fs.unlinkSync(large);
          resFuture.return(true);
        } else {
          resFuture.throw(err);
        }
      });
    }
    return resFuture.wait();
  }
});
```
Thanks,

#### Update: 
Added Collection update with versions for references

**Comment by dr-dimitru** [comment]
Hi @livimonte ,

Currently it is not possible, even blocking code (like Fiber/Future) won't work as `onAfterUpload` callback is totally asynchronous and detached from MainThread.

You need to really on Mongo record, please see [this thread](https://github.com/VeliovGroup/Meteor-Files/issues/191) we discussed similar behaviour with @owenhoskins

Let me know if it works for you

**Comment by livimonte** [comment]
Thanks @dr-dimitru, works =)

I updated the issue description with collection update. Maybe help someone.

Congratulations for the good work and it's true @owenhoskins: 

> I feel like I have control of my uploads with Meteor for the first time :)

**Comment by dr-dimitru** [comment]
@livimonte marked as [`In case of the fire - Read This`]
Thank you for the choice of this package, and your contribution.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
