### ISSUE TITLE
cURL upload

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/Meteor-Files#206]
Add to the docs article with examples about upload via cURL, including custom authentication.

**Comment by dr-dimitru** [comment]
Basically you there is 3 steps:
 - Start resumable upload (a.k.a. "*first byte*"), by sending meta-data to `[POST] "{downloadRoute}/{collectionName}/__upload"`
   * Headers: 
      - 'x-start': '1'
      - 'x-mtok': Meteor.connection._lastSessionId
   * Body:
      - file: "all file metadata as JSON, like name, type, size, {meta}"
      - fileId: "MongoDB id string"
      - chunkSize: "Your chunk size, it may be equal to file size, but upload won't be resumable"
      - fileLength: "Quantity of chunks"

 - After start request is ended send chunk(s) to  `[POST] "{downloadRoute}/{collectionName}/__upload"`
   * Headers:
     - 'x-mtok': Meteor.connection._lastSessionId || null
     - 'x-fileid': "MongoDB id"
     - 'x-chunkid': "Chunk number"
     - 'content-type': 'text/plain'
   * Body:
     - Raw base64 string

- After all chunks is sent we need to send EOF (a.k.a. *last byte*) to  `[POST] "{downloadRoute}/{collectionName}/__upload"`
   * Headers:
     - 'x-mtok': Meteor.connection._lastSessionId || null
     - 'x-fileid': "MongoDB id"
     - 'x-eof': '1'
     - 'content-type': 'text/plain'
   * Body - empty

Need someone to test all those steps and write docs.

**Comment by dr-dimitru** [comment]
quick note:
`Raw base64 string` is base64 string without `data:mime/type;format,` prefix

**Comment by dr-dimitru** [comment]
Highly related: https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js

**Comment by dr-dimitru** [comment]
Hey @noris666 ,

What do you think, can we close this one with your solution?

**Comment by noris666** [comment]
Hello @dr-dimitru !
Yes we can close with my solution. 
Because in 2 weeks I start the application with this implementation.  

But i think for better code i can modify my repo.

**Comment by dr-dimitru** [comment]
Good, just keep it updated.
References to your repo is added to wiki and read

Thank you @noris666

**Comment by noris666** [comment]
@dr-dimitru thx 4 support my implementation ! 👍 

And what you think directly add support POST to your package ?

**Comment by dr-dimitru** [comment]
Currently it's security trap.
Take a look on this thread: #159
Alternatively I offer to support `auth` header. Take a part in #159

**Comment by dr-dimitru** [comment]
And there is other caveats with resumable uploads

**Comment by noris666** [comment]
@dr-dimitru ok i understand all, thx for detailed answer.

**Comment by think-in-data** [comment]
@noris666 thanks for the solution. But I'm wondering what's the best practice to implement the HTTP backend for Meteor-Files that fit different sizes of files from 1KB to 1GB. I saw your solutions is mainly for avatars in your example [https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js](https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js), have you tried uploaded large-size files with cURL and any issues?

**Comment by noris666** [comment]
@think-in-data i'll checked maximum ~40MB file sizes. Let me know about results if you will try check upload big files.

**Comment by think-in-data** [comment]
@noris666 I haven't tried run with your example code, but I may implement my solution as @dr-dimitru has suggested. 

@dr-dimitru thanks. yes, that's also what I'm trying to apply, and I'll let you know if it works well.
