### ISSUE TITLE
support callback which will only called once before upload

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#208]
As mentioned in #207, currently, onBeforeUpload will called on each chunk upload, which could raise potential performance drop if some expensive operation is contained in onBeforeUpload. Would be great to support callback which would only execute once, either by change the current onBeforeUpload or add something like onInitiateUpload.

**Comment by dr-dimitru** [comment]
I'll stay with `onInitiateUpload `. As changing `onBeforeUpload` current behaviour, may break some current usage, or will request Major version release

**Comment by dr-dimitru** [comment]
Implemented in v1.7.2

**Comment by oeway** [comment]
@dr-dimitru It worked, but it seems that the returned value from `onInitiateUpload` is not used to reject a upload?

**Comment by oeway** [comment]
However, I can `throw new Meteor.Error('not-authorized');` in `onInitiateUpload ` to stop the upload.

**Comment by dr-dimitru** [comment]
Why not use `onBeforeUpload` to control/stop/continue upload?
`onInitiateUpload` is create for purpose you've described - `if some expensive operation is contained`. And it's asynchronous, throwing an exception will stop all process, but it might be somewhere in the middle or at the end of upload

**Comment by livimonte** [comment]
It would be better to make the file validation (check weight and extension for example) in onInitiateUpload instead of onBeforeUpload? Since that runs only once and before starting the upload.

**Comment by dr-dimitru** [comment]
This will be removed in v2.0
As it comes from early stages of this package it may break someone's integration

It was done this way to protect unfinished uploads from fraud actions. As previously was no control of uploaded size, currently any size overflow will abort upload.

**Comment by DrkCoater** [comment]
I've looked into the code, seems like onInitiateUpload is not being called if onBeforeUpload is not being defined, is this done intentionally?

**Comment by dr-dimitru** [comment]
@livimonte `onBeforeUpload` is made this way to avoid file mitigation during upload

**Comment by dr-dimitru** [comment]
@DrkCoater you right, this shouldn't be this way.
Fix will be released soon, thank you
