### ISSUE TITLE
FilesCollection.findOne(null) should return null

### ISSUE THREAD

**Issue by exKAZUu** [VeliovGroup/Meteor-Files#210]
Although `Mongo.Collection.findOne(null)` always returns `null`, `FilesCollection.findOne(null)` returns a document.
I feel it's confusing, so I would propose that `FilesCollection.findOne(null)` should return `null`.

**Comment by dr-dimitru** [comment]
Agree, will add to next release
Currently it acts as `FilesCollection.findOne({})`

**Comment by dr-dimitru** [comment]
Hi @exKAZUu ,

This issue is solved in [v1.7.3](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.3)
Please update and test it on your end.

**Comment by exKAZUu** [comment]
Hi, thank you for your update!
I checked the new version and found some issues.
(Sorry. I should have mentioned about `find`.)

Here is the behaviour of `Mongo.Collection` (i.e. expected).

```
Collection.find({}).fetch() => an array of documents
Collection.find().fetch() => an array of documents
Collection.find(null).fetch() => an empty array
Collection.find(undefined).fetch() => an empty array

Collection.findOne({}) => a documents
Collection.findOne() => a documents
Collection.findOne(null) => undefined
Collection.findOne(undefined) => undefined
```

However, FilesCollection now works as follows.

```
Collection.find({}).fetch() => an array of documents
Collection.find().fetch() => an array of documents
Collection.find(null).fetch() => an array of documents (should be an empty array)
Collection.find(undefined).fetch() => an array of documents (should be an empty array)

Collection.findOne({}) => a document
Collection.findOne() => undefined (should be a document)
Collection.findOne(null) => undefined
Collection.findOne(undefined) => undefined
```

**Comment by exKAZUu** [comment]
I suspect that it is caused by the difference between JavaScript and CoffeeScript.
Although CoffeeScript's default values for arguments are used when the argument is `null` or `undefined`, JavaScript's default values for arguments are used when the argument is only omitted.
