### ISSUE TITLE
Demo applications. How upload file in localhost in linux system

### ISSUE THREAD

**Issue by samurai-jack** [VeliovGroup/Meteor-Files#211]
Hi ran the demo applications.

I installed in Linux and Meteor.js version 1.4.1.1. For running applications made the upload pdf file. Clicking on the link to the stated file is not generated preview(Preview is not available, please download file) and I have no way to save the file on your computer(The failure of a network error).

Command "mongo meteor" I checked the contents of data collection:

{ "_id" : "EytqjTjQN99zDt9Ld", "name" : "uokik_zakupy_przez_internet_ulotka.pdf", "extension" : "pdf", "path" : "assets/app/uploads/uploadedFiles/EytqjTjQN99zDt9Ld.pdf", "meta" : { "blamed" : 0, "secured" : false, "expireAt" : ISODate("2016-09-01T06:04:44.082Z"), "unlisted" : false, "downloads" : 0, "created_at" : 1472623484081 }, "type" : "application/pdf", "size" : 219032, "versions" : { "original" : { "path" : "assets/app/uploads/uploadedFiles/EytqjTjQN99zDt9Ld.pdf", "size" : 219032, "type" : "application/pdf", "extension" : "pdf" } }, "isVideo" : false, "isAudio" : false, "isImage" : false, "isText" : false, "isJSON" : false, "isPDF" : true, "_storagePath" : "assets/app/uploads/uploadedFiles", "_downloadRoute" : "/cdn/storage", "_collectionName" : "uploadedFiles", "public" : false }

I noticed that the file should be saved in the path "assets/app/uploads/uploadedFiles". Is to save on server localhost Linux I have to create the system path. If so, in which directory.

**Comment by dr-dimitru** [comment]
1. Debug mode logs
 2. Read [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/85#issuecomment-221493110) and first item in [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq)

**Comment by dr-dimitru** [comment]
@samurai-jack your issue solved?

**Comment by samurai-jack** [comment]
Yes. I changed the variable "storagePath" in "images.collection.js" and files to store on the server. Now I just have to solve the problem with downloading files stored on the server, but look for solutions in the file README.md. Thank you for your help

**Comment by dr-dimitru** [comment]
> problem with downloading files

How do you generate downloadable link?

**Comment by samurai-jack** [comment]
At the moment there I changed any parameters in the application and a link to download the file is generated automatically. During sampling downloading the file receives information from the server "localhost server refused the connection." Also I am taking to find a variable responsible of downloading files on the server. I hope you find it ;)

**Comment by dr-dimitru** [comment]
I didn't get your answer.
How do you generate downloadable link?

**Comment by samurai-jack** [comment]
Sorry but by my lack of knowledge I posted a demo application that works on the same principle as live applications found on the website: https://files.veliov.com/. I run it on your server and upload and download files work automatically without any configuration.
Your question infers that I have to configure the application in order to be able to download the saved files on the server, which I did not.
If I can still ask for a moment of your attention, please explain to me or send the link what should be done to allow the application to generate the file view and download them from the server using the application.
Thank you in advance for your help

**Comment by dr-dimitru** [comment]
If you're using 1:1 copy of [this demo](https://github.com/VeliovGroup/Meteor-Files/tree/master/demo) everything should work. Make sure `ROOT_URL` and `MONGO_URL` env.vars is set

Enable debug mode in [files.collection.coffee#L51](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L51) and post your server logs.

**Comment by samurai-jack** [comment]
Applications run the command:
meteor altitude install
meteor
The file app.json value "ROOT_URL" and "MONGO_URL" are set to the value: "required": true

And this is the server log:
I20160831-17:19:39.624(0)? [FilesCollection] [find({"$or":[{"meta.unlisted":false,"meta.secured":false,"meta.blamed":{"$lt":3}},{"userId":null}]}, undefined)]
I20160831-17:19:39.627(0)? [FilesCollection] [FilesCursor] [count()]
I20160831-17:19:46.671(0)? [FilesCollection] [File Start HTTP] platan.txt - XmLaZ6Xzum2Ljyo8b
I20160831-17:19:46.672(0)? [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: platan.txt
I20160831-17:19:46.714(0)? [FilesCollection] [Upload] [HTTP] Got #1/1 chunks, dst: platan.txt
I20160831-17:19:46.743(0)? [FilesCollection] [Upload] [HTTP] Got #-1/1 chunks, dst: platan.txt
I20160831-17:19:46.745(0)? [FilesCollection] [Upload] [finish(ing)Upload] -> /home/vagrant/meteor_uploads/XmLaZ6Xzum2Ljyo8b.txt
I20160831-17:19:46.761(0)? [FilesCollection] [Upload] [finish(ed)Upload] -> /home/vagrant/meteor_uploads/XmLaZ6Xzum2Ljyo8b.txt
I20160831-17:19:46.793(0)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: XmLaZ6Xzum2Ljyo8b
I20160831-17:19:46.799(0)? [FilesCollection] [find({"$or":[{"_id":"XmLaZ6Xzum2Ljyo8b","meta.secured":false},{"_id":"XmLaZ6Xzum2Ljyo8b","meta.secured":true,"userId":null}]}, {"fields":{"_id":1,"name":1,"size":1,"type":1,"meta":1,"isPDF":1,"isText":1,"isJSON":1,"isVideo":1,"isAudio":1,"isImage":1,"extension":1,"_collectionName":1,"_downloadRoute":1}})]
I20160831-17:20:25.808(0)? [FilesCollection] [remove({"meta.expireAt":{"$lte":"2016-08-31T17:22:25.806Z"}})]

**Comment by dr-dimitru** [comment]
1. I see no incoming request for a file, are you behind proxy? 
 2. What is `altitude`?
 3. In browser's console wat output of `__meteor_runtime_config__`?
 4. Post your request headers for uploaded files (can be obtained on "Network" tab in dev tools)

**Comment by samurai-jack** [comment]
1. For windows 10 have installed the software vagrant to use Linux Ubuntu 14.04 on it meteor.js
2. should: meteor npm install
3. In browser's console:
ostrio_files.js?hash=3e43f18…:2558[FilesCollection] [find({}, {"sort":{"meta.created_at":-1}})]
ostrio_files.js?hash=3e43f18…:1123[FilesCollection] [FilesCursor] [observeChanges()]
ostrio_files.js?hash=3e43f18…:997[FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:997[FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:1071[FilesCollection] [FilesCursor] [map()]
ostrio_files.js?hash=3e43f18…:997[FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:777[FilesCollection] [FileCursor] [link(thumbnail40)]
ostrio_files.js?hash=3e43f18…:3704[FilesCollection] [link(RYoXmuZ4PNNswAEJb, thumbnail40)]
ostrio_files.js?hash=3e43f18…:997[FilesCollection] [FilesCursor] [count()]
localhost:3000/cdn/storage/uploadedFiles/RYoXmuZ4PNNswAEJb/thumbnail40/RYoXmuZ4PNNswAEJb.jpg:1 GET http://localhost:3000/cdn/storage/uploadedFiles/RYoXmuZ4PNNswAEJb/thumbnail40/RYoXmuZ4PNNswAEJb.jpg net::ERR_CONNECTION_REFUSED
ostrio_files.js?hash=3e43f18…:2621 [FilesCollection] [insert()]
ostrio_files.js?hash=3e43f18…:3093 [FilesCollection] [insert] [Tracker] [continue]
ostrio_files.js?hash=3e43f18…:3201 [FilesCollection] [insert] [.continue()]
ostrio_files.js?hash=3e43f18…:3124 [FilesCollection] [insert] using WebWorkers
ostrio_files.js?hash=3e43f18…:997 [FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:997 [FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:2828 loadFile link.txt: 217ms
ostrio_files.js?hash=3e43f18…:2789 insert link.txt: 344ms
ostrio_files.js?hash=3e43f18…:997 [FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:997 [FilesCollection] [FilesCursor] [count()]
ostrio_files.js?hash=3e43f18…:2531 [FilesCollection] [findOne("99mjDQJN6d5b5RG59", undefined)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(name)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(isImage)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(isImage)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(name)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(extension)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(type)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(name)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(name)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(isImage)]
ostrio_files.js?hash=3e43f18…:797 [FilesCollection] [FileCursor] [get(isImage)]
ostrio_files.js?hash=3e43f18…:832 [FilesCollection] [FileCursor] [with()]
ostrio_files.js?hash=3e43f18…:777 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=3e43f18…:3704 [FilesCollection] [link(99mjDQJN6d5b5RG59, original)]
ostrio_files.js?hash=3e43f18…:777 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=3e43f18…:3704 [FilesCollection] [link(99mjDQJN6d5b5RG59, original)]
httpcall_client.js:189 GET http://localhost:3000/cdn/storage/uploadedFiles/99mjDQJN6d5b5RG59/original/99mjDQJN6d5b5RG59.txt net::ERR_CONNECTION_REFUSEDHTTP.call @ httpcall_client.js:189(anonymous function) @ file.coffee:16(anonymous function) @ template.js:119Template._withTemplateInstanceFunc @ template.js:465fireCallbacks @ template.js:115(anonymous function) @ template.js:208(anonymous function) @ view.js:107Blaze._withCurrentView @ view.js:538(anonymous function) @ view.js:106Tracker._runFlush @ tracker.js:511Tracker.flush @ tracker.js:455Router._invalidateTracker @ router.js:496afterAllTriggersRan @ router.js:105Triggers.runTriggers @ triggers.js:89(anonymous function) @ router.js:110(anonymous function) @ route.js:76withValue @ dynamics_browser.js:23(anonymous function) @ timers.js:6(anonymous function) @ dynamics_browser.js:51
file.coffee:19 Error: network(…)(anonymous function) @ file.coffee:19(anonymous function) @ httpcall_client.js:83(anonymous function) @ underscore.js:750xhr.onreadystatechange @ httpcall_client.js:132
ostrio_files.js?hash=3e43f18…:777 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=3e43f18…:3704 [FilesCollection] [link(99mjDQJN6d5b5RG59, original)]

4. request headers on "Network"
Request URL:http://10.11.12.21:3000/favicon-16x16.png
Request Method:GET
Status Code:304 Not Modified
Remote Address:10.11.12.21:3000
Response Headers
view source
accept-ranges:bytes
cache-control:public, max-age=0
connection:keep-alive
date:Wed, 31 Aug 2016 17:38:45 GMT
etag:"f9e7172f899221371d01050d331a11771f6a995a"
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Host:10.11.12.21:3000
If-None-Match:"f9e7172f899221371d01050d331a11771f6a995a"
Referer:http://10.11.12.21:3000/99mjDQJN6d5b5RG59
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2844.0 Safari/537.36

**Comment by dr-dimitru** [comment]
1. Anyway there should be logs about accessing file, [see](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2162)
 2. Okay
 3. Doesn't say much, what about server logs
 4. I need headers for uploaded file not `favicon-16x16.png`

**Comment by samurai-jack** [comment]
Ok. Sorry
4.
Request URL:http://10.11.12.21:3000/cdn/storage/uploadedFiles/__upload
Request Method:POST
Status Code:204 No Content
Remote Address:10.11.12.21:3000
Response Headers
view source
connection:keep-alive
date:Wed, 31 Aug 2016 17:55:26 GMT
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:359
Content-Type:application/json
Cookie:x_mtok=5EjLhbPxCsJtvitoy
Host:10.11.12.21:3000
Origin:http://10.11.12.21:3000
Referer:http://10.11.12.21:3000/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2844.0 Safari/537.36
x-mtok:5EjLhbPxCsJtvitoy
x-start:1
Request Payload
view source
{file: {size: 17, type: "text/plain", name: "wasko.txt",…}, fileId: "tirEnwcDKWvg2r3zE",…}
chunkSize
:
163840
file
:
{size: 17, type: "text/plain", name: "wasko.txt",…}
fileId
:
"tirEnwcDKWvg2r3zE"
fileLength
:
1

and

Request URL:http://localhost:3000/cdn/storage/uploadedFiles/tirEnwcDKWvg2r3zE/original/tirEnwcDKWvg2r3zE.txt
Request Headers
Provisional headers are shown
Origin:http://10.11.12.21:3000
Referer:http://10.11.12.21:3000/tirEnwcDKWvg2r3zE
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2844.0 Safari/537.36

**Comment by dr-dimitru** [comment]
Okay, visit [http://localhost:3000/c...wcDKWvg2r3zE.txt](http://localhost:3000/cdn/storage/uploadedFiles/tirEnwcDKWvg2r3zE/original/tirEnwcDKWvg2r3zE.txt) directly

And copy-paste headers here. That's really weird

**Comment by samurai-jack** [comment]
Request URL:http://localhost:3000/cdn/storage/uploadedFiles/tirEnwcDKWvg2r3zE/original/tirEnwcDKWvg2r3zE.txt
Request Headers
Provisional headers are shown
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2844.0 Safari/537.36

**Comment by dr-dimitru** [comment]
tells me nothing :(

What in response?

**Comment by dr-dimitru** [comment]
It even has no response code

**Comment by samurai-jack** [comment]
My mistake in the address url ;))

Request URL:http://10.11.12.21:3000/cdn/storage/uploadedFiles/tirEnwcDKWvg2r3zE/original/tirEnwcDKWvg2r3zE.txt
Request Method:GET
Status Code:200 OK
Remote Address:10.11.12.21:3000
Response Headers
view source
accept-ranges:bytes
cache-control:public, max-age=31536000, s-maxage=31536000
connection:keep-alive
content-disposition:inline; filename="wasko.txt"; filename=*UTF-8"wasko.txt"; charset=utf-8
content-type:text/plain
date:Wed, 31 Aug 2016 18:10:10 GMT
transfer-encoding:chunked
vary:Accept-Encoding
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:x_mtok=4rWTLTdwDnK7rBThz
Host:10.11.12.21:3000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2844.0 Safari/537.36

The contents of the file is displayed by the browser

**Comment by dr-dimitru** [comment]
Got it you issue, you trying to access file on different origin. While in your browser you're on `localhost`, you app is on `10.11.12.21:3000`.

So open `10.11.12.21:3000` in browser and it will work

**Comment by samurai-jack** [comment]
But fool me. The whole poblem in the URL.
File Download address is:
http: // localhost: 3000 / cdn / storage / Uploadedfiles / tirEnwcDKWvg2r3zE / original / tirEnwcDKWvg2r3zE.txt? download = true

and should be:
http://10.11.12.21:3000/cdn/storage/uploadedFiles/tirEnwcDKWvg2r3zE/original/tirEnwcDKWvg2r3zE.txt?download=true

Is it possible to change the address of the server http: // localhost address http://10.11.12.21

**Comment by samurai-jack** [comment]
meteor run --port 10.11.12.21:3000
Everything works

**Comment by dr-dimitru** [comment]
Wrong!

`ROOT_URL=http://10.11.12.21:3000 meteor`

**Comment by dr-dimitru** [comment]
Is it solved now?

**Comment by samurai-jack** [comment]
yes
