### ISSUE TITLE
implementing virtual files  and smart upload

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#213]
I want to implement two features for my Meteor-Files powered website, I call them virtual files and smart upload:
1) virtual files
Add a record of a file without actually upload it, meta information will be stored in the record, which contains which client own that file, what is the real path on that client etc. If another client request the file:
  * if these two clients share the same machine, then I would like it to access the file with a file path or "cp" command. 
 * if these two clients are on different machine, then ideally I would like to have a p2p transmission between the owner client and the user client. But for now, let's say, we just upload it to the server and then another client download it.

2) smart upload
For files upload to the server, we have a lot of files which could be the same, even for the same user, they may upload the same file. Uploading exactly the same file and store them on the disk is a huge waste, so I want to use some hash code or md5 calculated on the client and verified before upload to the server, if the file is already exist on the server, we just skip the upload step and tell the user immediately that the file has been uploaded, we add another file document in the collection but share the real file path with another file document.

In order to implement these two features, what will suggest? For example, I need to add file document to the collection in a more flexible way, so what are the options do I have? For smart upload, since calculating hash of a big file can take a long time, can we start the uploading the hash calculation simultaneously, if we found the same file on the server, then we terminate the uploading only make the record? Any suggestions or ideas are highly appreciated.

**Comment by dr-dimitru** [comment]
1. You have no access to FS from browser. All you can is store Blob(s) (*user has to add files via input[type="file"]*), which all be lost after page reload; 
 2. Bad idea to waste CPU recourses for Hashing. And you can not hash chunks to get a whole file hash. Also what if I really need to upload two same files. You can implement logic somehow in onBeforeUpload or in onInitiateUpload

**Comment by oeway** [comment]
Hi, thanks for your reply. My user case is mostly for python client which has constant access to FS, and it works as a service.

**Comment by dr-dimitru** [comment]
I think you can write a wrapper on top of Meteor-Files package to implement solution which fits your needs

**Comment by dr-dimitru** [comment]
Hi @oeway 

This one partly covered in: #225
Also have you got any result with cURL uploads (#206)?

May we close this thread in favour of #255 ?

**Comment by oeway** [comment]
Sure.
I didn't have time to experiment cURL uploads, but that would be something I wanted to, because we now looking at a java implementation of file uploads, with only cURL upload would be easier without touching DDP.

**Comment by dr-dimitru** [comment]
I'll look on cURL uploads to be supported next release (2-4 weeks)
