### ISSUE TITLE
FilePaths, relative to storagePaths

### ISSUE THREAD

**Issue by vnmone** [VeliovGroup/Meteor-Files#215]
Is there a way to store filepaths, relative to config.storagePath?
By default files are uploaded to config.storagePath and files-collection stores paths, including storagePath.

This method of storage paths causes problems when transferring db+files from dev to production.

**Comment by dr-dimitru** [comment]
It requires changes.
Thats why we recommend to always use absolute path, from FAQ:
> To keep you storage persistent use absolute path outside of your project folder, we recommend to use /data directory

**Comment by dr-dimitru** [comment]
@vnmone any news from your end?

**Comment by vnmone** [comment]
Bad news, I stuck.(
What is the proper way to transfer files from dev to production?

**Comment by dr-dimitru** [comment]
`rsync` or `scp` both over SSH (*It's Linux of course*)

**Comment by vnmone** [comment]
Yes, but paths will be same.
It will be nice, if i can select another path on production (like in CollectionFS)

**Comment by dr-dimitru** [comment]
```js
Images = new FilesCollection({
   storagePath: (process.env.NODE_ENV === 'development') ? 'path/on/dev' : '/path/on/prod'
});
```

**Comment by vnmone** [comment]
Да, новые файлы на продакшене будут попадать в нужную папку, но файлы которые я перенесу с дев машины (файлы + коллекция) все равно не будут отображаться (если пути не совпадут), потому что в коллекции жестко прописан путь при загрузке файла.

Было бы здорово хранить пути, относительные к  config.storagePath и при обращении, допустим, через метод Files.findOne({}).link() проиcходило бы склеивание пути.

Извините за русский, на английском пока только читаю.

**Comment by dr-dimitru** [comment]
1. No, if you use absolute path from `/` root
 2. In your case I recommend to use 3rd party storage. GridFS will perfectly fit your needs.

**Comment by vnmone** [comment]
1. In case of Linux = yes
2. I 'll look into it , but will probably have to go back to collectionFS =(

**Comment by dr-dimitru** [comment]
I didn't get it, are you on Linux? If so, why this won't work for you?

**Comment by vnmone** [comment]
unfortunally, windows

**Comment by dr-dimitru** [comment]
Hi @vnmone ,

Any news on your end? Is this issue solved? Or it can be assumed closed?

**Comment by dr-dimitru** [comment]
Assumed a solved
