### ISSUE TITLE
Files are not able to unlink when File is uploaded to GoogleDrive

### ISSUE THREAD

**Issue by salmanhasni** [VeliovGroup/Meteor-Files#217]
I m not able to delete the file from local asset folder when using google drive storage integration

i see this line but it doesn't work
self.unlink(self.collection.findOne(fileRef._id), version);

**Comment by salmanhasni** [comment]
even i getting this error 
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor

**Comment by salmanhasni** [comment]
actually the problem is here 

```
            bucket.upload(fileRef.path, options, function(error, file){
                var upd;
                    if (error) {
                        console.error(error);
                    } else {
                        upd = {
                            $set: {}
                        };
                        upd['$set']["versions." + version + ".meta.pipeFrom"] = bucketMetadata.selfLink + '/' + filePath;
                        upd['$set']["versions." + version + ".meta.pipePath"] = filePath;
                        self.collection.update({
                            _id: fileRef._id
                        }, upd, function (error) {
                            if (error) {
                                console.error(error);
                            } else {
                                // Unlink original files from FS
                                // after successful upload to Google Cloud Storage
                                self.unlink(self.collection.findOne(fileRef._id), version);
                            }
                        });
                    }
            });

```

we need to **bound** bucket.upload callback

**Comment by salmanhasni** [comment]
@dr-dimitru can you please verify and update the wiki

**Comment by salmanhasni** [comment]
@dr-dimitru how can i trigger the after upload function on **load** function ??

**Comment by dr-dimitru** [comment]
Does "bounding" solved this issue on your end?

**Comment by salmanhasni** [comment]
@dr-dimitru Indeed

**Comment by dr-dimitru** [comment]
@salmanhasni would you like to send a PR?

**Comment by salmanhasni** [comment]
@dr-dimitru sure

**Comment by dr-dimitru** [comment]
Docs is updated, thank you @salmanhasni 

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
