### ISSUE TITLE
Byte Serving

### ISSUE THREAD

**Issue by FinnFrotscher** [VeliovGroup/Meteor-Files#227]
Hey, 
Can I enable [Byte Serving](http://stackoverflow.com/a/36101965) somehow?
I am having issues with `seeking` in a `<video />` due to `chromes` requirement of `byte serving`

**Comment by dr-dimitru** [comment]
@FinnFrotscher yes, add `?play=true` query to the file URL

**Comment by dr-dimitru** [comment]
You can test it with any video/audio file at files.veliov.com

**Comment by FinnFrotscher** [comment]
adding `?play=true` doesnt work for me. neither on my app nor on yours.

btw. Nice website!

**Comment by FinnFrotscher** [comment]
I am using chrome.
On firefox - no problem

**Comment by dr-dimitru** [comment]
What format are trying to make work?

**Comment by FinnFrotscher** [comment]
webm

**Comment by dr-dimitru** [comment]
Should be [supported](http://caniuse.com/#search=webm).
What actually error/misbehaviour is?
Could you check request/response headers when you're do time seeking?

**Comment by FinnFrotscher** [comment]
The indicator for `currentTime` on the videoplayer stays at the beginning until the video has played through once. Then it jumps to the end. afterwards I can seek asf. 
The player does not display any buffering.

**Comment by FinnFrotscher** [comment]
`<video autoPlay controls preload ref='video'src={this.props.video.link()+'?play=true'} type='video/webm' />`

**Comment by FinnFrotscher** [comment]
[like this](http://imgur.com/kzvJfYA)

**Comment by dr-dimitru** [comment]
Use `source` element inside `video` with content type
Like here: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/client/file/file.jade#L60

Try various setups with or without `preload`.
Is same video plays well on files.veliov.com?

**Comment by FinnFrotscher** [comment]
No. same error on files.veliov.com
And I tried the `source` element. didnt work

**Comment by dr-dimitru** [comment]
Works well on: https://files.veliov.com/kYcmiZ2LekSoSxx5F
Looks like your video has no key-frames or something else is wrong with its meta-data

**Comment by FinnFrotscher** [comment]
Ok I will investigate in that direction.

**Comment by FinnFrotscher** [comment]
Yes that seems to be the problem. But i cant figure out how to fix it. Can you point me into a direction>
