### ISSUE TITLE
storagePath based on file.size

### ISSUE THREAD

**Issue by jonathanredford** [VeliovGroup/Meteor-Files#228]
I commented in #225 but didn't want to hijack that thread and I realised my situation is a little different in that I am able to statically define storagePath but what I need is for a file to go to a specific folder based on it's attributes, in this case file size.

Here is what I have so far. It's simple but it is working as per expected.

I've defined two collections where I want the files to end up:

```
LargeFiles = new FilesCollection({
  storagePath: '/example/folder/large/',
  collectionName: 'LargeFiles',
  allowClientCode: false
});

SmallFiles = new FilesCollection({
  storagePath: '/example/folder/small/',
  collectionName: 'SmallFiles',
  allowClientCode: false
});
```

I've then defined the main collection which all files are uploaded to and used `onAfterUpload` to load the files into one of the other collections based on file size.

```
AllFiles = new FilesCollection({
  storagePath: '/example/folder/drop/',
  collectionName: 'AllFiles',
  allowClientCode: false,
  onAfterUpload: function(fileRef) {
    var assetURL = 'http://localhost:3000' + fileRef._downloadRoute + '/' + fileRef._collectionName + '/' + fileRef._id + '/original/' + fileRef._id + '.' + fileRef.extension;
    if(fileRef.size <= 10485760) {
      SmallFiles.load(assetURL);
    } else {
      LargeFiles.load(assetURL);
    }
  }
});
```

Are there any issues or potential problems with moving files around this way? From what I can tell it's a similar method used to move files to S3 - https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration

**Comment by dr-dimitru** [comment]
Yes, there is no problem to move file this way. Currently this is recommended way to move files after upload.
You just need to [`fs.rename`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_rename_oldpath_newpath_callback) and update `path` property in MongoDB

**Comment by jonathanredford** [comment]
Great, thanks @dr-dimitru
