### ISSUE TITLE
onBeforeRemove always receives a cursor with all files

### ISSUE THREAD

**Issue by macrozone** [VeliovGroup/Meteor-Files#229]
In the documentation, it says that it should receive a cursor which contains every file to remove, but this cursor always returns all documents, no matter how collection.remove is called

In the documentation, its also written, that this.file should point to the file to remove, but that value is always null. But because it can handle multiple file, this.file can never be correct.

Maybe we should rethink this. Shouldn't it be called once per file? Then, it would be mucj easier to understand.

**Comment by dr-dimitru** [comment]
Hi @macrozone ,

Good suggestion. Could you share your code which causes cursor to have all documents?

And there is no `this.file` in `onBeforeRemove`

**Comment by macrozone** [comment]
@dr-dimitru anyone:

```
MyFileCollection.remove(fileId);
MyFileCollection.remove({_id: fileId});
MyFileCollection.remove({});
```

all of them trigger onBeforeRemove with a cursor that contains all documents.

concerning `this.fileId`, its mentioned in the docs: https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor#use-onbeforeremove-to-avoid-unauthorized-remove

**Comment by dr-dimitru** [comment]
My bad, docs is fixed.

I'll update you about this issue later after investigation

**Comment by dr-dimitru** [comment]
Hi @macrozone 
Can not reproduce original issue `onBeforeRemove always receives a cursor with all files`.

On my end only `MyFileCollection.remove({});` return all cursors, *as it supposed to*

Could you explain more?

**Comment by dr-dimitru** [comment]
@macrozone just released new version, please update and let me know how it is going.

**Comment by dr-dimitru** [comment]
Hi @macrozone ,

Any chance for reproduction of original issue?

**Comment by dr-dimitru** [comment]
Closed due to issue owner silence

**Comment by macrozone** [comment]
I had no issue with that anymore, sorry for beeing silent about it and thanks for your efforts
