### ISSUE TITLE
link() on FileCursor always returns localhost:3000 as base url instead of the actual base url

### ISSUE THREAD

**Issue by sammarshall61** [VeliovGroup/Meteor-Files#231]
When calling link() on a FileCursor it always returns a url starting with localhost:3000. So it breaks when uploading to my EC2 instance. Is there a way to configure the base URL for this? I can't find it if there is

**Comment by dr-dimitru** [comment]
you may use any custom property on `meta` object
`link()` always points to origin domain as this will let you use `interceptDownload` to control serving flow

**Comment by dr-dimitru** [comment]
Hi @sammarshall61 ,

Have you figured out how to fix this?

**Comment by deepupathak** [comment]
I have the same problem

**Comment by dr-dimitru** [comment]
@sammarshall61 @deepupathak 
Could you please provide your current code you're using, its result, and expected result.

**Comment by sammarshall61** [comment]
I think my issue was that I wasn't setting the root_url environment variable correctly, cheers!

**Comment by deepupathak** [comment]
I think, it may be due to root_url environment variable. I'll set it and if any problem let you know.

**Comment by dr-dimitru** [comment]
@deepupathak good

**Comment by j1016h** [comment]
Is this the right way to set a ROOT_URL?

JS file under server folder:
Meteor.startup(function() {
    process.env.ROOT_URL = 'http://haojia.space:3000';
});

**Comment by dr-dimitru** [comment]
```shell
ROOT_URL="http://haojia.space:3000" meteor
```

**Comment by j1016h** [comment]
Thanks @dr-dimitru 
Have another question, maybe silly, If video and regular project are in different domain. How should I handle it?

**Comment by dr-dimitru** [comment]
Is both projects meteor-based? What "video project" and "regular project", what the difference?

**Comment by j1016h** [comment]
I just came up this concern. 
What is the solution if both are meteor based?
What is the solution if video project is other tech stack project?

**Comment by dr-dimitru** [comment]
1. Are they both on same physical/virtual machine?
 2. What are you using as proxy/web-server (*before node*)?
 3. Are project on different domain or subdomains?

Nginx + Phusion Passenger can easily solve most of that kind of tasks for you
