### ISSUE TITLE
how to show the preview of stored image ?

### ISSUE THREAD

**Issue by deepupathak** [VeliovGroup/Meteor-Files#233]
I successfully upload image to db but now i want to show that image at client side.
### So I have a question:
 How to show the preview of the stored images ?

**Comment by dr-dimitru** [comment]
What code you're currently using?
Usually it's done via `.link()` method

**Comment by deepupathak** [comment]
ok. got it.
I am using `.url()` method instead of `.link()` and it gives me an error.
Now problem solved.
Thanks.
now i am closing this thread.

**Comment by dr-dimitru** [comment]
@deepupathak I'm glad you solved it.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
