### ISSUE TITLE
some error in wiki 

### ISSUE THREAD

**Issue by h2y** [VeliovGroup/Meteor-Files#234]
<https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example>

the first code need `import {ReactMeteorData} from 'meteor/react-meteor-data';`

and the second need `import React from 'react';`

**Comment by dr-dimitru** [comment]
Hi @h2y ,

Thank you for notice, docs is updated.
Btw `import React from 'react';` is already exists or I'm looking at wrong place?

**Comment by h2y** [comment]
React miss define in the second code [FileIndividualFile.jsx](https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example#second-component-fileindividualfilejsx) in that page.

btw, thanks for the great project. :D

**Comment by dr-dimitru** [comment]
@h2y done.
Could you double-check this, please?

> btw, thanks for the great project. :D

Thank you for choice.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
