### ISSUE TITLE
File deleted while upload is ongoing

### ISSUE THREAD

**Issue by ck23onGithub** [VeliovGroup/Meteor-Files#237]
Good day,

First of all I'd like to thank you for this great package.

I have a question, though. While uploading a file, is there a method or function that is called when the file suddenly went missing?

Thank you.

**Comment by dr-dimitru** [comment]
Hi @ck23onGithub 

If any error appears upload is terminated with `abort` on client, which calls `abort` Meteor's method on server

**Comment by ck23onGithub** [comment]
Hi,

I tried using the `onAbort` in `insert`. it does not seem to work well for me.
Here is the code:

`uploadQuery = DATA_FILES.insert({
        file: file,
        streams: 'dynamic',
        chunkSize: 'dynamic',
        allowWebWorkers: true,
        onAbort: this.handleUploadAbort(),
        meta: {
          KF_SEQ: 1,
          KF_CSTMRCD: parseInt(fileDetails[2]),
          KF_BKNCD: parseInt(fileDetails[3]),
          KF_CSTMR_NAME: uploader,
          KF_UPLOAD_DT: new Date(),
          KF_KOUKAI_DATE: this.convertStringToDate(fileDetails[0]),
          KF_COMMENT: fileComment,
          KF_FILE_TYPE: parseInt(fileDetails[1]),
          KF_PWBS: fileDetails[4],
        },
      },
      false);`

**this.handleUploadAbort()** is a file within the class.

when I check it on debug using Chrome, it recognizes that **this.handleUploadAbort()** is a function. but I still get a `Match error` for the `onAbort`

**Comment by ck23onGithub** [comment]
Hi,

I'd like to make an update on my progress regarding this issue that I encounter.

I was able to use the `onAbort` of the `insert` command. The issue now is that it doesn't seem to be consistent. There are times that it calls the function in 'onAbort' and sometimes it does not.

I found out that when an error occurs while the upload is ongoing (the file went missing while uploading, in my case), it triggers the following:
`onUploaded`
`onAbort`
`onError`
`onEnd`
I forgot the specific order, but all of those are triggered. but then, as i mentioned, it does not do it all the time. there seemed to be a specific line of codes for it to be able to successfully catch the error.

**Comment by ck23onGithub** [comment]
The image below are `console.log`s that I inserted in the `onProgress` event. i think once aborted, it does not trigger the `onProgress` anymore. but i also inserted a `console.log` in `onAbort` but as shown below, nothing was called.

![doesnotabort](https://cloud.githubusercontent.com/assets/22335710/18743470/c01ce3fe-80eb-11e6-8a38-ac618a03b5fa.PNG)

![codesnippet](https://cloud.githubusercontent.com/assets/22335710/18743620/76863ed8-80ec-11e6-91b7-b3329a8db669.PNG)

I'm sorry for asking too many questions and I tried looking for other solutions but can't find one.

Thank you

**Comment by dr-dimitru** [comment]
> I tried using the onAbort in insert. it does not seem to work well for me.

The context of `FileUpload` will be binded to `onAbort` function.

1. Try to avoid double arrow functions, as it changes it's context
2. Try same code with event style
3. Use `debug` mode and post logs from both Server and Client here

**Comment by ck23onGithub** [comment]
Thanks.

I'll try what you suggested and give you an update as soon as im done.

**Comment by dr-dimitru** [comment]
Hi @ck23onGithub ,

Any news on your end?

**Comment by ck23onGithub** [comment]
Sorry, I am not able to try this the past few days. I'll post an update as soon as I am done testing them.

Thanks

**Comment by ck23onGithub** [comment]
Hi @dr-dimitru ,

I tried the suggestions you gave me.

> 1. Try to avoid double arrow functions, as it changes its context
> 2. Try same code with event style
> 3. Use debug mode and post logs from both Server and Client here

Here are the steps I did in my app:

1. select a file for upload
2. click upload button
3. while uploading, delete the file

Here's a caption of client side and server side logs:
![logsclientserver](https://cloud.githubusercontent.com/assets/22335710/18822112/139a9bca-83df-11e6-87be-3f7693decf11.PNG)

I think there should be an error somewhere that says that the resource is gone. But no errors are shown in the logs both from client side and server side.

Thank you

**Comment by dr-dimitru** [comment]
Hi @ck23onGithub 
 1. I don't see the `debug` logs on Client nor Server console. Only some custom logs
 2. Why would you delete file on server during upload?

**Comment by dr-dimitru** [comment]
I thought you issue what file is gone missing during upload, not you were removing file during upload....

**Comment by ck23onGithub** [comment]
I am trying to replicate a scenario where a file might be lost while the upload is ongoing. that's why i delete the file while the upload is happening. i know it may sound unnecessary, but I'm just trying to catch all possible errors that may occur.

> I don't see the debug logs on Client nor Server console. Only some custom logs
I'm sorry if i got the wrong logs. but as far as i can see, i dont think there are any logs when the file suddenly get lost while it is being uploaded.

is there anyway to make sure that the file you are uploading wont be deleted while you are not yet done uploading it? like locking the file or making a copy of it temporarily and deleting the copy immediately after the upload is done?

**Comment by dr-dimitru** [comment]
>  am trying to replicate a scenario where a file might be lost while the upload is ongoing. that's why i delete the file while the upload is happening. i know it may sound unnecessary, but I'm just trying to catch all possible errors that may occur.

Okay, there should be an error like: "session terminated, please start upload again"

> I'm sorry if i got the wrong logs. but as far as i can see, i dont think there are any logs when the file suddenly get lost while it is being uploaded.

It should put some light on why you're not getting proper error code.

> is there anyway to make sure that the file you are uploading wont be deleted while you are not yet done uploading it? like locking the file or making a copy of it temporarily and deleting the copy immediately after the upload is done?

Currently it only makes sure file is exists and memory is flushed to storage. As, one of the main initial features was low memory usage on server.

**Comment by ck23onGithub** [comment]
`Okay, there should be an error like: "session terminated, please start upload again"`

This should appear every time i delete the file when upload is ongoing, right? whether i have a specific function for `onAbort` or none?

**Comment by dr-dimitru** [comment]
> This should appear every time i delete the file when upload is ongoing, right?

Yes, upload should be terminated with this error

> whether i have a specific function for onAbort or none?

Any exception will cause `onAbort` to be triggered.

**Comment by ck23onGithub** [comment]
> Yes, upload should be terminated with this error

Then maybe something is not right in my app. because no errors are showing whenever I try to do this scenario. the progress simply stops whenever the file is deleted.

**Comment by ck23onGithub** [comment]
Hi!

I think i got it to work. it passed through my console logs inside the `onAbort` function. Though i really dont know now the root cause is.

**Comment by dr-dimitru** [comment]
@ck23onGithub that's why I need to see `debug` logs

**Comment by dr-dimitru** [comment]
Great, glad you've solved it

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)

**Comment by ck23onGithub** [comment]
I'm sorry but where do i get those logs? the logs that i make that is for the client side are showing in the debug tool of chrome. the server side logs are shown in the command prompt. if there are any errors in the client side, it displays in the debug tool of chrome. if there is something wrong in the backend, it displays in the command prompt. am i missing something? because right now, again, it does not display any console logs i put in `onAbort`. i'm thinking why it does not call that function all the time. if it is triggered, like you said, it should display my custom logs in the debug tool of chrome.

may i know what is the order of functions being called whenever upload function is aborted? i saw last night that the order is `abort` -> `end` -> `error`. is this correct?

**Comment by dr-dimitru** [comment]
> I'm sorry but where do i get those logs? i tried to run the project on debug mode and attached a screenshot of the console from the debug watcher but i think thats not what you were asking me.

Just pass `debug: true` to `FilesCollection` Constructor

> it displays in the command prompt. am i missing something?

No, you're just using some other debug options, I need `debug: true` in `FilesCollection` Constructor

**Comment by ck23onGithub** [comment]
I think its fine now. The problem could have been from the build. it does not reflect the code immediately.

Thanks for the time. I really appreciate it

**Comment by ck23onGithub** [comment]
Sorry. I have another question regarding this. what if **testfile.txt** exists in file system and i uploaded it again. what will happen?

**Comment by dr-dimitru** [comment]
I guess we moving it to #244 , right?

**Comment by ck23onGithub** [comment]
Hi again :smile: 

I have something.

What i did is:

1. upload a file
2. delete the file in my local storage while upload is ongoing
3. and this is what i got

![noabort](https://cloud.githubusercontent.com/assets/22335710/18938818/02e9b3b4-862e-11e6-8358-1e33b52f17e1.PNG)

and then i restart the app and cleared the file system then tried again
1. upload a file
2. delete the file in my local storage while upload is ongoing
3. and this is what i got (this time in the command prompt)

![noabortcmd](https://cloud.githubusercontent.com/assets/22335710/18938828/1dd0b222-862e-11e6-809a-f30a8b373a9a.PNG)

I think something is missing.

next, i tried uploading a file. no interruptions this time

1. upload file
2. success

then,

3. upload a file
4. delete the file in the local storage and this is what i got

![bigfilenoabort](https://cloud.githubusercontent.com/assets/22335710/18939180/15930b70-8631-11e6-88ea-f25e5f192f09.PNG)
![bigfilenoabort2](https://cloud.githubusercontent.com/assets/22335710/18939182/192a8ce0-8631-11e6-8323-d69823d1a9c4.PNG)

it should call abort after i delete the file, right? i tried waiting for more than a minute because i set the `continueUploadTTL: 60`. but nothings appears.

**Comment by ck23onGithub** [comment]
Hi,

The `onAbort` method works on my last update. But as of now, something seems to be off. There are times that the error does not trigger when the file suddenly disappears. I checked the logs before with `debug: true` for the filesCollection. After the file is gone, the logs stop and no error is triggered.

do you have any idea to why this happens? is this a bug of Meteor itself?

Here are the logs that I got.

part1
![bigfilenoabort](https://cloud.githubusercontent.com/assets/22335710/18978881/0748fd40-86f9-11e6-98b1-623f715b8689.PNG)
part2
![bigfilenoabort2](https://cloud.githubusercontent.com/assets/22335710/18978887/0eddeaf2-86f9-11e6-89d7-436552eee81e.PNG)

and here's another one
![noabort](https://cloud.githubusercontent.com/assets/22335710/18978901/2625defe-86f9-11e6-9e5e-7dfbc271bf44.PNG)
