### ISSUE TITLE
Unable to find file documents on the client

### ISSUE THREAD

**Issue by RavDanny** [VeliovGroup/Meteor-Files#238]
I'm using Meteor-Files version 1.7.3 and Meteor v. 1.4.1.1.
When I upload files, they show up in the mongodb collection, but not in the client.

Here is my shared code:

```
this.NetCdfFiles = new FilesCollection({
  collectionName: 'NetCdfFiles',
  storagePath: '/pals/data',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    // Allow upload of nc and r files only
    if (/nc/i.test(file.extension)) {
      return true;
    } else {
      return 'Only NetCDF files allowed';
    }
  }
});

if (Meteor.isClient) {
  Meteor.subscribe('files.netCdfFiles.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.netCdfFiles.all', function() {
    return NetCdfFiles.collection.find().cursor;
  });
}
```

In the mongodb cli it shows 7 documents.

But in my browser console:
```
NetCdfFiles.find().fetch()
[]
```
and mongol says there are 0 documents.

**Comment by dr-dimitru** [comment]
Hi @RavDanny 

Missed this issue as it was closed. Is it solved?

**Comment by RavDanny** [comment]
Yes. Thank you.

**Comment by dr-dimitru** [comment]
Great, please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)

**Comment by larzKke** [comment]
@RavDanny Hi, can u tell me how you solved your problem? I have the same problem at the moment...

**Comment by dr-dimitru** [comment]
@larzKke @RavDanny 
I guess publish/subscribe is solved it, isn't it?

**Comment by larzKke** [comment]
@dr-dimitru hm, I did it like in your example:

```
if (Meteor.isServer) {
  Images.denyClient();
  Meteor.publish('files.images.all', function () {
    return Images.find().cursor;
  });

} else {

  Meteor.subscribe('files.images.all');
}
```

```
Template.file.helpers({
  imageFile: function () {
    return Images.findOne();
  }
});
```

```
<template name='file'>
  {{#with imageFile.with}}
  Image:  <img src="{{link}}" alt="{{name}}" />
  {{else}}
    Loading Image...
  {{/with}}
</template>
```

**Comment by dr-dimitru** [comment]
@larzKke have you seen [this answer](https://github.com/VeliovGroup/meteor-autoform-file/issues/5#issuecomment-251947156)?

**Comment by dr-dimitru** [comment]
@larzKke use `debug` to see what actually happens on server when you publish data. Or add `console.log` to see if there is data in subscription.

**Comment by larzKke** [comment]
@dr-dimitru the first answer didn't changed anything

I changed the template and helper to 
```
  {{#if imageFile.count}}
    {{#each file in imageFile}}
      Image:  <img src="{{file.path}}" alt="{{file.name}}" />
    {{/each}}
  {{else}}
      Loading Image...
  {{/if}}
```
```
Template.file.helpers({
  imageFile: function () {
    return Images.find();   <--  findOne() didn't work, idk why 
  }
});
```

**Comment by dr-dimitru** [comment]
`findOne() return 'undefined'` - Is there a chance you return data to template before subscription is ready? Do you wait for subscription to be ready?

Btw, `.find()` [never returns undefined](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1462). It may return empty cursor, only `.findOne()` ,ey return false value.
