### ISSUE TITLE
Uploading mp4 as dataURI from Cordova (iOS) results in a corrupt / un-playable file

### ISSUE THREAD

**Issue by trymbill** [VeliovGroup/Meteor-Files#239]
I've been battling this one for a few days now so I thought I'd try and reach out for help.

I'm developing an app that records video on the users iOS device and saves it. I get a mp4 video file from the device and I've tripe checked to make sure that file is OK and it is, it plays perfectly fine when I download the contents of my device in Xcode.

But then, when I try and upload the file with Meteor-Files the file doesn't play. Here's my code:

```js
// Creating the collection
Collections.videos = new FilesCollection({
  debug: true,
  throttle: false,
  storagePath: 'assets/app/uploads/videos',
  collectionName: 'videos',
  allowClientCode: false
});

// Function to fetch a file from meteor's local web server in base64
function getBlobURL(url, callback) {
  var xhr = new XMLHttpRequest();
  xhr.responseType = 'blob';
  xhr.onload = function() {
    var reader = new FileReader();
    reader.onloadend = function() {
      callback(reader.result);
    }
    reader.readAsDataURL(xhr.response);
  };
  xhr.open('GET', url);
  xhr.send();
}

var file = '/local-filesystem' + url; // /local-filesystem because Meteor serves local files for Cordova through a local web server

getBlobURL(file, function (base64video) {
  console.log(base64video.substr(0,200)); // logging first 200 characters of the video base64 string (see below)
  Collections.videos.insert({
    file: base64video,
    isBase64: true,
    fileName: 'testing123.mp4',
    onUploaded: function (err, fileRef) {
      console.log('Video uploaded:', err, fileRef);
    },
    onError: function (err, fileData) {
      console.error('Error when uploading:', err, fileData);
    }
  });
});
```

Here's an example of the first 200 characters of a base64 string from a video:

```
data:video/mp4;base64,AAAAFGZ0eXBxdCAgAAAAAHF0ICAAAAAId2lkZQAAAABtZGF0AMxABwDume5NmehMFWjKCUoVE58eL543GCwAdL/OAAAAAHYNjhAP+J6AA4H/lgHx77IAAFeL/F9oAAHS+b1OzAAD5D6brvIAAAAfb9P3vx/73uAAAA/zf2b9M4v9n92AAA
```

I'm completely lost as to why this doesn't work and would love any help I can get :)

**Comment by dr-dimitru** [comment]
Hi @trymbill ,

We have faced this issue previously, but this was fixed.
 1. Make sure you're on the latest release
 2. Is uploaded file plays locally (not over http)?
 3. Could you analyze uploaded video file in VLC to find what actually went wrong with file?

**Comment by trymbill** [comment]
@dr-dimitru Oh sorry about a re-post then, I tried searching the issues db and couldn't find anything.

1 - ```$ meteor list ... ostrio:files 1.7.3```

2 - Yes, the uploaded file plays locally both over http through a video element within my application template and also when I download the application container from Xcode. So the file seems to be fine until it's read as data url and sent through Meteor-Files.

3 - Here's the tail of VLC trying to play the file:
```
avcodec debug: trying url: /Users/.../.../.../.meteor/local/build/programs/server/assets/app/uploads/videos/c7eu8fFZByqRBS8Xn.mp4
avcodec debug: CPU flags: 0x0107d3db
avcodec debug: detected format: mov,mp4,m4a,3gp,3g2,mj2
avcodec debug: Trying to seek too far : EOF?
avcodec debug: Trying to seek too far : EOF?
avcodec error: Could not open /Users/.../.../.../.meteor/local/build/programs/server/assets/app/uploads/videos/c7eu8fFZByqRBS8Xn.mp4: Unknown error
ps warning: this does not look like an MPEG PS stream, continuing anyway
core debug: using demux module "ps"
core debug: looking for a subtitle file in /Users/.../.../.../.meteor/local/build/programs/server/assets/app/uploads/videos/
core debug: looking for meta reader module matching "any": 2 candidates
lua debug: Trying Lua scripts in /Users/.../Library/Application Support/org.videolan.vlc/lua/meta/reader
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/reader
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/reader/filename.luac
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/reader
core debug: no meta reader modules matched
core debug: `file:///Users/.../.../.../.meteor/local/build/programs/server/assets/app/uploads/videos/c7eu8fFZByqRBS8Xn.mp4' successfully opened
ps warning: garbage at input, trying to resync...
macosx warning: variable stereo-mode doesn't exist or isn't handled
core debug: EOF reached
core debug: finished input
core debug: removing module "ps"
core debug: removing module "record"
core debug: removing module "filesystem"
core debug: dead input
core debug: changing item without a request (current 1/2)
core debug: nothing to play
macosx debug: releasing old sleep blocker (3385)
macosx debug: prevented sleep through IOKit (3466)
macosx debug: releasing sleep blocker (3466)
```

**Comment by dr-dimitru** [comment]
@trymbill 

 1. Good
 2. I meant try to check uploaded file (locally on server, or testing machine)
 3. Is it fails or keeps playing?

In terms of testing try to set in `.insert()` method:
```js
{
  streams: 1,
  chunkSize: data.length * 2
}
```

**Comment by trymbill** [comment]
@dr-dimitru 

2 - I thought you meant the original file, the one that's on the local Cordova Meteor web app (https://github.com/meteor/cordova-plugin-meteor-webapp). The file that's uploaded by Meteor-Files to .meteor/local/build/programs/server while running in development, that's the file I've been checking and that file that doesn't work
3 - It fails, never starts playing
4 - Tried adding streams and chunksize, still results in a corrupt file

**Comment by dr-dimitru** [comment]
@trymbill 
> Tried adding streams and chunksize, still results in a corrupt file

Hmm.. at this point you need to make sure the *String* you're getting from `getBlobURL` is correct.
Could you just put it into `<video src="[[base64here]]"></video>` and check if its playing

**Comment by trymbill** [comment]
@dr-dimitru Thanks for the quick response and help, really appreciate it!

Tried tossing the base64 encoded string straight into video element and it failed playing. The error code returned is MEDIA_ERR_SRC_NOT_SUPPORTED. So I guess that points a finger at the ```getBlobURL``` function.

I'm not too familiar with FileReader, can you see something wrong with that code or do you have an example of a way to get a base64 encoded string from xhr that works?

**Comment by dr-dimitru** [comment]
First, you need to make sure your device supports `mp4`
But, previously you have mention, this `mp4` file is captured by device (*so, I assume it as supported*). Another thing here - are you sure it returns `mp4` file not other format?

**Comment by trymbill** [comment]
Yeah device definitely supports mp4 and is returning mp4. The file that the device returns works fine, that file plays OK but as soon as I try and encode it with base64 it's corrupt.

**Comment by dr-dimitru** [comment]
This question is out of the scope of this package.
Could you please do this research by your own and get back here.
Then I can share your successful experience in our wiki, if you wish

**Comment by dr-dimitru** [comment]
@trymbill 
[Here is SO thread](http://stackoverflow.com/questions/29192327/get-base64-of-audio-data-from-cordova-capture) about audio file. But looks like same may be applied to video.

You need to get video right from `navigator.device.capture.captureVideo` callback

Let me know if it helps

**Comment by dr-dimitru** [comment]
@trymbill 

Actually if you will use `navigator.device.capture.captureVideo` no need to convert it to Base64 (*as it will be very inefficient*) you can just pass file(s) returned from callback to `.insert()`

**Comment by trymbill** [comment]
@dr-dimitru Thanks for the idea and help.

I'm actually not able to use capture.captureVideo because I need to record video without the user interacting with the device. The app is a security application that starts and stops recording of video from the camera based on motion being sensed, so the capture plugin for cordova isn't going to work.

I'm currently using this plugin to record video in the background: https://github.com/jamesla/backgroundvideo - it uses AVCaptureMovieFileOutput to grab the buffer and save it as an mp4. I don't think I can get a file object back from it that Meteor-Files would be able to use in ```.insert()``` but I might be wrong ...?

**Comment by dr-dimitru** [comment]
Docs says:

> cordova.plugins.backgroundvideo.stop() will return path

Have you tried to turn it into file?

**Comment by trymbill** [comment]
You mean turning the path into a file object? Yeah I tried that, came out
corrupt as well.

I'm starting to wonder if it's the local web app that meteor runs for ios,
if that's not returning the correct data through xhr requests.

**Comment by dr-dimitru** [comment]
Is there any other ways to get `background video`, without 3rd party packages?
I believe there is should be solution which returns raw binary.

**Comment by dr-dimitru** [comment]
Btw, what is returned in `xhr.response`? is it a file or *Blob*? If so, it's easy to turn *Blob* into *File* and try to upload it. No need to initiate `FileReader` to get *Base64* string

**Comment by trymbill** [comment]
Thanks for all the help @dr-dimitru.

It ended up being a pretty silly issue with the meteor local web app running for iOS which I managed to fix with a setTimeout. Seems like the output of AVCaptureDevice wasn't fully closed off when I XHR requested the file from the local web app. So I wasn't getting the full file. Waiting for 2 seconds before fetching the file works (almost) without issues.

Now I'm dealing with memory problems and the app crashing during the upload process ... but that's definitely not related to Meteor-Files so I'll go ahead and close this issue and again thank you for all the help and ideas!

**Comment by dr-dimitru** [comment]
> Now I'm dealing with memory problems and the app crashing during the upload process ... but that's definitely not related to Meteor-Files so I'll go ahead and close this issue and again thank you for all the help and ideas!

 1. Switch to `http` transport
 2. Play with `chunkSize`, and try to set `streams` to `1`
