### ISSUE TITLE
What is Meant by production / development? I have setup NODE_ENV=production

### ISSUE THREAD

**Issue by jasonify** [VeliovGroup/Meteor-Files#240]
I am having a hard time understanding what you mean by setting production? Can you please provide an example in the documentation?

on shell:
export NODE_ENV=production

console.log('Meteor.isProduction', Meteor.isProduction);

but I still see the files being uploaded to .meteor 

I searched the entire repo for "production" and found nothing.

**Comment by jasonify** [comment]
Also, is there a way to add a 'hook' / 'callback' for the file that just got uploaded and what name it was just given? 

Thanks

**Comment by dr-dimitru** [comment]
1. You're free to select any path for file storage on both production and development or any other value of `NODE_ENV` as this lib don;t rely on it. Just set `storagePath` to whatever you need
 2. `onAfterUpload` event will return record from MongoDB with `_path` property, which eventually points to file

**Comment by dr-dimitru** [comment]
@jasonify any news on your end?

**Comment by jasonify** [comment]
@dr-dimitru 

I will have to try again but what I meant was this part of the docs:
------------------------------------
Where files is stored by default?: by default if config.storagePath isn't passed into Constructor it's equals to assets/app/uploads and relative to running script:

On development stage: yourDevAppDir/.meteor/local/build/programs/server, note: all files will be removed as soon as your application will rebuild or you run meteor reset. To keep you storage persistent use absolute path outside of your project folder, we recommend to use /data directory

On production: yourProdAppDir/programs/server
----------------------------------------

What is meant by this? I find my files keep getting put into .meteor folder which gets deleted. Does this mean I have to hard code the absolute path to my meteor project when in production?

**Comment by jasonify** [comment]
2) onAfterUpload, is this a property that gets passed in to the initiation object? Where can I read more about it.

Thanks

**Comment by dr-dimitru** [comment]
Hey @jasonify ,

Thanks for clarification.
So, 
 1. The `development` it is stage when you run `meteor`;
 2. The `production` is when you run your app as regular node.js app after you do `meteor build`

**Comment by dr-dimitru** [comment]
Hey @jasonify , could I assume this thread as solved?

**Comment by dr-dimitru** [comment]
Closed due to silence
