### ISSUE TITLE
Remove templating and other blaze-depencenies

### ISSUE THREAD

**Issue by macrozone** [VeliovGroup/Meteor-Files#242]
when using this package without blaze, it will bloat the bundle because it loads templating, blaze, jquery and so on.

I think it's not needed to have this depencency, can we remove it or make it optional?

**Comment by dr-dimitru** [comment]
It comes with default template helper `fileURL`. Removing `templating` package will break it.

**Comment by macrozone** [comment]
Better declare it as weak-dependency and check if Template is there:

```
if(Meteor.isClient && global.Template) {

}
```

or here in coffeescript: ` Template?.registerHelper `

**Comment by dr-dimitru** [comment]
@macrozone thank you for suggestion, will use it in further release
