### ISSUE TITLE
ES6 Cannot find module 'meteor:package/ostrio/files'.

### ISSUE THREAD

**Issue by triasrahman** [VeliovGroup/Meteor-Files#243]
I'm having an issue:

How to implement on ES6 project? I've already put :
```
import { FilesCollection } from 'meteor/ostrio:files';
```

But at the console always showing `Cannot find module 'meteor:package/ostrio/files'.`

How I can call that class? Should I put typings definitions? Please help.

Thanks,

**Comment by dr-dimitru** [comment]
Have you installed package itself?

**Comment by dr-dimitru** [comment]
Hmm... weird..
 1. Put all default packages (*without* `:`) on top of `.meteor/packages` file
 2. Add `console.log(FilesCollection)` at any file in `/lib` folder (to see if it's available in global scope)
 3. As option use it without ES6 import, as `FilesCollection` already in global scope

**Comment by triasrahman** [comment]
Here is my `.meteor/packages` file:

```
meteor-base@1.0.4             
mobile-experience@1.0.4       
mongo@1.1.12                   
blaze-html-templates@1.0.4    
reactive-var@1.0.10            
jquery@1.11.9                  
tracker@1.1.0                 

standard-minifier-css@1.2.0   
standard-minifier-js@1.2.0    
es5-shim@4.6.14                
ecmascript@0.5.8              

check@1.2.3
reywood:publish-composite
meteortypescript:compiler
shell-server
accounts-base
ostrio:files
```

How can `FilesCollection` will be a global variable? When I try to call the variable on browser console, the output is:
`Uncaught ReferenceError: FilesCollection is not defined`

Thanks,

**Comment by dr-dimitru** [comment]
> How can FilesCollection will be a global variable? When I try to call the variable on browser console, the output is:
> Uncaught ReferenceError: FilesCollection is not defined

Must be in global scope, if it isn't - something went wrong. What `Meteor.Files`

**Comment by dr-dimitru** [comment]
Hey @triasrahman have you solved it with `Meteor.Files`?

**Comment by triasrahman** [comment]
Hi @dr-dimitru, I still didn't understand. What do you mean solving with `Meteor.Files` ?

**Comment by dr-dimitru** [comment]
@triasrahman You can use `Meteor.Files` instead of `FilesCollection`

**Comment by triasrahman** [comment]
I've tested to use it but an error showed:
`Property 'Files' does not exist on type 'typeof Meteor'`

But when I try to call `Meteor.Files` on console, there is a function.

Anyway, I'm using TypeScript for it. Is that the problem?

**Comment by dr-dimitru** [comment]
> But when I try to call Meteor.Files on console, there is a function.

Server ot Client? So you can use it, right?

> Anyway, I'm using TypeScript for it. Is that the problem?

No, idea. Never used TS with Meteor

**Comment by triasrahman** [comment]
I've just solved it by creating typings definition, it's because I'm using TypeScript.

After that, I've got an error when trying to upload. 

```
Images.insert is not a function
```

I follow your tutorial for uploading an image:

```
    // As plain base64:
    Images.insert({
      file: photo,
      isBase64: true, // <— Mandatory
      fileName: 'pic.jpg', // <— Mandatory
      type: 'image/jpg' // <— Mandatory
    });
```

The `Images` object is correct, it's a `FilesCollection` class. What's wrong?

Thanks!

**Comment by dr-dimitru** [comment]
Here is almost full TS definition for this package: https://github.com/VeliovGroup/Meteor-Files/issues/226

**Comment by triasrahman** [comment]
@dr-dimitru thanks!

Anyway, I just realized that I did `Images.insert()` on server side. It must be on client side right?

I'm using `meteor-client-side` (https://github.com/idanwe/meteor-client-side) for my Ionic project. Is it possible to upload/store image that triggered using Meteor methods? So the image data will be passed from client to server using method, and then the server store the image.

Thanks,

**Comment by dr-dimitru** [comment]
> Anyway, I just realized that I did Images.insert() on server side. It must be on client side right?

Right, on server there is bunch of methods like `load`, `addFile`, `write`


>  Is it possible to upload/store image that triggered using Meteor methods? So the image data will be passed from client to server using method, and then the server store the image.

Yes, you just pass it as Base64 or TypedArray to method, then write to FS, but in this case no need to use this lib

**Comment by triasrahman** [comment]
Where I can find the docs for `addFile` and `write` ?

**Comment by dr-dimitru** [comment]
[Wiki](https://github.com/VeliovGroup/Meteor-Files/wiki)
[addFile](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile)
[write](https://github.com/VeliovGroup/Meteor-Files/wiki/Write)

**Comment by triasrahman** [comment]
@dr-dimitru thanks :)

**Comment by dr-dimitru** [comment]
Do not heistate to ask more questions, thank you for a choice.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
