### ISSUE TITLE
Rollback from File System

### ISSUE THREAD

**Issue by ck23onGithub** [VeliovGroup/Meteor-Files#244]
Hi,

This is the scenario.

1. I upload a file
2. Before it finishes uploading, i delete it
3. After cancelling the **_upload_**, i checked the file system and the file is there, it is corrupt.

the file is not recorded in the database. this is OK.

How do i delete the file? I need to delete it because it won't let me upload a file with the same name in the same path.

**Comment by dr-dimitru** [comment]
> Before it finishes uploading, i delete it
> After cancelling the delete

How do you canceling delete, after deleting the file 0_o?

>  it is corrupt.

It is not corrupt but partly uploaded.

> I need to delete it because it won't let me upload a file with the same name in the same path.

For this reason I will never suggest to hack the `namingFunction`. As by default it makes sure there is no files with same name at FS

I thing you're digging in cases which rarely possible to happen. I can not imagine the case file may be deleted from FS unless it fully uploaded, only FS corruption or malfunction may cause this.

**Comment by ck23onGithub** [comment]
> How do you canceling delete, after deleting the file 0_o?

I'm sorry. i mean **After cancelling the upload**.
I'll update my first post

**Comment by ck23onGithub** [comment]
> For this reason I will never suggest to hack the namingFunction. As by default it makes sure there is no files with same name at FS

So there is no way to delete the _**partly uploaded**_ file?

**Comment by dr-dimitru** [comment]
> So there is no way to delete the partly uploaded file?

There is `continueUploadTTL` - if upload is not finished it will be terminated and all chunks garbage-collected

**Comment by dr-dimitru** [comment]
From the docs:

> If upload is not continued during this time, memory used for this upload will be freed. And uploaded chunks is removed. Server will no longer wait for upload, and if upload will be tied to be continued - Server will return 408 Error (Can't continue upload, session expired. Start upload again.)

**Comment by ck23onGithub** [comment]
Thank you. I'll check this. I have not studied the whole package very well and I'm sorry for that. is there another way to asks questions other than posting here as an issue? obviously this is not an issue of the package itself

**Comment by dr-dimitru** [comment]
@ck23onGithub it's fine to ask here. So, am I answered on your question?

**Comment by ck23onGithub** [comment]
I think this should be fine. thanks, as always
