### ISSUE TITLE
No file in /data folder after "File successfully uploaded" message

### ISSUE THREAD

**Issue by aposidelov** [VeliovGroup/Meteor-Files#246]
Hi, I am trying to run basic example from: https://github.com/VeliovGroup/Meteor-Files#api-overview-full-api.  I have progress bar, Successful alert, a document in images collection but no file uploaded in /data folder. I create in a project's root folder:
/.meteor
/data
/imports
/packages
...
---
METEOR@1.4.1.1
ostrio:files@1.7.3
Here is a conctructor that I use:
```
export const Images = new FilesCollection({
  collectionName: 'Images',
  storagePath: '/data',
  allowClientCode: false, // Disallow remove files from Client
  debug: true,
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```
Here is a server message that I got after image upload with debug: true : the last line is some with [removed], is it ok?
![met-server-m](https://cloud.githubusercontent.com/assets/2487197/18994904/25b640cc-872a-11e6-819d-02c257619928.png)
Here is a document in images collection and I got:
![met-server-m2](https://cloud.githubusercontent.com/assets/2487197/18995119/21ecef12-872b-11e6-9f5b-e0a1d6cde3c7.png)

**Comment by dr-dimitru** [comment]
Have you tried to use windows slash?:
```js
let nodePath = Npm.require('path');
export const Images = new FilesCollection({
  collectionName: 'Images',
  storagePath: nodePath.sep + 'data',
  allowClientCode: false, // Disallow remove files from Client
  debug: true,
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```

> the last line is some with [removed], is it ok?

Absolutely - yes.

Anyways you've said you can not discover image in `/data` but you can see it in browser, or not?

**Comment by aposidelov** [comment]
Thanks, it was a problem with storagePath. Playing with slashes didn't help but I've setup absolute path to /data folder like this:
```
export const Images = new FilesCollection({
  collectionName: 'Images',
  storagePath: process.env.PWD + '/data/Images/',
  allowClientCode: false, // Disallow remove files from Client
  debug: true,
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```
and it works now

**Comment by dr-dimitru** [comment]
Hi @aposidelov ,

Using `process.env.PWD` means it's relative to the running process, not to the FS root.
To make it __real absolute__ use `/data`

**Comment by aposidelov** [comment]
I have a meteor project path: 
c:/xampp/htdocs/meteor/mytest 
and data folder inside like this: 
c:/xampp/htdocs/meteor/mytest/data
so if I use '/data' it saves images by: 
c:/data
and if I use process.env.PWD + '/data' it saves:
c:/xampp/htdocs/meteor/mytest/data

**Comment by dr-dimitru** [comment]
@aposidelov 

It's up to you. Can I assume it as solved?

**Comment by aposidelov** [comment]
yes, also for above two cases I checked image collection:
1) with '/data' document has a path:  **\\data\\KaSAagkcJD7gZZ2Qn.jpg** but image is uploaded into **c:/data**
2) with process.env.PWD + '/data' document has path: **C:\\xampp\\htdocs\\meteor\\mytest\\data\\Images\\GeZgGBWXB6jsFr7GW.jpg** and image is there as well

**Comment by dr-dimitru** [comment]
Looks good to me, isn't ?

**Comment by aposidelov** [comment]
right, it works in both cases, thank you for help!

**Comment by dr-dimitru** [comment]
@aposidelov great

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
