### ISSUE TITLE
Can't find Google cloud keyFilename location

### ISSUE THREAD

**Issue by Spanomaly** [VeliovGroup/Meteor-Files#247]
I'm having an issue with using the Google cloud upload on production.
In the demo code, for keyFileName we add a path to our Google cloud key.json.  That works fine on my local dev machine, but I can't figure it out once the app is compiled and deployed on production with mup.

If on my dev machine, my key is at <project root>/server/key.json

How does that translate to a file location on a deployed production machine?

**Comment by dr-dimitru** [comment]
Hello @Spanomaly ,

Use `/private` directory, it is stale.
From the [docs](https://guide.meteor.com/structure.html#special-directories):
> All files inside a top-level directory called private/ are only accessible from server code and can be loaded via the Assets API. This can be used for private data files and any files that are in your project directory that you don’t want to be accessible from the outside.

**Comment by Spanomaly** [comment]
Thanks @dr-dimitru , that works great.

**Comment by dr-dimitru** [comment]
@Spanomaly glad you've solved it

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by nikhilgoswami** [comment]
{ Error: ENOENT: no such file or directory, open meteor/local/private/googleStorageJson.json'
W20180829-19:10:30.627(5.5)? (STDERR)   errno: -2,
W20180829-19:10:30.627(5.5)? (STDERR)   code: 'ENOENT',
W20180829-19:10:30.627(5.5)? (STDERR)   syscall: 'open',
W20180829-19:10:30.628(5.5)? (STDERR)   path: '/.meteor/local/private/googleStorageJson.json' }

path for keyFilename: '../../../private/googleStorageJson.json'

Is there something I am missing?

**Comment by dr-dimitru** [comment]
@nikhilgoswami obviously the path is wrong. Try [`meteor-root`](https://atmospherejs.com/ostrio/meteor-root) packages to define path as absolute.

**Comment by nikhilgoswami** [comment]
This worked for me thanks

**Comment by dr-dimitru** [comment]
@nikhilgoswami glad it helped

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
