### ISSUE TITLE
import { Template } from 'meteor/templating';

### ISSUE THREAD

**Issue by Pierrix25** [VeliovGroup/Meteor-Files#248]
Hello,

I'm a Meteor beginner... I want try this simplest demo package. 

The import key word in main.js script is not recognized... i presume something is missing but i don't know what...

Thank you for your help.

Pierre.

**Comment by dr-dimitru** [comment]
make sure `ecmascript` package is installed

**Comment by Pierrix25** [comment]
Ok thank you. It works.

**Comment by dr-dimitru** [comment]
@Pierrix25 

Great, glad you've solved it
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
