### ISSUE TITLE
Filename in FS

### ISSUE THREAD

**Issue by FinnFrotscher** [VeliovGroup/Meteor-Files#251]
I save video files with:
```
var uploadData = {
        file: data,
        fileName: 'ID_'+_id+'_TRY_'+this.state.count+'.webm',
        isBase64: true,
        streams: 'dynamic',
        chunkSize: 'dynamic',
        meta: {_id:_id}
      }
      var uploadInstance = Videos.insert(uploadData, false);

```

and get returned an `obj` with:
```
fileId:"g9E3nXaYKDCWo5egN"
fileName:"ID_84f2eb0a163ebb2f81a10b01_TRY_3.webm"
```

In my `fs` the file is saved as `g9E3nXaYKDCWo5egN.webm`
I want it to be saved as `ID_84f2eb0a163ebb2f81a10b01_TRY_3.webm`

How do I do that?
Thank you very much.
Finn

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher 

You're looking for `namingFunction` passed to [`Constructor`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor). But I'm afraid it's not possible to implement what you want, moreover I wouldn't recommend to change default behaviour.

The `fileName` you've used - sets filename which returned by server, for example when file is being downloaded.

Same question is widely discussed in #100 and #117 , please read both threads.

**Comment by FinnFrotscher** [comment]
I will.
BTW I have a Bounty up on [bountify](https://bountify.co/mongodb-complex-query-design-2) thats about to expire. I solved the issue already, cant redeem the funds and you helped me A LOT! 
If you want you can claim it. A working answer is in the comments.

**Comment by dr-dimitru** [comment]
@FinnFrotscher thank you for support. Done.
I'm glad you found my help useful. Are you okay to be added to the [supporters](https://github.com/VeliovGroup/Meteor-Files#supporters) section?

**Comment by FinnFrotscher** [comment]
Yes of course.

**Comment by dr-dimitru** [comment]
@FinnFrotscher will you close this thread, or there is some question left?

**Comment by FinnFrotscher** [comment]
I have yet to read through the threads. It will be done by tomorrow morning and then I can decide.

**Comment by dr-dimitru** [comment]
Hey @FinnFrotscher , any news ?

**Comment by FinnFrotscher** [comment]
Yes a question.
When I have the `config.namingFunction` setup on `this.Videos = new FilesCollection`, how do i pass params to it?

**Comment by dr-dimitru** [comment]
Params and context is passed upon moment when lib needs to get a name for a file.
On upload and FS write.
Just drop there `console.log(this, arguments);` so see what you can work with

**Comment by FinnFrotscher** [comment]
Works on localhost.
We push to server sometime this week probably.  Then I will close.

Solution:
`lib/collection.js` 
```
this.Videos = new FilesCollection({
  collectionName: 'Videos',
  allowClientCode: false,
  storagePath: '/data/imde',
  namingFunction: (args) => {
    console.log('\n namingFunction says: ');
    console.log(args.name);
    return args.name
  }
});
```

**Comment by dr-dimitru** [comment]
@FinnFrotscher 
I should warn you what this method allows to affect server side in naming files on FS from untrusted client.

**Comment by FinnFrotscher** [comment]
any precautions you suggest?

**Comment by dr-dimitru** [comment]
Replicate same logic you use in `fileName` inside `namingFunction` without passing there untrusted data which coming from *Client*

**Comment by FinnFrotscher** [comment]
How do I pass params to the `namingFunction` from the client?

**Comment by dr-dimitru** [comment]
No need to pass, as I said before - check function's context and arguments

**Comment by FinnFrotscher** [comment]
Where is the improvement, when I pass two variables and combine then on the server `(args)=>{return ID_'+args._id+'_TRY_'+args.count`} versus `fileName: 'ID_'+_id+'_TRY_'+this.state.count` on the client?

**Comment by dr-dimitru** [comment]
Everything except `meta` on `fileObj` (basically record from mongo) is trusted source.
Like `_id` in your example. Idk where `count` comes from, so I can not say is it trusted enough

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher ,
Let me know what you final solution, and how it's working on your end.

**Comment by FinnFrotscher** [comment]
It works fine :) 
We went with the original solution. 
Both `ID` and `count` are custom `vars`. But on the server we do make sure the string is of a certain length and such.

**Comment by dr-dimitru** [comment]
@FinnFrotscher nice to hear that.
