### ISSUE TITLE
Error after using gm function in _app.createThumbnails in Demo example

### ISSUE THREAD

**Issue by aposidelov** [VeliovGroup/Meteor-Files#252]
Hi, I downloaded Demo example to check how thumbnail generation works. Application seems to work OK, I can upload different files and see them in preview region. But as for images I figure out that thumbnails aren't generated and some error happens with an object that is returned by gm function.
Here is an object that is returned by gm function:
![met-server-m3](https://cloud.githubusercontent.com/assets/2487197/19081655/576445e0-8a5b-11e6-92de-5ac538407fa6.png)
It has some error: **spawn identity ENOENT** and cannot be used further. I investigated that it might happends because imagemagick is not installed. So I installed it: **meteor npm install imagemagick** but I still have gm object with error.

**Comment by dr-dimitru** [comment]
nam package it's just js-interface for gm.
You also need binary: http://www.graphicsmagick.org/INSTALL-windows.html

**Comment by dr-dimitru** [comment]
@aposidelov is it helped you?

**Comment by aposidelov** [comment]
yes, the error has been disappeared, but I have some things that are not clear for me. I see that thumbnails are generated but when I check a UploadedFiles collection I cannot see any info about thumbnail pathes and other details:
![met-server-m4](https://cloud.githubusercontent.com/assets/2487197/19107434/70496ad6-8aec-11e6-8368-4aa5b7c34c18.png)
Is it supposed to be something like
...
```
versions:
  thumbnail40
     path:
     extension:
     meta:
  preview
     path:
     extension:
     meta:
```
?
Also I was checking a logic of createThumbnails and for my example 2nd big if executes (if !!~['jpg', 'jpeg', 'png']) that have collection update with thumbnail details. Here is a log of **upd** string before it will be passed in collection.update:
![met-server-m5](https://cloud.githubusercontent.com/assets/2487197/19107626/6e3b1b30-8aed-11e6-8e69-3df301db2af1.png)

**Comment by dr-dimitru** [comment]
The amount of published data is limited, take a look: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L289

**Comment by aposidelov** [comment]
Thank you!!! Now it's clear
