### ISSUE TITLE
how to upload multiple image or files??

### ISSUE THREAD

**Issue by sunil111** [VeliovGroup/Meteor-Files#253]

**Comment by dr-dimitru** [comment]
Hi @sunil111 

Take a look on this solution: https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/client/upload/upload-form.coffee#L53

**Comment by sunil111** [comment]
var file = e.target.files[0];
var Uid = Meteor.userId();
    
    for(var i=0; i<file.length ; i++){

        Images.insert({
          file: file,
          streams: 'dynamic',
          chunkSize: 'dynamic',
          meta: {Uid: Uid}
        }, true);

      };

Sir ..This is my code..
i am so confused. please ..can you tell me how to multiple image insert in Image.insert statement.

**Comment by dr-dimitru** [comment]
```js
Template.uploadForm.events({
  'change #fileInput': function (e, template) {
    if (e.currentTarget.files) {
      _.each(e.currentTarget.files, function (file) {
        Images.insert({
          file: file
        });
      });
    }
  }
});
```

**Comment by sunil111** [comment]
Thank you so much @dr-dimitru

**Comment by dr-dimitru** [comment]
@sunil111 glad it helped, do not hesitate to ask more.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
