### ISSUE TITLE
Rename file after upload aborts

### ISSUE THREAD

**Issue by ck23onGithub** [VeliovGroup/Meteor-Files#256]
Hi,

I have a question.

Is it possible to rename a file after its upload fails?

as of now i'm getting an error `EPERM: operation not permitted, rename...` when i try to rename the file.

May i know why its not permitted to rename the file even if the upload is already aborted?

Are there any work arounds so i can rename the file if it is possible? I really need to do it.

**Comment by ck23onGithub** [comment]
Is this related why i cant rename a file?

![uploading](https://cloud.githubusercontent.com/assets/22335710/19138188/7379df90-8bac-11e6-81ee-91d23b91cd9f.PNG)

i also tried closing the browser and a pop up says that

![errorpopup](https://cloud.githubusercontent.com/assets/22335710/19138243/f99830b8-8bac-11e6-9b72-3e7cea96ee80.PNG)

This means 'there is a possibility that the changes you have made will not be saved'.

**Comment by dr-dimitru** [comment]
> Is it possible to rename a file after its upload fails?

If upload fails, file will be removed. So, no you can not rename file which is removed.
Or I've got your question wrong..

> May i know why its not permitted to rename the file even if the upload is already aborted?

As I've said you probably trying to rename file which is in the process of removing, or at least it has open descriptor and it;s locked on FS level

> i also tried closing the browser and a pop up says that

I assume what upload is not finished.

Anyways could you describe more, like why upload is aborted? Why upload fails?

**Comment by ck23onGithub** [comment]
> If upload fails, file will be removed. So, no you can not rename file which is removed.

Mine does not get removed. lol

i tried to delete the file while uploading is ongoing. here are the screenshot of logs of what happened.

![noerror](https://cloud.githubusercontent.com/assets/22335710/19147029/c42e58da-8be8-11e6-95a3-fb650ba6ba98.png)

![noerror1](https://cloud.githubusercontent.com/assets/22335710/19147031/c6e3ff9e-8be8-11e6-8044-94b9a709d01f.png)

and the file is still exists in my storage path.

> I assume what upload is not finished.

I'll try to test this more. I'm thinking that i can make a work around for my situation.

**Comment by dr-dimitru** [comment]
Where and how do you actually remove the file?

>  Mine does not get removed. lol

It may be removed by `continueUploadTTL`. Otherwise *MF* will keep open descriptor, which should lead to file locking

**Comment by ck23onGithub** [comment]
i did not do anything in the codes. you said that it will be removed automatically so i simply tried to do an upload and make it fail (by deleting the file thats being uploaded). and then i check my file system and its still there. i set `continueUploadTTL: 5` so i can see the changes immediately. but the files are not disappearing in the folder

**Comment by dr-dimitru** [comment]
I meant what exactly do you do (*what command you're execute*) to remove the file?

**Comment by ck23onGithub** [comment]
shift + delete

permanent delete :D

**Comment by dr-dimitru** [comment]
Okay, if you changing `continueUploadTTL` without resetting MongoDB collection indexes it wouldn't apply, see [code here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L618) (*as it based on top of Mongo's TTL*).

**Comment by dr-dimitru** [comment]
you need to remove `__pre_*` collection or reset indexes on it

**Comment by ck23onGithub** [comment]
Thanks. I'll try this and report immediately.

**Comment by ck23onGithub** [comment]
ahm... how do i drop it in the shell? my collection name is `Files`

I'm typing `db.__pre_Files.drop()` and its an error.

**Comment by dr-dimitru** [comment]
I've protected special collection from prying hands.
Use:
`db.getCollection('__pre_Files').drop()`

**Comment by ck23onGithub** [comment]
thank you for the help. this is what i've been looking for. i thought the `continueUploadTTL` does not work for me.

**Comment by dr-dimitru** [comment]
Hooray! Glad it helped you.

**Comment by ck23onGithub** [comment]
I'm sorry to bother you again about this, @dr-dimitru 

the file in the `fs` does not get deleted automatically if the upload fails. and sometimes the descriptor remains open event after the time indicated in `continueUploadTTL`. i found this out because i try to do a `fs.stat` on a file 5secs after it triggered upload fail

**Comment by ck23onGithub** [comment]
i notice that it is being deleted if it is not in seen in the 'Sources' of the debug tool of Google Chrome. but sometimes it is not deleted there

**Comment by dr-dimitru** [comment]
@ck23onGithub I saw some messages posted by you. But can't find them here. I guess it is solved, right?

**Comment by ck23onGithub** [comment]
i deleted it because i was confirming it. its about the file that is being deleted if the upload fails.

the problem i saw is that sometimes, the file descriptor does not close immediately after the upload fails. is there any work around for this?

and if the upload fail, if i retry to upload it, will it append? given that my `continueuploadTTL` is `5`.

**Comment by ck23onGithub** [comment]
> the problem i saw is that sometimes, the file descriptor does not close immediately after the upload fails. is there any work around for this?

if there is none, what is the reason why this happens? maybe if its really impossible to make sure that this issue does not happen, a good explanation will be good to make it acceptable. :smile:

**Comment by dr-dimitru** [comment]
> and if the upload fail, if i retry to upload it, will it append?

Not it's possible only for paused uploads. Like you can start big file upload, close you laptop, go to other location open laptop, and click "continue" button.

Can not answer other question, as I can not see the issue there. Lib is good at descriptors and files management.

**Comment by ck23onGithub** [comment]
hmm. its causing a big issue when the file desciptor is not closed. the next upload always fails.

though there are times that when i delete the file i am uploading, the file is immediately removed in the sources of the debug tool of the browser

**Comment by dr-dimitru** [comment]
I see no connection between fd (*which is server only*) and "sources" in browser

**Comment by ck23onGithub** [comment]
regarding `continueuploadTTL`, this starts when the upload starts, right? if my `continueuploadTTL` is set to 5sec, and my upload does not finish within 5sec, will it trigger an error?

**Comment by dr-dimitru** [comment]
> regarding continueuploadTTL, this starts when the upload starts, right? if my continueuploadTTL is set to 5sec, and my upload does not finish within 5sec, will it trigger an error?

Right.

**Comment by ck23onGithub** [comment]
OMG. . . i thought that if it is in progress, the timer will stop. . . so this is my issue. i thought something weird was going on with my app. oh no. . . :laughing:

**Comment by ck23onGithub** [comment]
after the set time in `continueuploadTTL`, the file descriptor will be closed, am i right?

**Comment by dr-dimitru** [comment]
> after the set time in continueuploadTTL, the file descriptor will be closed, am i right?

Right, or right after file is uploaded
