### ISSUE TITLE
Error: Method '_FilesCollectionStart_MyCollection' not found

### ISSUE THREAD

**Issue by Victordmdb** [VeliovGroup/Meteor-Files#258]
Hi!

I've implemented the React version taken from https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example, but I'm getting the above error if i upload a file at 
`uploadInstance.on('end',(err,f)=>{if(err) console.log(err)}`
I get the same error for FilesCollectionAbort_ coming from the `on('error'`

Any idea what the source of the issue would be?

**Comment by Victordmdb** [comment]
Sorry sorry,

Just found the solution in https://github.com/VeliovGroup/Meteor-Files/issues/110

**Comment by dr-dimitru** [comment]
Hi @Victordmdb ,

I'm glad you've solved it.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)

**Comment by Victordmdb** [comment]
Will do! Great package
