### ISSUE TITLE
serving files from gridfs with react-router

### ISSUE THREAD

**Issue by nialexsan** [VeliovGroup/Meteor-Files#259]
In brief, I have a Meteor app with React-router and gridfs for storing the files. 

The uploading is working just fine, but I cannot figure out how to serve uploaded files to the client from gridfs since all the files are in the mongodb. 

I suppose that there should be some stuff in `interceptDownload` just like in GridFS Integration wiki example, but I can't figure out how to execute this callback with the React router.

Have you any ideas or maybe useful links for resolving this?

**Comment by dr-dimitru** [comment]
Hi @nialexsan 

Do not worry about integration with router.
*MF* lib serves files from server. To generate downloadable link use `.link()` method in Client side.

And, yes use `interceptDownload` as it shown in GridFS integration at Wiki

**Comment by dr-dimitru** [comment]
Also take a look on #75

**Comment by nialexsan** [comment]
No luck with this, still getting 404.

I should define some route for retrieving uploaded files.

The `.link()` returns path like this: 
> /cdn/storage/QMDEB4EDY3G6CEdGm.jpg

but this route is not defined in the app

**Comment by dr-dimitru** [comment]
No need to define this route.

**Comment by nialexsan** [comment]
while trying to access the file like 

> http://localhost:3000/cdn/storage/QMDEB4EDY3G6CEdGm.jpg

app throws an error page, which I have set in my routes

> Error [404]: /assets/app/uploads/Images/QMDEB4EDY3G6CEdGm.jpg does not exist. 

in case of removing route for 404 I get 

> Warning: [react-router] Location "/cdn/storage/QMDEB4EDY3G6CEdGm.jpg" did not match any routes

**Comment by dr-dimitru** [comment]
Try to play with `downloadRoute`, make sure it is not interfere with any of yours client side route.
And make sure image is uploaded and exists.

Dev stage note form FAQ:

> note: __all files will be removed as soon as your application will rebuild__

**Comment by dr-dimitru** [comment]
Also use `debug` option, to see what actually is happening on the server.
Post here your server's logs

**Comment by nialexsan** [comment]
Hi @dr-dimitru! Thanks for helping! Today I have checked the same links with the same code and it happened that everything was working just fine. 

One of that awkward moments, when you don't know what was the reason behind that dysfunctional code =)

Thanks for your help once again!
