### ISSUE TITLE
Question: Debug help

### ISSUE THREAD

**Issue by elewis33** [VeliovGroup/Meteor-Files#262]
I've only been using Meteor Files for a short time and it seems to be working fine, but when I restart my meteor server I'm getting the following feedback from Meteor:

```
I20161010-18:51:41.707(-6)? [FilesCollection.storagePath] Set to: /data/meteor/apps/zipper/zips
=> Meteor server restarted
I20161010-18:51:41.833(-6)? [FilesCollection] [find({}, undefined)]
```

I'm assuming the last line is not correct, i.e. something is wrong with my code. How can I find out what is causing that? In my startup I'm not interacting with the FilesCollection at all. 

Is there something wrong with the way I'm initializing the FilesCollection?

```
Uploads = new Meteor.Files({
  debug: true,
  collectionName: 'Uploads',
  allowClientCode: false, // Disallow remove files from Client
  public: true,
  downloadRoute: 'public/surveys/wireless/zips/',
  storagePath: '/data/meteor/apps/zipper/zips/',
  parentDirPermissions: 0774,
  permissions: 0774,
  onBeforeUpload: function (file) {
    // control file size and allowed file formats here
    if (file.size <= 1024*1024*20 && /zip|png|jpg|jpeg|mp3|mp4|mpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please limit upload size to 20MB';
    }
  }
});
```

Any help or pointers are greatly appreciated.

**Comment by dr-dimitru** [comment]
Hi @elewis33 ,
Looks, good to me.
May it be caused by `publish` function?

**Comment by dr-dimitru** [comment]
@elewis33 any news on your end?

**Comment by elewis33** [comment]
No, I have no idea why the debug is listing this
```
=> Meteor server restarted
I20161010-18:51:41.833(-6)? [FilesCollection] [find({}, undefined)]
```
Sometimes it's not outputting that line on restart, sometime it is... Everything seems to be working so I guess I won't worry about it. But every time I restart and see that message, I worry about it. :/

**Comment by elewis33** [comment]
Is there some way to get a more verbose debug output, to see what's going on in some more detail?

**Comment by dr-dimitru** [comment]
If you're worried about `undefined`, it is just means you haven't passed second argument. So you're good

**Comment by elewis33** [comment]
Ok, got it, thanks for that clarification. Feel free to close.

**Comment by dr-dimitru** [comment]
it actually logs every call. More than enough.
You can rewrite it and add `console.trace()` to see where it comes from
