### ISSUE TITLE
TypeError: Cannot read property '_resolvedSchema' of undefined

### ISSUE THREAD

**Issue by i-siddiq** [VeliovGroup/Meteor-Files#263]
I am doing simple file upload with following code.
/lib/collections/images.js
```javascript
Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onbeforeunloadMessage: function () {
  return 'Upload is still in progress! Upload will be aborted if you leave this page!';
  },
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }    
  }
});

if (Meteor.isClient) {
  Meteor.subscribe('files.images.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.images.all', function () {
    return Images.find().cursor;
  });
  Images.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    },
    remove: function() {
      return true;
    }
  });
}
```

/lib/collections/profiles.js

```javascript
Profiles = new Mongo.Collection('profiles');


if (Meteor.isServer) {
  Profiles.allow({
    insert: function (userId, doc) {
      return true;
    },

    update: function (userId, doc, fieldNames, modifier) {
      return true;
    },

    remove: function (userId, doc) {
      return true;
    }
  });

}
images = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 60,
  },
  profilePic: {
    type: String,
    label: "Profile Picture",
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: 'Images'
      }
    }
  }
});

Profiles.attachSchema(images);

```
**errors on server side are:**

=> Meteor server restarted

I20161012-01:37:04.697(3)? [FilesCollection] [find({}, undefined)]

I20161012-01:37:04.848(3)? Kadira: Successfully connected

I20161012-01:42:19.473(3)? [FilesCollection] [find({}, undefined)]

I20161012-01:43:39.411(3)? [FilesCollection] [File Start Method] tim_80x80.png - to6ZvvzXeSJPaTqeF

I20161012-01:43:39.416(3)? [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: tim_80x80.png

I20161012-01:43:39.576(3)? [FilesCollection] [Abort Method]: to6ZvvzXeSJPaTqeF - undefined

**errors on chrome console are:**

[FilesCollection] [findOne({"_id":false}, undefined)]
ostrio_files.js?hash=eac8f11…:2628 [FilesCollection] [insert()]
ostrio_files.js?hash=eac8f11…:3115 [FilesCollection] [insert] [Tracker] [continue]
ostrio_files.js?hash=eac8f11…:3223 [FilesCollection] [insert] [.continue()]
ostrio_files.js?hash=eac8f11…:3146 [FilesCollection] [insert] using WebWorkers
ostrio_files.js?hash=eac8f11…:3057 [FilesCollection] [_Start] Error: errorClass {error: 403, reason: "Please upload image, with size equal or less than 10MB", details: undefined, message: "Please upload image, with size equal or less than 10MB [403]", errorType: "Meteor.Error"}handleStart @ ostrio_files.js?hash=eac8f11…:3057(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625(anonymous function) @ ddp.js:133onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
ostrio_files.js?hash=eac8f11…:2796 insert tim_80x80.png: 157.317ms
ostrio_files.js?hash=eac8f11…:2803 [FilesCollection] [insert] [end] Error: errorClass {error: 403, reason: "Please upload image, with size equal or less than 10MB", details: undefined, message: "Please upload image, with size equal or less than 10MB [403]", errorType: "Meteor.Error"}module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end @ ostrio_files.js?hash=eac8f11…:2803emitEvent @ event-emitter.jsx:380handleStart @ ostrio_files.js?hash=eac8f11…:3059(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625(anonymous function) @ ddp.js:133onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
ostrio_files.js?hash=eac8f11…:3246 [FilesCollection] [insert] [.abort()]
ostrio_files.js?hash=eac8f11…:3212 [FilesCollection] [insert] [.pause()]
ostrio_files.js?hash=eac8f11…:3255 insert tim_80x80.png: 176.062ms
debug.js:41 Exception in delivering result of invoking '_FilesCollectionStart_Images': TypeError: Cannot read property '_resolvedSchema' of undefined
    at Object.autoFormGetValidationContext [as getValidationContext] (http://localhost:3000/packages/aldeed_autoform.js?hash=bc39be6ca27d0c59949383895549e303297ced7f:2417:16)
    at FileUpload.<anonymous> (http://localhost:3000/packages/ostrio_autoform-files.js?hash=8a3eda0832fcfc9a72e8074bb2edc747305799b4:254:18)
    at FileUpload.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
    at UploadInstance.module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:2807:21)
    at UploadInstance.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
    at handleStart (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:3059:16)
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3557:12)
    at MethodInvoker.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3577:10)
    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4736:9)

I have been trying for hours, any ideas what is wrong? I am using latest meteor plus ostrio:autoform-files@1.0.7 and ostrio:files@1.7.3.

**Comment by dr-dimitru** [comment]
Hi @i-siddiq ,

Take a look on this thread [solved]: https://github.com/VeliovGroup/meteor-autoform-file/issues/5#issuecomment-252452127

**Comment by i-siddiq** [comment]
ok thanks , I will follow that thread.
