### ISSUE TITLE
QUESTION: download from localhost

### ISSUE THREAD

**Issue by ck23onGithub** [VeliovGroup/Meteor-Files#270]
Hi,

When I run my Meteor app, I notice that the links of the downloadable files are from `localhost`. Because of that, if I try to access the app from another device, the download link still shows `localhost` and the file can't be downloaded. May I know if I'm missing something here?

I'm trying to run the Meteor app using `meteor run`. This creates a link with `localhost`

I tried running it using `meteor run -port <myIP:port>`. This creates a link directly to my IP and I can download the file.

But if I run the app using `meteor run -port <myPublicIP:port>`, there's an error.

Is there a way to access the app through my public IP but the download is directed to my IP address?

I really think I'm missing something. But I don't know what specifically.

Thanks

**Comment by ck23onGithub** [comment]
This is what I'm trying to do:

I run the meteor app at my pc. and then I'll open the app using other pc that have a different IP. when he download the file, I want it to use my IP address as the host of the file and not 'localhost'.

Is it possible?

**Comment by dr-dimitru** [comment]
Yes, just pass `ROOT_URL` env.var:

```shell
ROOT_URL=http://your_ip:port meteor
```

**Comment by ck23onGithub** [comment]
> ROOT_URL=http://your_ip:port meteor

is this different from `Meteor.absoluteUrl.defaultOptions.rootUrl`? I've read some issues regarding about changing the `ROOT_URL`

Thanks. I'll try this.

**Comment by dr-dimitru** [comment]
Should work, I haven't heard about any issues with it

**Comment by ck23onGithub** [comment]
I tried this one:

`Meteor.startup(() => {
  Meteor.absoluteUrl.defaultOptions.rootUrl = 'http://192.168.222.61:5000';
  process.env.ROOT_URL = 'http://192.168.222.61:5000';`

then i run the app using

`meteor run`

but when i hover on the download link, i can still see `localhost`

**Comment by dr-dimitru** [comment]
Idk about `Meteor.absoluteUrl.defaultOptions.rootUrl`.
You've asked me for solution - use `ROOT_URL`, I think it's clear

**Comment by ck23onGithub** [comment]
i checked the net and saw something like this to set the `ROOT_URL`

i have this on my settings.json
`{
	"ROOT_URL": "http://laulap.com"
}`

and run may project using
`meteor run settings.json`

Is this what you meant?

**Comment by ck23onGithub** [comment]
I was able to set the `ROOT_URL` by running `set ROOT_URL=http://myurl` and running `meteor run`

I opened my app using `http://myurl:3000`

I saw that the links were changed to reflect the new `ROOT_URL`. but when i clicked it, i got an error saying
`Error: 'value' required in setHeader("Set-Cookie", value)`

**Comment by dr-dimitru** [comment]
Why you doing something else but not what I've said in my answer?
Copy-paste next line to the Terminal (Console where you're running your meteor):
```shell
ROOT_URL=http://myurl:3000 meteor
```

Yes, first you set environment variable for command after space, which is just `meteor`

**Comment by dr-dimitru** [comment]
Hey @ck23onGithub ,
Have solved it?

**Comment by dr-dimitru** [comment]
@ck23onGithub any news on your end?

**Comment by ck23onGithub** [comment]
sorry. been busy the past few days. its ok on my end now so I'll close this one now. thank you
