### ISSUE TITLE
Upload from non-meteor App

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [VeliovGroup/Meteor-Files#271]
Hi, I have a Meteor server which is using this package to handle uploads
On the other side, I have a react-native app, which is not a Meteor app, so I can't install this package on it. (Although, I'm using https://www.npmjs.com/package/react-native-meteor to communicate with the backend)

I am wondering how I could upload a file from my react-native application to a Meteor backend which is using this package (preferably using HTTP, not DDP) ...

Any ideas?

**Comment by dr-dimitru** [comment]
Hi @rafaelcorreiapoli ,

Take a look at this example of POST upload (cURL upload): https://github.com/noris666/Meteor-Files-POST-Example

**Comment by dr-dimitru** [comment]
@rafaelcorreiapoli any news on your end?

**Comment by rafaelcorreiapoli** [comment]
Thanks! that's exactly what I needed. But I have not tested it yet, I will try it tomorrow

**Comment by dr-dimitru** [comment]
Okay @rafaelcorreiapoli , let me know then

**Comment by dr-dimitru** [comment]
@rafaelcorreiapoli I guess it's solved, reopen if not
