### ISSUE TITLE
Download link with custom ddp

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [VeliovGroup/Meteor-Files#272]
Hello! We need to figure out how to get the custom DDP remote IP so we can build the download link correctly
https://github.com/VeliovGroup/Meteor-Files/blob/e2600d0b58bd56e11f93a630855dce3a2dd28479/files.coffee#L2362

In the current implementation, it will always be ROOT_URL, which is not correct if I'm using a custom DDP

refer to #254

**Comment by dr-dimitru** [comment]
But files downloads via HTTP
And #254 is merged and released

**Comment by rafaelcorreiapoli** [comment]
Take a look at this example:

I have a client that has a ROOT_URL =http:// localhost:3000, that's my main meteor server
In this client, I'm uploading the files with a custom ddp connection, which points to http://localhost:4000 (this is another meteor app, that has the only purpose to upload files)
When I call FilesCollection.link(), it gives me this link:
http://localhost:3000/....../

So my main server (the one at port 3000) will be the one responsible to pipe the request to s3. But my main server knows nothing about file uploads...
the link should point to http://localhost:4000/..../ so this meteor app will pipe the request correctly

**Comment by dr-dimitru** [comment]
@rafaelcorreiapoli 

1. it's generated on the client, so it doesn't know where it was uploaded to
2. You can add extra field to `meta` object, like `host`

and do:
```js
link = file.meta.host + file.link().replace(/http(s)?\:\/\//i, '').replace(document.location.host, '');
```

Moreover you may stop using `link()` method in favour of your own, URI schema is simple:
```
{host}/{file._downloadRoute}/{file._id}/{version}/{file._id}.{file.extension}
```

**Comment by rafaelcorreiapoli** [comment]
Maybe i'm missing something, but I still think that the file download depends on the server
I know the link is generated on the client, but it must point to the same server where the upload has been made, which is not always the server on ROOT_URL, since we now support custom DDP connections

But, for now, the workaround is to generate a link myself, following the schema you wrote above, where host = http://localhost:4000, not ROOT_URL (http://localhost:3000)

Thanks! If you want, you may close this issue. But I still think that we need a PR to solve this because people using customDDP + s3 will have problem

**Comment by dr-dimitru** [comment]
@rafaelcorreiapoli are you using Collections over different DDPs too?

**Comment by rafaelcorreiapoli** [comment]
Yes!
```js
import { DDP } from 'meteor/ddp-client'
import { Mongo } from 'meteor/mongo'
import { FilesCollection } from 'meteor/rafa93br:files-custom-ddp';

const filesDDPUrl = Meteor.settings.public.filesDDPUrl
if (!filesDDPUrl) throw new Error('Must config filesDDPUrl in settings.json!')

export const FileDDP = DDP.connect(filesDDPUrl)

const collection = new Mongo.Collection('files', {
  connection: FileDDP,
})

export default new FilesCollection({
  ddp: FileDDP,
  debug: true,
  collection,
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (/png|jpg|jpeg|bmp/i.test(file.extension) || file.type === 'image/webp' || file.type === 'image/png') {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```

**Comment by dr-dimitru** [comment]
@rafaelcorreiapoli is this solved? You latest post looks solid.
As for S3 we already suggest to use `interceptDownload` you may proxy-pass request to your other host if image is not found on the host which received request, or as mentioned before use extra property to know where image is stored exactly and reroute request.
