### ISSUE TITLE
Are there any step by step tutorials for how to use subversions?

### ISSUE THREAD

**Issue by spiotr12** [VeliovGroup/Meteor-Files#274]
Are there any step by step tutorials for how to use subversions for images as thumbnails? The package overall is great! 

thanks a lot!

**Comment by dr-dimitru** [comment]
Hi @spiotr12 ,

Thank you. I'm glad you found my work useful.
Have you seen [this demo](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/server/image-processing.coffee)?

**Comment by spiotr12** [comment]
Yes, but it is all in coffee script which I find difficult to extract the code to use in thumbnails. 
in this section [link](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper#display-thumbnail) you redirect to 'Create and Manage Subversions' but you don't mention any thumbnails there or at least how to use this for images files.  That would be great If you could put up some more info there. 

Thanks a lot if you'd do!

**Comment by dr-dimitru** [comment]
There is pseudo code compatible with any need, like image, video or any other file subversion. Basic idea is what you catch uploaded file in `onAfterUpload` hook. Then you just update MongoDB record.

For example you've received image, when `onAfterUpload` is triggered you take file's `path` and send it to `gm` (GraphicsMagic), after it returns data - you update file's `versions` with new data.

**Comment by spiotr12** [comment]
Okay, I will try that. Thanks!

**Comment by dr-dimitru** [comment]
@spiotr12 let me know if it works for you

**Comment by spiotr12** [comment]
Hi

I've managed to do this. I've used GraphicsMagic Node package [link](http://aheckmann.github.io/gm/).

Here is my code - in case someone would like to see this part:

`export function createThumbnail(file, _callback) {
	console.log('start making thumbnail');
	let name, newFilePath, size, type, extension, version = 'thumbnail', info;

	let mime = Npm.require('mime');
	let path = Npm.require('path');
	let fs = Npm.require('fs');
	let stats = fs.statSync(file);

	// prepare thumbnail info
	size = stats["size"];
	type = mime.lookup(file);
	extension = path.extname(file);

	name = path.basename(file, extension) + '-' + version;
	newFilePath = path.dirname(file) + '/' + name + extension;

	info = {
		name: name,
		path: newFilePath,
		size: size,	// check thumbnail size
		type: type,
		extension: extension.replace('.', ''),	//remove dot for return object
		version: version,
		success: false
	};

	let gm = Npm.require('gm');

	// create a file copy
	let thumbFile = _.clone(file);
	// Process image to create a thumbnail
	gm(thumbFile)
		.resize(Meteor.settings.public.app_settings.thumbnail_width)	// width
		.autoOrient()
		.write(newFilePath, function (err) {
			if (err) {
				console.log('GM error:', err);
				info.success = false;
			} else {
				info.success = true;
			}
			console.log('finished making thumbnail');
			_callback(info);
		})
	;
}`

And then the version update:

`		createThumbnail(sourceFile, function (thumbInfo) {
			bound(function () {
				thumbnailDetails = thumbInfo;
				console.log('update db with thumbnail')
				// Add thumbnail to mongodb
				if (thumbnailDetails.success) {
					let upd;
					upd = {
						$set: {}
					};
					upd['$set']['versions.' + thumbnailDetails.version] = {
						path: thumbnailDetails.path,
						size: thumbnailDetails.size,
						type: thumbnailDetails.type,
						extension: thumbnailDetails.extension
					};
					self.collection.update(fileRef._id, upd);
				}
});
		});
`

**Comment by PolGuixe** [comment]
@spiotr12 thanks for the snippets. Just one questions are you doing the image processing synchronously or asynchronously?

**Comment by dr-dimitru** [comment]
@PolGuixe 

`gm` wrapper and its methods is asynchronous.
`onAfterUpload` called asynchronously too, and detached from main fiber thread.

**Comment by PolGuixe** [comment]
@dr-dimitru Then I should put the Knox upload part into a callback, that is executed once the image processing has finished?

**Comment by dr-dimitru** [comment]
@PolGuixe right, and meanwhile files being changed/transferred to AWS - it will be served from FS
