### ISSUE TITLE
Error: Cannot find module './lib'

### ISSUE THREAD

**Issue by obiwarn** [VeliovGroup/Meteor-Files#275]
On Meteor 1.4.2 I get the above error when I install gridfs-stream. Anyone else?

**Comment by obiwarn** [comment]
Ah you also need to add `--save` to the `meteor npm install` command

**Comment by obiwarn** [comment]
Better update the readme?

**Comment by dr-dimitru** [comment]
Hi @obiwarn ,

PRs is always welcome, or you can point me to the docs where `--save` flag is missed

**Comment by dr-dimitru** [comment]
https://github.com/VeliovGroup/Meteor-Files/commit/a3652778e7d28e593834fe6e6df67bf2801cfeda
