### ISSUE TITLE
Create and Manage Subversions: file.someHowConvertVideoAndReturnFileData(format) and version info

### ISSUE THREAD

**Issue by spiotr12** [VeliovGroup/Meteor-Files#277]
Could you explain what should happen during `file.someHowConvertVideoAndReturnFileData(format)` ?

Do you use graphicsmagic or imagemagic in that example? (seems like that imagemagic to me, please correct me if I'm wrong).

How do you get `version` info from that function (like path, size, type)?

I'm trying to understand what you've did on video subversion to create image thumbnails (and upload it to S3 later on).

Thanks a lot!

**Comment by spiotr12** [comment]
Ok so I came up with this:

`createThumbnail(sourceFile, function (thumbInfo) {
	bound(function () {
		console.log('callback info', thumbInfo);
		thumbnailDetails = thumbInfo;
		console.log('thumbnail details\n', thumbnailDetails);

		// Add thumbnail to mongodb
		if (thumbnailDetails.success) {
			let upd;
			upd = {
				$set: {}
			};
			upd['$set']['versions.' + thumbnailDetails.version] = {
				path: thumbnailDetails.path,
				size: thumbnailDetails.size,
				type: thumbnailDetails.type,
				extension: thumbnailDetails.extension
			};
			self.collection.update(fileRef._id, upd);
		}
	});
});`

and my createThumbnail function is:

`function createThumbnail(file, _callback) {
	let name, newFilePath, size, type, extension, version = 'thumb', info;

	let mime = Npm.require('mime');
	let path = Npm.require('path');
	let fs = Npm.require('fs');
	let stats = fs.statSync(file);

	// prepare thumbnail info
	size = stats["size"];
	type = mime.lookup(file);
	extension = path.extname(file);

	name = path.basename(file, extension) + '-' + version;
	newFilePath = path.dirname(file) + '/' + name + extension;

	info = {
		name: name,
		path: newFilePath,
		size: size,
		type: type,
		extension: extension.replace('.', ''),	//remove dot for return object
		version: version,
		success: false
	};

	let gm = Npm.require('gm');

	// create a file copy
	let thumbFile = _.clone(file);
	gm(thumbFile)
		.resize(Meteor.settings.public.app_settings.thumbnail_width)	// width
		.autoOrient()
		.write(newFilePath, function (err) {
			if (err) {
				console.log('GM error:', err);
				info.success = false;
			} else {
				info.success = true;
			}
			_callback(info);
		})
	;
}`

If you'd have a moment to advice me on this code that be great. This seems to work fine.

**Comment by dr-dimitru** [comment]
Hello @spiotr12 ,

In demo app we use [this function](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/server/image-processing.coffee#L4) for image cropping/resizing.

Basically you put all logic into `onAfterUpload`.
Then you do all async jobs is needs to be done (converting/cropping/etc.). Then you manually update `versions` property in Mongo, with new versions.

Hope it helps. Let me know.

**Comment by dr-dimitru** [comment]
Hi @spiotr12 ,

Could we close this one? Your latest post looks solid
