### ISSUE TITLE
Invalid _downloadRoute and download from subdomain

### ISSUE THREAD

**Issue by RaymondLC92** [VeliovGroup/Meteor-Files#278]
1. I set _downloadRoute in the Constructor.

downloadRoute: '/mnt/media-nyc1-01/images',

2. The download route listed after doing Images.findOne is:

_downloadRoute: "/cdn/storage"

3. File upload works (files are uploaded to /mnt/media-nyc1-01/images via storagePath)

I want to be able to deliver images from a subdomain i.e.:

media.mydomain.com/images/myimage.png

Is there a way to do this? Why is the _downloadRoute value on the cursor not the same as the constructor? I was attempting to use imageFile.link to get the link in the template but it returns an invalid url. I tried hard coding http://media.mydomain.com/images/{{image.name}} but the image file name is random. Finally I tried storing the ACTUAL file name in the meta object, unfortunately I don't seem to be able to access the name via: "imageFile.meta.name".

Any assistance with this is hugely appreciated.

I've managed to get the link to work via hard coding http://media.mydomain.com/images/{{image._id}}.{{image.extension}}

Is there no way however to get downloadRoute to work with subdomains?

**Comment by dr-dimitru** [comment]
Hi @RaymondLC92 ,

Thank you for report. Sorry for delay with reply, I'm travelling now.
I'll investigate this as soon as get a chance.

**Comment by RaymondLC92** [comment]
@dr-dimitru 

No problem, take your time & enjoy your trip.

**Comment by dr-dimitru** [comment]
Hello @RaymondLC92 ,

Thank you for patience. Please take a look on [this post](https://github.com/VeliovGroup/Meteor-Files/issues/272#issuecomment-256523292).

Yes, currently functionality is limited to generate links related to origin.

To hard code download-like use next schema:
```
{host}/{file._downloadRoute}/{file._id}/{version}/{file._id}.{file.extension}
```

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
