### ISSUE TITLE
Template Helper fileURL does not work on findOne()

### ISSUE THREAD

**Issue by spiotr12** [VeliovGroup/Meteor-Files#283]
So I came across this issue:

When I try to call `fileURL ` on `this` (being a fileCursor from findOne()) it does not work. What worked instead was `this.link <version>`.

On the other hand, when I try to clean my code, `fileURL `does work on object from find() but then the this.ling does not work. 

It took me a while to discover that. It is either I read something wrong or the helper does work only on iterated element from find() but does not work on findOne() element; and vice versa for  ` this.link`

Might be worth to investigate that?

**Comment by dr-dimitru** [comment]
Hello @spiotr12 ,

*FilesCursor* and *FileCursor* is cursors, where `cursor !== fileObj`. Think of cursors as interface to object. To get actual object(s) you need to call `.get()` method on *FilesCursor* and/or *FileCursor*.

Let me know if it helps
