### ISSUE TITLE
Images are still there after removing from filesystem 

### ISSUE THREAD

**Issue by lightsnow0** [VeliovGroup/Meteor-Files#284]
I'm pretty new to meteor, so sry when this is a stupid question. I adjusted the constructor to:
```js
this.Images = new Meteor.Files({
    debug: false,
    collectionName: 'Images',
    storagePath: '/images',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*10 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```
And my images are saved in the directoy /images which works perfect. 
But why are my images still in my application after removing them from my folder ?

**Comment by dr-dimitru** [comment]
Hello @lightsnow0 ,

App uses Mongo.Collection to know where and what files is stored. If you have removed files from FS, but not from collection, application will think files still exists.

Let me know if it helps

**Comment by lightsnow0** [comment]
Ok, so I get why the system thinks there is still an image. It's because there is still a link to the image in the mongo. 
But why displays my app still the images ? There is no image anymore ? Or are the images also in the mongo ? If yes, i don't get the sense of gridfs ....

**Comment by dr-dimitru** [comment]
@lightsnow0 if you're using GridFS - yes, images in a MongoDB. Otherwise it may be the browser cache.

**Comment by lightsnow0** [comment]
You're right, was the cache, thanks for the fast reply 👍 
And thanks for the great package :)

**Comment by dr-dimitru** [comment]
@lightsnow0 glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
