### ISSUE TITLE
this.userId in protected function is null when used in a package

### ISSUE THREAD

**Issue by thomasspiesser** [VeliovGroup/Meteor-Files#287]
Hey everyone,

first of all, let me express my thanks for this great package!

I unfortunately have the issue that I cannot use the `protected` function as I would like to because `this.userId` and `this.user()` always returns `null`. 

I have set up a little reproduction repo [here](https://github.com/thomasspiesser/ostrio-files-bug).

To give you a bit of context:
Since I share my models across many apps, I set it up as a git-submodule in a meteor package that I can then just add to the main app. That is why, the code is in a meteor package and not just in a `/lib` folder.

Btw, I have tested the code in the `/lib` folder and found that there it works perfectly. So the problem really boils down to the usage within a meteor package.

I would very much appreciate some help on this.

Cheers!

**Comment by sammarshall61** [comment]
I'm having a similar issue, in interceptDownload this.user() is undefined but in onBeforeUpload it works as expect. I agree with the above though loving the package!

**Comment by menelike** [comment]
I can reproduce this. The userId cookie seems to be missing, tested on `localhost:3000` and `127.0.0.1:3000`, chrome/osx. Currently no time to dig in further

**Comment by thomasspiesser** [comment]
Thanks @menelike for the confirmation. If you can point me into a direction I can poke around a bit. Maybe I can help.

**Comment by menelike** [comment]
Some debug steps can be seen in https://github.com/VeliovGroup/Meteor-Files/issues/159. Cookies are set with https://github.com/VeliovGroup/Meteor-Cookies/ , you need to understand why meteor-files could not set the cookie.

And of course, please make sure that your cookie is missing as well.

**Comment by dr-dimitru** [comment]
Hi @thomasspiesser 

As you can see in #159 there is not mush we can do.
Please see my [PR](https://github.com/thomasspiesser/ostrio-files-bug/pull/1/files) for example of authentication via get query. Token is changed frequently and get query is encrypted inside HTTPS (SSL) connection, if you will use it carefully it will be safe.

**Comment by thomasspiesser** [comment]
@dr-dimitru thanks for having taken the time to look into it.

**Comment by dr-dimitru** [comment]
@thomasspiesser which it helps. BTW is it solved alreay on your end? If so, how?

**Comment by deeeed** [comment]
any workaround for this? I have the same issue

**Comment by thomasspiesser** [comment]
@deeeed have a look at the PR mentioned above. Personally, I moved the code from the package into the main application...

**Comment by deeeed** [comment]
I did use the workaround but it's far from ideal, at the moment I am sharing my model from the package with multiple projects. Are you just duplicating the code in each projects?

**Comment by thomasspiesser** [comment]
No, I kept everything in the package except for the files collection stuff. I did not need that bit in the other projects yet but as soon as I do I will have to come up with something. Duplicating the code manually is not an option. I will try a `common` git submodule folder I think as I manage the package through a submodule already. So same setup but not as a meteor package but a simple folder. Haven't done that though...

**Comment by dr-dimitru** [comment]
Hello guys @thomasspiesser @deeeed ,

Any ideas how to solve it on our end?
I would like to solve it, could you point me to the right direction?

And if you already have a solution - PRs is always welcome.

**Comment by deeeed** [comment]
@dr-dimitru I used the workaround with the session as a query parameter but I am not really satisfied with it. 

Could we use a callback hook instead of defining the function in the constructor?
This way we may be able to run in the correct context even if the Collections are defined inside a package.

**Comment by dr-dimitru** [comment]
> Could we use a callback hook instead of defining the function in the constructor?

Not in the current implementation, at least unless we add token query authorization into core.
But, we should be able to do so, in v2.0, I've planned it for this summer
