### ISSUE TITLE
Some mobile browser can not choose more images at a time?

### ISSUE THREAD

**Issue by strongant** [VeliovGroup/Meteor-Files#288]
- Such as:
  - UC(Mobile)[https://www.baidu.com/link?url=JaBAxEHYngVmGMC8l29A-Fxs3cT9Yj2NZ3uXOeLkxFwEPonJdTumO5uggyIMJ6rd8_YDQ_atVDEVow93Wla8531XuWUFnamE31OegGh_gYkIGgn7ULSHfzxAQWPEAd1i&wd=&eqid=ae05c4bf00065c5100000004582c6c87](uc)
  - Baidu(Mobile)[https://www.baidu.com/link?url=Tcwnfnx79N32fn65cLR_hZd1hxWjWtGMPkdW4Y7V7OWCStVapj0YmMTCCWgYiL5DD48pm6cMVptBJ46hJPqAx2j7h3t79fGsjQrg9CaAF2xuutaO4xsZWfZE40RM9Tj7&wd=&eqid=d08d2bca000600a800000004582c6cb7](baidu)

**Comment by dr-dimitru** [comment]
Hello @strongant 

Both links is broken. Never faced UC or Baidu, but if there is limitation in browser - it's out of our control

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
