### ISSUE TITLE
Small working sample

### ISSUE THREAD

**Issue by genyded** [VeliovGroup/Meteor-Files#29]
Hi,

I could not find an email address or other contact information so I am opening an issue to really ask a question. Is there a small working sample of Meteor-Files anywhere? The readme is overwhelming and in coffee so it's not great for new Meteor developers that may not know coffee. It would really help if there was just a small real working example of uploading a small file to FS somewhere.

**Comment by dr-dimitru** [comment]
Hi @genyded 
You can asks questions in our gitter group: https://gitter.im/VeliovGroup/Meteor-Files
I just created basic app: https://github.com/VeliovGroup/ostrio-files-example
I'll ad more examples during this month

**Comment by dr-dimitru** [comment]
@genyded did you tried example app? Everything is clear?

**Comment by ameesters** [comment]
could you provide a pure JS example with handlebars so non coffeescript+ejs+sass people can understand it as well?

**Comment by dr-dimitru** [comment]
@ameesters okay, I'll try until end of this week

**Comment by NROL39** [comment]
I'd like that too, i've been trying to integrate it to an existing handlebars+coffeescript meteor app and it keeps telling me there's no route.
also, im using iron-router if it makes any difference

**Comment by dr-dimitru** [comment]
@NROL39 while js+html versions on the way, could you post your code here? Which route is not found?

**Comment by NROL39** [comment]
````
Collections.files = new Meteor.Files
  collectionName: 'files'
  storagePath: '/home/cypher/dev/uploads',
  downloadRoute: '/downloads'
  debug: true # Let's see some stats - monitor browser's and server's console
````
I'm being told 
````
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/downloads/files/N7ttFaXurvyWGK3hF/original/N7ttFaXurvyWGK3hF.png"
````

**Comment by dr-dimitru** [comment]
Do you run this code on both server and client?

**Comment by NROL39** [comment]
Yes

**Comment by dr-dimitru** [comment]
what if you omit `downloadRoute` property? route found?

**Comment by NROL39** [comment]
Nope

**Comment by dr-dimitru** [comment]
iron-router separately installed?

**Comment by NROL39** [comment]
Yes, [this is my routes files](https://gist.github.com/NROL39/e5d2967b814dc48425d4)

**Comment by dr-dimitru** [comment]
Remove last two lines:
```coffee
Router.route "/downloads",
  name: "downloads"
```
Route will be created on collection initialisation

**Comment by dr-dimitru** [comment]
Alternatively try to wrap code into `Meteor.startup()`:
```coffee
Meteor.startup ->
   Collections.files = new Meteor.Files
     collectionName: 'files'
     storagePath: '/home/cypher/dev/uploads',
     downloadRoute: '/downloads'
     debug: true # Let's see some stats - monitor browser's and server's console
```

**Comment by NROL39** [comment]
Oh, yeah, i added this one thinking it might be looking for an existing route, it still fails to find a route

**Comment by dr-dimitru** [comment]
I didn't see anything wrong with it.
Any debug messages?

**Comment by dr-dimitru** [comment]
Could you please leave here exact line (and few alines before/after) which throws this `Oops, looks like there's no route on the client or the server for url...` error?

**Comment by NROL39** [comment]
Alright, figured it out, i had iron-router configured with autoStart set to false (no client-sided routes).

**Comment by dr-dimitru** [comment]
@NROL39 but `downloadRoute` is server-side only

**Comment by dr-dimitru** [comment]
@NROL39 solved?

**Comment by NROL39** [comment]
Yes, just make sure iron-router is started on the client before attempting to download

**Comment by achirkof** [comment]
@dr-dimitru Hi!
I found your package wery useful but it is hard to me understand how it works because i don't know coffee and jade. I use pure js and handlebars. Somebody already ask you about example but i did'n find them. Could you please make them? I see your very cool [example](https://github.com/VeliovGroup/ostrio-files-example). But it also coffee+jade and it is not described how to retreave image information from collection to show it on web page. 
Also I have question about mobile app. How to make remote DDP subscription from mobile meteor app to web server to show on mobile images uploaded on web?

**Comment by dr-dimitru** [comment]
HI @achirkof ,
I prefer communicate in English to let other community participants easily get our experience.
 1. Yes, I know about requests for js+html examples but juts don't have enough time to done it, meanwhile you always can convert [coffee to js](http://js2.coffee/) and [jade to html](http://html2jade.org/)
 2. To publish data from server to client, you need just to publish it as you usually do for other collections, [example](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/lib/files.collection.coffee#L23) 
 3. This [example app](https://github.com/VeliovGroup/Meteor-Files/tree/master/demo) is pretty expressive

**Comment by achirkof** [comment]
Thank you for reply. I just see you update version - super!
Yes, i use these converters to better understand logic of this plugin. 
And what about DDP connection from mobile metero app to web app server? Is it possible?
I need to show images uploaded from web om mobile and vice versa.

**Comment by dr-dimitru** [comment]
On mobile and web everything works over HTTP(S), currently there is no working way to stream binary data back from server to client over DDP (we are actually working on "binary player" which works over DDP with any binary data.)
For mobile app we just set `public` option to `true`

**Comment by achirkof** [comment]
I try this [demo app](https://github.com/VeliovGroup/Meteor-Files/tree/master/demo) and it is some [error](http://i.imgur.com/HDDedEz.png).

About mobile. I dont need to steam video. I just need to show posts with images like it shows on the web. As to show posts - no problem, but images - i don't understand how to do it.

**Comment by dr-dimitru** [comment]
You just save `fileObj` returned as second argument from `onUploaded` callback to some field into your posts collection. Then pass this `fileObj` field into `{{fileURL fileObj}}` helper. [Example](https://github.com/VeliovGroup/Meteor-Files#to-get-download-url-for-file-you-only-need-fileref-object-so-there-is-no-need-for-subscription) 

```html
<img src="{{fileURL fileObj}}" />
```

**Comment by dr-dimitru** [comment]
The error appears locally on your machine? Server has error log?

**Comment by achirkof** [comment]
Error appears on the server(digital ocean). Directory for file is writable and file exists.

**Comment by dr-dimitru** [comment]
Can you get server log?

**Comment by achirkof** [comment]
You can check it [here](http://smartworkout.ru:4000/).

**Comment by dr-dimitru** [comment]
You have somewhere constraint for localhost.
Do you passed `ROOT_URL` to env.variable ([docs](http://docs.meteor.com/#/full/meteor_absoluteurl))?

![screen shot 2015-10-30 at 10 20 50 pm](https://cloud.githubusercontent.com/assets/1686778/10855778/9b64f432-7f54-11e5-8ffc-e8d8e4d9faee.png)

**Comment by achirkof** [comment]
I have to set export `ROOT_URL="http://smartworkout.ru:4000/"` and now it is working. But i don't think it is problem in env variable, because other application working well and serves images.

**Comment by dr-dimitru** [comment]
Maybe other apps don't rely on it

**Comment by achirkof** [comment]
Sorry, but i still don't understand how to retreave image data on clent.
I have:
**Collection**:
```javascript
 Avatars = new Meteor.Files({
      storagePath: 'assets/uploads/avatars/',
      collectionName: 'avatars',
      debug: true
 });
```
**Publication**:
```javascript
Meteor.publish('avatars', function() {
     return Avatars.find();
});
```
**Subscription**:
```javascript
Tracker.autorun(function () {
      Meteor.subscribe('avatars');
 });
```
My **client code**:
```javascript
// Change avatar
     'change #uploadAvatar': function (event, template) {
         event.preventDefault();
         var files = event.currentTarget.files;
         _.each(files, function(file) {
             Avatars.insert({
                 file: file,
                 onUploaded: function(error, fileObj) {
                     if (error) {
                         console.log(error);
                     } else {
                          console.log(fileObj._id);
                     }
                 }
             });
         });
     }
```
and it's working good. 
After upload image i have one record in **Avatars** collection:
```
meteor:PRIMARY> db.avatars.find()
{
        "_id" : "9FcJ83YhijjdJmJpC",
        "name" : "av_m1_small.png",
        "extension" : "png",
        "path" : "assets/uploads/avatars/imDlHpetLxUgDPWRh.png",
        "meta" : {

        },
        "type" : "image/png",
        "size" : 6562,
        "versions" : {
                "original" : {
                        "path" : "assets/uploads/avatars/imDlHpetLxUgDPWRh.png",
                        "size" : 6562,
                        "type" : "image/png",
                        "extension" : "png"
                }
        },
        "isVideo" : false,
        "isAudio" : false,
        "isImage" : true,
        "_prefix" : "0d4dfef397887bb18344f2801fb2aa4123b2e5fea0f873a7427855b92471e855",
        "_storagePath" : "assets/uploads/avatars",
        "_downloadRoute" : "/cdn/storage",
        "_collectionName" : "avatars",
        "updatedAt" : ISODate("2015-11-01T10:19:11.935Z")
}
```
But when i try to find image information on client it returns empty [] array or [object Object].
![image](http://i.imgur.com/j1OMm5x.png)
I thing somtheng wrong in publication or subscribtion but can't understand what.
Could you help?
Thanks.

**Comment by achirkof** [comment]
So.. I found the right way )
It should be like this
**Publication**:
```javascript
Meteor.publish('avatars', function() {
     return Avatars.collection.find();
});
```
**helper**
```javascript
Template.registerHelper('avatar', function() {
        var userProfile = Meteor.users.findOne({
           _id: Meteor.userId()
        });
     if (userProfile && userProfile.userAvatarId) {
           var avatarId = userProfile.userAvatarId;
         var avatar = Avatars.findOne(avatarId).link();
         return avatar;
       } else {
           return false;
       }
  });
```
and **template**
```javascript
 <img src="{{avatar}}" class="img-circle m-b" alt="avatar">
```

**Comment by dr-dimitru** [comment]
Yes the second way is seems to be right, but we using the mongodb as database, which doesn't really good in relationship it's better to denormalise your  `userProfile` schema with full copy of object returned from `Meteor.Files.insert`, then simply pass it to `fileURL` helper.

**Comment by achirkof** [comment]
Thanks. I will try this way.

**Comment by achirkof** [comment]
It also will be wery helpful to create example with image manipulation(resize for example) using ImageMagick or GraphiskMagick.

**Comment by dr-dimitru** [comment]
Working with images or any other files is a bit out of this package purposes. But I thought about post about it on habrahabr (maybe on winter holidays)

**Comment by achirkof** [comment]
I try to do this and if it success I post result code here.

**Comment by dr-dimitru** [comment]
It should be something like this, with `cfs:graphicsmagick` package:
```coffee
# @var {object} bound - Meteor.bindEnvironment aka Fiber wrapper
bound = Meteor.bindEnvironment (callback) -> return callback()

###
@description Require "fs-extra" npm package
###
fs = Npm.require 'fs-extra'
Future = Npm.require 'fibers/future'

Meteor.methods
  createThumbnails: (fileRef) ->
    check fileRef, Object
    if this.userId
      ctFut  = new Future()
      isLast = false

      onThumbSaved = (error) ->
        ctFut.throw Meteor.log.error 500, "Collections.PostsFiles.collection.update() in [createThumbnails] Method", error if error
        ctFut.return true if isLast

      ctFut.throw Meteor.log.error 404, "File #{fileRef.path} not found in [createThumbnails] Method" if not fs.existsSync fileRef.path
      image = gm(fileRef.path).noProfile()

      sizes =
        big3x:
          width: 3300
        big2x:
          width: 2200
        big:
          width: 1100
        medium3x: 
          width: 2100
        medium2x:
          width: 1400
        medium:
          width: 700
        small3x:
          width: 960
        small2x:
          width: 640
        small:
          width: 480
        thumbnail500:
          width: 500
          square: true
        thumbnail250:
          width: 250
          square: true
        thumbnail100:
          width: 100
          square: true
        thumbnail50:
          width: 50
          square: true

      image.size (error, features) ->
        ctFut.throw Meteor.log.error 500, "image.size() in [createThumbnails] Method", error if error
        i = 0

        _.each sizes, (size, name) ->
          img = _.clone image
          bound ->
            path = "#{Collections.PostsFiles.storagePath}/#{name}-#{fileRef._id}.#{fileRef.extension}"
            if not size.square
              if features.width > size.width
                img.resize(size.width).interlace('Line').write path, (error) ->
                  bound ->
                    ++i
                    isLast = true if i is Object.keys(sizes).length

                    ctFut.throw Meteor.log.error 500, "image.resize() in [createThumbnails] Method", error if error
                    stat = fs.statSync path
                    upd = 
                      $set: {}
                    upd['$set']['versions.' + name] = 
                      path: path
                      size: stat.size
                      type: fileRef.type
                      extension: fileRef.extension
                    Collections.PostsFiles.collection.update fileRef._id, upd, onThumbSaved
              else
                ++i
                isLast = true if i is Object.keys(sizes).length

                upd = 
                  $set: {}
                upd['$set']['versions.' + name] = 
                  path: fileRef.path
                  size: fileRef.size
                  type: fileRef.type
                  extension: fileRef.extension
                Collections.PostsFiles.collection.update fileRef._id, upd, onThumbSaved
            else
              x = 0
              y = 0
              widthRatio = features.width / size.width
              heightRatio = features.height / size.width
              widthNew = size.width
              heightNew = size.width

              if heightRatio < widthRatio
                widthNew = (size.width * features.width) / features.height
                x = (widthNew - size.width) / 2

              if heightRatio > widthRatio
                heightNew = (size.width * features.height) / features.width
                y = (heightNew - size.width) / 2

              img.resize(widthNew, heightNew).crop(size.width, size.width, x, y).interlace('Line').write path, (error) ->
                bound ->
                  ++i
                  isLast = true if i is Object.keys(sizes).length

                  ctFut.throw Meteor.log.error 500, "image.resize() in [createThumbnails] Method", error if error
                  stat = fs.statSync path
                  upd = 
                    $set: {}
                  upd['$set']['versions.' + name] = 
                    path: path
                    size: stat.size
                    type: fileRef.type
                    extension: fileRef.extension
                  Collections.PostsFiles.collection.update fileRef._id, upd, onThumbSaved

      return ctFut.wait()
```

**Comment by achirkof** [comment]
> It's better to denormalise your userProfile schema with full copy of object returned from `Meteor.Files.insert`

It's not clear for me how to insert `Meteor.Files` object to `Meteor.Collection` schema. My `userProfile` it's just a field in defaul `Meteor.users` collection. That's why I define `Avatars` collection like `Avatars.Files`, and put to userProfile `_id` of image from `Avatars` collection.

**Comment by dr-dimitru** [comment]
Hi @achirkof , when:
```coffee
// Change avatar
     'change #uploadAvatar': function (event, template) {
         event.preventDefault();
         var files = event.currentTarget.files;
         _.each(files, function(file) {
             Avatars.insert({
                 file: file,
                 onUploaded: function(error, fileObj) {
                     if (error) {
                         console.log(error);
                     } else {
                          console.log(fileObj._id);
                     }
                 }
             });
         });
     }
```

You save `fileObj` returned as argument from `onUploaded` to current (or any other) user's profile.
```coffee
Meteor.users.update userId, $set: profile: avatar: fileObj
```

**Comment by achirkof** [comment]
@dr-dimitru thank you. it is working great.
