### ISSUE TITLE
Is that possible to update a record?

### ISSUE THREAD

**Issue by marcuslma** [VeliovGroup/Meteor-Files#291]
Hi, I have doubt.

Is that possible to update a record, changing it **file** and other extra fields inside **meta**?

For example, I am inserting the following image:
```
const uploadInstance = Images.insert({
  file: event.target.post_image.files[0],
  meta: {
    linkTo: event.target.post_link.value,
    status: event.target.post_status.value,
    createdAt: new Date(),
  },
  streams: 'dynamic',
  chunkSize: 'dynamic',
}, false);

...
```

This is an example of an image upload used for a post of the blog of my website.
If I want to update this post, changing its image and other stuff, how can I do this?
Thanks for your help.

**Comment by dr-dimitru** [comment]
Hello @marcuslma ,

Sorry for delayed response. Yes, you can operate with records as with regular Mongo.Collection via `FilesCollection#collection`, to update records right after upload use `onAfterUpload` hook.

Let me know if it helps.

**Comment by marcuslma** [comment]
Hello @dr-dimitru,

Sorry for my delayed response too.
I think my question is a little bit confused.
I want to know if I can update the image itself through an update.

**Comment by dr-dimitru** [comment]
@marcuslma ,

Thank you for clarification. No, it's not possible, update is simplified to remove-insert operation

**Comment by marcuslma** [comment]
Ok! Thanks for the explanation.

**Comment by dr-dimitru** [comment]
- Discussion at: #309 , please participate if you need this feature, see [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/309#issuecomment-272073549)
 - Related #323
