### ISSUE TITLE
Thumbnails error after updating Meteor

### ISSUE THREAD

**Issue by AdrianAbba** [VeliovGroup/Meteor-Files#295]
![unbenannt](https://cloud.githubusercontent.com/assets/9356382/20524956/587c72e4-b0bd-11e6-9e9d-1212d1cb17fc.png)

After updating to the newst Meteor version, the thumbnails doesnt work anymore, getting this error.
Any Ideas :x?

**Comment by dr-dimitru** [comment]
Hello @AdrianAbba ,

Sorry for delay. Yes, `storagePath` now always is function, see [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/server/image-processing.coffee#L39)

I wish it's already fixed on your end.

**Comment by dr-dimitru** [comment]
Adde note to [v1.7.6](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.6) release, assuming this one as solved
