### ISSUE TITLE
onAfterUpload is not getting called

### ISSUE THREAD

**Issue by ankibalyan** [VeliovGroup/Meteor-Files#297]
#### how to implement onAfterUpload config function

but no such event occurs once the file uploaded successfully. I need to generate a thumbnail of the image once the image gets uploaded. I'm trying to use `onAfterUpload` event function, but it is not getting called at anytime. same with 'onBeforeUpload' on the server side.

```
    export const Attachments = new FilesCollection({
      collectionName: 'uploads',
      allowClientCode: false,
      onBeforeUpload: function (file) {
        console.log(file)
        // Allow upload files under 10MB
        if (file.size <= 10485760) {
          return true;
        } else {
          return 'Please upload image, with size equal or less than 10MB';
        }
      },
      downloadRoute: 'cdn/storage/uploads',
      storagePath: '/app/uploads',
      onAfterUpload: function(fileRef) {
        console.log("on After upload \n",fileRef)
      },
      public: true,
    });
```

**Comment by ankibalyan** [comment]
PS: I'm uploading file via http upload method.

**Comment by ankibalyan** [comment]
@dr-dimitru if you can, please tell me why the issue like this, em not seeing if any one faces this issue. It is because of http upload?

**Comment by dr-dimitru** [comment]
Hello @ankibalyan ,

Sorry for delayed response.
I've tested your config on my end (via DDP and HTTP), `onAfterUpload` is always called.

Have you tried event model? Like:
```js
Attachments.on('afterUpload', function (fileRef) {
  console.log("on After upload \n", fileRef);
});
```

**Comment by dr-dimitru** [comment]
Hello @ankibalyan ,

Is this issue still exists on your end?

**Comment by ankibalyan** [comment]
Sorry for delayed response.
I've started working on couple of other features of the app, I'm handling this part in my http request now, instead of `onAfterUpload` which I don't think is fine place, just a quick fix around.

Is this 'onAfterUpload' a client side function? Or, this can be called on the server side, I was trying this on server side.

**Comment by dr-dimitru** [comment]
Server only

**Comment by ankibalyan** [comment]
okay! I'll try this out in brand new sample app on git, and let you know if this works for me.

**Comment by ankibalyan** [comment]
@dr-dimitru I've retried implementing file upload, here is [sample app](https://github.com/ankibalyan/meteorFileUpload). I'm still not getting call on `onBeforeUpload` and `afterUpload`. Don't know what's wrong in my implementation.

**Comment by dr-dimitru** [comment]
Hi @ankibalyan ,

I've checked your code. Now I see why it's not called - you're using 3rd party (not internal) upload.
So, to trigger `onAfterUpload` [here](https://github.com/ankibalyan/meteorFileUpload/blob/master/imports/api/attachments/http_upload.js#L47) you need to add [`proceedAfterUpload `](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) fourth argument

 1. Note only `onAfterUpload` will be called in this case
 2. [here](https://github.com/ankibalyan/meteorFileUpload/blob/master/imports/api/attachments/attachments.js#L15) use "hook" (a.k.a. callback) style, not events. Example:
```js
const Attachments = new FilesCollection({
  collectionName: 'uploads',
  allowClientCode: false,
  downloadRoute: 'cdn/storage/uploads',
  storagePath: 'uploads',
  public: true,
  onBeforeUpload() { /*...*/ },
});
```

**Comment by ankibalyan** [comment]
Thanks @dr-dimitru, It works, even with event style.
a lilttle doubt, is "3rd party upload" you mean to http REST API upload?
is the same reason valid to `onBeforeUpload` method as well for not getting called, and we should perform such input validations input like file size or file type [here](https://github.com/ankibalyan/meteorFileUpload/blob/master/imports/api/attachments/http_upload.js#L20) in commented lines of code.

**Comment by dr-dimitru** [comment]
> It works, even with event style.

There is no such event `onBeforeUpload` nor `beforeUpload `, it's a hook/callback which expects to return *Boolean* value

> a lilttle doubt, is "3rd party upload" you mean to http REST API upload?

Yes, it's not internal method of Meteor-Files package

> perform such input validations input like file size or file type here in commented lines of code.

Yes, this will work as long as you send solid file (not by chunks).

Hope that helps

**Comment by ankibalyan** [comment]
> It works, even with event style.

> There is no such event onBeforeUpload nor beforeUpload, it's a hook/callback which expects to return Boolean value

This works for the `afterUpload` event on `Attachments` `FilesCollection`.

yes, It helped. Thanks a lot, I'm closing this issue :)
