### ISSUE TITLE
Feature request: Add userId to addfile

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#298]
When inserting a new document on an user initiated upload, `userId` is set per default within the generated document. 

In our case we do not allow an optional`userId` per `SimpleSchema`: 

```
  userId: {
    type: String,
    // optional: true
  }
```

We use `addFile` to add fixtures, technically there is no `userId`, but it would be great if we could just pass `userId` to `addFile` to stay consistent with user initiated uploads.

Thanks a lot!

**Comment by dr-dimitru** [comment]
Hello @menelike 

As #299 is satisfied, could it be done in `onAfterUpload` with `proceedAfterUpload` flag?

**Comment by menelike** [comment]
@dr-dimitru 

I thought of something simple like https://github.com/VeliovGroup/Meteor-Files/pull/305, but not sure if `userId` should be part of `_dataToSchema`.

**Comment by dr-dimitru** [comment]
Done in [v1.7.6](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.6)
