### ISSUE TITLE
Avoid Random.id() on addFile 

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#299]
I think its reasonable to switch from `Random.id()` to `_id` as a part of the insert callback.
https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1412

Moreover, it should be noted that `fileRef` in the callback of `addFile` is **not** the inserted document like described in https://github.com/VeliovGroup/Meteor-Files/blob/dd59d886db69e8d74db3ebb5e1c7bde74f0b64c9/docs/addFile.md 

> callback {Function} - Triggered after new record is added to Collection. With error, and fileRef, where fileRef is a new record from DB

Instead it's a predicted document, as data is not fetched from the database after insert. This may also fail on the next calls like `proceedAfterUpload`. We subclass collection.insert and add some extra fields like timestamps, in those cases we `findOne(fileRef._id)` to fetch the real document) and pass it to `proceedAfterUpload` on callback.

**Comment by dr-dimitru** [comment]
Hello @menelike ,

Updated in https://github.com/VeliovGroup/Meteor-Files/commit/81856738b0650c009c59fc22afed6f06a26f5505 an in https://github.com/VeliovGroup/Meteor-Files/commit/6e0b3a994b33519bed4c5be6725ed76a06b31c79

**Comment by menelike** [comment]
@dr-dimitru works like a charm. Thanks a lot, like always, great work/support!

**Comment by dr-dimitru** [comment]
Published as [v1.7.6](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.6)
