### ISSUE TITLE
Adding extra fields to insert

### ISSUE THREAD

**Issue by kenshinman** [VeliovGroup/Meteor-Files#302]
Hi, Nice package.
Please how can I add extra fields to the insert object e.g/ an `uploadedAt ` field. 
I've tried collection hooks but it returns an error 
Thanks

**Comment by crapthings** [comment]
@kenshinman 

try to attach your custom field inside meta

```
const upload = this.FilesCollection.insert({
          file: file,
          streams: 'dynamic',
          chunkSize: 'dynamic',
          meta: {
            _id: Random.id(),
            mycustomfield: 'blah blah blah'
          }
        }, false)
```

**Comment by dr-dimitru** [comment]
Hi @kenshinman ,

Solution suggested by @kenshinman is correct.

 1. For security reasons on Client side you able to extend only `meta` object
 2. On server - to extend fileObj use `onAfterUpload` hook
 3. collection hooks may not work as *FilesCollection* is not equals to Mongo Collection
 4. To operate on Mongo Collection level - use sub-property `collection` of *FilesCollection* instance (`FilesCollection#collection`)

**Comment by kenshinman** [comment]
@dr-dimitru Thanks
