### ISSUE TITLE
Downloading file to host browser from app within Docker container

### ISSUE THREAD

**Issue by RavDanny** [VeliovGroup/Meteor-Files#303]
Firstly, just want to tell you that this a great package. Thanks very much!

### I'm having an issue:
I am running Meteor 1.4.1 inside a Docker container on Ubuntu 16.04 on a Virtualbox VM on a Windows host machine.
There I set up the Simplest Download Button demo app.
To display the app on my host browser I use URL 192.168.56.120:3000, which is the IP address of my VM.
To make the download link work, I realised that I needed to set the ROOT_URL environment variable, otherwise the download link address would be localhost:3000/... 
I set it to http://192.168.56.120:3000.

When I run the app, the link address is 192.168.56.120:3000/cdn/storage..., however the download fails with a "No file" error.

What am I doing wrong?

**Comment by crapthings** [comment]
i think you should move files out from docker, why u save files inside docker

**Comment by RavDanny** [comment]
I am developing an app which will run in Docker. Currently it stores files inside its container, which I would think is a natural place to store them.

In production, although the app will run in a Docker container, the files will be stored externally in an Openstack Swift object storage container.  I have modified the [AWS S3 upload code provided](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration) to set that up.  That code uploads the file to the server first and then sends it to the object store. It maintains the standard URL link for downloading, but then pipes the download request to the object storage. So even then, one still needs to get the standard URL link working. But it's not working at all.

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Could you please enable "debug mode", by passing `{debug: true}` to collection *Constructor*.
Let's see where and how requests is coming to your app.

Meanwhile could you confirm files existence on FS, or successfully moved to S3?

**Comment by RavDanny** [comment]
Hi @dr-dimitru ,
The demo is now working. I think the problem there was something trivial.

As for my app which uploads to Openstack Swift, it is successfully moving the file there, however the download is still not working. I'm assuming I have to configure the interceptDownload function differently for Openstack. Is here the appropriate place to discuss it?

**Comment by dr-dimitru** [comment]
> Is here the appropriate place to discuss it?

Yes, drop what you have now.
 1. Is it returns

**Comment by RavDanny** [comment]
Here's the code: [openstack.txt](https://github.com/VeliovGroup/Meteor-Files/files/653802/openstack.txt)

1. Yes
2. Debug logs:

```
I20161214-12:44:50.244(0)? [FilesCollection.storagePath] Set to: /path/to/data
=> Meteor server restarted
I20161214-12:44:53.031(0)? [FilesCollection] [find(undefined, undefined)]
I20161214-12:44:56.350(0)? [FilesCollection] [find(undefined, undefined)]

# After upload
I20161214-12:45:19.116(0)? [FilesCollection] [File Start Method] testfile.nc - 7rXNDDrh8MgjY9GNp
I20161214-12:45:19.120(0)? [FilesCollection] [Upload] [Start Method] Got #-1/7 chunks, dst: testfile.nc
I20161214-12:45:19.477(0)? [FilesCollection] [Upload] [DDP] Got #1/7 chunks, dst: testfile.nc
I20161214-12:45:19.495(0)? [FilesCollection] [Upload] [DDP] Got #2/7 chunks, dst: testfile.nc
I20161214-12:45:19.529(0)? [FilesCollection] [Upload] [DDP] Got #3/7 chunks, dst: testfile.nc
I20161214-12:45:19.533(0)? [FilesCollection] [Upload] [DDP] Got #7/7 chunks, dst: testfile.nc
I20161214-12:45:19.561(0)? [FilesCollection] [Upload] [DDP] Got #4/7 chunks, dst: testfile.nc
I20161214-12:45:19.593(0)? [FilesCollection] [Upload] [DDP] Got #5/7 chunks, dst: testfile.nc
I20161214-12:45:19.618(0)? [FilesCollection] [Upload] [DDP] Got #6/7 chunks, dst: testfile.nc
I20161214-12:45:19.626(0)? [FilesCollection] [Upload] [DDP] Got #-1/7 chunks, dst: testfile.nc
I20161214-12:45:19.655(0)? [FilesCollection] [Upload] [finish(ing)Upload] -> /path/to/data/7rXNDDrh8MgjY9GNp.nc
I20161214-12:45:19.668(0)? [FilesCollection] [Upload] [finish(ed)Upload] -> /path/to/data/7rXNDDrh8MgjY9GNp.nc
I20161214-12:45:19.734(0)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: 7rXNDDrh8MgjY9GNp
I20161214-12:45:19.750(0)? [FilesCollection] [unlink(7rXNDDrh8MgjY9GNp, original)]
I20161214-12:45:27.411(0)? [FilesCollection] [findOne({"_id":"7rXNDDrh8MgjY9GNp"}, undefined)]

# After download
I20161214-12:46:36.197(0)? [FilesCollection] [download(/cdn/storage/StoredFiles/7rXNDDrh8MgjY9GNp/original/7rXNDDrh8MgjY9GNp.nc?download=true, original)]
I20161214-12:46:36.206(0)? [FilesCollection] [serve(/path/to/data/7rXNDDrh8MgjY9GNp.nc, original)] [200]
```

**Comment by dr-dimitru** [comment]
@RavDanny 

This line:
```
I20161214-12:46:36.206(0)? [FilesCollection] [serve(/path/to/data/7rXNDDrh8MgjY9GNp.nc, original)] [200]
```

Clearly says `200`  is response code for download request. Looks like `404` coming from proxied request.

Could you confirm what accessing `path` (*line 66 from attached file*) directly from browser returns a file?

**Comment by RavDanny** [comment]
Good point. I was using the keystone authentication URL instead of the Openstack Swift URL.
Now that I have changed it, it is returning:
`Unauthorized. This server could not verify that you are authorized to access the document you requested.`
Can you suggest how to configure it to perform keystone authentication (along the lines of the server code I attached)?

**Comment by dr-dimitru** [comment]
> the case where the object storage upload fails?

Could you provide specific case?

Is AWS setup mention on [this line](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/lib/files.collection.coffee#L11) and at [this docs](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration)

```js
  client = knox.createClient({
    key: 'xxx',
    secret: 'yyy',
    bucket: 'zzz',
    region: 'jjj'
  });
```

Doesn't make a client which can pass through AWS Authorisation?

**Comment by RavDanny** [comment]
>>  the case where the object storage upload fails?

> Could you provide specific case?

Sure. When you perform an upload, the package uploads the file to your local file system. Once that upload is complete, it then triggers an `upload.on('end'... )` event hook in the upload template, and an `onAfterUpload` hook in the collection declaration, which uploads to object storage.

Now, I have had situations where the upload to the file system succeeds, triggering the `upload.on('end'...)` hook, but the upload to object storage has failed with an EAI_AGAIN error, and I am not aware how to let the client know that. I was wondering if any of your demos deal with this possibility.

On the other point:
> Is AWS setup mention on this line and at this docs

>  client = knox.createClient({
>    key: 'xxx',
>    secret: 'yyy',
>    bucket: 'zzz',
>    region: 'jjj'
>  });
> Doesn't make a client which can pass through AWS Authorisation?

It certainly does, but since I am working with Openstack Swift using the Keystone API and I was asking if you had any suggestions about how to configure the `interceptDownload` function to work with keystone authentication the way I managed to do in the Meteor method in the code I sent. I suppose I could just make another Meteor method for downloads, but I thought it would be better to use the `this.serve()` function and I thought you might have a suggestion as to how to do it. If not, that's fine.

**Comment by dr-dimitru** [comment]
@RavDanny on which stage `EAI_AGAIN` error is thrown, at `onAfterUpload`? If so, you need to deal it on server, only way to tell the Client about a problem is update document at MongoDB for example with `{'meta.error': 'EAI_AGAIN'}`.

I haven't faced `Openstack Swift` nor `Keystone API` yet. All you need to use `.serve()` is readable stream. If `Keystone API` can create a readable stream to AWS, or provide all you need to compose one via `request` - pass stream it into `.serve()` as last argument.

**Comment by RavDanny** [comment]
> on which stage EAI_AGAIN error is thrown, at onAfterUpload?
Right.

Ok. Thanks.

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Have you fixed this issue on your end?
Btw - make sure you not run into https://github.com/VeliovGroup/Meteor-Files/issues/324

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if issue still persists on your end.

**Comment by RavDanny** [comment]
Sorry, I was away from work.
Yes, it is fixed now.
Thanks
