### ISSUE TITLE
URGENT PLEASE: Files are deleted after App Rebuilds

### ISSUE THREAD

**Issue by kenshinman** [VeliovGroup/Meteor-Files#304]
Hello, Please I need help with this package. This is my first time. This is quite urgent please.
The files seem to be deleted from the upload directory `assets\app\uploads\Images` after the application is rebuilt. Is there a way to solve this please? Thanks.

**Comment by dr-dimitru** [comment]
Hi @kenshinman 

Yes, From the [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):
> On development stage: `yourDevAppDir/.meteor/local/build/programs/server`
> Note: **All files will be removed as soon as your application rebuilds or you run meteor reset.** To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

**Comment by kenshinman** [comment]
@dr-dimitru Wow! Thanks for the swift response, I'll give it a try and get back to you. Thanks a lot

**Comment by kenshinman** [comment]
@dr-dimitru Thanks this works well on my localhost:3000. One issue though, I am deploying with mupx which wraps my app in a docker container. Any suggestions on how to refer to the directory outside the docker container? Thanks a lot

**Comment by dr-dimitru** [comment]
@kenshinman no idea, never used mup/x
I'm suggesting to use 3rd party, like AWS S3.
If mum/x deploys MongoDB from dev stage, use - GridFS

**Comment by crapthings** [comment]
@kenshinman pm2-meteor is another choice for deploy without docker

**Comment by dr-dimitru** [comment]
Hi @kenshinman 

Is this issue solved?

**Comment by kenshinman** [comment]
No.
Tried pm2-meteor but it didn't work also. Only mupx seems to work but still deletes my files. But I found a temporary solution. i would save all the uploaded files (images) somewhere on the server before deploying a new build then upload to the new docker path . This seems to work for now.

The latest MUP is a kinda a solution because it allows you add volumes to your docker container on deployment which means you can have persistent files. Still working on it though. Thanks for the help.

**Comment by FEA5T** [comment]
@dr-dimitru 
storagePath: '../../../../../data', should be the default file storage location, even on a dev stage, or console warning should be thrown telling the user to set an upload path.  There is nothing wrong with a persistent local folder on a dev stage.

Production builds will always point to a remote folder/dfs/aws anyways.
