### ISSUE TITLE
Crash/Infinite loop when setting Session variable to upload instance

### ISSUE THREAD

**Issue by sammarshall61** [VeliovGroup/Meteor-Files#311]
When you set the upload instance to a session variable you get a max stack size reached, only started happening on newest release of Meteor and or Meteor-Files. When I remove the Session.set("currentUpload",this), it works fine, see code below.

````
Template.message_upload_form.events({
    'change #message_upload_form-input': function (e, template) {
        if (e.currentTarget.files && e.currentTarget.files[0]) {
            // We upload only one file, in case 
            // there was multiple files selected
            var file = e.currentTarget.files[0];
            if (!file) {
                return;
            }
            var uploadInstance = Files.insert({
                file: file,
                streams: 'dynamic',
                chunkSize: 'dynamic'
            }, false)

            uploadInstance.on('start', function() {
                Session.set("currentUpload", this);
            });

            uploadInstance.on('end', function(error, fileObj) {
                if (error) {
                    alert('Error during upload: ' + error.reason);
                } else {
                    var message = {
                            file: fileObj._id
                        };
                
                    Meteor.call("newMessage", message);
                }

                Session.set("currentUpload", false);

                Tracker.afterFlush(function () {
                    $('.messages').scrollTop($('.messages').prop("scrollHeight"));
                });
            });

            uploadInstance.start();
        }
    }
});
````

Here is the console error

````
[FilesCollection] [insert()]
ostrio_files.js?hash=5858908…:3204 [FilesCollection] [insert] [Tracker] [continue]
ostrio_files.js?hash=5858908…:3312 [FilesCollection] [insert] [.continue()]
ostrio_files.js?hash=5858908…:3235 [FilesCollection] [insert] using WebWorkers
ejson.js?hash=0f17ced…:492 Uncaught RangeError: Maximum call stack size exceeded(…)EJSON.clone @ ejson.js?hash=0f17ced…:492EJSON.clone @ ejson.js?hash=0f17ced…:517(anonymous function) @ ejson.js?hash=0f17ced…:531_.each._.forEach @ underscore.js?hash=cde485f…:157EJSON.clone @ ejson.js?hash=0f17ced…:530(anonymous function) @ ejson.js?hash=0f17ced…

````

**Comment by dr-dimitru** [comment]
Hello @sammarshall61 ,

That's weird, latest release has no changes for Client.
Could you post full stack-trace of `RangeError`? Need to see its roots

**Comment by dr-dimitru** [comment]
Hi @sammarshall61 

I've checked Session sources, it accepts only [`EJSONable`](https://github.com/meteor/meteor/blob/devel/packages/session/session.js#L15) values. 

Session build on top of ReactiveDict, which [stringifies passed values](https://github.com/meteor/meteor/blob/devel/packages/reactive-dict/reactive-dict.js#L61) and *FileUpload* class isn't EJSONable value.

You're safe to use *ReactiveVar* which accepts [any value](https://github.com/meteor/meteor/blob/devel/packages/reactive-var/reactive-var.js#L81) and doesn't modify it.

**Comment by sammarshall61** [comment]
Ah okay makes sense, thanks for looking into that! Love meteor-files btw!

Sam

**Comment by dr-dimitru** [comment]
@sammarshall61 I'm glad you found my work useful.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
