### ISSUE TITLE
[Security] it's possible to override any file

### ISSUE THREAD

**Issue by macrozone** [VeliovGroup/Meteor-Files#312]
It's currently possible to override any existing file if you know it's id.

If you start an upload (eg. with the http-fallback) the old file gets overwritten imediatly.

It's possible to fix this by adding a check for existing files in `onBeforeUpload` (on the server),
but i think we should do a "security first" approach and do this for the user.

Maybe we should also not rely on the id that the user provides. We could probably use the first request that initiates the upload to create a new document on the server and return the id of that document. The following requests would then upload the chunks.

Thoughts?

**Comment by dr-dimitru** [comment]
> Maybe we should also not rely on the id that the user provides. We could probably use the first request that initiates the upload to create a new document on the server and return the id of that document. The following requests would then upload the chunks.

It's possible in current implementation, as upload has 3 stages:
 - Send meta-data, make sure everything is ok, trigger `onBeforeUpload` and other hooks
 - Asynchronously upload all chunks
 - EOF signal, which triggers `onAfterUpload` and other hooks

Actually I don't remember why `_id` is appeared on the Client. I assume it was a part of requests to let define how file will be named on FS.

**Comment by dr-dimitru** [comment]
Hi @macrozone ,

Could you provide test case?
Currently it's not possible to remove `fileId` field from communication between Client and Server during upload process.
But it's possible to prevent new upload for file with same `_id`, see - https://github.com/VeliovGroup/Meteor-Files/commit/2d132faf08c2687ecba95f70a93e496c819dd7af
