### ISSUE TITLE
Dropzone js upload fails 

### ISSUE THREAD

**Issue by lightsnow0** [VeliovGroup/Meteor-Files#314]
I integrated dropzone js by npm in my project which works fine. 
By `var file = Dropzone.forElement("#theZone").getAcceptedFiles()[0];`, i get my file wich works fine. After, i divide the code in two parts, these two (error occurs even when all code is together) : 

```
var uploadInstance = Images.insert({
        file: file,
        fileName:'viola.jpg',
        streams: 'dynamic',
        chunkSize: 'dynamic'
    }, false);

    handleUpload(uploadInstance, e, template);
```

```
handleUpload = function(uploadInstance, e, template){
  console.log(template);
  try {
    console.log("Template: " + template )
    uploadInstance.on('start', function() {
      console.log(template);
        template.currentUpload.set(this);
    });

    uploadInstance.on('end', function(error, fileObj) {
        if (error) {
            alert('Error during upload: ' + error.reason);
        } else {
            alert('File "' + fileObj.name + '" successfully uploaded');
        }
        template.currentUpload.set(false);
    });
    uploadInstance.start();
  } catch (e) {
    console.log(e);
  }
}
```

when i want to start the upload, i get this error 
````
[FilesCollection] [insert] [Tracker] [continue]
ostrio_files.js?hash=6e0783d…:3030 [FilesCollection] [insert] [.continue()]
ostrio_files.js?hash=6e0783d…:2957 [FilesCollection] [insert] using WebWorkers
B…e.TemplateInstance {view: B…e.View, data: null, firstNode: form#theZone.dropzone.dz-clickable.dz-started, lastNode: button#setZone, _allSubsReadyDep: T…r.Dependency…}
main.js:105 TypeError: Cannot read property 'set' of undefined(…)`
```

TypeError: Cannot read property 'set' of undefined(…), why does this error comes up and what can i do to avoid it ?

**Comment by dr-dimitru** [comment]
```js
template.currentUpload
```

is undefined, I don't see where you define this *ReactiveVar*

**Comment by dr-dimitru** [comment]
Hi @lightsnow0 any news on your end

**Comment by lightsnow0** [comment]
Yes, that was the problem, thanks for your help

**Comment by dr-dimitru** [comment]
@lightsnow0 I'm glad it helped you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
