### ISSUE TITLE
image's link "http://localhost/cdn..." on production

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/Meteor-Files#315]
After deploying my app on production server, all image links stopped working.
Links look like http://localhost/cdn/storage/Images/zwf7bGsqbGzA/original/zwf7pcabGzA.jpg.
But if i manually change it to http://mysite.com/cdn/storage/Images/zwf7bGsqbGzA/original/zwf7pcabGzA.jpg, such link viewed as expected.
I get them by:
`<img src="{{imageFile id}}"`
from helper:
```
imageFile(id) {
    let imgFile = Images.findOne({_id:id});
    if (imgFile) return imgFile.link();
  }
```
in local dev app all images viewed also ok, 
maybe you have thought over this case?

**Comment by dr-dimitru** [comment]
Hi @valorloff 

Have you set `ROOT_URL=http://mtsite.com` env.var ?

**Comment by dr-dimitru** [comment]
@valorloff also you don't need to create a helper, there one defined for you - `{{fileURL file}}`, read more - https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper

**Comment by dr-dimitru** [comment]
@valorloff is this solved on your end?

**Comment by valorloff** [comment]
Yes!
Big thank for your help and wiki!
Is it true that the maximum number of files in storagePath should not exceed 10k?

**Comment by valorloff** [comment]
for the purpose of move to "fileURL" i changed my helper to: 
 ```
 imageRef() {
    return Images.findOne();
  }
```
in template:
`<img src="{{fileURL imageRef 'thumb'}}" `
don"t show image, what's wrong?

**Comment by dr-dimitru** [comment]
> Is it true that the maximum number of files (for performance reasons) in storagePath should not exceed 10k?

Where this statement came from? This is depends form FileSystem, read [this SO thread](http://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory)

If you think you might hit the limits, there is two options:
 1. Use 3rd party storage, like in DB GridFS or AWS, etc.;
 2. Check [this answer](https://github.com/VeliovGroup/Meteor-Files/issues/317#issuecomment-268376215) where I give a solution to build deep folder structure.

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

Can we close this issue? Is it solved on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
