### ISSUE TITLE
[Security] explain which fields need to be published at least

### ISSUE THREAD

**Issue by macrozone** [VeliovGroup/Meteor-Files#316]
When following the example, you're publish function might look like this:

```
Meteor.publish('images.one', function (imageId) {
      return Images.find(imageId).cursor;
  });
```
This will publish all fields of course, also some sensitive ones. 
But you usually only need a few of those to create download-urls:

```
const fields = {
  _downloadRoute: true,
  _collectionName: true,
  extension: true,
};
```

this is the minimum in case you do not need "public" files (served by another webserver).

We should explain that in the readme.

I also think we could reduce that even more. In fact, you would only need a field which tells you the url to download. Or maybe only the id, because the FilesCollection has all the other information.

**Comment by dr-dimitru** [comment]
This is only required fields for client:
```js
{
  _id: 1,
  extension: 1,
  _downloadRoute: 1
}
```

**Comment by macrozone** [comment]
id is always published, you don't need to include that. _collectionName is needed as well, because it is used in the link() function

**Comment by dr-dimitru** [comment]
@macrozone you'r right :)
Updated my answer above

**Comment by dr-dimitru** [comment]
Added in: https://github.com/VeliovGroup/Meteor-Files/commit/95c074aa4e345e1ba57ac5830c4273607f327dbd
