### ISSUE TITLE
[Security] Is it safe to store _lastSessionId into cookie?

### ISSUE THREAD

**Issue by macrozone** [VeliovGroup/Meteor-Files#319]
I noticed that meteor-files stores the _lastSessionId into a cookie, so that calls to image urls can be verified.

This _lastSessionId is short-living. If you close a tab, it is usually gone on the server.

But i am unsure if this opens a hole for xss-attacks where it is possible to hijack a session.

 Meteor does not use cookies for sessions because of that (https://blog.meteor.com/why-meteor-doesnt-use-session-cookies-e988544f52c9#.lyw0zb5j1)

Did anyone took a closer look on that?

**Comment by dr-dimitru** [comment]
Here is loooong discussion about this: https://github.com/VeliovGroup/Meteor-Files/issues/159

**Comment by dr-dimitru** [comment]
It's always a good idea to check referrer header.

**Comment by dr-dimitru** [comment]
Hello @macrozone ,

Can we close this one in favour of #159 ?

**Comment by macrozone** [comment]
@dr-dimitru you can close.
