### ISSUE TITLE
Error: [FilesCollection] [remove] Run code from client is not allowed! [401]

### ISSUE THREAD

**Issue by jdnichollsc** [VeliovGroup/Meteor-Files#321]
I'm having the following issue:

Error: [FilesCollection] [remove] Run code from client is not allowed! [401]

I'm trying to delete files from a server method, check my example:

```javascript
export const updateContract = new ValidatedMethod({
  name: 'contracts.update',
  validate: Contracts.simpleSchema().validator({ clean: true, filter: false }),
  run(contract) {
    if(contract.removedFileId){
        Files.remove({_id: contract.removedFileId }); //Remove old file!
        delete contract.removedFileId;
    }
    return Contracts.update(contractId, {
      $set: contract
    });
  }
});
```

Thanks in advance, Nicholls

**Comment by dr-dimitru** [comment]
Hello @jdnichollsc ,

Are you running this code from client?
Because this error is [Client only error](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2083) and can't appear on Server.

Please add `console.log(Meteor.isClient);` somewhere inside `ValidatedMethod` to make sure you're running it from Server, not a Client.

**Comment by jdnichollsc** [comment]
Ohh excellent my friend! The method runs on client and server, fixed validating before remove:

```
if(Meteor.isServer && contract.removedFileId){
        Files.remove({_id: contract.removedFileId });
        delete contract.removedFileId;
    }
```
Thanks, Nicholls

**Comment by dr-dimitru** [comment]
@jdnichollsc I'm glad it helped

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
