### ISSUE TITLE
new feature for file reupload

### ISSUE THREAD

**Issue by mizsha** [VeliovGroup/Meteor-Files#323]
Is possible to do something like ?

`Images.update(_id, { file: file })`

I need reupload previously uploaded file without change of _id, but in docs i dont find recipe. Thanks

**Comment by dr-dimitru** [comment]
Hello @mizsha ,

Currently this is not possible.
I'll keep it as feature request.

**Comment by dr-dimitru** [comment]
- Discussion at: #309 , please participate if you need this feature, see [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/309#issuecomment-272073549)
 - Related #291
