### ISSUE TITLE
load() doesn't return anything....

### ISSUE THREAD

**Issue by PolGuixe** [VeliovGroup/Meteor-Files#325]
I am using the load function to load some dummy images to the collection: 
```
          const loadImage = Meteor.wrapAsync(ProductImages.load, ProductImages);
          const currentImageCount = initalImagesCount + index;
          const loremPixelValue = (currentImageCount % 10) + 1;
          const path = `http://lorempixel.com/800/640/sports/${loremPixelValue}/`;
          try {
            const newImage = loadImage(path, {
              fileName: `${currentImageCount}.jpg`,
            }, () => { return true }, true);
            console.log(newImage);
            return newImage;
          } catch (error) {
            console.error(error);
          }
```
I am passing a callback that just returns true and a the `proceedAfterUpload` to true. I am expecting `load()` to return something. 

If I remove the callback and the `proceedAfterUpload` it works. See: 
```
          const loadImage = Meteor.wrapAsync(ProductImages.load, ProductImages);
          const currentImageCount = initalImagesCount + index;
          const loremPixelValue = (currentImageCount % 10) + 1;
          const path = `http://lorempixel.com/800/640/sports/${loremPixelValue}/`;
          try {
            const newImage = loadImage(path, {
              fileName: `${currentImageCount}.jpg`,
            });
            console.log(newImage);
            return newImage;
          } catch (error) {
            console.error(error);
          }
```

Any idea why it doesn't work?

**Comment by dr-dimitru** [comment]
Hi @PolGuixe ,

Is it works without wrapping into `Meteor.wrapAsync`?

**Comment by PolGuixe** [comment]
Without the `Meteor.wrapAsync`, the load() function returns a doc, but the rest of my code don't. Would it work with a promise instead?

**Comment by dr-dimitru** [comment]
@PolGuixe no, it has no Promises support. Use `Future` from [`fibers/future`](https://www.npmjs.com/package/fibers#futures)

**Comment by PolGuixe** [comment]
@dr-dimitru I think the problem is that `Meteor.wrapAsync` expect the last parameter of the function to be a callback. However in `.load()` the callback isn't the last parameter. I think that just changing the variable order in `.load()` could solve the problem.

**Comment by PolGuixe** [comment]
@dr-dimitru I've created a wrapped for `.load()` where the callback is the last parameter and it works.

DISCLAIMER: this is a hack. 

```
      const loadImage = Meteor.wrapAsync(function (path, opts, callback) {
        const {
          proceedAfterUpload,
          ...options,
        } = opts;
        ProductImages.load(path, options, callback, proceedAfterUpload);
      });

      const initalImagesCount = ProductImages.find().cursor.fetch().length;
      return _.chain(count)
        .times((index) => {
          const currentImageCount = initalImagesCount + index;
          const loremPixelValue = (currentImageCount % 10) + 1;
          const path = `http://lorempixel.com/800/640/sports/${loremPixelValue}/`;
          try {
            const newImage = loadImage(path, {
              fileName: `${currentImageCount}.jpg`,
              proceedAfterUpload: true,
            });
            return newImage;
          } catch (error) {
            console.error(error);
          }
        })
        .compact()
        .value()
```

**Comment by dr-dimitru** [comment]
> where the callback is the last parameter and it works.

That's what my first thought was. But after I've [checked the code](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1330) - turns out order of arguments is not strict, well it should be in a order as in docs, but any or arguments can be skipped.

Also `Meteor.wrapAsync` expects *Function* callback not a last argument, but next after passed arguments by you. So, if you don't pass `proceedAfterUpload` it should work.

Disclaimer:
*It's not a bad design, it's an extra-feature :)*

**Comment by PolGuixe** [comment]
> So, if you don't pass `proceedAfterUpload` it should work.
I can confirm that in that case it works, but if you want to use `proceedAfterUpload` it doesn't work. 😅

**Comment by dr-dimitru** [comment]
@PolGuixe right.

[v2.0](https://github.com/VeliovGroup/Meteor-Files/issues/309) will fix it.

**Comment by dr-dimitru** [comment]
@PolGuixe can we close this one for now?

**Comment by PolGuixe** [comment]
Yes. ;)
