### ISSUE TITLE
How to show custom Avatar image with Meteor-files + Utilities:avatar?

### ISSUE THREAD

**Issue by 1073113** [VeliovGroup/Meteor-Files#326]
Hi, Dr.Dimitri,
I'm using [meteor-utilities/avatar](https://github.com/meteor-utilities/avatar/) it to consolidate user avatar.
My question is how to show up my custom image (avatar) using `utilities:avatar` as i have an object `profile.avatarImg` in a `User Collection` with the properties `'_id', 'extension', '_downloadRoute', '_collectionName'`?

I used to show my custom avatar with Template Helper like so ..
```<img src="{{fileURL currentUser.profile.avatarImg 'thumbnail'}}">```
But what if I use `Utilities:avatar`?

`utilities:avatar` package has a configuration options that I think it needs the imageURL.
```
Avatar.setOptions({
  customImageProperty: function() {
    var user = this;
    // calculate the image URL here
    return user.profileImageUrl;
  }
});
```

Do I have to make an URL like so? :
```{file._downloadRoute}/{file._id}/{version}/{file._id}.{file.extension}```

What is the alternate options? thanks for you suggestion in advance . Thnks.

**Comment by dr-dimitru** [comment]
Hello @1073113 

I recommend to update User's profile in `onAfterUpload` callback or `afterUpload` event.

Example (*Server*): 
```js
Avatars = new FilesCollection({/*...*/});

Avatars.on('afterUpload', (fileRef) => {
  Meteor.users.update({_id: fileRef.userId}, {
    $set: {
      'profile.avatar': Avatars.link(fileRef)
    }
  });
});
```

**Comment by 1073113** [comment]
Hi Dr.Dimitri, 
Thank you for your suggestions.
My issue solved.
