### ISSUE TITLE
Can't upload base64 image 

### ISSUE THREAD

**Issue by lightsnow0** [VeliovGroup/Meteor-Files#328]
Currently, i'm trying to upload a canvas image. Normal files work great by the way. So I have my canvas and I'm sure it's correct because I append it always to my body, so there is not the mistake. And then, I convert it to an DataUrl and want to upload it as seen in the docs : 

```
var url = image.toDataURL();
    var uploadInstance = Images.insert({
      file: url,
      isBase64: true, // <— Mandatory
      fileName: 'pic.png' // <— Mandatory
    });
```
But I'm getting this error: 
`errorType
:
"Match.Error"
message
:
"Match error: Unknown key in field isBase64"
path
:
"isBase64"`

Any idea how to fix this ?

**Comment by dr-dimitru** [comment]
Hello @lightsnow0 ,

Please provide full stack-trace, and few first symbols of `url` (50 symbols will be fine).

**Comment by lightsnow0** [comment]
With stack-trace you mean the whole error code ? 

Here the first 50 symbols : 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAoAA`

**Comment by dr-dimitru** [comment]
Stack-trace is a chain of called methods, functions with file and line number
Need to see its roots.

What browser/OS you're on?

**Comment by lightsnow0** [comment]
I'm using Windows 10 and I'm testing this project in Chrome 55.0.2883.87 m (64-bit) an Firefox 

And here is the stack `"Error
    at errorClass.<anonymous> (http://localhost:3000/packages/check.js?hash=63d7478b74cadc04d378bc2266ea8bd1bf6849d8:113:27)
    at new errorClass (http://localhost:3000/packages/meteor.js?hash=e3f53db3be730057fed1a5f709ecd5fc7cae1229:570:17)
    at exports.check (http://localhost:3000/packages/check.js?hash=63d7478b74cadc04d378bc2266ea8bd1bf6849d8:67:15)
    at new UploadInstance (http://localhost:3000/packages/ostrio_files.js?hash=6e0783de76151476b03f6bc675350141c683e62d:2561:7)
    at FilesCollection.module.runModuleSetters.FilesCollection.insert (http://localhost:3000/packages/ostrio_files.js?hash=6e0783de76151476b03f6bc675350141c683e62d:2519:12)
    at Object.clickUploadCroppedImage (http://localhost:3000/app/app.js?hash=53e6809b7f08b4c7177f74285907f302184a06f3:245:35)
    at http://localhost:3000/packages/blaze.js?hash=983d07ae9423dd57f5b3c9f92b5593d2952f1b86:3718:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=983d07ae9423dd57f5b3c9f92b5593d2952f1b86:3687:12)
    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=983d07ae9423dd57f5b3c9f92b5593d2952f1b86:3717:25)
    at http://localhost:3000/packages/blaze.js?hash=983d07ae9423dd57f5b3c9f92b5593d2952f1b86:2560:30"`

**Comment by dr-dimitru** [comment]
What Meteor and Meteor-Files version you're on?
Error says `isBase64` option is not supported

**Comment by lightsnow0** [comment]
I created the project on the 31.December 2016 so i should this would be the current version .. 
METEOR@1.4.2.3
But ...ostrio:files@1.6.6 

But i just removed and reinstalled the package and it's still 1.6.6, so how to upgrade it ?

**Comment by dr-dimitru** [comment]
`meteor update`

**Comment by lightsnow0** [comment]
Yes, now the upload get accepted but now the images arent't uploaded well as seen on  the image but there is no error 
<img width="123" alt="mistake" src="https://cloud.githubusercontent.com/assets/15818979/21957609/4b01635c-da9a-11e6-91dd-010b742279ff.PNG">

Here the logs from the server 
` [FilesCollection] [File Start Method] test.png - LYeiwBCxAMzF7NLoe
I20170114-20:41:49.347(1)? [FilesCollection] [Upload] [Start Method] Got #-1/6 chunks, dst: test.png
I20170114-20:41:49.710(1)? [FilesCollection] [Upload] [DDP] Got #1/6 chunks, dst: test.png
I20170114-20:41:49.747(1)? [FilesCollection] [Upload] [DDP] Got #2/6 chunks, dst: test.png
I20170114-20:41:49.835(1)? [FilesCollection] [Upload] [DDP] Got #3/6 chunks, dst: test.png
I20170114-20:41:49.904(1)? [FilesCollection] [Upload] [DDP] Got #4/6 chunks, dst: test.png
I20170114-20:41:49.991(1)? [FilesCollection] [Upload] [DDP] Got #5/6 chunks, dst: test.png
I20170114-20:41:49.995(1)? [FilesCollection] [Upload] [DDP] Got #6/6 chunks, dst: test.png
I20170114-20:41:49.998(1)? [FilesCollection] [Upload] [DDP] Got #-1/6 chunks, dst: test.png
I20170114-20:41:50.000(1)? [FilesCollection] [Upload] [finish(ing)Upload] -> /imagesUpload/\LYeiwBCxAMzF7NLoe.png
I20170114-20:41:50.013(1)? [FilesCollection] [Upload] [finish(ed)Upload] -> /imagesUpload/\LYeiwBCxAMzF7NLoe.png
I20170114-20:41:50.017(1)? [FilesCollection] [_preCollectionCursor.observe] [removed]: LYeiwBCxAMzF7NLoe
I20170114-20:41:50.043(1)? [FilesCollection] [download(/cdn/storage/Images/LYeiwBCxAMzF7NLoe/original/LYeiwBCxAMzF7NLoe.jpg, original)]
I20170114-20:41:50.080(1)? [FilesCollection] [serve(/imagesUpload/\LYeiwBCxAMzF7NLoe.png, original)] [200]
I20170114-20:41:50.122(1)? [FilesCollection] [download(/cdn/storage/Images/LYeiwBCxAMzF7NLoe/original/LYeiwBCxAMzF7NLoe.png, original)]
I20170114-20:41:50.123(1)? [FilesCollection] [serve(/imagesUpload/\LYeiwBCxAMzF7NLoe.png, original)] [200]`

**Comment by dr-dimitru** [comment]
Please, see https://github.com/VeliovGroup/Meteor-Files/issues/324, probably it's your case. Just downgrade to `v1.7.5`

**Comment by lightsnow0** [comment]
Perfect, now it works :) 👍 
Thx for your support

**Comment by dr-dimitru** [comment]
Hooray! glad it helped

**Comment by thearabbit** [comment]
Excuse me, how to convert regular file[0] to `var url = image.toDataURL();`

**Comment by dr-dimitru** [comment]
@thearabbit [use `FileReader `](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL#JavaScript)

**Comment by thearabbit** [comment]
Thanks I will try
