### ISSUE TITLE
Can't set allow/deny rules 

### ISSUE THREAD

**Issue by lightsnow0** [VeliovGroup/Meteor-Files#337]
Currently, I try to protect my application with allow/deny rules and server methods. 
Server methods didn't worked. I tried to pass my base64 as an argument for Meteor.call but the server respond that he don't know "Images.insert"  

So I though allow/deny should work but i was wrong... In my lib folder, i create my database with 

```
this.Images = new Meteor.Files({
  debug: true,
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  storagePath: '/imagesUpload2/',
  onBeforeUpload: function (file) {
    // Allow upload files under 100MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});  
``` 

I tried just to block all insertions with

```
Images.deny({
    insert: function(){
      console.log("Hello");
      return true;
    }
  })
```
But the code gets never executed. 
Do you have any idea how to solve that ?

**Comment by dr-dimitru** [comment]
Hello @lightsnow0 ,

Use `onBeforeUpload` and return `false` or error string.
*FilesCollection* !== *Mongo.Collection*

[*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) has a lot of hooks to control data-flow.

If you're looking for security concerns - read [security related issues](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=is%3Aissue%20security)

**Comment by lightsnow0** [comment]
Ok, when I return false it works but when i wan't to check if a user has the permission to upload an image, i could call a servermethod to check the permission, the problem ( as far as i know ), it's not possible to use the result of a servermethod directly, so i need to save it inside a session, but sessions can be edited by the "bad" user. So how to solve this lack ? 

```
onBeforeUpload: function (file) {
    // Allow upload files under 100MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
      Meteor.call('hasWriteAccess', function(error, result){
      return result;
    });
```

**Comment by dr-dimitru** [comment]
Why not move code of `hasWriteAccess` to the `onBeforeUpload`?

Needs to be mentioned - `onBeforeUpload` is synchronous, you can not call for async method/function, well... you can, but it won't affect `onBeforeUpload` results

**Comment by lightsnow0** [comment]
Because I access permission fields in this rule which aren't published on the client. So if there is an opportunity to not publish these fields, i would love to do that. 

Ok, that means i've no possibility to interact with my server "during" onBeforeUpload. 
Is there any possibility to use the Image.insert method on the server, then i could ignore the onBeforeUpload hook and do my own verification on the server ?

**Comment by dr-dimitru** [comment]
As `onBeforeUpload` is runs on both Server and Client you can check not published data on server.
Just split code with `Meteor.isServer` into two parts for Server and Client.
Let me know if this will work for you.

**Comment by lightsnow0** [comment]
Did you mean like that ? 

```
onBeforeUpload: function (file) {
    // Allow upload files under 100MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
      var canUploadImages = false;
      if(Meteor.isServer){
       canUploadImages = Meteor.users.findOne(Meteor.userId()).write;
      }
      console.log(canUploadImages);
      return canUploadImages;
    }
```

**Comment by dr-dimitru** [comment]
Kind of... `canUploadImages` should be true on client in this case

**Comment by lightsnow0** [comment]
I modified the isServer part with a simple console.log, the strange point is that there is no output in the console, so the server code is never executed like that.  and i checked my database, it's true. 

Is there a way to use the insert method on the server ?

**Comment by dr-dimitru** [comment]
> I modified the isServer part with a simple console.log, the strange point is that there is no output in the console, so the server code is never executed like that. and i checked my database, it's true.

That's weird. Post code which you're using for upload. Please read #297 

> Is there a way to use the insert method on the server ?

Sure, tale a look on [`.write()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) and [`.load()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Load) methods

**Comment by lightsnow0** [comment]
I think write would be the right thing, but do I get it right that the image should already be on the server with this line of code ? `fs.readFile('/data/imgs/sample.png', function (error, data)` or how can I upload an Image like that ?

**Comment by dr-dimitru** [comment]
It accepts *Buffer*, there is many ways to get a *Buffer* at Node.js, one of them is readFile.

> or how can I upload an Image like that ?

From Client to Server - use `.insert()` method. What reason to use `.write()` method?

**Comment by lightsnow0** [comment]
I'm already using insert, but I think we talked about two different points. 
The main question is: Do i have the opportunity to get "server feedback" in the onBefóreUpload Hook because the idea with (Meteor.isServer) didn't worked. 
If not, i need to publish my information to the client and solve it like that

**Comment by dr-dimitru** [comment]
It's not worked as you used `Meteor.userId()` which is not available in `onBeforeUpload`, use `this.userId` instead. 

Please [read the docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor):
`onBeforeUpload` Context:
 - this.file
 - this.user()
 - this.userId

**Comment by dr-dimitru** [comment]
Hi @lightsnow0 ,

Any news on your end?

**Comment by lightsnow0** [comment]
Not really, i don't get how to executed code on the server in onBeforeUpload, when i return false, nothing works but when i return true, my server code gets executed

**Comment by dr-dimitru** [comment]
Have you read the docs?
You must return *Boolean* value. To continue upload - return `true`, to abort - `false`

**Comment by lightsnow0** [comment]
Yeah i read the docs. 

The problem is that i don't know what I'm doing wrong, why is this example not working ? 

```
onBeforeUpload: function (file) {
    // Allow upload files under 100MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
      var canUploadImages = false;
      if(Meteor.isServer){
        if(this.userId){
          canUploadImages = true;
        } else {
          canUploadImages = false;
        }
      }
      return canUploadImages;
     
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
```

**Comment by dr-dimitru** [comment]
Because on the *Client* `canUploadImages` is always `false`

**Comment by lightsnow0** [comment]
Yeah but why is it always false, can't the server code change the value ?

**Comment by dr-dimitru** [comment]
No, because first it runs on Client.
```js
onBeforeUpload: function (file) {
    // Allow upload files under 100MB, and only in png/jpg/jpeg formats
    if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
      if(Meteor.isServer){
        if(this.userId){
          return true;
        }
      } else {
         return true;
      }
      return false;
     
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
```

**Comment by lightsnow0** [comment]
Now that's it ! 
Perfect, thank you very much, exactly what i wanted !
