### ISSUE TITLE
Base64 Image after upload - image color changes and breaks in between

### ISSUE THREAD

**Issue by maabalaji** [VeliovGroup/Meteor-Files#338]
### I'm having an issue:
I do not know what am I doing incorrectly but many image after upload as Base64 format are changing colors and breaking up in between, Please suggest a solution.

Before upload progress bar and after uploaded the original image saving like that, 
![image](https://cloud.githubusercontent.com/assets/2073313/22439676/2d148cd0-e6f6-11e6-978d-0b18bfe5d2b9.png)

**Comment by dr-dimitru** [comment]
Hello @maabalaji ,

Could you post your upload code please. How do you get Base64 string?

**Comment by maabalaji** [comment]
I am using SlimImageCropper.com to crop an image and get base64 once i got the image then I am assigning it to a Img tag while uploading it to server, below is the code:

  //Crop And Upload
  cropDoneAndUpload(){
    var self = this;
    var cropImage = $('#imgCropper').slim('dataBase64');  
    $('#whileUpload').css('display', 'block');
    document.getElementById('whileUpload').setAttribute('src', cropImage[0].output.image);
    this.uploadProfilePic(cropImage[0].output.image, self);
    $('#imgCropper').slim('destroy');
  },

  //called in browser upload & camera upload picture
  uploadProfilePic(dataURI, self){
    //console.log('uploadProfilePic',dataURI);
    const uploadInstance = ImgUploads.insert({
        file: dataURI,
        isBase64: true,
        fileName: 'profile.jpeg'
    }, false);
    self.setState({
        uploading: uploadInstance, // Keep track of this instance to use below
        inProgress: true // Show the progress bar now
    });       
    //if error then set state error 
    uploadInstance.on('error', function (err, fileObj) {
        self.setState({
            error: true,
            errorMessage: err
        });        
    });
    //on progress show top progress bar.
    uploadInstance.on('progress', function (progress, fileObj) {
      if(self.isMounted()){
        // Update our progress bar
        self.setState({
            progress: progress.toString()
        });        
      }
    });
    //on upload done.
    uploadInstance.on('uploaded', function (error, fileObj) {
      //console.log(fileObj._id);
      if(self.isMounted()){
        // Reset our state for the next file
        self.setState({
            uploading: [],
            progress: '0',
            inProgress: false,   //Hide the progress bar now
            cropMode: false
        });
      }
      var loadedPImg = ImgUploads.findOne({_id:fileObj._id}).link();
      const fileUrl = {};
      fileUrl.fileUrl = loadedPImg;
      //console.log('editPhotoCallback'+fileObj._id);
      self.props.editPhotoCallback(fileObj._id);
      //console.log(self.props.publicId);
    });
    
    //call start upload
    uploadInstance.start();
  },

**Comment by dr-dimitru** [comment]
So, the `cropImage[0].output.image` passed to `src` of `img` element is different from one downloaded from server? Or all three original image, `cropImage[0].output.image`, and file from server is different?

**Comment by maabalaji** [comment]
the cropImage[0].output.image is base64 output of the cropped image, while uploading I set it to a img tag id=whileUpload and which is showing on my post first image with orange progress bar.
I did console.log of cropImage[0].output.image and checked which is fine, but uploaded to server saved image is got corrupted.
I am using Meteor, ReactJS


import { FilesCollection } from 'meteor/ostrio:files';

ImgUploads = new FilesCollection({
    debug:false,
    collectionName: 'Images',
    permissions: 0755,
    cacheControl: 'public, max-age=31536000',
    allowClientCode: false, // Disallow remove files from Client
    onBeforeUpload: function (file) {
        // Allow upload files under 10MB, and only in png/jpg/jpeg formats
        //console.log('before upload', file.size);
        //if (file.size <= 1024*1024*100 && /png|jpg|jpeg/i.test(file.extension)) {
        //    return true;
        //} else {
        //    return 'Please upload image, with size equal or less than 10MB';
        //}
        return true;
    },
   onAfterUpload: function(image) {
        //console.log('after  upload', image);       
   }
});

if (Meteor.isServer) {
    ImgUploads.denyClient();
    Meteor.publish('files.images.all', function () {
        return ImgUploads.find().cursor;
    });
} else {
    Meteor.subscribe('files.images.all');
}

**Comment by dr-dimitru** [comment]
1. Could you go to `storagePath` on your server/dev machine and check upload file directly. Is it corrupted?
 2. It happens only on one specific image file or you have tried several files and all of them resulting corrupted?
 3. That will be great if you can post here original image and corrupted result

**Comment by maabalaji** [comment]
1. Please see following file has html, once is I took base64 from console.log and another one is after upload image from datauri.net 
[UploadImgBase64Issue.zip](https://github.com/VeliovGroup/Meteor-Files/files/740711/UploadImgBase64Issue.zip)

![image](https://cloud.githubusercontent.com/assets/2073313/22445842/1cb7148e-e70f-11e6-8762-1f848ea0e496.png)

2. it happens random but I guess when there is bigger size like more than 500kb data files.

3. I have zipped the data in a temp.html file

**Comment by dr-dimitru** [comment]
1. I need confirmation what uploaded file located at `storagePath` is actually corrupted, not base64 dataURI
 2. Could you please check you're on the latest package version. This issue is known and was fixed.

**Comment by maabalaji** [comment]
1. I am not uploading files, I am uploading using base64 dataURI, please see one corrupted file attached here.
![9e3piezsdvxknxcho](https://cloud.githubusercontent.com/assets/2073313/22451114/59340d0a-e731-11e6-9c31-8ba48e4fbb0d.jpeg)

2. I have ostrio:files@1.7.7

**Comment by maabalaji** [comment]
I have updated to 1.7.8, but same result.
when this is know issue, could you please provide me the fix, I will look in the installed code weather it is being placed or not.

**Comment by dr-dimitru** [comment]
@maabalaji take a look on [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/214#issuecomment-244396741)

I'm suggesting to limit `streams` to `1`:
```js
uploadProfilePic(dataURI, self){
  //console.log('uploadProfilePic',dataURI);
  const uploadInstance = ImgUploads.insert({
      streams: 1,
      file: dataURI,
      isBase64: true,
      fileName: 'profile.jpeg'
  }, false);
  self.setState({
      uploading: uploadInstance, // Keep track of this instance to use below
      inProgress: true // Show the progress bar now
  });       
 /* ... */
}
```

 1. What browser you're on? Have you tried different browsers?
 2. What OS you're on?

Please answer questions above (*to test it on my end*), and let me know if `streams: 1` solved this ice on your end

**Comment by maabalaji** [comment]
Thanks I will try with streams:1 option.
I have done using Chrome Browser from Windows 7 & MacBookPro.
And also did on Simulator iPhone 6 Plus.

**Comment by dr-dimitru** [comment]
Hmm... Chrome Browser should work well.
Let me know if `streams: 1` solved this issue

**Comment by maabalaji** [comment]
Some reason it started giving following NaN and do not upload now.
 [Upload] [DDP Start Method] Got #-1/NaN chunks, dst: profile.jpeg

**Comment by maabalaji** [comment]
My guess this may be is issue, when there is only one chunk then awesome - more than one chunk then it got corrupted  

![image](https://cloud.githubusercontent.com/assets/2073313/22488084/cef68532-e7d5-11e6-9e92-c165b2154e23.png)

**Comment by dr-dimitru** [comment]
What if you try with `allowWebWorkers: false` flag?
And could you please post full debug log from both server and client (*as text please*)?

**Comment by maabalaji** [comment]
I got this:

I20170131-19:42:18.191(-6)? [FilesCollection] [File Start Method] profile.jpeg - 9tNXZsvN8tC59Mr87
I20170131-19:42:18.192(-6)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/3 chunks, dst: profile.jpeg
I20170131-19:42:18.309(-6)? [FilesCollection] [Upload] [DDP] Got #1/3 chunks, dst: profile.jpeg
I20170131-19:42:18.367(-6)? [FilesCollection] [Upload] [DDP] Got #2/3 chunks, dst: profile.jpeg
I20170131-19:42:18.372(-6)? [FilesCollection] [Upload] [DDP] Got #3/3 chunks, dst: profile.jpeg
I20170131-19:42:18.374(-6)? [FilesCollection] [Upload] [DDP] Got #-1/3 chunks, dst: profile.jpeg
I20170131-19:42:18.377(-6)? [FilesCollection] [Upload] [finish(ing)Upload] -> assets\app\uploads\Images\9tNXZsvN8tC59Mr87.jpeg
I20170131-19:42:18.417(-6)? [FilesCollection] [Upload] [finish(ed)Upload] -> assets\app\uploads\Images\9tNXZsvN8tC59Mr87.jpeg
I20170131-19:42:18.418(-6)? [FilesCollection] [_preCollectionCursor.observe] [removed]: 9tNXZsvN8tC59Mr87
I20170131-19:42:18.445(-6)? [FilesCollection] [download(/cdn/storage/Images/9tNXZsvN8tC59Mr87/original/9tNXZsvN8tC59Mr87.jpeg, original)]
I20170131-19:42:18.447(-6)? [FilesCollection] [serve(assets\app\uploads\Images\9tNXZsvN8tC59Mr87.jpeg, original)] [200]
I20170131-19:42:34.892(-6)? [FilesCollection] [_preCollectionCursor.observe] [removed]: P3FJ7PMNd4HACLjN4
I20170131-19:42:34.894(-6)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: assets\app\uploads\Images\P3FJ7PMNd4HACLjN4.jpeg
I20170131-19:42:34.972(-6)? Exception in queued task: TypeError: Cannot read property 'abort' of undefined
I20170131-19:42:34.972(-6)?     at Object.removed (D:\Siri_BMW7_1037\cliqups\.meteor\local\build\programs\server\packages\ostrio_files.js:959:44)
I20170131-19:42:34.973(-6)?     at [object Object].observeChangesCallbacks.removed (packages\minimongo.js:3762:28)
I20170131-19:42:34.974(-6)?     at self.applyChange.removed (packages\minimongo.js:3664:44)
I20170131-19:42:34.974(-6)?     at packages/mongo/observe_multiplex.js:183:30
I20170131-19:42:34.974(-6)?     at Array.forEach (native)
I20170131-19:42:34.975(-6)?     at Function._.each._.forEach (packages\underscore.js:139:11)
I20170131-19:42:34.975(-6)?     at Object.task (packages/mongo/observe_multiplex.js:177:9)
I20170131-19:42:34.975(-6)?     at [object Object]._.extend._run (packages\meteor.js:807:18)
I20170131-19:42:34.975(-6)?     at packages\meteor.js:785:14

**Comment by maabalaji** [comment]
Please see below are the logs (allowWebWorkers: false)

Client Browser:

[FilesCollection] [insert()]
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"Zxozg6sPTg2tnE9Q8"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(Zxozg6sPTg2tnE9Q8, original)]
EditOrCreateCliqOrUser.jsx:291 true:Zxozg6sPTg2tnE9Q8
ostrio_files.js?hash=a67c8a2…:3206 [FilesCollection] [insert] [Tracker] [continue]
ostrio_files.js?hash=a67c8a2…:3314 [FilesCollection] [insert] [.continue()]
ostrio_files.js?hash=a67c8a2…:3239 [FilesCollection] [insert] using MainThread
ostrio_files.js?hash=a67c8a2…:2936 loadFile profile.jpeg: 142.975ms
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"Zxozg6sPTg2tnE9Q8"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(Zxozg6sPTg2tnE9Q8, original)]
EditOrCreateCliqOrUser.jsx:291 true:Zxozg6sPTg2tnE9Q8
ostrio_files.js?hash=a67c8a2…:2887 insert profile.jpeg: 222.853ms
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"Zxozg6sPTg2tnE9Q8"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(Zxozg6sPTg2tnE9Q8, original)]
EditOrCreateCliqOrUser.jsx:291 false:Zxozg6sPTg2tnE9Q8
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"E8XEvo2qQhWw7oHPu"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(E8XEvo2qQhWw7oHPu, original)]
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"BcQnDjEFRmqoS7Sz5"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(BcQnDjEFRmqoS7Sz5, original)]
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"E8XEvo2qQhWw7oHPu"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(E8XEvo2qQhWw7oHPu, original)]
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"E8XEvo2qQhWw7oHPu"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(E8XEvo2qQhWw7oHPu, original)]
ostrio_files.js?hash=a67c8a2…:2621 [FilesCollection] [findOne({"_id":"E8XEvo2qQhWw7oHPu"}, undefined)]
ostrio_files.js?hash=a67c8a2…:805 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js?hash=a67c8a2…:3818 [FilesCollection] [link(E8XEvo2qQhWw7oHPu, original)]

[FilesCollection] [File Start Method] profile.jpeg - E8XEvo2qQhWw7oHPu
I20170201-13:58:28.698(-6)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/2 chunks, dst: profile.jpeg

Meteor Local Server:

I20170201-13:58:28.803(-6)? [FilesCollection] [Upload] [DDP] Got #1/2 chunks, dst: profile.jpeg
I20170201-13:58:28.828(-6)? [FilesCollection] [Upload] [DDP] Got #2/2 chunks, dst: profile.jpeg
I20170201-13:58:28.831(-6)? [FilesCollection] [Upload] [DDP] Got #-1/2 chunks, dst: profile.jpeg
I20170201-13:58:28.835(-6)? [FilesCollection] [Upload] [finish(ing)Upload] -> assets\app\uploads\Images\E8XEvo2qQhWw7oHPu.jpeg
I20170201-13:58:28.881(-6)? [FilesCollection] [Upload] [finish(ed)Upload] -> assets\app\uploads\Images\E8XEvo2qQhWw7oHPu.jpeg
I20170201-13:58:28.884(-6)? [FilesCollection] [_preCollectionCursor.observe] [removed]: E8XEvo2qQhWw7oHPu
I20170201-13:58:28.929(-6)? [FilesCollection] [download(/cdn/storage/Images/Zxozg6sPTg2tnE9Q8/original/Zxozg6sPTg2tnE9Q8.jpeg, original)]
W20170201-13:58:28.933(-6)? (STDERR) [FilesCollection] [download(/cdn/storage/Images/Zxozg6sPTg2tnE9Q8/original/Zxozg6sPTg2tnE9Q8.jpeg)] [_404] File not found
I20170201-13:58:28.955(-6)? [FilesCollection] [download(/cdn/storage/Images/E8XEvo2qQhWw7oHPu/original/E8XEvo2qQhWw7oHPu.jpeg, original)]
I20170201-13:58:28.957(-6)? [FilesCollection] [serve(assets\app\uploads\Images\E8XEvo2qQhWw7oHPu.jpeg, original)] [200]
I20170201-13:59:30.964(-6)? [FilesCollection] [find(undefined, undefined)]
I20170201-13:59:32.391(-6)? [FilesCollection] [find(undefined, undefined)]

**Comment by maabalaji** [comment]
The following setting fixed it:
chunkSize:1024 * 2048,

**Comment by maabalaji** [comment]
Boss:
FYI: I have tested 1.7.5 version works perfectly on chunks, I have tested it.

**Comment by dr-dimitru** [comment]
Hello @maabalaji ,

Well but it fails on 1.7.8, right? Have you tried any other versions?

**Comment by maabalaji** [comment]
Yes 1.7.8 version fails, and I have tried in 1.7.6 also failed.

**Comment by menelike** [comment]
I can confirm that this problem does not exist on `1.7.5` but on `1.7.8`.

**Comment by dr-dimitru** [comment]
Hi @menelike ,

What happens if you set `allowWebWorkers: false` any positive changes?
I suspect WebWorker as root of this issue

**Comment by dr-dimitru** [comment]
Reproduced on my end, confirmed,e as stable bug.
Currently no idea why this happens.

@maabalaji as workaround I can suggest to use `new Blob()` constructor to create a *File* from base64 string and upload it as regular file.

**Comment by dr-dimitru** [comment]
Hello @maabalaji and @menelike ,

Thank you for reporting about this.
Should be solved in [latest release](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.10)

Fell free to reopen it.

**Comment by menelike** [comment]
I confirm that this works, tested against ostrio:files@1.7.11

Great job!
