### ISSUE TITLE
Meteor Files go missing after upload and service reset

### ISSUE THREAD

**Issue by jessejamesrichard** [VeliovGroup/Meteor-Files#339]
I'm uploading images and audio files using your library. It works well. One strange problem I've noticed, is that no matter what, the images stick around. However, if I restart meteor I lose all the audio files. Any idea why that might be?

**Comment by dr-dimitru** [comment]
Hello @jessejamesrichard and @saadbinsaeed,

From [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):
> __Note: All files will be removed as soon as your application rebuilds or you run meteor reset.__ To keep your storage persistent during development use an absolute path outside of your project folder, e.g. /data directory.

**Comment by jessejamesrichard** [comment]
Strange, all my images remain. Just my audio disappears. 

In production, what is the preferred method for file storage? A third party?

**Comment by dr-dimitru** [comment]
Make sure you're on latest package version, described behaviour sound like you're run into #324

**Comment by dr-dimitru** [comment]
Hi @jessejamesrichard ,

Any news on your end?

**Comment by dr-dimitru** [comment]
Hi @jessejamesrichard ,

Is this solved on your end?

**Comment by jessejamesrichard** [comment]
Sorry for the late reply. I moved exclusively to AWS since the local save seemed inconsistent.

**Comment by dr-dimitru** [comment]
@jessejamesrichard glad it's solved

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
