### ISSUE TITLE
[Publications] Problem with limits in publications

### ISSUE THREAD

**Issue by gaillota** [VeliovGroup/Meteor-Files#340]
Hi guys,

I have a problem with limits in publications. Whenever I use this code
```
const a = Photos.find({
    "meta.albumId": albumId
}, {
    limit: 10,
});

console.log(a.count());
```
The output is `18`, the number of photos in the album. I also tried with `Photos.collection.find` but I end up with the same output.
Is it normal behaviour ?
It's really annoying because I want to paginate my album and it changes the logic whether all photos are publish to the client or not.

Any ideas why ?

**Comment by dr-dimitru** [comment]
Hi @gaillota ,

Is it solved?

**Comment by gaillota** [comment]
Yes, it actually works, I don't know why.
Does the count function works on the whole query, regarding of the `limit `and `skip `parameters ?

Thanks for the quick reply btw.

**Comment by dr-dimitru** [comment]
Behaviour is same as on regular Meteor's Mongo.Collection

**Comment by gaillota** [comment]
Would you rather use `Photos.find().cursor` or `Photos.collection.find()` ?

**Comment by dr-dimitru** [comment]
You will have 100% equal results. It's just aliases.
Moreover `Photos.collection.find()` will be slightly (*human will not see difference*) faster.

**Comment by gaillota** [comment]
Alright, thanks for the answers.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
