### ISSUE TITLE
After redeploy images are not accessible, but still in mongo

### ISSUE THREAD

**Issue by gustavohr** [VeliovGroup/Meteor-Files#341]
Hello everyone, I'm having an issue and cannot find where my code is failing. I have added the volumes into the mup.json file and the images are well stored in the mongo. When I try to redeploy the app it cannot find the images. Inside the mongo the images path is "/images/....jpg" but the path that the app is trying to access is "/cdn/storage/Images/6zvBLJ622yizjkweM/original/...jpg" My point is that I'm sure that images are not being removed because I can see them inside the mongo, but the access path seems to be wrong. Before redeploying the image is fine but after redeploying the path seems to be broken. Thanks in advance for any help!

**Comment by dr-dimitru** [comment]
Hello @gustavohr ,

 1. What do you mean by "redeploy"? Have you changed physical/virtual machines?
 2. Where `storagePath` is pointing?
 3. Do not care about download path it's just fence for middleware

**Comment by gustavohr** [comment]
Hello @dr-dimitru, I have my app running in modulus.io when I upload an image everything seems to be working right, but when I deploy again my app the image path is broken... I think the problem is that the `.link()` method is returning the download path and not the actual path of the image, so when I deploy again my app the path is broken... My cuestion is how I get the real path?? When I look in the mongo the path is `/images/imageId.jpg` but I try to access to that path and the app tells me that there is no rute for that path.

**Comment by dr-dimitru** [comment]
1. Does modulus.io has persistent storage?
 2. Is there any chance `/image` got overwritten during deploy?
 3. Download URI is different from storage path in mind of security to avoid reverse engineering of your server infrastructure. Real storage path is stored in [`_storagePath`](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)
 4. Best way to make sure files is not gone is go to your server and `ls -la /images`
 5. Also please note what `/images` is not equal to `images`, while first is absolute path to FS root, second is relative to NodeJS process. And you may run into issue described at [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):
> Note: __All files will be removed as soon as your application rebuilds__ or you run `meteor reset`. To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

**Comment by gustavohr** [comment]
Thanks for answering! 

1. Yes, and I can check it when accessing to mongo... files still there.
2. No, images seems to be there.
3. The path that `.link()` return me is this one `/cdn/storage/Images/6zvBLJ622yizjkweM/original/...jpg`
4. Files are stored in and I can have access to them using Robomongo
5. When I try to use `/images` instead of `images` I get this error: `Error: [FilesCollection.Images] Path "/images" is not writable! [401]`.

**Comment by dr-dimitru** [comment]
1. Records at Mongo doesn't means files still exists at FS
 2. So, it was wiped on deploy
 3. Looks good
 4. Didn't get how Robomongo is relative to FS
 5. Create and set permissions on `/images`:
   - Create `mkdir /images`
   - Set permissions `chmod -R 755 /images`
   - Set owner if NodeJS runs under specific user: `chown -R user:user /images`

**Comment by gustavohr** [comment]
1. You are rigth I thought that having the record at Mongo meant the file was stored at FS
2. The deployment overwrote the files
3. I solved it by storing the files in Mongo via GridFS

Working now, files are not being removed!

One question: Is there any disadvantage on storing the files on Mongo via GridFS?

Thanks for yout help!

**Comment by dr-dimitru** [comment]
> Is there any disadvantage on storing the files on Mongo via GridFS?

RAM and other resources consumption, as Mongo tries to keep everything in RAM.
Might be slower on HDD unless chunks in RAM.

**Comment by gustavohr** [comment]
Ok! thanks!

**Comment by dr-dimitru** [comment]
I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
