### ISSUE TITLE
Share files with others

### ISSUE THREAD

**Issue by gaillota** [VeliovGroup/Meteor-Files#342]
Hello,

I'm having trouble sharing photos with other users. I'm able to share the Mongo documents, but when a user other than the owner tries to access the file, he gets a 404 "File Not Found :(".

I tried to change the `public` attribut to `true` but of course it doesn't change anything. So I'm guessing it's an issue on the FS level ? Or maybe the headers ?

What should I do to allow some users other than the owner access his files ?

**Comment by dr-dimitru** [comment]
Hello @gaillota ,

`public` flag is not about access permissions - is about how proxy server (*if any used*) will serve files from "public" directory.

Are you using `protected` flag?

**Comment by gaillota** [comment]
No I'm not. Here's an exemple of documents from my collection:
```
{
        "_id" : "k65MMxPYiTPnou7te",
        "size" : 32404,
        "type" : "image/jpeg",
        "name" : "wendys.jpg",
        "meta" : {
                "albumId" : "zhBiet8wXC3BDiKDy"
        },
        "extension" : "jpg",
        "userId" : "jtBCtW6HEPEsozZR5",
        "path" : "assets/uploads/photos\\k65MMxPYiTPnou7te.jpg",
        "versions" : {
                "original" : {
                        "path" : "assets/uploads/photos\\k65MMxPYiTPnou
7te.jpg",
                        "size" : 32404,
                        "type" : "image/jpeg",
                        "extension" : "jpg"
                }
        },
        "isVideo" : false,
        "isAudio" : false,
        "isImage" : true,
        "isText" : false,
        "isJSON" : false,
        "isPDF" : false,
        "_downloadRoute" : "/cdn/storage",
        "_collectionName" : "photos",
        "_storagePath" : "assets/uploads/photos",
        "public" : false
}

**Comment by dr-dimitru** [comment]
@gaillota ,

Post your *FilesCollection* definition

**Comment by gaillota** [comment]
```
export const Photos = new FilesCollection({
    collectionName: 'photos',
    allowClientCode: false,
    storagePath: 'assets/uploads/photos',
    onBeforeUpload: function (file) {
        // Allow upload files under 10MB, and only in png/jpg/jpeg formats
        if (file.size <= 10485760 && isImage(file)) {
            return true;
        }
        return 'Please upload an image, with size equal or less than 10MB';
    }
});

const isImage = file => file.type.indexOf("image") === 0 && /png|jpg|jpeg|gif/i.test(file.extension);
```

**Comment by dr-dimitru** [comment]
1. Are you on windows? (Just noticed double-backslash here: `assets/uploads/photos\\k65MMxPYiTPnou7te.jpg`)
 2. So, you're saying only one user can view/download uploaded files? Could you describe this behaviour more detailed
 3. Could you confirm uploaded files exists at `assets/uploads/photos` ?
 4. What version of Meteor and Meteor-Files you're on?

**Comment by gaillota** [comment]
1. Yes I'm on Windows
2. A user, let's say Dumbledore, can create albums, in which he can uploads photos (hence the `"meta.albumId"` in my FilesCollection). Then he can share albums with other users, let's say Voldemort. The problem is that when I log with Voldemort's account, the album that Dumbledore shared with him appears in the list of albums. But the photos inside the album don't. And when I try to copy/paste any photo url in the browser, I get a "File Not Found :(".
3. Funny you said that, I was seaching for the actual file when you replied. And I could not find the folder (assets/uploads/photo) in my directory's app. Is it normal ?
4. I'm on `ostrio:cookies@2.0.5`, `ostrio:files@1.7.5` and `METEOR@1.4.2.3`

**Comment by dr-dimitru** [comment]
1. Okay... hope it's not root of the issue, but might be
 2. Complicated... How about to test more simple cases to make sure files is uploaded and available
 3. No, [read FAQ](https://github.com/VeliovGroup/Meteor-Files#faq)
 4. Please update package to the [latest version](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.8)

**Comment by gaillota** [comment]
Ok, I tried the following:
- I changed the storagePath to an absolute path `/cdn/storage/uploads/photos`,
- I updated the package to the latest version.

I don't know which one did the trick, but now it works ! 
Still, I can't find the files in my app directory though, that's weird...

Anyway, thank you for your help.
