### ISSUE TITLE
config.storatePath when set /MeteorImageDataFolder - how to find physical path

### ISSUE THREAD

**Issue by maabalaji** [VeliovGroup/Meteor-Files#343]
### I have a question:

ImgUploads = new FilesCollection({
    debug: true,
    collectionName: 'Images',
    permissions: 0755,
    cacheControl: 'public, max-age=31536000',
    allowClientCode: false, // Disallow remove files from Client
    streams: 'dynamic',
    chunkSize: 'dynamic',
    allowWebWorkers: false,
    storagePath:'/MeteorImagesDataFolder',
    onBeforeUpload: function (file) {

Where to find the Physical path:
using Windows 10 Pro.

[FilesCollection] [File Start Method] profile.jpeg - e77orokQe3uqGBaMZ
I20170203-13:40:24.361(-6)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: profile.jpeg
I20170203-13:40:24.489(-6)? [FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: profile.jpeg
I20170203-13:40:24.493(-6)? [FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: profile.jpeg
I20170203-13:40:24.496(-6)? [FilesCollection] [Upload] [finish(ing)Upload] -> /MeteorImagesDataFolder\e77orokQe3uqGBaMZ.jpeg
I20170203-13:40:24.543(-6)? [FilesCollection] [Upload] [finish(ed)Upload] -> /MeteorImagesDataFolder\e77orokQe3uqGBaMZ.jpeg
I20170203-13:40:24.546(-6)? [FilesCollection] [_preCollectionCursor.observe] [removed]: e77orokQe3uqGBaMZ
I20170203-13:40:24.566(-6)? [FilesCollection] [download(/cdn/storage/Images/e77orokQe3uqGBaMZ/original/e77orokQe3uqGBaMZ.jpeg, original)]
I20170203-13:40:24.568(-6)? [FilesCollection] [serve(/MeteorImagesDataFolder\e77orokQe3uqGBaMZ.jpeg, original)] [200]
I20170203-13:40:28.193(-6)? [FilesCollection] [download(/cdn/storage/Images/Z2qT5YTX5ACNpZDzd/original/Z2qT5YTX5ACNpZDzd.jpeg, original)]

**Comment by dr-dimitru** [comment]
Please use windows slashes or [`path.sep`](https://nodejs.org/api/path.html#path_path_sep) in `storagePath`
And you should be able to find at root of system dive

**Comment by maabalaji** [comment]
Yes, Thank you.

**Comment by dr-dimitru** [comment]
Hi @maabalaji ,
Can we close this one?
