### ISSUE TITLE
Image Load with local but not with IP

### ISSUE THREAD

**Issue by maabalaji** [VeliovGroup/Meteor-Files#344]
### I'm having an issue:
Hi,
With the following Path I am able to see the Image
http://localhost:3000/cdn/storage/Images/XgEj5BDC6xdkRfgsc/original/XgEj5BDC6xdkRfgsc.jpeg

where as when I use same image with IP
http://192.168.0.18:3000/cdn/storage/Images/XgEj5BDC6xdkRfgsc/original/XgEj5BDC6xdkRfgsc.jpeg

the image is not showing up could you please let me know what am I missing in config?

**Comment by dr-dimitru** [comment]
Hello @maabalaji ,

Try to set `ROOT_URL='http://192.168.0.18:3000'` environment variable
Similar issue is discussed [here](https://github.com/VeliovGroup/Meteor-Files/issues/347)

**Comment by maabalaji** [comment]
Thank you @dr-dimitru
