### ISSUE TITLE
"uploaded" / "end" event not fired

### ISSUE THREAD

**Issue by deeeed** [VeliovGroup/Meteor-Files#345]
Hi,

I am experiencing a strange issue when I deploy my app in production.
The "uploaded" and "end" events are never fired:

Here is an example of how I upload the file:
```
 let uploadInstance = UserPhotos.insert({
            file: file,
            transport: 'ddp',
            isBase64: false,
            streams: 'dynamic',
            chunkSize: 'dynamic'
        }, false);

        uploadInstance.on('start', function() {
            console.debug("Start upload", this);
            tpl.selectedFile.set(false);
            tpl.currentUpload.set(this);
        });

        uploadInstance.on('progress', function(progress, fileData) {
            console.debug("upload progress", progress, fileData);
        });

        uploadInstance.on('uploaded', function(error, fileData) {
            console.debug("uploaded", error, fileData);
        });

        uploadInstance.on('end', function(error, fileRef) {
            tpl.currentUpload.set(false);
            if(error) {
                sAlert.error(TAPi18n.__("common.errors.error"));
                console.debug("error upload", error);
                return;
            }

            console.debug("upload complete!");

            tpl.selectedFile.set(fileRef);
        });

        uploadInstance.start();
```
Nothing special, it works perfectly locally and on my test server but on my production server events are not fired...

Any idea what could prevent it ?

I also have another problem if I use 'http' transport, I get the following exception:
[FilesCollection] [Upload] [HTTP] Exception: [TypeError: base64 is not a function]

**Comment by dr-dimitru** [comment]
Hello @deeeed ,

`base64 is not a function` sounds like you're on old package version, where base64 is not yet supported. Similar issue is discussed [here](https://github.com/VeliovGroup/Meteor-Files/issues/328#issuecomment-272644569)

Let me know if it helps.

**Comment by deeeed** [comment]
Hi @dr-dimitru  ,

Actually I am using 1.7.8, which should be the latest version.
For the first problem I found the solution, it was my mistake I had an environment setting on production that was messing up my configuration...
I still have the base64 issue, which I will investigate later.

Thanks for the help

**Comment by dr-dimitru** [comment]
Hello @deeeed ,

Base64 issue should be solved in [latest release](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.10)
