### ISSUE TITLE
[Bug] Addfile ignores fileName

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#346]
`Addfile` generates an own filename (`doc.name`) no matter what, `opts.fileName` is always ignored. Tested against `v1.7.5` and `v1.7.8`.

Thanks a lot!

**Comment by dr-dimitru** [comment]
Hello @menelike ,

This is not supported, at least yet, going to add this

**Comment by dr-dimitru** [comment]
Hi @menelike please see v1.7.9

**Comment by menelike** [comment]
Thanks a lot @dr-dimitru 

I actually thought that this feature exists because it's described in https://github.com/VeliovGroup/Meteor-Files/wiki/addFile ? Maybe I got something wrong.

Anyway, great work, thanks a lot!
