### ISSUE TITLE
Uploaded files keep showing Localhost:3000

### ISSUE THREAD

**Issue by rikyperdana** [VeliovGroup/Meteor-Files#347]
I've been stuck for three days for this problem, any working solution will be so helpful
Here is my code at server/startup.js :
`
Meteor.startup(function() {
  Meteor.absoluteUrl.defaultOptions.rootUrl = 'http://my_ip:my_port',
  process.env.rootUrl = 'http://my_ip:my_port'
})
`
But nothing worked, each uploaded files keep showing link localhost:3000/cdn/storage/blablabla

**Comment by dr-dimitru** [comment]
Hello @rikyperdana 

Set environment variable [`ROOT_URL`](http://docs.meteor.com/api/core.html#Meteor-absoluteUrl) to `http://my_ip:my_port`.

This should fix your issue.
Let me know if it helps.

**Comment by rikyperdana** [comment]
What a quick reply :D 
I use Ubuntu 14.04, Meteor 1.4
I inserted ROOT_URL='http:my_ip:my_port/' to /etc/environment
And I also typed export ROOT_URL='http:my_ip:my_port/'
Yet nothing worked

**Comment by dr-dimitru** [comment]
In your console type this to run meteor (env.vars defined before command):
```shell
ROOT_URL='http://my_ip:my_port' meteor
```

**Comment by rikyperdana** [comment]
Thank God, it worked, bless you all veliov group member
I'm crying ;(

**Comment by dr-dimitru** [comment]
@rikyperdana ,

Happy to help :) . Next time do not hesitate to ask right away after you have faced an issue.
And thank you for the choice to use this lib.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by rikyperdana** [comment]
I don't mind breaking my piggy bank for this help :)
![veliov_group_payment](https://cloud.githubusercontent.com/assets/11875540/22767218/8d92e95e-eeac-11e6-8192-760824a821f2.png)
