### ISSUE TITLE
Question: play video as 206 status code

### ISSUE THREAD

**Issue by j1016h** [VeliovGroup/Meteor-Files#348]
Hi,
I want to build a video streaming website using Meteor-Files. I use GridFS as storage. I followed https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration instructions and built a demo. 
But I got one issue. The video is not responded as status code 206, instead it is always return as 200 status code.
It will be very appreciated if you can help me on this.

Thanks

**Comment by j1016h** [comment]
I wanted to upload my demo but it is 207MB...

**Comment by dr-dimitru** [comment]
Hello @j1016h ,

Well, how do you defined `interceptDownload` hook? Could you post it here?
Also [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/lib/files.collection.coffee#L90) is good example with important notes.

**Comment by j1016h** [comment]
Hi @dr-dimitru,
This is my interceptDownload:

interceptDownload(http, image, versionName) {
        console.log(123, versionName);
        // Serve file from GridFS
        const _id = (image.versions[versionName].meta || {}).gridFsFileId;
        if (_id) {
            const readStream = gfs.createReadStream({ _id: _id });
            readStream.on('error', err => {
                throw err;
            });
            console.log(333);
            readStream.pipe(http.response);
        }
        return Boolean(_id); // Serve file from either GridFS or FS if it wasn't uploaded yet
    }

**Comment by j1016h** [comment]
BTW, I use GridFS.

**Comment by dr-dimitru** [comment]
> BTW, I use GridFS.

ReadableStreams is same GridFS or AWS or anything else is ends with Stream.

Here is what you can try:
```js
interceptDownload(http, image, versionName) {
        // Serve file from GridFS
        const _id = (image.versions[versionName].meta || {}).gridFsFileId;
        if (_id) {
            this.serve(http, image, image.versions[version], versionName, gfs.createReadStream({ _id: _id }));
        }
        return Boolean(_id); // Serve file from either GridFS or FS if it wasn't uploaded yet
    } 
```

**Comment by j1016h** [comment]
@dr-dimitru Thank you for your quick response.
Somehow after trying your new interceptDownload function. It gives 500 status error :(

**Comment by dr-dimitru** [comment]
And what the error?

**Comment by j1016h** [comment]
ReferenceError: version is not defined
   at FilesCollection.interceptDownload (imports/myVideo.js:49:52)
   at FilesCollection.module.runModuleSetters.FilesCollection.download (/Users/I839603/edueex/code/prototypes/videolauncher4/.meteor/local/build/programs/server/packages/ostrio_files.js:2771:18)
   at Object.handle (/Users/I839603/edueex/code/prototypes/videolauncher4/.meteor/local/build/programs/server/packages/ostrio_files.js:1112:22)
   at next (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.handle (packages/ostrio_cookies.js:510:17)
   at next (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Function.app.handle (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:182:3)
   at Object.fn [as handle] (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:79:14)
   at next (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.WebAppInternals.staticFilesMiddleware (packages/webapp/webapp_server.js:369:5)

**Comment by j1016h** [comment]
@dr-dimitru tried to change 
this.serve(http, image, image.versions[version], versionName, gfs.createReadStream({ _id: _id }));
        
to

this.serve(http, image, image.versions[versionName], versionName, gfs.createReadStream({ _id: _id }));

But no luck.

**Comment by dr-dimitru** [comment]
Obvious to me. I've made a typo in my sample above - replace `version` with `versionName`
Also I recommend to take a look [here](https://github.com/aheckmann/gridfs-stream#createreadstream) you're definitely have to pass `range` to `createReadStream` options to implement 206 response codes.

> But no luck.

So what error says now?

**Comment by j1016h** [comment]
now the error is 503: Unexpected error.

**Comment by dr-dimitru** [comment]
Thats it? No stack trace?

**Comment by j1016h** [comment]
no stack trace..

**Comment by dr-dimitru** [comment]
Screenshot please...

**Comment by j1016h** [comment]
![screen shot 2017-02-09 at 00 01 07](https://cloud.githubusercontent.com/assets/4699158/22770020/f237557c-ee5a-11e6-9207-22924b992c3d.png)
![screen shot 2017-02-09 at 00 00 44](https://cloud.githubusercontent.com/assets/4699158/22770021/f237dfba-ee5a-11e6-85ed-78ea1229e87f.png)

**Comment by dr-dimitru** [comment]
On server. At Terminal/Console

**Comment by j1016h** [comment]
W20170209-00:06:18.363(-5)? (STDERR) /Users/I839603/.meteor/packages/npm-mongo/.2.2.11_2.1wlbvft++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:99
W20170209-00:06:18.363(-5)? (STDERR)     process.nextTick(function() { throw err; });
W20170209-00:06:18.363(-5)? (STDERR)                                   ^
W20170209-00:06:18.363(-5)? (STDERR) 
W20170209-00:06:18.363(-5)? (STDERR) Error: Can't render headers after they are sent to the client.
W20170209-00:06:18.364(-5)? (STDERR)     at ServerResponse.OutgoingMessage._renderHeaders (_http_outgoing.js:403:11)
W20170209-00:06:18.364(-5)? (STDERR)     at ServerResponse.writeHead (_http_server.js:184:20)
W20170209-00:06:18.364(-5)? (STDERR)     at ServerResponse.writeHead (/Users/I839603/.meteor/packages/webapp/.1.3.12.szsezk++os+web.browser+web.cordova/npm/node_modules/on-headers/index.js:55:19)
W20170209-00:06:18.364(-5)? (STDERR)     at GridReadStream.<anonymous> (/Users/I839603/edueex/code/prototypes/videolauncher4/.meteor/local/build/programs/server/packages/ostrio_files.js:2944:25)
W20170209-00:06:18.364(-5)? (STDERR)     at emitNone (events.js:67:13)
W20170209-00:06:18.365(-5)? (STDERR)     at GridReadStream.emit (events.js:166:7)
W20170209-00:06:18.365(-5)? (STDERR)     at /Users/I839603/edueex/code/prototypes/videolauncher4/node_modules/gridfs-stream/lib/readstream.js:127:20
W20170209-00:06:18.365(-5)? (STDERR)     at /Users/I839603/.meteor/packages/npm-mongo/.2.2.11_2.1wlbvft++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/gridfs/grid_store.js:935:7
W20170209-00:06:18.365(-5)? (STDERR)     at /Users/I839603/.meteor/packages/npm-mongo/.2.2.11_2.1wlbvft++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/gridfs/grid_store.js:1201:5
W20170209-00:06:18.365(-5)? (STDERR)     at handleCallback (/Users/I839603/.meteor/packages/npm-mongo/.2.2.11_2.1wlbvft++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:96:56)
=> Exited with code: 1

**Comment by dr-dimitru** [comment]
First - switch back to your initial code and add `range` to `createReadStream` options to implement 206 response codes. Read for more info - [here](https://github.com/aheckmann/gridfs-stream#createreadstream).

To get start/end bytes use `http` argument - there is everything you need. Some info can be found [here](http://stackoverflow.com/questions/3303029/http-range-header). [Here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2299) is how partial content handled by this lib. You can grab this code and change it to meet your needs

**Comment by j1016h** [comment]
tried to print console.log(http.request.headers.range); from the first line of interceptDownload function. It always returns 'bytes=0-'. Is this right?

**Comment by dr-dimitru** [comment]
Yes, you can check request headers sent by your browser at Network tab.

**Comment by j1016h** [comment]
Source code [Here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2377)
Should the range option key like startPos/endPos or start/end.

From [here](https://github.com/aheckmann/gridfs-stream#createreadstream) think it should be startPos/endPos.

**Comment by dr-dimitru** [comment]
right, but your browser asks everything form first byte, so you should reply with whole file, so - end will be fileSize - 1

**Comment by j1016h** [comment]
Hi @dr-dimitru ,
Thank you for your help. 
I got the 206 status resp working in gridfs now. I have attached the file below for your reference :)

I found the serve function you this lib always read file from file system(fs) instead of those third party storage(for example gridfs). That's why it didnt work by directly using serve function. 

[206responsegfs.js.zip](https://github.com/VeliovGroup/Meteor-Files/files/768111/206responsegfs.js.zip)

**Comment by dr-dimitru** [comment]
Hi @j1016h 

The 5th argument of `this.serve()` method is *ReadableStream* by default if it's not defined of false, method will try to find and read file from FS.

I'm glad you solved it.

Could you post only definition of your `interceptDownload` hook. So, I'll update our examples, and thank you for contribution, if you don't mind of course.

**Comment by j1016h** [comment]
Hi @dr-dimitru,
Of course I don't mind:) I'd love to make open source better. I have attached GFS version interceptDownload code below.

Thanks

[interceptDownloadForGFS.js.zip](https://github.com/VeliovGroup/Meteor-Files/files/768991/interceptDownloadForGFS.js.zip)

**Comment by dr-dimitru** [comment]
@j1016h docs is published [here](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS---206-Streaming)
