### ISSUE TITLE
Error with latest version of Meteor (1.4.2.6)

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/Meteor-Files#349]
Hello,

I have an error on the client side with the latest version of Meteor, which shows up in the JavaScript console:

Uncaught ReferenceError: EventEmitter is not defined
    at ostrio_files.js:1239
    at ostrio_files.js:1241
    at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (ostrio_files.js:4116)
    at fileEvaluate (modules-runtime.js:207)
    at require (modules-runtime.js:130)
    at ostrio_files.js:4186
    at ostrio_files.js:4197

As a result I am not able to access any pages of my app. Any idea how what could be broken?

**Comment by dr-dimitru** [comment]
Hi @marcoschwartz ,

 1. What browser and its version?
 2. What OS?

**Comment by marcoschwartz** [comment]
Hi! Using macOS 10.12.3, and with Chrome 56. Actually I found the root of the issue: it is the coffeescript 1.12.0_1 for Meteor, that was recently updated. With the previous version (1.11.1_4), it works fine.

**Comment by scottwillman** [comment]
+1

**Comment by vu-bui** [comment]
+1

**Comment by pal-pinter** [comment]
+1

Linux desktop 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux
Google Chrome 56.0.2924.87 (64-bit)
Firefox 51.0.1

**Comment by Mklueh** [comment]
+1 Chrome & Firefox

**Comment by zapaz** [comment]
+1

**Comment by dr-dimitru** [comment]
Hello everyone,

Thank you for report. I'm on it. New version will be published within hours

**Comment by dr-dimitru** [comment]
Hello everyone, please update to v1.7.9.
Let me know if latest release is works for you.

**Comment by vu-bui** [comment]
I have another problem with 1.7.9 at #353.
Thanks,
