### ISSUE TITLE
Can I run Meteor-Files in client mode with node-ddp-client?

### ISSUE THREAD

**Issue by oeway** [VeliovGroup/Meteor-Files#350]
Hi, 
Is there a better way to implement a client run in node.js to uploading files to another meteor server? With [node-ddp-client](https://github.com/oortcloud/node-ddp-client), I can in principle implement a client just like the one I made with python. 
But is there a better way to do that? Can I just reuse your code somehow?

**Comment by dr-dimitru** [comment]
Hello @oeway ,

I believe it's better to use HTTP. And might be solution implemented for Python is the quickest.
Moreover ddp uploads will be deprecated in [v2.*](https://github.com/VeliovGroup/Meteor-Files/issues/309)

**Comment by dr-dimitru** [comment]
Hi @oeway ,

Have you figured out how to solve this?

**Comment by oeway** [comment]
hi, I havent work on it yet. Good to know your opinion on that. Thanks.

**Comment by dr-dimitru** [comment]
Hi @oeway ,

Sorry, I've closed it. Feel free to reopen.
Actually this might be a good example for wiki
