### ISSUE TITLE
[FilesCollection] [writeStream] [Exception:] [500]

### ISSUE THREAD

**Issue by FinnFrotscher** [VeliovGroup/Meteor-Files#351]
I am getting this error on file-upload. 

Meteor 1.4 
Mac OS newest
Chrome newest

Serverside output
```
[FilesCollection] [File Start Method] a9rPN4j_460s.jpg - fmxmXngyD2y23hzNZ
[FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: a9rPN4j_460s.jpg
Exception in callback of async function: Error: [FilesCollection] [writeStream] [Exception:] [500]
at []/ostrio_files.js:86:19
at []/packages/ostrio_files.js:59:12
at runWithEnvironment (packages/meteor.js:1176:24)
[FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: a9rPN4j_460s.jpg
[FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: a9rPN4j_460s.jpg
```

Clientside output
```
[FilesCollection] [insert()]
[FilesCollection] [insert] [Tracker] [continue]
[FilesCollection] [insert] [.continue()]
[FilesCollection] [insert] using WebWorkers
loadFile a9rPN4j_460s.jpg: 92.085ms
```

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher 

Is this happens after meteor update?

**Comment by FinnFrotscher** [comment]
Hi
No even prior. It happened after I merged two branches. 
The update separated the ImagesCollection setup from Methods and Publish each into a unique file.

Now I have updated but the error persists.

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher ,

The roots if issue is [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L35).
Node can't create file descriptor it is permission issue or path where you're trying to write files to is not exists. Where are you writing files to?

**Comment by FinnFrotscher** [comment]
I had some issues with file permissions in the past. Do you have a guide on that topic?
The folder where it wants to save exists. 
I am using  `/data/images`. it worked in the past.

**Comment by dr-dimitru** [comment]
At first "just-to-check" use
```shell
chmod -R 777 /data/images
# if app has it's own user
chown -R appeaser:appuser /data/images
```

Make also sure parent path of `images` directory is allow access it.
```shell
chmod 777 /data
```

If this will solve your issue - set proper permissions, like `600` or `644` depend from your needs.
Do not forget set `permissions` and `parentDirPermissions` in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
