### ISSUE TITLE
Error: [FilesCollection.uploads] Path "/images" is not writable!

### ISSUE THREAD

**Issue by jetlej** [VeliovGroup/Meteor-Files#357]
On local, I've set my uploadPath to '/images' as instructed. However Meteor gives me the follow error on build: 

`Error: [FilesCollection.uploads] Path "/images" is not writable!`

Does the folder need to be created first? Where exactly?

**Comment by dr-dimitru** [comment]
Hi @jetlej ,

> Does the folder need to be created first?

Yes, if parent directory tree is writable by user which runs meteor/node.js process

> Where exactly?

Wherever you want, first `/` means your FS root

**Comment by jetlej** [comment]
I'm on OSX. Do I need to change permissions? 

What do you mean by FS root? 

Thanks so much for your help!

**Comment by dr-dimitru** [comment]
> What do you mean by FS root?

[FS root](https://en.wikipedia.org/wiki/Root_directory)

> I'm on OSX. Do I need to change permissions?

Most OSs shares similar vision for permissions, users and groups. I'm personally prefer `/data` directory in FS root, most of this is described in [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq)

Here is `/data/uploads` with very open permissions, but good for dev:
```shell
mkdir -p /data/uploads
chmod -R 777 /data
```

**Comment by jetlej** [comment]
I ran those commands and tried setting 'storagePath' to '/data' and to '/data/uploads' and no media is being added to that folder upon upload :/

**Comment by dr-dimitru** [comment]
set `debug: true` into FilesCollection Constructor, you should see where files going to be written upon meteor start

**Comment by dr-dimitru** [comment]
Hello @jetlej ,

Any news from your end?

**Comment by dr-dimitru** [comment]
Hi @jetlej 

Have you figured out how to setup storage path?

**Comment by mgscreativa** [comment]
For relative storage you could use process.env.PWD. The following code uploads files to METEOR-PROJECT-ROOT/uploads

```
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
    collectionName: 'Images',
    allowClientCode: false,
    storagePath: () => {
        return `${process.env.PWD}/uploads`;
    },
    onBeforeUpload: (file) => {
        if (file.size > 10485760) {
            return 'Please upload image, with size equal or less than 10MB.';
        }

        if (!/png|jpg|jpeg/i.test(file.extension)) {
            return `${file.extension}'s files are not allowed for upload.`;
        }

        return true;
    },
});

export default Images;
```

**Comment by dr-dimitru** [comment]
Here is also useful lib for working with relative paths - https://github.com/VeliovGroup/Meteor-root

**Comment by jetlej** [comment]
Sorry for the late reply! I had to create a folder in the root directory of my computer. On my Mac, that was the 'Macintosh HD' folder, even above the user folder.

**Comment by dr-dimitru** [comment]
@jetlej thank you for update

**Comment by mitsol** [comment]
> For relative storage you could use process.env.PWD. The following code uploads files to METEOR-PROJECT-ROOT/uploads
> 
> ES6 code
> 
> ```
> import { FilesCollection } from 'meteor/ostrio:files';
> 
> const Images = new FilesCollection({
>     collectionName: 'Images',
>     allowClientCode: false,
>     storagePath: () => {
>         return `${process.env.PWD}/uploads`;
>     },
>     onBeforeUpload: (file) => {
>         if (file.size > 10485760) {
>             return 'Please upload image, with size equal or less than 10MB.';
>         }
> 
>         if (!/png|jpg|jpeg/i.test(file.extension)) {
>             return `${file.extension}'s files are not allowed for upload.`;
>         }
> 
>         return true;
>     },
> });
> 
> export default Images;
> ```

i can't recommend doing this: If you plan to deploy the app, the ${process.env.PWD} differs. Unfortunately this path is stored in the database as well: so if you want to restore your backup for local development, the ${process.env.PWD} from the server is different to the one on the local dev environment and the files won't work in the app anymore.

**Comment by dr-dimitru** [comment]
@mitsol recommended approach to `storagePath`:
1. Outside of the project
2. Absolute path
