### ISSUE TITLE
Get upload progress information in other template

### ISSUE THREAD

**Issue by j1016h** [VeliovGroup/Meteor-Files#358]
I have 2 templates A and B. There are multiple template B instance in the page. File upload form is in template A. Is there anyway I can get upload progress object in template B?

**Comment by dr-dimitru** [comment]
Yes, create a global *ReactiveVar* or *Session*

**Comment by j1016h** [comment]
It would be good if we can have progress part of the file collection.

**Comment by dr-dimitru** [comment]
How is that possible? For example if you have 10 simultaneous uploads?

*FileUpload* instance is returned from `.insert()` is independent and you can set it to any variable you want, template-level or app-level.

**Comment by j1016h** [comment]
CFS has that feature but it has video play issue. so we changed to ostrio:files :)

**Comment by dr-dimitru** [comment]
CFS is dead in 2015
This package may use different approach

**Comment by j1016h** [comment]
Yes, we are planing to convert all the file upload to ostrio:files not only video files.

We are currently doing the passing fileUpload obj around approach to get progress info. Just wanted to know if there is any more easy way to handle it since we had to pass fileUpload to multiple levels. 
We can close this ticket if this is the only way for now.

**Comment by dr-dimitru** [comment]
We use application-wide `_app` *Object*
