### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by bevinhex** [VeliovGroup/Meteor-Files#359]
I wanted to get random files , but skip does not seem very effecient, So tried to install ```meteorhacks:aggregate```, it seems to be working fine for Mongo.Collection, but not for FileCollection, when I tried to use ```.aggregate``` function on the file collection, it gives me
```Uncaught TypeError: Images.aggregate is not a function``` error
Can Meteor-Files support aggregation operation? Mongodb is supporting it from version 3, Thanks.

**Comment by dr-dimitru** [comment]
Use `Images.collection`, read more about direct collection usage [here](https://github.com/VeliovGroup/Meteor-Files/wiki/collection)

**Comment by bevinhex** [comment]
Tried that, calling Images.collection.aggregate() give error
```Uncaught TypeError: Images.collection.aggregate is not a function```

**Comment by dr-dimitru** [comment]
Make sure you're on *Server* as `meteorhacks:aggregate` is server only package

**Comment by bevinhex** [comment]
The mothod above should be server side I believe

**Comment by dr-dimitru** [comment]
Right, what on server-side you're getting form?:
```js
console.log(Images.collection);
console.log(Images.collection.aggregate)
```

Have you tried to call `.aggregate()` on other default Mongo.Collection?
Like `Meteor.users.aggregate()`? To make sure `meteorhacks:aggregate` is working?

**Comment by bevinhex** [comment]
Okay, let me try

**Comment by bevinhex** [comment]
Ah my bad, it was not working for other Collections now, somehow I broke something,  meteorhacks:aggregate not working correctly. I'll post how I did after I was able to use aggregate with FileCollection.
Thanks you very much :)

**Comment by bevinhex** [comment]
On server side calling `Images.collection.aggregate({$sample:{size:1000}});` worked perfectly! Confirmed, meteorhacks:aggregate works nicely with Meteor-Files collection.

Can close this now.

**Comment by dr-dimitru** [comment]
Hi @bevinhex I'm glad it's solved. The one thing I was afraid of `meteorhacks:aggregate` - it's stale project with last commit more than 2 years ago. Thank you for testing this out.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
