### ISSUE TITLE
add package breaks app

### ISSUE THREAD

**Issue by crapthings** [VeliovGroup/Meteor-Files#36]
i think something conflict with files package

```sh
W20150916-23:31:03.689(8)? (STDERR)
W20150916-23:31:03.690(8)? (STDERR) /Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150916-23:31:03.690(8)? (STDERR) 						throw(ex);
W20150916-23:31:03.690(8)? (STDERR) 						      ^
W20150916-23:31:03.690(8)? (STDERR) TypeError: Object function (){                                                                                         // 253
W20150916-23:31:03.691(8)? (STDERR)         if( Object.prototype.toString.call(this) !== '[object Object]' &&                                      // 254
W20150916-23:31:03.691(8)? (STDERR)             Object.prototype.toString.call(this) !== '[object Array]'){                                        // 255
W20150916-23:31:03.691(8)? (STDERR)             return undefined;                                                                                  // 256
W20150916-23:31:03.691(8)? (STDERR)         }                                                                                                      // 257
W20150916-23:31:03.691(8)? (STDERR)         return this[Math.floor(Math.random() * this.length)];                                                  // 258
W20150916-23:31:03.691(8)? (STDERR)     } has no method 'arrayElement'
W20150916-23:31:03.691(8)? (STDERR)     at [object Object].self.phoneFormats (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:16:25)
W20150916-23:31:03.691(8)? (STDERR)     at [object Object].self.phoneNumber (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:5:38)
W20150916-23:31:03.691(8)? (STDERR)     at server/fixtures.coffee:25:25
W20150916-23:31:03.691(8)? (STDERR)     at server/fixtures.coffee:5:1
W20150916-23:31:03.691(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:222:10
W20150916-23:31:03.691(8)? (STDERR)     at Array.forEach (native)
W20150916-23:31:03.692(8)? (STDERR)     at Function._.each._.forEach (/Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150916-23:31:03.692(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
W20150916-23:31:09.259(8)? (STDERR)
W20150916-23:31:09.259(8)? (STDERR) /Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150916-23:31:09.259(8)? (STDERR) 						throw(ex);
W20150916-23:31:09.259(8)? (STDERR) 						      ^
W20150916-23:31:09.273(8)? (STDERR) TypeError: Object function (){                                                                                         // 253
W20150916-23:31:09.273(8)? (STDERR)         if( Object.prototype.toString.call(this) !== '[object Object]' &&                                      // 254
W20150916-23:31:09.273(8)? (STDERR)             Object.prototype.toString.call(this) !== '[object Array]'){                                        // 255
W20150916-23:31:09.273(8)? (STDERR)             return undefined;                                                                                  // 256
W20150916-23:31:09.274(8)? (STDERR)         }                                                                                                      // 257
W20150916-23:31:09.274(8)? (STDERR)         return this[Math.floor(Math.random() * this.length)];                                                  // 258
W20150916-23:31:09.274(8)? (STDERR)     } has no method 'arrayElement'
W20150916-23:31:09.274(8)? (STDERR)     at [object Object].self.phoneFormats (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:16:25)
W20150916-23:31:09.274(8)? (STDERR)     at [object Object].self.phoneNumber (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:5:38)
W20150916-23:31:09.274(8)? (STDERR)     at server/fixtures.coffee:25:25
W20150916-23:31:09.275(8)? (STDERR)     at server/fixtures.coffee:5:1
W20150916-23:31:09.275(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:222:10
W20150916-23:31:09.275(8)? (STDERR)     at Array.forEach (native)
W20150916-23:31:09.275(8)? (STDERR)     at Function._.each._.forEach (/Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150916-23:31:09.275(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
W20150916-23:31:14.633(8)? (STDERR)
W20150916-23:31:14.633(8)? (STDERR) /Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150916-23:31:14.633(8)? (STDERR) 						throw(ex);
W20150916-23:31:14.634(8)? (STDERR) 						      ^
W20150916-23:31:14.648(8)? (STDERR) TypeError: Object function (){                                                                                         // 253
W20150916-23:31:14.648(8)? (STDERR)         if( Object.prototype.toString.call(this) !== '[object Object]' &&                                      // 254
W20150916-23:31:14.648(8)? (STDERR)             Object.prototype.toString.call(this) !== '[object Array]'){                                        // 255
W20150916-23:31:14.648(8)? (STDERR)             return undefined;                                                                                  // 256
W20150916-23:31:14.648(8)? (STDERR)         }                                                                                                      // 257
W20150916-23:31:14.649(8)? (STDERR)         return this[Math.floor(Math.random() * this.length)];                                                  // 258
W20150916-23:31:14.649(8)? (STDERR)     } has no method 'arrayElement'
W20150916-23:31:14.649(8)? (STDERR)     at [object Object].self.phoneFormats (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:16:25)
W20150916-23:31:14.649(8)? (STDERR)     at [object Object].self.phoneNumber (/Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/isopacks/npm-container/npm/node_modules/faker/lib/phone_number.js:5:38)
W20150916-23:31:14.649(8)? (STDERR)     at server/fixtures.coffee:25:25
W20150916-23:31:14.649(8)? (STDERR)     at server/fixtures.coffee:5:1
W20150916-23:31:14.649(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:222:10
W20150916-23:31:14.649(8)? (STDERR)     at Array.forEach (native)
W20150916-23:31:14.649(8)? (STDERR)     at Function._.each._.forEach (/Users/monsterstep/.meteor/packages/meteor-tool/.1.1.4.16s0drq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150916-23:31:14.649(8)? (STDERR)     at /Volumes/Data/dev/nexushubs/lawflow/lawflow-system/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by dr-dimitru** [comment]
Is error disappears if you remove Meteor-Files package?
BTW, something is wrong inside `fibers` npm package, but Meteor-Files does/t use it.

**Comment by crapthings** [comment]
yes if i remove meteor files, the errors are gone.

**Comment by crapthings** [comment]
accounts-password                   1.1.1  Password support for accounts
aldeed:collection2                  2.5.0  Automatic validation of insert and update operations on the client and server.
aldeed:template-extension           3.4.3  Adds template features currently missing from the templating package
coffeescript                        1.0.6  Javascript dialect with fewer braces and semicolons
dburles:collection-helpers          1.0.3  Transform your collections with helpers that you define
dburles:mongo-collection-instances  0.3.4  Access your Mongo instances
fortawesome:fontawesome             4.4.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
iron:router                         1.0.9  Routing specifically designed for Meteor
jparker:crypto-md5                  0.1.1  MD5 algorithm for CryptoJS, standard secure algorithms
matb33:collection-hooks             0.8.0  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
maximum:server-transform            0.4.0  Meteor package to transform documents on publish
meteor-platform                     1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:fast-render             2.10.0  Render your app before the DDP connection even comes alive - magic?
meteorhacks:npm                     1.5.0  Use npm modules with your Meteor App
meteorhacks:subs-manager            1.6.2  Subscriptions Manager for Meteor
mquandalle:jade                     0.4.3_1  Jade template language
mquandalle:stylus                   1.1.1  Expressive, dynamic, robust CSS
msavin:mongol                       1.1.5  The insanely handy development package for Meteor.
npm-container                       1.1.0+ Contains all your npm dependencies
peerlibrary:blaze-components        0.13.0  Reusable components for Blaze
tmeasday:publish-counts             0.7.2  Publish the count of a cursor, in real time
zeroasterisk:throttle               0.3.2  A secure means of limiting interactions (emails, etc)
zeroasterisk:throttle-accounts      0.0.3  A secure means of limiting account login/create attempts
zimme:active-route                  2.3.2  Active route helpers

**Comment by crapthings** [comment]
i comment out this file it works but i don't know why

	#

	#

	faker = Meteor.npmRequire 'faker'

	#

	if Meteor.isServer

		#

		Meteor.drop()

		# add admin user

		unless Meteor.users.findOne { username: 'admin' }

			Accounts.createUser
				username: 'admin'
				password: 'admin'
				isAdmin: true
				profile:
					displayName: '管理员'
					mobile: faker.phone.phoneNumber()
					avatarHash: CryptoJS.MD5('admin').toString()
				status:
					notes: _.random 50, 500
					projects: _.random 50, 500
					tasks: _.random 50, 500
					comments: _.random 50, 500
					circles: _.random 50, 500
					posts: _.random 50, 500

			_(5).times ->
				Meteor.users.insert
					createdAt: faker.date.past()
					username: faker.name.findName()
					isAdmin: true
					profile:
						displayName: faker.name.findName()
						mobile: faker.phone.phoneNumber()
						avatarHash: CryptoJS.MD5(faker.lorem.sentence()).toString()
					status:
						notes: _.random 50, 500
						projects: _.random 50, 500
						tasks: _.random 50, 500
						comments: _.random 50, 500
						circles: _.random 50, 500
						posts: _.random 50, 500

		# add n organizations

		_(10).times ->
			Organizations.direct.insert
				title: faker.lorem.sentence()
				desc: faker.lorem.sentences()
				tel: faker.phone.phoneNumber()
				createdAt: faker.date.past()

		# add demo user to an random organization

		unless Meteor.users.findOne { username: 'demo' }

			Accounts.createUser
				username: 'demo'
				password: 'demo'
				organizationId: (_.sample Organizations.find().fetch())._id
				profile:
					displayName: '演示用户'
					mobile: faker.phone.phoneNumber()
					avatarHash: CryptoJS.MD5('demo').toString()
				status:
					notes: _.random 50, 500
					projects: _.random 50, 500
					tasks: _.random 50, 500
					comments: _.random 50, 500
					circles: _.random 50, 500
					posts: _.random 50, 500

		# add test user to an random organization

		unless Meteor.users.findOne { username: 'test' }

			Accounts.createUser
				username: 'test'
				password: 'test'
				organizationId: (_.sample Organizations.find().fetch())._id
				profile:
					displayName: '测试用户'
					mobile: faker.phone.phoneNumber()
					avatarHash: CryptoJS.MD5('test').toString()
				status:
					notes: _.random 50, 500
					projects: _.random 50, 500
					tasks: _.random 50, 500
					comments: _.random 50, 500
					circles: _.random 50, 500
					posts: _.random 50, 500

		# random users

		_(5).times ->
			Meteor.users.insert
				createdAt: faker.date.past()
				username: faker.name.findName()
				organizationId: (_.sample Organizations.find().fetch())._id
				profile:
					displayName: faker.name.findName()
					mobile: faker.phone.phoneNumber()
					avatarHash: CryptoJS.MD5(faker.lorem.sentence()).toString()
				status:
					notes: _.random 50, 500
					projects: _.random 50, 500
					tasks: _.random 50, 500
					comments: _.random 50, 500
					circles: _.random 50, 500
					posts: _.random 50, 500

		# feed tasks

		_(100).times ->
			Tasks.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				createdAt: faker.date.past()
				content: faker.lorem.sentences()
				completed: _.sample [true, false]
				important: _.sample [true, false]

		# feed projects

		_(10).times ->
			Projects.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				createdAt: faker.date.past()
				title: faker.lorem.sentence()
				desc: faker.lorem.sentences()
				content: faker.lorem.sentences()
				completed: false

		# feed announcements

		_(30).times ->
			Announcements.direct.insert
				userId: Meteor.users.findOne { username: 'admin' }
				createdAt: faker.date.past()
				title: faker.lorem.sentence()
				desc: faker.lorem.sentences()
				content: faker.lorem.sentences() + faker.lorem.sentences() + faker.lorem.sentences()

		# feed posts

		_(30).times ->
			Posts.direct.insert
				userId: Meteor.users.findOne { username: 'admin' }
				createdAt: faker.date.past()
				title: faker.lorem.sentence()
				desc: faker.lorem.sentences()
				content: faker.lorem.sentences()

		# feed notes

		_(100).times ->
			Notes.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				createdAt: faker.date.past()
				content: faker.lorem.sentences()

		# feed comments for notes

		_(100).times ->
			Comments.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				noteId: (_.sample Notes.find().fetch())._id
				createdAt: faker.date.past()
				content: faker.lorem.sentences()

		# feed circles

		_(100).times ->
			Circles.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				createdAt: faker.date.past()
				content: faker.lorem.sentences()

		# feed comments for circles

		_(100).times ->
			Comments.direct.insert
				userId: (_.sample Meteor.users.find().fetch())._id
				circleId: (_.sample Circles.find().fetch())._id
				createdAt: faker.date.past()
				content: faker.lorem.sentences()

**Comment by dr-dimitru** [comment]
@crapthings sorry I didn't get you. It is somehow solved now?

**Comment by dr-dimitru** [comment]
@crapthings any news on your end? Does it work with latest release?

**Comment by crapthings** [comment]
it works after i create a new project

i dont know why the faker breaks meteor file

let me try it when i finish work

**Comment by dr-dimitru** [comment]
@crapthings okay, keep this thread updated please

**Comment by dr-dimitru** [comment]
Hi @crapthings if this issue doesn't appear on your end anymore, don't you mind to close it?
