### ISSUE TITLE
Cross domain Video Play Issue

### ISSUE THREAD

**Issue by salmanhasni** [VeliovGroup/Meteor-Files#366]
I have edit my /etc/hosts "127.0.0.1 example.localhost" according to business logic. sub domain always needed to properly fetch all the required items from mongo, but I am stuck arround the images/video
because if i use .link() method it returns the url http://localhost:3000/cdn/storage/videos/uh2RbzwQ9PeAPm8yL/m3u8/uh2RbzwQ9PeAPm8yL.m3u8
where as i needed https://football.localhost:3000 to make the video to bypass the cross domain security issue

**Comment by salmanhasni** [comment]
@dr-dimitru can you please share some information here

**Comment by dr-dimitru** [comment]
Hi @salmanhasni ,

Quickest solution for you is overwrite `.link()` method to:
```js
const files = new FilesCollection({ /*...*/ });

const _origLink = files.link;
files.link = function (v) {
  return _origLink(v).replace(__meteor_runtime_config__.ROOT_URL, 'https://football.localhost:3000');
}
```

Where `https://football.localhost:3000` can be stored as env.variable or in Meteor.settings

Let me know if it helps

**Comment by salmanhasni** [comment]
Hi @dr-dimitru I will give it try today and will surely let you know. thanks for the quick response and heads up.

**Comment by salmanhasni** [comment]
for the quick fix it worked, I extended your idea to make it more dynamic than to store all possible subDomains in settings.
`_origLink.replace("://", "://" + subDomain + ".");`

**Comment by valorloff** [comment]
```
files.link = function (v) {
  return _origLink(v).replace(__meteor_runtime_config__.ROOT_URL, 'https://football.localhost:3000');
}
```
fantastic solution!
Big thanks!

**Comment by haibo32012** [comment]
I follow the stream files shared code, insert a video file and succeed and try play it on the page, but nothing play on the page, in the elements,**<source src="http://localhost:3000/cdn/storage/files/PKgKqxPXLJaEKEQdt/original/PKgKqxPXLJaEKEQdt.mp4?play=true" type="video/mp4">**
this is my storagePath: **'assets/app/uploads/files'**.

**Comment by haibo32012** [comment]
I follow the stream files example code, insert a video and succeed, try play it on the page, but nothing displayed. In the Elements place **src=http://localhost:3000/cdn/storage/files/PKgKqxPXLJaEKEQdt/original/PKgKqxPXLJaEKEQdt.mp4?play=true**
my storagePath:**'assets/app/uploads/files'**, this is the template code :**src="{{file.link}}?play=true"**, what's wrong?

**Comment by dr-dimitru** [comment]
Hello @haibo32012 ,

Looks good to me. 

 1. Where do you store file FS or GridFS?
 2. Does it throws any errors on Client or Server?
 3. What "Network" tab displays, any network errors?

**Comment by haibo32012** [comment]
@dr-dimitru I test on local, what's your mean store file FS or GridFS, when I create collection have already set storagePath, is this not enough?

**Comment by dr-dimitru** [comment]
> when I create collection have already set storagePath, is this not enough?

Enough.

What about?:
 1. Does it throws any errors on Client or Server?
 2. What "Network" tab displays, any network errors?

**Comment by haibo32012** [comment]
No Errors, Client or Server or Network.

**Comment by haibo32012** [comment]
I am still confuss when i upload a file, where the file is, what i say is on local FS, when i succeed upload a file, i  check the database and find it,i searched it on the my computer FS, can't find it.

**Comment by dr-dimitru** [comment]
> i searched it on the my computer FS, can't find it.

Where have you checked?

> No Errors, Client or Server or Network.

I'm still would like to see what network tab may tell us.
Could you post few screenshots?

**Comment by haibo32012** [comment]
![client upload picture](https://cloud.githubusercontent.com/assets/7117248/24338303/e468d4ca-12d6-11e7-80e1-cf5a622014f0.png)
![mongo database result](https://cloud.githubusercontent.com/assets/7117248/24338315/fef2fa8c-12d6-11e7-8f85-81085d5b53fb.png)

**Comment by haibo32012** [comment]
First is client picture, Second is mongo database result.

**Comment by dr-dimitru** [comment]
Hi @salmanhasni ,

According to original issue:
> try play it on the page, but nothing displayed

I need to see what server respond with when you're request file in a browser.
On screenshot - no request for uploaded file is sent from browser to server.
Please make sure: 
 1. Uploaded file is somehow requested from browser (with video/audio/img/etc. element)
 2. "Headers" tab is open under "Network" tab

**Comment by haibo32012** [comment]
![notfound](https://cloud.githubusercontent.com/assets/7117248/24458116/918d32dc-14ca-11e7-82f0-3e28dce92850.png)

this is when i use simple stream demo code test, it can't find data.what I confuse is where  the data store when i  upload a file under local development enviroment.

**Comment by dr-dimitru** [comment]
Hello @haibo32012 ,

Well - `404` means file not found by library.
Could you locate uploaded file inside directory defined via `storagePath`?
And what your `storagePath` is?

If you will enable debug-mode via `debug` flag set to `true` and passed into `FilesCollection` constructor - it will help a lot to solve your issue. Please, enable it and post full logs from Server and Client Console here.

Thank you.

**Comment by haibo32012** [comment]
thanks, I have figured out what's going on, the storeagePath set the wrong place, thanks so much for your patience.

**Comment by dr-dimitru** [comment]
@haibo32012 I'm glad it helped. Do not hesitate to ask more.

**Comment by salmanhasni** [comment]
instead of replacing original link I found a bit hacky general way to fix the cross domain issue

```
// Listen to incoming HTTP requests, can only be used on the server
http://www.something.com/path/to/intercept
WebApp.rawConnectHandlers.use("/path/to/intercept", function(req, res, next) {
  //define white list of urls, or can be done like adding subdomain prefixes before Meteor.absoluteUrl();
  let whiteList = [];
  const found = _.find(whiteList, function(url) {
    return url == req.headers.origin;
  });
  if(found){
    res.setHeader("Access-Control-Allow-Origin", req.headers.origin);
  }
  return next();
});
```

**Comment by dr-dimitru** [comment]
@salmanhasni ,

You're welcome to send PR with this snippet to docs :)
