### ISSUE TITLE
Ostrio files

### ISSUE THREAD

**Issue by varunajmera0** [VeliovGroup/Meteor-Files#367]
Whenever Meteor server starts, images are deleted from folder.

**Comment by dr-dimitru** [comment]
@varunajmera0 ,

From the [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> Note: All files will be removed as soon as your application rebuilds or you run meteor reset. To keep your storage persistent during development use an absolute path outside of your project folder, e.g. /data directory.
