### ISSUE TITLE
Set PATH imagemagick on ubuntu server

### ISSUE THREAD

**Issue by truongnx2** [VeliovGroup/Meteor-Files#371]
Hi ,
I  use ImageMagick on ubuntu server (using thumbnail image). However, I do not know as yet the configuration file PATH. Please help me. Thanks

**Comment by dr-dimitru** [comment]
Why do you need to add it into PATH variable?
Are you getting errors?
How have you installed ImageMagick?

**Comment by truongnx2** [comment]
I refer : https://github.com/CollectionFS/Meteor-CollectionFS/issues/232
Reason:
We have had a couple of issues in the stack related solely to the lack of installation of gm/im - so throwing an error if we can't find the binaries is a long wanted feature request. Debugging is otherwise difficult.
(I did read the node module gm code, and they rely on PATH it seems)

**Comment by dr-dimitru** [comment]
@truongnx2 How have you installed ImageMagick?

**Comment by truongnx2** [comment]
@dr-dimitru : On my Ubuntu server running : 
sudo apt-get update
sudo apt-get install graphicsmagick

**Comment by dr-dimitru** [comment]
@truongnx2 this installation way is made everything automatically
In the https://github.com/CollectionFS/Meteor-CollectionFS/issues/232 it's about Mac

So, are you getting errors?

**Comment by truongnx2** [comment]
No errors happen at all. Image has been uploaded to the server. But I do not use thumbnail

**Comment by truongnx2** [comment]
@dr-dimitru  No errors happen at all. Image has been uploaded to the server. But I do not use thumbnail

**Comment by dr-dimitru** [comment]
Okay, what is the issue?

**Comment by truongnx2** [comment]
@dr-dimitru : I use image-processing.js to get small size photos. However, when get xxx/thumbnail/abc.png is still the original image

**Comment by dr-dimitru** [comment]
@truongnx2 you're not getting enough information to understand your issue.

1. How do you check newly created thumbs? On FS or via URL in browser?

**Comment by truongnx2** [comment]
@dr-dimitru 
Sorry. I send an error on the server:

[45.77.16.136] [FilesCollection] [Upload] [finish(ing)Upload] -> /uploads/NASYNw
MLJkonHizwS.jpg
[45.77.16.136] [FilesCollection] [Upload] [finish(ed)Upload] -> /uploads/NASYNwM
LJkonHizwS.jpg
[45.77.16.136] Create thumbnail ...
[45.77.16.136] exists:  true
[45.77.16.136] [_app.createThumbnails] [_.each sizes] **[Error: Could not execute
GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "/uploads/NA
SYNwMLJkonHizwS.jpg" this most likely means the gm/convert binaries can't be fou
nd]**
[45.77.16.136] [_app.createThumbnails] [finish] undefined
[45.77.16.136] [FilesCollection] [_preCollectionCursor.observeChanges] [removed]
: NASYNwMLJkonHizwS

I think this error is due to the imagemagick configuration on the server (I use Ubuntu)

**Comment by dr-dimitru** [comment]
This question is unrelated to this package.
Marked as "help wanted", hope someone else will help you to solve it.
But, I'm sure a bit of Googling will easily help you.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if issue still persists on your end.
