### ISSUE TITLE
How to access `this.userId` in `onAfterUpload`?

### ISSUE THREAD

**Issue by thebarty** [VeliovGroup/Meteor-Files#376]
Hi guys,

I have an useCase where I am using GridFS (https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration) and I want to write the userId to the GridFS-doc after uploading (onAfterUpload).

In this code I can NOT grab userId:
```
onAfterUpload(image) {
  Object.keys(image.versions).forEach((versionName) => {
    log('this.userId', this.userId, Meteor.userId(), Meteor.user(), this)  // does NOT work! no Meteor.bindEnvironment()?
    const metadata = { versionName, imageId: image._id, storedAt: new Date() }  // Optional
    const writeStream = gfs.createWriteStream({ filename: image.name, metadata })
    fs.createReadStream(image.versions[versionName].path).pipe(writeStream)
    writeStream.on('close', Meteor.bindEnvironment((file) => {
      const property = `versions.${versionName}.meta.gridFsFileId`
      // If we store the ObjectID itself, Meteor (EJSON?) seems to convert it to a
      // LocalCollection.ObjectID, which GFS doesn't understand.
      this.collection.update(image._id, { $set: { [property]: file._id.toString() } })
      this.unlink(this.collection.findOne(image._id), versionName) // Unlink files from FS
    }))
  })
},
```

Any idea how to get there? ??

**Comment by dr-dimitru** [comment]
Hello @thebarty ,

In short - use `image.userId`.

`onAfterUpload` has nothing to do with `userId` it's asynchronous thread-detached hook, not related to any user.

If upload was made by logged-in user, the fileObject (`image` in your case) passed into `onAfterUpload` hook will have `userId`. See [Schema](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)

**Comment by thebarty** [comment]
@dr-dimitru Thanks a lot for the info!! 👍 And thanks for this great package!
