### ISSUE TITLE
.remove() error = undefined when _id not exists.

### ISSUE THREAD

**Issue by cortesa** [VeliovGroup/Meteor-Files#378]
When I try to remove an Image and its _id not exists in the collection, callback parameter (error) is undefined so callback condition (if(error){...}else{...}) do not work properly and run else part instead of if one.

Thanks.

**Comment by dr-dimitru** [comment]
Hello @cortesa ,

Is this happens on server, client or both?

**Comment by cortesa** [comment]
clients

2017-03-15 23:28 GMT+01:00 dr.dimitru <notifications@github.com>:

**Comment by cortesa** [comment]
client

**Comment by dr-dimitru** [comment]
Testing it now, how do you actually call `.remove()` method? Code-sample please

**Comment by cortesa** [comment]
thanks.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)

**Comment by cortesa** [comment]
Star on both. good Job.

2017-03-18 11:52 GMT+01:00 dr.dimitru <notifications@github.com>:
