### ISSUE TITLE
Secure `Collection.insert` via a Meteor method?

### ISSUE THREAD

**Issue by thebarty** [VeliovGroup/Meteor-Files#379]
Hi there,

following the API guide I have this code on the client. As you can see I am writing security-related data here (userId and _groupId).

I would much prefer to do this in a method.

```
      const upload = AvatarFilesCollection.insert({
        file: e.currentTarget.files[0],
        streams: 'dynamic',
        chunkSize: 'dynamic',
        meta: {
          type: 'AVATAR',
          _groupId: Partitioner.group(),
          userId: Meteor.user()._id,
        },
      }, false)
```

Can we do this serverside with a method? If yes, is there some example code somewhere?

**Comment by dr-dimitru** [comment]
Hello @thebarty ,

 1. Why you think method is "more" secure?
 2. If you use DDP as upload transport, data is sent in the same way as it sent via Methods
 3. Anyways if you want to separate logic use `onAfterUpload` hook to extend file Schema
 4. `userId` is always exists if upload was made by logged-in user, see [Schema](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)

Hope this will help, let me know

**Comment by thebarty** [comment]
@dr-dimitru: Thanks for the response. I'll play around with it a bit more.

What I like about methods is that they enable me to use the "Secret Server Code" pattern mentioned in https://guide.meteor.com/security.html.

**Comment by dr-dimitru** [comment]
Well, use SimpleSchema and update [pre-defined FilesCollection schema](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema) to meet your needs.

**Comment by dr-dimitru** [comment]
And `onAfterUpload` is the safest point to validate upload

**Comment by thebarty** [comment]
@dr-dimitru: ok cool! Thanks for the info!

**Comment by dr-dimitru** [comment]
Hello @thebarty 

Is this solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if issue still persists on your end.
