### ISSUE TITLE
Optimizing an Image going to Amazon S3

### ISSUE THREAD

**Issue by AndyNormore** [VeliovGroup/Meteor-Files#380]
Great plugin, love it. Running on www.SkyRooms.IO - it's a beauty!

I have configured S3 and CloudFront to deliver the images - but I need to compress images before I send them up. 

What's the best practice to achieve this? Thanks again!

**Comment by AndyNormore** [comment]
Example, I have an un-optimized image at 833kb, when optimized hits 350kb.

**Comment by AndyNormore** [comment]
Looking at these packages, can this work?

https://github.com/sourcey/s3-image-optimizer

https://github.com/imagemin/imagemin

**Comment by dr-dimitru** [comment]
Hello @AndyNormore ,

I'm using only GraphicksMagick. For more see [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/server/image-processing.js#L91).

First is to crop/resize uploaded images to format you wish to use. Next is optimize it. For png I can recommend PNGyu, for other formats - ImageOptim, they should have CLI version for Linux.

Let me know if it helped you.

**Comment by AndyNormore** [comment]
Ahhh very nice! I will check in to this later today and update the thread.

**Comment by dr-dimitru** [comment]
Hi @AndyNormore ,

Any news on your end?

**Comment by AndyNormore** [comment]
Oh hi, I actually ended up COMPLETELY removing Meteor Files... and moving to Cloudinary.com's service.

It does all this imagemagic as a service over an HTTP request. So, I couldn't figure this one out!

Cheers and good luck.
