### ISSUE TITLE
GridFS details - How to display files on client via Mongo and NOT CDN?

### ISSUE THREAD

**Issue by thebarty** [VeliovGroup/Meteor-Files#381]
Hi @dr-dimitru,

how do I subscribe to gridFS on the client and read the images via GridFS and NOT via CDN?

Following your guide it seems like `*.chunks` collection is actually filled, BUT when doing a `doc.link` on the client I am still getting the files via CDN??

Do I need to subscribe to the gridFS collections, or use a different function than link?

**Comment by dr-dimitru** [comment]
This lib follows API consistency, so no matter what you're using for storage, files and Mongo records accessed in the same manner.

**Comment by thebarty** [comment]
so what how does the url of a valid gridfs-link look like?

Just for clarification, I am displaying my file like
```
<img class="avatar-image img-circle img-responsive" data-file-name="{{doc.getProfileImage.name}}" src="{{doc.getProfileImage.link}}" alt="{{doc.name}}"/>
```

and right now the url contains "/CDN/*". Is this correct? Does the data really come from gridFs then, or is it still served via standard filesystem-FS?

**Comment by dr-dimitru** [comment]
> and right now the url contains "/CDN/*". Is this correct? Does the data really come from gridFs then, or is it still served via standard filesystem-FS?

Yes, it's okay. Downloadable URL doesn't depends from storage. All magic is done in `interceptDownload` when you proxy request from client to GrifdFS, or any other storage

**Comment by dr-dimitru** [comment]
Hi @thebarty ,

This this one solved?

**Comment by thebarty** [comment]
Hi @dr-dimitru, please check out my comment here. You can close this topic if you like. https://github.com/VeliovGroup/Meteor-Files/issues/382

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if issue still persists on your end.
