### ISSUE TITLE
`Collection.write()` NOT automatically writing to GridFS when on server

### ISSUE THREAD

**Issue by thebarty** [VeliovGroup/Meteor-Files#382]
Just noticed that (following the GridFS guide), doing a `ImagesCollection.write` on the server will NOT automatically write the files to GridFS when run on server. 

I lost some time on understanding what has happend here and I guess it would be really nice for future users to get that from the WIKI.

**Comment by dr-dimitru** [comment]
Why you're using `.write()` method? Not upload (`.insert()`)?
If you've defined GridFS integration in `onAfterUpload` hook, use fourth argument to apply it to [`.write()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) method.

**Comment by thebarty** [comment]
In my usecase I am generating initials-images on the server (when a new user is inserted), so I want to fill gridFs from serverside. According to the API (https://github.com/VeliovGroup/Meteor-Files/wiki) `.insert()` is only available on client-side, right?

**Comment by dr-dimitru** [comment]
Hi @thebarty ,

Have you figured this issue out?

**Comment by thebarty** [comment]
Hi @dr-dimitru,

first of all: thanks again for your support and help! I know that getting such a thing to work takes a lot of effort and I really appreciate it!

To give you some constructive feedback: I found that this package was too much of a hassle to get running and the GRIDFS-API is more a implementation-guidance than an API. 

Looking back I wish I tried a different package right from the beginning - your README looked so promising that I thought: lets give it a try. In the end I feel like I "lost" 3 days in vain, BUT I learned a lot. 

I had much better luck with https://github.com/jalik/jalik-ufs. Check out the codebase. Its really nice and clean. And switching to a different storage-provider is the matter of installing another sub-package.

Just my point of view and like I said: it is meant for constructive feedback. I really appreciate your work. 👍

**Comment by dr-dimitru** [comment]
Hello @thebarty ,

Thank you for feedback, I guess you were looking for drop-in solution.
And unfortunately this is not that kind of packages.

I'll put my best into v2.0 to bring simpler and more clean API, this package and its codebase almost 3 years old, and getting ugly. You may went through [this discussion](https://github.com/VeliovGroup/Meteor-Files/issues/309) and leave your wishes for v2.0.

The main direction of this package is file delivery to the server, and then let to developer decide what to do with a file. Leave a file on FS as it is, modify it or move to other storage.

Thank you once again for feedback, it means a lot.
