### ISSUE TITLE
Using standard FS: will this package work on galaxy?

### ISSUE THREAD

**Issue by thebarty** [VeliovGroup/Meteor-Files#383]
Hi @dr-dimitru,

I am considering skipping the GridFS stuff for starting up. It got more complicated than I thought.

Do you know if using standard-FS stuff will work when deploying to galaxy?

**Comment by dr-dimitru** [comment]
It will work anywhere with persistent FileSystem.
I haven't faced Galaxy yet myself. But quick Googling shows what it [has not persistent FS](https://github.com/meteor/galaxy-docs/blob/master/content/file-storage.md)

Try AWS or Google Storage - you may find it more simple.
BTW what went wrong with GridFS?

**Comment by thebarty** [comment]
Alright, thanks to the hint with galaxy. This is really good and important to know. Maybe you should include that in the docs. Know I have some more motivation for getting GridFS to work. 👍 See my other topics for my gridFS questions. In general I feel like there is still quite some manual work to do and when there is manual work, there are always places to put in errors.

**Comment by dr-dimitru** [comment]
Closed in favor of other two issues by you.
Feel free to reopen it in case if issue still persists on your end.
