### ISSUE TITLE
Custom url root for images

### ISSUE THREAD

**Issue by achtan** [VeliovGroup/Meteor-Files#385]
hi is it possible to set custom url root i.e. `http://images.domain.com/...`?

**Comment by dr-dimitru** [comment]
Sure, check this thread - https://github.com/VeliovGroup/Meteor-Files/issues/366

**Comment by dr-dimitru** [comment]
Hello @achtan ,

Any news from your end?
Is #366 answered your question?

**Comment by achtan** [comment]
hi sry for not responding, currently i can't try it, so i close this issue for now and i will open it later if necessary

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if issue still persists on your end.
