### ISSUE TITLE
addFile runs first, then everything else

### ISSUE THREAD

**Issue by AdrianAbba** [VeliovGroup/Meteor-Files#386]
```
if(Meteor.isServer){
      
      XlsFiles.denyClient();
      XlsFiles.collection.attachSchema(XlsFiles.schema);
      mongoXlsx.mongoData2Xlsx(data, model, function(err, data) {
        console.log(data)
        console.log('File saved at:', data.fullPath); 
      });
      XlsFiles.addFile("C:/Users/Adrian/Desktop/JTabelle.xlsx", {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        fileId: 'abc123AwesomeId',
        userId: Meteor.userId(),
        meta: {}

      });
 
        Meteor.publish('files.xlsFiles.all', function () {
        return XlsFiles.find().cursor;
      });
      
    }else {

    Meteor.subscribe('files.xlsFiles.all');
  }
```

Im using the mongo-xlsx package in combination with your package.

I have the problem, the addFile Method is running before the mongoXlsx.mongoData2Xlsx Method.
Any ideas how to controll the order :x?

didnt find much for threading in meteor :/

**Comment by dr-dimitru** [comment]
Well, both `addFile` and `mongoData2Xlsx` is both asynchronous. [This Twitter post](https://twitter.com/iamdevloper/status/808344541669498881) will explain better than anyone else.

To solve it there is two options:
 1. Make `mongoXlsx.mongoData2Xlsx` via `Meteor.wrapAsync`
 2. Put `XlsFiles.addFile` inside of `mongoXlsx.mongoData2Xlsx` callback

Note - second option is more efficient, but less pretty

**Comment by AdrianAbba** [comment]
option 2 works fine.
Tried option 1 but have problems to combine both with the right syntax ❌ 
and i guess your addFile package has an bug:

```
 Exception in callback of async function: ReferenceError: fileName is not defined
I20170319-12:31:06.060(1)?     at packages/ostrio_files/files.coffee:1495:58
I20170319-12:31:06.061(1)?     at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed:collection2-core/collection2.js:485:15)
I20170319-12:31:06.062(1)?     at packages/mongo/collection.js:643:5
I20170319-12:31:06.063(1)?     at runWithEnvironment (packages\meteor.js:1176:24)
I20170319-12:31:06.065(1)?     at packages\meteor.js:1189:14
I20170319-12:31:06.066(1)?     at packages/mongo/mongo_driver.js:326:7
I20170319-12:31:06.067(1)?     at runWithEnvironment (packages\meteor.js:1176:24)
```

```
XlsFiles.addFile(data.fullPath, {
    fileName:data.fullPath,
    name:data.fullPath,
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    fileId: 'abc123AwesomeId',
    userId: userId,
    meta: {}
});
```

the document doesnt have an field with "fileName",
even if i delete the fileName field of these syntax, im getting the same error

**Comment by dr-dimitru** [comment]
Hello @AdrianAbba ,

Could you please create separate issue regarding `addFile` and `fileName` prop.
Mention there what Meteor/FilesCollection version, platform (win/mac/linux) you're on. And a bit of your code which causing an error.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if issue still persists on your end.
