### ISSUE TITLE
Can't find npm module 'meteor/ostrio:files'

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/Meteor-Files#388]
Hi!
I created a new meteor project, based on the old source files, 
then 
```
meteor add ostrio:files
import { FilesCollection } from 'meteor/ostrio:files';
```
in collection.js
 I'm having an issue:
` Error: Can't find npm module 'meteor/ostrio:files'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?`
how to solve it?

**Comment by dr-dimitru** [comment]
Hi @valorloff ,

What meteor and `ostrio:files` version you're on?
Make sure you're on the latest `ostrio:files` version

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

Is this issue fixed?

**Comment by valorloff** [comment]
Hi!
Yes, fixed, Sorry for the false alarm

**Comment by dr-dimitru** [comment]
No worries

**Comment by sardormajano** [comment]
I'm still having this problem, though I have the latest version of the package (ostrio:files). It is asking for "fs-extra" npm package. Locally, in my computer, if I install "fs-extra" package manually (npm install --save fs-extra), it works. But when I deploy the app using mup, it is giving me the same error on the remote server. 

What could be the problem?

**Comment by paulincai** [comment]
@sardormajano #420
