### ISSUE TITLE
Failed to display thumbnail.

### ISSUE THREAD

**Issue by xshadowlegendx** [VeliovGroup/Meteor-Files#389]
I've searched inside issues of Meteor-Files package about image resize, and i follow this link and copy paste from the code. [link: https://github.com/VeliovGroup/Meteor-Files/issues/277 ].
I've manage to update the file into the collection, which i can see inside versions has both 'original' and 'thumbnail', i also check inside .meteor/.../myImages/ and it has the subversion of the file with prefix thumbnail ( uniqueid-thumbnail.jpg ).
When I display the file on the client, it only display the original image, and i did not get any error message both client and server console.
My client side code:
 //Client.js

        Template.displayImg.helpers({

            displayImg: ()=> Images.findOne({}).link('thumbnail')

        });
    //Client.html
    <img src="{{ displayImg }}" />

***My afterupload code is taken from the link above, which it works as expect, uploaded => resize the image => update back to collection.

But I've notice this somehow, when taking from thumbnail, the server console output this line:
[FilesCollection] [download(/cdn/storage/images/hjrRGyAmb4KAxXK69/thumbnail/hjrRGyAmb4KAxXK69.png, thumbnail)]

Inside meteor mongo, checking the versions of the image shows that both original and thumbnail has the same size (I think they should not have the same size right?), but inside the .meteor/.../images folder, i can see my thumbnail resized and the size is reduced.

**Comment by dr-dimitru** [comment]
Hello @xshadowlegendx ,

Could you post raw record from MongoDB here?

**Comment by xshadowlegendx** [comment]
Ok, below are the db.fs.files and db.images accordingly
//FS
{
	"_id" : ObjectId("58d495ebcdbcd41863ed45ac"),
	"filename" : "Peaceful_mind_1920.png",
	"contentType" : "binary/octet-stream",
	"length" : 895805,
	"chunkSize" : 261120,
	"uploadDate" : ISODate("2017-03-24T03:43:39.267Z"),
	"aliases" : null,
	"metadata" : {
		"versionName" : "original",
		"imageId" : "hjrRGyAmb4KAxXK69",
		"storedAt" : ISODate("2017-03-24T03:43:39.198Z")
	},
	"md5" : "e8c3e9de721711d081305df2cf8ca202"
}
 
//Images collection
{
	"_id" : "hjrRGyAmb4KAxXK69",
	"size" : 895805,
	"type" : "image/png",
	"name" : "Peaceful_mind_1920.png",
	"meta" : {
		
	},
	"ext" : "png",
	"extension" : "png",
	"extensionWithDot" : ".png",
	"mime" : "image/png",
	"mime-type" : "image/png",
	"userId" : null,
	"path" : "images/hjrRGyAmb4KAxXK69.png",
	"versions" : {
		"original" : {
			"path" : "images/hjrRGyAmb4KAxXK69.png",
			"size" : 895805,
			"type" : "image/png",
			"extension" : "png",
			"meta" : {
				"gridFsFileId" : "58d495ebcdbcd41863ed45ac"
			}
		},
		"thumbnail" : {
			"path" : "images/hjrRGyAmb4KAxXK69-thumbnail.png",
			"size" : 895805,
			"type" : "image/png",
			"extension" : "png",
			"meta" : {
				"gridFsFileId" : "58d495ebcdbcd41863ed45ac"
			}
		}
	},
	"_downloadRoute" : "/cdn/storage",
	"_collectionName" : "images",
	"isVideo" : false,
	"isAudio" : false,
	"isImage" : true,
	"isText" : false,
	"isJSON" : false,
	"isPDF" : false,
	"_storagePath" : "images",
	"public" : false
}

**Comment by dr-dimitru** [comment]
Well, after creating thumbnail you should:
 1. Read new file size and update it in version's Object
 2. Move thumbnail to GridFS and update `meta.gridFsFileId` currently you pointing to same record at GridFS for both original and thumbnail files

**Comment by xshadowlegendx** [comment]
Ok, thanks u very much, I'm outside right now so i will try it and then report back to u after that.

**Comment by xshadowlegendx** [comment]
Hello, I have follow what u've said, and it the thumbnail works now, thanks you very much :D

**Comment by dr-dimitru** [comment]
Hello @xshadowlegendx ,

No worries, I'm glad it helped you :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
