### ISSUE TITLE
Request: remove iron-router dependencies or enable choice of router

### ISSUE THREAD

**Issue by miri-am** [VeliovGroup/Meteor-Files#39]
Would like to use the package with flow-router. Does this make sense?

Maybe https://github.com/nicolaslopezj/meteor-router-layer could be use to support multiple routers?

**Comment by dr-dimitru** [comment]
I don't see any reason for this, only way to simplify package is switch to middleware `WebApp.connectHandlers.use()`. Iron-router only used on server now as middleware.
Which reason you have to strip iron router?

**Comment by miri-am** [comment]
Okay, so it wont interfere with a client-side router? Then it would be okay for me, I guess.

**Comment by dr-dimitru** [comment]
Used on server only: https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L224,L234
I guess theres no interference even routes will have same URI - but it is not recommended, and after page is refreshed by user server will catch this call.

**Comment by dr-dimitru** [comment]
@miri-am any new on your end? Any interference is found?

**Comment by miri-am** [comment]
@dr-dimitru Sorry, didn't try so far. Will keep you updated once I do. Thanks! Closing it for now, because it does not seem to be an issue.
