### ISSUE TITLE
how to modify path of original image ?

### ISSUE THREAD

**Issue by achtan** [VeliovGroup/Meteor-Files#390]
i want custom path for original image for example:
````js
const path = fileRef._storagePath + "/" + fileRef.meta.postId + "/" + fileRef._id + "." + fileRef.extension;
````
is it possible to set this path before upload? or i should just move my file after upload?

**Comment by dr-dimitru** [comment]
Hello @achtan ,

Make `storagePath` a *Function*. See [relative thread](https://github.com/VeliovGroup/Meteor-Files/issues/317)

**Comment by achtan** [comment]
thansk
