### ISSUE TITLE
Downloaded file seems to be defect

### ISSUE THREAD

**Issue by AdrianAbba** [VeliovGroup/Meteor-Files#391]
![unbensdsdannt](https://cloud.githubusercontent.com/assets/9356382/24362919/89843364-130e-11e7-9ed4-5e20ef3ab35a.png)

The left Window is the information of the working file.
In Robomongo u can see the Document after using addFile.
The right window shows the information of the downloaded file.

The size increased and i cant open the file anymore.

my Code:
```
mongoXlsx.mongoData2Xlsx(data, model, function(err, data) {
          console.log(data)
          console.log('File saved at:', data.fullPath);
            XlsFiles.addFile(data.fullPath, {
              fileName:data.fullPath,
              name:data.fullPath,
              type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
              fileId: userId,
              userId: courseId,
              meta: {}
            });
        });
```

**Comment by dr-dimitru** [comment]
What is `mongoXlsx.mongoData2Xlsx` doing?
`.addFile()` method just links file and it's metadata to Collection without moving bits around.
 1. How do you move file from FS to MongoDB?
 2. What the second line after `GroBe` means? There is same size.

**Comment by AdrianAbba** [comment]
1. The file location is in the Meteor project folder
2. the first one means Size and the 2nd one means size on driver

u can see the whole method Code here:

https://github.com/VeliovGroup/Meteor-Files/issues/392#issuecomment-289490940

mongoXlsx.mongoData2Xlsx is an package for creating excel files(xlsx), this one is working fine.
I can open the file without problems.
its weird :x the downloaded file "should" work without problems too.

**Comment by dr-dimitru** [comment]
As Understood:
 1. Generated file opened directly - is fine
 2. Same file opened after download - is broken

Right?

 1. Do you use any 3rd party storage (GridFS, AWS, etc.)?
 2. What query parameters do you use to download file `?download=true`, or none?
 3. What is in "Network" tab? I would like to see headers.
 4. What browser is used to download a file?
 5. Is it binary xlsx or text xls? Could you compare raw file contents?

**Comment by dr-dimitru** [comment]
@AdrianAbba any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
