### ISSUE TITLE
link not generating synchronously :

### ISSUE THREAD

**Issue by tanmoy12** [VeliovGroup/Meteor-Files#393]
### I'm having an issue:
 1. Search [issues](https://github.com/VeliovGroup/Meteor-Files/issues), maybe your issue is already solved
 2. We have useful threads makred as [`In case of the fire - Read This`](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=%E2%9C%93&q=label%3A%22In%20case%20of%20the%20fire%20-%20Read%20This%22%20), read them too
 3. Before submitting an issue make sure it's only related to `Meteor-Files` package
 4. If your issue not solved:
  - Give expressive description
  - Version of `Meteor-Files` you're expecting this issue
  - Version of `Meteor` you're expecting this issue
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  
### I have a suggestion:
 1. PRs is always welcome - [send a PR](https://github.com/VeliovGroup/Meteor-Files/compare)
  - Always send PRs only to `dev` branch, thank you
 2. If you you can not send a PR for some reason:
  - Describe your feature / request
  - How you going to use it? Give a usage example(s)
  
### Documentation is missing something or incorrect (have typos, etc.)
 1. PRs is always welcome - [send a PR](https://github.com/VeliovGroup/Meteor-Files/compare)
  - Always send PRs only to `dev` branch, thank you
 2. If you you can not send a PR for some reason:
  - Give a short description what you have changed/added and why
  - Make sure you're using correct markdown markup
  - Make sure all code blocks starts with tripple ``` (*tilda*) and have a syntax tag, for more read [this docs](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)
  - Post your addition/changes in issue, we will manage it

**Comment by dr-dimitru** [comment]
?
