### ISSUE TITLE
link not generating synchronously : link = ImagesCol.findOne({_id: Meteor.user().profile.ProPic}).link();   I'm getting an error can not read link of undefined

### ISSUE THREAD

**Issue by tanmoy12** [VeliovGroup/Meteor-Files#394]

**Comment by dr-dimitru** [comment]
Hello @tanmoy12 

Well, this means cursor is empty.
```js
let link = '';
const cursor = ImagesCol.findOne({_id: Meteor.user().profile.ProPic});
if (cursor) {
   link = cursor.link();
}
```

Is this happens on Client or Server?

**Comment by tanmoy12** [comment]
This was client side..
Thank you so much, this solved the problem!!

Another issue i'm facing is images don't load after 2 or 3 days of uploading them, this is the error :

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by dr-dimitru** [comment]
Hello @tanmoy12 ,

Regarding this:

> Another issue i'm facing is images don't load after 2 or 3 days of uploading them, this is the error :
> 
> Failed to load resource: the server responded with a status of 404 (Not Found)

Quick guess is you ran into behavior described in [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> Note: All files will be removed as soon as your application rebuilds or you run `meteor reset`. To keep your storage persistent during development use an absolute path outside of your project folder, e.g. `/data` directory.

**Comment by tanmoy12** [comment]
I'm a novice with meteor.. can you please review my code what i'm doing wrong. I did not completely understand the idea of different absolute path. Thank you so much for your time. 

I'm uploading two files when a user signs up: 1. profile picture. 2. image of a seal & signature. I'm using package accounts-password to signup user. 

if(this.state.empProPic && this.state.empSeal){
            let uploadInstance = ImagesCol.insert({
                file: that.state.empProPic,
                streams: 'dynamic',
                chunkSize: 'dynamic',
                allowWebWorkers: true // If you see issues with uploads, change this to false
            }, false);

            uploadInstance.on('uploaded', function (error, fileObjPro) {

                let uploadInstance2 = ImagesCol.insert({
                    file: that.state.empSeal,
                    streams: 'dynamic',
                    chunkSize: 'dynamic',
                    allowWebWorkers: true // If you see issues with uploads, change this to false
                }, false);

                uploadInstance2.on('uploaded', function (error, fileObjSeal) {

                    if(password==repassword){
                        var User = {
                            username: username,
                            email: email,
                            password: password,
                            profile: {
                                designation: designation,
                                mobno: mobno,
                                ProPic: fileObjPro._id,
                                seal: fileObjSeal._id
                            }
                        };
                        Accounts.createUser(User, function (err) {
                            if (err) {
                                var message= err.reason;
                                Bert.alert(message, 'danger', 'growl-top-right');
                            }else {
                                Bert.alert('User Signed up', 'success', 'growl-top-right');
                            }
                        });
                    }
                    else{
                        Bert.alert('Passwords do not match!!', 'danger', 'growl-top-right');
                    }
                });

                uploadInstance2.on('error', function (error, fileObjSeal) {
                    console.log('Error during upload: ' + error);
                });

                uploadInstance2.start();

            });

            uploadInstance.on('error', function (error, fileObj) {
                console.log('Error during upload: ' + error);
            });

            uploadInstance.start(); // Must manually start the upload
        }
        else{
            Bert.alert('Upload necessary files!!', 'danger', 'growl-top-right');
        }

**Comment by dr-dimitru** [comment]
Hello @tanmoy12 ,

Sorry I'm lost the point, what was the question?

**Comment by tanmoy12** [comment]
"To keep your storage persistent during development use an absolute path outside of your project folder, e.g. /data directory."

I don't understand how i can do that. I am uploading the code i am using to upload a file. I'm using Meteor with react.

    uploadIt(e){
        "use strict";
        e.preventDefault();
        var that = this;
        if (e.currentTarget.files && e.currentTarget.files[0]) {
            // We upload only one file, in case
            // there was multiple files selected
            var file = e.currentTarget.files[0];
            //console.log(file.width);
            if (file) {
                let uploadInstance = ImagesCol.insert({
                    file: file,
                    meta: {
                        locator: that.props.fileLocator,
                        userId: Meteor.userId() // Optional, used to check on server for file tampering
                    },
                    streams: 'dynamic',
                    chunkSize: 'dynamic',
                    allowWebWorkers: true // If you see issues with uploads, change this to false
                }, false);

                uploadInstance.on('uploaded', function (error, fileObj) {
                    console.log('uploaded: ', fileObj);
                    that.setState({
                        uploading: [],
                        progress: 0,
                        inProgress: false
                    });
                });

                uploadInstance.on('error', function (error, fileObj) {
                    console.log('Error during upload: ' + error);
                });

                uploadInstance.start(); // Must manually start the upload
            }
        }
    }

**Comment by dr-dimitru** [comment]
Where do you initialize `ImagesCol`?

**Comment by tanmoy12** [comment]
In collection folder in a file named images.js: here's the code

    ImagesCol = new FilesCollection({
        collectionName: 'Images',
        allowClientCode: false, // Disallow remove files from Client
        onBeforeUpload: function (file) {
            // Allow upload files under 10MB, and only in png/jpg/jpeg formats
            if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
                return true;
            } else {
                return 'Please upload image, with size equal or less than 10MB';
            }
        }
    });

**Comment by dr-dimitru** [comment]
```js
ImagesCol = new FilesCollection({
    collectionName: 'Images',
    storagePath: `/data`,
    allowClientCode: false, // Disallow remove files from Client
    onBeforeUpload: function (file) {
        // Allow upload files under 10MB, and only in png/jpg/jpeg formats
        if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
            return true;
        } else {
            return 'Please upload image, with size equal or less than 10MB';
        }
    }
});
```

And make sure `/data` exists (terminal/console):
```shell
mkdir -p /data
```

**Comment by haibo32012** [comment]
I am building a video stream web, on the home page, i want display some most watched videos, this is js code:
Template.hotTopic.helpers({
	file: function() {
		return files.find({"meta.view_count": {"$gte": 100}}, {sort: {"meta.created_at": -1}});
	}
});
On the template:
<template name="hotTopic">
<div class="container">
  {{#each file}}
  <a href="/post/{{_id}}">
    <video width="320" height="240">
      <source src="{{link}}" type="{{type}}"/>
    </video>
    <li>{{name}}</li>
  </a>
  <a href="/user/{{userId}}">
    <li>{{userId}}</li>
  </a>
  {{else}}
    Loading Video
  {{/each}}
</div>
</template>
I use link() try to download the video and display it on the page, I failed, I watched this wiki  link() only use on findOne(), and about find(), found this code:
filesCursor.each(function (file) {
  // Only available in .each():
  file.link();
  file.remove();
  file.with(); // <-- Reactive object
});
so if i want to display a few downloadable videos, how should i write the code?

**Comment by haibo32012** [comment]
I am building a video stream web, on the home page, i want display some most watched videos, this is js code:
```
Template.hotTopic.helpers({
  file: function() {
    return files.find({"meta.view_count": {"$gte": 100}}, {sort: {"meta.created_at": -1}});
 }
});
```
On the template:
```
<template name="hotTopic">
<div class="container">
  {{#each file}}
  <a href="/post/{{_id}}">
    <video width="320" height="240">
      <source src="{{link}}" type="{{type}}"/>
    </video>
    <li>{{name}}</li>
  </a>
  <a href="/user/{{userId}}">
    <li>{{userId}}</li>
  </a>
  {{else}}
    Loading Video
  {{/each}}
</div>
</template>
```
I use link() try to download the video and display it on the page, I failed, I watched this wiki link() only use on findOne(), and about find(), found this code:
```
 filesCursor.each(function (file) { 
// Only available in .each(): 
  file.link(); 
  file.remove(); 
  file.with(); // <-- Reactive object 
}); 
```
so if i want to display a few downloadable videos, how should i write the code?

**Comment by dr-dimitru** [comment]
Hello @haibo32012 ,

Take a look on `each` iterator at [demo app](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/abfa01b27685ee3b07567c855986de9659c82167/demo/client/index.jade#L7), and here is [`.link()` method used](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/abfa01b27685ee3b07567c855986de9659c82167/demo/client/listing/listing-row.jade#L14).

And for streaming use - [`?play=true`, see docs](https://github.com/VeliovGroup/Meteor-Files/blob/dd59d886db69e8d74db3ebb5e1c7bde74f0b64c9/docs/template-helper.md#example-for-video-with-multiple-subversions).

And `.each()`is not a callback, `.each()` simply returns *FilesCursor* as *Object*

**Comment by haibo32012** [comment]
Thanks for your answer, I check the answer, still have confuse, I try more concrete express my question on the below.
WIKI findOne() example:
```
var file = Images.findOne({_id: 'Rfy2HLutYK4XWkwhm'});
// Generate downloadable link:
file.link();
// Get cursor's data as reactive Object
file.with();
```
I am use this in my video play page:
this is helpers code:
```
Template.videoPlay.helpers({
	file: function() {
		let id = FlowRouter.getParam('_id');
		let file = files.findOne({_id: id}) || {};
		return file;
	}
});
```
This is my template code:
```
<template name="videoPlay">
{{#with file.with}}
  <video  width="320" height="240" controls="controls" autoplay>
    <source src="{{link}}?play=true" type="{{type}}"/>
    <track kind="captions" src="test.vtt"/>
  </video>
{{/with}}
```
In the play page, video finish the download and can play.
In my display a few most watched videos page, this is helpers code:
```
Template.main.helpers({
  file: function () {
  	console.log(files.findOne());
  	return files.find({}, {sort: {'meta.created_at': -1}});
  }
});
```
**In this template I try use link again**, this is code:
```
<template name="main">
<div class="container">
  {{#each file}}
  <a href="/post/{{_id}}">
    <video proload='auto' width="320" height="240">
      <source src="{{link}}" type="{{type}}"/>
    </video>
  {{else}}
    Loading Video
  {{/each}}
  </div>
</template>
```
In this page, video do not download and can play. the link() do not generate a downloadable url, I check the source code:
```
  ###
  @locus Anywhere
  @memberOf FileCursor
  @name link
  @param version {String} - Name of file's subversion
  @summary Returns downloadable URL to File
  @returns {String}
  ###
  link: (version) ->
    console.info "[FilesCollection] [FileCursor] [link(#{version})]" if @_collection.debug
    return if @_fileRef then @_collection.link(@_fileRef, version) else ''

###
```
also check the with() code:
```
  ###
  @locus Anywhere
  @memberOf FileCursor
  @name with
  @summary Returns reactive version of current FileCursor, useful to use with `{{#with}}...{{/with}}` block template helper
  @returns {[Object]}
  ###
  with: ->
    console.info '[FilesCollection] [FileCursor] [with()]' if @_collection.debug
    self = @
    return _.extend self, @_collection.collection.findOne @_fileRef._id

###
```
and each() code:
 ```
 ###
  @locus Anywhere
  @memberOf FilesCursor
  @name each
  @summary Returns an Array of FileCursor made for each document on current cursor
           Useful when using in {{#each FilesCursor#each}}...{{/each}} block template helper
  @returns {[FileCursor]}
  ###
  each: ->
    self = @
    return @map (file) ->
      return new FileCursor file, self._collection

###
```
and still don't understand why link() can't generate a downloadable url under each.how can i generate a downloadable link under each?

**Comment by haibo32012** [comment]
Thanks for your answer @dr-dimitru , I check the answer, still have confuse, I try more concrete express my question on the below.
WIKI findOne() example:

```
var file = Images.findOne({_id: 'Rfy2HLutYK4XWkwhm'});
// Generate downloadable link:
file.link();
// Get cursor's data as reactive Object
file.with();

```
I am use this in my video play page:
this is helpers code:

```
Template.videoPlay.helpers({
	file: function() {
		let id = FlowRouter.getParam('_id');
		let file = files.findOne({_id: id}) || {};
		return file;
	}
});
```

This is my template code:

```
<template name="videoPlay">
{{#with file.with}}
  <video  width="320" height="240" controls="controls" autoplay>
    <source src="{{link}}?play=true" type="{{type}}"/>
    <track kind="captions" src="test.vtt"/>
  </video>
{{/with}}
```

In the play page, video finish the download and can play.
In my display a few most watched videos page, this is helpers code:
```

Template.main.helpers({
  file: function () {
  	console.log(files.findOne());
  	return files.find({}, {sort: {'meta.created_at': -1}});
  }
});
```

**In this template I try use link again**, this is code:

```
<template name="main">
<div class="container">
  {{#each file}}
  <a href="/post/{{_id}}">
    <video proload='auto' width="320" height="240">
      <source src="{{link}}" type="{{type}}"/>
    </video>
  {{else}}
    Loading Video
  {{/each}}
  </div>
</template>
```

In this page, video do not download and can play. the link() do not generate a downloadable url, I check the source code:
```

  ###
  @locus Anywhere
  @memberOf FileCursor
  @name link
  @param version {String} - Name of file's subversion
  @summary Returns downloadable URL to File
  @returns {String}
  ###
  link: (version) ->
    console.info "[FilesCollection] [FileCursor] [link(#{version})]" if @_collection.debug
    return if @_fileRef then @_collection.link(@_fileRef, version) else ''

###
```

also check the with() code:
```

  ###
  @locus Anywhere
  @memberOf FileCursor
  @name with
  @summary Returns reactive version of current FileCursor, useful to use with `{{#with}}...{{/with}}` block template helper
  @returns {[Object]}
  ###
  with: ->
    console.info '[FilesCollection] [FileCursor] [with()]' if @_collection.debug
    self = @
    return _.extend self, @_collection.collection.findOne @_fileRef._id

###
```

and each() code:

```
###
 @locus Anywhere
 @memberOf FilesCursor
 @name each
 @summary Returns an Array of FileCursor made for each document on current cursor
          Useful when using in {{#each FilesCursor#each}}...{{/each}} block template helper
 @returns {[FileCursor]}
 ###
 each: ->
   self = @
   return @map (file) ->
     return new FileCursor file, self._collection

###
```

and still don't understand why link() can't generate a downloadable url under each.how can i generate a downloadable link under each?

**Comment by dr-dimitru** [comment]
Hello @haibo32012 ,

Okay, now I think I've got your issue.

So, you can use [`fileURL` template helper](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper) and pass context of the `each` block:

```html
<template name="main">
  <div class="container">
    {{#each file}}
      <a href="/post/{{_id}}">
        <video proload='auto' width="320" height="240">
          <source src="{{fileURL this}}" type="{{type}}"/>
        </video>
      </a> <!-- this closing tag was missed -->
    {{else}}
      Loading Video
    {{/each}}
  </div>
</template>
```

Let me know if it helps.

**Comment by haibo32012** [comment]
@dr-dimitru yes, it works,I am so stupid, didn't notice **fileURL**, and when you provide link  for streaming use - [?play=true, see docs.](url), I confused about fileURL, didn't notice it in the bottom of the files.coffee,thank you so much!
```
if Meteor.isClient
  ###
  @locus Client
  @TemplateHelper
  @name fileURL
  @param {Object} fileRef - File reference object
  @param {String} version - [Optional] Version of file you would like to request
  @summary Get download URL for file by fileRef, even without subscription
  @example {{fileURL fileRef}}
  @returns {String}
  ###
  Meteor.startup ->
    if Template?
      Template.registerHelper 'fileURL', (fileRef, version) ->
        return undefined if not fileRef or not _.isObject fileRef
        version = if not version or not _.isString(version) then 'original' else version
        if fileRef._id
          return formatFleURL fileRef, version
        else
          return ''
return
```

**Comment by dr-dimitru** [comment]
Hi @haibo32012 ,
I'm glad it's solved.

@tanmoy12 is your initial issue solved?

**Comment by tanmoy12** [comment]
Yes it is solved. Sorry to have responded so late. 

Thank you so much for the help. Meteor-files is a very handy tool.

**Comment by dr-dimitru** [comment]
@tanmoy12 
Great, thank you for feedback.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
