### ISSUE TITLE
File content before upload

### ISSUE THREAD

**Issue by theWeird** [VeliovGroup/Meteor-Files#396]
On a current project I need to access the file contents before upload to check for confidential informations and to replace it by an encrypted version of itself.  
I also need to access the content of a received file to decrypt it on browser side.

Is it possible in one of the provided events to access and modify the content of the files?

**Comment by dr-dimitru** [comment]
Hello @theWeird ,

Sure, take a look on:
 - [.pipe()](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#piping)
 - Other option is to get File contents via [`FileReader `](http://www.javascripture.com/FileReader), see [example](http://www.javascripture.com/FileReader). Modify it to meet your needs, and then convert it to `base64` with [`.readAsDataURL()`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL) method. And [upload file as `base64`](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#upload-base64-string)

**Comment by theWeird** [comment]
pipe is exactly what I need.
Thank you for your suggestion.

**Comment by dr-dimitru** [comment]
Hi @theWeird ,

I'm glad it fits your needs.
If you don't mind - share your sample code with `.pipe()` usage to our wiki.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
