### ISSUE TITLE
.write( ) not passing through onAfterUpload( ) of FilesCollection

### ISSUE THREAD

**Issue by mking200** [VeliovGroup/Meteor-Files#397]
I noticed when using the .write( ) to upload a file, it uploads straight to the file system and not the one set on the onAfterUpload( ) option.   

In my case, am storing the images on GridFS, but the files uploaded using .write( ) does not get uploaded to MongoDB. Only on the file system.

Thanks

**Comment by dr-dimitru** [comment]
Hello @mking200 ,

[`write(buffer [, opts, callback, proceedAfterUpload])`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) set fourth argument `proceedAfterUpload` to true.

Let me know if it helps

**Comment by mking200** [comment]
Sorry I forgot this option.   I'll try it and let you know if it works.

**Comment by mking200** [comment]
Yes, this is working.  Thanks!

**Comment by dr-dimitru** [comment]
Great, I'm glad it's solved

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
