### ISSUE TITLE
.link("thumbnail") displays original while thumbnail is not yet created, but won´t switch to thumb afterwards

### ISSUE THREAD

**Issue by Mklueh** [VeliovGroup/Meteor-Files#399]
I´m facing a smaller issue when uploading images and creating thumbnails.

In my template helper I´m using this code to fetch the thumbnail

```
 thumbnail: function () {
            return Collections.Files.findOne({_id: this._id}).link('thumbnail');
        }
```

The problem is, it displays the original according to the documentation, when the thumbnail doesn´t exist, which is the case right after the upload. My problem is now, that after I´ve created the tumbnail, I update the collection, but the image doesn´t change to thumbnail. I need to reload the whole page first.

What is the best way to refresh it/make link() reactive?

**Comment by dr-dimitru** [comment]
Hello @Mklueh 

The best way is to wait for thumbnail is to be created, here is snippet taken from [demo app](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/client/listing/listing-row.js#L5):

```js
{
  thumbnail: function () {
    const img = Collections.AppFiles.findOne({_id: this._id};
    if (img.versions.thumbnail) {
      // Return thumbnail
      return img.link('thumbnail');
    } else {
      // Return temporary placeholder
      return '/img/some-image-placeholder.jpg';
    }
  }
}
```

Hope you've got the main idea from snipped above.
Let me know if this approach fits your needs.

**Comment by Mklueh** [comment]
Thank you for the fast response.

Works for me ;)

**Comment by dr-dimitru** [comment]
@Mklueh ,

I'm glad this solved your issue.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
