### ISSUE TITLE
How reference not uploaded files in FileCollection

### ISSUE THREAD

**Issue by davinciagf** [VeliovGroup/Meteor-Files#401]
Hi,

I am creating an app where the authenticated and authorised user has the possibility to download files (zip files, pdf files,...) from the app depending on his request. The files are stored in the filesystem and their sizes can exceed 1Go. In addition, new files can be created by web processing depending on user requests. Is it possible to use Meteor-Files to reference these files on a FileCollection aiming to manage their availability to the users ? 

Thanks

**Comment by dr-dimitru** [comment]
Hello @davinciagf ,

Sure it's possible - pass `protected` option as *Function* into [`FilesCollection` constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor).

Here is example from our demo application - https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/lib/files.collection.js#L66

**Comment by davinciagf** [comment]
Hi @dr-dimitru 

Thanks.
I used the [write function](https://github.com/VeliovGroup/Meteor-Files/wiki/Write)  to populate FileCollection with existing files in the filesystem. The files located in the storagePath can be directly open with success. But when I try to download a file recorded in the FileCollection with a simple download button (client side), I encountered an error. All downloaded files have a size of 12ko!
Could you help me to solve this error ? Is it linked to the _downloadRoute - I have tried with and without config.downloadRoute? 

Here, the information regarding to a file in the fileCollection:
```
{
    "_id" : "3YsENTSsgTL8NoPc4",
    "name" : "logo.png",
    "extension" : "png",
    "path" : "/Users/Desktop/test2/3YsENTSsgTL8NoPc4.png",
    "meta" : {},
    "type" : "image/png",
    "size" : 10329,
    "userId" : null,
    "versions" : {
        "original" : {
            "path" : "/Users/Desktop/test2/3YsENTSsgTL8NoPc4.png",
            "size" : 10329,
            "type" : "image/png",
            "extension" : "png"
        }
    },
    "_downloadRoute" : "/uploads",
    "_collectionName" : "Documents",
    "isVideo" : false,
    "isAudio" : false,
    "isImage" : true,
    "isText" : false,
    "isJSON" : false,
    "isPDF" : false,
    "_storagePath" : "/Users/Desktop/test2"
}  
```

**Comment by dr-dimitru** [comment]
Hello @davinciagf ,

Yes, downloadable URL is build from `_id`, `version`, `extension` and `downloadRoute`.

See #316 and [Collection docs (*at the very bottom*)](https://github.com/VeliovGroup/Meteor-Files/blob/bf651c648e6755244d4a71c9d74ed0344a1b5091/docs/collection.md).

**Comment by davinciagf** [comment]
Thanks

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
