### ISSUE TITLE
Protecting files based on version

### ISSUE THREAD

**Issue by deeeed** [VeliovGroup/Meteor-Files#402]
I have 
For example, after uploading an image I save 3 versions (original, preview, blurry), and would like to protect only the "original" and "preview" versions.

The problem is that the **protected** method only contains the fileObj, **interceptDownload** seems to be a better place to do that. The wiki recommends using **protected**, is there a reason why I shouldn't use **interceptDownload** instead?

**Comment by dr-dimitru** [comment]
Hello @deeeed ,

Yes, for your case you can use `downloadCallback` which has all you need:
 - `this.request` (you can get version out of requested URL)
 - `this.response`
 - `this.user`
 - `fileRef` as argument

While `protected` is isomorphic hook, and primary made to check users' authorization
And `interceptDownload` made to change data-flow

Hope that helps, let me know.

**Comment by deeeed** [comment]
Thanks it did.

**Comment by dr-dimitru** [comment]
Hello @deeeed ,

Great, I'm glad it's solved for you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
