### ISSUE TITLE
Heroku Deploy failed

### ISSUE THREAD

**Issue by danjimgar** [VeliovGroup/Meteor-Files#403]
Hi,

When i copy the repo on Heroku, it built good but:

![image](https://cloud.githubusercontent.com/assets/9274074/25356529/bae18410-293a-11e7-8eb8-ec1545cfc2f7.png)

When i tried to enter with URL, Heroku shows an error:

![image](https://cloud.githubusercontent.com/assets/9274074/25356565/ee1419b0-293a-11e7-8b1b-3d805497d399.png)

And there are no errors in the log.

**Comment by dr-dimitru** [comment]
Hello @danjimgar ,

If there is no logs, could you contact Heroku for more info, theirs Support team is open and respond quickly.

And what deploy/installation method?

**Comment by dr-dimitru** [comment]
Hello @danjimgar ,

Is this issue solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
