### ISSUE TITLE
Access plain file content in .pipe()

### ISSUE THREAD

**Issue by theWeird** [VeliovGroup/Meteor-Files#404]
As suggested in #396 I use pipe to encrypt the content of a file before upload.

```javascript
 const uploader = EntryAttachments.insert({
    file: attachment,
    streams: 'dynamic',
    chunkSize: 'dynamic',
  }, false);
  uploader.pipe(plainContent => {
    console.log('PLAIN CONTENT', plainContent);
...
```

For a test I used a simple textfile "test.txt" with content
"Just a simple dummy text file"

If I use pipe and dump out the file content that is passed in, it looks like this:  
> PLAIN CONTENT SnVzdCBhIHNpbXBsZSBkdW1teSB0ZXh0IGZpbGUK

So, that doesn't look like the content from my testfile. What is it?
How can I access the plain content?

(on your question in the last issue: Yes, I can write an example once I have my workflow ... working ;) )

**Comment by dr-dimitru** [comment]
Hello @theWeird 

From the [docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#piping): 
> data flow uses dataURI (Base64)

Means all chunks passed as it is from the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL)

Hope that will help, let me know.

**Comment by dr-dimitru** [comment]
Hello @theWeird ,

Any updates on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
