### ISSUE TITLE
Insert is not a function

### ISSUE THREAD

**Issue by pacozaa** [VeliovGroup/Meteor-Files#407]
I used this code but when I call method below, there is an error.
``` javascript
Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});

Meteor.methods({
  saveimage: function(capture_type,file,fingerpos,name){
    var upload = Images.insert({
        file: file,
        streams: 'dynamic',
        chunkSize: 'dynamic'
      }, false);
    upload.start();
  }
});
```
Here is a full error.

![capture](https://cloud.githubusercontent.com/assets/3154089/25692898/196d125a-30d0-11e7-8b05-9d1bafaa185f.JPG)

Anyone know a solution?

**Comment by dr-dimitru** [comment]
Hello @pacozaa ,

`.insert()` is *Client* only method (a.k.a. *upload*).
You're trying to run inside *Meteor.Method* which executed on the server.
Take a look on [this demo app](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo-simplest-upload/client/main.js#L29) to find out more about how to use `.insert()` to upload files

**Comment by pacozaa** [comment]
@dr-dimitru 

How to use `.insert()` on server-side?

**Comment by dr-dimitru** [comment]
Hello @pacozaa ,

Take a look on [`. addFile()`](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile) and [`.write()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write), also take a look into [docs](https://github.com/VeliovGroup/Meteor-Files/wiki) to find a solution for your needs.

**Comment by dr-dimitru** [comment]
Hello @pacozaa ,

Is this issue solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by JoaoCardoso193** [comment]
Using `.addFile()` seems to work with no errors, but the collection always shows up as empty?
