### ISSUE TITLE
Great project! Congratulations 

### ISSUE THREAD

**Issue by iSuslov** [VeliovGroup/Meteor-Files#41]
Thank you guys! I wish we would see truly stable version.

**Comment by dr-dimitru** [comment]
Hi @iSuslov thank you for your comment.
What you actually find as unstable or non-production ready?

**Comment by iSuslov** [comment]
From what I see and what I tried everything is perfect so far. Only one thing unclear for me right now:
when I upload a file without extension, it uploads 100% and then throws exception "Extension is required", I don't know if it's configurable or not, so did not raise a bug. Expected behavior could be:
1a) Raise exception on upload start.
1b) Make it configurable for files without extension.

Another small thing is to have doc for pure javascript users too, I know some people have not touched coffee, so could be confused with the doc.

**Comment by dr-dimitru** [comment]
Files without extension now supported. See 2d7e84965259fa4cfb7c0235fcee583f3d0e510c

**Comment by iSuslov** [comment]
Great! Thank you very much
