### ISSUE TITLE
Issues with CSP

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-Files#411]
Hi! I have enabled Content Security Policy meteor package **meteor/browser-policy-common**

Now I'm getting this error ostrio:files related to CSP

> Refused to create a worker from 'blob:http://localhost:3000/ef628f55-736b-4b36-a32d-b1056adfaa8c' because it violates the following Content Security Policy directive: "default-src 'self' http://fonts.googleapis.com https://fonts.googleapis.com http://fonts.gstatic.com https://fonts.gstatic.com http://code.ionicframework.com https://code.ionicframework.com". Note that 'worker-src' was not explicitly set, so 'default-src' is used as a fallback.

My actual browser-policy-common config looks like this

```
import { BrowserPolicy } from 'meteor/browser-policy-common';
// e.g., BrowserPolicy.content.allowOriginForAll( 's3.amazonaws.com' );
// BrowserPolicy.content.allowFontOrigin("data:");

BrowserPolicy.framing.disallow();
BrowserPolicy.content.disallowInlineScripts();
BrowserPolicy.content.disallowEval();
BrowserPolicy.content.allowInlineStyles();
BrowserPolicy.content.allowFontDataUrl();

const trusted = [
  'fonts.googleapis.com',
  'fonts.gstatic.com',
  'code.ionicframework.com',
];

_.each(trusted, (origin) => {
  BrowserPolicy.content.allowOriginForAll(origin);
});
```
Can you tell me shich config should I change to allow ostrio:files to work?

Thanks a lot!

**Comment by dr-dimitru** [comment]
Hello @mgscreativa ,

Please see this [SO thread](http://stackoverflow.com/questions/28467789/content-security-policy-object-src-blob). And [this commit](https://github.com/SpiderOak/crypton/pull/387/files#diff-0f3fd2081611e8e8550ba6f1e56b1cf9R28) on repository with similar issue.

**Comment by mgscreativa** [comment]
Great! added **blob:** to trusted array and now works!

```
const trusted = [
  'fonts.googleapis.com',
  'fonts.gstatic.com',
  'code.ionicframework.com',
  'blob:',
];
```

**Comment by dr-dimitru** [comment]
Hey @mgscreativa ,

I'm glad it's fixed for you now.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
