### ISSUE TITLE
upload doesn't start on cordova android

### ISSUE THREAD

**Issue by deeeed** [VeliovGroup/Meteor-Files#412]
I have been trying to debug my android app for a while and although I am pretty sure it worked before, I am now always stuck with a 0% upload on android.
It works perfectly on IOS and web version.

![image](https://cloud.githubusercontent.com/assets/4800095/26186488/a85ce78e-3bc4-11e7-9bfd-fdc279cf5508.png)

Here is my server log:

![image](https://cloud.githubusercontent.com/assets/4800095/26186533/f806586a-3bc4-11e7-8cc4-f061d8734d5c.png)

Any ideas what could be causing this error ?
I also added App.accessRule('*'); just in case...

Here is my upload initialization code:
```javascript
let uploadInstance = UserPhotos.insert({
            file: file,
            transport: 'ddp',
            isBase64: false,
            streams: 'dynamic',
            chunkSize: 'dynamic'
        }, false);

        window.inst = uploadInstance;

        uploadInstance.on('start', function() {
            console.debug("Start upload", this);
            tpl.selectedFile.set(false);
            tpl.currentUpload.set(this);
        });

        uploadInstance.on('pause', function(progress, fileData) {
            console.debug("on pause", progress, fileData);
        });

        uploadInstance.on('progress', function(progress, fileData) {
            console.debug("upload progress", progress, fileData);
        });

        uploadInstance.on('uploaded', function(error, fileData) {
            console.debug("uploaded", error, fileData);
        });

        uploadInstance.on('abort', function(error, fileData) {
            tpl.currentUpload.set(false);
            console.debug("upload aborted");
        });

        uploadInstance.on('end', function(error, fileRef) {
            tpl.currentUpload.set(false);
            if(error) {
                sAlert.error(TAPi18n.__("common.errors.error"));
                console.debug("error upload", error);
                return;
            }

            console.debug("upload complete!");

            tpl.selectedFile.set(fileRef);
            // sAlert.success(`File ${fileRef.name} successfully uploaded`);
        });

        uploadInstance.start();
```

**Comment by dr-dimitru** [comment]
Hello @deeeed ,

Looks like you've got disconnected (*DDP connection is broken*).
```js
// What is output of Meteor.status()?
Meteor.status();

// If you run Meteor.reconnect(), does upload continues?
Meteor.reconnect();
```

**Comment by deeeed** [comment]
Good catch, it seems to be connection related but at the same time the subscriptions have been working which don't make much sense ...

**Comment by dr-dimitru** [comment]
@deeeed  what if you change transport to HTTP? `{transport: 'http'}`
Note: `ddp` will be deprecated in v2.0 in favor of `http` as it faster and asynchronous

**Comment by deeeed** [comment]
I tried to switch to http, it works well in browser but on cordova I have different errors on android and ios. I added the debug switch and checked out the source but I am quite uncomfortable with coffeescript...
For Android:
![image](https://cloud.githubusercontent.com/assets/4800095/26256469/a3351b4c-3cef-11e7-9c75-d0f3daa1884f.png)

On my server logs:

![image](https://cloud.githubusercontent.com/assets/4800095/26256495/b4b6f50c-3cef-11e7-9274-e8ab1738bdac.png)

It seems to me that the sendEOF method is supposed to get a json string response but instead get an html result...
![image](https://cloud.githubusercontent.com/assets/4800095/26256594/107b8cc2-3cf0-11e7-889f-68d0102def08.png)

For iphone, I have a totally different error, which is:

**Failed to load resource: the server responded with a status of 405 (Method Not Allowed)**

![image](https://cloud.githubusercontent.com/assets/4800095/26256689/5ae88864-3cf0-11e7-8cde-43f4b7012dd6.png)

Server logs are not very verbose:
![image](https://cloud.githubusercontent.com/assets/4800095/26256772/971868e0-3cf0-11e7-8c9f-e5d216def834.png)

So just in case I am also attaching my collection declaration [https://gist.github.com/anonymous/5b25927d0095e9213b104687363718e1](url)


Any help greatly appreciated :)

**Comment by dr-dimitru** [comment]
@deeeed Meanwhile I'm getting into the issue, please go through [this cordova-related thread](https://github.com/VeliovGroup/Meteor-Files/issues/159).

**Comment by dr-dimitru** [comment]
Related: #418

**Comment by dr-dimitru** [comment]
Hi @deeeed ,

Turns out while testing locally you can use both DDP and HTTP transports.
Testing from devices in same W/LAN requires to set `ROOT_URL` and `--mobile-server`

example:
```shell
ROOT_URL='http://192.168.0.2:3000' meteor --mobile-server http://192.168.0.2:3000
```

**Comment by dr-dimitru** [comment]
Hi @deeeed ,

Could you please try upload with this setting on Cordova:
```js
App.accessRule("blob:*");
```

Let me know if it makes a difference

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by deeeed** [comment]
I get back on this issue since I believe I now found the cause.
On cordova, it seems the ddp connection is interrupted during the selection of the photo on the phone, thus after selection it needs time to reconnect.

My fix was to track the connection status before to begin upload:
```
tpl.autorun((c) => {
            let online = isOnline();
            // console.debug("autorun upload", online);
            if (online) {
                beginUpload(file, tpl);
                c.stop();
            }
        });
```

**Comment by dr-dimitru** [comment]
Hi @deeeed what `meteor` and `ostrio:files` versions you are on?
See #445 for more info on known issue on Android
