### ISSUE TITLE
Error with the new S3 example

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/Meteor-Files#416]
Hello,

I just modified my app to use the new S3 example (the one using aws-sdk instead of Knox). I moved the code server-side as written in the tutorial (it was in the same file as the other collections before), but now I have the error:

ReferenceError: Images is not defined

What can I do to fix this? It seems that all the images are gone. Do I still need to put some code about the Images collection inside the lib folder? Thanks!

**Comment by paulincai** [comment]
@marcoschwartz not much I can say but I noticed the example is not structured in the typical Meteor way, not it is react-like.
What  I did was to make sure:

1. Client side - new FilesCollection is only Client, not a common location.
2. Server side - literally put it on the server, make sure no client access. I get collection not defined when I initialize a collection and I don't export / import it to where I need it. For instance:

const Images = new FilesCollection etc etc on the client side. Then export { Images } and import it in the code to where you need to use it import { Images }  from you '../ your file.' I stopped using Blaze 2 years back and can't remember if Collections define global. I'd just make sure in the client side I only import { Images } of the client definition.

Where I see the difference with what I did before is that the collection is being define twice separately client and server while in Meteor you normally do it once in a common location like imports/api.

Not much but I hope it help and I also help you're not on Heroku :)

**Comment by marcoschwartz** [comment]
Thanks for the answer, but I am still confused about what to put where. Before I had it in lib (so some parts where shared by the client & server), now I put it all on server side, with the same subscribe/publish, but now the uploading & serving images doesn't work anymore. It would be good to have a clear example of all the files that need to be changed with the new aws-sdk integration, but for now it's very confusing. Thanks!

**Comment by paulincai** [comment]
I think the example shows which files go on the client:
https://github.com/VeliovGroup/Meteor-Files/pull/408/files


+### Client side example to access the file store

**Create this in a Client only side**

 +import {Meteor} from 'meteor/meteor';
 +import {FilesCollection} from 'meteor/ostrio:files';
 
 _const UserFiles_ = new FilesCollection({
 +  debug: true,
 +  collectionName: 'userFiles',
 +  allowClientCode: false, // Disallow remove files from Client
 +  onBeforeUpload: function (file) {
 +    //allow uploads under 25MB
 +    if (file.size <= 1024 * 1024 * 25) {
 +      return true;
 +    }
 +    else {
 +      return 'Please upload documents, with size equal or less than 25MB';
 +    }
 +  }
 +});
export { UserFiles }

The following goes in the code in somefile.js, in a public location. In this file you can import the declaration above to avail of it



import {  UserFiles } from '../thefileabove.js'
 +//This goes in your code once you have the files in place, from a form event
 +let file = event.currentTarget.files[0];
 +let uploadInstance = UserFiles.insert({
 +          file: file,
 +          meta: {
 +            userId: Meteor.userId()
 +          },
 +          streams: 'dynamic',
 +          chunkSize: 'dynamic',
 +          allowWebWorkers: false
 +        }, false);
 +
 +```

**Comment by marcoschwartz** [comment]
Thanks so much for the information, that made it work!

**Comment by marcoschwartz** [comment]
Another question: does somebody know if with aws-sdk the files are served from S3 or from Cloudfront? I know that with the previous example you had to enter your cloudfront URL

**Comment by dr-dimitru** [comment]
@marcoschwartz no need for CloudFront with `aws-sdk`, you can enable it if you need to have public access to the files.

**Comment by dr-dimitru** [comment]
@marcoschwartz 

> ReferenceError: Images is not defined

In new S3 example, we used "new" meteor style in mind, - where everything is stored under `/imports/` directory, and every file have to be `import`ed before it will be used.

If you're want old Meteor behavior, - just omit `const`/`let`/`var` keyword before variable - to create a global variable.

**Comment by marcoschwartz** [comment]
Awesome, thanks for all the answers! I think the new meteor style was the main issue for me. Closing this :)

**Comment by dr-dimitru** [comment]
@marcoschwartz I'm glad it's works for you now.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
