### ISSUE TITLE
v1.7.15 Syntax error?

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-Files#418]
@dr-dimitru did this update:  ostrio:files@1.7.13 to ostrio:files@1.7.15 then:
![screen shot 2017-05-19 at 22 40 25](https://cloud.githubusercontent.com/assets/26188915/26261951/3e533a98-3ce4-11e7-8c8d-25658c0322ae.png)

Would you say there might be some problems with the package?!

**Comment by paulincai** [comment]
Back to 1.7.13 everything is ok.

**Comment by paulincai** [comment]
Perhaps my fault...1.7.13 does the same, need to check some more.

**Comment by dr-dimitru** [comment]
This means [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1860) server returned HTML (*or something else*) instead of JSON

Check "Network" tab to see what was requested, and what retuned in response

**Comment by dr-dimitru** [comment]
Anyways it's a good catch, I'll what this into `try .. catch ..` and display a message to user

**Comment by dr-dimitru** [comment]
Related: #412

**Comment by dr-dimitru** [comment]
@paulincai is this happens in Cordova app?

**Comment by paulincai** [comment]
Figured that out. 
UserFiles.insert({transport: 'http'}) on DEV or local station. I am having my Android (wifi), shot a photo and inserted, got the error in the browser console (of the Android app). Reverted back to ddp, all ok. I believe http works fine with production or public deployment as I know I did photos in Heroku over http.

And this reminds me that I cannot see my pictures in Heroku, spent another 4 hours today trying to see why I get H18 on all MeteorFiles assets. No the right place to ask but would you know if and how we can force waiting for a little longer on these assets.

**Comment by paulincai** [comment]
In this situation as I imagine people might be switching that up in dev and prod, I'd display a message: You are running an http option for insert in a local environment. Please switch to ddp while in development.

**Comment by dr-dimitru** [comment]
But it works fine on my end, as long as I provide proper `ROOT_URL` which points to my IP address at W/LAN

**Comment by dr-dimitru** [comment]
@paulincai have you tried something like?:
```shell
ROOT_URL='http://192.168.0.2:3000' meteor --mobile-server http://192.168.0.2:3000
```

**Comment by paulincai** [comment]
@dr-dimitru yes, just did and got the same error. I am pushing now again to Heroku just to make sure everything is fine there. So just to answer to you I got the same error with and without ROOT_URL while on local.

**Comment by dr-dimitru** [comment]
@paulincai I would like to see your "Network" tab, including headers

**Comment by paulincai** [comment]
@dr-dimitru by that you mean browser console inspector tab?

**Comment by dr-dimitru** [comment]
@paulincai right, screenshot of few

**Comment by paulincai** [comment]
@dr-dimitru sorry for the wait, was little busy with Heroku where unfortunately seem to get the same result. In red is Android and last line is IOS. Taking console shots now and get back to you.
![screen shot 2017-05-20 at 00 21 52](https://cloud.githubusercontent.com/assets/26188915/26265493/67f848da-3cf2-11e7-979a-01b0b0700058.png)

**Comment by dr-dimitru** [comment]
@paulincai I thought it's Client error, isn't it?
This screenshot doesn't tells much, browser's "Network" tab in inspector will tell more

**Comment by dr-dimitru** [comment]
I'm fighting with Heroku issue now too

**Comment by paulincai** [comment]
No output to the network tab :( . Like o, not moving...
![screen shot 2017-05-20 at 00 26 33](https://cloud.githubusercontent.com/assets/26188915/26265670/1874a942-3cf3-11e7-99e1-7ba5dbef7b40.png)

**Comment by dr-dimitru** [comment]
I see WebWorker is disabled, right? Why?

**Comment by paulincai** [comment]
@dr-dimitru  What I did earlier today that might affect is that I installed the npm throttle. I just removed it and retrying everything again

**Comment by paulincai** [comment]
@dr-dimitru this is my insert config:
![Uploading Screen Shot 2017-05-20 at 00.37.53.png…]()
because of the next shot. I though for the time being until things are clear, I should go the safer side  and that looked safer by the wording.
![screen shot 2017-05-20 at 00 37 19](https://cloud.githubusercontent.com/assets/26188915/26266160/37dc5846-3cf5-11e7-9715-ab4f3354a1e9.png)

**Comment by dr-dimitru** [comment]
Sure, I've asked to test if there is any difference in behavior w/o WebWorkers

**Comment by dr-dimitru** [comment]
Please update to the latest release, let's see if this issue is changed/fixed

**Comment by dr-dimitru** [comment]
Hello @paulincai ,

Is this one solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
