### ISSUE TITLE
S3 Photo Assets unavailable after exactly 2 minutes

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-Files#421]
V1.7.16, local station. After exactly 2 minutes, my photos disappear from the view and I get this in the console (see below). This is valid for Cordova and Web.
I cannot confirm the behavior in my production deployment since I cannot deploy to Heroku.

![screen shot 2017-05-20 at 13 36 13](https://cloud.githubusercontent.com/assets/26188915/26276217/b6b2b582-3d83-11e7-8e05-e3a3e8c95a6c.png)

**Comment by dr-dimitru** [comment]
@paulincai 
 - Does this happens in a browser? 
 - What code is used to produce this error?
 - Any server errors?
 - I would like to see network tab

**Comment by paulincai** [comment]
- Happens in a browser as well as Cordova (installed App)

- I am not sure if this is what you are asking, the error was shown from Chrome dev console

- No server errors. This just looks like a disconnection from files not from the server. The server shows me if a client gets disconnected but I am not disconnected, I just loose touch with the files.

Below, first is IOS, then Android then Chrome Web on the same station

In IOS you can see out of 4 images, the second (in black not red) is with Cached on Yes. That is the one that remains on the screen "forever" as expected.
![ios](https://cloud.githubusercontent.com/assets/26188915/26276654/60bccfa6-3d8c-11e7-8366-bf3f6b064811.png)
![android](https://cloud.githubusercontent.com/assets/26188915/26276666/9a6bb0fa-3d8c-11e7-8442-a5f214ef5ddd.png)

![Uploading Chrome Web.png…]()

**Comment by paulincai** [comment]
@dr-dimitru something worth mentioning, I haven't done the changes to code, as mentioned in your comments of the last version. This is my code that was working in 1.7.14 with the package update at 1.7.16.

I am catching up now with the changes you suggested and will test again.

**Comment by dr-dimitru** [comment]
1. Is there enabled filter (red funnel icon) in Android Chrome Debugger? As there is no worthy info at all
 2. Safari dev tools is almost useless too
 3. Third screenshot is broken
 4. Could you enable `debug`, to check if request for image(s) reached Server?

**Comment by dr-dimitru** [comment]
Btw,
 - `1.7.15` first time `Npm.require` changed to `require`
 - `1.7.16` `require` changed back to `Npm.require`, due to #417
 - So `1.7.14` and `1.7.16` should be the same in terms of file upload and file serving

**Comment by paulincai** [comment]
Don't really know what was in my mind when I sent you files with no meaning :). Here we go:
The first screen shows failure after 2 minutes
![screen shot 2017-05-20 at 19 52 02](https://cloud.githubusercontent.com/assets/26188915/26277263/35ec0eb8-3d96-11e7-9396-fa8d709a59c2.png)

the next 3 shots with specific names shows the same browser, just refreshed with a different behavior, at time will just bring only 2 files instead of 4. First 2 files are pending for almost 2 minutes then they show and the other 2 files are disconnected. After another almost 2 minutes those 2 files get disconnected too.

 
![at start](https://cloud.githubusercontent.com/assets/26188915/26277402/a4311f84-3d97-11e7-8c1d-aa804efec205.png)

![2 min](https://cloud.githubusercontent.com/assets/26188915/26277411/ddf2bc32-3d97-11e7-91b7-5d69a442d9ca.png)

![3 5min](https://cloud.githubusercontent.com/assets/26188915/26277418/fac926f2-3d97-11e7-9fa2-740c26f59181.png)


Lastly, the server console shows the following on refresh ( download of images) and nothing else when they disappear.

![screen shot 2017-05-20 at 20 06 22](https://cloud.githubusercontent.com/assets/26188915/26277431/47ef9524-3d98-11e7-8577-c93b444869c8.png)

**Comment by dr-dimitru** [comment]
I would like to see headers of any failed file.
Speaking of error - it's obvious, some why size of the file differs from what mentioned in headers.
 1. Are files stored on FS locally or at AWS:S3?
 2. How do you create thumbs? Do you update/save it's meta-data on Mongo?
 3. Could you post one of the MongoDB records, where file has subversions?
 4. In terms of debugging set `integrityCheck: true` on *FilesCollection* Constructor

**Comment by dr-dimitru** [comment]
Other thought - somewhy middleware didn't catch the request and returns HTML as in #418 and #412

**Comment by dr-dimitru** [comment]
Ok, sorry for `Are files stored on FS locally or at AWS:S3?` question, so if requests is piped to AWS:S3 and `Content-Length`  is mismatch - S3 somehow changed the files.

Could you post your `interceptDownload`? If you're using code from [this tutorial](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration) compare file size in `this.httpResponse.headers` and `fileRef.versions[version]`, does it differs?

**Comment by paulincai** [comment]
Testing now with the config in the tutorial. Get back to you in 2 min

**Comment by paulincai** [comment]
While re-writing this area of the code I understood the parts in the 'new' intercept which are closely related to my disconnection. What I suspected, but with no scientific reasons was that my preview file is being replaced by my original file. DB records show good, no issues to suspect in that area. However, as I am writing, it's been 5 minute and the "streaming" is going on. I think we are perfectly fine now. Will give it 10 more minutes and then we can close the matter.

**Comment by paulincai** [comment]
Incredibly fast, no words to describe... love and thanks for looking all day over all these useless screen shots I've been sending to you ...
I'll be focusing on Heroku now

**Comment by dr-dimitru** [comment]
Great, see you at #420
