### ISSUE TITLE
Question about code fileRef, vRef

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-Files#425]
@dr-dimitru in my code, maybe I am doing something different and have different data types.

In onAfterUpload(fileRef) where you put the object:

![screen shot 2017-05-21 at 06 14 15](https://cloud.githubusercontent.com/assets/26188915/26280618/d3e0a75e-3dec-11e7-9de1-ad0179256b45.png)

I have fileRef as Object and vRef as String, and I am fine with it.
ex vRef: assets/app/uploads/uploadedFiles/x320-6nPmJGbTw9o4wH6es.jpeg . I guess this is the path to the file on the local storage before moving to S3.

You have vRef as Object (e.g. vRef.type). Would you please confirm it is an object in your case.

**Comment by dr-dimitru** [comment]
> Would you please confirm it is an object in your case.

Yes, it's an Object on my end.
```js
const vRef = fileRef[version];
```

Where `version` is name of subversion, like `original` or `thumbnail`

**Comment by paulincai** [comment]
Ok, thanks, I found the place where I am switching the type, same name but different functions. It goes into the image processing as object and comes out as a string :)). Full processing... Tx a lot
