### ISSUE TITLE
Question: Documentation - study case: mobile camera to S3

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-Files#426]
@dr-dimitru in order to add value to this amazing repo which really serves entirely my demand for security and confidentiality, I would like to share part of my code workflow, tested on mobile, documented, as a possible inspiration for the mobile developers using this library (mobile being so important today). I would count on you to touch it if you feel something is not right and give it in the best shape to the users. I am having the entire workflow take the image, process with canvas on the mobile (with estimated size) pass to the insert procedure for upload to Material Files and process via IM and then pass it to S3 uploader. So...what do you think?

**Comment by dr-dimitru** [comment]
Sure, let's do it.

**Comment by paulincai** [comment]
@dr-dimitru ...working on it.

**Comment by jwaitze** [comment]
@paulincai I recently implemented the same procedure in one of my projects. (input file(s) -> proportional resizing via canvas -> upload to Meteor-Files -> create thumbnail using GraphicsMagick/ImageMagick -> upload original and thumbnail to S3 bucket -> update files collection with file retrieval information)

I support your idea to share this workflow with the community - and I'd like to share my implementation with you if you think it could help with your documenting. Let me know =)

**Comment by mgscreativa** [comment]
Hi! @paulincai @jwaitze !
Are you planning to release the example in React Native code?

**Comment by paulincai** [comment]
@jwaitze @mgscreativa my intention is for Meteor (indeed), React, ES6.
@jwaitze I am thinking to document very well what we put in the code. For instance...what and why with Canvas. Perhaps we should do two-three comparison tests for image resolutions like time taken to process the base64 through canvas. For ImageMagick, I have a workflow for polaroid (not the polaroid offered by IM cause that is a little useless for the mobile screen. Again, I think we should offer some hints there for how to build the modifiers and some links to the documents. I mean when an individual goes through the document she should find all sources of information (that  we used) and no need to start intensive searches in stackoverflow, google, etc. I am a rather new programmer converted from Technology management so you may expect that I am still in the phase ...if it does the job...it does the job.. :). So let's build on our stuff before we add it here. Should we do a separate repo just to edit documents and maintain communication without polluting this repo? At the end we add the document here and vanish the working repo.

**Comment by dr-dimitru** [comment]
> Should we do a separate repo just to edit documents and maintain communication without polluting this repo?

You are free to push your progress to this repo.
Are you planning to fit everything into single document?

**Comment by dr-dimitru** [comment]
Hello @paulincai ,

Do you have any news on this thread?

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if you are going to finish this idea
