### ISSUE TITLE
Can't find npm module 'file-type'

### ISSUE THREAD

**Issue by MhdTahsinAlshalabi** [VeliovGroup/Meteor-Files#427]
i have this error after install  ostrio:files and import it,

Error: Can't find npm module 'file-type'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?

I did this :
1- meteor add ostrio:files in terminal 
and in my source code i just add this line and get the a above error.
2- import { FilesCollection } from "meteor/ostrio:files";

My environment
ubuntu: 16.4 , 64bit
meteor: 1.4.4.2
npm : 3.10.3

**Comment by dr-dimitru** [comment]
Hello @MhdTahsinAlshalabi ,

Please see #417 #420 and https://github.com/meteor/meteor/issues/8708

Let me know how it works for you.

**Comment by dr-dimitru** [comment]
Just noticed NPM version on your end is outdated, please update NPM to 4.5.0, and make sure node.js is 4.8.2 [as required by Meteor](https://github.com/meteor/meteor/blob/devel/History.md#v1442-2017-05-02)
```shell
npm install -g npm@4
```

**Comment by dr-dimitru** [comment]
- Is updating NPM solved this issue?
 - Anyways issue was confirmed by other users, please update to [v1.7.17](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.17) and  let me know how it work for you

**Comment by MhdTahsinAlshalabi** [comment]
Thanks  for all this efforts @dr-dimitru
I fix this issue by install file-type

` npm install --save file-type`
https://www.npmjs.com/package/file-type
Thanks again  👍
