### ISSUE TITLE
Protected this.userId is null on IOS and Android

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-Files#429]
@dr-dimitru I believe this is something we already discussed about but I am not getting anywhere with it.  A short summary.
Under **'protected'**, I am getting **this.userId** from browser but IOS and Android return null. (I am in production on Heroku)
If I am not wrong last time you said to resolve this function/situation on another side, via publications or methods and determine authorization to access.

After battling with this the whole night, I am out of ideas. The point is that if I don't return under **'protected'** the right **true** I cannot have the files secured. It is only under **protected** as far as I understand, that I can totally deny access to an URL, otherwise, I can copy-paste the URL, give it to you and you get the document. Unless I know who you are, I cannot decide whether I should let you access it or not.
Example in my case: I need to share a document with 2 other users which are part of a discussion. I want to prevent them from extending the link to other people (from Browser Inspector for instance). On the other hand, I want to deny them access after we are done with the discussion. I have an array of user ids I need to compare against but when on mobile...there is nothing I can pull from them to compare against the allowed access array. Even if I un-publish this data from them, if they somehow retain the links, they can access data.

The HTML header doesn't seem to help either. There is no userId coming over with the session.

Any suggestions?

**Comment by dr-dimitru** [comment]
Hello @paulincai ,

Please see [this comment](https://github.com/VeliovGroup/Meteor-Files/issues/159#issuecomment-266405812).
And its implementation in [this PR](https://github.com/thomasspiesser/ostrio-files-bug/pull/1/files)

Let me know what do you think.

**Comment by dr-dimitru** [comment]
Hi @paulincai ,

Any news on this one?

**Comment by dr-dimitru** [comment]
@paulincai any news on this one? Can we close it in favor of #159 ?

**Comment by paulincai** [comment]
@dr-dimitru I believe this can be closed now. The solution offered in #159 worked satisfactory. I know I am behind with my study case but please note that I didn't forget nor abandoned.

**Comment by dr-dimitru** [comment]
> note that I didn't forget nor abandoned.

Noted. No, worries.
