### ISSUE TITLE
Backend file link for React example?

### ISSUE THREAD

**Issue by mikasjoman** [VeliovGroup/Meteor-Files#431]
### I have a suggestion:

That you add a link to the backend code to the https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example

I have not yet figured out where to find the backend code even though you write "the server side methods and publications the same."

**Comment by dr-dimitru** [comment]
Hello @mikasjoman ,

Sorry for delay (*actually I just forgot to respond here*), it's done now - https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example

Let me know if it's expressive enough.
