### ISSUE TITLE
 Error: Can't find npm module 'fs-extra'

### ISSUE THREAD

**Issue by stefanve** [VeliovGroup/Meteor-Files#432]
After updating to Meteor  1.4.4.3  and ostrio:files@1.7.16 I get:

 Error: Can't find npm module 'fs-extra'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?

After downgrading to ostrio:files@1.7.13 everything worked again

**Comment by dr-dimitru** [comment]
Duplicate, see #427 and #420 for solution

**Comment by dr-dimitru** [comment]
Should be fixed in [v1.7.17](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.17) please update, let me know how it work for you

**Comment by stefanve** [comment]
Tested with Meteor 1.5 and it seem to work fine. Thank you!

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
