### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by haojia321** [VeliovGroup/Meteor-Files#434]
One of my meteor package is using ostrio:files. After upgrading to latest ostrio:files and latest meteor. I got below issue, issue will not happen if I remove ostrio:files dependency from my package.

```
modules.js?hash=355b762…:22419 Uncaught ReferenceError: Buffer is not defined
    at util.js (modules.js?hash=355b762…:22419)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at meteorInstall.node_modules.meteor-node-stubs.node_modules.readable-stream.lib._stream_readable.js (modules.js?hash=355b762…:18103)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at meteorInstall.node_modules.meteor-node-stubs.node_modules.readable-stream.readable.js (modules.js?hash=355b762…:18038)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at meteorInstall.node_modules.meteor-node-stubs.node_modules.stream-browserify.index.js (modules.js?hash=355b762…:17922)
```

**Comment by dr-dimitru** [comment]
What Meteor version and Meteor-Files version you're on?
BTW two of latest releases somehow broken (#420), have you tried to downgrade?

**Comment by dr-dimitru** [comment]
@haojia321 just found this - https://github.com/meteor/meteor/issues/8645#issuecomment-302253375

**Comment by dr-dimitru** [comment]
Hello @haojia321 ,

Have you fixed it?

**Comment by haojia321** [comment]
Sorry for the delay @dr-dimitru , Yes this work around will work by add global.Buffer = global.Buffer || require("buffer").Buffer;

But my question is, will it be better to handle this in ostrio:files package itself?

**Comment by dr-dimitru** [comment]
> But my question is, will it be better to handle this in ostrio:files package itself?

Sure update is coming.

**Comment by haojia321** [comment]
@dr-dimitru as always, you rock!

**Comment by dr-dimitru** [comment]
@haojia321 have you already tried [dynamic `import()`](https://forums.meteor.com/t/flow-router-meteor-1-5-per-route-dynamic-import/36870)?

**Comment by haojia321** [comment]
No, we are still in 1.4.4.3. Will update in here after we update to meteor 1.5.

Should we remove tag wont fix if we are planning to fix in package itself?

**Comment by dr-dimitru** [comment]
> Should we remove tag wont fix if we are planning to fix in package itself?

But this behavior won't change anytime in the future, due to core changes in Meteor>=1.5

**Comment by dr-dimitru** [comment]
I'm going to reopen this. As we can't reproduce this error with our 3 demo apps, nor with our production app. Need more investigation.

**Comment by dr-dimitru** [comment]
@haojia321 is this still an issue?

**Comment by haojia321** [comment]
Hi @dr-dimitru,
As we discussed above by adding global.Buffer = global.Buffer || require("buffer").Buffer;

Do you think it will be possible to put that code in your package since your package is using Buffer and Meteor no longer set Buffer to global variable? That way might help package user keeping their code clean?

**Comment by dr-dimitru** [comment]
It's not this package issue. We can't reproduce this error with our 3 demo apps, nor with our production app. Are you sure `Buffer` is not used anywhere in your app' code, NPN or Atmosphere packages?

**Comment by haojia321** [comment]
Any idea how to check if Buffer is used by certain packages?

-- 
Best regards
Hao Jia
Cell phone: 641-455-9631
Send from my iPhone 7

**Comment by dr-dimitru** [comment]
No idea, maybe better to [ask here](https://github.com/meteor/meteor/issues/8645) or [search here](https://github.com/meteor/meteor/search?utf8=✓&q=Buffer&type=) one of the first is widely used OAuth.

**Comment by haojia321** [comment]
Ok. Im closing this issue here.

**Comment by dr-dimitru** [comment]
If you will find which package caused it, left its name here

**Comment by Vandell63** [comment]
Hi there, I got this issue in one way if :  
```
const Images = new FilesCollection({
	collectionName: 'Images',
	onBeforeUpload(file) {
	},
	onAfterUpload(file) {
            ///SERVER SIDE NO ISSUE WITH BUFFER
        }
```
But if you use it with the eventListener : 

`Images.on('afterUpload'....` /// CLIENT SIDE 
effectively you'll get the issue Buffer is not defined. 
global.Buffer = global.Buffer || require("buffer").Buffer is a nice workaround.

**Comment by dr-dimitru** [comment]
Hello @Vandell63 ,

Thank you for this exploring.
```js
Images.on('afterUpload')
```
Is *Server* only event as well as  `onBeforeUpload` *Server* only hook.
I can not assume it as issue as it is not supposed to be used on the *Client*.
