### ISSUE TITLE
There is no route for the path

### ISSUE THREAD

**Issue by lleoooell** [VeliovGroup/Meteor-Files#436]
HI everybody,

Thanks for this awesome package,

i setup the package to work with S3 upload, everything seems to work fine...
my problem is to display the images on the client, 
i have a helper who bring me the url with the .link() function.
but when i try to access http://localhost:3000/cdn/storage/2uvdTA7XXnNNtizss.png
i've got an error from flow router : 
kadira_flow-router.js?hash=4ca3941…:519 There is no route for the path: /cdn/storage/2uvdTA7XXnNNtizss.png

how can i setup flow router to drive the request correctly ? what i'am doing wrong ?
i presume the magic is located under the interceptDownload function ?

Thanks for your help.

Best regards,
Léo

**Comment by dr-dimitru** [comment]
Hello @lleoooell ,

Could you please post your `.meteor/packages` file?
My quick guess is `kadira:flow-router` placed above `ostrio:files`, if I'm right - that means `flow-router` intercepts requests and not passing it no next listener. To solve this, simply place `ostrio:files` above `kadira:flow-router` in `.meteor/packages` file

**Comment by lleoooell** [comment]
Hi @dr-dimitru 
Thanks for your quick answer !
Your guess was right, but it solved 50% of the problem, with ostrio:files above kadira:flow-router, there is no more error message of 'no route for path' in the client console...but still a 404 page not found...
<img width="864" alt="capture d ecran 2017-06-01 a 22 10 06" src="https://cloud.githubusercontent.com/assets/8329070/26698664/1c6ab9fa-4717-11e7-9adc-ecc83d48b927.png">
<img width="788" alt="capture d ecran 2017-06-01 a 22 09 44" src="https://cloud.githubusercontent.com/assets/8329070/26698671/23d28ad8-4717-11e7-9f97-9cf7749e0bee.png">

**Comment by dr-dimitru** [comment]
1. Does this works locally?
 2. Enable debug mode with `{debug: true}` passed into `FilesCollection` constructor - so we will see if request reaches `FilesCollection`, and where it stuck. Post here both Client and Server logs

**Comment by lleoooell** [comment]
1. yes, It works locally, after i remove onAfterUpload() and interceptDownload() functions in my files.js.
url generated by .link() is :
http://localhost:3000/cdn/storage/Images/zhSqdv9QjowCfDLey/original/zhSqdv9QjowCfDLey.png
(with S3 setup was : http://localhost:3000/cdn/storage/2uvdTA7XXnNNtizss.png)
<img width="816" alt="capture d ecran 2017-06-01 a 22 33 14" src="https://cloud.githubusercontent.com/assets/8329070/26699572/ad3677aa-471a-11e7-9dbe-ea818b156bc3.png">
(only the first object is find because the previous one was uploaded with my S3 setup)
2 See here server logs : 
<img width="1032" alt="capture d ecran 2017-06-01 a 22 34 52" src="https://cloud.githubusercontent.com/assets/8329070/26699636/dae572c8-471a-11e7-887a-10f5344dfe71.png">

my guess is that i really have a problem with my intercept function...

**Comment by dr-dimitru** [comment]
1. How do you generate a link? With `FileCursor#link()` method or `{{fuleURL fileObj}}` helper?
 2. My guess something wrong in `onAfterUpload()` as link generated out of the record in MongoDB, and your screenshot (with requested URL) indicates what something is missing

**Comment by lleoooell** [comment]
when i upload a picture with my S3 setup i presume everything is ok for the upload part : 
<img width="964" alt="capture d ecran 2017-06-01 a 22 42 38" src="https://cloud.githubusercontent.com/assets/8329070/26699906/c3b4af14-471b-11e7-9a8d-ea1277ee5eb4.png">
but as soon as i try to display it : 
<img width="1049" alt="capture d ecran 2017-06-01 a 22 44 31" src="https://cloud.githubusercontent.com/assets/8329070/26699964/fcfaee50-471b-11e7-8816-1a4323d00878.png">

and here is the function, basically the one pasted from the example : 
` interceptDownload(http, fileRef, version) {
      let path;

      if (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) {
        path = fileRef.versions[version].meta.pipePath;
      }

      if (path) {
        // If file is successfully moved to AWS:S3
        // We will pipe request to AWS:S3
        // So, original link will stay always secure

        // To force ?play and ?download parameters
        // and to keep original file name, content-type,
        // content-disposition, chunked "streaming" and cache-control
        // we're using low-level .serve() method
        const opts = {
          Bucket: s3Conf.bucket,
          Key: path
        };

        if (http.request.headers.range) {
          const vRef  = fileRef.versions[version];
          let range   = _.clone(http.request.headers.range);
          const array = range.split(/bytes=([0-9]*)-([0-9]*)/);
          const start = parseInt(array[1]);
          let end     = parseInt(array[2]);
          if (isNaN(end)) {
            // Request data from AWS:S3 by small chunks
            end       = (start + this.chunkSize) - 1;
            if (end >= vRef.size) {
              end     = vRef.size - 1;
            }
          }
          opts.Range   = `bytes=${start}-${end}`;
          http.request.headers.range = `bytes=${start}-${end}`;
        }

        const fileColl = this;
        s3.getObject(opts, function (error) {
          if (error) {
            console.error(error);
            if (!http.response.finished) {
              http.response.end();
            }
          } else {
            if (http.request.headers.range && this.httpResponse.headers['content-range']) {
              // Set proper range header in according to what is returned from AWS:S3
              http.request.headers.range = this.httpResponse.headers['content-range'].split('/')[0].replace('bytes ', 'bytes=');
            }

            const dataStream = new stream.PassThrough();
            fileColl.serve(http, fileRef, fileRef.versions[version], version, dataStream);
            dataStream.end(this.data.Body);
          }
        });

        return true;
      }
      // While file is not yet uploaded to AWS:S3
      // It will be served file from FS
      return false;
    }`

**Comment by dr-dimitru** [comment]
Could you add `console.log(fileColl)` after it's defined and before `.serve` to check what is there?

**Comment by lleoooell** [comment]
I'm generating a link like that : 

_in my template html : 
`<img class="pulseImg" src="{{getImageById imgId}}">
`
getImageById is a global client helper : 
`Template.registerHelper('getImageById', function(id) {
    var test = Images.findOne({"_id" : id});
    console.log(test.link());
    return test.link();

});`

**Comment by lleoooell** [comment]
here is my console log fileCol
`I20170601-22:52:15.535(2)? FilesCollection {
I20170601-22:52:15.549(2)?   domain: null,
I20170601-22:52:15.571(2)?   _events: { handleUpload: [Function], finishUpload: [Function] },
I20170601-22:52:15.572(2)?   _eventsCount: 2,
I20170601-22:52:15.572(2)?   _maxListeners: undefined,
I20170601-22:52:15.573(2)?   storagePath: 'assets/app/uploads/uploadedFiles',
I20170601-22:52:15.573(2)?   collectionName: 'Images',
I20170601-22:52:15.573(2)?   downloadRoute: '/cdn/storage',
I20170601-22:52:15.573(2)?   schema: 
I20170601-22:52:15.574(2)?    { size: { type: [Function: Number] },
I20170601-22:52:15.574(2)?      name: { type: [Function: String] },
I20170601-22:52:15.574(2)?      type: { type: [Function: String] },
I20170601-22:52:15.574(2)?      path: { type: [Function: String] },
I20170601-22:52:15.575(2)?      isVideo: { type: [Function: Boolean] },
I20170601-22:52:15.575(2)?      isAudio: { type: [Function: Boolean] },
I20170601-22:52:15.575(2)?      isImage: { type: [Function: Boolean] },
I20170601-22:52:15.575(2)?      isText: { type: [Function: Boolean] },
I20170601-22:52:15.575(2)?      isJSON: { type: [Function: Boolean] },
I20170601-22:52:15.576(2)?      _prefix: { type: [Function: String] },
I20170601-22:52:15.577(2)?      extension: { type: [Function: String], optional: true },
I20170601-22:52:15.577(2)?      _storagePath: { type: [Function: String] },
I20170601-22:52:15.579(2)?      _downloadRoute: { type: [Function: String] },
I20170601-22:52:15.579(2)?      _collectionName: { type: [Function: String] },
I20170601-22:52:15.579(2)?      public: { type: [Function: Boolean], optional: true },
I20170601-22:52:15.610(2)?      meta: { type: [Function: Object], blackbox: true, optional: true },
I20170601-22:52:15.745(2)?      userId: { type: [Function: String], optional: true },
I20170601-22:52:15.745(2)?      updatedAt: { type: [Function: Date], autoValue: [Function] },
I20170601-22:52:15.746(2)?      versions: { type: [Function: Object], blackbox: true } },
I20170601-22:52:15.746(2)?   chunkSize: 524288,
I20170601-22:52:15.751(2)?   namingFunction: false,
I20170601-22:52:15.751(2)?   debug: true,
I20170601-22:52:15.752(2)?   onbeforeunloadMessage: undefined,
I20170601-22:52:15.753(2)?   permissions: 420,
I20170601-22:52:15.753(2)?   parentDirPermissions: 493,
I20170601-22:52:15.754(2)?   allowClientCode: true,
I20170601-22:52:15.754(2)?   onBeforeUpload: [Function],
I20170601-22:52:15.754(2)?   integrityCheck: true,
I20170601-22:52:15.754(2)?   protected: false,
I20170601-22:52:15.755(2)?   public: false,
I20170601-22:52:15.755(2)?   strict: true,
I20170601-22:52:15.755(2)?   downloadCallback: false,
I20170601-22:52:15.755(2)?   cacheControl: 'public, max-age=31536000, s-maxage=31536000',
I20170601-22:52:15.755(2)?   throttle: false,
I20170601-22:52:15.756(2)?   onAfterUpload: [Function],
I20170601-22:52:15.756(2)?   interceptDownload: [Function],
I20170601-22:52:15.756(2)?   onBeforeRemove: false,
I20170601-22:52:15.756(2)?   _writableStreams: {},
I20170601-22:52:15.756(2)?   cursor: null,
I20170601-22:52:15.757(2)?   search: { _id: 'zSHfCfczsD9PExnh6' },
I20170601-22:52:15.757(2)?   collection: 
I20170601-22:52:15.757(2)?    { _makeNewID: [Function],
I20170601-22:52:15.757(2)?      _transform: null,
I20170601-22:52:15.758(2)?      _connection: 
I20170601-22:52:15.758(2)?       { options: [Object],
I20170601-22:52:15.758(2)?         onConnectionHook: [Object],
I20170601-22:52:15.758(2)?         onMessageHook: [Object],
I20170601-22:52:15.758(2)?         publish_handlers: [Object],
I20170601-22:52:15.759(2)?         universal_publish_handlers: [Object],
I20170601-22:52:15.759(2)?         method_handlers: [Object],
I20170601-22:52:15.759(2)?         sessions: [Object],
I20170601-22:52:15.759(2)?         stream_server: [Object] },
I20170601-22:52:15.762(2)?      _collection: 
I20170601-22:52:15.769(2)?       { find: [Function: bound ],
I20170601-22:52:15.770(2)?         findOne: [Function: bound ],
I20170601-22:52:15.770(2)?         insert: [Function: bound ],
I20170601-22:52:15.771(2)?         update: [Function: bound ],
I20170601-22:52:15.771(2)?         upsert: [Function: bound ],
I20170601-22:52:15.771(2)?         remove: [Function: bound ],
I20170601-22:52:15.771(2)?         _ensureIndex: [Function: bound ],
I20170601-22:52:15.771(2)?         _dropIndex: [Function: bound ],
I20170601-22:52:15.772(2)?         _createCappedCollection: [Function: bound ],
I20170601-22:52:15.772(2)?         dropCollection: [Function: bound ],
I20170601-22:52:15.772(2)?         rawCollection: [Function: bound ] },
I20170601-22:52:15.772(2)?      _name: 'Images',
I20170601-22:52:15.773(2)?      _driver: { mongo: [Object] },
I20170601-22:52:15.773(2)?      _restricted: false,
I20170601-22:52:15.773(2)?      _insecure: undefined,
I20170601-22:52:15.773(2)?      _validators: 
I20170601-22:52:15.774(2)?       { insert: [Object],
I20170601-22:52:15.774(2)?         update: [Object],
I20170601-22:52:15.774(2)?         remove: [Object],
I20170601-22:52:15.774(2)?         upsert: [Object],
I20170601-22:52:15.775(2)?         fetch: [],
I20170601-22:52:15.775(2)?         fetchAllFields: false },
I20170601-22:52:15.775(2)?      _prefix: '/Images/' },
I20170601-22:52:15.775(2)?   currentFile: 
I20170601-22:52:15.776(2)?    { _id: 'zSHfCfczsD9PExnh6',
I20170601-22:52:15.777(2)?      name: 'Capture d’écran 2017-05-28 à 21.35.29.png',
I20170601-22:52:15.777(2)?      extension: 'png',
I20170601-22:52:15.778(2)?      path: 'assets/app/uploads/uploadedFiles/zSHfCfczsD9PExnh6.png',
I20170601-22:52:15.778(2)?      meta: {},
I20170601-22:52:15.785(2)?      type: 'image/png',
I20170601-22:52:15.786(2)?      size: 251545,
I20170601-22:52:15.786(2)?      versions: { original: [Object] },
I20170601-22:52:15.786(2)?      isVideo: false,
I20170601-22:52:15.787(2)?      isAudio: false,
I20170601-22:52:15.788(2)?      isImage: true,
I20170601-22:52:15.789(2)?      isText: false,
I20170601-22:52:15.789(2)?      isJSON: false,
I20170601-22:52:15.789(2)?      _prefix: 'daed0032bd8efdc5224d5da5b99f1f3641b9432a8c11d7c2e5e400b8aa3791e2',
I20170601-22:52:15.790(2)?      _storagePath: 'assets/app/uploads/uploadedFiles',
I20170601-22:52:15.800(2)?      _downloadRoute: '/cdn/storage',
I20170601-22:52:15.800(2)?      _collectionName: 'Images',
I20170601-22:52:15.800(2)?      userId: 'aRLmKuAbtJc9fJXoH',
I20170601-22:52:15.801(2)?      public: false },
I20170601-22:52:15.801(2)?   _prefix: 'daed0032bd8efdc5224d5da5b99f1f3641b9432a8c11d7c2e5e400b8aa3791e2',
I20170601-22:52:15.801(2)?   checkAccess: [Function],
I20170601-22:52:15.802(2)?   methodNames: 
I20170601-22:52:15.802(2)?    { MeteorFileAbort: 'MeteorFileAbortdaed0032bd8efdc5224d5da5b99f1f3641b9432a8c11d7c2e5e400b8aa3791e2',
I20170601-22:52:15.802(2)?      MeteorFileWrite: 'MeteorFileWritedaed0032bd8efdc5224d5da5b99f1f3641b9432a8c11d7c2e5e400b8aa3791e2',
I20170601-22:52:15.803(2)?      MeteorFileUnlink: 'MeteorFileUnlinkdaed0032bd8efdc5224d5da5b99f1f3641b9432a8c11d7c2e5e400b8aa3791e2' },
I20170601-22:52:15.803(2)?   remove: [Function] }`

**Comment by dr-dimitru** [comment]
Could you check what is inside `test` ? `console.log(test)`

**Comment by dr-dimitru** [comment]
according to your log `fileCol` is exists and has right value.
What FilesCollection version you're on? May be it's too old to have `.serve`?

**Comment by lleoooell** [comment]
test looks like this : 
<img width="704" alt="capture d ecran 2017-06-01 a 22 59 07" src="https://cloud.githubusercontent.com/assets/8329070/26700549/0bd216fe-471e-11e7-86a6-015c3b022d5c.png">

ostrio file version is :  
ostrio:files@1.5.6

(many thanks for your help)

**Comment by dr-dimitru** [comment]
Yes `ostrio:files@1.5.6` is too old to have `.serve`, and may have other bugs.
Could you update?

**Comment by dr-dimitru** [comment]
Funny thing today `ostrio:files@1.5.6` is exactly an year old

**Comment by lleoooell** [comment]
yes, i did !!!! and it woks right now...
I'm sorry for all of this...and thank you so much for your time...i only install package with meteor add...and didn't check the version...

i run 
meteor update ostrio:file 
(it update to 1.7.)

then i had to install fs extra : 
meteor npm install fs.extra --save
and file type, 
meteor npm install file-type --save

because i had this error : 
Error: Can't find npm module 'file-type'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
same for fs extra.

but now, everything is working...thank you so much !!!!!!!

**Comment by dr-dimitru** [comment]
> but now, everything is working...thank you so much !!!!!!!

Great! 👍 

> then i had to install fs extra :
> and file type,

Yes, latest release have annoying issue with NPM dependencies, stay tuned for updates at #420

> I'm sorry for all of this...and thank you so much for your time...i only install package with meteor add...and didn't check the version...

No worries, I'm glad to help. Check out our other [meteor packages](https://atmospherejs.com/ostrio).

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)

**Comment by lleoooell** [comment]
done ^^

**Comment by fmorgens** [comment]
I am having a similar issue. I get the same error message (There is no route for the path) when trying to access a file. 
I moved ostrio:files above kadira:flow-router but that didn't help.
I am using version 1.13. 
If I set public to true in the constructor it works.
But I dont want everyone to be able to access the files so that is not an option.

**Comment by dr-dimitru** [comment]
@fmorgens If you've solved your issue — feel free to share a solution
