### ISSUE TITLE
Updated to Meteor 1.5 and getting some errors

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-Files#437]
Hi! I tested updated my meteor project to M 1.5 and got this at startup, so the app won't start

> W20170601-19:53:36.476(-3)? (STDERR) /home/.meteor/packages/meteor-tool/.1.5.0.1hpmnt8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
> W20170601-19:53:36.476(-3)? (STDERR) 						throw(ex);
> W20170601-19:53:36.477(-3)? (STDERR) 						^
> W20170601-19:53:36.478(-3)? (STDERR) 
> W20170601-19:53:36.478(-3)? (STDERR) Error: Can't find npm module 'file-type'. Did you forget to call 'Npm.depends' in package.js within the 'ostrio_files' package?
> W20170601-19:53:36.479(-3)? (STDERR)     at Object.require (/home/projects/project/meteor-server-app/.meteor/local/build/programs/server/boot.js:230:17)
> W20170601-19:53:36.479(-3)? (STDERR)     at meteorInstall.node_modules.meteor.ostrio:files.files.coffee.js (packages/ostrio_files/files.coffee:12:18)
> W20170601-19:53:36.479(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
> W20170601-19:53:36.480(-3)? (STDERR)     at require (packages/modules-runtime.js:228:16)
> W20170601-19:53:36.480(-3)? (STDERR)     at /home/projects/project/meteor-server-app/.meteor/local/build/programs/server/packages/ostrio_files.js:4394:15
> W20170601-19:53:36.480(-3)? (STDERR)     at /home/projects/project/meteor-server-app/.meteor/local/build/programs/server/packages/ostrio_files.js:4405:3
> W20170601-19:53:36.480(-3)? (STDERR)     at /home/projects/project/meteor-server-app/.meteor/local/build/programs/server/boot.js:338:34
> W20170601-19:53:36.481(-3)? (STDERR)     at Array.forEach (native)
> W20170601-19:53:36.481(-3)? (STDERR)     at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.5.0.1hpmnt8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
> W20170601-19:53:36.481(-3)? (STDERR)     at /home/projects/project/meteor-server-app/.meteor/local/build/programs/server/boot.js:158:5

**Comment by dr-dimitru** [comment]
See: #420

**Comment by sotarules** [comment]
I'm also commenting over on #420 but I wanted to follow here too, because this is a direct hit on my symptoms (Meteor 1.5).

**Comment by mgscreativa** [comment]
Got it working with meteor npm install --save file-type fs-extra

ostrio:files v1.7.16
Meteor v1.5

**Comment by sotarules** [comment]
@mgscreativa I was able to get my development environment working by using **meteor npm install** on **file-type** and **fs-extra**; however, when I build the project and then install the bundle on a production server, when I start the production server, I get the same error on the server.

Can you confirm or refute this on your system?

If I'm right about this **meteor npm install** approach should be seen as a _circumvention_ as opposed to _solution_.

**Comment by mgscreativa** [comment]
Sorri, I ran **npm install --save file-type fs-extra** Just deployed to heroku and it works...

**Comment by sotarules** [comment]
@mgscreativa I wonder what the difference is, maybe @dr-dimitru know.

I'm deploying it on my own VMWare Ubuntu 16.04.  When I install the bundle, that seems to work, but when I start the server, I see the dreaded error messages in the **.forever** log files.

**Comment by mgscreativa** [comment]
@sotarules Sorry, I really don't know why that happens to you... @dr-dimitru is the master here!

**Comment by dr-dimitru** [comment]
Should be fixed in [v1.7.17](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.17) please update, let me know how it work for you

**Comment by mgscreativa** [comment]
Updated to v1.7.17 and removed file-type from package.json and works ok

**Comment by dr-dimitru** [comment]
@mgscreativa great news, thank you for update and report in the first place.
Feel free to reopen it in case if the issue will pop back on your end.
