### ISSUE TITLE
Slow performance with the AWS integration

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/Meteor-Files#440]
Hello,

I am having a performance issue when playing (small) videos with Meteor files and the new AWS example (using aws-sdk). 

Before I was using the Knox example and I had no issues. Now, when I load the video files either with video js or directly by putting the link of my website in the browser (for example something like /cdn/storage/Images/7D4ivLXQpKMxjBwuj/original/7D4ivLXQpKMxjBwuj.mp4), it plays very slowly and it's just unusable. When I type the link to S3 directly, I have no issues. 

I thought it might be related to the streaming feature that was included recently, but I tried playing with the chunk size without success. Can somebody help? Thanks!

**Comment by marcoschwartz** [comment]
I can confirm that reverting to the 'old' AWS example with Knox solves the issues. I have no problem with small files like images, but videos are just unplayable with the new example, either with video js or with the standard HTML5 player. Can anyone help? Thanks!

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

The weird thing I'm having opposite situation was slow with `Knox` and now it's much better.
I recommend to start with official [aws:s3 SDK docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html), check what features might be used to solve this.

I'll be back on this later next week. Hope you may figure out something in meanwhile.

**Comment by marcoschwartz** [comment]
Thanks for the fast answer :) For now I did a quick fix indeed (for videos only), I am just using Request (like on the Knox example) to directly pipe the file from the URL of the file on S3.

**Comment by dr-dimitru** [comment]
> I am just using Request (like on the Knox example) to directly pipe the file from the URL of the file on S3.

This means you're using CloudFront, right?
CloudFront acts differently and really may cause better performance, and it will take care of "streaming", as it's kind of FileServer/CDN.

In the updated AWS:S3 tutorial we used direct access to the files via SDK, so we need to deal with "streaming", chunks and etc. by ourself, but it's simpler and cheaper technique, as using CloudFront you're paying for its usage separately.

I'm highly recommend to use `.serve()` method even using CoudFront. As piping stream directly to CloudFront may lead to security issues (you may quickly compare response headers w/o CloudFront to get what I'm talking about). Just pass `request(/*..*/)` to the `.serve()` method, like:
```js
this.serve(http, fileRef, fileRef.versions[version], version, request({
  url: path,
  headers: _.pick(http.request.headers, 'range', 'cache-control', 'connection')
}));
```

I guess we should update our tutorial or provide alternative tutorial with CloudFront usage, as it will definitely lead to better performance.

**Comment by marcoschwartz** [comment]
I think not, but not sure actually. I directly pass the URL of the file on S3 (and not with the cloudfront URL), for example: https://s3-us-west-2.amazonaws.com/arest/logo.png . So I am not using cloudfront right?

Alright, I'll adapt my apps to use the .serve() method :)

**Comment by dr-dimitru** [comment]
> So I am not using cloudfront right?

Not sure, need to see what do you do to get this direct link.

**Comment by marcoschwartz** [comment]
For sure! Here is my 'hacked' interceptDownload function:

`interceptDownload(http, fileRef, version) {

        let path;

        if (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) {
            path = fileRef.versions[version].meta.pipePath;
        }

        if (path) {

            const opts = {
                Bucket: s3Conf.bucket,
                Key: path
            };

            // Build S3 path
            var s3_path = 'https://s3-' + s3Conf.region + '.amazonaws.com/' + s3Conf.bucket + '/' + path;
            console.log(s3_path);

            Request({
                url: s3_path,
                headers: _.pick(http.request.headers, 'range', 'accept-language', 'accept', 'cache-control', 'pragma', 'connection', 'upgrade-insecure-requests', 'user-agent')
            }).pipe(http.response);

            return true;
        }

        return false;
    }
`

**Comment by dr-dimitru** [comment]
1. Not if those header make any sense: `'accept-language', 'accept', 'pragma', 'upgrade-insecure-requests', 'user-agent'`, just takes over traffic
 2. This `'https://s3-' + s3Conf.region + '.amazonaws.com/' + s3Conf.bucket + '/' + path` is great! Haven't seen this before (*I'm not really fan of AWS though*), do you have a reference where you found it?
 3. What is access policy to the files, why even I'm can download your files?
 4. Don't want to be annoying, but please read and follow [GHFMD](https://help.github.com/articles/about-writing-and-formatting-on-github/)

**Comment by marcoschwartz** [comment]
1. Indeed, I'll remove them
2. Not really a reference, just went to my S3 interface, saw how links looked like & copied that into the app
3. Indeed I guess it's publicly accessible, I don't really care as it's all pictures/videos from my blog(s) anyway, but it will be better if it was secure indeed
4. Thanks, I definitely need to learn more about that !

**Comment by dr-dimitru** [comment]
I bet we setup access policy during old integration example. I guess it were required by CloudFront.
All is clear, just curious how to update access policy to block everything except your app IPs, or I remember there was temp session key generator.

**Comment by marcoschwartz** [comment]
I tried to modify my example as you said using the serve() function, but now I have this error on the server when a video file is served:

bundle/bundle/programs/server/packages/ostrio_files.js:3430
[104.236.37.13]            http.request.abort();                                                                                      //
[104.236.37.13]                         ^
[104.236.37.13]
[104.236.37.13]TypeError: http.request.abort is not a function
[104.236.37.13]    at Request.<anonymous> (/bundle/bundle/programs/server/packages/ostrio_files.js:3430:26)
[104.236.37.13]    at emitNone (events.js:67:13)
[104.236.37.13]    at Request.emit (events.js:166:7)
[104.236.37.13]    at Request.abort (/bundle/bundle/programs/server/npm/node_modules/request/request.js:1186:8)
[104.236.37.13]    at ServerResponse.<anonymous> (/bundle/bundle/programs/server/packages/ostrio_files.js:3407:20)
[104.236.37.13]    at emitNone (events.js:72:20)
[104.236.37.13]    at ServerResponse.emit (events.js:166:7)
[104.236.37.13]    at Socket.onServerResponseClose (_http_server.js:132:44)
[104.236.37.13]    at emitOne (events.js:82:20)
[104.236.37.13]    at Socket.emit (events.js:169:7)
[104.236.37.13]

**Comment by dr-dimitru** [comment]
1. Make sure [arguments in a right place](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L2356)
 2. See [example here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/lib/files.collection.js#L176) just replace `dataStream` with `request`

**Comment by dr-dimitru** [comment]
@marcoschwartz is this one solved?

**Comment by marcoschwartz** [comment]
I'd say no, even if the workaround works there is still an issue with the S3 example when playing videos (> 10 MB). Would be great if somebody else could also report on the issue (or if it's just me).

**Comment by dr-dimitru** [comment]
1. Does video plays smoothly on direct access?
 2. Have you tried to change [AWS S3 storage class](https://aws.amazon.com/s3/storage-classes/)?
 3. If you play video which is uploaded to server (*not AWS*) does it play smoothly? If not maybe your server is bottleneck?

There is few possible variations of bottleneck:
 0. Last mile
 1. Your server
 2. Connection between your server and AWS
 3. AWS S3 storage

And each should be checked. As I've said before I'm running Meteor-Files demo on the same code and have no issues. One thing I did - make sure AWS:S3 and Heroku is in the same region.

My stack:
 1. Nginx Proxy Gateway
 2. Heroku Hobby
 3. Free Sandbox MongoLab
 4. AWS:S3 standard storage class

**Comment by dr-dimitru** [comment]
@marcoschwartz this looks useful: https://medium.com/@stockholmux/node-js-streams-proxies-and-amazon-s3-50b4fabdedbd

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
