### ISSUE TITLE
Integration with linux VPS server

### ISSUE THREAD

**Issue by tanmoy12** [VeliovGroup/Meteor-Files#442]
I'm deploying my Meteor app in a linux VPS server, but images uploaded are not displaying in the app. I'm guessing this is a storage location problem . Here's my images collection declaration . 

    ImagesCol = new FilesCollection({
        collectionName: 'Images',
        storagePath: '../data',

        allowClientCode: false, // Disallow remove files from Client
        onBeforeUpload: function (file) {
             // Allow upload files under 10MB, and only in png/jpg/jpeg formats
             if (file.size <= 10485760) {
                 return true;
             } else {
                 return 'Please upload image, with size equal or less than 10MB';
             }
        }
    });

**Comment by dr-dimitru** [comment]
1. What is the error `404`?
 2. Any server error?
 3. What debug mode says?

**Comment by tanmoy12** [comment]
there are no errors. on my localhost, when i upload images, the images are displayed fine. I ran it on a vps server, the app don't seem to find the images after upload. can you tell me in which directory the images get uploaded. i'm using storage path '../data'

**Comment by dr-dimitru** [comment]
Well it's uploaded to `../data` (relative to process).

> there are no errors.

Then where is the issue? If image/files is not shown, check the "Network" tab in your browser to see what is happening.

And what debug mode says?

**Comment by tanmoy12** [comment]
I'm running the app just fine in my machine. 
I deployed the app in a linux vps server, by cloning from my github repository, and uploaded images are not getting found. 
I'm new to this, So i'm not sure about the debug mode. 
The network tab shows the id of the image in red. 

If you take the trouble, check out the site link:

http://204.9.187.54:3000/File

Thank you.

**Comment by dr-dimitru** [comment]
1. See `config.debug` [here](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
 2. Check server logs, there is must be something
 3. If you want to make sure files is in a right place change storagePath to `/data`, and make sure directory exists and writable with `mkdir /data` and `chmod 777 /data`
 4. But what really you should do is read FAQ, readme, issues and wiki of this repository, where most of the things is already covered.

**Comment by dr-dimitru** [comment]
Hi @tanmoy12 any news on your end?

**Comment by tanmoy12** [comment]
I changed the storagePath as you said to "/data". 
After uploading images i can see that the images got saved in "/data" folder my VPS server. 
but they are not showing up in my site.
I must add the images get loaded from localhost, from my machine, 
But does not work from remote VPS server.

**Comment by dr-dimitru** [comment]
Have you got a chance to enable debug mode?
Btw this looks related: https://github.com/VeliovGroup/Meteor-Files/issues/447#issuecomment-307558769

**Comment by tanmoy12** [comment]
I don't know how to enable debug mode in a vps server, I'm working on the server through a ssh connection from terminal.

**Comment by tanmoy12** [comment]
The #447 issue looks exactly like mine.

**Comment by tanmoy12** [comment]
The issue is same, I can see the files got uploaded, but the file's are not found with 404 error. I did not understand the solution though

**Comment by dr-dimitru** [comment]
1. Are you using PM2 too as in #447 ?
 2. See `debug` flag in a [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by tanmoy12** [comment]
No i'm not using PM2. I'll try debug in constructor now.

**Comment by dr-dimitru** [comment]
What are you using for deployment?

**Comment by tanmoy12** [comment]
Not anything in particular,
I cloned from github;  ran meteor, thats it. 
Here's a screenshot after debug flag.

![screenshot from 2017-06-10 18-32-47](https://user-images.githubusercontent.com/10713353/27002784-8a618470-4e0b-11e7-8938-31f572db5349.png)

**Comment by tanmoy12** [comment]
[FilesCollection] [findOne({"_id":"EyHnivLzggq5kdedA"}, undefined)]
ostrio_files.js:760 [FilesCollection] [FileCursor] [link(undefined)]
ostrio_files.js:3533 [FilesCollection] [link(EyHnivLzggq5kdedA, original)]


this is debug output.

**Comment by dr-dimitru** [comment]
Looks like request isn't even reaching Meteor-Files package.
Move `ostrio:files` above other packages that may listen for incoming requests in `.meteor/packages` file. For example it's known interference issue with `flow-router`

**Comment by tanmoy12** [comment]
I did move ostro:files above all other installed packages, it didn't solve the problem.

**Comment by dr-dimitru** [comment]
Okay, then: 
 1. How URL to the file is generated? Are you sure it's properly generated? Is `ROOT_URL` set?
 2. Could you take a screenshot of Network tab where 404 error is shown including response headers

**Comment by tanmoy12** [comment]
This is a code snippet of how image links are made :
     const cursor = ImagesCol.findOne({_id: Meteor.user().profile.ProPic});
            if (cursor) {
                link = cursor.link();
            }

I don't know anything about **ROOT_URL**


![screenshot from 2017-06-11 02-04-48](https://user-images.githubusercontent.com/10713353/27005934-6a1cb57e-4e4a-11e7-8076-8ad1547a76d2.png)

**Comment by dr-dimitru** [comment]
> I don't know anything about `ROOT_URL`

If you haven't set `ROOT_URL` this might be a reason for this behavior.
Read docs here: https://docs.meteor.com/environment-variables.html#ROOT-URL

**Comment by tanmoy12** [comment]
Are you suggesting I use any tool to deploy the app? Like mupx or docker? 
I've read the docs, but i could find a way to access ROOT_URL without using a tool to deploy. 

Thank you

**Comment by dr-dimitru** [comment]
@tanmoy12 how do you start your meteor/node.js app?

**Comment by tanmoy12** [comment]
In my vps server through a SSH connection, 
I pull my repository, 
I use "nohup meteor &" to run the app.

**Comment by dr-dimitru** [comment]
Before `nohup` you can pass every env.var:
```shell
ROOT_URL="http://example.com" MONGO_URL="mongodb://example.com" nohup meteor &
```

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
