### ISSUE TITLE
Pictures don't show

### ISSUE THREAD

**Issue by mozibrand** [VeliovGroup/Meteor-Files#447]
test website: http://mbemd.mozibrand.com/upload
in localhost is ok, The deployment to the server image is not show,is error, what's the problem

code
1: lib/collections/images.js
![1](https://user-images.githubusercontent.com/24447931/27002001-5bfeb0b4-4e09-11e7-8010-6944d204f01a.jpg)

2: show images list
client/views/templates/module/upFile.html
![2](https://user-images.githubusercontent.com/24447931/27002011-7bf2c5a4-4e09-11e7-8cf2-382e22a8a764.jpg)

3: image item
client/views/templates/module/imageItem.html
![3](https://user-images.githubusercontent.com/24447931/27002049-18bf3700-4e0a-11e7-9e35-09daa893c3da.jpg)

4: images item js
client/views/templates/module/imageItem.js
![4](https://user-images.githubusercontent.com/24447931/27002053-2d4d7b1e-4e0a-11e7-979b-e3a3f1729223.jpg)

5: error list
![5](https://user-images.githubusercontent.com/24447931/27002058-41a5ce86-4e0a-11e7-95de-790121750104.jpg)

6: website: http://mbemd.mozibrand.com/upload

Thank you very much

**Comment by mozibrand** [comment]
s

**Comment by dr-dimitru** [comment]
Change `storagePath` to `/data/`.
And make sure `/data` directory exists and writable:
```shell
mkdir /data
chmod 777 /data
```

**Comment by mozibrand** [comment]
I have a try，now

**Comment by mozibrand** [comment]
It doesn't show up, upload no problem, I can see the uploaded picture file

**Comment by dr-dimitru** [comment]
I'm strongly recommend to enable debug mode with passing `{debug: true}` to *FilesCollection Constructor*.

**Comment by mozibrand** [comment]
sorry, I've already solved it，Is my problem，Configure the pm2 url error，It's normal now , very very thank you  http://mbemd.mozibrand.com

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by mozibrand** [comment]
ok，Very good packages，Thumb up immediately
