### ISSUE TITLE
Just installed one package, a new meteor project, really doesn't support IE?

### ISSUE THREAD

**Issue by mozibrand** [VeliovGroup/Meteor-Files#448]
Just installed one package, a new meteor project, really doesn't support IE?

![1211](https://user-images.githubusercontent.com/24447931/27008140-ac3a14fe-4e9c-11e7-8ccc-845c3ca29fe6.jpg)

Are you there, very urgent, and now the test is whether this package doesn't support IE, because the ES6 arrow function doesn't support IE

**Comment by dr-dimitru** [comment]
Closed in favor #445
