### ISSUE TITLE
Insert file on server

### ISSUE THREAD

**Issue by stefanve** [VeliovGroup/Meteor-Files#449]
I'm tired and probably a bit thick - but I do not see how I should go about to simply add a file that the server have picked up somewhere. Process is that I have a PDF-form-fill server on one machine and my Meteor access that with form data and get  a link to PDF file in return. 
If link, I do a GET and can save it on my local file system. All is well, apart from that I want it into my filesCollection with the other files. 
Can that be done? Is a few hours of sleep all I need?

**Comment by dr-dimitru** [comment]
Hello @stefanve ,

Take a look on:
 - [`. addFile()`](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile) - Add local file to FilesCollection from FS
 - [`.write()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) - Write a `Buffer` to FS and add record to Files collection

**Comment by stefanve** [comment]
Perfect, thanks!

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by badis** [comment]
I couldn't use write function. 
I am getting this error: `Error during upload: TypeError: Images.write is not a function.`
https://github.com/VeliovGroup/Meteor-Files/issues/520
