### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iSuslov** [VeliovGroup/Meteor-Files#45]
Little feature request. I think it would be helpful to have the ability to prevent auto upload. So we can render custom UI controllers for the upload and then manually call `continue()`

**Comment by dr-dimitru** [comment]
You can trigger upload by `click`ing submit button in a form. And on `change` event get blob of file and display it in template passing to `src` the base64 encoded string.

**Comment by dr-dimitru** [comment]
I've meant - upload behavior fully controlled by you

**Comment by dr-dimitru** [comment]
@iSuslov it is still a topic to discuss? Otherwise I prefer to close this issue...

**Comment by iSuslov** [comment]
It's OK.
