### ISSUE TITLE
OnBeforeUpload hook check image dimension

### ISSUE THREAD

**Issue by MarcoTribuz** [VeliovGroup/Meteor-Files#453]
Hi everyone, i'm having an issue. 
How can check the image size like width and height in OnBeforeUpload Hook? 
thanks in advance.
Marco

**Comment by dr-dimitru** [comment]
Hello @MarcoTribuz ,

Do you want to measure image size on Client or Server?

**Comment by MarcoTribuz** [comment]
Hello @dr-dimitru, and thanks for your fast response. i try on client, is it possible?

**Comment by dr-dimitru** [comment]
Yes, but before upload you have to transform it to Canvas, measure dimensions, and then upload as base64. 

I belive @paulincai can tell you more if he have a time.

**Comment by dr-dimitru** [comment]
[Here is good example](https://stackoverflow.com/a/5174151/1320932) if file meets you requirements - you pass it as base64 string from `reader.readAsDataURL(file);` to [`FilesCollection#insert`](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#upload-base64-string)

**Comment by dr-dimitru** [comment]
Hello @MarcoTribuz ,

Is this issue solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
