### ISSUE TITLE
How to use each() for find()?

### ISSUE THREAD

**Issue by alvara** [VeliovGroup/Meteor-Files#456]
I am trying to display all the files within my files collection but having trouble using the each() method from find() to access the link, from the documentation:

> each() - {[FileCursor]} - Returns an Array of FileCursor made for each document on current Cursor. Useful when using in {{#each FilesCursor#each}}...{{/each}} block template helper

This is my current code:

```javascript
attachment() {
        return colPriceQuotesAttachments.find();
    }
```

```html
{{#each attachment.each}}
        {{this.link}}<br>
{{/each}}
```

Unfortunately nothing displays..
Any advice on what I am doing wrong?

**Comment by alvara** [comment]
solved it! Just had to upgrade my ostrio:files package from 1.5.6 to 1.8.0. Everything is working now.

**Comment by dr-dimitru** [comment]
Hello @alvara ,

I'm glad this was an easy fix :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
