### ISSUE TITLE
How to sort records by some kind of timestamp?

### ISSUE THREAD

**Issue by rlhk** [VeliovGroup/Meteor-Files#459]
I'm looking for a way to sort records by created / modified time. 
However I don't see any time related fields in the created mongoDB records. 

(I'm using the latest version 1.8)
Any workaround? Thanks!

If it's a missing feature, I'm happy to submit a PR by adding a createdAt field.

**Comment by dr-dimitru** [comment]
Hello @rlhk ,

Pass timestamp into `meta` object, referred as `settings.meta` in the [docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))

And see [this example](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/client/upload/upload-form.js#L80)

Let me know if it is helped.

**Comment by rlhk** [comment]
Hi @dr-dimitru , that works like a champ. First time to learn you could sort by nested attributes. Great flexibility 👍

**Comment by dr-dimitru** [comment]
@rlhk glad it's solved for you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by FEA5T** [comment]
@rlhk 

```
onInitiateUpload(file) {
	file.createdOn = new Date(); // semantic
	file.createdAt = new Date().getTime(); // value based
},
```

Above is the proper way to do it.  Allowing the client to set the time means anyone in the debugger can create a fake time (spoof the time).  Meta should be used for other information that is not security/time sensitive.
