### ISSUE TITLE
Images disappear after server restart

### ISSUE THREAD

**Issue by achirkof** [VeliovGroup/Meteor-Files#46]
I am saving all my images in directory: `storagePath: 'assets/uploads/avatars/'` and after restart server directory with files disappear. All data still exist in collection but files are gone. Maybe I have to store images in another place?

**Comment by dr-dimitru** [comment]
As meteor completely rebuild `server` directory after you've made changes on server-side all uploaded files will be removed. During development you may change `storagePath` option to something relative to your FS (`/tmp/UploadedFiles`) or relative to your user (`~/tmp/..`)

**Comment by achirkof** [comment]
Yes, it helps. Thanks.
