### ISSUE TITLE
Meteor 1.5 build does not contain Assets directory (images missing) 

### ISSUE THREAD

**Issue by sidkdbl07** [VeliovGroup/Meteor-Files#460]
I've posted to forums.meteor here:
[Meteor forums](https://forums.meteor.com/t/ostrio-files-files-not-included-in-build/37857/2)

After building the meteor app and deploying to the web server, my images are nowhere to be found on the server. When I try to find one of the images that should be there I get no results

> find ./ -name Electrical-1.png -print

Do I need to do something in particular to build?

**Comment by sidkdbl07** [comment]
[cmj.tar.gz](https://github.com/VeliovGroup/Meteor-Files/files/1146953/cmj.tar.gz)

Here is the meteor project. It works locally, but fails when I build it for deployment

**Comment by sidkdbl07** [comment]
Well, I found a work-around (unless this is the intended functionality of this library).

I setup the storagePath as a variable in Meteor.settings
- for local, it's set to ./plans
- for production, it's set to /home/sid/plans

After copying the build to the server, I then copied the plans directory to /home/sid/ manually.

Seems to work.

**Comment by dr-dimitru** [comment]
Hello @sidkdbl07 ,

Sorry for delay, yes this is expected behavior.
You can create `/home/sid/plans` directory on local (dev) machine, and then hard-code it to `storagePath`

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
