### ISSUE TITLE
Get path or fileReadStream from Meteor Files object

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/Meteor-Files#461]
Hello,

It's probably a very simple question, but I just spent hours trying to find a solution ... for a project I am making (with https://github.com/huttarichard/instagram-private-api) I need to get either a path or a fileReadStream object from some image that I have stored with Meteor Files (using the S3 example).

When I insert fileRef.path as the path, it tells me it can't find the file ... however I guess I need to get the files from S3 but I don't know how to do that. Which is the right way to pass the path or a filestream for an image stored with Meteor Files? Thanks!

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

Yes, it's easy, just grab a code from [`interceptDownload` hook in AWS:S3 example](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration).

You should end up with something like:
```js
import stream from 'stream';
import S3 from 'aws-sdk/clients/s3'; // http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

const s3 = new S3({
  secretAccessKey: _SECRET_,
  accessKeyId: _KEY_,
  region: _REGION_,
  httpOptions: {
    timeout: 6000,
    agent: false
  }
});

let path;
const file = FilesCollection#findOne(_id);

if (file && file.versions && file.versions['original'] && file.versions['original'].meta && file.versions['original'].meta.pipePath) {
  path = file.versions['original'].meta.pipePath;
}

if (path) {
  const opts = {
    Bucket: _BUCKET_NAME_,
    Key: path
  };

  s3.getObject(opts, function (error) {
    if (error) {
      console.error(error);
    } else {
      const dataStream = new stream.PassThrough();
      dataStream.end(this.data.Body);
      // ---> dataStream is the stream you can pass to Instagram
    }
  });
```

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

Have you solved it?

**Comment by marcoschwartz** [comment]
Yeah that works now, thanks for the help!
