### ISSUE TITLE
Custom ddp connenction: insert ok, find.fetch always return empty array

### ISSUE THREAD

**Issue by Zentelechia** [VeliovGroup/Meteor-Files#467]
I'm using 1.8.1
Meteor 1.51

Problem on client (Android, Cordova)
Default mobile server (A)  for cordova app uses only for hot code push of new versions of App

I have another server (B), which stores files in FileCollection

On mobile App, after setting custom dpp connection in FileCollection Constructor (to server B) - I got this issue:
I can upload files to server (B) via this object ( so, insert method working well)
But I always recieve empty cursor if I try to find some files (On server publishing working well - as I recieve files in my simple Client (not Cordova, and uses default Meteor connection) 

I've tryed many ways but still not solved my issue

Where to dig?

**Comment by dr-dimitru** [comment]
Hello @Zentelechia ,

Take a look on `config.ddp` at [*FilesCollection* Constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor).

My guess you should use different connection for Cordova app and Website.
Let me know if it helped.

**Comment by Zentelechia** [comment]
Hello @dr-dimitru,

Thanks for the fast reply!

I use different connections:
**It's for Cordova:**
Images = new FilesCollection({
			collectionName: 'Images',
			ddp: server_connection.get()
		});
server_connection - is a reactive var, which stores DDP.connect answer


**It's for Website**
Images = new FilesCollection({
	collectionName: 'Images'
});

**Comment by dr-dimitru** [comment]
Oh, okay...
I think you also should pass `collection` instead of `collectionName`.

And `collection` should be created on custom DDP connection, see [docs](http://docs.meteor.com/api/collections.html#Mongo-Collection):
```js
Images = new FilesCollection({
  collection: new Mongo.Collection('Images', {
    connection: server_connection.get()
  }),
  ddp: server_connection.get()
});
```

**Comment by dr-dimitru** [comment]
And one more thing.... You have mentioned `publish` but not `subscribe`, are you subscribing for data?

**Comment by Zentelechia** [comment]
It's Work!

```
Images = new FilesCollection({
  collection: new Mongo.Collection('Images', {
    connection: server_connection.get()
  }),
  ddp: server_connection.get()
});

```

I've tryed to pass collection object with connection parameter, but not passed ddp to FilesCollection - it not worked


Спасибо!)

**Comment by dr-dimitru** [comment]
@Zentelechia hoooray! I'm glad it's solved so quickly.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
