### ISSUE TITLE
fileType errors when detecting webm/matroska files

### ISSUE THREAD

**Issue by s-ol** [VeliovGroup/Meteor-Files#472]
This is a very weird glitch and I have been digging for hours and am not quite sure what the reason is. Basically when a webm is uploaded and the `file-type` MIME detection is used, it throws an error that is captured by [server.coffee:699](https://github.com/VeliovGroup/Meteor-Files/blob/master/server.coffee#L699).

The error thrown is `TypeError: sliced.findIndex is not  a function`, and it comes from [index:217](https://github.com/sindresorhus/file-type/blob/master/index.js#L217) in `file-type`.

A bit more digging reveals that `buf.subarray()` in the line above (216), for some reason, does **NOT** return a valid buffer object, but instead seems to return a normal object.

Here are my debugging code additions:
```diff
    ###
    @locus Anywhere
    @memberOf FilesCollection
    @name _getMimeType
    @param {Object} fileData - File Object
    @summary Returns file's mime-type
    @returns {String}
    ###
    _getMimeType: (fileData) ->
      check fileData, Object
      mime = fileData.type if fileData?.type
      if fileData.path and (not mime or not _.isString mime)
        try
          buf = new Buffer 262
          fd  = fs.openSync fileData.path, 'r'
          br  = fs.readSync fd, buf, 0, 262, 0
          fs.close fd, NOOP
          buf = buf.slice 0, br if br < 262
+         test = buf.subarray(4, 4 + 4096);
+         console.log 'sliced', (typeof test), test, !!test.findIndex
+         test = new Uint8Array()
+         console.log 'u8', (typeof test), test, !!test.findIndex
+         console.log 'buf', (typeof buf), buf, !!buf.findIndex
          {mime, ext} = fileType buf
       catch error
+        console.error error
     if not mime or not _.isString mime
       mime = 'application/octet-stream'
     return mime
```

The 'sliced' log value (`test = buf.subarray(4, 4 + 4096)`) mimics `file-type`'s internal code and as you can see, the result is a plain object without `.findIndex`, which is the reason for the non-detection by `file-type` (file is classified as `application/octet-stream`):

```
sliced object { '0': 159, ...,  '257': 76 } false
u8 object Uint8Array {} true
buf object <Buffer 1a 45 df a3 ... > true
(STDERR) [TypeError: sliced.findIndex is not a function]
```

Also the `Buffer` and `Uint8Array` instances themselves work just fine, only the `new Buffer().subarray()` return value is weird.

I suspected this was some weird side-effect of the `meteor 1.5.1` update to `node 4.8.4`, but testing in node reveals that Buffer is working fine:
```
docker run -ti --rm node:4.8.4
> new Buffer(262)
<Buffer 40 fb 77 02 00 00 00 00 40 fb 77 02 00 00 00 00 40 fb 77 02 00 00 00 00 0a 00 00 00 00 00 00 00 a8 52 78 02 00 00 00 00 05 00 00 00 01 00 00 00 00 00 ... >
> new Buffer(262).subarray(4, 4100).findIndex
[Function: findIndex]
```

My best guess is that this is a side effect from some broken polyfill trying to patch over the Uint8Array/Buffer implementation in pure JS (and failing hard) but I haven't been able to find out much. I attached a demo file that triggers the correct code path in `file-type`, just make sure to `delete fileRef.type` in `onAfterUpload` to trigger `file-type` detection when testing.

[webm_test.zip](https://github.com/VeliovGroup/Meteor-Files/files/1205386/webm_test.zip)

**Comment by dr-dimitru** [comment]
Hello @s-ol ,

```js
new Buffer(262);
```
Is fine for node v4.8.4, *Buffer* constructor is deprecated in later node versions.

Have you tried to report the bug to [`file-type` repository](https://github.com/sindresorhus/file-type/issues)?
Hope @sindresorhus can tell us more about what is going on.

**Comment by dr-dimitru** [comment]
Hello @s-ol ,

Did you get a chance to raise this issue on the [`file-type` repository](https://github.com/sindresorhus/file-type/issues)?

**Comment by s-ol** [comment]
sorry @dr-dimitru, I haven't, in part because I suspect this is not their fault and a glitch connected to meteor.

**Comment by dr-dimitru** [comment]
> I suspect this is not their fault and a glitch connected to meteor

Chance is small, as `_getMimeType` called on *Server* only, so there is no Meteor's tweaks around `Buffer` omplementation

**Comment by dr-dimitru** [comment]
@s-ol any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
