### ISSUE TITLE
How to update collection with modified path after uploaded file was moved

### ISSUE THREAD

**Issue by Avijobo** [VeliovGroup/Meteor-Files#473]
Hi,

Depending on the program flow, I may need to move each uploaded file to a different individual folder tree afterwards on the server. (I cannot do this at upload time with storagePath(), since at that time the folder tree is still unknown.) What I do now, is after I moved the file I update the file document fileRef.path with the new path. However this does not seem to be sufficient, because when I then afterwards e.g. remove the document from the collection, the moved file is not automatically deleted anymore. So what else do I need to take care of? 

Thanks in advance

**Comment by dr-dimitru** [comment]
Hello @Avijobo ,

There is three properties used to physically locate the file:
 1. `fileRef.path`
 2. `fileRef._storagePath`
 3. `fileRef.versions.original.path`

See [Schema docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)

Let me know if it helped.

**Comment by Avijobo** [comment]
That works! Thanks a million for your excellent support!

**Comment by dr-dimitru** [comment]
@Avijobo great! I'm glad we have solved it.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
