### ISSUE TITLE
404 on /cdn/storage when using in production app

### ISSUE THREAD

**Issue by jankapunkt** [VeliovGroup/Meteor-Files#475]
I have the problem, that on my local dev everything runs fine, but on my server, there is always a 404 after upload regarding the path /cdn/stotage... and I also can't find the image in the given folder of the storage path.

Is this maybe a permission issue or something? Am I missing to create a /cdn/storage route in my router or as a folder on my server? (I did not really found something on that in the Wiki or the other issues). I thought that /cdn/storage is just a virtual path to retrieve the file stream?

     - Version of `Meteor-Files` you're experiencing this issue

Latest

     - Version of `Meteor` you're experiencing this issue

1.5.1

     - Is it *Client* or *Server* issue?

Seems to be server related. Server is Ubuntu 16.04.2 LTS

     - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

Error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.mywebsite.com/cdn/storage/imagefiles/mgabEN5ZDKfmEb4vL/original/mgabEN5ZDKfmEb4vL.png

```
Constructor: default constructor from the examples

Console output on upload:

```
images on before upload { size: 436029,
  type: 'image/png',
  name: '1045px-Konzept-karte_der_Freien_Software.svg.png',
  meta: {},
  ext: 'png',
  extension: 'png',
  extensionWithDot: '.png',
  mime: 'image/png',
  'mime-type': 'image/png',
  _id: 'mgabEN5ZDKfmEb4vL',
  userId: 'CtA8i4rKmJ3ugAQxD',
  path: 'assets/app/uploads/imagefiles/mgabEN5ZDKfmEb4vL.png',
  versions: 
   { original: 
      { path: 'assets/app/uploads/imagefiles/mgabEN5ZDKfmEb4vL.png',
        size: 436029,
        type: 'image/png',
        extension: 'png' } },
  _downloadRoute: '/cdn/storage',
  _collectionName: 'imagefiles',
  isVideo: false,
  isAudio: false,
  isImage: true,
  isText: false,
  isJSON: false,
  isPDF: false,
  _storagePath: 'assets/app/uploads/imagefiles' }

```

**Comment by dr-dimitru** [comment]
Hello @jankapunkt ,

 1. I'm highly recommend to debug prod server with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor).
 2. Set `storagePath` relative to the "root" of the file system (*starting with `/`*), from the [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) docs:

> The Meteor-Files package operates on the host filesystem, unlike Meteor Assets. When a relative path is specified for config.storagePath (path starts with ./ or no slash) files will be located relative to the assets folder.
> 
> When an absolute path is used (path starts with /) files will be located starting at the root of the filesystem.

**Comment by dr-dimitru** [comment]
Hi @jankapunkt is this one solved?

**Comment by jankapunkt** [comment]
sry for no response I got stuck on another issue with proxiing corretly to my websocket. When this is resolved I will try again, because before that I dont know if there is a proxy or access problem with the server. You can keep this on hold or close and I will reopen, once I resolved my proxy issue and this problem still persists.

**Comment by dr-dimitru** [comment]
> I got stuck on another issue with proxiing corretly to my websocket.

Sounds familiar, we can help you with this, during last two years we have run (hosted / deployed) more than 70 Meteor's projects. What your current setup, and what is the issue. *Feel free to move this discussion to forums.meteor.com .*

> You can keep this on hold

Sure, just want to make sure ticket is not stale.

**Comment by jankapunkt** [comment]
Thanks a lot! My forum question is here: https://forums.meteor.com/t/connecting-to-websocket-returns-400-prod-proxy/39029

**Comment by jankapunkt** [comment]
Okay I solved the issue with the nginx and the web socket. The problem still persists. Unfortunately I can't get a console output yet. But I managed to get the /cdn/storage path to be accessible (that was an nginx/apache issue) and also checked the mongodb after a new test upload:

```javascript
db. unitfiles.find().pretty()

{
	"_id" : "Pd8wdrsW3GoBJYS25",
	"size" : 985390,
	"type" : "image/jpeg",
	"name" : "austin-schmid-28822.jpg",
	"meta" : {
		
	},
	"ext" : "jpg",
	"extension" : "jpg",
	"extensionWithDot" : ".jpg",
	"mime" : "image/jpeg",
	"mime-type" : "image/jpeg",
	"userId" : "CtA8i4rKmJ3ugAQxD",
	"path" : "assets/app/uploads/unitfiles/Pd8wdrsW3GoBJYS25.jpg",
	"versions" : {
		"original" : {
			"path" : "assets/app/uploads/unitfiles/Pd8wdrsW3GoBJYS25.jpg",
			"size" : 985390,
			"type" : "image/jpeg",
			"extension" : "jpg"
		}
	},
	"_downloadRoute" : "/cdn/storage",
	"_collectionName" : "unitfiles",
	"isVideo" : false,
	"isAudio" : false,
	"isImage" : true,
	"isText" : false,
	"isJSON" : false,
	"isPDF" : false,
	"_storagePath" : "assets/app/uploads/unitfiles",
	"public" : false
}
```

It seems that the upload has been completed, but the image is not previewed or accessible. It just got stuck on 100% (using the files autoform package):

![bildschirmfoto 2017-09-05 um 14 16 37](https://user-images.githubusercontent.com/1135285/30060797-1f320e6c-9245-11e7-9fb4-5cd34d6cb4f6.png)

My FilesCollection has the following constructor (mainly the example from Images):



```javascript
export const UnitFiles = new FilesCollection({
	collectionName: "unitfiles",
	allowClientCode: true,
	debug: Meteor.isServer && process.env.NODE_ENV === 'development',
	storagePath: 'assets/app/uploads/unitfiles',

	onBeforeUpload(file) {
		if (file.size <= 10485760 && /pdf|png|jpg|jpeg|doc|docx|ppt|pptx/i.test(file.extension))
			return true;
		return UnitFileErrors.FILE_SIZE;
	},


	onAfterUpload(uploadedFile) {
		// Move file to GridFS
		Object.keys(uploadedFile.versions).forEach(versionName => {
			const metadata = {versionName, fileId: uploadedFile._id, storedAt: new Date()}; // Optional
			const writeStream = gfs.createWriteStream({filename: uploadedFile.name, metadata});

			fs.createReadStream(uploadedFile.versions[versionName].path).pipe(writeStream);

			writeStream.on('close', Meteor.bindEnvironment(file => {
				const property = `versions.${versionName}.meta.gridFsFileId`;

				// If we store the ObjectID itself, Meteor (EJSON?) seems to convert it to a
				// LocalCollection.ObjectID, which GFS doesn't understand.
				// console.log("uploaded unit files to: ", file._id, property, uploadedFile._id);
				this.collection.update(uploadedFile._id, {$set: {[property]: file._id.toString()}});
				this.unlink(this.collection.findOne(uploadedFile._id), versionName); // Unlink files from FS
			}));
		});
	},

	interceptDownload(http, file, versionName) {
		// Serve file from GridFS
		const _id = (file.versions[versionName].meta || {}).gridFsFileId;
		if (_id) {
			const readStream = gfs.createReadStream({_id});
			readStream.on('error', err => { throw err; });
			readStream.pipe(http.response);
		}
		return Boolean(_id); // Serve file from either GridFS or FS if it wasn't uploaded yet
	},

	onAfterRemove(files) {
		// Remove corresponding file from GridFS
		files.forEach(file => {
			Object.keys(file.versions).forEach(versionName => {
				const _id = (file.versions[versionName].meta || {}).gridFsFileId;
				if (_id) gfs.remove({_id}, err => { if (err) throw err; });
			});
		});
	}
});


if (Meteor.isServer) {
	Meteor.publish('files.unitfiles.all', function () {
		return UnitFiles.collection.find({});
	});
	UnitFiles.allowClient();
	UnitFiles.allow({
		insert: function() {
			return true;
		},
		update: function() {
			return false;
		},
		remove: function() {
			return true;
		}
	});
}

if (Meteor.isClient) {
	Meteor.subscribe("files.unitfiles.all");
}
```

I can provide more information, if you need.

**Comment by jankapunkt** [comment]
Update

Okay I found out, that the 404 was an apache issue. There was some apache process running in the realm of this applications domain. However, this did not fix the issue 100%, I had also to create the asset upload folder.

Very strange because in my dev app I created the folder including subfolders (`assets/app/uploads/unitfiles` as shown in the example above) AND even a dummy js file in order to keep the folder referenced but Meteor did not put that folder into my bundle.

However after mkdir -p app/uploads/unitfiles in my programs/server/assets folder and applying the correct user ownership everything works out.

You can close this issue. Thanks for your patience.

**Comment by dr-dimitru** [comment]
Hello @jankapunkt ,

Great, I'm glad your issue is solved now.
Speaking of storage path ,I highly recommend setting `storagePath` to an absolute value as described in [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq) this will help to avoid further issues, as it may get wiped out when you will deploy app update (*of course it depends on deployment*).
