### ISSUE TITLE
Windows Edge and "allowWebWorkers" if debug is enabled

### ISSUE THREAD

**Issue by Avijobo** [VeliovGroup/Meteor-Files#476]
For your information: when using Edge browser, sometimes file upload does not start or gets halted after a few chunks when "allowWebworkers" is set (= default). In these cases the upload state remains "active" however nothing happens anymore, no errors occur, the file just does not get uploaded any further. 

All works well on Edge if "allowWebworkers" is set to false.

**Comment by dr-dimitru** [comment]
Hello @Avijobo ,

Thank you for this report.

Could you please confirm this is the case for [our demo app](https://files.veliov.com)? (*I don't have access to Edge now*).

**Comment by Avijobo** [comment]
Yes I can get a similar behavior with the demo app, but it doesn't always occur, and you need to upload files simultaneously. I uploaded 4 files (+- 20MB each) simultaneously, and after about 70% the uploads halted. When clicking the "resume" button (which I don't have in my app... is there a real need to?) I could get all 4 files continuing to upload, but at the end only 1 file was intact, the other 3 were "damaged" on the server and contained errors.

**Comment by dr-dimitru** [comment]
> which I don't have in my app... is there a real need to?

It might be a good option if app is made to upload large files, which may help in case of network failures.

Thank you for report it will require us to investigate it.
Hope if anyone else having this issue will report too.

@Avijobo please name exact version of Windows and Edge you're using.

**Comment by Avijobo** [comment]
Windows 10 Pro Version 1607 OS Build 14393.1593
Microsoft Edge 38.14393.1066.0

**Comment by dr-dimitru** [comment]
@Avijobo what you have described here, reminds me about #458 , where Safari on Mac and iOS was hanging with multiple upload streams and large chunk size. The solution is to use `http` transport, with `{stream: 1, chunkSize: 102400}` options passed to `.insert()` methods, see [this comment for more info](https://github.com/VeliovGroup/Meteor-Files/issues/458#issuecomment-313086326).

Could you please confirm this happens on `ddp` and `http` transports or only one of them?

**Comment by dr-dimitru** [comment]
I know @mozibrand and @laosb have experience with IE and helped to test and make this package compatible with IE.

Guys, I'll be glad if you can share your thoughts on this issue.

**Comment by laosb** [comment]
I don't have access to Windows machines at this moment, but if you have any further questions I can try to gain it. 😉

**Comment by Avijobo** [comment]
Update: I also had similar problems with the "demo-simplest-upload" app: both Edge and IE11 did not start uploading a file, unless their "developer tools" were active in the browser.... very weird.

Fix: Set 'debug' option to false in the FilesCollection constructor config. 

If 'debug: true' is set in these browsers, uploads do not get started, not in developer mode or production mode, and regardless of the upload settings (http/ddp, allowWebWorkers etc...). 
If 'debug: false' is set (or 'debug; field is omitted), everything works as expected, with all upload settings.

**Comment by dr-dimitru** [comment]
> If 'debug: true' is set in these browsers, uploads do not get started, not in developer mode or production mode, and regardless of the upload settings (http/ddp, allowWebWorkers etc...).
> If 'debug: false' is set (or 'debug; field is omitted), everything works as expected, with all upload settings.

This is very useful, we will try to find a root of the issue. Meanwhile you're good with disabled `debug`, right?

**Comment by Avijobo** [comment]
Yes, perfect! I am happy Edge and IE11 work perfect now, also in production... once again thanks for your commitment!

**Comment by dr-dimitru** [comment]
Thank you. Let's keep it open, unless we find the root of the issue.

**Comment by dr-dimitru** [comment]
@Avijobo can not reproduce it on our end.
Marked as [In a case of the fire - Read This] if someone else will run into the same issue, and renamed to `Windows Edge and "allowWebWorkers" if debug is enabled`.

Feel free to reopen it in case if the issue still persists on your end.
