### ISSUE TITLE
no file cleanup after upload aborted?

### ISSUE THREAD

**Issue by Avijobo** [VeliovGroup/Meteor-Files#477]
When an upload is aborted, it seems that the partially uploaded file is not deleted. Is this expected behavior?

**Comment by dr-dimitru** [comment]
Hello @Avijobo ,

>  Is this expected behavior?

No.

Could you confirm it somehow? Note: if for any reason file chunks is not removed on "abort" event, there is [`continueUploadTTL`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) option, which should clean this up.

**Comment by Avijobo** [comment]
I added an "abort" option to my local copy of "demo-simplest-upload", and the problem is there too: the aborted uploading file does no get deleted.

To test, his is what I added to main.js:
 
```
'click #progress': function (e, template) {
		var currentUpload = template.currentUpload.get();
		currentUpload.abort();
	}
```
During upload, clicking on the "progress percentage text" aborts the current upload. 

This is the server log:

...
I20170823-13:18:50.776(2)? [FilesCollection] [Upload] [DDP] Got #55/90 chunks, dst: Dominique_Santé.jpg
I20170823-13:18:50.794(2)? [FilesCollection] [Upload] [DDP] Got #56/90 chunks, dst: Dominique_Santé.jpg
I20170823-13:18:50.813(2)? [FilesCollection] [Upload] [DDP] Got #57/90 chunks, dst: Dominique_Santé.jpg
I20170823-13:18:50.814(2)? [FilesCollection] [Abort Method]: coMgTn5oSenCdNoBj - assets\app\uploads\Images\coMgTn5oSenCdNoBj.jpg
I20170823-13:18:50.817(2)? [FilesCollection] [remove({"_id":"coMgTn5oSenCdNoBj"})]
I20170823-13:18:50.821(2)? [FilesCollection] [unlink(coMgTn5oSenCdNoBj, undefined)]
I20170823-13:18:50.823(2)? [FilesCollection] [_preCollectionCursor.observe] [removed]: coMgTn5oSenCdNoBj
I20170823-13:18:50.825(2)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: coMgTn5oSenCdNoBj

This is the client log:

[FilesCollection] [insert()]
client.coffee:42 [FilesCollection] [FileUpload] [constructor]
client.coffee:42 [FilesCollection] [insert] using WebWorkers
client.coffee:42 [FilesCollection] [UploadInstance] [createStreams]
client.coffee:42 [FilesCollection] [insert] [.abort()]
client.coffee:42 [FilesCollection] [insert] [.pause()]
client.coffee:794 insert Dominique_Santé.jpg: 1509.675048828125ms

Adding the field 'continueUploadTTL: 60' to the constructor config object does not clean up the file either, even waiting much longer than 60 seconds. (NOTE: a number must be given as a type here, not a string as the documentation indicates.)

So I do not find a way to have an aborted uploading file being cleaned up. This is all tested in developer mode, with the default storage path.

**Comment by dr-dimitru** [comment]
Are you on Windows?

**Comment by Avijobo** [comment]
Yes, Windows 10 Pro

**Comment by dr-dimitru** [comment]
Could you please describe your env:

 1. Dev OS
 2. Prod OS
 3. Meteor version
 4. Meteor-Files package version

**Comment by Avijobo** [comment]
Dev OS: Windows 10 Pro Version 1607 OS Build 14393.1593
Prod OS: not tested this in production environment yet

I updated the "demo-simplest-upload" app to all latest versions. This is the project's .meteor versions file content:

allow-deny@1.0.6
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
coffeescript@1.12.7_1
coffeescript-compiler@1.12.7_1
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.13
es5-shim@4.6.15
fastclick@1.0.13
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jquery@1.11.10
launch-screen@1.1.1
livedata@1.0.18
logging@1.1.17
meteor@1.7.1
meteor-base@1.1.0
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
mobile-experience@1.0.4
mobile-status-bar@1.0.14
modules@0.9.4
modules-runtime@0.8.0
mongo@1.1.22
mongo-id@1.0.6
npm-mongo@2.2.30
observe-sequence@1.0.16
ordered-dict@1.0.9
ostrio:cookies@2.2.2
ostrio:files@1.8.2
ostrio:templatehelpers@1.1.3
promise@0.8.9
random@1.0.10
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.3
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
webapp@1.3.17
webapp-hashing@1.0.9

**Comment by dr-dimitru** [comment]
@Avijobo okay.

Need to find a MS device somewhere, or hopefully someone from community can step-in to confirm this is a bug. Marked as "help wanted", feel free to post a link at [forums.meteor.com](http://forums.meteor.com/).

**Comment by dr-dimitru** [comment]
Hey @Avijobo ,

Sorry for delay on this.
I've tested this case a lot, and I can not reproduce it in any way.
Only if upload is too fast and I'm clicking "abort" button after last chunk is already sent.

Feel free to reopen it in case if the issue still persists on your end.
