### ISSUE TITLE
Uploading from app with another port

### ISSUE THREAD

**Issue by aspirinchaos** [VeliovGroup/Meteor-Files#478]
I have 2 apps. first app run and on port 3000, second run on port 3030 and use mongo from 1st app. When I try to upload some image from 2nd apps, upload is ended without error, but file isn't in folder for images. uploading from 1st app is normal. 
     
> - Version of `Meteor-Files` you're experiencing this issue

1.8.2
     
> - Version of `Meteor` you're experiencing this issue

1.5
 
> - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

```[FilesCollection] [find({"userId":"jBxsw3tbCMKp24yrt","meta.type":"driver-photo"}, {"sort":{"meta.uploaded":-1}})]
[FilesCollection] [File Start Method] 577a6333aa8cd.jpeg - ixtxT9psdBmbiybK7
[FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: 577a6333aa8cd.jpeg
[FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: 577a6333aa8cd.jpeg
[FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: 577a6333aa8cd.jpeg
[FilesCollection] [Upload] [finish(ing)Upload] -> /Users/aspirin/adPlace/driver/images//ixtxT9psdBmbiybK7.jpeg
[FilesCollection] [Upload] [finish(ed)Upload] -> /Users/aspirin/adPlace/driver/images//ixtxT9psdBmbiybK7.jpeg
[FilesCollection] [_preCollectionCursor.observe] [removed]: ixtxT9psdBmbiybK7
[FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: ixtxT9psdBmbiybK7
[FilesCollection] [download(/cdn/storage/DriverImage/ixtxT9psdBmbiybK7/original/ixtxT9psdBmbiybK7.jpeg, original)]
(STDERR) [FilesCollection] [download(/cdn/storage/DriverImage/ixtxT9psdBmbiybK7/original/ixtxT9psdBmbiybK7.jpeg)] [_404] File not found

**Comment by dr-dimitru** [comment]
Hello @aspirinchaos ,

 1. Posted logs is from the first or second server?
 2. Could you locate uploaded files under directory specified in `storagePath` option? (*To make sure files is written to FS*)
 3. Could you post where generated "downloadable" link is pointing to?

**Comment by aspirinchaos** [comment]
@dr-dimitru 
1. second server
2. no, directory is empty
3. file from db
```
{
    "_id" : "hovCCEM9E88Zug7Xy",
    "size" : 47228,
    "type" : "image/jpeg",
    "name" : "577a6333aa8cd.jpeg",
    "meta" : {
        "type" : "driver-photo",
        "uploaded" : ISODate("2017-08-21T21:14:18.490Z")
    },
    "ext" : "jpeg",
    "extension" : "jpeg",
    "extensionWithDot" : ".jpeg",
    "mime" : "image/jpeg",
    "mime-type" : "image/jpeg",
    "userId" : "jBxsw3tbCMKp24yrt",
    "path" : "/Users/aspirin/adPlace/driver/images/hovCCEM9E88Zug7Xy.jpeg",
    "versions" : {
        "original" : {
            "path" : "/Users/aspirin/adPlace/driver/images/hovCCEM9E88Zug7Xy.jpeg",
            "size" : 47228,
            "type" : "image/jpeg",
            "extension" : "jpeg"
        }
    },
    "_downloadRoute" : "/cdn/storage",
    "_collectionName" : "DriverImage",
    "isVideo" : false,
    "isAudio" : false,
    "isImage" : true,
    "isText" : false,
    "isJSON" : false,
    "isPDF" : false,
    "_storagePath" : "/Users/aspirin/adPlace/driver/images/",
    "public" : false
}

**Comment by aspirinchaos** [comment]
This is strange, but now it works..

**Comment by dr-dimitru** [comment]
> This is strange, but now it works..

Well... `meteor reset` sometimes helps me a lot

**Comment by aspirinchaos** [comment]
I executed `meteor reset` few hours ago, but it didn't help.
maybe re adding package helped

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
