### ISSUE TITLE
metadata wiped out in some cases.

### ISSUE THREAD

**Issue by znewsham** [VeliovGroup/Meteor-Files#481]
I am having an intermittent problem in a production environment, where my metadata is being cleared on submission - this is a huge problem because the metadata we pass in identifies the owner (not user, but "group") in a multi client system.

I did some tracing on the server with Kadira, in the onUploaded callback I get the following object:

    {"_id":"DznTQp283RhBwALCQ",
    "name":"SPECIAL vs TRIPS (COVER 8 CHECK) - Copy.png",
    "extension":"png",
    "path":"/tmp/DznTQp283RhBwALCQ.png",
    "meta":{},
    "type":"image/png",
    "size":56438,
    "userId":null,
    "versions":(omitted of brevity),
    "_downloadRoute":"/cdn/storage",
    "_collectionName":"images",
    "isVideo":false,
    "isAudio":false,
    "isImage":true,
    "isText":false,
    "isJSON":false,
    "isPDF":false,
    "_storagePath":"/tmp"}

My insert code looks like this:

          Images.insert({
            file: dataURL,
            meta: {
              teamId: methodToGetTeamId(),
              parentType: "a thing",
              parentId: "aThingsId",
              url: window.location.href //to aid debugging
            },
            isBase64: true,
            fileName: name + '.png',
            onUploaded(error, fileRef){
              if(error){
                Notifications.error("Couldn't save image", error.message);
              }
              else {
                ParentCollection.update({_id: "aThingsId"}, {$set: {imageId: fileRef._id}});
                Notifications.success("Saved!", "", {timeout: 1000});
              }
            }
          });

despite the userId: null logged - the user IS logged in, the ParentCollection.update code would fail otherwise, and it does not (I've triple checked this). The image is uploaded successfully and the parent is updated with the imageId, but the inserted image is missing its meta field - this happens intermittently, but frequently (around 50 times per day) but exclusively with this collection. The only difference between this insert call, and the other collections, is for the other collections we use an upload form, so we pass autostart: false to the insert method, and manually trigger .start() on the result, isBase64 isn't used and we also pass in 

  	        streams: 'dynamic',
  	        chunkSize: 'dynamic',

I am unable to replicate this in our staging, or dev environments, so any assistance here would be great

**Comment by dr-dimitru** [comment]
1. Issue you have described is common for < `v1.6.0`, what Meteor-Files package and Meteor version you're on?
 2. Use `onBeforeUpload` hook to catch uploads without `meta` objects, deny upload, and log Client's data (Browser, OS, other client's headers)

My guess is some of the browsers, or suspicious users somehow break `meta` Object.

**Comment by znewsham** [comment]
god, I feel so stupid :( this was coming from somewhere else entirely, from the logs it just LOOKED like it was coming from this. We have a server side "clone" method that was calling `Images.load` without any metadata - sorry for wasting your time

**Comment by dr-dimitru** [comment]
@znewsham I'm glad we've found the truth.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
