### ISSUE TITLE
Internet Explorer 11 blank page

### ISSUE THREAD

**Issue by mi-k4** [VeliovGroup/Meteor-Files#483]
Hello, I opened an issue on the forum of Meteor, and after investigation it would seem that the error comes of ostrio:files.

https://forums.meteor.com/t/internet-explorer-11-blank-page/38810

I have enabled the debug mode in the constructor. 

```debug: true,
  storagePath: '/opt/uploads',
  downloadRoute: '/uploads/pictures/',
  collectionName: 'images',
  allowClientCode: false,
  public: false,
  chunkSize: 1024 * 2048,
  throttle: 1024 * 512,
  cacheControl: 'public, max-age=31536000',
```

When I load the homepage of the project for the first time, the page is empty. When I refresh her, an error appears in the console, here she is:

![image](https://user-images.githubusercontent.com/3338681/29654117-30eb2ff0-88ac-11e7-8c81-493244fe701f.png)

The error seems to concern this line in the repository:

https://github.com/VeliovGroup/Meteor-Files/blob/master/client.coffee#L170

And the logs server side:

```
=> Started proxy.
=> Started MongoDB.
I20170824-08:35:49.566(2)? [FilesCollection.storagePath] Set to: /opt/uploads
=> Started your app.

=> App running at: http://localhost:3000/
```
My file .meteor/versions:

```
accounts-base@1.3.1
accounts-password@1.4.0
alanning:roles@1.2.16
aldeed:collection2-core@2.0.1
aldeed:schema-deny@2.0.0
aldeed:schema-index@2.0.0
aldeed:simple-schema@1.5.3
aldeed:template-extension@4.1.0
allow-deny@1.0.6
arillo:flow-router-helpers@0.5.2
audit-argument-checks@1.0.7
autoupdate@1.3.12
babel-compiler@6.19.4
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.1.1
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
cfs:http-methods@0.0.32
check@1.2.5
coffeescript@1.12.7_1
coffeescript-compiler@1.12.7_1
dburles:google-maps@1.1.5
ddp@1.3.0
ddp-client@2.0.0
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.0
deps@1.0.12
diff-sequence@1.0.7
dynamic-import@0.1.1
ecmascript@0.8.2 # <===================================== here
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.13
email@1.2.3
es5-shim@4.6.15 # <===================================== here
fastclick@1.0.13
froatsnook:request@2.74.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
isotope:isotope@2.1.0_1
jeremy:geocomplete@1.8.0
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
mdg:validated-method@1.1.0
mdg:validation-error@0.5.1
meteor@1.7.1 # <===================================== here
meteor-base@1.1.0
meteorhacks:async@1.0.0
meteorspark:util@0.2.0
mikowals:batch-insert@1.1.14
minifier-css@1.2.16
minifier-js@2.1.1
minimongo@1.2.1
mobile-experience@1.0.4
mobile-status-bar@1.0.14
modules@0.9.4
modules-runtime@0.8.0
momentjs:moment@2.18.1
mongo@1.1.22
mongo-id@1.0.6
mrt:jquery-imagesloaded@0.0.2
nefiltari:yaki@0.1.81
npm-bcrypt@0.9.3
npm-mongo@2.2.30
observe-sequence@1.0.16
ordered-dict@1.0.9
ostrio:cookies@2.2.2
ostrio:files@1.8.2 # <===================================== here
percolate:momentum@0.7.2
percolate:velocityjs@1.2.1_1
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.8.9
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.4
simple:json-routes@2.1.0
simple:reactive-method@1.0.2
softwarerero:accounts-t9n@1.3.11
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@2.1.1
tap:i18n@1.8.2
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.1
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
url@1.1.0
useraccounts:core@1.14.2
useraccounts:flow-routing@1.14.2
useraccounts:unstyled@1.14.2
webapp@1.3.17
webapp-hashing@1.0.9
wizonesolutions:underscore-string@1.0.0
zimme:active-route@2.3.2
```

In the console, it seems nevertheless whether it is an integer which is used:
![log](https://user-images.githubusercontent.com/3338681/29654020-d033f944-88ab-11e7-8557-6fd2bcb07c63.png)

Could you help me ?

Sorry, i don't speak english very well

thanks and good day

**Comment by dr-dimitru** [comment]
Hello @mi-k4 ,

 1. Is error appears if you don't set `chunkSize`?
 2. Is error appears if you set `chunkSize` to a *Number* (without multiplication, like: `2097152`)?

**Comment by mi-k4** [comment]
Hello,

thank you very much of your fast answer. 

Yes, if I delete the chunksize or if I allocate him directly the value 2097152 without multiplication I have the same error.

**Comment by dr-dimitru** [comment]
Hello, 

Can't figure out a reason for this now.
Hope  @mozibrand and @laosb can take a look on this, what may cause such weird behavior in IE? Is `2097152` too big Number for IE?

**Comment by mi-k4** [comment]
Hello @dr-dimitru,

it would seem that the error is not really bound to meteor-files, but anymore to the fact of the use of the strict mode.

![strict](https://user-images.githubusercontent.com/3338681/29857623-d76d3e0c-8d59-11e7-9c6d-ded960a147b4.png)

Are you a idea ?

**Comment by dr-dimitru** [comment]
@mi-k4 no idea where "strict mode" may came from, lib is written in a CoffeeScript which does not `use strict`.

Only web worker is written in JS and `use strict`, there is no place where `arguments` is called.

Is there a possibility to click on the error to see place in code where it was thrown?

**Comment by mi-k4** [comment]
Hello,

the error is throw at this line :

![check-file](https://user-images.githubusercontent.com/3338681/30015208-07beeab6-9150-11e7-86f3-442b9468f1ff.png)

https://github.com/meteor/meteor/blob/master/packages/check/match.js#L39

thank

**Comment by dr-dimitru** [comment]
> I'm going to open an issue in the github of meteor.

Drop a link here

**Comment by mi-k4** [comment]
yes https://github.com/meteor/meteor/issues/9056

**Comment by dr-dimitru** [comment]
Hello @mi-k4 ,

Is this issue exists if you update to the latest Meteor (*1.5.2*)?

**Comment by mi-k4** [comment]
Hello, I have the same error with the new version of meteor. I managed to reproduce a similar error with this repository:

https://github.com/mi-k4/meteor-project-error

the error :

![capture d ecran_2017-09-12_08-14-33](https://user-images.githubusercontent.com/3338681/30311225-91c18472-9794-11e7-9523-3ad8ed15561d.png)

**Comment by mi-k4** [comment]
Hello, the problem is solved, 

I had install babel-polyfill to correct a bug for meteor simpl-schema and the problem came from there. I updated to the last version of simpl-schema to benefit of this PR :
https://github.com/aldeed/node-simple-schema/pull/42/commits/836269148c3cb949819b99a63296c0153bb8fba8
 and to remove babel-polyfill and now that works.

Thank you very mutch for your help and for your awsome package meteor-files.

**Comment by dr-dimitru** [comment]
@mi-k4 I'm glad this one is solved.

> Thank you very much for your help and for you package meteor-files, it is brilliant

These words mean a lot to me and our team, thank you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
