### ISSUE TITLE
[Help wanted] AWS-S3-Integration

### ISSUE THREAD

**Issue by haojia321** [VeliovGroup/Meteor-Files#484]
Hi 
I want to use AWS S3 as our storage. I'm having some questions when I read https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration

Say I put Server-side-file-store.js under imports/server and the UserFiles collection in this file is the collection to upload file to AWS S3. I want to select a file from client and upload to AWS S3. 
My questions:
1. how does the client side know UserFiles collection if I only put it in server folder?
2. Don't we need to export UserFiles in Server-side-file-store.js?

**Comment by dr-dimitru** [comment]
TL;TR;

 1. Client won't know about *FilesCollection* defined on Server
 2. To where?

Better to speak code, let me start first. Exact code splitting looks like this:
```js
// /imports/client/collections/files.js
import { FilesCollection }   from 'meteor/ostrio:files';
const files = new FilesCollection({/* ... */});
export { files };
```

```js
// /imports/server/collections/files.js
import { FilesCollection }   from 'meteor/ostrio:files';
const files = new FilesCollection({/* ... */});
export { files };
```

This is basically all you need to know, yes, it's not really follows DNRY policy, and you're may repeat in a *FilesCollection* config. But in this package passes options to *FilesCollection* Constructor mostly different on Server and Client. Then on the Client's files always import `/imports/client/collections/files.js`, and on server `/imports/server/collections/files.js`.

**Comment by haojia321** [comment]
I got confused, AWS integration wiki only mentioned to put Server-side-file-store.js under imports/server. 
Do you mean I also need to have another file collection in user side? If yes, do I need to write s3 specific code on user side file collection too?

**Comment by haojia321** [comment]
[videoaws.zip](https://github.com/VeliovGroup/Meteor-Files/files/1258790/videoaws.zip)

**Comment by haojia321** [comment]
I have uploaded my demo above.
What Im trying to do is upload a file to UserFiles. I have defined UserFiles as instructed in the wiki page.

**Comment by dr-dimitru** [comment]
> Do you mean I also need to have another file collection in user side?

Yes. if *FilesCollection* instance will be used on the Client.

> If yes, do I need to write s3 specific code on user side file collection too?

No, no changes are required on Client side, adding/using 3rd party storage is Server only task. Client code for upload and read remains the same.

> I have uploaded my demo above.
> What Im trying to do is upload a file to UserFiles. I have defined UserFiles as instructed in the wiki page.

Sorry can't download a file now. If you can post it here, in separate repo or pastebin - it will help.

**Comment by haojia321** [comment]
Thanks for the quick response.
For my understanding to your comments, I have to upload the file to my server's physical storage. Then use server side AWS file collection to upload file to aws. Is it correct? If it is correct, does that mean server will be able to upload file from server storage to aws only if client file upload is completed?

The attached file is a complete meteor project folder. Will google drive share work for you?

Thanks again for the support.

**Comment by dr-dimitru** [comment]
> For my understanding to your comments, I have to upload the file to my server's physical storage. Then use server side AWS file collection to upload file to aws. Is it correct?

Yes.

>  If it is correct, does that mean server will be able to upload file from server storage to aws only if client file upload is completed?

True.

> The attached file is a complete meteor project folder. Will google drive share work for you?

No. But I'll take a look once I have a chance.

**Comment by haojia321** [comment]
Should these user and server collection have same collection name?

**Comment by haojia321** [comment]
Hi @dr-dimitru ,
How can I upload the file to S3 after file is uploaded to meteor server from browser?

**Comment by haojia321** [comment]
Hi I have attached a working project for aws s3 integration below. Feel free to put it under your aws wiki page in case other folks have same questions.

**Comment by haojia321** [comment]
[final-aws.zip](https://github.com/VeliovGroup/Meteor-Files/files/1262321/final-aws.zip)

**Comment by dr-dimitru** [comment]
Reopened with `[DOCUMENTATION]` tag

**Comment by haojia321** [comment]
[CORRECTED-final-aws.zip](https://github.com/VeliovGroup/Meteor-Files/files/1268245/CORRECTED-final-aws.zip)

**Comment by anaghakomawar** [comment]
Thanks haojia321 for the code. I have implemented it. The video is uploaded and shown, but the thing is I am not able to see it in my S3 video. Can you please help to know what should be the url for the video if it is stored on S3

**Comment by dr-dimitru** [comment]
@anaghakomawar you simply retrieve it with [`fileURL` helper](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper) or [`.link()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/link).

So it doesn't matter where file is stored on FS, S3, DropBox or any other 3rd party storage, API stays the same
