### ISSUE TITLE
How to create thumbnails in docker container (via Meteor Up etc)

### ISSUE THREAD

**Issue by programthis** [VeliovGroup/Meteor-Files#489]
I'm currently attempting to create thumbnails on my production server (which is in a docker container thanks to Meteor up) but I am met with this error:

`[159.203.61.14][_app.createThumbnails] [_.each sizes] [Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "/images/pFLwvoTSWppt4WhF3.jpg" this most likely means the gm/convert binaries can't be found]`

The main images themselves are uploaded correctly without an errors but I am wondering if anyone has been successful in getting thumbnails to generate correctly. I believe it must have to do with installing graphicsmagick in a docker container, unless there is something else I'm missing?

**Comment by dr-dimitru** [comment]
Hello @programthis ,

 - First take a look on [MUP/X related docs](https://github.com/VeliovGroup/Meteor-Files/wiki/MeteorUp-(MUP)-Usage)
 - All you need is to add GraphicsMagick to Docker Image or use one where `gm` is already build-in:
   * Add to `Dockerfile`:
```shell
RUN apt-get update
RUN apt-get install -y graphicsmagick
```

Let me know if this is solved your issue

**Comment by dr-dimitru** [comment]
@programthis also may be useful to take a look on [demo repo](https://github.com/VeliovGroup/Meteor-Files-Demo): 
 - [Aptfile](https://github.com/VeliovGroup/Meteor-Files-Demo/blob/master/Aptfile)
 - [Dockerfile](https://github.com/VeliovGroup/Meteor-Files-Demo/blob/master/Dockerfile)
 - [Procfile](https://github.com/VeliovGroup/Meteor-Files-Demo/blob/master/Procfile)

**Comment by programthis** [comment]
@dr-dimitru thank you very much. I found a docker image to use with those very commands you referenced and it now works.

**Comment by dr-dimitru** [comment]
@programthis awesome, I'm glad it helped you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
