### ISSUE TITLE
Video on AWS

### ISSUE THREAD

**Issue by haojia321** [VeliovGroup/Meteor-Files#491]
Hi,
I use ostrio:files as meteor file upload package and AWS as storage. I'm able to upload video file to aws successfully. 
But if I copy the uploaded file url(http://yourdomain/cdn/storage/OstrioVideo/rYxM3957sT6vePT3W/original/rYxM3957sT6vePT3W.mov) and paste into a new browser tab address bar. It actually downloads the file not display this video in a player.
Added ?play=true did help.

Please advice.

**Comment by haojia321** [comment]
invalid. I figured it depends on the video file extension.

**Comment by Steve1820** [comment]
@haojia321 what file extension did you use?
