### ISSUE TITLE
upload from Cordova: on WiFi works, on 3G - no

### ISSUE THREAD

**Issue by Zentelechia** [VeliovGroup/Meteor-Files#492]
I use ostrio:files v 1.8.2
Meteor 1.5.1
Cordova client

I'm sending small files 4K as base64 from Cordova client
When WiFi is on - upload is sucessfull. On 3G - not (connection to Meteor Server is good)
This is client code for upload:
```javascript
var upload = Images.insert({
      file: 'data:image/jpeg;base64,'+imageData,
      isBase64: true, // <— Mandatory,
      fileName: Date.now()+'.jpg', 
      streams: 'dynamic',
      chunkSize: 'dynamic',
      meta: meta
    }, false);

    upload.on('start', function () {
      console.log('upoad started');
      template.currentUpload.set(this);
    });

    upload.on('uploaded', function (error, fileObj) {
      console.log(error);
    });

    upload.on('progress', function (p) {
      console.log(p);
    });

    upload.on('error', function(e){
      console.log(e);
    });
    upload.on('end', function (error, fileObj) {
      if (error) {
        console.log(error);
      } else {

      }
      template.currentUpload.set(false);
      Session.set("taking_picture",false);
    });
    console.log(upload);
    upload.start();
```

server code

```javascript
  var Images = new FilesCollection({
    collectionName: 'Images',
    storagePath: storagePath,
    debug: true,
    allowClientCode: true, 
    onBeforeUpload: function (file) {
      if (file.size <= 3*1024*1024 && /jpg|jpeg/i.test(file.extension)) {
        return true;
      } else {
        return 'Please upload image, with size equal or less than 3MB';
      }
    },

    onAfterUpload: function(img){
     
 try {

      s=Shippings.findOne({ticket: img.meta.ticket});
      var d;
      if (img.meta.type=="start") {
        d=dist(img.meta.location.lat,img.meta.location.lng,s.start_point[0],s.start_point[1]);
      }
      if (img.meta.type=="end") {
        d=dist(img.meta.location.lat,img.meta.location.lng,s.end_point[0],s.end_point[1]);
      }
      Images.update(img._id, {$set : {
        "meta.distance" : d
      }});
      }
      catch(e) {
        console.log(e);
      }

    }
  });
```

On Server I see following debug messages in console when I try to upload file from Cordova client
```{r, engine='bash', count_lines}
I20170914-15:46:15.692(0)? [FilesCollection] [File Start Method] 1505403975181.jpg - GRCxPvyd5XLeQXyiv
I20170914-15:46:15.695(0)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: 1505403975181.jpg
 ```
What it can be?

**Comment by dr-dimitru** [comment]
Hello @Zentelechia ,

 1. Are there any Client logs and/or errors?
 2. Try with `streams` set to `1`

*Sorry for delay,* please keep this thread updated

**Comment by Zentelechia** [comment]
Hello @dr-dimitru 
1. No Clients logs or errors (I assigned handlers for all available events  - no errors). Sequence - upload pause->upload started......nothning
2. I tryed - the same

**Comment by dr-dimitru** [comment]
@Zentelechia Try to use `transport: 'http'`

**Comment by dr-dimitru** [comment]
and update `ostrio:files` to the latest release, please.

**Comment by dr-dimitru** [comment]
I think issue is here: `file: 'data:image/jpeg;base64,'+imageData`
While it should be one of:

 - `file: 'data:image/jpeg,'+imageData`
 - `file: 'image/jpeg,'+imageData`
 - `file: imageData`

And could you `console.log(imageData)` to make sure `imageData` actually holds data

**Comment by Zentelechia** [comment]
With 'http' transport - I got error like 'You are behind proxy.... try to use ddp'  (I say about 3G)
imageData - it's ok (long bas64 string)
I have updated to 1.8.3 - but still same situation

About  **file: 'data:image/jpeg;base64,'+imageData** - I will try it later, but main issue - that this works for WiFi

**Comment by dr-dimitru** [comment]
> With 'http' transport - I got error like 'You are behind proxy.... try to use ddp' (I say about 3G)

This is the Client error. Do you have any Server errors/logs?

> imageData - it's ok (long bas64 string)
> I have updated to 1.8.3 - but still same situation

Good

> About file: 'data:image/jpeg;base64,'+imageData - I will try it later, but main issue - that this works for WiFi

Got it. Could you try (*for testing purpose*) to upload file without encoding it to Base64? Let's see if it's related to base64 encoded uploads only, or to any type of upload method.

Also if you upload from same mobile device, but from a web version (*not Cordova*) will it work?

**Comment by Zentelechia** [comment]
I tryed to upload  file (from input type="file") -the same - works on Wifi only

Ок, later will test with web version

**Comment by dr-dimitru** [comment]
> I tryed to upload file (from input type="file") -the same - works on Wifi only

Hmmm...


> Ок, later will test with web version

Ok, keep this thread updated

**Comment by Zentelechia** [comment]
I just noticed, that this issue appeared after  closing  issue #467 - (when I change collection option inside FileCollection Constructor)

**Comment by dr-dimitru** [comment]
@Zentelechia could you post a code where it's used?

**Comment by dr-dimitru** [comment]
@Zentelechia is this one solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by Zentelechia** [comment]
Hi @dr-dimitru !

Sorry for long silence, I'm swamped right now

From my last message, as I needed solution  - I used another way to transfer images from cordova client to server  over 3G (insert base64 string, representing image,  into ordinary Collection - and then on Server move it into FileCollection) I know that it is very bad usecase, but it works for me

May be little later I'll continue experiments with this issue

**Comment by dr-dimitru** [comment]
@Zentelechia thank you for update.
Feel free to reopen it at anytime.
