### ISSUE TITLE
After cancel files upload on client side, server side throws error

### ISSUE THREAD

**Issue by Diwei-Chen** [VeliovGroup/Meteor-Files#493]
After users cancel the files upload process, then the Meteor-Files server will throw the error message - `[FilesCollection] [writeStream] [ensureFile] [open] [Error:] [500]` . 

Is it because when the upload process is canceled, the file will be removed immediately on server side, then server is writing data to a file which is not exist? Even though as stated it has checked the file exists or not, but could that be interrupted by an asynchronous process which tries to delete the file?   
![33](https://user-images.githubusercontent.com/26317142/30631896-5ed994aa-9e29-11e7-967b-eff494ba1712.png)
 
The `permissions ` and `parentDirPermissions ` we set to the files collection both are 0777 and we deploy it on Galaxy server. 

Also, not sure how could we handle this error on our codes..

Thanks

**Comment by dr-dimitru** [comment]
Hello @Diwei-Chen ,

Looks like a [bug] candidate.
Please follow our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE), and add missing info:

   - Version of `Meteor-Files` you're experiencing this issue
   - Version of `Meteor` you're experiencing this issue
   - Is it *Client* or *Server* issue?
   - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

ty

**Comment by Diwei-Chen** [comment]
Thanks for your quick reply @dr-dimitru 

Sorry, those are:
* We are on `Meteor-Files` 1.8.2*
* `Meteor` 1.5.2
* This is Server issue
* The Server logs are listed below:
```
8yv9w
2017-09-21 10:51:36+10:00Dropped 731 lines of logs. Consider reducing log volume in your app.
8yv9w
2017-09-21 10:51:36+10:00[FilesCollection] [File Start Method] 1 copy.png - KqszK8jamB3hvGmGa
8yv9w
2017-09-21 10:51:36+10:00[FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: 1 copy.png
8yv9w
2017-09-21 10:51:37+10:00[FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: 1 copy.png
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [Abort Method]: KqszK8jamB3hvGmGa - assets/app/uploads/ibmConnectionsFiles/KqszK8jamB3hvGmGa.png
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [remove({"_id":"KqszK8jamB3hvGmGa"})]
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [_preCollectionCursor.observe] [removed]: KqszK8jamB3hvGmGa
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: KqszK8jamB3hvGmGa
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [unlink(KqszK8jamB3hvGmGa, undefined)]
8yv9w
2017-09-21 10:51:38+10:00[FilesCollection] [Abort Method]: KqszK8jamB3hvGmGa - undefined
xd39

```

**Comment by dr-dimitru** [comment]
Hello @Diwei-Chen ,

Thank you for the update.

 1. Is this happens only on Galaxy or any environment including development?
 2. Is the issue appears on the development too, please describe your dev.env? Linux? Mac? Win?
 3. Is the Abort method called by the user or programmatically?
 4. Is the issue appears on the every "Abort" invocation or only sometimes?

**Comment by Diwei-Chen** [comment]
Hi @dr-dimitru 

1. This error only throws on Galaxy yesterday. I couldn't replicate it on my local server.
![22](https://user-images.githubusercontent.com/26317142/30676653-7d760cbc-9eca-11e7-8d57-5a2d758c4e4d.png)

2. My dev.env is on Mac(10.12.6). When I try to upload a file today(just normal upload), although the progress shows curValue is 100, the state is still "active" instead of "completed"
<img width="810" alt="tt" src="https://user-images.githubusercontent.com/26317142/30676794-44cb4fa2-9ecb-11e7-83eb-aa71568e9474.png">
Also, the server throws following exception:
```
I20170921-12:42:24.175(10)? Exception in callback of async function: Error: [FilesCollection] [writeStream] [ensureFile] [Error:] [500]
I20170921-12:42:24.177(10)?     at packages/ostrio_files/write-stream.coffee:36:17
I20170921-12:42:24.179(10)?     at packages/ostrio_files/write-stream.coffee:7:55
I20170921-12:42:24.180(10)?     at runWithEnvironment (packages/meteor.js:1189:24)
```

3. The Abort method is called by the user. The code snippet is: 
```
"click #cancel-upload": function(e, template) {
    const currentUpload = template.data.currentUpload.get();
    _.each(currentUpload, (ref) => {
      if (typeof ref.abort === 'function') {
        ref.abort();
        console.log('ref abort', ref);
      }
    })
    template.data.currentUpload.set(currentUpload);
    template.data.isUploadCanceled.set(true);
    $('#modal-upload-cancel').modal('hide');
    $('#modal-upload-progress').modal('hide');
  },
```

4. It appears on every "Abort" invocation in my use case.

Regards,

**Comment by dr-dimitru** [comment]
Marked as [help wanted], I haven't faced Galaxy yet. 
I know it uses Docker solution deep inside and [has no persistent storage](http://galaxy-guide.meteor.com/file-storage.html), same as Heroku (*where it works fine*).

@Diwei-Chen any ideas how it might be related to [this](http://galaxy-guide.meteor.com/file-storage.html)? Like if file was removed before upload is finished?

Take a look on next threads:
 - https://github.com/VeliovGroup/Meteor-Files/issues/398
 - Looks like similar issue: https://github.com/VeliovGroup/Meteor-Files/issues/452

**Comment by Diwei-Chen** [comment]
Thanks for explanation @dr-dimitru 

Yes, this is related to our issue and it is one of the two that causes the problem. As we used the default path so probably we don't have the permissions to write files. But after we changed it to the absolute path which is suggested as '/tmp', this issue still exists.

We then did some revisions on our codes and we found we shouldn't `abort()` the file upload process that has finished. Cos the abort method will remove the file reference on the file collection and unlink(remove) the corresponding file. But after the file has been uploaded to our server, we needed to do one more step on the file, which is another process(FileReader) is processing the file. So if we abort all the file upload processes, which will raise race condition on our server and then the server crashed by unhandled exception thrown by FileReader.

We now have fixed the issue and thanks heaps for your help!

Regards,
Diwei

**Comment by dr-dimitru** [comment]
>  Cos the abort method will remove the file reference on the file collection and unlink(remove) the corresponding file.

👍 👨‍✈️ 

> We now have fixed the issue and thanks heaps for your help!

Great, I'm glad it helped you.
Feel free to reopen it in case if the issue still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
