### ISSUE TITLE
Meteor(React) : There is already a collection named "collection_name"

### ISSUE THREAD

**Issue by rashmimhatre100** [VeliovGroup/Meteor-Files#494]
/imports/usersProfiles/api/AttachmentFile.js
Imported this file in server/main.js

    // Declare the Meteor file collection on the Server
    export const AttachmentFile = new FilesCollection({
        debug: true, // Change to `true` for debugging
        storagePath: 'abcData',
        collectionName : 'abc',
        // Disallow Client to execute remove, use the Meteor.method
        allowClientCode: false,
        chunkSize: 1024 * 1024,
    });

/imports/usersProfiles/components/AttachmentFile.js
Imported this file in /imports/components/editprofile.js

    import { Meteor } from 'meteor/meteor';
    import { FilesCollection } from 'meteor/ostrio:files';
    export const AttachmentFile = new FilesCollection({
       collectionName: 'abc',
       allowClientCode: false,
       chunkSize: 1024 * 1024
    });

Getting error and crashing my app, error=> There is already a collection named "abc"

Thanks in advance!

**Comment by dr-dimitru** [comment]
Hello @rashmimhatre100 ,

Obviously collection is created twice.
Is this issue happens on Server or Client? 

What debugging logs tells you? Could you trace back where collections is created?

**Comment by rashmimhatre100** [comment]
Thing is I waz importing all the components at lib/router.js 
Lib is client as well as server.

Below setting has to be at client side. so finally I imported the file directly into /client/main.js

`     
        export const AttachmentFile = new FilesCollection({
        debug: true, // Change to `true` for debugging
        storagePath: 'abcData',
        collectionName : 'abc',
        // Disallow Client to execute remove, use the Meteor.method
        allowClientCode: false,
        chunkSize: 1024 * 1024,
        });
`

Now, it's working fine.

**Comment by dr-dimitru** [comment]
> Lib is client as well as server.

👍 

> Now, it's working fine.

I'm glad it helped you :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
