### ISSUE TITLE
Files are gone after reboot !!!

### ISSUE THREAD

**Issue by mokaid** [VeliovGroup/Meteor-Files#499]
HELLO 
I added the volume is the mup.json .. 
folder been created in docker and storings images normally 
but still upon restart files disappear ..
any advice ?!!

**Comment by dr-dimitru** [comment]
Hello @mokaid ,

No advice here, better to ask at Docker or MUP repository.
From my point of view it's not related to this repository.
WDYT?

**Comment by Remeus** [comment]
Everything seems to work normally with MUP, I have just done a deployment and all the images were kept intact in the mounted volume.

**Comment by mokaid** [comment]
@Remeus  you mean like i have to set the volume manually on the server !! 
doesn't mup take care of creating and mounting the volume ?

**Comment by Remeus** [comment]
@mokaid No indeed, MUP takes care of everything. You just need to add the volume to be mounted in your mup.js file `app: { volumes: { "/images": "/images" }, ... }` and then reference this mounted volume in your File Collection creation `export const Images = new FilesCollection({ storagePath: "/images", ... });`.
Then everything should work.

**Comment by dr-dimitru** [comment]
@Remeus thank you for info

@mokaid have you solved it?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
