### ISSUE TITLE
How to get file path of selected file from HTML form

### ISSUE THREAD

**Issue by tobitech** [VeliovGroup/Meteor-Files#502]
Hello, I have to upload files from the server side of my project, so I'm using addFile() method, but I don't know how to get the file path of the selected file from file input in my HTML form. Please can you help with this?

**Comment by dr-dimitru** [comment]
Hello @tobitech ,

 1. Files added via `.addFile()` accessible within `.find()` or `.findOne()` as any other uploaded file
 2. I didn't get this one: ` but I don't know how to get the file path of the selected file from file input in my HTML form`, please speak code
 3. `Please can you help with this?` Sure just explain what do you want to accomplish

**Comment by tobitech** [comment]
Okay. Want to upload file that a user selects from an HTML 5 input file type. 
`<input type="file" id="productImage">`
1. Creating a database of products that have images as one of their parameters. so in my Template events I would get the file with `var file = $('#productImage').get(0).files[0];`. 

2. I can just use insert file from the client side and would add it to an Assets Collection of type FilesCollection. But I want the insert to be made on the server side by calling a Meteor method, so I have to use addFile() or writeFile based on your docs. But addFile() needs a path to the file to be inserted.
3. I have tried this from the client 
`reader.onload = function(e) {
                filePath = e.target.result;
                console.log(filePath);
            };
            reader.readAsDataURL(file);
           Meteor.call('insert method', filePath);`
and this also 
`pathURL = URL.createObjectURL(event.target.files[0]);.` 
but addFile() keeps throwing an error that “No such file or directory”.
4. So that's the full explanation on what i'm trying to do. I hope you clearly understand

**Comment by dr-dimitru** [comment]
@tobitech thank you for more info.

 1. `.addFile()`, `.load()` and  `.write()` are server only methods
 2. As I see you want to *upload* files from HTML5 form, you should use `.insert()` method
 3. Returned result from `.insert()` method can be added to the `product`, for example as `image` field
 4. When user submits the form you will need to `.insert()` selected image as a first step, then send all other form data via Meteor's method to the server
 5. [Upload on form submit code sample](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/upload/upload-form.js#L252)
 6. Another option is to upload file right away after it's selected
 7. [Upload on select code sample](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo-simplest-upload/client/main.js#L23)
 8. [`.insert()` method docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#events-based-example)

Let me know if this helped you.

**Comment by tobitech** [comment]
That was going to be my last try. I just felt it would be more secured to insert files into collections (including FilesCollection) from the server. Thank. So if I may ask. What kind of files then can one upload with `.addFile()`, `.write()`? files in a directory already on the server? What's a sample use case?

**Comment by dr-dimitru** [comment]
1. Security is widely discussed topic, and this is one of our top priorities. You can find out more in a tickets marked with [`SECURITY` label](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=is%3Aissue%20label%3ASECURITY%20). TL;TR; This package is secure, and provides a lot of tools (*as hooks*) to control upload and download flow. But don't take my word for it, ask on [Meteor's forum](https://forums.meteor.com)
 2. [`.write()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) - Use it when you have a file as a *Buffer*
 3. [`.addFile()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile) - Use it when you have a file on the local file system and you know its absolute path.

**Comment by dr-dimitru** [comment]
@tobitech any news? Is this one solved?

**Comment by tobitech** [comment]
Yes

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
