### ISSUE TITLE
Streaming files is slow on Galaxy

### ISSUE THREAD

**Issue by victerryso** [VeliovGroup/Meteor-Files#506]
Hi there,

I'm having problems with streaming files (0 - 4mb videos) smoothly from my AWS S3 Bucket (ap-southeast-2). My app is hosted on Galaxy (ap-southeast-2) and my database is hosted on Compose (sl-aus-syd-1).

It was initially slow at first since the server and database were in America. I'm from Sydney.
I have tried on my local computer and it runs smooth.
I have tried using AWS EC2 (ap-southeast-2) and it runs smooth.

Any suggestions?

```
meteor@1.4.3.2
ostrio:files@1.7.13
aws-sdk@^2.92.0
```

**Comment by dr-dimitru** [comment]
Hello @victerryso ,

Only moving all parts (AWS, MongoDB and Nodejs server) into the same location or at least as close as possible.

We're on files.veliov.com running smoothly though having all parts in different locations (mongolab + AWS:S3 + Heroku), how bad is your delays?

**Comment by victerryso** [comment]
Server, database and storage are all in Sydney now. So the video starts
streaming fine but cuts off after a few seconds. I wonder if it's the way
Galaxy is built because it works smoothly on an ec2 via mup.

On Oct 19, 2017 6:23 PM, "dr.dimitru" <notifications@github.com> wrote:

Hello @victerryso <https://github.com/victerryso> ,

Only moving all parts (AWS, MongoDB and Nodejs server) into the same
location or at least as close as possible.

We're on files.veliov.com running smoothly though having all parts in
different locations (mongolab + AWS:S3 + Heroku), how bad is your delays?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/VeliovGroup/Meteor-Files/issues/506#issuecomment-337822088>,
or mute the thread

**Comment by dr-dimitru** [comment]
@victerryso 

I've never tried Galaxy. Prefer dedicated servers. Using heroku in our case as we having integration with it.

Can't tell you more. You should keep testing different solutions to find one which will meet your needs

**Comment by victerryso** [comment]
I'll try heroku and digital ocean to see if the problem is galaxy. Thanks for your help.

Cheers!

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by victerryso** [comment]
Hi there, I managed to solve the problem by using your previous code base.
I changed intercept download to create a read stream and pipe oppose to `.serve()`

[AWS S3 Integration - 4ae9996](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration/4ae9996b4ebfcb51b9674843bea514acb87cf492)

Thank you for your help! It's much appreciated.

**Comment by dr-dimitru** [comment]
@victerryso version of the AWS:S3 tutorial you're referring to, has a lack of streaming data (*chunked download*), memory may leak on large files, all necessary headers may not be set.

What actually you have fixed? The load performance only, or downloading wasn't working at all?

Maybe we can figure out what is wrong with current implementation in tutorial?

**Comment by victerryso** [comment]
Essentially, the video kept buffering when loading a video. It didn't occur
in aws ec2,  digital ocean or locally using production environments, only
galaxy.

Maybe it's the way galaxy fetches data from external sources and sends it
through to the client.

**Comment by dr-dimitru** [comment]
@victerryso yes, it may like one long connection over multiple short, common issue for "Cloud" solutions.

**Comment by izaa** [comment]
I have this similar problem. 

Setup 1:
- dev machine windows 10
- database mLab dev-database eu-west-1
- s3  eu-west-1
- starts playing but cuts shortly.

Setup 2:
- Meteor Galaxy eu-west-1
- database mLab dev-database eu-west-1
- s3  eu-west-1
- videos not playing at all.

So @victerryso what you exactly did to get this working? 

Thanks!

**Comment by victerryso** [comment]
Hi @izaa,

I managed to use an older version of the [AWS S3 Integration Docs](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration/4ae9996b4ebfcb51b9674843bea514acb87cf492#server-side-file-storejs) to intercept and serve the file.

Hope this helps :)

```
interceptDownload(http, fileRef, version) {
  let path;

  if (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) {
    path = fileRef.versions[version].meta.pipePath;
  }

  if (path) {
    http.response.setHeader('content-type', fileRef.type || 'application/pdf');
    http.response.setHeader('content-length', fileRef.size || 0);

    s3.getObject({
      Bucket: s3Conf.bucket,
      Key: path
    }).createReadStream().on('error', (err) => {
      bound(() => {
        console.error(err);
      });
    }).pipe(http.response);

    return true;
  }

  return false;
}
```

**Comment by dr-dimitru** [comment]
@izaa please tell us how it ends for you? Have you made it work?

**Comment by izaa** [comment]
So far, only this works good enough. I have Amazon CloudFare since without CloudFare it didn't work quite good. Still looking for better approach :)

```
    interceptDownload(http, fileRef, version) {
      let path = (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) ? fileRef.versions[version].meta.pipePath : void 0;

      if (path) {
     const opts = {
          Bucket: s3Conf.Bucket,
          Key: path
        };


        request(Meteor.settings.private.AWS.CloudFrontURL + path).pipe(http.response);
        return true;
      }
      // While file is not yet uploaded to AWS:S3
      // It will be served file from FS
      return false;
    }, // interceptDownload

```

**Comment by dr-dimitru** [comment]
@izaa you mean CloudF**l**are, right? Or CloudFront only?

**Comment by izaa** [comment]
@dr-dimitru sorry, CloudFront, i edited the post. I think my videos are too large, so now i'm configuring Elastic Transcoder to after upload -event.

**Comment by dr-dimitru** [comment]
> I think my videos are too large

Like what large? I think size not that matter as bitrate.

**Comment by izaa** [comment]
Actually Galaxy is not the problem. If i'm not doing request(..).pipe(..) the viedos might not play at all or it takes too much time even my localho dev environment. I'll investigate.

**Comment by dr-dimitru** [comment]
From the [current example](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration) - [`.serve()` ](https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1776) will do piping for you, but also will take care about chunks, as it's required for time-seeking in streaming files, like video and audio
