### ISSUE TITLE
Support for meteorhacks:cluster

### ISSUE THREAD

**Issue by davidyaha** [VeliovGroup/Meteor-Files#51]
It would be great if the client methods and the server methods would have been different packages and I could specify the cluster node to upload files to.

Check out https://github.com/meteorhacks/cluster#microservices for more info about cluster and micro-services.

Thanks for the package!

**Comment by dr-dimitru** [comment]
Hi @davidyaha ,
 - For server only usage you may define File.Collection only on server. But you can not do same thing for client only. But what functionality you wish to have on client only?
 - Microservices... - in my experience we used to have separated "mini"-apps which shares same DB or host or something else similar. I see no issues why you can not do microservice with Meteor-Files package now. Please ensure what you exactly can not implement.

Thank you for using this package. If you found this driver useful do not hesitate to star it at both github and atmosphere. Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Expressive%20file-management%20in%20%23Meteor%20via%20%40veliovgroup) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

**Comment by dr-dimitru** [comment]
BTW about [cluster package](https://github.com/meteorhacks/cluster#microservices) - I don't like theirs concept. Basically they re-invent things which already exists and trusted in front of developers and system administrators. Like nginx, HAProxy, AWS ELB - I'm and thousands of devops can stand for theirs reputation, at least they are have longer history.

We're in our production using stack of `User` `->` `AWS ELB` (cloud) `->` `HAProxy` (cluster) `->` `Nginx` (Host VM) `->` `Phusion Passenger` (Client VM) `->` `Node`. Uptime guaranteed.

**Comment by davidyaha** [comment]
Hi @dr-dimitru 
In my implementation I would like a micro service to have different DB than the ui-provider micro service.
https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L878
The Meteor.call in this line could also be changed to some kind of an abstraction that will allow changing the default DDP connection that Meteor.call uses.

I really like the DDP upload in this package and I would like to upload through DDP a file to be analysed on a micro service that handles this kind of background work only.

I could also send the file through the web micro service to the analyser micro service but that also means that I need to implement your logic by myself and it doesn't seem to me like a good thing.

About this package being not the best at load balancing, I totally agree. But, I use it a service discovery more than a LB and while there are solutions out there for it like eureka or zookeeper, having this kind of service integrated into meteor opens up some very cool possibilities. One of them I am currently writing in a branch of Zodiac - https://github.com/GuildOfProgrammers/Zodiac/tree/feature/microservices

That being said, I do think that I might need to rewrite some or the cluster package, but for now it will do.

P.S. Already starred :) 
Once I'll finish my current project that uses it, I'll post about this package, guaranteed.

**Comment by dr-dimitru** [comment]
@davidyaha thank you )
I hope to put my hand on your suggestion soon. I'll let you know

**Comment by dr-dimitru** [comment]
Finally done in [`v1.7.4`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.4)

**Comment by dr-dimitru** [comment]
Please check on your end
