### ISSUE TITLE
Http upload transport problem

### ISSUE THREAD

**Issue by livimonte** [VeliovGroup/Meteor-Files#511]
Hi @dr-dimitru , 

I'm trying to change the upload transport to http, but i always get the same problem: nothing happen with zero logs on client/server after 'onStart'. And after a long time, i get the error: 'Error: network'.

My upload works fine with DDP, i use macOS Sierra, chrome, Meteor 1.5.2.2, ostrio 1.8.3 and i tried: 
  Update ostrio to 1.9.0;
  Update meteor-node-stubs to 0.3.2;
  Change 'stream' and 'chunkSize' values to dynamic or streams: 1, chunkSize: 102400;
  Change allowWebWorkers to true/false;
  Change server debug to true/false;
  Change continueUploadTTL to a larger time;
  Change allowClientCode to true/false;
  Upload diferent files, sizes and formats (upload is only for images);
  
Any ideas?

![start](https://user-images.githubusercontent.com/1934765/31844831-10a3ea10-b5da-11e7-8fd3-0bd3a29758cf.png)
![error](https://user-images.githubusercontent.com/1934765/31844832-10c6c36e-b5da-11e7-9d9b-4b5b12511a03.png)

**Comment by dr-dimitru** [comment]
Hello @livimonte ,

Please follow our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Post *Client* and *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by dr-dimitru** [comment]
And do you get the same error using HTTP upload at [our demo app](https://files.veliov.com)?

**Comment by livimonte** [comment]
Hi @dr-dimitru , follows the client and server logs.

Client
![screen shot 2017-10-21 at 01 19 45](https://user-images.githubusercontent.com/1934765/31847913-396e8b1a-b604-11e7-8b8b-ed53dcc60edf.png)

Server
![screen shot 2017-10-21 at 01 20 18](https://user-images.githubusercontent.com/1934765/31847915-435d3a9a-b604-11e7-8a6f-9c3f2fd259f9.png)

The demo app worked, with ddp and http. I've tried the following code: (client-server) and dependency versions, the only differences I found are the headers and the path to upload (/Users/myuser/ jobs/ clients/proj/site/ app/ uploads/ histories) i also checked the folder permissions (ok) and also, it works fine with ddp.

Follow the printouts of __upload headers:

My App
![screen shot 2017-10-21 at 01 35 24](https://user-images.githubusercontent.com/1934765/31847919-56dfc330-b604-11e7-976c-6a11200df36a.png)
![screen shot 2017-10-21 at 01 42 41](https://user-images.githubusercontent.com/1934765/31847922-5c2faf4e-b604-11e7-92a7-6946a7c06fc0.png)

 Demo
![screen shot 2017-10-21 at 02 07 22](https://user-images.githubusercontent.com/1934765/31847927-9cc2f19c-b604-11e7-9455-dbdbce644e67.png)


Client/Server Code
![screen shot 2017-10-21 at 02 03 01](https://user-images.githubusercontent.com/1934765/31847933-cf83eafa-b604-11e7-8f96-d98b7d17449d.png)
![screen shot 2017-10-21 at 02 00 53](https://user-images.githubusercontent.com/1934765/31847934-cfa8eda0-b604-11e7-9154-f4e87f996a3d.png)

**Comment by dr-dimitru** [comment]
@livimonte thank you for update.
Could you post contents of `./meteor/packages` file?

**Comment by livimonte** [comment]
Follow:

## Meteor
meteor-base@1.1.0
ecmascript@0.8.3
es5-shim@4.6.15
check@1.2.5
tracker@1.1.3
random@1.0.10
mongo@1.2.2
http@1.2.12
shell-server@0.2.4
session@1.1.7
blaze-html-templates@1.0.4
dynamic-import@0.1.3

## Standard
email@1.2.3
lookback:emails
jquery@1.11.10
underscore@1.0.10
underscorestring:underscore.string
rzymek:moment-locale-pt-br
aldeed:moment-timezone
u2622:persistent-session
reactive-var@1.0.11
reactive-dict@1.1.9
fourseven:scss
#juliancwirko:postcss
seba:minifiers-autoprefixer


## Data
aldeed:simple-schema
aldeed:collection2
dburles:collection-helpers
alanning:roles
mdg:validated-method
mdg:validation-error
meteorhacks:subs-manager
#meteorhacks:fast-render
reywood:publish-composite
meteorhacks:aggregate
jcbernack:reactive-aggregate


## Helpers
meteorhacks:ssr
meteorhacks:unblock
#kit:basic-auth
raix:handlebar-helpers
aldeed:template-extension
djedi:sanitize-html
pcel:serialize
ostrio:meteor-root
chrismbeckett:toastr

## Routing
kadira:flow-router@2.11.0
kadira:blaze-layout
arillo:flow-router-helpers
zimme:active-route
meteorhacks:picker


## Accounts
accounts-ui@1.1.9
useraccounts:unstyled
useraccounts:flow-routing
accounts-password@1.4.0
accounts-facebook@1.2.1
service-configuration@1.0.11
facebook-config-ui@1.0.0


## SEO
meteorhacks:inject-initial
mdg:seo
kadira:dochead

## Production
standard-minifier-js@2.1.2
ddp-rate-limiter@1.0.7
mixmax:smart-disconnect

## Upload
ostrio:templatehelpers
ostrio:files

## Others
#bundle-visualizer

**Comment by dr-dimitru** [comment]
Move 

```
## Upload
ostrio:templatehelpers
ostrio:files
```

Right above:
```
## Routing
kadira:flow-router@2.11.0
```

**Comment by dr-dimitru** [comment]
Also I would like to see headers and response of failed request:

![screen shot 2017-10-21 at 4 15 22 pm](https://user-images.githubusercontent.com/1686778/31852148-503009c4-b67b-11e7-91ab-0cfc5dda15f7.png)

**Comment by livimonte** [comment]
It works !!

Changing the order i found an error with the meteorhacks:picker. The problem is in the use of the midware bodyParser.json() with the Picker, if I comment this line the upload with http works:

Does not work:
const bodyParser = require ('body-parser');
Picker.middleware (bodyParser.json ());
Picker.middleware (bodyParser.urlencoded ({extended: false}));

Works:
const bodyParser = require ('body-parser');
//Picker.middleware (bodyParser.json ());
Picker.middleware (bodyParser.urlencoded ({extended: false}));

I thought it might be the limit, but that did not work:
const bodyParser = require ('body-parser');
Picker.middleware (bodyParser.json ({limit: 60000000}));
Picker.middleware (bodyParser.urlencoded ({extended: false, limit: 60000000}));

Do you know what it could be and if have a way to work using bodyParser?

Thanks and about the header response, it fails:

![screen shot 2017-10-21 at 12 01 43](https://user-images.githubusercontent.com/1934765/31852575-c2a982a0-b658-11e7-9bb4-6011a57e5863.png)

![screen shot 2017-10-21 at 12 01 55](https://user-images.githubusercontent.com/1934765/31852577-c6a2404a-b658-11e7-998b-cb60dcb1f819.png)

**Comment by dr-dimitru** [comment]
> It works !! Changing the order

Awesome! :)
Order affects the order of middleware being registered.
And some packages like picker or SSR or routinf doesn't fully follows middleware convention and not passing request further to other middleware(s)

> The problem is in the use of the midware bodyParser.json() with the Picker
> Do you know what it could be and if have a way to work using bodyParser?

No idea, I've never faced the picker nor `body-parser` lib, you're better to nock into theirs issues.

**Comment by livimonte** [comment]
No problem, I'll take a look there ;)

Many thanks @dr-dimitru , congratulations for the great package and good work you do on your projects.

**Comment by dr-dimitru** [comment]
@livimonte thank you a lot for feedback, it means a lot :)
And I'm glad this issue is solved.


Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by think-in-data** [comment]
@dr-dimitru  hello, I met almost the issue with the same phenomenon in my project, when I'm trying to enable the "HTTP" transport , with error below from browser console.  Any ideas about how to fix that?

![image](https://user-images.githubusercontent.com/26931875/38465944-56c2f856-3b54-11e8-8eac-b57e3fce8fd3.png)

environment:
- meteor: Meteor 1.4.3.1
- Meteor Files: ostrio:files@1.7.11
- OS: Mac High Sierra, 10.13.1
- browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)

.meteor/packages

```
# meteor libraries
meteor-base@1.0.4
ecmascript@0.6.3
es5-shim@4.6.15
check@1.2.4
tracker@1.1.2
session@1.1.7

# standard libraries
jquery@1.11.10
underscore@1.0.10
less@2.7.9

# ui
static-html@1.1.12_1
react-meteor-data
simple:highlight.js

# network
http@1.2.11

# data
mongo@1.1.15
aldeed:simple-schema
aldeed:collection2
dburles:collection-helpers
reywood:publish-composite
mdg:validated-method
mdg:validation-error
meteorhacks:aggregate

# file system
ostrio:files

# i18n
universe:i18n

# accounts
accounts-password@1.3.4

# mobile
crosswalk@1.7.1
mobile-experience@1.0.4
chriswessels:hammer

# production
juliancwirko:postcss@1.0.0-beta.11
standard-minifier-js@1.2.2
ddp-rate-limiter@1.0.6
app-prod-security

# rest apis
simple:rest-accounts-password
simple:rest

# testing
factory
publication-collector
xolvio:cleaner
dispatch:mocha-phantomjs
practicalmeteor:mocha@2.1.1-rc.1
hwillson:stub-collections

# debugging
msavin:mongol

# search
easy:search

```

**Comment by think-in-data** [comment]
@dr-dimitru Now I tried to find workarounds. It seems the "upload with HTTP" only works after I remove both the **simple:rest** and **simple:rest-accounts-password** packages from the project. 

But these two packages are necessary for my current feature. The reason is explained as below (I may be wrong). 

Besides the issue when switching the transport mode to "HTTP" at client, I'm also working on exposing HTTP endpoint to support file upload with cURL for Meteor Files, and also enable rest APIs for other Meteor Collections in my project. 

**simple:rest** seems to be a good solution for setting up rest APIs for publications, methods, and Collections, but I'm not sure it's the best way to enable file uploading with HTTP for Meteor-File backed project. 

That's why I'm using the **simple:rest** package here to serve my above needs, which unfortunately seems to be conflicted with **ostrio:files** in HTTP transport mode. 

If you guys have any recommended suggestions, you're very welcome. 😄

**Comment by dr-dimitru** [comment]
@think-in-data 

> Now I tried to find workarounds. It seems the "upload with HTTP" only works after I remove both the simple:rest and simple:rest-accounts-password packages from the project.

Such packages intercept all incoming requests. Ways to solve:

 1. Place `ostrio:files` package higher then such packages in the `.meteor/packages` file
 2. Register collections (run `new FilesCollection({/* ... */})`) before `Meteor.startup()` callback
 3. Register same route in a such packages as it used in `ostrio:files` for http upload, and just pass (*usually calling* `next()`) to the next middleware handler.

**Comment by livimonte** [comment]
I also had some problems with https and i am using ddp now. I vote to keep ddp.

**Comment by think-in-data** [comment]
@dr-dimitru thanks for solutions. Do I need to do all the 3 steps, or either one should work?

In my `.meteor/packages` file, the `ostrio:files` is above `simple:rest`, but it doesn't work unless I remove the `simple:rest` packages.

**Comment by think-in-data** [comment]
@livimonte @dr-dimitru good to know. thanks 👍  I think it's fine to keep DDP for `insert` method at client. 

Regarding uploading file from non-meteor HTTP client, e.g. cURL, to a Meteor server with Meteor Files, do you know any best practice? I'm experimenting with `simple:rest` for such a feature.

**Comment by dr-dimitru** [comment]
@think-in-data 

> I saw the resolved issue on #206, but does it really work well for large files like 1GB?

Why? Our library supports upload of files of any sizes, through all upload protocols

**Comment by think-in-data** [comment]
@dr-dimitru it looks like that example will consume significant memory when read/write file into Meteor-Files, and it bypass the chunk-level upload process implemented by Meteor Files.

The example from [https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js](https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js)

```js
_fs.readFile(req.file.path, function (_readError, _readData) {
            if (_readError) {
              console.log(_readError);
            } else {
              Avatars.write(_readData, _addFileMeta, function (_uploadError, _uploadData) {
                if (_uploadError) {
                  console.log(_uploadError);
                } else {
                  console.log('upload data=', _uploadData); 
                  _fs.unlink(req.file.path); // remove temp upload
                }
              });
            }
          });
```

**Comment by livimonte** [comment]
@think-in-data about the simple:rest problem, i never used it but the problem i had with picker (server-side routes) was that it run in all routes and it don't work well with uploads. When i filter the upload routes, it works. Here is the code i used with picker: 

```javascript
let postRoutes = Picker.filter(function(req, res) {
  return req.method == "POST" && req.url.indexOf('__upload') === -1;
});

//Apply middlewares after filter
postRoutes.middleware( bodyParser.json({limit:'500kb'}) );
postRoutes.middleware( bodyParser.urlencoded( { extended: false } ) );
```

**Comment by dr-dimitru** [comment]
@think-in-data for chunked upload you will need to write a client which can split a file into chunks and manage an upload.

For inspiration you may take a look on [python-based solution](https://github.com/VeliovGroup/meteor-python-files). You can use this repository to upload files, instead of cURL from any Linux environment (*but script requires little changes to work from CLI*).

**Comment by think-in-data** [comment]
@livimonte thanks a lot! That brings good insight for the issue I met I think. 😆

**Comment by think-in-data** [comment]
@dr-dimitru thanks so much! I think that `meteor-python-files` solution should work well for file upload from any client machines. 😄 I'll have a try. 

But my project requires a rest API that can be used from any cURL-like HTTP client. I may add some extra handling on server side similar to what the example did and pay attention to memory usage:  [https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js](https://github.com/noris666/Meteor-Files-POST-Example/blob/master/avatars.example.js)
