### ISSUE TITLE
Unable to find folder when '/uploads/files' is passed to config.storagePath

### ISSUE THREAD

**Issue by Gigacross** [VeliovGroup/Meteor-Files#512]
### Unable to find `/uploads/files` directory in `config.storagePath : '/uploads/files'`

According to the documentation, I should be able to find the directory that stores all the uploaded files if you pass an absolute path into `config.storagePath`. 

My file looks like this: 

```
const ExcelFiles = new FilesCollection({
  storagePath: '/uploads/excel',
  downloadRoute: '/files/excel',
  collectionName: 'ExcelFiles',
  permissions: 0755,
  allowClientCode: false,
  cacheControl: 'public, max-age=31536000',
  debug: true,
  // Read more about cacheControl: https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers
  onbeforeunloadMessage() {
    return 'Upload is still in progress! Upload will be aborted if you leave this page!';
  },
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    // Note: You should never trust to extension and mime-type here
    // as this data comes from client and can be easily substitute
    // to check file's "magic-numbers" use `mmmagic` or `file-type` package
    // real extension and mime-type can be checked on client (untrusted side)
    // and on server at `onAfterUpload` hook (trusted side)
    // if (file.size <= 10485760 && /png|jpe?g/i.test(file.ext)) {
    if (file.size <= 10485760 ) {
        
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  },
  downloadCallback(fileObj) {
    if (this.params.query.download == 'true') {
      // Increment downloads counter
      Images.update(fileObj._id, {$inc: {'meta.downloads': 1}});
    }
    // Must return true to continue download
    return true;
  },
  // protected(fileObj) {
  //   // Check if current user is owner of the file
  //   if (fileObj.meta.owner === this.userId) {
  //     return true;
  //   } else {
  //     return false;
  //   }
  // }
});

// Export FilesCollection instance, so it can be imported in other files
export default ExcelFiles;
```
Turned on `config.debug : true`

In my windows console, I'm getting: 

```
I20171026-18:11:53.722(8)? [FilesCollection.storagePath] Set to: /uploads/excel
=> Meteor server restarted
I20171026-18:11:54.269(8)? [FilesCollection] [find({}, undefined)]
I20171026-18:11:58.490(8)? [FilesCollection] [find({}, undefined)]

```
Am I supposed to be able to actually see a folder being created in the root path of dev environment? 

![rootdirstructure](https://user-images.githubusercontent.com/441611/32048013-7e35cb8a-ba7a-11e7-9f56-76540cc226cf.JPG)

No folder is created. However I am still able to download the file after restarting the server, that means the storagePath remains persistent. 

Currently I am developing on windows with the following packages on **Meteor 1.5.2.2**.

> accounts-password                 1.4.1* Password support for accounts
> alanning:roles                    1.2.16  Authorization package for Meteor
> blaze-html-templates              1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
> ecmascript                        0.8.3  Compiler plugin that supports ES2015+ in all .js files
> es5-shim                          4.6.15  Shims and polyfills to improve ECMAScript 5 support
> johanbrook:publication-collector  1.0.10  Test a Meteor publication by collecting its output.
> kadira:blaze-layout               2.3.0  Layout Manager for Blaze (works well with FlowRouter)
> kadira:flow-router                2.12.1  Carefully Designed Client Side Router for Meteor
> less                              2.7.9  Leaner CSS language
> materialize:materialize           0.100.2  Materialize (official): A modern responsive front-end framework based on Material Design
> meteor-base                       1.1.0  Packages that every Meteor app needs
> mobile-experience                 1.0.5  Packages for a great mobile user experience
> mongo                             1.2.2  Adaptor for using MongoDB and Minimongo over DDP
> ostrio:files                      1.9.0  File upload via DDP/HTTP to server FS, AWS, GridFS, DropBox, Google Drive or other 3rd party storage
> practicalmeteor:mocha             2.4.5_6  Write package tests with mocha and run them in the browser or from the command line with spacejam.
> reactive-var                      1.0.11  Reactive variable
> session                           1.1.7  Session variable
> shell-server                      0.2.4  Server-side component of the `meteor shell` command.
> standard-minifier-css             1.3.5  Standard css minifier used with Meteor apps by default.
> standard-minifier-js              2.1.2  Standard javascript minifiers used with Meteor apps by default.
> tracker                           1.1.3  Dependency tracker to allow reactive callbacks
> underscore                        1.0.10  Collection of small helpers: _.map, _.each, ...
> useraccounts:flow-routing         1.14.2  UserAccounts package providing routes configuration capability via kadira:flow-router.
> useraccounts:materialize          1.14.2  Accounts Templates styled for Materialize Css.

**Comment by inromualdo** [comment]
I think that you should find that folder (cd /uploads/files)... **Not in your meteor projet**

**Comment by Gigacross** [comment]
Thank you! @inromualdo I found it at `<c:\>uploads\files` or in this case `<c:\>uploads\excel` according to my config file. I hope this helps another person out there developing on windows.!

**Comment by dr-dimitru** [comment]
The leading forward slash is the [__root of your computer file system__](https://en.wikipedia.org/wiki/Root_directory)

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
