### ISSUE TITLE
Question: How to get link in js

### ISSUE THREAD

**Issue by kasiula03** [VeliovGroup/Meteor-Files#513]
When I defined helper like 
`image: function() {return Images.findOne()}` 

then I can get link in html like this "{image.link}", but what about js file?
When I try display link on console:
`console.log(Images.findOne().link)` 
then I get info: "function FilesCollection.prototype.link()".
How can I get this link in my js file?

**Comment by dr-dimitru** [comment]
Hello @kasiula03 ,

TL;TR;
```js
var Images = new FilesCollection({collectionName: 'Images'});

// Usage:
Images.collection.find({}).forEach(function (fileRef) {
  Images.link(fileRef);
});

Images.findOne({}).link();
// Get thumbnail subversion
Images.findOne({}).link('thumbnail');
// Equals to above
var fileRef = Images.collection.findOne({});
Images.link(fileRef, 'thumbnail');
```


Here is docs:
 - [`.link()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/link)
 - [`.link()` on *FileCursor*](https://github.com/VeliovGroup/Meteor-Files/wiki/FileCursor)

**Comment by kasiula03** [comment]
Hi @dr-dimitru 
Looks like my helper execute twice, I got two console message, the first one is undefined, but second it's what I wanted.
Thank you :)

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by FEA5T** [comment]
Here is the sexy line you really want:

`Images.find({}).forEach(function (f) { f.link = Images.link(f); });`

Shame that `.link` isn't already a getter on the file object.

**Comment by dr-dimitru** [comment]
@FEA5T 

> Shame that .link isn't already a getter on the file object.

[😧](https://github.com/VeliovGroup/Meteor-Files/blob/master/CODE_OF_CONDUCT.md#our-standards) - [🤔](https://github.com/VeliovGroup/Meteor-Files/blob/master/CONTRIBUTING.md#i-have-a-suggestion) - Both is clickable

**Comment by FEA5T** [comment]
@dr-dimitru Huh?

**Comment by dr-dimitru** [comment]
https://github.com/VeliovGroup/Meteor-Files/blob/master/CODE_OF_CONDUCT.md#our-standards
https://github.com/VeliovGroup/Meteor-Files/blob/master/CONTRIBUTING.md#i-have-a-suggestion
