### ISSUE TITLE
How to return error from onAfterUpload method to client

### ISSUE THREAD

**Issue by koblents** [VeliovGroup/Meteor-Files#514]
Hello!

I am using your package. 
On client side, after I start upload I have handlers:

                uploadInstance.on('end', function (error, fileObj) 
                uploadInstance.on('error', function (error, fileObj) 

And on server side I have method onAfterUpload - inside this method there is a case, when I wan't to return error to client and see it in parameter ERROR in its handles, but I don't know how to do this ans didn't found solution on your wiki

- I tried to return false 
- I tried to return some text

Nothing of it I see on the client. 

Thanks

**Comment by dr-dimitru** [comment]
Hello @koblents ,

Not possible, as `onAfterUpload` is triggered asynchronously after upload is successfully finished.
Please describe your case in details, what are you trying to accomplish?

**Comment by vbelolapotkov** [comment]
@koblents you can update file doc in onAfterUpload with status/error of the file processing. 
On the client you can subscribe to file doc and observe changes to monitor after upload progress.
I used that approach to notify client when file processing (thumb creation + anti virus scanning) is completed.

**Comment by dr-dimitru** [comment]
+1 for method suggested by @vbelolapotkov 
We use the same approach in our demo app, listening for generated thumbs availability, see [code here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/listing/listing-row.js#L13), you can use any other property in the same way.

**Comment by dr-dimitru** [comment]
Hello @koblents ,

Have you solved it?

**Comment by koblents** [comment]
No, I didn't, because in my logic, if I have some error inside onAfterUpload - I immediately delete file and mongoDB row - and with it I don't know how to tell client about it.

**Comment by dr-dimitru** [comment]
@koblents inside `onAfterUpload` hook add `deleted` or `error` property, if any of those props exists on the file's record show error message and hide them. Then set [Mongo's TTL Index](https://docs.mongodb.com/manual/core/index-ttl/), file's record will be automatically removed upon expiration. See [this tutorial](https://docs.mongodb.com/manual/tutorial/expire-data/).

See similar approach used in [our demo app](https://files.veliov.com) and __very important comment__ [here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L384-L393)

Let me know if it helped you.

**Comment by koblents** [comment]
thanks @dr-dimitru I don't really like this solution, because it seems to complicated, can confuse users and also can reflect more issues.
But anyway I think we can close this issue - you gave me few solutions and if it will become critical for me, I will use one of them. 

Thanks

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
