### ISSUE TITLE
Collection.link crashes Meteor

### ISSUE THREAD

**Issue by yanickrochon** [VeliovGroup/Meteor-Files#515]
### I'm having an issue:

During some test, I have a `FilesCollection` collection instance with some missing `GridFS` files. I wanted to simulate some data loss and realized that, when this is the case, and the file is missing, the entire Meteor app crashes when I try to download the file :

```jsx
const imageLink = fooCollection.link(image);

return (<img src={ imageLink } />);
```

I'm not sure if this can actually be resolved itn this module, but I'd like so fail safe to prevent Meteor from crashing it this is the case.

**Comment by dr-dimitru** [comment]
Hello @yanickrochon ,

Please update this issue according to our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

     - Give an expressive description
     - Version of `Meteor-Files` you're experiencing this issue
     - Version of `Meteor` you're experiencing this issue
     - Is it *Client* or *Server* issue?
     - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
