### ISSUE TITLE
[Question] How to empty storagePath before uploading ?

### ISSUE THREAD

**Issue by axelvaindal** [VeliovGroup/Meteor-Files#518]
Hi,

I was experimenting with your package and find myself wanting to delete the content of the destination before uploading.
I looked inside issue & wiki, but didn't find anything appropriate.
Is this something possible with this package ?

My goal here is to prevent destination folder from increasing in size with non-used file (or legacy file).
For instance, I may upload a file whenever a user update his profile picture, but after a long time, there will be plenty of unused file in the folder which should be deleted.

I would like to be able to delete specific file (based on filename/id) and clean entire folder.
Thanks for your answer,

**EDIT:** I figured out how to clean older file in the `onAfterUpload` hook thanks to userId being passed in the file definition. Still looking for emptying destination folder if this is possible with the package.

By the way, and in order to prevent from opening other issues, I may have noticed a few irregularity about link (which sure come from my code, but can't understand why).

I upload the files in `/uploads/images/avatars/users/userId/` which works fine (I can see the files in my server FS).
However the generated link is still in the form of `localhost:3000/cdn/storage/...`.
I tried rewriting `downloadRoute` but I don't think this is the write way since now the generated link is in the form : `/uploads/images/avatars/users/collection_name/file_id/original/file_id`.

I also noted that if I use the `namingFunction`, although my file is correctly named on the FS, the link is still generated based on the file id which is a bit weird.

Can't figure myself out of this, can you enlighten me please ? 🙂 

See stack trace from debug below : 

```
I20171114-10:18:43.607(1)? [FilesCollection] [File Start Method] Avatar.jpg - sTcsMWR6ZFdYmsioC
I20171114-10:18:43.608(1)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: Avatar.jpg
I20171114-10:18:43.640(1)? [FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: Avatar.jpg
I20171114-10:18:43.651(1)? [FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: Avatar.jpg
I20171114-10:18:43.652(1)? [FilesCollection] [Upload] [finish(ing)Upload] -> /uploads/images/avatars/users/uT2oq6RqBpqLhzx8G/sTcsMWR6ZFdYmsioC.jpg
I20171114-10:18:43.656(1)? [FilesCollection] [Upload] [finish(ed)Upload] -> /uploads/images/avatars/users/uT2oq6RqBpqLhzx8G/sTcsMWR6ZFdYmsioC.jpg
I20171114-10:18:43.656(1)? [FilesCollection] [findOne({"_id":"sTcsMWR6ZFdYmsioC"}, undefined)]
I20171114-10:18:43.659(1)? [FilesCollection] [_preCollectionCursor.observe] [changed]: sTcsMWR6ZFdYmsioC
I20171114-10:18:43.662(1)? [FilesCollection] [FileCursor] [link(original)]
I20171114-10:18:43.662(1)? [FilesCollection] [link(sTcsMWR6ZFdYmsioC, original)]
I20171114-10:18:43.671(1)? [FilesCollection] [_preCollectionCursor.observe] [removed]: sTcsMWR6ZFdYmsioC
I20171114-10:18:43.675(1)? http://localhost:3000/uploads/images/avatars/users/user_avatars/sTcsMWR6ZFdYmsioC/original/sTcsMWR6ZFdYmsioC.jpg
I20171114-10:24:19.511(1)? [FilesCollection.storagePath] Set to: /uploads/images/avatars
```
Corresponding collection code:

```javascript
export const UserAvatar = new FilesCollection(
{
    collectionName: "user_avatars",
    debug: true,
    downloadRoute: "/uploads/images/avatars/users/",
    storagePath: function(file)
    {
        if (Meteor.isServer)
        {
            let fs = require("fs-extra");
            if (file && file.userId)
            {
                let path = "/uploads/images/avatars/users/" + file.userId + "/";
                fs.ensureDirSync(path);

                return path;
            }
        }

        return "/uploads/images/avatars/";
    },
    onBeforeUpload(file)
    {
        if (file.size <= AVATAR_MAX_SIZE && /png|jpg|jpeg/i.test(file.extension))
            return true;

        return "Please, upload avatar with size equal or less than 10MB!";
    },
    onAfterUpload(file)
    {
        if (Meteor.isServer)
        {
            let test = UserAvatar.findOne({_id: file._id});
            let user = User.findOne({_id: file.userId});

            if (user && test)
            {
                user.avatar = test.link();
                user.save();
            }
        }
    }
});
```

**Comment by dr-dimitru** [comment]
> wanting to delete the content of the destination before uploading.

I believe [`fs-extra`](https://www.npmjs.com/package/fs-extra) can solve it using [`.emptyDir()` method](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/emptyDir.md).

But you will also need to remove everything from database, so using *pseudo code* below:
```js
Meteor.startup(() => {
   FilesCollection#remove({});
});
```
is much easier and safer, snippet is taken [from here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L381-L382).

> My goal here is to prevent destination folder from increasing in size with non-used file (or legacy file).

Legacy files may be removed using Mongo's TTL indexes, see [related discussion here](https://github.com/VeliovGroup/Meteor-Files/issues/514#issuecomment-343980981).

> For instance, I may upload a file whenever a user update his profile picture, but after a long time, there will be plenty of unused file in the folder which should be deleted.

For this case you should remove a file using [`.remove()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/remove).

> EDIT: I figured out how to clean older file in the onAfterUpload hook thanks to userId being passed in the file definition. Still looking for emptying destination folder if this is possible with the package.

You may pass user's id into [`.remove()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/remove), to remove all user's files.

```js
FilesCollection#remove({ userId: 'xxx' });
```

> I upload the files in /uploads/images/avatars/users/userId/ which works fine (I can see the files in my server FS).
> However the generated link is still in the form of localhost:3000/cdn/storage/....
> I tried rewriting downloadRoute but I don't think this is the write way since now the generated link is in the form : /uploads/images/avatars/users/collection_name/file_id/original/file_id.
> I also noted that if I use the namingFunction, although my file is correctly named on the FS, the link is still generated based on the file id which is a bit weird.

```js
true === (storagePath !== downloadRoute !== namingFunction)
```

All `storagePath`, `downloadRoute`, and `namingFunction` is not related in any way.
Do not ever alter the way how `.link()` method works, we made it this way, to avoid reverse engineering over your server's file system structure, so it's always remains the same, whenever storage at your FS, GridFS or AWS:S3, it isn't possible to figure out.

Think of `downloadRoute` is it is a "fence" in front of real location of the file.
*Note:* there is `public` option, which alters this default behavior.

`namingFunction` only affects how files is being named at your FS, not generated link. It allows to create "infinitely" directory inherence to avoid hitting max allowed files/dirs in single directory.


@axelvaindal let me know if this is helpful, or you need more info.

**Comment by axelvaindal** [comment]
@dr-dimitru Thanks for all your answers, this is quite explicit !

I have no further questions concerning the emptying of the destination path, `Mongo TTL indexes` and `FilesCollection#remove` method will do the trick.

Concerning the difference between the 3 config options, I think I get the most of it.
Based on your explanations, I understand this : 

- `storagePath` : Define the files location after they are uploaded (final destination path on the FS).
- `namingFunctionè : Only allow file renaming on the FS
- `downloadRoute`:  This is NOT the real location of the file, only a _safe passage_ to get the file without exposing the true nature of the file system (no way of knowing if we use server FS, GridFS,AWS:S3).

So, based on this explanations, if I put my files outside of my meteor project directory (i.e an absolute path `/uploads/images/*`) and update my user avatar link when the file is finished uploading with the `link()` method, I should be able to pass the path generated to a `src` attribute of an `<img />` tag and see my image displayed ?

```
onAfterUpload(file)
    {
        if (Meteor.isServer)
        {
            let avatar = UserAvatar.findOne({_id: file._id});
            let user = User.findOne({_id: file.userId});

            if (user && avatar)
            {
                user.avatar = avatar.link();
                user.save();
            }
        }
    }

// in any React component

<img src={this.props.user.avatar} />
```

However, the generated link for avatar is still this one : 
`http://localhost:3000/cdn/storage/user_avatars/6XDx4B8vwpYWnA4Lm/original/6XDx4B8vwpYWnA4Lm.jpg` and I get the `net::ERR_CONNECTION_REFUSED` error.

I use default publication (which publish everything about the UserAvatar FilesCollection) and subscribed correctly. My `storagePath` is chmoded 777 to be sure this is not about permissions.

There must be a misunderstanding somewhere, but can't find out.

**Comment by dr-dimitru** [comment]
1. Is the `http://localhost:3000` right domain?
 2. Make sure `ROOT_URL` env.var is properly set

To find out the roots of the `net::ERR_CONNECTION_REFUSED`, we need:
 1. "DevTools" -> "Network" -> "Headers" tab screenshot of the failed request
 2. One more time Server and Client "debug" logs
 3. And try to put `ostrio:files` package on top of `.meteor/packages` file, right after default packages (which has no `:` colon), perhaps some other package (like *routing*) registered catch-all middleware and not passing it to the next handler.

**Comment by axelvaindal** [comment]
1. Yes, this is my dev environment.
2. Tried export ROOT_URL with correct value and the `ROOT_URL=http://localhost:3000 meteor` syntax with no differences

net::ERR_CONNECTION_REFUSED related debug information:

1.
 ![image](https://user-images.githubusercontent.com/11026659/32895091-302bc8fc-cadf-11e7-8fae-159137e8c1af.png)

2.
Server log: 
```
// On app loading
[FilesCollection.storagePath] Set to: /uploads/images/avatars
// On image upload (which works fine)
I20171116-14:59:15.241(1)? [FilesCollection] [File Start Method] Avatar.jpg - JkgTYGuPkESXgWMYN
I20171116-14:59:15.242(1)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/1 chunks, dst: Avatar.jpg
I20171116-14:59:15.278(1)? [FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: Avatar.jpg
I20171116-14:59:15.287(1)? [FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: Avatar.jpg
I20171116-14:59:15.287(1)? [FilesCollection] [Upload] [finish(ing)Upload] -> /uploads/images/avatars/users/J9xSmYsSdQRz4FXhC/JkgTYGuPkESXgWMYN.jpg
I20171116-14:59:15.291(1)? [FilesCollection] [Upload] [finish(ed)Upload] -> /uploads/images/avatars/users/J9xSmYsSdQRz4FXhC/JkgTYGuPkESXgWMYN.jpg
I20171116-14:59:15.291(1)? [FilesCollection] [findOne({"_id":"JkgTYGuPkESXgWMYN"}, undefined)]
I20171116-14:59:15.293(1)? [FilesCollection] [_preCollectionCursor.observe] [changed]: JkgTYGuPkESXgWMYN
I20171116-14:59:15.295(1)? [FilesCollection] [FileCursor] [link(original)]
I20171116-14:59:15.296(1)? [FilesCollection] [link(JkgTYGuPkESXgWMYN, original)]
I20171116-14:59:15.302(1)? [FilesCollection] [_preCollectionCursor.observe] [removed]: JkgTYGuPkESXgWMYN

```

Client log: 
```
XHR finished loading: GET "http://192.168.1.200:3000/sockjs/info?cb=3ghzwqkxie".
GET http://localhost:3000/cdn/storage/user_avatars/JkgTYGuPkESXgWMYN/original/JkgTYGuPkESXgWMYN.jpg net::ERR_CONNECTION_REFUSED
```

3. Put the package name where specified but didn't change anything in result.

**Comment by dr-dimitru** [comment]
On a server you should have incoming request for a file. But it isn't there.
This means some other package (like routing) registered catch-all middleware and not passing it to the next handler.

 1. What do you use for routing? FlowRouter?
 2. Do you use `Picker` package?
 3. On a Server - register *FileCollection* as soon as possible, and before any other server routes.

**Comment by axelvaindal** [comment]
I indeed use FlowRouter for routing.
My `server.js` file looks like this (no server routes are defined) : 

```
import { Meteor } from "meteor/meteor";

import "./collections.js"; // This import the FilesCollection instance named UserAvatar
import "./hooks.js";
import "./methods.js";
import "./publications.js";

if (Meteor.isServer)
{
	Meteor.startup(() =>
	{
  		console.info("Yggdrasill Server running.");
	});
}
```

I do not use Picker.

**Comment by dr-dimitru** [comment]
@axelvaindal  Well everything looks very good, and should work properly.

 1. What happens when you're trying to access file directly by generated URL? Like `http://localhost:3000/cdn/storage/user_avatars/JkgTYGuPkESXgWMYN/original/JkgTYGuPkESXgWMYN.jpg`
 2. Have you tried other browsers?

Could you please also tell me more about your environment?:
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?

**Comment by axelvaindal** [comment]
@dr-dimitru That is what I thought as well, but still not working 😄.

1. I get the same error than when trying to process the request through the browser (ERR_CONNECTION_REFUSED).
2. Just tried Mozilla Firefox & Edge latest version. The problem is the same.

Informations : 

- Meteor Files version : `Meteor-Files@1.9.1`
- Meteor version : `meteor@1.6.0`
- OS : Windows 10 64 bit in Google Chrome v62, Mozilla Firefox v57, Microsoft Edge v40.

See header output from Firefox below : 

![image](https://user-images.githubusercontent.com/11026659/32915314-bcdfd64c-cb18-11e7-9a36-906a5ce721ae.png)

**Comment by dr-dimitru** [comment]
> sorry again for wasting your time

No worries, happy to help.
This is common issue, that's why I'm always asking about `ROOT_URL`, but in your case it was set, but you had to change it to your local IP, or maybe it's ok for Windows?

 - Galaxy: Not personally, it works fine, but you need to remember it has no persistent storage (*as I remember*), so you will need to use GridFS, AWS or some other 3rd party storage
 - It depends...
     1. Yes, node is not the best file-serving solution, but what if you need to control an access to the files?
     2. Using CloudFlare will give you all benefits of CDN features, no need to upload files to CDN's storage.

**Comment by axelvaindal** [comment]
Actually, my localhost:3000 usually refers to my local machine when I'm running `meteor` on my computer, but currently I am using a dedicated server in my local network which has the 192.168.1.200 IP address, thus the confusion in my mind (completely forgot I was running `meteor` command through SSH & SFTP).

We are using Galaxy in prod (and works fine until now), but I am a bit concerned about pushing file uploading to production right now without any further research on how best handle files with CDN.
I believe I remember the `Meteor Guide` recommends using CloudFront from AWS to serve public file and bundled files (such as JS & CSS), but I never used it myself, so this need further research about uploaded file. If the file are automatically fetched from the Galaxy container, uploading them as I do will be sufficient considering whenever the upload is done, the CDN will get the file and download it to server for other people around the world (thus no local access will be done, always through the CDN).
This needs confirmation though.

Anyway, this is not issue related, so I think we can close this now 🙂.

**Comment by dr-dimitru** [comment]
👍 
Feel free to reopen it in case if the issue still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
