### ISSUE TITLE
Allow returning custom Meteor.Error from onBeforeUpload hook

### ISSUE THREAD

**Issue by axelvaindal** [VeliovGroup/Meteor-Files#519]
Hi,

I just tried to customize error message sent from the `onBeforeUpload` hook to match my current architecture design, and it seems that it's only allowed to customize the message sent.
For instance:

```
onBeforeUpload(file)
{
        if (file.size <= MAX_SIXE)
            return true;

        return "File size is not correct.";
}

// which display the following error in my browser console
{
    details: undefined
    error : 403 
    errorType : "Meteor.Error"
    isClientSafe: true
    message: "File size is not correct. [403]"
    reason: "File size is not correct. [403]"
}
```

My goal here is to be able to send my own `Meteor.Error` because I use an handwritten module which is able to handle specific error code.
On server, my `Logger` generates a `Meteor.Error` based on a code and throws it.
On client, my `Logger` catches the generated `Meteor.Error` and, (if the code is recognized!) displays it in a an alert box in my UI.

The problem here is that if I execute the code below, I don't have access to my custom error message and code, and thus my error box is not displayed. 

```
onBeforeUpload(file)
    {
        if (file.size <= AVATAR_MAX_SIZE && Validator.isImage(file))
            return true;

        Logger.error(ErrorCode.IMPROPER_AVATAR);
    },

// Output
{
    details: undefined
    error : 403 // This code doesn't exist for my Logger & this is not the Logger specified code
    errorType : "Meteor.Error"
    isClientSafe: true
    message: "collection.onBeforeUpload() returned false [403]" // this is not my custom message
    reason: "collection.onBeforeUpload() returned false" // this is not my custom message
}
```
 
This is not actually a bug, but more an improvement suggestion for returning custom `Meteor.Error` in the `onBeforeUpload` hook.
I suppose that the current behavior must be : 

- If the `onBeforeUpload` return true, then continue upload
- If it returns anything else, check if string is provided and pass it to an internally generated `Meteor.Error` (if no string is passed, just return default `Meteor.Error`)

Is it possible to check if a `Meteor.Error` has already been thrown and rethrowing it if it's the case ?
This would allow error customization for whoever wants a specific error handling usage.

**Comment by dr-dimitru** [comment]
Hello @axelvaindal ,
Sorry for delay, somehow I've missed this ticket.

Have you tried to catch error in `onError` or `onEnd` event in [`.insert()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))?

**Comment by axelvaindal** [comment]
Hi @dr-dimitru, no worries 🙂.

Actually, it seems catching is not necessary.
My quoted code is actually working exactly as it should.
Subtil difference between working and not working code is here : 

```javascript
// NOT WORKING
if (file.size > AVATAR_MAX_SIZE || Validator.isImage(file))
            return Logger.error(ErrorCode.IMPROPER_AVATAR);

// WORKING
if (file.size > AVATAR_MAX_SIZE || Validator.isImage(file))
            Logger.error(ErrorCode.IMPROPER_AVATAR);
```

This is actually expected behavior since `Logger.error` throws directly the Meteor error without returning it (i.e return is `undefined`). This is why my code wasn't working and my personal issue is resolved.

However, perhaps this may be interesting for some other cases.
If we return the Meteor.Error directly (without throwing it), previous behavior is confirmed.

I tried to catch error using : 

```
onError(error)
    {
        try {

        } catch (e) {
            console.log(e);
        }
    }
```

but I'm not sure this was what you wanted me to test.
The real question here is : what if the user want to prepare a `Meteor.Error` by himself and let your package throws it ?
I think this is unlikely, considering I actually throws it myself because I have a personal module for this (and I suppose other people as well), but this is worth mentioning I couldn't catch the error properly in this case.
Should I try anything else to help dig deeper in this particular behavior or this is irrelevant and we should consider this issue closed ?

**Comment by dr-dimitru** [comment]
I meant "catch" in spoken form:
```js
onError(error) {
       // do what you need with an error
}
```

> The real question here is : what if the user want to prepare a Meteor.Error by himself and let your package throws it ?

Package wouldn't throw an error inside `onBeforeUpload`, error will be redirected into `onError` hook, and then into `onEnd`.

Closing it for now.

**Comment by axelvaindal** [comment]
Well, yeah completely tried that.
If the `onBeforeUpload` return anything else than true or string, the default error is in the `error` var.

Thus, if I do following code, everything works fine:  

```javascript
// in collection design
onBeforeUpload()
{
    throw new Meteor.error(code, message);
}

// in upload manager
onError(error)
{
    console.log(error); // error is the correct error
    Logger.displayError(error); // Working well, everything is fine for me.
}
```` 

But if I do following code, this is not working : 

```javascript
// in collection design
onBeforeUpload()
{
    return new Meteor.error(code, message);
}
// in upload manager
onError(error)
{
    console.log(error); // error is the default error (i.e [403] ... returned false ...)
    Logger.displayError(error); // Not working cause error.err & err.reason are not as expected
}
```` 

Based on what you just said : 
> Package wouldn't throw an error inside onBeforeUpload

Should I update my `onBeforeUpload` code and **not** use `throw Meteor.error` in this context ? 😕

**Comment by dr-dimitru** [comment]
> Should I update my onBeforeUpload code and not use throw Meteor.error in this context ? 😕

Right, you can `return "IMPROPER_AVATAR"`:

```js
// in collection design
onBeforeUpload()
{
    return message;
}
// in upload manager
onError(error)
{
    console.log(error);
    Logger.displayError(error);
}
```

Or in your case:
```js
// in collection design
onBeforeUpload()
{
    return 'IMPROPER_AVATAR';
}
// in upload manager
onError(error)
{
    console.log(error);
    Logger.displayError(ErrorCode[error]);
}
```

**Comment by axelvaindal** [comment]
Well, that is not how Logger was meant to be 😕.
It is supposed to use a `Meteor.Error` because this is also what I use in methods and subscription, and because message/criticality/type of error are fetched based on code and stored server side as a `SystemError` (which we can track for statistics usage, issue tracking and more) thanks to `Logger.error`.

`Logger.displayError` is a function made to simply store the generated `Meteor.error` into a client side collection for UX only. This is not really convenient to fetch error message twice as this could be done once & only once (when generating the `Meteor.error` in the first place).

What is the reason I **should not** throw a `Meteor.error` from `onBeforeUpdate` ? 🙂

**Comment by dr-dimitru** [comment]
> It is supposed to use a `Meteor.Error`

I guess it can be done this way:
```js
// in collection design
onBeforeUpload()
{
    return 'IMPROPER_AVATAR';
}
// in upload manager
onError(error)
{
    console.log(error);
    Logger.displayError(new Meteor.Error(code, ErrorCode[error]));
}
```

> What is the reason I should not throw a Meteor.error from onBeforeUpdate ? 🙂

No need to interrupt main thread, or catch exception in other place. From the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw):

> If no catch block exists among caller functions, the program will terminate.

**Comment by axelvaindal** [comment]
Alright, will be doing it this way then.
Thanks for your answers !
