### ISSUE TITLE
Error while uploading a base64 encoded file using a Meteor Method.

### ISSUE THREAD

**Issue by badis** [VeliovGroup/Meteor-Files#521]
Here is the code of a method used in server:

```
export const insertImage = new ValidatedMethod({
  name: 'images.insert',
  validate: new SimpleSchema({
    file: { type: String },
  }).validator(),
  run({ file }) {
    Images.write(new Buffer(file, 'base64'), {
      fileName: 'ImageName.png',
      type: 'image/png',
    }, function (error, fileRef) {
      if (error) {
        throw error;
      } else {
        console.log(`${fileRef.name} is successfully saved to FS. _id: ${fileRef._id}`);
        return fileRef;
      }
    });
  },
});

```
1. I am receiving file encode in base64 from frontend correctly.
The document is created in mongo database but the image saved in FS is corrupted.(it's not an image).
https://imgur.com/a/yCE2A

2. I am not able to receive fileRef, or information of saved document to client( frontend).

**Comment by badis** [comment]
Well for the first point I have made a progress on fixing it using this hack: https://gist.github.com/madhums/e749dca107e26d72b64d

Now I am able to save image correctly. here my new Method.

```
export const insertImage = new ValidatedMethod({
  name: 'images.insert',
  validate: new SimpleSchema({
    file: { type: String },
  }).validator(),
  run({ file }) {
    Images.write(new Buffer(file.replace(/^data:image\/\w+;base64,/, ''), 'base64'), {
      fileName: 'ImageName.png',
      type: 'image/png',
    }, (error, fileRef) => {
      if (error) {
        throw error;
      } else {
        console.log(`${fileRef.name} is successfully saved to FS. _id: ${fileRef._id}`);
        return fileRef;
      }
    });
  },
});

```
I am intending to use this method for all types of files and I am not sure if it will work (videos, pdf ... etc).
Please let me know what you think !

**Comment by dr-dimitru** [comment]
@badis I didn't get it. Have you solved it?

**Comment by badis** [comment]
Yes, I solved the first part. 
Now i need to return information to client.
I am not able to receive fileRef, or information of saved document to client( frontend).

**Comment by badis** [comment]
`.wrapAsync` sounds good ! because it's a meteor function.
Can you please help me implementing it with my code.
`Images.write` returns a `FilesCollection` instance. I want to return `fileRef` to my client.

**Comment by dr-dimitru** [comment]
Sure, you just wrapping it up, regardless what this function returns, as we interested in a callback of this function:
```js
const asyncWrite = Meteor.wrapAsync(Images.write);
// That's it
// Now when you need fileRef:
const fileRef = asyncWrite(buffer, opts);
```

**Comment by badis** [comment]
Thank you !
