### ISSUE TITLE
How do I export files collection for AWS s3 integration?

### ISSUE THREAD

**Issue by tobitech** [VeliovGroup/Meteor-Files#523]
Please how do I export the files collection (instance of FilesCollection) that was created in the code.
when I add an export keyword to the beginning of the statement i get an error in my IDE that says `export declarations are only allowed at the top level of module scope`

**Comment by dr-dimitru** [comment]
I guess you have a parser error. This error/rule should apply only to `import` keyword. You're safe to ignore it.

**Comment by tobitech** [comment]
I've ignored it but still showing red though, doesn't matter. It works anyway. I love the great work you've done with this package, the most amazing thing was that I didn't have to change client API code when I migrated from GridFS to AWS S3 integration. Nice work man.

**Comment by dr-dimitru** [comment]
> I've ignored it but still showing red though, doesn't matter. It works anyway.

What IDE are you using?
Which ES6 linter are you using?

>  I love the great work you've done with this package, the most amazing thing was that I didn't have to change client API code when I migrated from GridFS to AWS S3 integration. Nice work man.

My pleasure. Really glad to hear what you have found my work useful, appreciated.
Yes, widely open API with minimally needed methods let accomplish such things when you're not limited by API structure and free to implement whatever meets your needs, multiple storages of a different kind, easy post-processing, file's subversions, and etc.

**Comment by tobitech** [comment]
I'm using Visual Studio Code 
using JSHint
I'm yet to explore all the powers of the package :)

**Comment by dr-dimitru** [comment]
> using JSHint

Oh, perhaps you should consider switching to `SublimeLinter-contrib-eslint` for full ES6 syntax support

I guess we can close this one?

**Comment by tobitech** [comment]
yeah
