### ISSUE TITLE
breaking changes between 1.8.2 and 1.9.1

### ISSUE THREAD

**Issue by znewsham** [VeliovGroup/Meteor-Files#525]
The removal of the `_.extend(self, _fileRef)` in FileCursor.js as compared to FileCursor.coffee means functions defined on the transformed document aren't available. i.e., `Images.findOne().myFunction()` no longer works

**Comment by dr-dimitru** [comment]
Hello @znewsham ,

```js
Object.assign(this, _fileRef);
```

Is doing the same (*our tests haven't indicated an change here*). Could you share a piece of code where you're extending *FileCursor* class?

**Comment by znewsham** [comment]
@dr-dimitru we're not extending the class itself, you can see this bug with this code:


    var GoodCursor = function(fileRef){
     _.extend(this, fileRef);
    }
    var FileRef = function(){
    }
    FileRef.prototype.someFunc = function(){return "test";}
    console.log(new GoodCursor(new FileRef()).someFunc)

versus:

    var BadCursor = function(fileRef){
     Object.assign(this, fileRef);
    }
    var FileRef = function(){
    }
    FileRef.prototype.someFunc = function(){return "test";}
    console.log(new BadCursor(new FileRef()).someFunc)


looks like a difference between _.extend and Object.assign

**Comment by znewsham** [comment]
@dr-dimitru I suspect this will only happen on the client where classes are converted into functions with prototypes - when I tried the same test on the client, declaring a class for FileRef, I got different results.

**Comment by dr-dimitru** [comment]
1. You can `extend` class
 2. You can extend/add props to its instance, after calling it with `new` keyword

Feels like I'm getting you wrong, and I need more info on what you're trying to accomplish.

**Comment by znewsham** [comment]
Is there a reason you can't continue to use _.extend vs Object.assign? It is this change causing the problem.

I want to use a transform function, as I would with any other Mongo collection so a call to `Images.find()` will return me an object of type `Image`

    export const Images = new FilesCollection({
        ...
    });

    export class Image extends Offlineable{
      constructor(doc){
        super();
        _.extend(this, doc);
      }
      someFunction(){
        return "test";
      }
    } 
    Images.collection._transform = function(doc){
      return new Image(doc);
    };

Under 1.8.2 both `Images.collection.findOne()`  and `Images.findOne()` will return me an object with all the instance methods of `Image` defined. 

In 1.9.1 `Images.collection.findOne()`  returns me an instance of `Image`, `Images.findOne()` returns me an object WITHOUT any of the instance methods of `Image` defined.

To be clear - the issue is exclusively to do with methods defined on the `_fileRef` variable (e.g., because its an instance of `Image`.

Does that clear things up?

**Comment by dr-dimitru** [comment]
@znewsham thank you for contribution. [v1.9.2](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.2) is out.
