### ISSUE TITLE
How to give a custom name to a file download?

### ISSUE THREAD

**Issue by Mklueh** [VeliovGroup/Meteor-Files#528]
I want to set the file name on the fly once a download is triggered.

However, the naming function seems to be only relevant for the name the file is stored under.

Is this possible by any chance?

**Comment by dr-dimitru** [comment]
Hello @Mklueh ,

There is two ways (*or both*) to accomplish this:
 - [*easy*] Using [`download` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download), see [example](https://www.w3schools.com/tags/att_a_download.asp)
 - [*difficult*] Using [`Content-Disposition` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)

To use `download` attribute simply add it to links in a template:
```handlebars
<a href="{{file.link}}" download="filename.ext">Download file</a>
```

To use `Content-Disposition` header, read [this article](https://github.com/VeliovGroup/Meteor-Files/wiki/Custom-Response-Headers)

**Comment by Mklueh** [comment]
@dr-dimitru wow I didn´t know this was possible through HTML directly, thank you very much!

**Comment by dr-dimitru** [comment]
@Mklueh I'm this one is solved :) 

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by Mklueh** [comment]
@dr-dimitru Tried it now, download tag doesn´t do anything and keeps the FileCollection name. Trying Content-Disposition now

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.

 1. What browser you're on?
 2. This feature isn't supported only on few browsers - https://caniuse.com/#feat=download

**Comment by Mklueh** [comment]
I´m using the latest version of Chrome, which should be supported according to that list. Weird

**Comment by dr-dimitru** [comment]
@Mklueh Share how you're using it, your code + chrome devtools screenshot, mb you have a typo somewhere

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
