### ISSUE TITLE
No Preview for files 

### ISSUE THREAD

**Issue by daslicht** [VeliovGroup/Meteor-Files#53]
Hi, I don't get any file prelisten or view here:

http://_.meteor.com/gt2uRGekimkrjRWhb

?

**Comment by dr-dimitru** [comment]
It depends from browser support of `mp3` format. 
 - In Chrome works fine - [proof](http://_.meteor.com/MS89wLKPX9vMJqpKZ)
 - In Safari not loading, as it has no support for `mp3`

**Comment by daslicht** [comment]
Ahh thank you !
