### ISSUE TITLE
link() crashes if extension exists but has no value

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#532]
Our app started to crash because 
```
const vRef = ((fileRef.versions && fileRef.versions[version]) || fileRef);

  if (_.has(vRef, 'extension')) {
    ext = `.${vRef.extension.replace(/^\./, '')}`;
  } else {
    ext = '';
  }
```
https://github.com/VeliovGroup/Meteor-Files/blob/master/lib.js#L71 

just checks if the property exists (`_.has`) and doesn't check if a value is given/or value is a string. The default schema sets extension to string, the value is optional (keep in mind that `versions` are also affected as they have an extension field too). 

Yes, the first solution should be to fix the database, but also I think that `link()` should be more fail-safe in this case.

**Comment by dr-dimitru** [comment]
@menelike thank you, merged and published as [`v1.9.3`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.3)

**Comment by menelike** [comment]
@dr-dimitru 
Thank you for your support and the speed you maintain this project. You are doing a very good job here! Applause!

**Comment by dr-dimitru** [comment]
![you're welcome menelike](https://media3.giphy.com/media/3o7TKrbXUnCJkzAWu4/giphy.gif)
