### ISSUE TITLE
Error downloading pdf in Chrome

### ISSUE THREAD

**Issue by WimAtIHomer** [VeliovGroup/Meteor-Files#539]
- Version of `Meteor-Files` : 1.8.3
  - Version of `Meteor`: 1.5.2.2

In Chrome I receive by a file download an ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION error. Like in #9 

In Firefox I can download the file and this is the Content-Disposition that is received in the response.
attachment; filename="4729%20Krohne%20Altometer,%20Vondelingenplaat-Rt.,%20Petroleumweg%2036%20-%20pijpstuk%2020%20inch-600%20pond.pdf"; filename*=UTF-8''4729%20Krohne%20Altometer,%20Vondelingenplaat-Rt.,%20Petroleumweg%2036%20-%20pijpstuk%2020%20inch-600%20pond.pdf; charset=UTF-8

If I remove the comma's from the filename in the database the download is working.

**Comment by dr-dimitru** [comment]
Hello @WimAtIHomer ,

Please update this thread following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Screenshot of "Network" tab in DevTools, where error and all request/response headers are visible

**Comment by dr-dimitru** [comment]
Hello @WimAtIHomer ,

Thank you for discovering this one, update is published as [`v1.9.5`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.5).
Let me know if this one is fixed for you, or feel free to reopen it in case if the issue still persists on your end.

**Comment by WimAtIHomer** [comment]
Thanx @dr-dimitru 
Works as expected now, thanx for the quick fix.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
