### ISSUE TITLE
Client sets file location once, Server can access at will

### ISSUE THREAD

**Issue by maco144** [VeliovGroup/Meteor-Files#54]
My project is reading clients game log files and outputting results. I have client set location for a text log file for a game they play when they sign up. Currently only the upload occurs when client calls the upload. I want it to be so that once file location is defined/set then both client and server can access file passively without client having to explicitly call upload. So once client is logged in I would have access to file as a streaming read/write that can be open/called at any time. Is this currently possible and I am failing on way to implement or would this be possible as enhancement? 
Thank you for reviewing.

**Comment by dr-dimitru** [comment]
I believe this issue belong to front-end file access/reading
You can store path to file defined by user for later usage, not sure about access to this file without explicit  user permission.

This package will accept any `File` object for upload.

**Comment by maco144** [comment]
Yes the explicit permission I have issue with and cannot find workaround. I wonder if a way to hack around it or if way to treat like server always has read access. I will close as this isnt issue with package.

**Comment by dr-dimitru** [comment]
But I'm 99% sure browser's security policy will not allow this action, unless you use browser or flash plug-in
