### ISSUE TITLE
POST ignores ROOT_URL --mobile-server   

### ISSUE THREAD

**Issue by hacknlove** [VeliovGroup/Meteor-Files#540]
Meteor-Files version 1.9.1
Meteor version 1.6

The uploads are not working from cordova android, so I run `ROOT_URL='http://192.168.0.20:3000' meteor run android-device --settings settings.json --mobile-server 'http://192.168.0.20:3000'`

In the developer tools I see that the path of the POST is `http://localhost:12848/cdn/storage/adjuntos/__upload` instead of `http://192.168.0.20:3000/cdn/storage/adjuntos/__upload`

**Comment by dr-dimitru** [comment]
Hello @hacknlove ,

tl;tr;
Smooth upload experience on cordova, is guaranteed only with `ddp` transport.

This is [known "feature"](https://github.com/VeliovGroup/Meteor-Files/issues/159#issuecomment-238620345).

I think we can classify this as feature, to allow using value defined in `--mobile-server` for upload and download files skipping internal "fake" server.

/cc @menelike @s-ol

**Comment by hacknlove** [comment]
thank you @dr-dimitru for your speed answering

DDP is deprecated, isn't it ?

Should I hook on onBeforeUpload and use XMLHttpRequest to upload the file myself with ?

**Comment by dr-dimitru** [comment]
> DDP is deprecated, isn't it ?

No, not at all, where this info coming from?

> Should I hook on onBeforeUpload and use XMLHttpRequest to upload the file myself with ?

It's much much complex than looks at the first moment.
In the case you decide go this way - you will end up with your own package :)

**Comment by dr-dimitru** [comment]
Posted as feature - #547 
Feel free to reopen it in case if the issue still persists on your end.
