### ISSUE TITLE
[Upload] [DDP Start Method] Got #-1/8 chunks

### ISSUE THREAD

**Issue by acemtp** [VeliovGroup/Meteor-Files#543]
I'm having an issue on METEOR@1.6.0.1 with latest meteor files package version.

When I upload an image using DDP (I use the simple example from your website) on the FS.

It works on locally on my mac.
In production it failed at 100% uploaded (I tried different files with the same error)

I have this error on the server:

```
[FilesCollection] [File Start Method] IMG_0087.jpg - X66sfTdNcs8tbQNRN
[FilesCollection] [Upload] [DDP Start Method] Got #-1/8 chunks, dst: IMG_0087.jpg
Exception in callback of async function: Error: [FilesCollection] [writeStream] [ensureFile] [Error:] [500]
    at bound (packages/ostrio:files/write-stream.js:44:19)
    at Meteor.bindEnvironment.callback (packages/ostrio:files/write-stream.js:10:52)
    at runWithEnvironment (packages/meteor.js:1240:24)
[FilesCollection] [Upload] [DDP] Got #1/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #2/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #8/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #3/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #4/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #5/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #6/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #7/8 chunks, dst: IMG_0087.jpg
[FilesCollection] [Upload] [DDP] Got #-1/8 chunks, dst: IMG_0087.jpg
```

**Comment by acemtp** [comment]
Ok, it was a file permission on the FS storage.

**Comment by dr-dimitru** [comment]
Great, you have found a solution so quickly.
If you have found this project useful, please, take a minute to support it:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
