### ISSUE TITLE
Invalid non-string/buffer chunk while writing file on server

### ISSUE THREAD

**Issue by inromualdo** [VeliovGroup/Meteor-Files#546]
While writing file:
```js
Files.write(data,{
        type: 'application/pdf',
        fileName: 'sample.pdf',
        meta: {
          reference: "ref",
          version: 1
        }, function (error, fileRef) {
          if (error) {
            throw error;
          } else {
            console.log(fileRef.name + ' is successfully saved to FS. _id: ' + fileRef._id);
          }
        }
      });
```
The error "Invalid non-string/buffer chunk" appear with a blank file in the path.
  - Version of `Meteor-Files` 1.9.3
  - Version of `Meteor` 1.6.1
  - OS Linux (It work on Mac), Chrome browser
  - It is *Server* issue?
```
Exception in callback of async function: TypeError: invalid non-string/buffer chunk
```

**Comment by dr-dimitru** [comment]
Hello @inromualdo ,

 1. FYI [syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)
 2. Post *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
 3. What you're passing as `data`? Where it's coming from? Could you console.log it?

**Comment by inromualdo** [comment]
Hello.
I just update Meteor to 1.6.1 and every thing work. What was the problem?

**Comment by dr-dimitru** [comment]
> What was the problem?

 1. What version you were on?

**Comment by inromualdo** [comment]
1.5.1

**Comment by dr-dimitru** [comment]
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
1. Are you on `1.6.1` (*beta*) or `1.6.0.1` (*stable*)?
 2. Take a look on Meteor's [changelog](https://github.com/meteor/meteor/blob/devel/History.md) to see what is changed between your updates, but I don't see any significant and related changes
 3. Since you're on the latest Meteor release, you can update Meteor-Files package ti the [latest release](https://github.com/VeliovGroup/Meteor-Files/releases)

Sure, there is might be a bug in Meteor or Meteor-Files package, which was recently fixed, it's always a good idea to keep packages updated.

**Comment by inromualdo** [comment]
I try to reproduce this issus but i can not.
I am on 1.6.1 in Linux before it was on 1.5.1
I will close it. If i get this problem again, i will contact with other informations

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
