### ISSUE TITLE
Error should not be triggered after successful upload

### ISSUE THREAD

**Issue by vjau** [VeliovGroup/Meteor-Files#549]
This is not really an issue but more something that bothers me with current behaviour of this module.
When an upload is completed, the "onUploaded" callback is called. 
The documentation says "Callback, triggered when upload is finished".
As i understand it, this mean the upload is considered a success.
The problem is that if an error occurs in the afterUpload callback on the server, the onError callback is called.
Which means an upload considered successful can then give an error. 
With this behaviour, a file that has been correctly uploaded, that is on the filesystem on the server, that is commited in the DB, gives an error.
I think this is not appropriate.
IMHO, an exception in "afterUpload" should not trigger the onError callback.
IMHO again, the user of the module should handle exceptions in afterUpload the way he see fit.
Or perhaps an "onAfterUploadError" callback could be called, but i would prefer the first solution.

Thank you.

**Comment by dr-dimitru** [comment]
@vjau agree on this opinion.

 - `onUploaded` should be named on `onEnd`;
 - `onUploaded` called with 2 arguments, `error` and `fileRef`, so there is need to use `onError`;
 - `onError` could be used when `onUploaded` hook isn't registered.

I'll take it into account, we will name all methods and hooks very carefully in `v2.0`.
Current naming ideas [here](https://github.com/VeliovGroup/Meteor-Files/projects/2?), feel free to take a part.

**Comment by dr-dimitru** [comment]
closing as this could break current `v1.x`
