### ISSUE TITLE
Image.url() returns http://localhost url in production

### ISSUE THREAD

**Issue by wanchopeblanco** [VeliovGroup/Meteor-Files#55]
Im having a problem when uploading images on my production server, Image.url() function is returning am http://localhost url instead of my domain url, also i need to get the address in https.

Is there a config that im missing or something?

By the way, thanks for the great work.

**Comment by dr-dimitru** [comment]
Hi @wanchopeblanco 
Is `ROOT_URL` set?

From docs:
> Generate an absolute URL pointing to the application. The server reads from the `ROOT_URL` environment variable to determine where it is running. This is taken care of automatically for apps deployed with meteor deploy, but must be provided when using meteor build.

**Comment by wanchopeblanco** [comment]
Hi @dr-dimitru 

It was already set, I did reconfig with mup and solve the problem.
Thanks for pointing that up, and for the quick reply.

**Comment by dr-dimitru** [comment]
You're welcome.
Please star this package, [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Expressive%20file-management%20in%20%23Meteor%20via%20%40veliovgroup) or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files) if you like it and found useful.
