### ISSUE TITLE
Meteor crashes after the package is added

### ISSUE THREAD

**Issue by luckyvs1** [VeliovGroup/Meteor-Files#551]
### I'm having an issue:
  - Meteor crashes after the package is added 
  - Version of `Meteor-Files` you're experiencing this issue: 1.9.5
  - Version of `Meteor` you're experiencing this issue: METEOR@1.4.1.3
  - Where this issue appears? OS (Mac)

The following error is seen: 

   While building for web.browser:
   packages/ostrio:files/core.js:12:2: /packages/ostrio:files/core.js: Missing
   class properties transform.
   
   While building for os.osx.x86_64:
   packages/ostrio:files/core.js:12:2: /packages/ostrio:files/core.js: Missing
   class properties transform.

**Comment by dr-dimitru** [comment]
Hello @luckyvs1 ,

Not sure what may be wrong, meteor@1.4.* is a way too old.

 1. As I understood - application works fine in development, unless you try to run `meteor build`?
 2. Could you post contents of `.meteor/packages` file?

**Comment by luckyvs1** [comment]
For the above the errors occurred when i run `meteor` in the command line.

Here are the contents of the .meteor/packages file:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.13                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.10            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0_1   # CSS minifier run for production mode
standard-minifier-js@1.2.0_1    # JS minifier run for production mode
es5-shim@4.6.14_1                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.8_1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.1            # Server-side component of the `meteor shell` command

iron:router
accounts-password
accounts-ui
mrt:jquery-ui
mfpierre:chartist-js
cleandersonlobo:sweetalert2
snamoah:bootstrap-wizard
session
alanning:roles
jswanson:bootstrap3.3.7
random
tmeasday:presence
check
momentjs:moment
remcoder:chronos
u2622:persistent-session
lepozepo:s3
loftsteinn:photoswipe
voodoohop:masonrify
mystor:device-detection
mdg:camera
tap:i18n
tap:i18n-ui
meteortoys:allthings
fortawesome:fontawesome
email
meteorhacks:ssr
mrgalaxy:stripe
smaltcreation:paypal-rest-api
patrickml:braintree
kadira:flow-router
easy:search
sergeyt:typeahead
mrt:ryw:blog
aldeed:http-fix
ostrio:files
```

**Comment by dr-dimitru** [comment]
Packages looks good.

Perhaps you should check and update your NPM dependencies:
```shell
# check for outdated packages
meteor npm outdated

# update packages
meteor npm update --save
```

**Comment by luckyvs1** [comment]
Thank you for the help, updating Meteor to V1.5.0 allows the package to be added without any issue

**Comment by dr-dimitru** [comment]
@luckyvs1 Great, I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
