### ISSUE TITLE
Question Amazon S3 Integration 

### ISSUE THREAD

**Issue by luckyvs1** [VeliovGroup/Meteor-Files#553]
### I'm having an issue:
  - I'm having an issue importing S3 credentials in the required format
    * I am using the settings.json file method using the one liner after it was checked with a json parser      
   `{"s3":{"key":"bob","secret":"bobbilly","bucket":"bob"}}`

  - Version of `Meteor-Files` you're experiencing this issue `Meteor-Files@1.9.5`
  - Version of `Meteor` you're experiencing this issue `Meteor@1.5`
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version? OS (Mac)

Would i store the settings in the settings.json file then execute the app using `meteor --settings settings.json` ? And use the code provided in Server-side-file-store.js (from the wiki: https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration)?  

The error I receive is `Error: Missing Meteor file settings [401]`

**Comment by dr-dimitru** [comment]
Hello @luckyvs1 ,

Could you please update this issue with full stacktrace? I'm wondering what file/line this erro coming from.

**Comment by luckyvs1** [comment]
I have resolved the errors mentioned above by passing a region parameter with the default region code (will verify proper code prior to implementation) so the format of the settings.json file is            
` {"s3":{"key":"bob","secret":"bob/billy","bucket":"bob", "region": "us-standard"}}`

**Comment by dr-dimitru** [comment]
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
