### ISSUE TITLE
Documents retrieved with find().fetch() have no link method

### ISSUE THREAD

**Issue by vjau** [VeliovGroup/Meteor-Files#554]
I am having a strange issue on the client with 1.9.5 on Meteor 1.6.0.1

With "FilesColl" collection, when i am doing on the client in the console:
```js
FilesColl.findOne().link();
```
It works.

But when i'm doing:
```js
FilesColl.find().fetch()[0].link();
```
It says that there is no link function. 

Thank you.

**Comment by vjau** [comment]
Oh, i understand, i must use "each", not "fetch".
So the correct usage is 
```js
FilesColle.find().each()[0].link();
```
since fetch() gives access to pure data object without methods.

**Comment by mksh-su** [comment]
Hello @vjau ,

Thanks for reporting on this. We are glad that you've solved this issue on your own. 😄 👍 

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)

**Comment by vjau** [comment]
Actually, you react exemple seems to be wrong, since it uses find().fetch(), which AFAIK cannot work with link().

**Comment by dr-dimitru** [comment]
Hello @vjau ,

Could you please point where `.link()` method is used on raw *Array* of *Object*s returned from `.fetch()`? Are we talking about the same [React example](https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example)?

**Comment by vjau** [comment]
I'm wrong again. 
Actually, what is disturbing, is that the meteor mixin is doing that :
````js
docs: UserFiles.find().fetch()
```

and the react component render method is doing that : 
```js
let fileCursors = this.data.docs;
let display = fileCursors.map((aFile, key) => {
        // console.log('A file: ', aFile.link(), aFile.get('name'));
        let link = UserFiles.findOne({_id: aFile._id}).link();
```

but this.data.docs are NOT "fileCursors" but pure data objects.
And then these pure data objects are used to get their _id and reget the true file cursors from the FilesCollection. This is slighlty confusing.
And the commented console.log code (which couldn't work if uncommented), make me think this was probably some non working code hacked to make it work.

**Comment by dr-dimitru** [comment]
@vjau Agree on:
 1. `fileCursors` variable should be renamed to `fileDocs` (*or similar*);
 2. Commented `console.log` should be removed or changed to working example;

This wiki document originally was created by @vtocco , hopefully he can take a part and update it.
@vjau you are welcome to send a PR too, wiki source [is here](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/react-example.md).
