### ISSUE TITLE
404 with modified download button exemple

### ISSUE THREAD

**Issue by vjau** [VeliovGroup/Meteor-Files#555]
I have modified the demo-simplest-download-button,
replacing the ```<a href...``` line with
```<img src="{{link}}"/>```
But when i do that, i get a 404 error. 
Meteor Files version 1.9.5, Meteor 1.6.0.1

Server log : 
```
I20180113-23:09:38.182(1)? [FilesCollection] [find({}, undefined)]
I20180113-23:09:42.443(1)? [FilesCollection] [find({}, undefined)]
I20180113-23:09:42.692(1)? [FilesCollection] [download(/cdn/storage/Images/2eHyZDpi8YHBd5sHf/original/2eHyZDpi8YHBd5sHf, original)]
I20180113-23:09:42.693(1)? [FilesCollection] [download(/cdn/storage/Images/2eHyZDpi8YHBd5sHf/original/2eHyZDpi8YHBd5sHf)] [_404] File not found
```

Client log :
```
[FilesCollection] [findOne({}, undefined)]
core.js:88:7
[FilesCollection] [FileCursor] [with()]
core.js:88:7
[FilesCollection] [FileCursor] [link(original)]
core.js:88:7
[FilesCollection] [link(2eHyZDpi8YHBd5sHf, original)]
```

**Comment by mksh-su** [comment]
Hello @vjau ,

Thank you for reporting on this.
 1. What browser are you using? Does this happen in other browsers?
 2. Please make sure you haven't run into the issue described in our [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq). __Note: All files will be removed as soon as your application rebuilds.__

**Comment by vjau** [comment]
You are right, this is point 2 related. I thought because the file was inserted by the code this problem would not occur, but when doing meteor reset the problem disappear. Thank you.

**Comment by dr-dimitru** [comment]
@vjau great, we're glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
