### ISSUE TITLE
About the settings of insert (upload)

### ISSUE THREAD

**Issue by ShifaSZ** [VeliovGroup/Meteor-Files#556]
I'm having an issue with using insert (upload) method: the Wiki document for parameter "settings" seems incomplete. For example, I cannot find the descriptions for "fileName" setting which shown in the upload base64 examples. I'm hesitating to use it because there is no document for the setting.

Beside base64, can I use "insert" to upload text or binary data to the file collection?

Thanks.

**Comment by mksh-su** [comment]
Hello @ShifaSZ ,

 1. The `fileName` option originally was specific for base64, but right now it can be used for all types of uploads. Thanks for noticing it, we will update the Wiki;
 2. Any base64 encoded string can be uploaded with no dependency from its source. It can be audio, video, picture, text, etc.

PR is always welcome, source is [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/insert.md). 

//cc @dr-dimitru

**Comment by ShifaSZ** [comment]
Thanks @mksh-su , I will close this issue when the doc is updated.

**Comment by dr-dimitru** [comment]
Docs are updated. New release is published as [`v1.9.6`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.6). @ShifaSZ thank you for mentioning this omission.
