### ISSUE TITLE
How to Copy file collection data to another file collection, so the link() in meteor is working

### ISSUE THREAD

**Issue by NageshAdhe** [VeliovGroup/Meteor-Files#558]
Hi, I am using ostrio file package, i want to maintain the history of my images which, are uploaded.
I just want to copy current data of file collection and insert to new file collection, In this when i inserted data to another collection, we open the link by using link(), the uploaded image i not found in given link because the new id get generated. Please help me to get this resolve

**Comment by dr-dimitru** [comment]
Hello @NageshAdhe ,

Please speak code. Now it's unclear to me what are you trying to accomplish.

> I just want to copy current data of file collection and insert to new file collection

This is unclear.
 1. Is this the same server?
 2. Do you wish do duplicate data in a *FilesCollection*, or file also?
 3. Where files is stored? FS? 3rd party?

> In this when i inserted data to another collection

I would like to see the code.
 1. How that data is inserted?
 2. Are you doing in on the Server?

**Comment by dr-dimitru** [comment]
@NageshAdhe any news on this one? Have you solved it?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by Nilsalunkhe** [comment]
@dr-dimitru 
I get All images from collection using Images.find({}).fetch();

after that I want to insert each file in to new collection.

Are you doing in on the Server?: Yes we are doing this on server

Code : 

 var images = Images.collection.find({}).fetch();
        for (let i = 0; i< images.length; i++) {
            delete images[i]["_id"];
            HistoryImages.insert(images[i]);
        }
