### ISSUE TITLE
Add upload state property

### ISSUE THREAD

**Issue by jdmswong** [VeliovGroup/Meteor-Files#56]
It would be useful to support the state of the upload in the object returned from `files.insert()`

Perhaps name it `state` with its only values being:
* active
* paused
* aborted
* completed

That would be very helpful in styling the progress bar relative to the upload state, so users could easily see the status of their upload.

**Comment by jdmswong** [comment]
https://github.com/VeliovGroup/Meteor-Files/pull/57

**Comment by dr-dimitru** [comment]
Published as [v1.3.15](https://github.com/VeliovGroup/Meteor-Files/releases/tag/v1.3.15)
@jdmswong thank you for contribution
