### ISSUE TITLE
Can it be used with Stream?

### ISSUE THREAD

**Issue by PolGuixe** [VeliovGroup/Meteor-Files#562]
I want to use it with [Stream](https://www.npmjs.com/package/stream). 

However, I am finding difficulties. The code example is:

```js

function createInsertHandler(attribute, Collection) {
  return function (document, currentUser) {
    if (document[attribute] instanceof Readable) {
      console.log(document[attribute]);
      Images.write(document[attribute], {
        fileName: document[attribute].filename,
        type: document[attribute].mimeType,
      }, function (error, fileRef) {
      if (error) {
        throw error;
      } else {
        console.log(fileRef.name + ' is successfully saved to FS. _id: ' + fileRef._id);
        return fileRef._id;
      }
    });
      // const file = new FS.File();
      // file.attachData(document[attribute], { type: document[attribute].mimeType });
      // file.owner = currentUser._id;
      // file.name(document[attribute].filename);
      // file.type(document[attribute].mimeType);
      // console.log('before');
      // const { _id } = Collection.insert(file);
      // console.log('after');
      // return _id;

    }
    return document[attribute];
  }
}
```
The error I am getting is: `TypeError: Invalid non-string/buffer chunk`. 

I as it can be seen I am trying to substitute `CollectionFS`. I am building a Vulcan app and I am trying to use https://github.com/OrigenStudio/file-scalar to add file system capabilities.

Additional information:
- Meteor: v1.6.0.1
- Meteor-files: v1.9.6
- MacOS 10.13.2
- Server issue

Any hints would be welcome ;)

**Comment by mksh-su** [comment]
Hello @PolGuixe ,

Please, let us know a little more about this issue - for example, the Meteor and Meteor-files versions that you're using, your OS and browser etc. For more information read our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE) when describing the details.
Thanks in advance!

cc// @dr-dimitru

**Comment by dr-dimitru** [comment]
Hello @PolGuixe ,

### TL;TR;
No, you cannot use streams.


### Full answer:
 1. `.write()` and `.addFile()` methods are *Server* only (the `stream` package you've referenced is for a browser);
 2. I suggest next usage:
    1. Write a file to FS
    2. Use [`.addFile()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile) to add file to the *FilesCollection*

Let me know wdyt.
+1 to @mksh-su , filling an issue following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE), will help a lot to provide you right suggestion.

**Comment by PolGuixe** [comment]
@mksh-su thanks for the advice. I've modified the first entry to include version information. 

@dr-dimitru I need to have a better understanding of how streams work. However:
 - The function I defined above is executed in server. 
 - I thought streams can provide a buffer, hence `.write()` could accept it as input.
 - Any idea how can I write the file to FS?

**Comment by dr-dimitru** [comment]
@PolGuixe 

TL;TR;
```js
const wstream = fs.createWriteStream('/path/to/where/you/wish/store/a/file');
readableStream.pipe(wstream);

// in your case readableStream is the document[attribute]
```

We are better to start with answering leading questions (*as your current request isn't clear for me*):
 1. What are you trying accomplish?
 2. Where data (*stream, buffer, or in other form*) comes from?

**Comment by dr-dimitru** [comment]
Looks similar to https://github.com/VeliovGroup/Meteor-Files/issues/567

BTW @PolGuixe have you solved it?

**Comment by PolGuixe** [comment]
@dr-dimitru I've managed to make it work 😃 however I still need to tidy the code a bit and do some refactoring.

Right now it's working with just using the local file system. 


BTW where are the files stored locally? I can't find it in `.meteor/build/programs/server/assets/app/uploads/ImageFiles`? `ImageFiles` is the name of the collection.

**Comment by dr-dimitru** [comment]
@PolGuixe this info can be found in our [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> 1. __Where are files stored by default?__: by default if `config.storagePath` isn't passed into [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) it's equals to `assets/app/uploads` and relative to running script:
>    * On `development` stage: `yourDevAppDir/.meteor/local/build/programs/server`. __Note: All files will be removed as soon as your application rebuilds__ or you run `meteor reset`. To keep your storage persistent during development use an absolute path *outside of your project folder*, e.g. `/data` directory.
>    * On `production`: `yourProdAppDir/programs/server`. __Note: If using MeteorUp (MUP), Docker volumes must to be added to__ `mup.json`, see [MUP usage](https://github.com/VeliovGroup/Meteor-Files/wiki/MeteorUp-(MUP)-Usage)

Yes, last directory named according to collection name

**Comment by PolGuixe** [comment]
@dr-dimitru when using `.addFile` the `onBeforeUpload`event is not triggered. How would you validate on client?

**Comment by dr-dimitru** [comment]
@PolGuixe `.addFile()` a *Server* only method. `onBeforeUpload` a *Client* only hook. `onBeforeUpload` only relative to upload (`.insert()` method)

**Comment by PolGuixe** [comment]
@dr-dimitru then the `onAfterUpload` event is not triggered neither...

**Comment by dr-dimitru** [comment]
@PolGuixe ,

> then the onAfterUpload event is not triggered neither...

Please update thread with a code sample you're on right now.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
