### ISSUE TITLE
addFile alternative do to an "upload" on server-side

### ISSUE THREAD

**Issue by Mklueh** [VeliovGroup/Meteor-Files#567]
I need to migrate files from my old system into my new one. Using addFile only adds a reference to the file within my old system, however I need to kind of simulate the upload which also processes that file and creates thumbnails, renaming and directory creation.

How can I do that?

**Comment by dr-dimitru** [comment]
Hello @Mklueh ,

Use `.write()` method.

**Comment by dr-dimitru** [comment]
@Mklueh this thread looks similar - https://github.com/VeliovGroup/Meteor-Files/issues/562

Have you solved it with `.write()` method?

**Comment by Mklueh** [comment]
@dr-dimitru Kind of, but not the way I expected. 

For example the **onBeforeUpload** function is not called where I fetch and attach a reference to another collection. But I can work with it, thank you ;)

**Comment by dr-dimitru** [comment]
Hello @Mklueh ,

Do you read the docs?:
 - [`.addFile()`](https://github.com/VeliovGroup/Meteor-Files/wiki/addFile)
 - [`.write()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Write)
 - [`.load()`](https://github.com/VeliovGroup/Meteor-Files/wiki/Load)

All three above has fourth argument `proceedAfterUpload`, if set to `true`, it will call `onAfterUpload` hook after itself.

**Comment by Mklueh** [comment]
Thx, misunderstood that

**Comment by dr-dimitru** [comment]
@Mklueh let us know if `.write()` fully fills your needs
