### ISSUE TITLE
Safari won't play videos served by AWS S3

### ISSUE THREAD

**Issue by izaa** [VeliovGroup/Meteor-Files#568]
Hi,

i have a problem with Safari web browser.
- Safari version is 9.1.2
- Meteor Files version: ostrio:files@1.9.6
- Meteor version 1.6.1

I'm uploading videos to AWS S3 using Meteor Files. Everything works fine. However, when I try to play those videos, Safari is not playing them at all. Some versions of Safari works fine I think, but this version not. Safari's version is 9.1.2. Videos' play fine with Chrome, Opera, IE and Firefox in Windows.

**interceptDownload-section is as below**

```
    interceptDownload(http, fileRef, version) {
      let path = (fileRef && fileRef.versions && fileRef.versions[version] && fileRef.versions[version].meta && fileRef.versions[version].meta.pipePath) ? fileRef.versions[version].meta.pipePath : void 0;

      if (path) {
        const opts = {
          Bucket: s3Conf.Bucket,
          Key: path
        }
        const vRef = fileRef.versions[version];
        let range = _.clone(http.request.headers.range);
        if (range) {

          const array = range.split(/bytes=([0-9]*)-([0-9]*)/);
          // array on luokaa [ '', '0', '1', '' ] tai jotain sellaista
          const start = parseInt(array[1]);
          let end = parseInt(array[2]);
          const size = vRef.size || fileRef.size;
          if (isNaN(end)) {
            // Request data from AWS:S3 by small chunks
            end = (start + this.chunkSize) - 1;
            if (end >= size) {
              end = size - 1;
            }
          }
          //opts.Range = `bytes=${start}-${end}`;
          http.request.headers.range = `bytes=${start}-${end}`;
          //http.respnse.statusCode = 206;
        } else {
          console.log('what, cannot find range', fileRef);
        }
        http.response.setHeader('content-range', `${http.request.headers.range}/${fileRef.size}` );
        http.response.setHeader('content-type', fileRef.type || 'application/pdf');
        http.response.setHeader('content-length', fileRef.size || 0);

        client.getObject(opts).createReadStream().on('error', (err) => {
          bound(() => {
            console.error('bound 1: ', err, 'path', path);
          });
        }).pipe(http.response);

        return true;
      }

      return false;
    }






```

BTW: if I uncomment `opts.Range = `bytes=${start}-${end}`;` none of the browsers play video, why?

**HTTP request is** 
```

{ 'x-forwarded-host': '192.168.1.13:3000',
 'x-forwarded-proto': 'http',
 'x-forwarded-port': '3000',
 'x-forwarded-for': '192.168.1.20',
 connection: 'keep-alive',
 'accept-encoding': 'identity',
 referer: 'http://192.168.1.13:3000/cdn/storage/user_files/6Q7Wpot5idbmicnk2/webvideo/6Q7Wpot5idbmicnk2.mp4?play=true',
 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7',
 accept: '*/*',
 range: 'bytes=0-1',
 cookie: 'x_mtok=PptAk38gMpE4ARm88',
 'x-playback-session-id': '588AAC75-0566-40F6-AF1F-4861BDAF12A0',
 'accept-language': 'en-us',
 host: '192.168.1.13:3000' }
```

What I understand it is very typical for Safari to send bytes=0-1, is it? How to handle that?

Ok, when trying to play using Safari, AWS sends timeout 

```
bound 1:  { TimeoutError: Connection timed out after 6000ms
   at ClientRequest.<anonymous> (C:\Users\userna\Documents\Meteor_Project\node_modules\aws-sdk\lib\http\node.js:83:34)
   at Object.onceWrapper (events.js:313:30)
   at emitNone (events.js:106:13)
   at ClientRequest.emit (events.js:208:7)
   at Socket.emitTimeout (_http_client.js:708:34)
   at Object.onceWrapper (events.js:313:30)
   at emitNone (events.js:106:13)
   at Socket.emit (events.js:208:7)
   at Socket._onTimeout (net.js:407:8)
   at ontimeout (timers.js:475:11)
   at tryOnTimeout (timers.js:310:5)
   at Timer.listOnTimeout (timers.js:270:5)
 message: 'Connection timed out after 6000ms',
 code: 'TimeoutError',
 time: 2018-01-25T20:41:47.536Z,
 region: 'eu-west-1',
 hostname: 'myhost.s3.eu-west-1.amazonaws.com',
 retryable: false,
 statusCode: 200,
 retryDelay: 48.079054397763855 } path videos/daa/dee.mp4


```

That doesn't happen if using any other browser.

Same behavior in my local dev environment than in Galaxy. I cannot get your example AWS code working but this code works in other browsers. What should I try next?

Thank you for the help!

**Comment by dr-dimitru** [comment]
Hello @izaa ,

 1. Please update question following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE)
 2. Safari `v9.1.2` is outdated and unsupported, so Apple doesn't guarantee it to works, nor we are. Have you tried latest Safari `v11.0.3`?

**Comment by dr-dimitru** [comment]
3. Does videos playing when uploaded to our [demo app](https://files.veliov.com)?
 4. Take a look on [implementation used at our demo app](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L139), try to use this approach.

**Comment by izaa** [comment]
Thank you @dr-dimitru i updated the question:
- Safari version is 9.1.2
- Meteor Files version: ostrio:files@1.9.6
- Meteor version 1.6.1

I need to try newer Safari. I'm not a mac user but i'm investigatin an issue users have. But if that is too old Safari let me try newer, thanks!

I have tried your demo approach also, but somehow i don't get it to work in any browser. Your live demo app works, but does it stream files from AWS ?

**Comment by dr-dimitru** [comment]
@izaa 

>  but does it stream files from AWS ?

Yes. As you [see here](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L171) - `dataStream` is "piped" inside `fileColl.serve()` method. And [only requested](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L166) chunk by browser is pulled from AWS.

**Comment by dr-dimitru** [comment]
> I'm not a mac user

Bad news, - there is no new Safari for Win, it's discontinued.

**Comment by izaa** [comment]
Oh, I am not a mac daily user but now i have a mac so i can trooubleshoot the problem.  I need to try to debug your code, i don't understand why it didn't work ..Thanks!

But Safari requests Bytes=0-1 but it can be a bug in safari?

**Comment by izaa** [comment]
@dr-dimitru 

can you tell if my object have some missing information?

If i try your example, the FilesCollection serve-method in debug mode says :

>  [FilesCollection] [serve(undefined, webvideo)] [206]

called 
`              fileColl.serve(http, fileRef, fileRef.versions[version], version, dataStream);
`
where fileRef.versions[version] is 
```
{ type: 'video/mp4',
extension: 'mp4',
 meta: { pipePath: 'videos/JCRLMXfvtXQ25e9EE/eoFtuHPd5baghZRPd.mp4' },
_id: '6Q7Wpot5idbmicnk2' 
}

and version is `webvideo`
```

The object, (am I missing version size or something else?)

```

{
    "_id" : "WZh99M5GrA6LjHD8t",
    "size" : 1309831,
    "type" : "video/mp4",
    "name" : "pers.mp4",
    "meta" : {
        "createdAt" : ISODate("2018-01-25T11:42:02.869Z"),
        "public" : false
    },
    "ext" : "mp4",
    "extension" : "mp4",
    "extensionWithDot" : ".mp4",
    "mime" : "video/mp4",
    "mime-type" : "video/mp4",
    "userId" : "JCRLMXfvtXQ25e9EE",
    "path" : "assets/app/uploads/uploadedFiles/WZh99M5GrA6LjHD8t.mp4",
    "versions" : {
        "original" : {
            "path" : "assets/app/uploads/uploadedFiles/WZh99M5GrA6LjHD8t.mp4",
            "size" : 1309831,
            "type" : "video/mp4",
            "extension" : "mp4",
            "meta" : {
                "pipePath" : "user_files/JCRLMXfvtXQ25e9EE/8DPxxsAYpwEWRpryr.mp4"
            }
        },
        "webvideo" : {
            "type" : "video/mp4",
            "extension" : "mp4",
            "meta" : {
                "pipePath" : "videos/JCRLMXfvtXQ25e9EE/8DPxxsAYpwEWRpryr.mp4"
            }
        },
        "thumbnail400" : {
            "type" : "image/png",
            "extension" : "png",
            "meta" : {
                "pipePath" : "videos/JCRLMXfvtXQ25e9EE/8DPxxsAYpwEWRpryr/thumb-00001.png"
            }
        }
    },
    "_downloadRoute" : "/cdn/storage",
    "_collectionName" : "user_files",
    "isVideo" : true,
    "isAudio" : false,
    "isImage" : false,
    "isText" : false,
    "isJSON" : false,
    "isPDF" : false,
    "_storagePath" : "assets/app/uploads/uploadedFiles",
    "public" : false,
    "postJobsDone" : true
}
```

**Comment by dr-dimitru** [comment]
> But Safari requests Bytes=0-1 but it can be a bug in safari?

Safari still has this behavior, it's the it work.

**Comment by dr-dimitru** [comment]
> I'm missing subversion's size and path properties and that is why your example is not working! So storing subversions should store size and path info too!

Yes, you're better to update all metadata on subversions. But since it's not used in your case you're good. Especially if it works in other browsers

**Comment by izaa** [comment]
Ok this works now _better_ in Safari if I fetch the correct size of transcoded video and update the collection. And also using your AWS example code. But only problem is now that they wont play on Galaxy. Galaxy downloads chunks very, very slowly.. Nice :) 

I'll figure this out!

**Comment by dr-dimitru** [comment]
Hello @izaa ,

This is known Galaxy issue, and there is nothing we can do about it. It works on Heroku though, and any dedicated servers. Similar issues:

 - https://github.com/VeliovGroup/Meteor-Files/issues/529
 - https://github.com/VeliovGroup/Meteor-Files/issues/506
 - https://github.com/VeliovGroup/Meteor-Files/issues/383

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
