### ISSUE TITLE
How to customize image link for uploaded file

### ISSUE THREAD

**Issue by NageshAdhe** [VeliovGroup/Meteor-Files#573]
Hi,
I just upload one Image file using File collection in **meteor** and use following code..
```
 var uploadInstance = Images.insert({
   file: currentfile,
   meta: {productVersionId: productVersionId},
   streams: 'dynamic',
   chunkSize: 'dynamic',
}, false);
```
then i get image link using `link()` function, the generated link contains `_id` value, its working, but i want to insert this record into another collection, after inserting, the `_id` is changed, so the link generated is different, and the given path image is not present, could you please help me sort this.

**Comment by mksh-su** [comment]
Hello @NageshAdhe ,

Please, follow our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE) when describing a problem. We would need to know the version of Meteor and Meteor-Files that you use. Also, do you get any error?
And don't forget to format the code in your messages appropriately :)

**Comment by NageshAdhe** [comment]
I'm having an issue:
  - I just upload one Image file using ostrio  File collection in meteor on client side it is working fine, 
    but I want to copy this uploaded file into another collection on server side, the generated link for copied record is not working properly
  - In ostrio:files@1.8.3 
  - In Meteor 1.7.2 Version
  - on chrome version Version 64.0.3282.140 
  - see the following code on client side..
         var uploadInstance = Images.insert({
         file: currentfile,
         meta: {productVersionId: productVersionId},
         streams: 'dynamic',
         chunkSize: 'dynamic',
      }, false);
      
  -- Inserted record I copied to another collection
  
   var images = Images.collection._collection.find({}).fetch();
        console.log("Images-----------------------"+JSON.stringify(images));
        for (let i = 0; i< images.length; i++) {
            images[i].meta['version'] = version;
            delete images[i]["_id"];
            HistoryImages.collection._collection.insert(images[i]);
        }
--this above entry is also succusfully inserted, but when I get link using following code
  Images.find({meta: {isDeleted:false}});
  
  Link is generated is not working, because when we insert to another collection new '_id' is genrated in mongodb, 
  the genearated link is /cdn/storage/Images/7s8ZSuJ45uBjHMFF9/original/7s8ZSuJ45uBjHMFF9.jpg, '_id' -->7s8ZSuJ45uBjHMFF9 
  
  We are trying to maintaining version for images, so we need this to work. Please help me to resolve this I am trying this from last month
  
 Thank you,

**Comment by dr-dimitru** [comment]
@NageshAdhe ,

It's not clear what are you trying to accomplish. Take a look at your [versioning tutorial](https://github.com/VeliovGroup/Meteor-Files/wiki/Create-and-Manage-Subversions).

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
