### ISSUE TITLE
React example does not work...

### ISSUE THREAD

**Issue by iojanis** [VeliovGroup/Meteor-Files#577]
### I'm having an issue:
  - I'm facing errors while implementing meteor files into my react application
  - I'm using the newest version of meteor files
  - I'm using Meteor 1.6.1
  - Linux
  - Server issue ?
  - There are no server logs for this problem...

I already tried this:
https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example

Firstly I had to add:
import createReactClass from 'create-react-class';
and 
import PropTypes from 'prop-types';

in UploadFile.jsx I added:
import Files from '../../../api/Files/Files.js';

but then in web console: 

TypeError: Files.find is not a function[Learn More]
FileUpload.jsx:25:12
Files
ReferenceError: Files is not defined

I even tried:

**Comment by iojanis** [comment]
`import { ReactMeteorData } from 'meteor/react-meteor-data';
import React from 'react';
import Files from '../../../api/Files/Files.js';
import { Meteor } from 'meteor/meteor';
import IndividualFile from '../FileIndividualFile/FileIndividualFile.jsx';
import { _ } from 'meteor/underscore';

import createReactClass from 'create-react-class';

const FileUploadComponent = createReactClass({
  mixins: [ReactMeteorData],

  getInitialState(){
    return {
      uploading: [],
      progress: 0,
      inProgress: false
    }
  },

  getMeteorData() {
    var handle = Meteor.subscribe('files.all');
    return {
      docsReadyYet: handle.ready(),
      docs: Files.find().fetch() // Collection is UserFiles
    };
  },

  uploadIt(e){
    "use strict";
    e.preventDefault();

    let self = this;

    if (e.currentTarget.files && e.currentTarget.files[0]) {
      // We upload only one file, in case
      // there was multiple files selected
      var file = e.currentTarget.files[0];

      if (file) {
        let uploadInstance = Files.insert({
          file: file,
          meta: {
            locator: self.props.fileLocator,
            userId: Meteor.userId() // Optional, used to check on server for file tampering
          },
          streams: 'dynamic',
          chunkSize: 'dynamic',
          allowWebWorkers: true // If you see issues with uploads, change this to false
        }, false);

        self.setState({
          uploading: uploadInstance, // Keep track of this instance to use below
          inProgress: true // Show the progress bar now
        });

        // These are the event functions, don't need most of them, it shows where we are in the process
        uploadInstance.on('start', function () {
          console.log('Starting');
        });

        uploadInstance.on('end', function (error, fileObj) {
          console.log('On end File Object: ', fileObj);
        });

        uploadInstance.on('uploaded', function (error, fileObj) {
          console.log('uploaded: ', fileObj);

          // Remove the filename from the upload box
          self.refs['fileinput'].value = '';

          // Reset our state for the next file
          self.setState({
            uploading: [],
            progress: 0,
            inProgress: false
          });
        });

        uploadInstance.on('error', function (error, fileObj) {
          console.log('Error during upload: ' + error);
        });

        uploadInstance.on('progress', function (progress, fileObj) {
          console.log('Upload Percentage: ' + progress);
          // Update our progress bar
          self.setState({
            progress: progress
          })
        });

        uploadInstance.start(); // Must manually start the upload
      }
    }
  },

  // This is our progress bar, bootstrap styled
  // Remove this function if not needed
  showUploads() {
    console.log('**********************************', this.state.uploading);

    if (!_.isEmpty(this.state.uploading)) {
      return <div>
        {this.state.uploading.file.name}

        <div className="progress progress-bar-default">
          <div style={{width: this.state.progress + '%'}} aria-valuemax="100"
             aria-valuemin="0"
             aria-valuenow={this.state.progress || 0} role="progressbar"
             className="progress-bar">
            <span className="sr-only">{this.state.progress}% Complete (success)</span>
            <span>{this.state.progress}%</span>
          </div>
        </div>
      </div>
    }
  },

  render() {
    if (this.data.docsReadyYet) {
      'use strict';

      let fileCursors = this.data.docs;

      // Run through each file that the user has stored
      // (make sure the subscription only sends files owned by this user)
      let display = fileCursors.map((aFile, key) => {
        // console.log('A file: ', aFile.link(), aFile.get('name'));
        let link = Files.findOne({_id: aFile._id}).link();  //The "view/download" link

        // Send out components that show details of each file
        return <div key={'file' + key}>
          <IndividualFile
            fileName={aFile.name}
            fileUrl={link}
            fileId={aFile._id}
            fileSize={aFile.size}
          />
        </div>
      });

      return <div>
        <div className="row">
          <div className="col-md-12">
            <p>Upload New File:</p>
            <input type="file" id="fileinput" disabled={this.state.inProgress} ref="fileinput"
                 onChange={this.uploadIt}/>
          </div>
        </div>

        <div className="row m-t-sm m-b-sm">
          <div className="col-md-6">

            {this.showUploads()}

          </div>
          <div className="col-md-6">
          </div>
        </div>

        {display}

      </div>
    }
    else return <div></div>
  }
});

export default FileUploadComponent;
`

**Comment by dr-dimitru** [comment]
Hello @iojanis ,

Could you show what is inside of `../../../api/Files/Files.js` file? How `File` is exported there?

Related to #572

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
