### ISSUE TITLE
Missing class properties transform.

### ISSUE THREAD

**Issue by chaudharykiran** [VeliovGroup/Meteor-Files#578]
### I'm having an issue:
  -  While building for os.linux.x86_64:    packages/ostrio:files/core.js:12:2: /packages/ostrio:files/core.js: Missing class properties transform.
- I am using Meteor 1.4.4.1
- I am using ostrio:files 1.9.7
- App is unable to start because of error. 
- I am using Ubuntu 16.04 LTS as OS.

**Comment by dr-dimitru** [comment]
Hello @chaudharykiran ,

 1. You will need to install version compatible with `meteor@1.4`
 2. What version of `ostrio:files` you're on?
 3. Please follow our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE).

**Comment by chaudharykiran** [comment]
Hello @dr-dimitru , Sorry for issue temaplate.
I am in Meteor 1.4.4.1.

**Comment by dr-dimitru** [comment]
> Sorry for issue template.

No worries. Could you please update this thread with info we request at our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE)

**Comment by chaudharykiran** [comment]
I am using ostrio:files v 1.9.7 and ostrio:cookies v 2.2.4

**Comment by dr-dimitru** [comment]
You should downgrade to `v1.7*`, try:
 - `1.7.16`, `1.7.15` or `1.7.14`

```shell
meteor remove ostrio:files
meteor add ostrio:files@1.7.16
```

**Comment by dr-dimitru** [comment]
Note - it's always a good idea to use latest available software.
We can not guarantee `meteor@1.4` and `ostrio:files@1.7` will work stable

**Comment by dr-dimitru** [comment]
@chaudharykiran there is more info requested in our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE): 
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Is it *Client* or *Server* issue?

**Comment by chaudharykiran** [comment]
@dr-dimitru I downgradef to 1.7.15 but again another error is occurring ` TypeError: FileCollection is not a function`. When should I found documentation of 1.7.15.

**Comment by dr-dimitru** [comment]
@chaudharykiran check [`v1.7.15` release](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.7.15) and [its readme](https://github.com/VeliovGroup/Meteor-Files/tree/c0a5c804dfbdca2b04f02f6be3f16118495496d7#api-overview-full-api)

**Comment by chaudharykiran** [comment]
I am very very thankful to you @dr-dimitru. Thank you once again.

**Comment by dr-dimitru** [comment]
@chaudharykiran you're welcome :)
I hope you will be able to upgrade to latest release soon.

Let me know once this issue will be solved.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
