### ISSUE TITLE
Can't get logged user in 'protected' function

### ISSUE THREAD

**Issue by danielruiz7** [VeliovGroup/Meteor-Files#58]
Hi,

I'm trying to add some security when downloading files but I can't get the user info inside the 'protected' function. My configuration looks like this:

```js
Documents = new Meteor.Files({
  storagePath: "D:/temp",
  collectionName: 'documents',
  downloadRoute: '/doc',
  allowClientCode: true,
  chunkSize: 256*128,
  protected: (fileObj) => {
    console.log(fileObj);
    return true;
  }
});
```

The file is downloaded and I can get the info of the fileObj but I tried this.userId (undefined), this.user() -gives an TypeError.. has no method 'user'. 

What am I doing wrong?

**Comment by dr-dimitru** [comment]
Hi @danielruiz7 ,

1. Make sure you have installed `accounts-base` package
2. This is server's or client's code?
   - If this is isomorphic, could you post errors for both server and client, but separately
3. What if you write code in coffee or ES5? (*not sure how babel handle this*)
4. Could you post for both `client` and `server`:
```js
console.log(this);
console.log(this.userId);
console.log(this.user()); // post full "TypeError..."
```

**Comment by dr-dimitru** [comment]
I believe it is fuinction's context issue

**Comment by danielruiz7** [comment]
Thanks for the quick response @dr-dimitru ,

- `accounts-base` is installed.
- The code is isomorphic but as I can see in the code the  checkAccess function is only called in server when downloading a file.
- Tried ES5 with `protected: function(fileObj) { ... }` instead of `protected: (fileObj) => { ... }` and tried coffee:

`@Documents = new Meteor.Files
  storagePath: "D:/temp"
  collectionName: 'documents'
  downloadRoute: '/doc'
  allowClientCode: true
  chunkSize: 256 * 128
  protected: (fileObj) ->
    console.log fileObj
    console.log 'coffee userId ' + @userId
    console.log 'coffee user() ' + @user()
    return true`

In both cases something strange happens. Protected function is called twice. First time returns te correct value and second time returns undefined for userId and user():

`I20160315-03:56:48.410(1)? { _id: 's7tNPFzF7RpyQoJp6',
I20160315-03:56:48.411(1)?   name: 'Chrysanthemum.jpg',
I20160315-03:56:48.411(1)?   extension: 'jpg',
I20160315-03:56:48.411(1)?   path: 'D:/temp/JKwJJiwbTfvaFSICv.jpg',
I20160315-03:56:48.411(1)?   meta:
I20160315-03:56:48.412(1)?   { owner_id: 'vJ6X9xqvWNv3LeZMD' },
I20160315-03:56:48.412(1)?   type: 'image/jpeg',
I20160315-03:56:48.412(1)?   size: 879394,
I20160315-03:56:48.412(1)?   versions:
I20160315-03:56:48.412(1)?    { original:
I20160315-03:56:48.413(1)?       { path: 'D:/temp/JKwJJiwbTfvaFSICv.jpg
',
I20160315-03:56:48.413(1)?         size: 879394,
I20160315-03:56:48.413(1)?         type: 'image/jpeg',
I20160315-03:56:48.413(1)?         extension: 'jpg' } },
I20160315-03:56:48.413(1)?   isVideo: false,
I20160315-03:56:48.413(1)?   isAudio: false,
I20160315-03:56:48.413(1)?   isImage: true,
I20160315-03:56:48.414(1)?   _prefix: 'cbda5a345d006e2ae0dc1900d56658701cead8180
ce53bb2dcdab660d35ee293',
I20160315-03:56:48.414(1)?   _storagePath: 'D:/temp',
I20160315-03:56:48.414(1)?   _downloadRoute: '/doc',
I20160315-03:56:48.414(1)?   _collectionName: 'documents',
I20160315-03:56:48.414(1)?   updatedAt: Mon Mar 14 2016 15:43:30 GMT+0100 (Hora
estándar romance) }
**I20160315-03:56:48.428(1)? js user() [object Object]
I20160315-03:56:48.428(1)? js userId: vJ6X9xqvWNv3LeZMD**
I20160315-03:56:48.428(1)? { _id: 's7tNPFzF7RpyQoJp6',
I20160315-03:56:48.429(1)?   name: 'Chrysanthemum.jpg',
I20160315-03:56:48.429(1)?   extension: 'jpg',
I20160315-03:56:48.429(1)?   path: 'D:/temp/JKwJJiwbTfvaFSICv.jpg',
I20160315-03:56:48.429(1)?   meta:
I20160315-03:56:48.430(1)?   { owner_id: 'vJ6X9xqvWNv3LeZMD' },
I20160315-03:56:48.430(1)?   type: 'image/jpeg',
I20160315-03:56:48.430(1)?   size: 879394,
I20160315-03:56:48.430(1)?   versions:
I20160315-03:56:48.430(1)?    { original:
I20160315-03:56:48.431(1)?       { path: 'D:/temp/JKwJJiwbTfvaFSICv.jpg
',
I20160315-03:56:48.431(1)?         size: 879394,
I20160315-03:56:48.431(1)?         type: 'image/jpeg',
I20160315-03:56:48.431(1)?         extension: 'jpg' } },
I20160315-03:56:48.431(1)?   isVideo: false,
I20160315-03:56:48.431(1)?   isAudio: false,
I20160315-03:56:48.432(1)?   isImage: true,
I20160315-03:56:48.432(1)?   _prefix: 'cbda5a345d006e2ae0dc1900d56658701cead8180
ce53bb2dcdab660d35ee293',
I20160315-03:56:48.432(1)?   _storagePath: 'D:/temp',
I20160315-03:56:48.432(1)?   _downloadRoute: '/doc',
I20160315-03:56:48.432(1)?   _collectionName: 'documents',
I20160315-03:56:48.432(1)?   updatedAt: Mon Mar 14 2016 15:43:30 GMT+0100 (Hora
estándar romance) }
**I20160315-03:56:48.433(1)? js userId: undefined
I20160315-03:56:48.433(1)? js user() undefined**
`

I also notice that when server is restarted and I try to access the file for the first time (not accessed before) fileObj returns null. This is the log:

`=> Meteor server restarted
I20160315-04:11:00.305(1)? null
I20160315-04:11:00.307(1)? js userId: vJ6X9xqvWNv3LeZMD
I20160315-04:11:00.308(1)? js user() [object Object]
I20160315-04:11:00.308(1)? null
I20160315-04:11:00.309(1)? js userId: undefined
I20160315-04:11:00.309(1)? js user() undefined`

Then when I refresh the page a couple of times I finally get the fileObj.

So of course when I put some logic in my code based on fileObj.meta I get a TypeError:

`W20160315-04:06:38.861(1)? (STDERR) TypeError: Cannot read property 'meta' of nu
ll
W20160315-04:06:38.861(1)? (STDERR)     at Object._protected (model/documents.j
s:15:1)
W20160315-04:06:38.862(1)? (STDERR)     at Files.checkAccess (packages/ostrio_fi
les/files.coffee:206:44)
W20160315-04:06:38.862(1)? (STDERR)     at Object.handle (packages/ostrio_files/
files.coffee:241:69)`

Any ideas?

**Comment by danielruiz7** [comment]
Hello,

I finally solve the problem with the combination of `protected` and `downloadCallback`. This is the code:

```js
...
  protected: true,
  downloadCallback: function(fileObj) {
    console.log(fileObj);
    console.log('js userId: ' + this.userId);
    console.log('js user() ' + this.user());

    if (!this.userId || !fileObj)
      return 401;
    if (user()._id == fileObj.meta.owner_id) {
      return true;
    }
    return 401;
  }
...
```

Thanks

**Comment by thomasspiesser** [comment]
Hey @danielruiz7 I'm having the same issue here, `this.userId` and `this.user()` both return `null`. How did you solve it?

**Comment by danielruiz7** [comment]
Hello @thomasspiesser, the following code is working for me now:

`Documents = new Meteor.Files({
  storagePath: "/Users/danielruiz/dev/temp",
  collectionName: 'documents',
  downloadRoute: '/doc',
  onbeforeunloadMessage: 'Sure?',
  allowClientCode: true,
  chunkSize: 4096*128,
  protected: function(fileObj) {
    // console.log('protected js userId: ' + this.userId);
    if (!this.userId) {
      return 401;
    }
    return true;
  },
  downloadCallback: function(fileObj) {
    // console.log(fileObj);
    // console.log('downloadCallback js userId: ' + this.userId);
    // console.log('downloadCallback js user() ' + this.user());
    // return true;
    if (!this.userId || !fileObj)
      return 401;
    if (this.user()._id == fileObj.meta.owner_id) {
      return true;
    }
    return 401;
  }
});`

Regards

**Comment by thomasspiesser** [comment]
@danielruiz7 thanks. How is it that it starting working for you I am wondering? I guess I have to file a new ticket then.
