### ISSUE TITLE
MongoError: file with id xxx not opened for writing

### ISSUE THREAD

**Issue by xxhenglyxx** [VeliovGroup/Meteor-Files#584]
Meteor-Files Version: 1.9.8
Meteor Version: 1.6.1
Issue appears on Desktop
Client or Server Issues: Server throws me a MongoError and on the client side throws me `` service unavailable. Server Error 503``
![screen shot 2018-02-27 at 11 54 14 pm](https://user-images.githubusercontent.com/28291947/36742159-8fb74676-1c19-11e8-8963-cabc05d919c9.png)

Step to reproduce the problem:

    // some test component.jsx

    ...
    fetchImage = async _ => {

        const response = await methodCall ( 'files.findOne', 'file-idxxx' );

        this.setState. ( { src: Files.link ( response ) } );

    }

    render () {

        const { src } = this.state;

        return (
            <div>
                    // click on this to simply get image link and view it, the response return just fine and i can successfully get the link, but after inject it into src, it throw me the MongoError
                    <button onClick={ this.fetchImage }>fetch</button>
                    <img src={ src } />
            </div>
        );

    }

methods for the files.findOne

    // methods.js

    'files.findOne' ( _id ) {

        // tried Files.findOne ( { _id } ) and throws me a Unhandled Promised Rejection error and maximum call stack exceed
        return Files.collection.findOne ( { _id } );

    }

methodCall.js

    const methodCall = ( ...params ) => new Promise ( ( resolve, reject ) => {

        const method = params [ 0 ];

        store.dispatch ( methodRequest ( { method } ) );

        Meteor.call ( ...params, ( error, response ) => {

            if ( error ) {

                store.dispatch ( methodFailure ( { method, error: error.reason } ) );

                return reject ( error );

            }

            store.dispatch ( methodSuccess () );

            return resolve ( response );

        });

    } );

**Comment by dr-dimitru** [comment]
Hello @xxhenglyxx ,

Thank you for reporting about this. Please update this thread following [our issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

- Post __full__ *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by xxhenglyxx** [comment]
@dr-dimitru I turned on the debug mode and see no differences in both Client and Server log. The first image is the whole error from the server and here is the client:
![screen shot 2018-02-28 at 11 01 35 am](https://user-images.githubusercontent.com/28291947/36769428-cb531900-1c76-11e8-8721-f0d5cc854551.png)
Do I have to explicitly specific the storagePath ? the default one is at ``assets/app/uploads/files`` right ? When I went into ``.meteor/local/build/programs/server/assets/app/uploads/files`` I did not see anything there

**Comment by dr-dimitru** [comment]
@xxhenglyxx to help you we need more info. Please provide a full logs from server.

> Do I have to explicitly specific the storagePath ? the default one is at assets/app/uploads/files right ?

You don't have to, but you may wish to. See [our FAQ](https://github.com/VeliovGroup/Meteor-Files#faq) for more info.

**Comment by xxhenglyxx** [comment]
This is the server log: ![screen shot 2018-02-28 at 2 43 07 pm](https://user-images.githubusercontent.com/28291947/36775719-c5656920-1c95-11e8-9a54-38a4cd2cab31.png)

**Comment by dr-dimitru** [comment]
@xxhenglyxx this isn't all logs.

There is should be: 
 - [`[FilesCollection.storagePath] Set to:`](https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L267) with path of where files will be uploaded;
 - If path isn't writable you should see [this error](https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L271).

What storage do you use? FS? GridFS? AWS? Something else?
Looks like this error is related to Mongo (*as it starts with* `MongoError`).

Could you also please post contents of `.meteor/packages` file?

**Comment by xxhenglyxx** [comment]
I use GridFS. Here is all content of .meteor/packages

    # Meteor packages used by this project, one per line.
    # Check this file (and the other files in this directory) into your repository.
    # 'meteor add' and 'meteor remove' will edit this file for you,
    # but you can also edit it by hand.

    meteor-base@1.3.0             # Packages every Meteor app needs to have
    mobile-experience@1.0.5       # Packages for a great mobile UX
    mongo@1.4.2                   # The database Meteor supports right now
    reactive-var@1.0.11            # Reactive variable for tracker
    tracker@1.1.3                 # Meteor's client-side reactive programming library

    standard-minifier-css@1.4.0   # CSS minifier run for production mode
    standard-minifier-js@2.3.1    # JS minifier run for production mode
    es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers
    ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code
    shell-server@0.3.1            # Server-side component of the `meteor shell` command

    kadira:flow-router      # FlowRouter is a very simple router for Meteor

    meteortesting:mocha               # A package for writing and running your meteor app and package tests with mocha
    johanbrook:publication-collector  # Test a Meteor publication by collecting its output
    fourseven:scss
    ostrio:files
    aldeed:collection2@3.0.0
    static-html
    alanning:roles
    accounts-password
    reywood:publish-composite
    jss:flag-icon

package.json

    "dependencies": {
        "@babel/runtime": "^7.0.0-beta.36",
        "fs-extra": "^5.0.0",
        "gridfs-stream": "^1.1.1",
        "i18next": "^10.5.0",
        "meteor-node-stubs": "^0.3.2",
        "react": "^16.2.0",
        "react-dom": "^16.2.0",
        "react-i18next": "^7.4.0",
        "react-komposer": "^2.0.0",
        "react-mounter": "^1.2.0",
        "react-redux": "^5.0.7",
        "redux": "^3.7.2",
        "simpl-schema": "^1.4.2"
     },
    "devDependencies": {
        "chai": "^4.1.2",
        "redux-logger": "^3.0.6"
    }

Images.js // previously Files.js, I just refactored it out to Images and collectionName to images, the rest stay the same

    const Images = new FilesCollection ({

    // debug: Meteor.isServer && process.env.NODE_ENV === 'development',
    debug: true,
    collectionName: 'images',
    allowClientCode: false,

    onBeforeUpload ( file ) {

        if ( file.size <= 10485760 && /png|jpg|jpeg/i.test ( file.extension ) ) {

            file.meta.public = false;
            file.meta.removed = false;
        
            return true;

        }

        return "Invalid image format";

    },

    onAfterUpload ( file ) {

        Object.keys ( file.versions ).forEach ( versionName => {

            const metadata = { versionName, file_id: file._id, stored_at: new Date () };
            const writeStream = gridfs.createWriteStream ( { filename: file.name, metadata } );

            fs.createReadStream ( file.versions [ versionName ].path ).pipe ( writeStream );

            writeStream.on ( 'close', Meteor.bindEnvironment ( uploadedFile => {

                const property = `versions.${ versionName }.meta.gridFsFileId`;

                this.collection.update ( file._id.toString (), { $set: { [ property ]: file._id.toString () } } );

                this.unlink ( this.collection.findOne ( file._id.toString () ), versionName );

            }));

        });

    },

    interceptDownload ( http, file, versionName ) {

        const _id = ( file.versions [ versionName ].meta || {} ).gridFsFileId;

        if ( _id ) {

            const readStream = gridfs.createReadStream ( { _id } );
            readStream.on ( 'error', error => { throw error; } );
            readStream.pipe ( http.response );

        }

        return Boolean ( _id );

    },

    onAfterRemove ( files ) {

        files.forEach ( file => {

            Object.keys ( file.versions ).forEach ( versionName => {

                const _id = ( image.versions [ versionName ].meta || {} ).gridFsFileId;

                if ( _id ) gridfs.remove ( { _id }, error => { if ( error ) throw error; } );

            });

        });

    }

    });

**Comment by xxhenglyxx** [comment]
I console log inside the readStream.on error, it throws error there when piping the http.response;

    interceptDownload ( http, file, versionName ) {

        const _id = ( file.versions [ versionName ].meta || {} ).gridFsFileId;

        if ( _id ) {

            const readStream = gridfs.createReadStream ( { _id } );
            readStream.on ( 'error', error => {

               // error occured when piping the http.response for serving file from GridFS
                console.log ( "***********" ); 
                console.log( error ); 
                throw error; 

            } );
            readStream.pipe ( http.response );

        }

        return Boolean ( _id );

    },

**Comment by xxhenglyxx** [comment]
I tried subscribing to the collection and link the image to see if it makes any different, but it output the same error.

![screen shot 2018-03-01 at 7 54 33 am](https://user-images.githubusercontent.com/28291947/36821635-7f33bec0-1d26-11e8-8b57-402b48e346b3.png)

![screen shot 2018-03-01 at 7 58 44 am](https://user-images.githubusercontent.com/28291947/36821667-a5b57430-1d26-11e8-8212-eb6a97427c61.png)

**Comment by dr-dimitru** [comment]
@xxhenglyxx 
 1. Place `ostrio:files` above `kadira:flow-router` (at `.meteor/packages`), as it may interfere on middleware;
 2. This is GridFS issue, for more read:
    - https://stackoverflow.com/questions/30872110/extract-file-from-mongodb-using-gridfs-file-with-id-not-opened-for-writing
    - https://github.com/aheckmann/gridfs-stream/issues/111
 3. At screenshots I see you're requesting a file, but how it was placed into the collection, where is upload?
 4. This error very rare for GridFS, please make sure requested file exists, and not corrupted at MongoDB. For clean tests run `meteor reset`, perhaps data is corrupted.

**Comment by xxhenglyxx** [comment]
I have placed ``ostrio:files`` on top of ``kadira:flow-router`` now and did a meteor reset, re upload the image and link it but it still output the same error. After it is inserted, it will exist in ``assets/app/uploads/images`` isnt it ? I did not see it inside the folder but only in database record.
Does the output after the file inserted correct ? It should not removed after insert right ?
![screen shot 2018-03-01 at 8 48 30 pm](https://user-images.githubusercontent.com/28291947/36847815-0cac3c94-1d92-11e8-9122-4e3d047bb132.png)

**Comment by dr-dimitru** [comment]
@xxhenglyxx 
 1. Try to upload and view files without GridFS, doest it work?

> After it is inserted, it will exist in `assets/app/uploads/images` isnt it ?

It isn't. The file is removed after moving to GridFS, at this line:
```js
this.unlink(this.collection.findOne(file._id.toString()), versionName);
```

> Does the output after the file inserted correct ?

Looks good

> It should not removed after insert right ?

Removed, after moved to GridFS.

**Comment by xxhenglyxx** [comment]
@dr-dimitru  Yes, upload and view file without GridFS works fine.

**Comment by dr-dimitru** [comment]
@xxhenglyxx great.
Now please review your GridFS integration implementation. Make sure you're [following our tutorial](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration), for more info take a look at [advanced integration with streaming support](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS---206-Streaming)

**Comment by xxhenglyxx** [comment]
I reviewed it three times and first I noticed that the metadata of file instead of ``image_id`` I have changed it to ``imageId`` and also ``store_at`` to ``storeAt`` in the ``onAfterUpload`` method, where ``const meta = {..., imageId: file._id };``, second time I just added the ``storagePath``. Third time which I review again of the GridFS integration implementation and I did not see anything wrong there.
Could you please help me take a look at it ? Here is the codes: [Uploading codes.txt…]()

**Comment by dr-dimitru** [comment]
@xxhenglyxx 
try to wrap interceptDownload into try..catch:
```js
interceptDownload ( http, file, versionName ) {

    const _id = ( file.versions [ versionName ].meta || {} ).gridFsFileId;

    if ( _id ) {
        try {
           const readStream = gridfs.createReadStream ( { _id } );
           readStream.on ( 'error', error => { throw error; } );
           readStream.pipe ( http.response );
        } catch (_e) {
           return false;
        }

    }

    return Boolean ( _id );

},
```

**Comment by xxhenglyxx** [comment]
Wrapping the interceptDownload around ``readStream`` inside the ``_id`` block still throws me the same error. Instead of wrapping try/catch, I return false inside the ``onError`` callback of readStream so it that stop it from throwing error, But that still did not solve the problem.
I can see the file is being downloaded and it linked to it but the image did not show.
![screen shot 2018-03-02 at 12 20 09 am](https://user-images.githubusercontent.com/28291947/36858962-9b9e6662-1daf-11e8-9531-1e048a88165d.png)
![screen shot 2018-03-02 at 12 20 21 am](https://user-images.githubusercontent.com/28291947/36858974-a05027ea-1daf-11e8-9c08-f8d1040ed76d.png)

**Comment by dr-dimitru** [comment]
@xxhenglyxx previously you've said you see a record at MongoDB, do you see a File at GridFS related collections?

**Comment by xxhenglyxx** [comment]
Yes. Here is the screenshot of the record. It has only one record. The ``__pre_images`` is empty though.
![screen shot 2018-03-02 at 9 13 11 am](https://user-images.githubusercontent.com/28291947/36880215-08f609b4-1dfa-11e8-9b1a-7311b5fbd863.png)

**Comment by dr-dimitru** [comment]
@xxhenglyxx just tested GridFS at our [GridFS test repository](https://github.com/VeliovGroup/files-gridfs-autoform-example), feel free to download it and test on your end.

Please note a comment [here](https://github.com/VeliovGroup/files-gridfs-autoform-example/blob/master/lib/images.js#L43). Try to wrap `gridFsFileId` into `new Mongo.ObjectID()`:

```js
interceptDownload ( http, file, versionName ) {

    const _id = new Mongo.ObjectID((file.versions [ versionName ].meta || {} ).gridFsFileId);

    if ( _id ) {
        try {
           const readStream = gridfs.createReadStream ( { _id } );
           readStream.on ( 'error', error => { throw error; } );
           readStream.pipe ( http.response );
        } catch (_e) {
           return false;
        }

    }

    return Boolean ( _id );

},
```

**Comment by xxhenglyxx** [comment]
@dr-dimitru after wrapping it with ``new Mongo.ObjectID ()`` it output this error:

![screen shot 2018-03-02 at 10 03 24 pm](https://user-images.githubusercontent.com/28291947/36905286-98487f5a-1e65-11e8-9bc6-c902d331ed3f.png)

Then I tried wrapping the whole thing with try catch:

    interceptDownload ( http, file, versionName ) {

        try {

            const _id = new Mongo.ObjectID ( ( file.versions [ versionName ].meta || {} ).gridFsFileId );

            if ( _id ) {

                const readStream = gridFs.createReadStream ( { _id } );
                readStream.on ( 'error', error => { throw error; } );
                readStream.pipe ( http.response );

            }

            return Boolean ( _id );

        } catch ( error ) {

            console.log ( error );

        }

    }

Then I get this kind of error:

![screen shot 2018-03-02 at 10 07 34 pm](https://user-images.githubusercontent.com/28291947/36905518-27aad6de-1e66-11e8-9db6-45e3ecdcac92.png)

This is how I fetch the image on the Client side:

    // Test.jsx

    class Test extends React.Component {

        ...

        fetch = () => {

            const { images } = this.props;

            if ( images.length ) {

                this.setState ( { src: Images.link ( images [ 0 ] } );

            }

        }

        render () {

            const { src } = this.state;

            return (
                <div>
                    <button onClick={ this.fetch } >fetch</button>
                    <img src={ src } />
                </div>
            );

        }

    }

    const composer = function ( props, onData ) {

        const subscription = Meteor.subscribe ( 'publicImages' );

        if ( subscription.ready () ) {

            const images = Images.find ().fetch ();

            onData ( null, { subscription, images, loading: false } );

        }

        onData ( null, { loading: true } );

    }

    export default compose ( trackerLoader ( composer ) ) ( connect ( mapStateToProp ) ( Home ) );

    // publications.js

    Meteor.publish ( 'publicImages', function () {

        return Images.find ( { meta: { public: true, removed: false } } ).cursor;

    })

**Comment by dr-dimitru** [comment]
@xxhenglyxx something is wrong with your setup. It works smoothly for other folks.
 
 1. This is actually interesting (*might be helpful*) error, please do `console.log((file.versions [versionName].meta || {}).gridFsFileId);` at `interceptDownload` and `console.log(file._id)` at `onAfterUpload`;
 2. This is related only to *Server*, your *Client* code is fine;
 3. I suggest you to check other [GridFS related issue](https://github.com/VeliovGroup/Meteor-Files/issues?utf8=✓&q=label%3AGridFS+) you may find something to help you.

**Comment by xxhenglyxx** [comment]
I did a meteor reset after adding ``console.log`` both id at ``interceptDownload`` and ``onAfterUpload``, upload a file and link them, they bot had the same id and yes same error lol.
![screen shot 2018-03-02 at 11 59 06 pm](https://user-images.githubusercontent.com/28291947/36911359-e26f5c92-1e75-11e8-93c2-ea848ea43a39.png)

**Comment by xxhenglyxx** [comment]
@dr-dimitru I finally found the problem. It was a very very very silly mistake that I have made and cost me days of thinking of this.

        writeStream.on ( 'close', Meteor.bindEnvironment ( uploadedFile => {

            const property = `versions.${ versionName }.meta.gridFsFileId`;

            // it should be uploadedFile._id.toString () but not file._id.toString ();
            this.collection.update ( file._id.toString (), { $set: { [ property ]: file._id.toString () } } );

            this.unlink ( this.collection.findOne ( file._id.toString () ), versionName );

        }));

After adding the ``new Mongo.ObjectID``, it gives clearer error message that the id was not exist, and the GridFS related issues u pointed me to #341, that it exist in mongo record does not mean it exist in FS. So I went to compare again against the wiki at the ``afterUpload`` hook and then saw the mistake

**Comment by dr-dimitru** [comment]
@xxhenglyxx Mistakes teach you.

I'm glad to be helpful :)
That's why I keep telling to compare your code to our working tutorials and demo repositories.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
