### ISSUE TITLE
_preCollection options 

### ISSUE THREAD

**Issue by Gariest** [VeliovGroup/Meteor-Files#585]
Hi,

I'd wonder if we could add options to _preCollection, since if you defined your options to your Files collection, those don't pass into _preCollection. I'd like to used it to add mainly _suppressSameNameError.

Thanks in advance!

**Comment by Gariest** [comment]
Hello,
is something wrong with this request?
Thanks.

**Comment by dr-dimitru** [comment]
Hello @Gariest ,

Yes, suggested approach is a bit different from what we have for main underlying Mongo collection.
We like your suggestion, but want to switch "options" in favor of *Mongo.Collection* instance.

In current implementation you can pass a *Mongo.Collection* instance or its name (see [docs here](config.collection)), we suggest to add:
 - `preCollectionName` - {*String*} - [Server]
 - `preCollection` - {*Mongo.Collection*} Instance - [Server] - You can pass your own Mongo Collection instance {preCollection: new Mongo.Collection('preMyFiles')}

wdyt?

**Comment by Gariest** [comment]
Sure, no problem. I will update my PR according to your suggestion. :)

Thanks.

**Comment by dr-dimitru** [comment]
Merged and published as [`v1.9.9`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.9)
