### ISSUE TITLE
Delete file from FS on deletion from collection via MongoDB-manager?

### ISSUE THREAD

**Issue by natschoman** [VeliovGroup/Meteor-Files#589]
Hello,

I want to switch from CollectionFS to this very nice and well maintained package.
One thing I am missing a little bit is that in CollectionFS files get removed from the filesystem if the documents where removed directly from the collections via a DB-manager (eg. Robomongo).

Is this anyhow possible with Meteor-Files?

Thanks

**Comment by dr-dimitru** [comment]
Hello @natschoman ,

Unfortunately, not.
If you're using GridFS storage, it would work, but you should remove it from both FilesCollcrion and GridFS manually.

For all other cases [`.remove()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/remove) should be called.
