### ISSUE TITLE
Upload pause not working

### ISSUE THREAD

**Issue by danielruiz7** [VeliovGroup/Meteor-Files#59]
Hello,

I get the following client error when I try to pause a file upload:

`TypeError: Cannot read property 'get' of undefined
    at Meteor.Files.Files.insert.Meteor.isClient.result.toggle (files.coffee:791)`

files.coffee:791

```js
...
          toggle: () ->
            if @onPause.get() then @continue() else @pause() 
...
```

This is how I call the funcion:

```js

       this.insert;
       this.addFile = (files) => {
        ...

         this.insert = Documents.insert({
          ...
         });
      }

      this.togglePause = () => {
        if (this.insert !== undefined) {
          this.insert.toggle.call();
        }
      }

```

`this.insert.onPause` is returning false. Why @onPause is undefined?

**Comment by danielruiz7** [comment]
Sorry! my mistake.

I was wrong using .call();

just simply `this.insert.toggle` and it works.

**Comment by danielruiz7** [comment]
I solved this by adding this.insert as thisArg of the call function:

```js
this.insert.toggle.call(this.insert);
```

**Comment by dr-dimitru** [comment]
Hi @danielruiz7 
Glad you loved this one.
But why not just?:
```js
this.insert.toggle();
```

**Comment by dr-dimitru** [comment]
Please see [this line](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo/client/upload-form.coffee#L11) in demo app. Same is applying for `toggle` method

**Comment by danielruiz7** [comment]
You are right!

Too many hours working hehe

Nice package by the way ;-)

**Comment by dr-dimitru** [comment]
@danielruiz7 thank you, I appreciated you found my work useful.
Do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Meteor file upload - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)
