### ISSUE TITLE
Setting disableDownload to true also prevents upload

### ISSUE THREAD

**Issue by afiouni** [VeliovGroup/Meteor-Files#593]
When I use disableDownload: true in the constructor (on server), files fail to upload (over HTTP) and I get the following error on client console:

> Something went wrong! [sendEOF] method doesn't returned JSON! Looks like you're on Cordova app or behind proxy, switching to DDP transport is recommended.

Any feedback why this is happening, or how I can prevent the error while still preventing downloads?

**Comment by dr-dimitru** [comment]
Hello @afiouni ,

We can not reproduce this issue as you've described. We're running tests on our demo app, toggling [this line](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js#L65).

Please update this thread following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE).

  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  - Post sample of *FilesCollection* constructor configuration you're using on both *Client* and *Server*

**Comment by dr-dimitru** [comment]
@afiouni bug confirmed, hold on for update

**Comment by dr-dimitru** [comment]
Fixed and published as [`v1.9.9`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.9)
@afiouni Please let me know how it works on your end.

**Comment by afiouni** [comment]
Working great as expected... thank you :)

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
