### ISSUE TITLE
Files corrupted on download

### ISSUE THREAD

**Issue by FrancisBou** [VeliovGroup/Meteor-Files#595]
- Version of `Meteor-Files` **latest**
  - Version of `Meteor` **1.6.1**
  - Browser name and its version? **Every**
  - I'm using filesystem upload (default)

The files are uploaded properly, I can open them from the upload  folder where they are uploaded without issue.
However using this code to download the file starts the download properly but the size of the downloaded file is similar "not equal" to the file in the upload folder (sometimes bigger). I can't open the file, office/adobe says the file is corrupted. Images are currupted too.

`<a href="{{link}}?download=true" download="{{name}}" target="_parent">Télécharger</a>`

**Comment by dr-dimitru** [comment]
Hello @FrancisBou ,

We need more info:
 1. Screenshot of "Network" tab in DevTool where downloaded file is selected and "Headers" section is visible
 2. Please, post contents of `.meteor/packages` file

**Comment by FrancisBou** [comment]
Hi dr-dimitru,

Unfortunalety I can't get the download to show in the network tab, I've got no filter and "all" is selected, recording is on ,not sure why it's not there.

**package file**
`meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library
standard-minifier-css@1.4.0   # CSS minifier run for production mode
standard-minifier-js@2.3.1    # JS minifier run for production mode
es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command
accounts-base
accounts-password
useraccounts:bootstrap
accounts-ui
percolate:migrations
alanning:roles
kadira:flow-router
kadira:blaze-layout
session
arillo:flow-router-helpers
aldeed:template-extension
mdg:validated-method
mdg:validation-error
aldeed:simple-schema
aldeed:collection2
msavin:sjobs
http
percolate:paginated-subscription
ostrio:files
`

**Comment by dr-dimitru** [comment]
@FrancisBou , thank you for update.

 1. Okay, you always can do `curl -v "http://localhost:3000/link/to/the/file"`
 2. Move `ostrio:files` to the line __above__ `kadira:flow-router` - *This should solve the issue*

Let me know if it helped.

**Comment by FrancisBou** [comment]
It seems that the link method returns an empty value, the downloaded file is in fact HTML, that's a bit embarassing! I saw you can use the "fileURL" helper and it works. Thanks so much @dr-dimitru

**Comment by dr-dimitru** [comment]
@FrancisBou `link` should work too. But it depends from how you iterate over the cursor.
Could you share your HTML+Blaze Template code?

**Comment by FrancisBou** [comment]
I iterate using each: 
```
{{#each communiques}}
  <a class="list-group-item" href="{{link}}?download=true" download="{{name}}" target="_parent">
    <i class="fa fa-file-pdf-o fa-fw"></i> {{ meta.nom }}
  </a>
{{/each}}
```
```
Template.communiques.helpers({
  communiques() {
    return Communiques.find({});
  }
});
```

**Comment by dr-dimitru** [comment]
To have access to all features you should iterate using `.each` property:
```spacebars
{{#each communiques.each}}
  <a class="list-group-item" href="{{link}}?download=true" download="{{name}}" target="_parent">
    <i class="fa fa-file-pdf-o fa-fw"></i> {{ meta.nom }}
  </a>
{{/each}}
```

**Comment by FrancisBou** [comment]
dr-dimitru I should have read more carefully, thanks for the help!

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
