### ISSUE TITLE
Cleanup filenames at start/at end of upload(?)

### ISSUE THREAD

**Issue by edovino** [VeliovGroup/Meteor-Files#596]
Meteor-Files version: 1.9.0
Meteor version: 1.5.4.1
OS: Occurs At least on OS X and Linux, with Chrome (tested with v. 65.0.3325.181 on linux)

What would be the correct way to sanitize filenames? 
Sometimes users upload files that contain comma's in the filename, and recently Chrome has started choking on that: The filename*=UTF-8' content disposition header that's generated during downlaod contains the unquoted original filename (which is the correct way of doing this, I believe), but Chrome will currently (incorrectly, I believe) give a ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION error, and cancel the download.
I've verified that this problem can be fixed by manually updating the 'name' attribute in the file-uploads collection, but I'm not sure what's the best way of fixing this in code.

**Comment by dr-dimitru** [comment]
Hello @edovino ,

Please update your question following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Screenshot of the error in "DevTools" -> "Network" tab + "Headers" tab
  - Example of file name you're experiencing this issue


Issue you've described was fixed few months ago, every release tested agains next file names:
 - Special chars: `One-±!@#$%^&*()_+|?\/';';.,><Pixel,Pink.jpg`
 - Double extension + very long name: `appletouchiconprecomposedappletouchiconprecomposedappletouchiconprecomposedappletouchiconprecomposed.png.png`
 - Multiple comas: `file,with,comw,in,name.jpg`
 - Multiple dots: `meteor......many....dots...file..name..JPG`
 - Mixed encoding: `Αντίγραφο της Coca-Cola Wall.JPG`
 - Cyrillic: `кока-кола стена копия.JPG`
 - Glyphs: `コカ・コーラウォールコピー.JPG` and `可口可乐墙副本.JPG`

**Comment by dr-dimitru** [comment]
> what's the best way of fixing this in code

Just set `fileName` option in [`.insert()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)). On server in a [`onAfterUpload` event/hook](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor#use-onafterupload-to-avoid-mime-type-andor-extension-substitution) you may check `name` property of the file's object and update it in case if it contains any of the forbidden symbols.

**Comment by edovino** [comment]
Thank you for your fast & extensive response!
I'll keep the onAfterUpload hook in mind if I need to do more manipulations, for now upgrading to Meteor-Files 1.9.7 fixed it. Should have tried that first - sorry!

**Comment by dr-dimitru** [comment]
@edovino I'm glad this one is solved, in a such easy way :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
