### ISSUE TITLE
Streaming video on ios mobile application

### ISSUE THREAD

**Issue by rolljee** [VeliovGroup/Meteor-Files#597]
# This is a question, not an issue

Hello @dr-dimitru 

I'm currently trying to stream my file to an ios application.

The stream is working perfectly on the web app, but once I go to the mobile app the playback could not launch.

Have you ever experienced this kind of problems? and is there any known issue on this?

Permission maybe? I don't really know where to look if this is Cordova related? or  Meteor-files not being able to stream the file on mobile?

Let you know that making a shortcut on mobile using safari is working to make the video launch on the video element.

**Comment by dr-dimitru** [comment]
Hello @rolljee ,

What type of the file you're steaming?

From my experience it's ends up with selecting format, encoder, frame-rate, keyframe timing and etc.

**Comment by dr-dimitru** [comment]
@rolljee yes, generated URL can be changed using `--mobile-server` exclusively for Cordova, since [`v1.9.8`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.8), see #547 for more details.

wdyt?

**Comment by rolljee** [comment]
Okay ! didn't saw it since it's the first time i ran into this issue using Cordova.

I didn't deep dive into the process that prepare the download, but i from what i see

We cannot download the download a file if the Meteor.absoluteUrl() don't match the current URL i'm pn.

I just think we should be able to download the file regardless of the url we currently are :)

I cannot work on this for now, but i'll soon be able to dive a bit into that process to see if we might find a correct answer on this.

You think it make sense ? or am i wrong ?


------------------

# regarding the first subject of the issue

I found the way to create the link on cordova but i ran into a `File not found`

Should it be the downloadCallback witch return false on Meteor.isCordova ?

**Comment by dr-dimitru** [comment]
> I just think we should be able to download the file regardless of the url we currently are :)

Feel free to generate URL in a way you want, I don't see an issue in having your own custom function.

> Should it be the downloadCallback witch return false on Meteor.isCordova ?

Why it returns `false` on Cordova?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by rolljee** [comment]
Oh yeah, sorry about that I've been working on a lot of other fields lately, I'll reopen it as soon as I'll getting back to this Cordova stuff.
