### ISSUE TITLE
What should I set my FilesCollection.storagePath to on deployment?

### ISSUE THREAD

**Issue by zacharyabolton** [VeliovGroup/Meteor-Files#599]
Hello,

My deployment will not persist on new version push. I'm deploying my first app (just for fun) on Galaxy, and using MongoDB through Compose as my database provider. On each new version push, all the data stays, but the actual file (which I've limited to PDFs only for the time being) cannot load. Pardon my ignorance, but I do not know if they are gone, or simply inaccessible. Through compose, my collection still contains all the data it should. The app just does bring up the file, like it was beforehand. I understand that I should not set my storagePath to anywhere inside the .meteor folder, since this rebuilds constantly, but I am lost as to where to set it to. I have tried a lot of different things to no avail. Currently, I have it set to '/'.

Thanks for any help!
-Z

**Comment by dr-dimitru** [comment]
Hello @zacharyabolton  ,
 
 1. Galaxy [has no persistent storage](https://galaxy-guide.meteor.com/file-storage.html). So, you need to use [third party storage](https://github.com/VeliovGroup/Meteor-Files/wiki/Third-party-storage)
 2. Set it to `/meteor-app/uploads`, create directory `sudo mkdir -p /meteor-app/uploads` and set permissions `sudo chmod 777 -R /meteor-app`

**Comment by zacharyabolton** [comment]
Hey @dr-dimitru,

I'm using Compose which I thought was that. I set up my MONGO_URL and ROOT_URL in my settings.json file (I think correctly) as well as other setup steps. I was under the impression that my databases and associated data would be stored here and would be served to the app when needed. The distribution seems to be setup correctly since when I ad a document on the front-end, my Compose mongo collection insert a matching document on the backend. Is that just meta data, and it won't actually store the document itself?

I really appreciate your help. I know I likely sound like an imbecile, but I'm very new to coding in general, and I've been stuck on this for days.

-Z

**Comment by dr-dimitru** [comment]
@zacharyabolton to store files in a MongoDB,  you should [use GridFS](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration).

By default files stored on FS, and its description (*a.k.a. meta-data*) stored in DB.

**Comment by zacharyabolton** [comment]
@dr-dimitru,

That's what I'll do then. I've been looking at the GridFS documentation. Is GridFS like an auxiliary to help with storing files in my MongoDB, such as my distribution with Compose? Or does it render a service like compose unnecessary?

**Comment by dr-dimitru** [comment]
@zacharyabolton what is Compose? Link?

**Comment by zacharyabolton** [comment]
https://www.compose.com

**Comment by dr-dimitru** [comment]
@zacharyabolton GridFS is build on top of MongoDB, no need to have anything "special". It just works on any MongoDB.

**Comment by zacharyabolton** [comment]
@dr-dimitru so it basically just allows for file-storage like I'm trying to accomplish. If I implement it I should be able to get ostrio:files, GridFS, and my Compose MongoDB distribution to all cooperate and upload/serve PDF files?

**Comment by zacharyabolton** [comment]
@dr-dimitru, I've started implementing it. What should I make the downloadRoute? The same as storagePath?

**Comment by dr-dimitru** [comment]
> What should I make the `downloadRoute`?

Anything you like, it's just a fence

> The same as `storagePath`?

no, no, no. Those two options aren't related.

**Comment by dr-dimitru** [comment]
>  If I implement it I should be able to get ostrio:files, GridFS, and my Compose MongoDB distribution to all cooperate and upload/serve PDF files?

Not, actually.

 1. Meteor + `ostrio:files` + `gridfs` NPM package + other libs and packages are on your server
 2. `GridFS` is a standard which describes how to upload, store, and query files in MongoDB, `gridfs` NPM package - is a package which implements and follows this standard
 3. MongoDB at Compose

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
