### ISSUE TITLE
Playing video with "?play=true"

### ISSUE THREAD

**Issue by marcchapeau** [VeliovGroup/Meteor-Files#60]
Thank you for this good meteor package.

When I upload a video file and I try to play it on Google Chrome (Desktop), it works perfectly but with an other browser, for example Mozilla Firefox, you can just read the first few seconds an it stops. And with Safari it just does not work.

You can experiment that with the Meteor-Files live demo. Upload the demo video file of the VideoJS website (playing well on all the browser mobile/desktop).

Thx.

**Comment by dr-dimitru** [comment]
Hi @marcchapeau ,
I'm glad you like this package.

I believe your issue is related to #53 
Please confirm you're converting video to required formats to support all browsers, see [caniuse video](http://caniuse.com/#search=video)

But at the same time it is not explains why video stops. In terms of demo app (hosted on meteor) it may be speed issue, as meteor platform for demo apps is not good in performance and speed. Have you tested it locally?

**Comment by marcchapeau** [comment]
Thx for your answer.

Yes, I tested it locally and on production with my own dedicated server with the same result. As I said,  the demo video file of VideoJS works on all browser so it is probably not a video format issue. The only difference i can see is that on VideoJS, the video is directly served from server and with your package and the "?play=true" request the video is manually served with partial-range http request. Of course, I tried to directly put the same video file in the meteor public folder and it works perfectly (without using your package).

Maybe this is due to the implementation of the "partial-range" between the different browsers...

Thanks for your help.

**Comment by dr-dimitru** [comment]
`partial-range` is tested on most browsers in major version. If wrong part or length of chunk is returned in headers, you should see error in "Network" tab of dev-tools (in Chrome for example). Are you sure file is served by Meteor (nodejs), not a proxy server, like nginx or Apache?

1. Do you have any errors, js or network, or any other?
2. You're playing video by build-in `video` tag or with using third-party js-video-player?

**Comment by marcchapeau** [comment]
With Chrome in network tab of dev-tools i can see each partial-range request without problem. With Firefox, it's strange because there is no line representing the partial-range request.
When i try this on my own environnement, i get exactly the same result with your live demo. I just uploaded the video on your demo website ([http://_.meteor.com/pixQjkAa4DLC5WvEH](url)).

I think this is not an environnement problem.

Sorry for your time but I try to solve this problem without success and your package is the only one working good to upload and serve video file with meteor (except this little problem ^^)

**Comment by dr-dimitru** [comment]
Confirmed, only in FF.
What I see right now, the FF is not requesting next chunk from server after receiving `206` response code, and keeps playing first chunk. On screenshot you can see correct response and headers.

Could you please try third-party player, it should fix this issue, as they know how to handle such cases.
Or try to use link without `?play=true` query, and/or try to use `?download=true` query (both methods will increase sever's CPU and memory usage).

Sorry, I but I don't have time now to code and play around with settings. But I'm able to answer for any further questions. And do not forget to tell about your solution.

![screen shot 2016-03-21 at 7 00 34 pm](https://cloud.githubusercontent.com/assets/1686778/13924909/abf4d27a-ef9f-11e5-96d7-cc2949e46813.png)

**Comment by dr-dimitru** [comment]
Hey @marcchapeau ,
Any news on your end?

**Comment by marcchapeau** [comment]
Sorry, I was working on another project.

But yes, I have some news. I tried to a third party player (videoJs) and there is the same problem. With Chrome, it works perfectly and with FF always the same first chunk.

I tried with and without `?play=true`, and with `?download=true` but there is always the problem. The only difference is with `?download=true`, you can right click on the video player to download the file. Without  `?download=true` or with `?play=true`, the dowloaded file is an empty file.

So sorry but i did not find a solution to solve this problem...

**Comment by dr-dimitru** [comment]
@marcchapeau I've [called for help of community](https://twitter.com/smart_egg/status/712664815848841216), you may would like to spread it bigger (*as i don't have much followers*).
Or/and aside to it, you can ask on [SO](http://stackoverflow.com). Reference this thread, with tags of `firefox`, `node.js`, `a/v streaming`, `meteor`

**Comment by dr-dimitru** [comment]
@marcchapeau any news around this issue?

**Comment by dr-dimitru** [comment]
Hi @marcchapeau could you please check on your end, if this issue is solved at latest release?

**Comment by marcchapeau** [comment]
Sorry but unfortunately the problem does not seem to be resolved.
With Chrome it works well, but with FF only the the first chunk is sent to the browser.

Thank you for the support of Meteor 1.3.

**Comment by dr-dimitru** [comment]
Heads up, this issue was solved in 1.4.0, could you please confirm on your end?

BTW if you're curious what it was caused by, read:
 - [Mozilla Bug 1182869](https://bugzilla.mozilla.org/show_bug.cgi?id=1182869)
 - [Mozilla Bug 570755](https://bugzilla.mozilla.org/show_bug.cgi?id=570755)
 - In a short form: *Do not use Content-Length within Content-Encoding: chunked and 206 response code*
