### ISSUE TITLE
After file upload, file is not existed in local file storage

### ISSUE THREAD

**Issue by seniordev555** [VeliovGroup/Meteor-Files#601]
After file upload is finished, it shows such messages in console.
![image](https://user-images.githubusercontent.com/17595822/38866140-922a4ac0-4248-11e8-8c10-3834c3b6da81.png)

So there is no file saved in storage.

Does anyone face this problem before?

My version is ostrio:files@1.9.5 & METEOR@1.6.0.1

**Comment by dr-dimitru** [comment]
Hello @seniordev555 ,

Thank you for reporting this. We need more info, please follow [our issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  - Could you update to the [latest release](https://github.com/VeliovGroup/Meteor-Files/releases)?
  - Are you using `http` or `ddp` upload protocol?
  - What are you using for `storagePath` option?
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by dr-dimitru** [comment]
@seniordev555 for the no.5 we would like to see screenshot or copy/pasted text from server and client logs (console)

**Comment by seniordev555** [comment]
This is the model class:
`const fileSchema = {
  ...FilesCollection.schema,
  verified: {
    type: Boolean,
    defaultValue: false
  }
};

const File = new FilesCollection({
  collectionName: 'files',
  schema: fileSchema,
  storagePath: process.env.UPLOAD_FILES_PATH || '/uploads/files',
  allowClientCode: true,
  debug: true,
  downloadCallback(fileObj) {
    if (this.params.query.download == 'true') {
      // Increment downloads counter
      File.update(fileObj._id, {$inc: {'meta.downloads': 1}});
    }
    // Must return true to continue download
    return true;
  },
  onAfterUpload(fileObj) {
    if (fileObj.meta && fileObj.meta.crypto) {
      Meteor.call('file.encrypt', fileObj.path);
    }

    return true;
  }
});`


This is the console when file is uploaded:
![image](https://user-images.githubusercontent.com/17595822/38877753-14366d68-4268-11e8-9a95-07d58117bd15.png)

**Comment by seniordev555** [comment]
As you can see, after file is uploaded, it is automatically removed and said `removeUnfinishedUpload`.

So file is not saved in local storage.

**Comment by dr-dimitru** [comment]
@seniordev555 please try to upload file without using Schema.

**Comment by dr-dimitru** [comment]
Is the `/uploads/files` path exists? What permissions does it have?

**Comment by seniordev555** [comment]
process.env.UPLOAD_FILES_PATH has own value for file path.

/Volumes/Data/Work/project/files

This folder exists.

**Comment by dr-dimitru** [comment]
Is it writable? [What permissions](https://en.wikipedia.org/wiki/File_system_permissions) does it have?

**Comment by dr-dimitru** [comment]
Try with setting `777`:

```shell
sudo chmod -R 777 /Volumes/Data/Work/project/files
```

**Comment by seniordev555** [comment]
This is the updated file permission:
![image](https://user-images.githubusercontent.com/17595822/38883601-2107300a-4276-11e8-9154-2811310ac10e.png)


Still removed:
![image](https://user-images.githubusercontent.com/17595822/38883620-2bbe862e-4276-11e8-8f9a-35c19a5d1d21.png)

**Comment by dr-dimitru** [comment]
@seniordev555 please update to the latest release [`v1.9.10`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.9.10). This release __may__ solve your issue.

**Comment by seniordev555** [comment]
Let me try.

**Comment by seniordev555** [comment]
Hmm, I think 1.9.10 is suitable for meteor 1.6.1.1

But my meteor project is 1.6.0.1 and it shouldn't upgrade due to some reason.

**Comment by dr-dimitru** [comment]
@seniordev555 so what version you're on now?
Latest and current version are for `meteor@1.6.1` and newer.

**Comment by seniordev555** [comment]
My meteor version is 1.6.0.1

And ostrio:files version is 1.5.6.

For some reason, I am not able to upgrade my meteor version.

**Comment by seniordev555** [comment]
I can upgrade to v 1.9.4.

But still have same issue

**Comment by seniordev555** [comment]
The problem is that I've used same code in other project and it is working well.

Only in this project, I'm not able to save uploaded files.

Very strange behavior.

**Comment by dr-dimitru** [comment]
Have you tried?:
```shell
meteor reset
meteor npm update --save
meteor update --all-packages
meteor npm remove meteor-node-stubs && meteor npm install meteor-node-stubs
meteor npm install core-js @babel/runtime@^7.0.0-beta.44
```

**Comment by dr-dimitru** [comment]
@seniordev555

> Why is file deleted after finish uploading?

for the some reason it has no special flag which gives a signal what file is fully written to FS (e.g. uploaded).

**Comment by dr-dimitru** [comment]
@seniordev555 have you found a way to update to the latest Meteor and package release?

**Comment by seniordev555** [comment]
> for the some reason it has no special flag which gives a signal what file is fully written to FS (e.g. uploaded).

Could we catch the error with try-catch block? So if there is no error, it doesn't call such method like removed or removedUnfinishedUpload event or something else.

**Comment by dr-dimitru** [comment]
> Could we catch the error with try-catch block?

No everything is asynchronous. I believe something wrong with your setup. Try to omit `storagePath` and let to the package manage it, let's see if it upload will work this way. Also, have you tried to use `ddp` for upload transport? I recommend to try different options.

**Comment by seniordev555** [comment]
Due to **[_preCollectionCursor.observe] [removed]** and **[_preCollectionCursor.observe] [removeUnfinishedUpload]**, the file is not saved.

DDP and HTTP are not working.

**Comment by dr-dimitru** [comment]
Hello @seniordev555 any news on this one? Have you found a solution?
Have you upgraded to the latest release?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by aspirinchaos** [comment]
i have the same problem.
i start 2 apps on 1 mongo. i had a different `storagePath`  for same collection.
in app **A**: `path/to/folder`
in app **B**: `/path/to/folder` <- upload file in this app
fix `storagePath` in app **A** resolve issue.

**Comment by dr-dimitru** [comment]
Hello @aspirinchaos,

Yes, as stated in our [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq), - we've always recommend to use absolute path, as in your *B* server example
