### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by zacharyabolton** [VeliovGroup/Meteor-Files#604]
I have been trying to utilize ostrio:files with little success. I know that this is due to my own ignorance rather than the technology itself, but I'm looking for guidance. I have a database set up at mlab.com and have used the mongo URL to successfully deploy my app on Galaxy. The app definitely has access to the mlab DB because it's pulling the metadata from the objects, however I cannot get it to download the actual files which I'm uploading. I'm using fs & gridfs-stream as outlined here: https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration and when I first deploy my app it has the collection, Docs,  which I defined with `export const Docs = new FilesCollection({ [...] })`. However, once I upload a new document, two new collections, fs.files and fs.chunks are created in my mlab distribution.

I feel like the answer has to do with this, but I don't know how or what to do. What I'm currently doing is using `<a href="{{link}}?download=true" download="{{name}}" target="_parent" type="{{type}}">` in my html as outlined here: https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-download-button

The page itself, again, displays the file as well as pulls the correct metadata. And if I've just uploaded the file without pushing a new deploy, then it downloads fine. _However_ once I push another deploy, when I try to download a file that was uploaded before the most recent deploy, it downloads an un-openable PDF file of very small, and incorrect, size.

**Comment by dr-dimitru** [comment]
Hello @zacharyabolton ,

Please update your OP following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  1. Version of `Meteor-Files` you're experiencing this issue
  2. Version of `Meteor` you're experiencing this issue
  3. Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  4. Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
 5. Post contents of `.meteor/packages` file
 6. What routing library are you using?
 7. Are you using `*picker*` package(s)?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
