### ISSUE TITLE
Http CORS problem

### ISSUE THREAD

**Issue by AjandM** [VeliovGroup/Meteor-Files#607]
Hi, Im using this package and its awesome. There is no problem with DDP transport unless the speed so I decide to switch to HTTP. It works perfectly is development mode but when it goes to production ( actually staging ) when I try to upload sth this error shows: 

> Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

> I think it's obviously a problem with CORS and not this package and this problem should be in stackoverflow and not github issues but I couldn't find any other use cases with meteor and CORS because of no direct http communication in Meteor apps. After all with a perfect wiki I think this problem should be in wiki.

I tried to fix this problem with Meteor WebApp package:
`WebApp.connectHandlers.use(function(req, res, next) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Header", "*");
  return next();
});`

But it doesn't work. Any Idea how to solve this problem?

**Comment by dr-dimitru** [comment]
Hello @AjandM 

Could you please update OP following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  1. Version of `Meteor-Files` you're experiencing this issue
  2. Version of `Meteor` you're experiencing this issue
  3. Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  4. Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  5. Screenshot of the "Network" Tab with open "Headers" tab for failed request
  6. Are you uploading from one domain name to another? Why CORS related question raised here?
  7. Is the `Access-Control-Allow-Headers` header exists in the first page response?
  8. Do you set `ROOT_URL` env.var?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
