### ISSUE TITLE
Is it possible to name "rename" files on download?

### ISSUE THREAD

**Issue by raedle** [VeliovGroup/Meteor-Files#609]
### I have a suggestion:
When files are downloaded with the `fileRef.link()` they will be named after the file on the server. However, I would like to "rename" the file when downloaded. I tried the `a[download]` attribute, but that doesn't seem to work even though the files are downloaded from the same origin.

I'm using React and I would like to do something like:
```
<Button size="small" color="primary" href={this.props.video.link() + '?download=true'} download="custom-name.mp4">Download</Button>
```

The filename in the systems save dialog should then default to custom-name.mp4.

Any ideas how to achieve that?

**Comment by raedle** [comment]
Unfortunately, the filename required when downloading a file is unknown at the time of the upload/insert.

So, the insert wouldn't work anyway

**Comment by raedle** [comment]
Great! Thank you for your improvements.

Also, how do you feel about an additional parameter on the link to make it `easier` to customize the download filename?

For example:
`<a href={fileRef.link() + '?download=my-new-filename.mp4'}>Download</a>`

or

`<a href={fileRef.link() + '?download=true&downloadFileName=my-new-filename.mp4'}>Download</a>`

**Comment by dr-dimitru** [comment]
We see no need to change current API.
at the same time you can easily add support for it in your current implementation, via reading value of `http.params.query.download`.

**Comment by dr-dimitru** [comment]
@raedle looks nice.

Just to stay on the safe side, pass `filename` query string through `decodeURIComponent`, otherwise it may be encoded twice.

**Comment by dr-dimitru** [comment]
Feel free to close it in case if the issue is solved on your end.

**Comment by raedle** [comment]
Yes, the problem is solved. Thank you, Dimitru for your quick response. That's very rare and thus very much appreciated!

**Comment by dr-dimitru** [comment]
@raedle my pleasure :) Thank you for choosing our lib.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
