### ISSUE TITLE
can find uploaded images in folder

### ISSUE THREAD

**Issue by msio777** [VeliovGroup/Meteor-Files#61]
Hi,
I'm using version 1.2.1 on osx 10.11(el capitan) and I cant find my uploaded images on FS. debug says
`Meteor.Files Debugger: The file tennis-icon.png (binary) was saved to assets/app/uploads/uploadedFiles/knRbZlNgtDVFEuFrp.png` but this kind of path doest even exist
Please help me :) thanks
Best Regards

**Comment by dr-dimitru** [comment]
Hi @msio777 
This path is relative to Meteor's root, to find out full path take a look on [meteor-root](https://atmospherejs.com/ostrio/meteor-root) package

**Comment by msio777** [comment]
It doesnt work I cant find uploaded image in whole FS but If I dont set storagePath I get this
`{ [Error: Unfinished upload (probably caused by server reboot or aborted operation) [500]]
W20160322-19:03:20.933(1)? (STDERR)   error: 500,
W20160322-19:03:20.933(1)? (STDERR)   reason: 'Unfinished upload (probably caused by server reboot or aborted operation)',
W20160322-19:03:20.933(1)? (STDERR)   details: { [Error: EACCES, permission denied '/assets'] errno: 3, code: 'EACCES', path: '/assets', syscall: 'mkdir' },
W20160322-19:03:20.933(1)? (STDERR)   message: 'Unfinished upload (probably caused by server reboot or aborted operation) [500]',
W20160322-19:03:20.933(1)? (STDERR)   errorType: 'Meteor.Error' }
`

**Comment by dr-dimitru** [comment]
This message:
```
Error: EACCES, permission denied '/assets'
```
Explains everything, check permissions on that folder, again to find full path use [meteor-root](https://atmospherejs.com/ostrio/meteor-root) package

**Comment by msio777** [comment]
I know but this assets folder doest exist and I already tried Meteor.rootPath and Meteor.absolutePath but nothing. Should I store this images explicitly with some property ?

**Comment by dr-dimitru** [comment]
It will be created once you call `new Meteor.Files()` somewhere deep in `.meteor` directory of your project. Note: *All files will be wiped out on meteor restart/rebuild*, unless you store files relative to your OS's root

**Comment by msio777** [comment]
I found there is folder .meteor...programs/server/assets but there is nothing and I got still  

> Error: EACCES, permission denied '/assets' 

and I set chmod 777 on /assets folder

**Comment by msio777** [comment]
I figured it out. it is necessary set `storagePath` property. If I set `storagePath= 'images'`I find the folder in `projectRoot/.meteor/local/build/programs/server` but If I want to set  images folder from home `~/images` it doesnt work and `~/images` will be created in `projectRoot/.meteor/local/build/programs/server`

**Comment by dr-dimitru** [comment]
@msio777 are you on Win, Mac or Linux?

**Comment by msio777** [comment]
I mentioned osx 10.11(el capitan) . I think el capitan can cause the issue. it has this feature 
System Integrity Protection [https://en.wikipedia.org/wiki/System_Integrity_Protection](url)

**Comment by dr-dimitru** [comment]
I'm glad you have solved this.
If you found this package useful, please do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=File upload and delivery in Meteorjs - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

**Comment by msio777** [comment]
unfortunately I did not solve this because I want to have my images in home folder :(

**Comment by msio777** [comment]
I got the feeling that meteor files set just projectPath a there is no way to go up in FS outside of projectPath . What do you think ?

**Comment by dr-dimitru** [comment]
Use absolute path (for MacOS X): `/Users/YourAccountName/storagePath/`
Answering on your last question: *Meteor is same as nodejs, so you can use FS according to permissions under user you're running nodejs (meteor)*

**Comment by dr-dimitru** [comment]
@msio777 please, let me know if this issue is solved

**Comment by msio777** [comment]
:grimacing:  My bad. I called  `Meteor.absolutePath` returns on client undefined and no storagePath was defeined. but how Can I set storagePath just on server but I want to have still reference to Meteor.Files object in template 
thanks

**Comment by dr-dimitru** [comment]
Hi @msio777 ,
Sorry, but I didn't get you. Could you please tell me:
1. What are you exactly trying to accomplish?
2. What have you already done (code)?
3. Where is an issue?

**Comment by msio777** [comment]
Sorry, I mean I wanted to store my images in projectRoot. I figured out that `Meteor.absolutePath`returns undefined on client (makes sense) a `storagePath` attribute in Meteor.Files object was not set. it means I had to set `storagePath`  manually to `'/Users/xxx/myMeteorProject/images'` and all images are uploaded to folder images in projectRoot. anyway if I dont set storagePath, I get error because of permission on access folder .. check the message above.

**Comment by dr-dimitru** [comment]
Two solutions:
1. Run as `sudo` (__bad idea__)
2. Set correct permissions, *so user under which you're running* `meteor` *command will have access to* `/Users/xxx/myMeteorProject/images`
3. __Make sure you have set correct, and existing path__, try to `cd /Users/xxx/myMeteorProject/images` from console

**Comment by msio777** [comment]
I've already done this. it resolved :+1:

**Comment by dr-dimitru** [comment]
Great! If you found this package useful, please do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=File upload and delivery in Meteorjs - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

Cheers!
