### ISSUE TITLE
Uploaded event fired before progress=100 event

### ISSUE THREAD

**Issue by raedle** [VeliovGroup/Meteor-Files#611]
First, thank you very much for providing this cool package for uploading files with Meteor!

Is there a reason why the "uploaded" event is fired before the "progress" event (with 100% progress) is fired?

The following code:
```
uploadInstance.on("start", () => {
    console.log('starting upload');
});

uploadInstance.on("progress", (progress, fileObj) => {
    console.log("progress", progress);
});

uploadInstance.on("uploaded", (error, fileObj) => {
    console.log("uploaded");
});
```

results in the console log below:

```
starting upload
progress 5
progress 37
progress 63
uploaded
progress 100
```

**Comment by raedle** [comment]
The same counts for "end" event.

```
starting upload
progress 5
progress 47
progress 89
uploaded
end
progress 100
```

**Comment by dr-dimitru** [comment]
@raedle have you managed to solve it?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by raedle** [comment]
I was out-of-office. Yep, the issue still exists

**Comment by dr-dimitru** [comment]
@raedle thank you for update on this one.
Feel free to close it in case if the issue is solved on your end.

**Comment by raedle** [comment]
@dr-dimitru Your fix works. Thank you. I'm closing the issue
