### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Gr05** [VeliovGroup/Meteor-Files#612]
### I'm having an issue:
  - Give an expressive description of what is went wrong
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  
### I had an issue and I've solved it on my own:
  - Provide a description of steps that you've followed to solve the problem
  - Provide links to websites and/or pages with the information that helped you (*if there are any*)

### I have a suggestion:
  - Describe your feature / request
  - How you going to use it? Give a usage example(s)

### Documentation is missing something or incorrect (have typos, etc.):
  - Give an expressive description what you have changed/added and why
  - Make sure you're using correct markdown markup
  - Make sure all code blocks starts with tripple ``` (*backtick*) and have a syntax tag, for more read [this docs](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting)
  - Post your addition/changes in issue, we will manage it

**Comment by dr-dimitru** [comment]
🤔😕
