### ISSUE TITLE
How to update uploaded file ? (using AWS s3 Integration)

### ISSUE THREAD

**Issue by csKangGdcomm** [VeliovGroup/Meteor-Files#614]
First of all, Thanks for maintaining great library 

### I have a question:
  - Describe your feature / request
How to update image when using AWS s3 Integration.  

I used the code [wiki](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration) provided. it works well!
I can create documents of userFiles collection and the file was uploaded on my s3 buket,
The next step after successing uploading is updating current file which was already uploaded.
I checked example at [github](https://github.com/VeliovGroup/Meteor-Files-Demos ), however, I failed to find how to update the file. ( How to update the document  or what kind of API should I use...)
Can you give me some advise?

**Comment by dr-dimitru** [comment]
Hello @csKangGdcomm ,

What do you mean by "How to update the document"?

 1. Update record's meta-data?
 2. Update file itself?

**Comment by csKangGdcomm** [comment]
`{
  _id: 'RsxiWy6v5RQsc5QxN',
  size: 84115,
  type: 'image/jpeg',
  name: '1.jpeg',
  meta: {
    userId: '4BRjnRDKSPJ9vdmFQ',
    location: 'fake',
  },
  ext: 'jpeg',
  extension: 'jpeg',
  extensionWithDot: '.jpeg',
  mime: 'image/jpeg',
  'mime-type': 'image/jpeg',
  userId: '4BRjnRDKSPJ9vdmFQ',
  path: 'assets/app/uploads/uploadedFiles/RsxiWy6v5RQsc5QxN.jpeg',
  versions: {
    original: {
      path: 'assets/app/uploads/uploadedFiles/RsxiWy6v5RQsc5QxN.jpeg',
      size: 84115,
      type: 'image/jpeg',
      extension: 'jpeg',
      meta: {
        pipePath: 'v1/DQdGybu4SNkgXmSpY-original.jpeg',
      },
    },
  },
  _downloadRoute: '/cdn/storage',
  _collectionName: 'ImageFiles',
  isVideo: false,
  isAudio: false,
  isImage: true,
  isText: false,
  isJSON: false,
  isPDF: false,
  _storagePath: 'assets/app/uploads/uploadedFiles',
  public: false,
};`

above is the document of FilesCollection collection.

I think Update file means the document should be updated with the information (size, type, name,  especially versions.original.meta.pipePath(location of AWS S3) and etc... ) without _id.

After updating the file, User can see the new uploaded file.

I think insert api just create new document with new information, I can replace the new _id of document, but It seems that it is not exactly update the information....

Simple use case is that user upload image. after that, the user want to change the image. So, the system should change new image and should delete the old image already uploaded.

Thank you!

**Comment by dr-dimitru** [comment]
@csKangGdcomm

> Simple use case is that user upload image. after that, the user want to change the image. So, the system should change new image and should delete the old image already uploaded.

Just remove old file and record in DB, and upload a new one, no need to update it. Plus it's correct way to avoid running into the cached results as file will have new _id and URL.

> I need the versions.original.meta.pipePath because after updating file, the system have to delete the file which is already uploaded on AWS s3.

If you've followed our tutorial you don't need to do it manually, we've covered this case [here](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration):
```js
  // Intercept FilesCollection's remove method to remove file from AWS:S3
  const _origRemove = UserFiles.remove;
  UserFiles.remove = function (search) {
    const cursor = this.collection.find(search);
    cursor.forEach((fileRef) => {
      _.each(fileRef.versions, (vRef) => {
        if (vRef && vRef.meta && vRef.meta.pipePath) {
          // Remove the object from AWS:S3 first, then we will call the original FilesCollection remove
          s3.deleteObject({
            Bucket: s3Conf.bucket,
            Key: vRef.meta.pipePath,
          }, (error) => {
            bound(() => {
              if (error) {
                console.error(error);
              }
            });
          });
        }
      });
    });

    //remove original file from database
    _origRemove.call(this, search);
```

**Comment by csKangGdcomm** [comment]
Thank you so much!
I understand what you mean. I should follow your way.
Anyway, I already stared this repo 👍

**Comment by dr-dimitru** [comment]
@csKangGdcomm thank you, hope my answer helped you :)
