### ISSUE TITLE
Adding Meteor Files to an existing collection

### ISSUE THREAD

**Issue by sbdm05** [VeliovGroup/Meteor-Files#615]
I set up the upload field following the instructions. (using React)
Now, it saves in a new collection UserFiles. 
I would like the image to be attached to a different collection. I have tried doing so using simpl-schema. 
In the doc, I found the default Files collection schema. 
https://github.com/VeliovGroup/Meteor-Files/wiki/Schema

Can you give me any hint on how to do that ? 
Best

**Comment by dr-dimitru** [comment]
Hello @sbdm05 ,

Not sure what you're exactly mean by:

 > I would like the image to be attached to a different collection.

But in MongoDB there is two ways to reference data between collections:
 1. Referense by `_id` as in any other relational database
 2. [recommended] Get shallow copy of the record from `UserFiles` and attach it to the collection of your choice, it can be done in `onAfterUpload` hook or `afterUpload` event

**Comment by dr-dimitru** [comment]
Hello @sbdm05 ,
Any news on your end? Have you solved it?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
