### ISSUE TITLE
Looking for better documentation for how to convert from CollectionFS

### ISSUE THREAD

**Issue by schlaegerz** [VeliovGroup/Meteor-Files#618]
I currently have a production app that is running CollectionFS, but it is now causing more and more headache and I am looking to switch as soon as possible. 

I already have all my files in S3 so I shouldn't need to transfer any files over, but I am trying to find if there is any good way to just migrate all the Mongo Collection records over to this package to make sure it continues to work. 

Is there any good guide in how to just add existing S3 files to a Meteor-Files collection, without downloading and re-uploading them, I'm trying to make sure we do this with as little risk as possible, as I do have a few thousand files that will need to be migrated.

Also, I can't quite find anything about this in the documentation,  but is there support for multiple copies/stores of one file? In my current app we store multiple copies of each image so that we can quickly load a thumbnail instead of loading the entire image.

**Comment by dr-dimitru** [comment]
@schlaegerz what you've described is requires a lot of work to fit your specific case. But we have some links to help you to start with:

 - [CFS to MeteorFiles migration guide](https://github.com/VeliovGroup/Meteor-Files/wiki/Converting-from-CollectionFS)
 - [How to use file's subversions](https://github.com/VeliovGroup/Meteor-Files/wiki/Create-and-Manage-Subversions)

If you want to hire someone to help you with this case, we have team members who are available on an hourly basis and ready to help you.

**Comment by dr-dimitru** [comment]
Redirect will work for sure. You can build any url you like, even skipping `collectionName` part, just do not forget to put it into request to *FilesCollection*.

And `/cfs/files` part of URL can be tuned via [`downloadRoute`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor).

wdyt?

**Comment by schlaegerz** [comment]
For anyone else looking into this I was able to figure out all the issues I was having. I was able to get the majority of it by looking at [the demo](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/server/files.collection.js)

And then the other key is to just use the old cfs collections
```

Images = new FilesCollection({
   collection: new Mongo.Collection('cfs.Images.filerecord',
    downloadRoute: '/cfs/files',
   ....
```
And then you can convert all the entries like this:
```
tranformItem = function(collection, item, isImage, copyToFolder, defaultType)
{
  try{
    if(!item)
    {
      console.warn("Item not passed in")
      return;
    }
    
    if(!item.original)
    {
      console.warn("Updating already updated item")
      return //Already updated
    }
  
    let extension = item.original && item.original.name && item.original.name.replace(/^.*\./, '') // ".stl";
  
    item.extension = extension
    let versions = {}

    let fileKey = item.original && item.original.key
    if(!fileKey)
    {
      if(item.copies)
      {
        let copyKeyList = Object.keys(item.copies)
        if(copyKeyList)
        {
          let copyKey = copyKeyList[0]
          let copy = copyKey && item.copies[copyKey]
          fileKey = copy && copy.key
          if(!fileKey)
          {
            return
          }
        }
      }
    }
  
    let set =  {
      isImage: isImage,
      
      isAudio:false,
      isJSON:false,
      isPDF:false,
      isText:false,
      isVideo:false,
      ext: extension,
      extension: extension,
      extensionWithDot: "." + extension,
      'mime-type': item.original.type || defaultType,
      _storagePath: filesLocation,
      _downloadRoute: collection.downloadRoute,
      _collectionName: collection.collectionName,
      meta: item.meta || item.metadata,
      userId: item.userId || item.metadata && item.metadata.owner,
    }
  
    set["size"] = item.original.size,
    set["name"] = item.original.name,
    set["mime"] = item.original.type  || defaultType,
    set["type"] = item.original.type  || defaultType,
    set["path"] = filesLocation + "/" + fileKey
  
    const setPipe =  USES3
    if(item.copies)
    {
      Object.keys(item.copies).forEach((key)=>{
        let copy = item.copies[key]
        let itemKey = copy.key || fileKey
        versions[key] = {
          path: filesLocation + "/" + itemKey,
          size: copy.size,
          name: copy.name,
          extension: extension,
          mime: copy.type,
          type: copy.type,
        }
    
        if(setPipe)
        {
          versions[key]['meta'] = {
            pipePath:  copyToFolder[key] +"/" + item.copies[key].key
          }
        }
      })
      set.versions = versions
    }
    collection.update({_id:item._id}, {$set:set})
  }
  catch(error)
  {
    console.error("Failed to update item", error, item)
  }
}
```
And then for redirecting if you have cases like me we you have old clients that cannot be updated easily. This probably doesn't get all the same features as the other files, but it works for me.
```

WebApp.connectHandlers.use('/cfs/files/images/', function(request, response, next) {
    let id = request.url.split('/')[1]
    if(id)
    {
      const params = {
        query: {},
        file: id + '.png', // You will have to get the right extension, my case is always the same
        _id: id,
        version: "thumbnails", // You will have to get the right version, my case is always the same
        name: id + '.png',
      };
      const http = {request: request, response: response, params}
      if(Images._checkAccess(http))
      {
        Images.download(http, "thumbnails", Imagess.findOne({_id:id}))
      }
      else
      {
        next()
      }
    }
    else
    {
      next()
    }
  })

```
