### ISSUE TITLE
Looking for a way/method to apply rate limit to uploading

### ISSUE THREAD

**Issue by minhna** [VeliovGroup/Meteor-Files#619]
Hi, Meteor-Files is awesome. I'm looking for a method to set rate limit to user likes the `DDPRateLimit` does.
For example we allow 1 client to upload only 10 photos in 30 seconds.
Thank you.

**Comment by dr-dimitru** [comment]
Hello @minhna ,

Yes, it can be easily done inside `interceptDownload` or `downloadCallback` hooks on a *Server*.
`downloadCallback` hook is much easier  to use as simply requires to return `true` if download allowed and `false` if download should be restricted.

Inside of `downloadCallback` you can set and later check user's latest download time and incremental counter for downloads within 30 seconds range.

wdyt?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
