### ISSUE TITLE
Confusing typo in wiki

### ISSUE THREAD

**Issue by janjackson** [VeliovGroup/Meteor-Files#620]
https://github.com/VeliovGroup/Meteor-Files/wiki/remove

is about how to remove Images.

Images.link() needs to be replaced with Images.remove()

I could not find the file in the repo, so sry that it's an issue and not a PR

Thanks a lot for the great work! :)

**Comment by dr-dimitru** [comment]
@janjackson good catch ；）
Fixed. 
FYI: Up-to-date docs always can be found at [`docs` directory](https://github.com/VeliovGroup/Meteor-Files/tree/master/docs)

Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
