### ISSUE TITLE
Question: How to migrate local files to S3

### ISSUE THREAD

**Issue by kations** [VeliovGroup/Meteor-Files#621]
Hi and thanks for the great package,

i haven't found something in the docs, how easy it is to migrate from local files on the server to aws S3? 

My Collection looks like this:
```js
ImageFiles = new FilesCollection({
  collectionName: 'imageFiles',
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg|pdf/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});
```
Did I just have to copy the folders to S3? And change my Code like in the docs for S3?

Would be great if someone could guide me in the right direction.

Thanks

**Comment by dr-dimitru** [comment]
Hey @kations ,

I'm glad you've found our lib to be useful :)

You need to code to move files from local storage to AWS:S3.
As I understood you're already using *FilesCollection* to store files and has some files at the storage, right? If so, simplest way will be to create a new collection with different name following our [AWS:S3 integration tutorial](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration). Then:

 1. Loop through all files at the __old__ collection, like `ImageFiles .find({}).forEach()`;
 2. Inside `forEach` read each file into a *Buffer* using `const buf = fs.readFileSync(file._storagePath)`;
 3. And pass the *Buffer* with a file, and `meta` into [`.write()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) of the __new__ collection, like: `NewImagesFiles.write(buf, filesMeta, function (err, fileRef) {/*...*/}, true);`, __note: fourth argument must be true__ to make all this thing working
 4. Run the script and after migration you can rename __variable__ of the new collection to the old one, and use it as before

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
