### ISSUE TITLE
Rarely occurring error "duplicate key error collection" while uploading a file

### ISSUE THREAD

**Issue by SimonSimCity** [VeliovGroup/Meteor-Files#624]
## Give an expressive description of what is went wrong

I got told by a test-user that he wasn't able to upload files and started investigating on it. This was while he was testing an application which was running in developer-mode. It looked that the server was quite busy at the time he tried it, but what wondered me the most was this stack-trace I found in the server-log:

```
Exception while invoking method '_FilesCollectionStart_imports' WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: meteor.__pre_imports index: _id_ dup key: { : \"echv4XieGSspQcKMx\" }","op":{"file":{"size":38750000,"type":"text/plain","name":"artikelstamm1020_7.txt","meta":{"projectId":"9vxGNLmcaMwkMr5dd","importId":"63129d9f-a76d-46cd-abd1-acf6e17ecdb0","uploaded_at":"2018-06-20T16:30:16.365Z","autoCreateJob":true},"ext":"txt","extension":"txt","extensionWithDot":".txt","mime":"text/plain","mime-type":"text/plain","_id":"echv4XieGSspQcKMx","userId":"yMv6ubhv8WkzkHeEN","path":"/tmp/imports/echv4XieGSspQcKMx.txt","versions":{"original":{"path":"/tmp/imports/echv4XieGSspQcKMx.txt","size":38750000,"type":"text/plain","extension":"txt"}},"_downloadRoute":"/cdn/storage","_collectionName":"imports","isVideo":false,"isAudio":false,"isImage":false,"isText":true,"isJSON":false,"isPDF":false,"_storagePath":"/tmp/imports"},"fileId":"echv4XieGSspQcKMx","chunkSize":327680,"fileLength":119,"_id":"echv4XieGSspQcKMx","createdAt":"2018-06-20T16:35:21.482Z","maxLength":119}})
    at Function.MongoError.create (/Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:139:22)
    at /Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:668:23
    at handleCallback (/Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /Users/simon/.meteor/packages/npm-mongo/.2.2.33.1x467hb.o59m++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Exception in callback of async function: Error: [FilesCollection] [writeStream] [ensureFile] [open] [Error:] [500]
    at bound (packages/ostrio:files/write-stream.js:49:25)
    at Meteor.bindEnvironment.callback (packages/ostrio:files/write-stream.js:10:52)
    at runWithEnvironment (packages/meteor.js:1240:24)
```

I have to further investigate it and first wanted to ask if you guys have a clue how this could occur ...

If you ask me, this very much sounds like the method used here isn't idempotent: https://guide.meteor.com/methods.html#retries

## Version of `Meteor-Files` you're experiencing this issue

I'm using `1.9.11`

## Version of `Meteor` you're experiencing this issue

I'm using `1.6.0.1`

## Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?

The server was running on a Mac OS X 10.13.5 and the browser was Google Chrome version 67.0.3396.87

## Is it *Client* or *Server* issue?

I guess a server issue, since I found the exception-stack in the server logs and the client just showed that the upload was unsuccessful.

## Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

This is something I have give you when the error get's reproducible - or at least happens once more. I just got the report by a user after it already was not reproducible and found the posted excerpt which occurred at the time he faced the problem.

**Comment by dr-dimitru** [comment]
Hello @SimonSimCity ,

I'm very sorry for being silent for a month.
Fix released in [`v1.10.0`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.10.0).
Let me know if it solves the issue.
Feel free to reopen it in case if the issue is still persists on your end.
