### ISSUE TITLE
onBeforeUpload Not Treating True Correctly?

### ISSUE THREAD

**Issue by SeraVault** [VeliovGroup/Meteor-Files#627]
I have this in my onBeforeUpload function:

    var planDisk = {value returned from function1};  
    var diskUsage = {value returned from function2};
    var diskUsagePlusFile = diskUsage + file.size;
    var enoughSpace = (planDisk >= diskUsagePlusFile);
    if (enoughSpace) {
        return true;
    } else {
        toastr.error(TAPi18n.__('outOfDiskSpace'));
        return false;
    }        

Even though it's returning "true", the upload is not sticking and it's like it returned false (but didn't).  

If I put a "return true;" as the 1st statement, the uploads work.  

Any ideas?

**Comment by dr-dimitru** [comment]
Hello @SeraVault ,

Sorry for the late reply. Have you solved it on your own?
If so, what was the issue?

**Comment by SeraVault** [comment]
Hi,

I wasn't able to solve the problem.  I implemented code outside of the
onBeforeUpdate event to handle the situation.


Thanks!

**Comment by dr-dimitru** [comment]
Do you wish to reopen this ticket and post full definition of your collection, so we can proceed further with fix?
