### ISSUE TITLE
Updating the filename

### ISSUE THREAD

**Issue by aureooms** [VeliovGroup/Meteor-Files#628]
### Documentation is missing something or incorrect (have typos, etc.):

What is the proper way of updating the filename of an existing record? This seems to be missing from the documentation.

**Comment by dr-dimitru** [comment]
Hello @aureooms ,

File's data stored in MongoDB, and it can be easily updated with simple `.update` query. To find out available fields see [schema](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema), to access underlying *Collection* see - [collection](https://github.com/VeliovGroup/Meteor-Files/wiki/collection). For example:

```js
const Images = new FilesCollection({collectionName: 'Images'});
Images.collection.update(_id, {
  $set: {
    name: 'newName'
  }
});
```

Let me know if this info is helpful.

**Comment by aureooms** [comment]
Do we also have to manually update extension fields, etc?

**Comment by dr-dimitru** [comment]
@aureooms if extension is changed - yes.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
