### ISSUE TITLE
Unable to download files using Cordova

### ISSUE THREAD

**Issue by SeraVault** [VeliovGroup/Meteor-Files#629]
When trying to download files under a compiled Meteor Cordova app, I'm using a "fetch" for further processing.  I'm getting a "TypeError: Failed to fetch".  Any ideas?

**Comment by dr-dimitru** [comment]
Hello @SeraVault ,

Post the code you're using.
And update thread following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE).

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
