### ISSUE TITLE
Service Unavailable when using ?play=true in the demo

### ISSUE THREAD

**Issue by Aur0r** [VeliovGroup/Meteor-Files#63]
Hi,
thank you for this great plugin!

The only thing that doesn't work for me is the ?play=true streaming (with an mp3 file). The download option works but the play option returns "Service Unavailable" (Screenshot of the demo can be found attached).

Could you please give me a hint why this is happening? Thanks!
![serviceunavailable_503](https://cloud.githubusercontent.com/assets/444048/14333885/27622b2a-fc51-11e5-9731-631d536788ba.PNG)

**Comment by dr-dimitru** [comment]
Hi, I'm glad you've found this package useful for your needs.

To investigate this issue I need:
 0. Can you locate uploaded file on your local/dev machine?
 1. Any server's errors or logs?
 2. How about turn on [`debug`](https://github.com/VeliovGroup/Meteor-Files#new-meteorfilesconfig-isomorphic) `new Meteor.Files({debug: true})`, and post all output here?
 3. Which Meteor version?
 4. Which platform you're on Mac, Min, Linux?
 5. This is happens only with `?play=true` query? How about to try without any query?
 6. This is happens inly with `mp3` files? Have you tried other formats?
 7.  Please note this package wasn't tested yet (*by me*) with Meteor 1.3.1 (*but it should definitely work, as changes wasn't about modules used in this package*)

**Comment by Aur0r** [comment]
1. The file is available on my system and I can download it via the ?download=true option.
![meteorfilesuploaded](https://cloud.githubusercontent.com/assets/444048/14334371/4bff9fd2-fc54-11e5-9c31-890ae70e29f4.PNG)
2. No server error logs.
3. Now it is turned on:
Server:
![meteorfilesserverdebug](https://cloud.githubusercontent.com/assets/444048/14334391/6f4701a6-fc54-11e5-945b-d4672c3a8c33.PNG)

Client:
![meteorfilesclientdebug](https://cloud.githubusercontent.com/assets/444048/14334398/7e7d094a-fc54-11e5-9419-fdb96305694a.PNG)

4. Meteor 1.3.1 (as I wrote no error updating the packages worked fine)
5. Windows 10 (Chrome Version 49.0.2623.110 m)
6. The ?play=true and without query options show the same result
![meteorfilesclientwithoutquery](https://cloud.githubusercontent.com/assets/444048/14334470/ecef5554-fc54-11e5-9865-6d3c9e39abe4.PNG)
7. I have also tried zip files without the ?download=true option they work. But for example for mp4 it doesn't work without query parameter and also with the ?play=true option it doesn't work for mp4. Only the download option works.
![meteorfilesclientmp4](https://cloud.githubusercontent.com/assets/444048/14334548/67cdc36e-fc55-11e5-85f7-668863311c07.PNG)
![meteorfilesservermp4](https://cloud.githubusercontent.com/assets/444048/14334563/8c7c932a-fc55-11e5-937d-bb5c134af788.PNG)
8. Yes I image that you haven't had the chance to test it yet :)

Thank you for the fast response! :)

**Comment by Aur0r** [comment]
If you need to know which package versions I used you can have a look at the zip file of the demo I used.
[demo.zip](https://github.com/VeliovGroup/Meteor-Files/files/207453/demo.zip)

**Comment by dr-dimitru** [comment]
Solved in [1.3.17](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.3.17), thank you for bug report.

If you found this package useful, please do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=File upload and delivery in Meteorjs - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

**Comment by Aur0r** [comment]
Thank you very much, great work! Had already starred the project on github now I did it on Atmosphere as well :)

I also had a look at https://veliovgroup.com/. Seems interesting, keep up the good work!
