### ISSUE TITLE
meteor 1.7 Issue

### ISSUE THREAD

**Issue by freeseamew** [VeliovGroup/Meteor-Files#630]
I can not upload meteor 1.7 with the following error. I would appreciate your comments on this part.

Error during upload: Method '_FilesCollectionStart_Images' not found

**Comment by dr-dimitru** [comment]
Hello @freeseamew ,
Please update your question following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  - __Definition of *FilesCollection*__ (e.g.: `new FilesCollection({/*...*/})`)
  - __Post contents of `.meteor/packages` file__
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by freeseamew** [comment]
I had used 'ostrio: files@1.9.11'.

The source used in the test was the demo of the link below.
https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-upload

Testing was done in two versions of metor.

In meteor version 1.6.1 we found that it worked fine.

However, in meteor 1.7.0.3, a popup error "Error during upload: Method '_FilesCollectionStart_Images' not found' occurred and uploading did not work normally.

My os is mac os.

**Comment by dr-dimitru** [comment]
@freeseamew although you haven't provided enough information about your issue, here is some of my thoughts:

 1. Make sure *FilesCollection* is defined on both *Server* and *Client* (this particular issue looks like collection defined only on *Client*)
 2. Try to switch to `http` transport

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by anjunatic** [comment]
+1 with the same problem! 
Meteor 1.7.0.5
> Error: [meteor-autoform-files] No such collection "ProductImages" [404]
downgrade to 1.6.1.4 solves the problem

**Comment by dr-dimitru** [comment]
@anjunatic thank you for your report.
`ostrio:files` and `ostrio:autoform-files` two different packages, please follow thread [here](https://github.com/VeliovGroup/meteor-autoform-file/issues/45)
