### ISSUE TITLE
Meteor when rebooting deletes the folder where the images are saved

### ISSUE THREAD

**Issue by HC-Isma** [VeliovGroup/Meteor-Files#631]
I'm having an issue:

Meteor to start or restart removes and recreates the folder where the images are uploaded ('assets\app\uploads\Images'), and all previously loaded images are lost.
Therefore when starting again Meteor can not find the images.
Any suggestions ..?
I tried the **demo-simplest-upload** and it has the same problem.

  - Version of `Meteor-Files`: ostrio:files@1.9.11
  - Version of `Meteor`: Meteor 1.7.0.3
  -  OS (Win 10)? 

Thank you..!!!

**Comment by dr-dimitru** [comment]
Hello @HC-Isma ,

This behavior is expected, as Meteor wipes down all internal folders on rebuild (*rebuilds all folders*). This is [described in our FAQ](https://github.com/VeliovGroup/Meteor-Files#faq):

> - Where are files stored by default?: by default if `config.storagePath` isn't passed into Constructor it's equals to `assets/app/upload`s and relative to running script:
>    * On development stage: `yourDevAppDir/.meteor/local/build/programs/server`. Note: __All files will be removed as soon as your application rebuilds or you run meteor reset. To keep your storage persistent during development use an absolute path outside of your project folder__, e.g. `/data` directory.
>    * On production: `yourProdAppDir/programs/server`. Note: If using MeteorUp (MUP), Docker volumes must to be added to mup.json, see MUP usage

Let me know if it helped you

**Comment by HC-Isma** [comment]
it is understood
Thank you very much...!!!!

**Comment by dr-dimitru** [comment]
@HC-Isma I'm glad it's solved for you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
