### ISSUE TITLE
Template.subscriptionsReady returns true while file subscription is not yet ready.

### ISSUE THREAD

**Issue by mozfet** [VeliovGroup/Meteor-Files#635]
On the client, Template.subscriptionsReady returns true while file subscription are not yet ready. I'm using Meteor 1.6.1.3 with ostrio:files@1.9.11.

I'm using template level subscriptions in a Blaze Template to subscribe to a Meteor File Collection.
In my template HTML, I use a {{#if Template.subscriptionsReady}} block to ensure all collections are ready before I start querying them inside the block. I query the collection by using a helper to retrieve file documents from the File Collection.

The first time this helper is called (from inside the block), any query against File Collection returns undefined. A few moments later, the document I'm looking for is found. This shows to me that the subscription did not complete, while the helper could not be called before all subscriptions are ready.

In the code below, the first time the filename helper is called an "Exception in template helper: TypeError: Cannot read property 'fetch' of undefined" is thrown, a few moments later the filename is however found...

```javascript
Template.blog.onCreated(() => {
  Meteor.subscribe('blog.posts')
  Meteor.subscribe('files.blog.post')
})

Template.blog.helpers({
  posts() {
    return BlogPosts.find({})
  },
  filename(postId) {
    const fileCursor = BlogFiles.findOne(postId)
    const fileDoc = fileCursor.fetch()[0]  // this is also weird.. I do a findOne, but recieve a cursor
    return fileDoc.name
  }
})
```

```html
<Template name = "blog">
  {{#if Template.subscriptionsReady}}
      {{#each post in posts}}
        {{filename post._id}}
      {{/each}}
    {{/if}}
  {{/if}}
</Template>
```

My logs indicate only the following relevant entry, regardless of an error being thrown or not.
```
[FilesCollection] [findOne("24vn2rtYdW8rTPNsR", undefined)]
```

However, when I set a reactive var in javascript when the file subscription is ready and check the reactive var in html, it works without any exceptions...

```javascript
Template.blog.onCreated(() => {
  const instance = Template.instance()
  instance.state = {isReady: new ReactiveVar(false)}
  Meteor.subscribe('blog.posts')
  Meteor.subscribe('files.blog.post', true, (error) => {
    instance.state.isReady.set(true)
  })
})

Template.blog.helpers({
  posts() {
    return BlogPosts.find({})
  },
  filename(postId) {
    const fileCursor = BlogFiles.findOne(postId)
    const fileDoc = fileCursor.fetch()[0]  // this is also weird.. I do a findOne, but recieve cursor
    return fileDoc.name
  }
})
```

```html
<Template name = "blog">
  {{#if Template.subscriptionsReady}}
    {{#if instance.state.filesReady.get}}
      {{#each post in posts}}
        {{filename post._id}}
      {{/each}}
    {{/if}}
  {{/if}}
</Template>
```

Note that I use a global helper loaded on client startup that I use a to avoid unnecessary "getter" helpers
```javascript
Template.registerHelper('instance', function() {
  return Template.instance();
});
```

**Comment by dr-dimitru** [comment]
Hey @mozfet ,

`Template.subscriptionsReady` works __only__ if you do so-called "template-level subscriptions".
So you have to use `this.subscribe` instead of `Meteor.subscribe`, and mind `function`, not a "fat-arrow":
```js
Template.blog.onCreated(function () { // <-- function
  this.subscribe('blog.posts'); // <-- template-level subscription
  this.subscribe('files.blog.post'); // <-- template-level subscription
});
```

**Comment by mozfet** [comment]
@dr-dimitru (while I'm beating head against the wall for being an idiot) You are right, but in my case I should have used instance.subscribe. My instance was obtained using Template.instance(), some consider this a best practice which makes code portable between sections of template javascript, such as helpers and events and delegated functions).

**Comment by dr-dimitru** [comment]
@mozfet no worries, we all sometimes need second pair of eyes ;)
I'm glad we have figured it out together.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.me/drdimitru/25)
