### ISSUE TITLE
how to use `fileName` in Insert method?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-Files#637]
I tried to change set file name when upload
```
// don't work
Files.insert({
        file: file[0],
        fileName: 'import.xlsx',
        streams: 'dynamic',
        chunkSize: 'dynamic',
        onUploaded(err, fileObj) {
           ...
        }
------
// don't work
Files.insert({
        file: file[0],
        isBase64: true, // <— Mandatory
        fileName: 'import.xlsx', // <— Mandatory
        streams: 'dynamic',
        chunkSize: 'dynamic',
        onUploaded(err, fileObj) {
           ...
        }
```
Please help me

**Comment by thearabbit** [comment]
I tried
```
          var reader = new FileReader()
          reader.onload = readerEvt => {
               // readerEvt.target.result // use this for file update
          }
          reader.readAsBinaryString(this.file[0])
```
But still don't work

**Comment by dr-dimitru** [comment]
Hello @thearabbit ,

 1. Why do you think `fileName: 'import.xlsx'` doesn't work? How have you check it? What browser?
 2. I didn't get how second comment related to original post?
 3. Please update this thread following out [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE)

**Comment by thearabbit** [comment]
Sorry for late.
I use `Chrome`.
I have problem to pass the `file[0]` to server method
```js
// Client
Meteor.call('insetImg', file[0], .........)

// Server
Meteor.methods({
   insertImg(file){
    ....
  }
})
```

**Comment by dr-dimitru** [comment]
@thearabbit  you can not pass `file[0]` to server method. You should use `FilesCollection#insert` on the client.

**Comment by thearabbit** [comment]
Very thanks, It work fine.
