### ISSUE TITLE
Why is this.userId in protected() null in some cases while Meteor.server.session has a valid userId?

### ISSUE THREAD

**Issue by tehXor** [VeliovGroup/Meteor-Files#642]
I came across strange behaviour of `protected()` where `this.userId` and `this.user()` are `null`.

It only happens in dev environments though. I guess because the server runs separated from the client but in production behind the same public port. Only in the dev environments there is a different port for the DDP connection. Still even there the problem only happens in some scenarios seemingly where logged in users had no other interactions with the files collection so far and just try to download a file by URL.

This all is no big problem since in every case there is always a valid `userId` accessible from within `protected()` in the current `Meteor.server.sessions` object. So my only concern is, could I run in problems when I use this id from `Meteor.server.sessions` as fallback in production (I can't think of any)? Or has it good reasons that `this.userId` is sometimes `null` even there is a `Meteor.server.sessions`?

**Comment by dr-dimitru** [comment]
Hello @tehXor ,

Thank you for reporting about this. Could you please update this thread following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):
  - Give an expressive description of what is went wrong
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

__Additional Questions__:
  - How user attempt to download a file, directly by link (like inserting into browser)? Or via link but from meteor app UI?
  - When it fails, could you post (copy or screenshot) cookies stored at that moment on the client?

**Comment by tehXor** [comment]
Sorry for not filling in the full issue from - it thought this more as a question than an actual issue since it is no issue in most setups (even not in our production setup - it just bugs the devs in their environments and this is why we want to change it ;-)). Still here a short roundup:

For description see op /  ostrio:files 1.10.1 / meteor 1.7.0.4 / Linux and Windows, tested with Chrome but probably platform and browser independent / 'Access denied!' on the client caused by the server not having access to the userId in protected() / n/a but see below for further info

**Additional Info:**
* Download happens via link but there never is a 'meteor app UI' in our case since it is a independent (Ionic/Angular) client which just includes meteor without using its UI/templating at all
* This seems interesting: When it fails there is *no* cookie at all (only local storage with Meteor.loginToken, Meteor.userId, etc.). When you use the app a little (ie also go to views with file list) at some point a `x_mtok` cookie gets set and from this point on it obviously stops failing also on the other views.

But still my question: Even when it fails (no cookie) there is a valid `Meteor.server.sessions` accessible in protected() from which we can use the `userId` instead of `this.userId`. Is this a bad idea for some reasons I don't know yet?

**Comment by dr-dimitru** [comment]
> This seems interesting: When it fails there is no cookie at all... ...__When you use the app a little__...

Well, it means `x_mtok` cookie not set. User needs to follow a link (where cookie will be set/updated) to pass authorization on server.

> But still my question: Even when it fails (no cookie) there is a valid Meteor.server.sessions accessible in protected() from which we can use the userId instead of this.userId. Is this a bad idea for some reasons I don't know yet?

Login other users at the same time and you will see `Meteor.server.sessions` holds data for all logged-in users, how will you identify a user who is requesting a file without a cookie?

**Comment by tehXor** [comment]
> how will you identify a user who is requesting a file without a cookie?

We simply pass the user session in question as parameter of the file link (we also had a custom getLink() function anyways so this was no problem).
We have this for several weeks now in staging and it seems very robust.

Still I'm not sure why there is no `x_mtok` cookie when there is a valid user session server side and obviously also client side (since everything non file related - like subscriptions to other collections or `Meteor.call()`s work with the logged in user id).
But if you don't see a bigger problem of accessing the `userId` from `Meteor.server.sessions` we will keep our current solution and push it to production at some point. Also we didn't see a problem there it makes me somewhat uneasy to know it exists in dev environments and maybe still also could exist in some cases for production (: 
Anyways, if it also doesn't hint to some kind of maybe bug in Meteor-Files this issue can easily be closed.

**Comment by dr-dimitru** [comment]
@tehXor  the very same issue was raised in #500 , take a look. We have covered and discudden all pros and cons.
We came up with solution in [this PR](https://github.com/thomasspiesser/ostrio-files-bug/pull/1/files#diff-ce079999c484c3f4db9b0cf78320926eR9)

**Comment by tehXor** [comment]
#500 looks very related (also not totally). The PR however looks like quite exactly what we did as well. So I'm now even more confident in using it. Thanks for the input (and sorry i didn't find the related Issue and PR beforehand, idk how I missed it...).

**Comment by dr-dimitru** [comment]
@tehXor I'm glad you've found a way to solve it.
Authentication via getting query was widely discussed with many other users, even considered to implement in a core, but in this case we can not provide 100% security over it, as it would require us for extra documentation explaining why it's important to add extra security level if you're using MF package, and not every developer will ever read or follow it. As you see we stick to the "more acceptable" approach, leaving a room for you (*developer*) to extend and implement extra-features on demand.
