### ISSUE TITLE
Unlinking file with versions won't unlink main file

### ISSUE THREAD

**Issue by gischer** [VeliovGroup/Meteor-Files#643]
### I'm having an issue:
 When I delete a file for which I have generated a thumbnail, the thumnail file (in the file system) is deleted, but not the original file downloaded.

I'm using Meteor-Files 1.9.11* with Meteor 1.7 on Mac OS 10.12.6 with Version 68.0.3440.106 (Official Build) (64-bit).

This is a server issue.  A file which I think should be deleted/unlinked is not, and there's no good way I can see to do that.

When I look at server.js, `unlink` is defined at line 1471 and my read of this code suggests that the bug is here.  If there is a `versions` object, then all the versions are deleted, but the original is not.

Maybe there is an intended way to use this that I don't understand, but it seems to me that instead of an `else` clause that deletes the primary file, it should always delete the primary file, after checking to see if their are versions, and so on.

Here's a debug log, with one line added by my code (beginning with `[Thumbnail]`)
```
I20180904-14:39:45.386(-7)? [FilesCollection] [download(/cdn/storage/Images/HEq5wvcB35fmeaida/original/HEq5wvcB35fmeaida.jpg, original)]
I20180904-14:39:45.387(-7)? [FilesCollection] [serve(assets/app/uploads/Images/HEq5wvcB35fmeaida.jpg, original)] [200]
I20180904-14:39:45.392(-7)? [FilesCollection] [_preCollectionCursor.observe] [removed]: HEq5wvcB35fmeaida
I20180904-14:39:45.462(-7)? [FilesCollection] [findOne("HEq5wvcB35fmeaida", undefined)]
I20180904-14:39:45.467(-7)? [Thumbnail] generated and linked for  HEq5wvcB35fmeaida
I20180904-14:39:45.512(-7)? [FilesCollection] [download(/cdn/storage/Images/HEq5wvcB35fmeaida/thumbnail/HEq5wvcB35fmeaida.png, thumbnail)]
I20180904-14:39:45.513(-7)? [FilesCollection] [serve(assets/app/uploads/Images/thumbnail-HEq5wvcB35fmeaida.png, thumbnail)] [200]
I20180904-14:40:03.688(-7)? [FilesCollection] [remove({"_id":"HEq5wvcB35fmeaida"})]
I20180904-14:40:03.694(-7)? [FilesCollection] [unlink(HEq5wvcB35fmeaida, undefined)]
```
  
I plan to work around this for now by grabbing the path to the primary and using fs to delete it myself after calling remove(), unless you have a better suggestion.

I like this package a lot, it has simplified some tasks enormously.

**Comment by dr-dimitru** [comment]
Hello @gischer ,

Do you have any updates on this one? *Sorry for the late reply.*
If it's still relevant, could you post a code used to call `.remove()` method?

**Comment by micktaiwan** [comment]
Just a remark
`const fileRef = Images.find(imageId).fetch()[0];`
You could do
`const fileRef = Images.findOne(imageId).get();`

**Comment by dr-dimitru** [comment]
Hello @gischer,

> When I look at server.js, unlink is defined at line 1471 and my read of this code suggests that the bug is here. If there is a versions object, then all the versions are deleted, but the original is not.

`versions` object always has `original` object where `fileObj.versions.original.path === fileObj.path`

And we can not reproduce same issue. Try latest available package release, maybe it's solved.

Feel free to reopen it in case if the issue is still persists on your end.
