### ISSUE TITLE
How to update an image.

### ISSUE THREAD

**Issue by sir007** [VeliovGroup/Meteor-Files#645]
Hi,
Thank you for the great module !
My environment:
- Windows 7
- METEOR@1.6.0.1
- ostrio:files  1.9.6

I successfully inserted image; but i cannot update it.     
  
Client.js 

Template.Image.events({
  'change #fileInput'(e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
		
		image = e.currentTarget.files[0];

			Meteor.call('updateImage',(image, error, result) =>{

					if(error){
						console.log(error.reason); 
						
					}

					else {
						console.log("success");
					}
							
			});	
	
    }
  }
});

server.js 

'updateImage'(
					image
					){
		
					userIdProfile = imagesProfile.findOne({userId: Meteor.userId()}).userId;
					return imagesProfile.update(
						{
							userId: userIdProfile
						},
						{
							$set:
							{ 
						 
								file: imageProfile,
								LastUpdate: new Date()    
							}
						}
					)
							
	},

Server logs:
W20180922-01:37:51.321(1)? (STDERR) (node:3492) UnhandledPromiseRejectionWarning
: Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack
size exceeded
W20180922-01:37:51.323(1)? (STDERR) (node:3492) [DEP0018] DeprecationWarning: Un
handled promise rejections are deprecated. In the future, promise rejections tha
t are not handled will terminate the Node.js process with a non-zero exit code.

Do you have a idea on how to solve it?

**Comment by dr-dimitru** [comment]
Hello @sir007 ,

Update is possible, but it will require extra coding.
We highly recommend to remove and upload/load/write/add a new image

**Comment by sir007** [comment]
Thanks @dr-dimitru 
I'm still having some problems:

server.js

'updateImage'(
image
){
id = imagesProfile.findOne({userId: Meteor.userId()})._id;
					images.remove({_id: id}, (error) => {
						if (error) {
							console.error(' failed to delete file, error:  ${error.reason}');
						} 
						else {
							console.info('File deleted');
							fs.readFile(image, function (error, data) {
							  if (error) {
								throw error;
							  } else {
								imagesProfile.write(data, {
								  fileName: image,
								  userId: Meteor.userId(), 
								}, function (writeError, fileRef) {
								  if (writeError) {
									throw writeError;
								  } else {
									console.log(fileRef.name + ' is successfully saved to FS. _id: ' + fileRef._id);
								  }
								});
							  }
							});
															
						}
					});
						
}

Server logs:
Exception in callback of async function: TypeError: path must be a string or Buffer

I understand that the problem is the line:
"fs.readFile(image, function (error, data)"
image is the file submit by the client. Is it correct to use it as a buffer ?

**Comment by dr-dimitru** [comment]
@sir007 
```js
console.log(image);
```

**Comment by sir007** [comment]
Hi @dr-dimitru ,
are you very busy ?

**Comment by dr-dimitru** [comment]
@sir007 

> image is an object, to you know how to get the file's name of that object?

[`e.currentTarget.files[0].name`](https://developer.mozilla.org/en-US/docs/Web/API/File/name)

> imagesProfile.remove({_id: id}) --------> only delete the doc; but does not delete the file in the FS . How to delete the doc and the file in FS ?

[`.remove()`](https://github.com/VeliovGroup/Meteor-Files/wiki/remove) removes both record and file

**Comment by sir007** [comment]
@dr-dimitru,
on the browser console console.log(image.name) prints the name of the image uploaded;
on the server side, console.log(image.name)  prints undefined

I tried the following codes : 
const util = require('util');
console.log(util.inspect(image, {showHidden: false, depth: null})); // prints an emty object

console.log(JSON.stringify(image, null, 4)); // prints an empty object

but:
console.log(image);  // prints (object, object)

I don't understand

**Comment by dr-dimitru** [comment]
@sir007 it's difficult to understand what you're trying to accomplish.

**Comment by sir007** [comment]
@dr-dimitru  sorry if my goal is difficult to understand.
I want to develop a feature that allows users to update their profile image.
You advised me to delete the old image and add the new image.
This the code used:

client.js

Template.ModifierImageProfile.events({
  'change #fileInput'(e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
		image = e.currentTarget.files[0];
			Meteor.call('updateImage', image,(error, result) =>{
					if(error){
						alert(error.reason);
					}

					else {
						alert("image updated");
					}
							
			});	
	
	
    }
  }
});


server.js

'updateImage'(image){
		
				check (image, Object);
								try {
					if (!this.userId) {
						throw new Meteor.Error('405', 'Accès denied');
					}
					
					imageId = imagesProfile.findOne({userId: Meteor.userId()})._id;
					images.remove({_id: Id}, (error) => {
						if (error) {
							console.error('error while deleting file, error:  ${error.reason}');
						} 
						else {
							console.info('file deleted');
							
							fs.readFile(image, function (error, data) {
							  if (error) {
								throw error;
							  } else {
								images.write(data, {
								  fileName: image.name,
								  userId: Meteor.userId(), 
								}, function (writeError, fileRef) {
								  if (writeError) {
									throw writeError;
								  } else {
									console.log(fileRef.name + ' is successfully saved to FS. _id: ' + fileRef._id);
								  }
								});
							  }
							});
														
						}
					});
				} 
	 
				catch (exception) {
					throw new Meteor.Error('405', exception.message);
				} 	
	},
	
});

The code can delete the old image ; but cannot add the new one.
I'm not sure that the server receives the image sent by the browser (using the method updateImage), because console.log (image.name) client side displays the name of the image but on the server side nothing is displayed.
I'm probably not on the right track or something is missing or wrongin the code.

**Comment by dr-dimitru** [comment]
@sir007 why you're using `.write()` method, while you should use `.insert()`?

That's scenario you should stick to:
1. User clicks <kbd>Update</kbd> (or click on `input[type="file"]`)
2. Trigger click on `input[type="file"]`
3. User picks image to upload
4. Inside of `change input[type="file"]` event:
   1. Trigger `image.remove` *Meteor* server method
   2. Inside of `image.remove` *Meteor* method callback:
      1. Pass image to `FilesCollection#upload()` method

**Comment by sir007** [comment]
@dr-dimitru,
 let me try, i will let you know.

**Comment by sir007** [comment]
@dr-dimitru ,

i hope that is you are talking about : 

client.js

Template.image.events({
  'change #fileInput'(e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
		
		image = e.currentTarget.files[0];
		
		imageId = images.findOne({userId: Meteor.userId()})._id;
		images.remove({_id: imageId, userId: Meteor.userId() }, (error) => {
			if (error) {
				console.error(`File wasn't removed, error:  ${error.reason}`);
			} else {
				console.info('File successfully removed');				
						
				Meteor.call('FilesCollection#upload', image,(error, result) =>{

					if(error){
						console.log(error.reason);
					}

					else {
						console.log("image updated");
					}
							
				});	 
				
				
			}
		});


    }
  }
});

**Comment by dr-dimitru** [comment]
> i hope that is you are talking about :

No. Im telling you to use [`.insert()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))

**Comment by sir007** [comment]
@dr-dimitru thank you for allowing me to move forward.
This is the new code:
client.js

Template.ModifierImageProfile.events({
  'change #fileInput'(e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
		
		image = e.currentTarget.files[0];
		
		imageId = imagesProfile.findOne({userId: Meteor.userId()})._id;
		images.remove({_id: imageId, userId: Meteor.userId() }, (error) => {
			if (error) {
				console.error(`File wasn't removed, error:  ${error.reason}`);
			} else {
				console.info('File successfully removed');				
						
				images.insert({
					file: image,
					onStart() {
					  template.currentFile.set(this);
					},
					onUploaded(error, fileObj) {
					  if (error) {
						alert('Error during upload: ' + error);
					  } else {
						alert('File "' + fileObj.name + '" successfully uploaded');
					  }
					  template.currentFile.set(false);
					},
					streams: 'dynamic',
					chunkSize: 'dynamic'
				});		
			}	 
				
		});
		
    }
  }
});

collection.js
imagesProfile = new FilesCollection({
  collectionName: 'imagesprofile',
  storagePath: "C:/meteorapps/teledocta/public/imagesProfile",
  allowClientCode: true, // allow remove files from Client
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  },

    onBeforeRemove(cursor) {
    const records = cursor.fetch();

    if (records && records.length) {
      if (this.userId) {
		user = const user = this.user();
        //const user = this.user();
        // Assuming user.profile.docs is array
        // with file's records _id(s)

        for (let i = 0, len = records.length; i < len; i++) {
          const file = records[i];
          if (!~user.docs.indexOf(file._id)) {
            // Return false if at least one document
            // is not owned by current user
            return false;
          }
        }
      }
    }

    return true;
  }

I have the following exception
Exception while invoking method '_FilesCollectionRemove_images' TypeError: Cannot read property 'indexOf' of undefined

**Comment by dr-dimitru** [comment]
Feels like it doesn't relative to lib, and you're experiencing issue in your own codebase.
Feel free to reopen it in case if the issue is still persists on your end.
