### ISSUE TITLE
Calling a method from within Files.write callback losses logged in status

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-Files#648]
### I'm having an issue:
Hi! @dr-dimitru. I have setup a Meteor **server** method to upload files from React Native app. The upload process is just fine, I can upload files sent by RN using ```react-native-meteor``` package by converting them from base64 to Buffer. After upload, I want to call a method from ```Files.write``` callback but seems to lost logged in status in the called method.

I'm calling this method (reports.insert) from React Native:
```
export const insertReport = new ValidatedMethod({
  name: 'reports.insert',
  validate: ReportsSchema.validator(),
  run(report) {
...
...
...
        Files.write(
          Buffer.from(
            report.image.replace(/^data:image\/\w+;base64,/, ''),
            'base64',
          ),
          {
            fileName: `report.${extension}`,
            type: fileMime,
            meta: { uploadFolder, fileType },
            userId: this.userId,
          },
          function(error, result) {
            if (error) {
                console.log('Error during upload:', error);
            } else {
              Meteor.call(
                'reports.updateReportImage',  // Here reports.updateReportImage seems to lost logged in status
                {
                  reportId,
                  reportImageId: null,
                  fileId: result._id,
                },
                (error, result) => {
                  if (error) {
                      console.log('Error during uploadFile:', error);
                  }
                    console.log('uploadFile result:', result);
                },
              );
            }
          },
          true,  // I want onAfterUpload to be processed
        );
...
...
...
});
```
After running the method, I get : **Error: { Error: [reports.updateReportImage] Public access denied [notLogged]** which is my error message for the reports.updateReportImage method if not logged. To check logged in status in reports.updateReportImage I'm using LoggedInMixing package like this:
```
export const updateReportImage = new ValidatedMethod({
  name: 'reports.updateReportImage',
  mixins: [LoggedInMixin],
  checkLoggedInError: {
    error: 'notLogged',
    message: '[reports.updateReportImage] Public access denied',
    reason: 'You need to have a valid account,
  },
```
  - Version of `Meteor-Files` ostrio:files@1.10.2
  - Version of `Meteor` METEOR@1.7.0.5
  - Where this issue appears? Meteor
  - Is it *Client* or *Server* issue? Server

Do you have an idea on how can I solve this to not lose logged in status?

Thanks!

**Comment by dr-dimitru** [comment]
Hello @mgscreativa ,

I'm very sorry for the late reply, it seems to me not related to Meteor-Files package, but only to `ValidatedMethod` configuration. Let me know if you have solved this issue and how, thank you.

**Comment by mgscreativa** [comment]
Hi! Solved it this way https://github.com/mgscreativa/React-Native-Upload-Files-to-Meteor-Server by implementing an API endpoint in meteor

**Comment by dr-dimitru** [comment]
@mgscreativa good job 👍
