### ISSUE TITLE
Exception from sub Images

### ISSUE THREAD

**Issue by msio777** [VeliovGroup/Meteor-Files#65]
Hi

I got this kind of exception 
```shell
Meteor.Files Debugger: [find(undefined)]
I20160409-16:15:55.655(2)? Exception from sub Images id GngR84PRRRtf9ZjhC Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
I20160409-16:15:55.655(2)?     at check (packages/check.js:138:15)
I20160409-16:15:55.655(2)?     at Files.Meteor.Files.Files.find (packages/ostrio_files/files.coffee:695:5)
I20160409-16:15:55.656(2)?     at Subscription._handler (server/init.js:10:26)
I20160409-16:15:55.656(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160409-16:15:55.656(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160409-16:15:55.656(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160409-16:15:55.656(2)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160409-16:15:55.656(2)?     at packages/ddp-server/livedata_server.js:551:43
I20160409-16:15:55.657(2)? Sanitized and reported to the client as: Match failed [400]
```

thanks for help
Best Regards
Michal

**Comment by dr-dimitru** [comment]
Hi @msio777 

1. You're passing `undefined` to `find()` method, is this correct?
2. This error appears in new package version, on old codebase?

Please, provide you code sample

**Comment by msio777** [comment]
Unfortunately I dont pass any parameter and in v1.4.1

**Comment by dr-dimitru** [comment]
Just pass empty object `findOne({})`
This will be fixed in v1.4.2

**Comment by msio777** [comment]
I even dont use findOne({}) .. If I switch to route with Meteor.Files .. I got this kind of exception

**Comment by dr-dimitru** [comment]
Please, post your code here, where you're using Meteor.Files, and your publish/subscribe block

**Comment by msio777** [comment]
`InterestIcons = new Meteor.Files({
    collectionName: 'InterestIcons',
    storagePath: '~/interests',
    debug: true
});`

`InterestIcons.collection.allow({
    insert: function () {
        return true;
    },
    update: function () {
        return true;
    }
});`

` 'change [name="icon"]': function (e, t) {
        var file = e.currentTarget.files[0];
        InterestIcons.insert({
            file: file,
            onUploaded: function (error, fileObj) {
                if (error) {
                    alert('Error during upload: ' + error);
                } else {
                    alert('File "' + fileObj.name + '" successfully uploaded');
                }
            },
            streams: 'dynamic',
            chunkSize: 'dynamic'
        });
    }`


I dont have any own custom publlish/subscription and still I got this exception

**Comment by dr-dimitru** [comment]
Remove this block (*this is done internally*):
```
InterestIcons.collection.allow({
    insert: function () {
        return true;
    },
    update: function () {
        return true;
    }
});
```

This happens after file is uploaded?

**Comment by dr-dimitru** [comment]
Let me know if this issue persists in v1.4.2

**Comment by msio777** [comment]
yeah, I got just this validation in browser 
`Uncaught Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation`
please open the issue

**Comment by msio777** [comment]
How can I fit it. I used example from github

**Comment by dr-dimitru** [comment]
Which example exactly?
1. I need to understand what you're running
2. Where this error appears Client or Server?
3. What platform you're on? Win? Mac? Linux?

**Comment by msio777** [comment]
Meteor 1.3, Mac OSX 10.11.4, on Client in Browser appears that error

**Comment by dr-dimitru** [comment]
0. Could you post all code of your app? How subscription error may appear if you're not subscribing to anything?
1. Have you updated package to v1.4.2?

**Comment by msio777** [comment]
I am so sorry. On the other application I didnt have thw newest version ... best package for file upload .. I am gonna share it :+1: 

close the issue please

**Comment by dr-dimitru** [comment]
No worries, thank you for contribution and participation, cheers!
