### ISSUE TITLE
Upload files from React Native to Meteor with Meteor-Files

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-Files#650]
Hi @dr-dimitru! In my quest to be able to upload files from my React Native app to Meteor using your package I've created this demo repo to test things up https://github.com/mgscreativa/React-Native-Upload-Files-to-Meteor-Server

After you clone it, you will need to edit settings-demo.json, specifically **DROPBOX_TOKEN**, then cd into **meteor-server** and run `meteor --settings settings-development.json`. Then cd into **react-native-app** and run `expo start`.

You will need to install expo: `sudo npm install -g expo`. then , in your Android or iPhone you can get the app running by downloading the expo app.
### Meteor login
- **user**: admin@admin.com
- **password**: password

## Notes
- It uses base64 to transfer the files
- So far, I can only upload images, taken or grabbed from camera roll
- If I try to upload a video from camera roll, it uploads just fine, but file get's corrupted (can't play it, maybe base64 to blame?)
- If I try to upload a file from document picker, it uploads just fine, but file get's corrupted (can't open it, maybe base64 to blame?)

I hope you get some time to run the project and point me about the right way to upload files from React Native. Thanks a lot in advise

**Comment by mgscreativa** [comment]
Hi! Just wanted to mention that I've added https://github.com/mgscreativa/React-Native-Upload-Files-to-Meteor-Server to my test repo, so far, testing /api/v1/uploads with postman works just fine, will test with RN and let you know.

Regards

PS: I want to write a demo that really works for RN and your files package...

**Comment by mgscreativa** [comment]
Hi! Just wanted to say that the corrupted files upload issue is definitely because of base64. I updated my repo by using raw post and an Apisauce post to the meteor server without using base64 at all and it works just fine!.

So, for me this question is solved as POST is the best option right now.

Consider that FileReader.readAsBinaryString and FileReader.readAsArrayBuffer aren't implemented in RN yet so it's not posible to forge File object to send binary data through DDP. Maybe if thoose functions get implemented, it may be possible to call FIles.insert from RN.

Last note, @dr-dimitru, would you be so ind to mention my repo in Meteor-Files your docs, so RN+Meteor newbies like may avoid the hassle of file uploads to Meteor server.

Thanks!

**Comment by dr-dimitru** [comment]
Hello @mgscreativa 

> Last note, @dr-dimitru, would you be so kind to mention my repo in Meteor-Files your docs?, so RN+Meteor newbies like may avoid the hassle of file uploads to Meteor server.

Sure, np. Feel free to send a PR to our docs and wiki to `dev` branch.

> Consider that FileReader.readAsBinaryString and FileReader.readAsArrayBuffer aren't implemented in RN yet so it's not posible to forge File object to send binary data through DDP. Maybe if thoose functions get implemented, it may be possible to call FIles.insert from RN.

Can't you use something similar as reading image via Canvas and pulling base64 out of it?

**Comment by mgscreativa** [comment]
Hi @dr-dimitru! just created a PR in dev branch https://github.com/VeliovGroup/Meteor-Files/pull/652 but I don't know how to PR the Wiki, do you know how can I add the new **docs/react-native-example.md** to the Wiki?

Thanks!

**Comment by dr-dimitru** [comment]
We will do proofreading on our end then push update to the Wiki.
Thank you for PR, we're very busy this month, so merge might be delayed.

**Comment by dr-dimitru** [comment]
@mgscreativa please see my comments and requested changes on #652 and feel free to reopen discussion with following PR, thank you.
