### ISSUE TITLE
Always reload page after Files.insert()?

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-Files#651]
I base on `Meteor + Vue`.
- Meteor 1.7.0.5
- Files 1.10.2

```js
const Files = new FilesCollection({
  storagePath: () => {
    return `${Meteor.absolutePath}/fileUploads` // project path
  },
  collectionName: 'app_files',
})
```

```js
// Vue tmp
<p>
      <img
        :src="filePreview"
        width="120px"
        height="125px"
      />
      <input
        ref="fileUploadHidden"
        type="file"
        accept="image/*"
        style="display: none"
        @change="filePicked"
      >
    </p>

    <el-button
      type="default"
      @click="pickFile"
    >Select file</el-button>
    <el-button
      type="primary"
      @click="uploadFile"
    >Upload file</el-button>
-----------
// Vue method
    uploadFile() {
      if (this.fileUpload) {
        Files.insert({
          file: this.fileUpload,
          streams: 'dynamic',
          chunkSize: 'dynamic',
          onUploaded(err, fileObj) {
            console.log('Upload', fileObj)
            if (err) {
              Notify.error({ message: 'File upload is error' })
            } else {
              Notify.success({ message: 'File upload is success' })
            }
          },
        })
      } else {
        Notify.error({ message: 'File upload is required' })
      }
    },
```
I tried to use `@click.prevent="pickFile"`, still reload.
Please help me.

**Comment by dr-dimitru** [comment]
Hello @thearabbit ,

Could you run a profiler with network logging to find out what causes page reload?
Haven't seen that weird behavior, looks like unrelated to Meteor-FIles.

**Comment by thearabbit** [comment]
Thanks for your reply.
Maybe problem with `fileUploads folder` is in `Project Path`!!!
```js
/my-app
   client/
   server/
   fileUploads/
```
Could you example to use `PC Path` on `Mac, Ubuntu and Window`?
```js
const Files = new FilesCollection({
  storagePath: () => {
    return `~/Desktop/fileUploads` // Mac, Ubuntu
    return `~/Desktop/fileUploads` // Windows
  },
  collectionName: 'app_files',
})
```
Please help me

**Comment by thearabbit** [comment]
It still store in `.meteor/....`.
But I would like to store in `~/Desktop/fileUploads`

**Comment by dr-dimitru** [comment]
@thearabbit do not use `~` in a `storagePath`.
__Always__ use *absolute* paths. For no-brainer solution use [`meteor-root` package](https://atmospherejs.com/ostrio/meteor-root).
But in your case this isn't necessary, just update your path. It should be something like:
```
/Volumes/sda/users/thearabbit/Desktop/fileUploads
```

**Comment by thearabbit** [comment]
I tried 
```js
return `${Meteor.absolutePath}/fileUploads`
---
/app
  fileUploads/
```
But It always reload page when uploaded.
So I would like to trie store outside `meteor project`.
Could I use `meteor-root` prefix for outside?
Please example

**Comment by thearabbit** [comment]
I tried `cd to Volumes` on terminal
```
~ cd /Volumes/sda/
cd: no such file or directory: /Volumes/sda/
```

**Comment by thearabbit** [comment]
Could advise should be use `outside path, project path, ./meteor path...`?

**Comment by dr-dimitru** [comment]
@thearabbit read about [navigation in Unix-like systems](https://www.digitalocean.com/community/tutorials/basic-linux-navigation-and-file-management)

> I tried cd to Volumes on terminal

I don't know your particular environment, all paths in my examples are __pseudo__-paths

> Could advise should be use outside path, project path, ./meteor path...?

```bash
# outside
./meteor/../storagePath

# as we recommend:
/data/uploads
```

Create `/data/uploads`:

```shell
mkdir -p /data/uploads
chmod -R 777 /data
```

```js
const Files = new FilesCollection({
  storagePath: () => {
    return `\data\uploads` // Mac, Ubuntu
    return `C:\data\uploads` // Windows
  },
  collectionName: 'app_files',
})
```

**Comment by thearabbit** [comment]
Very thanks again.
It work fine 👍
