### ISSUE TITLE
Problem extending schema

### ISSUE THREAD

**Issue by felixb101** [VeliovGroup/Meteor-Files#653]
Schema extension as described in the docs simply does not work. Keep getting "Match error: Unkown key..."

**Comment by felixb101** [comment]
const mySchema = {
  ...FilesCollection.schema,
  myProp: {type: String, optional: true},
};

const Images = new FilesCollection({
  storagePath: 'assets/app/uploads/Images',
  downloadRoute: '/files/images',
  protected: false,
  collectionName: 'Images',
  schema: mySchema,
 ....
Images.collection.attachSchema(new SimpleSchema(Images.schema));

**Comment by felixb101** [comment]
Documentation issue. ONLY ALLOWED to add sub-fields in the META main field.

**Comment by jankapunkt** [comment]
@felixb101 mind to add a PR on this?

**Comment by felixb101** [comment]
The issue is that trying to extend the schema didn't work for me. However, adding my own object to the "meta" field worked like a charm:

`        let uploadInstance = Images.insert({
          file: file,
          meta: {
            locator: self.props.fileLocator,
            parent: Parent,
            userId: Meteor.userId(), // Optional, used to check on server for file tampering
            uploadedAt: (new Date()).toISOString(),
          },
          streams: 'dynamic',
          chunkSize: 'dynamic',
          allowWebWorkers: true // If you see issues with uploads, change this to false
        }, false)
`
