### ISSUE TITLE
Thousands of S3 bucket requests with S3 integration

### ISSUE THREAD

**Issue by cmoses8626** [VeliovGroup/Meteor-Files#654]
WONDERFUL package, thanks so much! I've successfully setup the S3 integration. I enabled S3 service logs and it appears thousands of access requests are being made multiple times every minute to the bucket I connected to the files collection. However, I've only run my app a few times, so there are thousands of access requests that I am not making - and there are no other users in the app.

Here's a screenshot showing the timestamps of the service logs:
<img width="326" alt="screen shot 2018-11-20 at 10 34 54 am" src="https://user-images.githubusercontent.com/1293068/48784491-c6e38980-ecb0-11e8-97fb-505e4293d3ef.png">

Is this expected behavior?

I'm using package v1.10.2 with Meteor 1.8.

**Comment by dr-dimitru** [comment]
Hello @cmoses8626 ,

This is definitely not expected, but as S3 integration isn't part of the core, – you should look into [integration implementation](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration) and `aws-sdk` package itself.

Maybe it's normal behavior, are you able to see payload of those requests?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
