### ISSUE TITLE
Client can't establish a connection to the server at ws:localhost:8080/websockets.

### ISSUE THREAD

**Issue by gischer** [VeliovGroup/Meteor-Files#655]
### I'm having an issue:

I have created a Meteor app which uploads images and videos and lets users add things to them in an overlay display, as well as add titles and so on.

When I run this app using "meteor -p 8080" and try to access it from another computer using the URL http://[ip address]:8080/, it doesn't work right.  I see lots of errors in the console that say,  "Firefox can't establish a connection to the server at ws:localhost:8080/websockets."

I'm using version 1.9.11 of Meteor-Files on version 1.7.0.5 of Meteor

I'm unsure of what's going on here. I have seen suggestions that Websockets will not allow connections that aren't encrypted.  However,  I know that Meteor/DDP uses websockets, and I have successfully used other Meteor apps running this way.  So I'm very confused at this point, and unsure just where to look.

**Comment by dr-dimitru** [comment]
Hello @gischer ,

Have you tried to set `ROOT_URL` env.var? Like:

```shell
ROOT_URL="http://[ip address]:8080/" meteor -p 8080
```

**Comment by gischer** [comment]
I resolved this issue and forgot to close this.  Sorry about that.  I think I had a configuration issue, actually.
