### ISSUE TITLE
how to auto config Collection without `mkdir -p /data/uploads` by manual

### ISSUE THREAD

**Issue by thearabbit** [VeliovGroup/Meteor-Files#657]
I would like to auto config Collection, without create directory store by manual `mkdir -p /data/uploads`.
Please help me
```js
const Files = new FilesCollection({
  // debug: true,
  storagePath: () => {
    return '/data/meteor_uploads'
  },
  collectionName: 'app_files',
})
```

**Comment by jankapunkt** [comment]
You could write a shell script to automate this step before starting your application or deploying to the server.

**Comment by dr-dimitru** [comment]
Hello @thearabbit ,

If `/data/` directory exists and writable, `/data/meteor_uploads` will be automatically created.
Feel free to close it in case if the issue is solved on your end.

**Comment by thearabbit** [comment]
@jankapunkt, could you example `You could write a shell script to automate this step before starting your application or deploying...`

I use `Mup` to deploy.

**Comment by thearabbit** [comment]
@dr-dimitru, Very thanks.
Could I automate to create `/data`, if don't exist?

**Comment by dr-dimitru** [comment]
@thearabbit you can use [`preinstall` property](https://docs.npmjs.com/misc/scripts) in `package.json` file:

```json
{
  "name": "my-meteor-app",
  "version": "1.0.0",
  "description": "description",
  "main": "main.js",
  "scripts": {
    "preinstall": "mkdir -p /data/uploads",
    "start": "node main.js"
  }
}
```

**Comment by dr-dimitru** [comment]
@thearabbit friendly ping, have you solved this task somehow?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
