### ISSUE TITLE
Update the docs: For the S3 integration to work the IAM user also needs "DeleteObject" permission

### ISSUE THREAD

**Issue by tschneid** [VeliovGroup/Meteor-Files#658]
I followed the instructions for the [AWS S3 Integration](https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration), which also includes a wrapper to delete files from S3 when `Images.remove()` is called. When trying this out `s3.deleteObject` throws `AccessDenied`.

To make this work the IAM user additionally needs the `DeleteObject` permission (which is not set in the linked [example](https://vincetocco.com/backup-your-servers-automatically-to-amazon-aws-s3/) on how to set up AWS S3). So the adapted policy would be: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME",
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}
```
Only `"s3:DeleteObject",` was added.
Does anyone see any security implications with this?

**Comment by jankapunkt** [comment]
@tschneid would you mind to open a PR with updated instructions?

**Comment by jankapunkt** [comment]
Merged via https://github.com/VeliovGroup/Meteor-Files/pull/689 feel free to reopen if there remains anything related to this issue.
