### ISSUE TITLE
cant show inserted image 

### ISSUE THREAD

**Issue by msio777** [VeliovGroup/Meteor-Files#66]
hi,

I use thus code 
```html
    {{#if currentFile}}
        Uploading <b>{{currentFile.file.name}}</b>:
        <span id="progress">{{progress}}%</span>
        <img src="{{fileURL imageFile}}" alt="{{imageFile.name}}"/>
    {{else}}
        <input id="fileInput" type="file"/>
    {{/if}}
    <hr>
```

and that in template helper 
```js
   imageFile: function () {
        return InterestIcons.collection.findOne({});
    }
```

and cant see the uploaded image 

Best regards

**Comment by msio777** [comment]
picture is uploaded server:

`Meteor.Files Debugger: [MeteorFileWrite] {name: K8g3CxveXuPCswMhQ, meta:[object Object]}
I20160409-22:51:54.725(2)? Meteor.Files Debugger: Received chunk #1 of 1 chunks, file: dance-icon.png
I20160409-22:51:54.802(2)? Meteor.Files Debugger: [MeteorFileWrite] {name: K8g3CxveXuPCswMhQ, meta:[object Object]}
I20160409-22:51:54.802(2)? Meteor.Files Debugger: Received chunk #-1 of 1 chunks, file: dance-icon.png
I20160409-22:51:54.811(2)? Meteor.Files Debugger: The file dance-icon.png (binary) was saved to ~/interests/K8g3CxveXuPCswMhQ.png`

on the client:
`Meteor.Files Debugger: [insert()]
files.coffee:878 Meteor.Files Debugger: Connection established continue() upload
files.coffee:884 insert: 121.977ms`

**Comment by dr-dimitru** [comment]
Have you subscribed to this data? Please see [this example](https://github.com/VeliovGroup/Meteor-Files/blob/master/demo-simplest-streaming/lib/files.collections.js#L27)

**Comment by dr-dimitru** [comment]
Also you need to change template to:
```html
    {{#if currentFile}}
        Uploading <b>{{currentFile.file.name}}</b>:
        <span id="progress">{{progress}}%</span>
    {{else}}
        <input id="fileInput" type="file"/>
    {{/if}}
    <hr>
    {{#if imageFile}}
         <img src="{{fileURL imageFile}}" alt="{{imageFile.name}}"/>
    {{/if}}
```

**Comment by msio777** [comment]
server 

`Meteor.publish('files.images.all', function () {
    return InterestIcons.collection.find({});
});`

client 
`Router.route('/interests/new', {
    name: 'newInterest',
    waitOn: function () {
        return [Meteor.subscribe('InterestType'),Meteor.subscribe('files.images.all')];
    }
});`

**Comment by dr-dimitru** [comment]
Does my comment about template fix this issue?

**Comment by msio777** [comment]
unfortunately no .. looks better 
`I20160409-22:58:32.321(2)? Meteor.Files Debugger: [findOne("Azyz5KMzneroddsWW")]
I20160409-22:58:32.322(2)? Meteor.Files Debugger: [download(/cdn/storage/InterestIcons/Azyz5KMzneroddsWW/original/Azyz5KMzneroddsWW.png, original)]
W20160409-22:58:32.324(2)? (STDERR) Meteor.Files Debugger: [download(/cdn/storage/InterestIcons/Azyz5KMzneroddsWW/original/Azyz5KMzneroddsWW.png)] [404] File not found`

**Comment by msio777** [comment]
but the image is in filesystem I checked it

**Comment by dr-dimitru** [comment]
Okay, I saw from you previous issue, what you're using path relative to you user (starts with `~`)
Could you try to change it to absolute path?

**Comment by dr-dimitru** [comment]
Or even try to keep package's default (*for testing purpose*)

**Comment by msio777** [comment]
I have it but I didnt want to publish it ;)

**Comment by msio777** [comment]
It works right know but It finds only one image but I want to display curently uploaded

**Comment by dr-dimitru** [comment]
Then do something like:
```js
Template.uploadForm.onCreated(function () {
  this.uploadedFile = new ReactiveVar(false);
});

Template.uploadForm.helpers({
  currentFile: function () {
    return Template.instance().currentFile.get();
  },
  uploadedFile: function () {
    return Template.instance().uploadedFile.get();
  }
});

Template.uploadForm.events({
  'change #fileInput': function (e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
      var file = e.currentTarget.files[0];

      template.currentFile.set(Images.insert({
        file: file,
        onUploaded: function (error, fileObj) {
          if (error) {
            alert('Error during upload: ' + error);
          } else {
            // Two options
            // First (no need for subscription):
            template.uploadedFile.set(fileObj);
            // Second (subscription needed):
            template.uploadedFile.set(InterestIcons.collection.findOne({_id: fileObj._id}));
          }
          template.currentFile.set(false);
        },
        streams: 'dynamic',
        chunkSize: 'dynamic'
      }));
    }
  }
});
```

**Comment by dr-dimitru** [comment]
I'n off for today, will check you reply tomorrow

**Comment by msio777** [comment]
I figured it out with similar implementation .. thanks a lot man :)

**Comment by dr-dimitru** [comment]
Solved? Right?

**Comment by msio777** [comment]
that's right .. thanks for your support :)
