### ISSUE TITLE
One frontend many meteor+ostrio:files servers

### ISSUE THREAD

**Issue by portah** [VeliovGroup/Meteor-Files#660]
I have quite a complicated setup. Meteor + ostrio:files - servers and one meteor+angular frontend. Frontend uses oauth2 client to authorize itself on one of  Meteor + ostrio:files server (s1). Oauth2 process opens popup to s1 uses meteor password package and then redirects back to the frontend server.  Client can create extra DDP connection to s1 with access token to authorize this extra DDP connection FilesCollection can be attached to this DDP and upload works just fine. After finishing upload I have a direct link to s1 http://s1/cdn/storage/raw_data_files/t4gHGDfRcrr2s39kR/original/t4gHGDfRcrr2s39kR.tsv which gives access deny. 

If I understand right, it happens because meteor closes the original connection after oauth2 popup (s1) closed and I can't access this.userId inside protect function. If I open extra tab in chrome to s1 server I can download file. 

One workaround that I can see it's to add a token after direct link like (?token=...) I can use JWT.

Is there any simpler solutions?

Thanks

**Comment by dr-dimitru** [comment]
Related to #692 
@portah please upgrade package to latest available release, this issue should be solved by now
Feel free to reopen it in case if the issue is still persists on your end.
