### ISSUE TITLE
Streaming files on mobile application (cordova)

### ISSUE THREAD

**Issue by AntoineTohan** [VeliovGroup/Meteor-Files#661]
Hello, 
I am trying to get video playback work with Meteor 1.8.0.1 and Cordova on Android and IOS devices. I'm currently trying to stream my file with simple HTML5 video tag. My video file is an .mp4 in h264 codec. 
We used meteor package file : ostrio:files (VeliovGroup/Meteor-Files) verison 1.9.11. Notice that we  generate custom URL instead of use file.link(), that can be used with --mobile-server in Cordova (see in the #597 issue).
Example of custom URL that we use for stream file in classic browser. 
```
https://domain.com/cdn/storage/Filesupload/cFPNcK5K5bFpcc/original/c2pcatHFPK5bFc.mp4 
```
The stream is working perfectly on the web app, but once I go to the mobile app the playback could not launch.

First of all when i start my mobile application i get this error multiples times (but the application work perfectly) : 
```
Failed to load http://192.168.17.3:3000/_timesync: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12768' is therefore not allowed access.
```

And when i'm trying to stream my file i get two errors : 

```
Refused to load the image 'android-webview-video-poster:default_video_poster/-2094984208415350593' because it violates the following Content Security Policy directive: "default-src * gap: data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```
Related to SCP meteor/meteor#8965 i think :/ but even after a long search that I couldn't fix this bug. 

And the last error related to my link stream :
```
GET https://domain.com/cdn/storage/Filesupload/2Nc2YatHFPK5bFpcc/original/2Nc2YatHFPK5bFpcc.mp4  net::ERR_CONNECTION_REFUSED
```
But when I click on the link to open it in the browser the link works perfectly. The HTML video player launch perfectly in mobile too but the video can't be load. 

Have you ever experienced this kind of problems before ? and is there any known issue ?

Permission on android maybe ? I don't really know where to look if this is Cordova , ostrio:files, Content Security Policy or Meteor related ?

**Comment by dr-dimitru** [comment]
Hello @AntoineTohan 

Take a look on https://github.com/VeliovGroup/Meteor-Files/issues/547

 1. Do you set `MOBILE_DDP_URL` env.var?
 2. What upload transport you're using?

**Comment by dr-dimitru** [comment]
We don't support WebRTC, this branch is abandoned.

Could you please update this thread with info following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Give an expressive description of what is went wrong
  - Version of `Meteor-Files` you're experiencing this issue
  - Version of `Meteor` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  - Is it *Client* or *Server* issue?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by AntoineTohan** [comment]
Thank you for answering again @dr-dimitru !

 WebRTC, this branch is abandoned. Ok but then does that mean it's not compatible with the latest versions of Cordova, IOS and Android ?

Below I put the answer to the issue template. For more information the first post was very detailed :

1. Give an expressive description of what is went wrong
- I am trying to get video playback work with Meteor and Cordova on Android and IOS devices. I'm currently trying to stream my file with simple HTML5 video tag. My video file is an .mp4 in h264 codec.

2. Version of Meteor-Files you're experiencing this issue
- Meteor-Files version 1.9.11

3. Version of Meteor you're experiencing this issue
- Meteor 1.8.0.1 

4. Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
- Cordova on Android and IOS devices (all versions of android and IOS).

5. Is it Client or Server issue?
- I don't know :disappointed: 

6. Post Client and/or Server logs with enabled debug option, you can enable "debug" mode in Constructor
- These are the server and client logs in same time because I run my Android or IOS application on real devices, so I can't dissociate them.

```
[INFO:CONSOLE(544)] "[FilesCollection] [find({"name":{"$regex":{}}}, undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FilesCursor] [count()]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [find({"$or":[{"name":{"$regex":{}}},{"meta.folders":{"$regex":{}}}]}, {"sort":{"name":1}})]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FilesCursor] [fetch()]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne(false, undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [find({"name":{"$regex":{}}}, undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FilesCursor] [count()]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [find({"$or":[{"name":{"$regex":{}}},{"meta.folders":{"$regex":{}}}]}, {"sort":{"name":1}})]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FilesCursor] [fetch()]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne(false, undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne("BEpoYw4ZPE92XFPLN", undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FileCursor] [get(undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [find({"meta.sourceId":"BEpoYw4ZPE92XFPLN"}, undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [FilesCursor] [fetch()]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne("BEpoYw4ZPE92XFPLN", undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne("BEpoYw4ZPE92XFPLN", undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(0)] "Refused to load the image 'android-webview-video-poster:default_video_poster/-4175200696651447828' because it violates the following Content Security Policy directive: "default-src * gap: data: blob: 'unsafe-inline' 'unsafe-eval' ws: wss:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
", source: http://localhost:12768/ (0)
[INFO:CONSOLE(544)] "[FilesCollection] [findOne("BEpoYw4ZPE92XFPLN", undefined)]", source: http://localhost:12768/__cordova/packages/ostrio_files.js?hash=bb1139387c40daa1423a3c1f137f30cf3d480f81 (544)
[INFO:CONSOLE(0)] "Failed to load http://192.168.1.17:3000/_timesync: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:12768' is therefore not allowed access.", source: http://localhost:12768/ (0)
[INFO:CONSOLE(1082)] "Error syncing to server time: ", source: http://localhost:12768/__cordova/packages/meteor.js?hash=f02c61cd69d98a091d98d62dff022bd106b404cf (1082)
[INFO:CONSOLE(1080)] "Max number of time sync attempts reached. Giving up.", source: http://localhost:12768/__cordova/packages/meteor.js?hash=f02c61cd69d98a091d98d62dff022bd106b404cf (1080)
```

**Comment by dr-dimitru** [comment]
You've got the idea of this package wrong.

All features is related only to files __upload__. Download (e.g. play, stream) is always done via HTTP (TCP/IP). And yes, it wouldn't ever work in Cordova as you will need to use native WebRTC package, and this branch is far away from implementing this.

**Comment by jankapunkt** [comment]
I will close this for now as it is not related to any further features of this package so far. Feel free to reopen if an issue comes up that is related to this and specific parts of this package.
