### ISSUE TITLE
writing over an existing file

### ISSUE THREAD

**Issue by Leekao** [VeliovGroup/Meteor-Files#667]
On my server I create a pdf for the user with React-pdf, after it's created I add it to the fs using collection.write and I use the unique document id as the filename, thing is what I want is for every new file to overwrite the previous one (like an upsert flag), is there any idiomatic way of achieving what I need?

**Comment by dr-dimitru** [comment]
@Leekao I'm sorry for the late reply, this can not be achieved without removing file by `_id` and adding a new one with the very same `_id`. This is limited for security reasons.
Feel free to reopen it in case if the issue is still persists on your end.
