### ISSUE TITLE
Retrieving files from Filecollection 

### ISSUE THREAD

**Issue by AnshulBasia** [VeliovGroup/Meteor-Files#674]
I can store files in my database but how can I show them on client's frontend using img tag ?
PS: I am using meteor react for webapp.

**Comment by dr-dimitru** [comment]
Hey @AnshulBasia ,

It depends from what you're using on front-end react, blaze, vue.

Here is example for Blaze from our wiki — https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper:

```js

import { Meteor }          from 'meteor/meteor';
import { Template }        from 'meteor/templating';
import { FilesCollection } from 'meteor/ostrio:files';

const Files = new FilesCollection({collectionName: 'Files'});
if (Meteor.isClient) {
  Meteor.subscribe('files.all');

  Template.example.helpers({
    fileRef: Files.collection.findOne({})
  });
} else {
  Meteor.publish('files.all', function () {
    return Files.collection.find({});
  });
}
```

```handlebars
<template name="example">
  <img src="{{fileURL fileRef}}">
</template>
```

**Comment by AnshulBasia** [comment]
Hey @dr-dimitru, Thanks a lot.  I am using react and have not been able to display the image. I got my UI to upload an image in the database with name, storagepath, isimage, etc. But how can I actually display on the webpage using img tag ?

**Comment by dr-dimitru** [comment]
@AnshulBasia in React use [`.link()` or `FilesCollection#link()` methods](https://github.com/VeliovGroup/Meteor-Files/wiki/link), let me know if you need more info on that.

**Comment by dr-dimitru** [comment]
@AnshulBasia Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by banana618859** [comment]
> @AnshulBasia in React use [`.link()` or `FilesCollection#link()` methods](https://github.com/VeliovGroup/Meteor-Files/wiki/link), let me know if you need more info on that.
**meteor vue element-ui**
```
Images.collection.find({}).forEach(function (fileRef) {
          console.log('--downloadUrl:',Images.link(fileRef))
          urlArr.push(Images.link(fileRef))
        });
```
Thank you very much!

**Comment by dr-dimitru** [comment]
Hello @banana618859 ,

sorry didn't get your message, is it a question? Maybe better to start new issue thread?
