### ISSUE TITLE
[crash] during upload on closing connexion 

### ISSUE THREAD

**Issue by jamalcoder** [VeliovGroup/Meteor-Files#675]
using meteor 1.8.x and react 16.8.x

im uploading an audio file if the file is bigger than 8min+ the upload crash i resolved that by setting streams to 1
all works fine but if i close connection react crash on production(on local i have to slow down the connection to do that) on computer i close the connexion multiple time to get the crash but on mobile just disabling wifi crash the app during upload.

**Comment by dr-dimitru** [comment]
Hello @jamalcoder ,

Please update this thread following [our issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE):

  - Version of `Meteor-Files` you're experiencing this issue
  - Where this issue appears? OS (Mac/Win/Linux)? Browser/Device name and its version?
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
  - What transport you're using for upload HTTP or DDP?

**Comment by jamalcoder** [comment]
Meteor-Files : v1.10.2
issue tested on windows 10 and android 8 (both on google chrome)
transport : http(streams: 1, chunkSize: 'dynamique')
client log after setting debug to true:

.....cdn/storage/vmessages/__upload 499 (Client Disconnected)
[FilesCollection] [UploadInstance] [end] useraudio.mp3
3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139 Timer 'insert useraudio.mp3' does not exist
end @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
e @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
t.binData.ddp.config.transport.n.call.e @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
(anonymous) @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:99
m.onreadystatechange @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:99
XMLHttpRequest.send (async)
c.call @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:99
sendChunk @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
e @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
fileData.size.config.onBeforeUpload.f.isFunction.collection.onBeforeUpload.f.isFunction.worker.worker.onmessage.e @ 3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:139
3346aba883c544184b8c91ef2a16f4dbde7bb75d.js?meteor_js_resource=true:9 Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20failed%20%5B499%5D%20%3C!DOCTYPE%20html%3E%20%09%3Chtml%3E%20%09%20%20%3Chead%3E%20%09%09%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1%22%3E%20%09%09%3Cmeta%20charset%3D%22utf-8%22%3E%20%09%09%3Ctitle%3EApplication%20Error%3C%2Ftitle%3E%20%09%09%3Cstyle%20media%3D%22screen%22%3E%20%09%09%20%20html%2Cbody%2Ciframe%20%7B%20%09%09%09margin%3A%200%3B%20%09%09%09padding%3A%200%3B%20%09%09%20%20%7D%20%09%09%20%20html%2Cbody%20%7B%20%09%09%09height%3A%20100%25%3B%20%09%09%09overflow%3A%20hidden%3B%20%09%09%20%20%7D%20%09%09%20%20iframe%20%7B%20%09%09%09width%3A%20100%25%3B%20%09%09%09height%3A%20100%25%3B%20%09%09%09border%3A%200%3B%20%09%09%20%20%7D%20%09%09%3C%2Fstyle%3E%20%09%20%20%3C%2Fhead%3E%20%09%20%20%3Cbody%3E%20%09%09%3Ciframe%20src%3D%22%2F%2Fwww.herokucdn.com%2Ferror-pages%2Fapplication-error.html%22%3E%3C%2Fiframe%3E%20%09%20%20%3C%2Fbody%3E%20%09%3C...&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

i think after this log the file  ends before the upload finish

**Comment by jamalcoder** [comment]
hi @dr-dimitru 

sorry i forgot server side logs...and i think no error here at server side

2019-02-19T20:44:59.545958+00:00 app[web.1]: [FilesCollection] [find({"meta.vr":true}, {"sort":{"$natural":-1},"limit":20,"fields":{"meta.vr":0}})]
2019-02-19T20:49:55.316401+00:00 app[web.1]: [FilesCollection] [find({"meta.vr":true}, {"sort":{"$natural":-1},"limit":20,"fields":{"meta.vr":0}})]
2019-02-19T20:53:07.625586+00:00 app[web.1]: [FilesCollection] [File Start HTTP] useraudio.mp3 - rTvTbAmfGcRBD8iZw
2019-02-19T20:53:07.625802+00:00 app[web.1]: [FilesCollection] [Upload] [HTTP Start Method] Got #-1/5 chunks, dst: useraudio.mp3
2019-02-19T20:53:20.851105+00:00 app[web.1]: [FilesCollection] [Upload] [HTTP] Got #1/5 chunks, dst: useraudio.mp3

**Comment by jamalcoder** [comment]
**solved**

```
this.uploadInstance.on('error', (error, fileObj) => {
            this.setState({uploadStarted: false, uploadProgress: 0});
            popUpMessage(error);
            console.log(error);
        });
```

i was calling a function reference(popUpMessage) from a parent component inside event upload and that's why react crashed
------------------------------------------------------------------------------
i have a question is there an exemple that shows a custom ddp connexion for upload instead of the default Meteor connexion (default DDP block the app)

**Comment by dr-dimitru** [comment]
Closing as [solved].
@jamalcoder Custom DDP connection can be created using [`DDP.connect`](https://docs.meteor.com/api/connections.html#DDP-connect)
