### ISSUE TITLE
Secure a file's download route, so that unauthenticated access is denied

### ISSUE THREAD

**Issue by jpsear** [VeliovGroup/Meteor-Files#677]
I would like to secure a file's "download" route (on the server) so an unauthenticated user cannot access it. I have tried using `Meteor.userId()` inside `interceptDownload` and it's not available, as it's not a Meteor method: 

```
Error: Meteor.userId can only be invoked in method calls or publications.
```

Any suggestions?

_Versions:_
```
ostrio:files@1.10.2
METEOR@1.8.0.2
"aws-sdk": "^2.413.0"
```

**Comment by jpsear** [comment]
Gah! Super simple, there is a `protected` config key for the collection constructor:

```
const Files = new FilesCollection({
  protected: true
})
```

**Comment by jpsear** [comment]
Just re-opening this, as I have a question. Is it possible to get the userId of the current request inside `interceptDownload`? I would like to do further checking on a user's permissions...

**Comment by jpsear** [comment]
Once again, found it. `downloadCallback` is the method I was looking for, as this exposes the userId...

```
Files.downloadCallback = function (fileObj) {
  console.log(this.userId)
  return true // false to deny access
}
```

**Comment by make-github-pseudonymous-again** [comment]
@jpsear I believe you can pass a function to `protected` instead of a `boolean`.
