### ISSUE TITLE
Emit S3 file upload progress to client

### ISSUE THREAD

**Issue by jpsear** [VeliovGroup/Meteor-Files#678]
I have set up an S3 integration and it's working well. However, I built a progress bar for uploads and am struggling to see how to tie together the progress of the initial upload to my app server with the upload status to S3.

I know that the AWS SDK can provide me with the upload status as a stream by using this:

```js
.on('httpUploadProgress', (progress) => {
  console.log(progress)
})
```

However, this happens on the server in a post-upload task (`onAfterUpload`), so by this point, Meter-Files' upload percentage is complete.
  
### Potential solutions

* Write the AWS progress to a collection and subscribe to it. This seems like such an unnecessary overhead.

* Pause my progress bar at 75% and then just wait until the file is uploaded to S3 (I will know when the `pipePath` is populated) and then flick the progress to 100%. This is fine, but very clunky.

Any thoughts?

**Comment by jankapunkt** [comment]
related: https://github.com/VeliovGroup/Meteor-Files/issues/685

**Comment by dr-dimitru** [comment]
Closing in favor of #685, although #685 was created later, I've left explanation why this isn't possible in current implementation in #685, please kindly move all further discussion to #685
