### ISSUE TITLE
[Solved] Move GridFS files/chunks from one DB to another via DDP connection 

### ISSUE THREAD

**Issue by jankapunkt** [VeliovGroup/Meteor-Files#686]
Note: This is rather a question than an issue / bug. However, the answer to this questions could potentially be added to the wiki / documentation. 

### Background:

I have two Meteor apps using this package to upload files to their **own Mongo (separate) instances** using GridFS as storage.

I am currently syncing a specific set of documents from one app to the other via `DDP.connect` and it works fine.

### Problem

However, I can't figure out how to "move" or "copy" the chunks in the GridFS from one app to the other, too.

Anyone ever found out how to do that?

I am neither do sharding nor replication on the DBs so it would be failsafe for my apps to preserve the ids and really just "move" / "copy" the files data from DB1 to DB2.

**Comment by jankapunkt** [comment]
Okay was easier than I thought, thanks to [some comment in this SO question](https://stackoverflow.com/questions/55991727/meteor-mongo-gridfs-copy-files-and-chunks-to-another-db-without-dump):

You can just create two collections for 'fs.files' and 'fs.chunks' and copy these doucments to the remote DB as every other document.

@dr-dimitru should I create a Wiki Entry for copying GridFS files between different DBs, which happens sometimes between service-oriented apps / microservices.

**Comment by dr-dimitru** [comment]
Hello @jankapunkt ,

Thank you a lot for investigating this one on your own. Yes, I'd be happy to accept this type of tutorial.
Please make sure you add a link to your doc to ToC and other related parts of the Wikis.

**Comment by jankapunkt** [comment]
Added via #687

**Comment by jankapunkt** [comment]
merged
