### ISSUE TITLE
v1.4.2 uploading large files doesn't work anymore ?

### ISSUE THREAD

**Issue by marcchapeau** [VeliovGroup/Meteor-Files#69]
Hi,

Firstly thanks for this new version. We can now play videos on all browsers. Good work and thank you for  your reactivity !

Unfortunately with this new version when i try to upload a small file, it works perfectly but if i try with a larger file (in my case more than 300Mo but I will try other size to test) the upload process freeze, no chunk is sent to the server.
There was no problem with the previous version.

I can't test it with your live demo because we can't upload a file larger than 128Mo.

**Comment by dr-dimitru** [comment]
Hi @marcchapeau 
It is caused by `readAsDataURL()` method. Before we used `readAsArrayBuffer()`, which was causing triple work on both browser and server.

Current plan is to dedicate this job to Web Worker. If you have any suggestions, we will be glad for your help.

**Comment by dr-dimitru** [comment]
Hi @marcchapeau thank you for contribution.
This issue is solved in [v1.4.3](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.4.3)
Please check on your end.
