### ISSUE TITLE
Get collection data after insert using '.load' method?

### ISSUE THREAD

**Issue by butaminas** [VeliovGroup/Meteor-Files#690]
### I'm having an issue:
I have 2 collections, one is for storing the actual data about an item another is for storing images of that item.

I get all of the data including images from API, so at first, I upload the image using:
`let imageCollection = Images.load(data.image)`

Then I insert the rest of the data into another collection including the recently inserted image:
`Items.Insert({ info: data.info, image: imageCollection })`

End result - first collection has data of uploaded image and second collection has data of item including the uploaded image (either it's image link, id or object).

The problem is that I can't get any data after uploading an image. I don't get the inserted document, instead, I get FilesCollection with no data:

```javascript
FilesCollection {
   _events: 
    { _handleUpload: 
       EE {
         fn: [Function: _handleUpload],
         context: [Circular],
         once: false },
      _finishUpload: 
       EE {
         fn: [Function: _finishUpload],
         context: [Circular],
         once: false } },
   _eventsCount: 2,
   debug: false,
   schema: 
    { _id: { type: [Function: String] },
      size: { type: [Function: Number] },
      name: { type: [Function: String] },
      type: { type: [Function: String] },
      path: { type: [Function: String] },
      isVideo: { type: [Function: Boolean] },
      isAudio: { type: [Function: Boolean] },
      isImage: { type: [Function: Boolean] },
      isText: { type: [Function: Boolean] },
      isJSON: { type: [Function: Boolean] },
      isPDF: { type: [Function: Boolean] },
      extension: { type: [Function: String], optional: true },
      ext: { type: [Function: String], optional: true },
      extensionWithDot: { type: [Function: String], optional: true },
      mime: { type: [Function: String], optional: true },
      'mime-type': { type: [Function: String], optional: true },
      _storagePath: { type: [Function: String] },
      _downloadRoute: { type: [Function: String] },
      _collectionName: { type: [Function: String] },
      public: { type: [Function: Boolean], optional: true },
      meta: { type: [Function: Object], blackbox: true, optional: true },
      userId: { type: [Function: String], optional: true },
      updatedAt: { type: [Function: Date], optional: true },
      versions: { type: [Function: Object], blackbox: true } },
   public: false,
   strict: true,
   chunkSize: 524288,
   protected: false,
   collection: 
    Collection {
      _makeNewID: [Function],
      _transform: null,
      _connection: 
...
```

Therefore, adding `imageCollection` or `imageCollection.id` or `imageCollection._id` gets me nowhere.

How can I fix that?
And is there anyway I could skip creating the images collection and just insert everything straight into Items collection?

Thanks in advance.

**Comment by dr-dimitru** [comment]
Hello @butaminas,

Please read [`.load()` method docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Load) carefully, `.load()` method doesn't return inserted file-data, you got to use `callback` function as 3rd argument.

Feel free to reopen it in case if the issue is still persists on your end.
