### ISSUE TITLE
Embedding encrypted files

### ISSUE THREAD

**Issue by sylido** [VeliovGroup/Meteor-Files#694]
I have files that are stored encrypted, when I generate a URL for them the interceptDownload hook decrypts them and sends them over to the client, the file gets downloaded and everything works fine. Now if I try to use the URL in an `embed` html object or similar, I get an error saying that the file `PDF` in this case cannot be loaded. Is there a way to stream + decrypt files without the user having to specifically download them ?

If there's any other alternative way of doing this I'm open to suggestions as well.

**Comment by dr-dimitru** [comment]
Hello @sylido ,

I'd like to see server logs for both cases to understand difference. Please, post server logs with enabled `debug` option for "download" and for "embedded" file

**Comment by dr-dimitru** [comment]
@sylido friendly ping

**Comment by sylido** [comment]
hey @dr-dimitru I think I had the wrong headers going - I was trying with the download one which didn’t work. Next I tried with “inline” which resulted in the browser’s tab freezing. Then I just removed that header part completely and the stream + download now work as expected, thanks for the nudge in the right direction.
