### ISSUE TITLE
Custom download link

### ISSUE THREAD

**Issue by mariusrak** [VeliovGroup/Meteor-Files#700]
Would it be possible to expose an API for defining custom URLs? I guess it has to do with [this line](https://github.com/VeliovGroup/Meteor-Files/blob/50831583d56fdab7628c54391a4a68a9242ae74c/server.js#L612). The API could be configurable function which would take `httpReq._parsedUrl.path` or `httpReq._parsedUrl` and collection name as arguments and return object containing file id and file version which should be sent for download.

**Comment by dr-dimitru** [comment]
Hey @mariusrak ,

What exactly do you want to accomplish? `httpReq` is [exposed in `interceptDownload`](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor), but has no relation to "*defining custom URLs*"

**Comment by mariusrak** [comment]
I'd like to provide more user friendly urls. E.g. currently I don't like that ID is twice in the URL.

**Comment by hluz** [comment]
You should be able to have any string in the name. By default the name id fileId + .suffix (i.e., the final part of the url). I think there is a setting in config to provide a function that returns a string as the file name. I use the filename as the name instead of the fileId.

**Comment by mariusrak** [comment]
@hluz , thanks, while that fulfill part of my use case, I'd still prefer more flexibility.

**Comment by dr-dimitru** [comment]
@mariusrak register another [`WebApp.connectHandlers.use()`](https://docs.meteor.com/packages/webapp.html) and pipe request to Meteor-Files URL

**Comment by mariusrak** [comment]
It seem like little bit of unnecessary overhead which would not be optimal, performance-wise. But if there's not other option, it might be okay. But how can I pipe the request? I didn't find anything in docs about it. Thanks.

**Comment by dr-dimitru** [comment]
@mariusrak your incoming request is Stream, so use [`.pipe()`](https://www.npmjs.com/package/request#streaming)

**Comment by dr-dimitru** [comment]
@mariusrak friendly ping, is this solved?

**Comment by mariusrak** [comment]
I didn't get to it yet. But as I'm reading the docs, it seems like there would be whole new request through network API which seems like too much overhead. Am I correct? If yes, then I'd rather search for another solution.

**Comment by dr-dimitru** [comment]
@mariusrak if you're talking about "piping" request — yes. Also you can do HTTP redirect, then client will decide how to manage connection

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
