### ISSUE TITLE
onAfterUpload - fails other uploads if it takes too long

### ISSUE THREAD

**Issue by sylido** [VeliovGroup/Meteor-Files#701]
When uploading a series of large files, we are doing client side encryption, we then decrypt the file in the onAfterUpload hook. Afterwards we encrypt the file, delete the existing file on disk and write it to disk (synchronously), then we update a meta flag named "encrypted" to true to signalize that the file is uploaded/encrypted correctly at that point.

On the client side though we can have other files that follow the first file. If all the files are small this process works flawlessly. If it's files that are around 15-20mb (our max) the process seems to break for the files that are to be uploaded after the larger file, no matter their size. It seems like the onAfterUpload hook is just taking too long to do the things we are doing. Is there a way to unblock this process so that it can process the next file ? 

I guess the first solution to this problem that I can think of, is to just move the functionality in onAfterUpload to a separate meteor method that gets called from the client side after we get the OK on the upload, so that the other uploads don't get stopped.

**Comment by dr-dimitru** [comment]
> I guess the first solution to this problem that I can think of, is to just move the functionality in onAfterUpload to a separate meteor method that gets called from the client side after we get the OK on the upload, so that the other uploads don't get stopped.

in case of `onAfterUpload` we're talking only about *Server*, so forget about Meteor.Methods.
To make `onAfterUpload` 100% async wrap it to separate fiber using `Fibers` (*complex, but efficient*) library or parallel it with simply using `process.nextTick` callback (*simple, but less efficient*).

Let me know if that was helpful

**Comment by hluz** [comment]
or use `async onAfterUpload` wrap it a function returning a promise and use await. Something like this should do it:


```javascript
async onAfterUpload(file) {
  const upFile = (file) => {
    return new Promise( (resolve, reject) => {
      
      // your code

      // when done
      resolve();
    })
  }
  await upFile(file);
}
```

**Comment by dr-dimitru** [comment]
@sylido any news? Is this one fixed?

**Comment by sylido** [comment]
@dr-dimitru it turns out that the problem was coming from having too many files in the collection, which slowed down the client side reactivity significantly even though a low number of them were getting published. It will be some time until I get to refactoring this particular part of the code to use the asynchronous method - feel free to close it for now since it's a more of an edge case rather than a common use, thanks for the suggestion on how to fix it !
