### ISSUE TITLE
Gridfs Performance lose on built-in Mongo vs External Mongo

### ISSUE THREAD

**Issue by kakadais** [VeliovGroup/Meteor-Files#703]
I've benchmarked a lot using Meteor-Files-Demo/demo-simplest-upload,
then I found built-in MongoDB is way faster then external MongoDB for file-download.

Using the built-in MongoDB is almost three times faster than external one,
even I set external one properly.
And when using external the project was built so that can be reduce wasting of performance,
but the result was same. 

I know this could be caused by MongoDB environtment setting or embeding MongoDB to Meteor.js,
but I used quite simple demo and small image(4kb) so the DB structure is completely same,
so I think if we could reduce this performance losing, that would be neccessary.

On my test,  I used NPM 'download' pacakge and sent bunch of download request at once continusely. (like (1000 req/sec) * 30 times ...)
I will attach the test code and mass result data if it's neccessary.

- OSX / Meteor(1.7.0.3) /  Meteor-Files(1.11.0) / MongoDB(4.0.10/SingleREPL)

Where could be difference come from?

Thanks.

**Comment by jankapunkt** [comment]
Did you benchmark locally in the dev environment or in a staging environment using production builds? Many packages behave different in dev than when being build using production flags.

**Comment by kakadais** [comment]
@jankapunkt I've tested locally and tested Development mode for built-in MongoDB / tested Deploy mode for external MongoDB. As you said I'll test in Development mode for external MongoDB again and let you know.

**Comment by kakadais** [comment]
@jankapunkt Finally I've got new test result. The result shows Development project is faster than Deployment project which has been Built almost twice on over 3000 req/sec traffic.

![image](https://user-images.githubusercontent.com/5265343/63201823-37c0a200-c087-11e9-8695-038a1e3c0c9c.png)

I agree with your opinition that the Dev mode could be different
but I tested on the same environment, locally / MongoDB(external/single REPL)
so I doubt there could be some waste some resource
or my fault ^^

Could you analyse with me though? 

Thanks in advance.

**Comment by kakadais** [comment]
Oh crap. And this could be another thread but if I can ask you though,
Why the HTTP-SERVER which is just a simplest webserver on NPM package is the best on this simple stress test??!?!
I'm focuss on the Meteor and Files but Nginx and Apache AND HTTP-SERVER result is quite interested for me.
I'll check the combination of those front-static-webserver as well.

**Comment by jankapunkt** [comment]
> Oh crap. And this could be another thread but if I can ask you though,
Why the HTTP-SERVER which is just a simplest webserver on NPM package is the best on this simple stress test??!?!
I'm focuss on the Meteor and Files but Nginx and Apache AND HTTP-SERVER result is quite interested for me.
I'll check the combination of those front-static-webserver as well.

Hmmm, I am not sure where this intends to go. The pros and cons of the different protocols have [already been documented](https://github.com/VeliovGroup/Meteor-Files/wiki/About-Upload-Transports).


> I know this could be caused by MongoDB environtment setting or embeding MongoDB to Meteor.js,

It is hard to determine, if the whole performance issue is related to this package. There are many factors between the upload, this package and your mongod writing some binary to the db.

> I used quite simple demo and small image(4kb) so the DB structure is completely same,
so I think if we could reduce this performance losing, that would be neccessary.

As long as we don't find hard evidence, that this package is the cause of performance issues we should not take action on the code.

However I think @dr-dimitru agrees, that any performance report that indicates a certain part of this code as a cause is very welcomed (as well as an accompanying PR :slightly_smiling_face:  )

**Comment by dr-dimitru** [comment]
> As long as we don't find hard evidence, that this package is the cause of performance issues we should not take action on the code.

Totally agree. To remote mongo data has to travel distances and servers aren't that powerful as your development stage.

> However I think @dr-dimitru agrees, that any performance report that indicates a certain part of this code as a cause is very welcomed (as well as an accompanying PR 🙂 )

👨‍💻 PRs are always welcome 🤘



Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
