### ISSUE TITLE
Aborted upload says it's active

### ISSUE THREAD

**Issue by mariusrak** [VeliovGroup/Meteor-Files#706]
When on `abort` event is emited, the reactive variable `state` says that the upload instance is still `active`. After a while (not sure when) the value changes to `aborted`. I guess in the callback the value should be already correct.

Apparently, [this line](https://github.com/VeliovGroup/Meteor-Files/blob/master/upload.js#L77) should be before the events are emited.

**Comment by jankapunkt** [comment]
If it's only a minor change, would you mind to open a PR for it?

**Comment by dr-dimitru** [comment]
Implemented in https://github.com/VeliovGroup/Meteor-Files/commit/036081828b568e4e007d0be22b64261d3d8f5524

Feel free to reopen it in case if the issue is still persists on your end.
