### ISSUE TITLE
is it possible to update the metadata?

### ISSUE THREAD

**Issue by FinnFrotscher** [VeliovGroup/Meteor-Files#71]
I am trying to update the metadata of an existing Images collection like this:
` Images.collection.update(this._id, {$set: {'meta.big': !this.meta.big}});`
'big' is a boolean. 
but i get `update failed: Access denied`

my fault or impossible?

**Comment by dr-dimitru** [comment]
Hi @FinnFrotscher ,
To make this package more secure place, we block all actions from client by default.
Please use server side [methods](http://docs.meteor.com/#/full/meteor_methods) to update collection on server.

Example:
```javascript
// Server:
Meteor.methods({
  'collections.images.update': function (_id, set) {
     check(_id, String);
     check(set, Object);
     // Run more check(s) here to make sure this call is permitted
     this.unblock(); // <-- Use to make this method asynchronous
     Images.collection.update(_id, {$set: set});
     return true;
  }
})

// Client
Meteor.call('collections.images.update', this._id, {'meta.big': !this.meta.big})
```

**Comment by dr-dimitru** [comment]
Also you can rewrite `deny` rule on this collection (*at your own risk*):

```javascript
Images.collection.deny({
  insert: function() {
    return true;
  },
  update: function() {
    return false; // <-- Allow update from client
  },
  remove: function() {
    return true;
  }
});
```

**Comment by FinnFrotscher** [comment]
Thanks! The Method works 👍  and thx for the package!

**Comment by dr-dimitru** [comment]
@FinnFrotscher 
Glad you found it helpful. 
Do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). 
Also you may like to [Tweet](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files&text=File%20upload%20and%20delivery%20in%20Meteorjs%20-%20now%20it's%20easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
