### ISSUE TITLE
function for removing variants?

### ISSUE THREAD

**Issue by meecect** [VeliovGroup/Meteor-Files#716]
It looks like .remove() will remove the document from the collection and the file from the filesystem, but is there an option to only remove only a specified version?  Or would I need to implement that myself?

**Comment by dr-dimitru** [comment]
Hello @meecect ,

Please take a look on [`.unlink()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/unlink). It will remove only a file. To remove a sub-version's meta-data you need to write an `update` query manually

**Comment by meecect** [comment]
ok, I used unlink() and then manually updated the versions property in an update call.  Works fine, thanks.

**Comment by dr-dimitru** [comment]
@meecect I'm glad it's solved.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - Donate via [Patreon](https://patreon.com/dr_dimitru) or [PayPal](https://paypal.me/veliovgroup)
