### ISSUE TITLE
How to use AWS with React example

### ISSUE THREAD

**Issue by radykal** [VeliovGroup/Meteor-Files#719]
Hi,

I am trying to realize the react example with AWS integration. In order to subscribe to the collection in the component, I need to export the collection. In your React example, you named it UserFiles. But I do not see the import of UserFiles in the Fileupload.js

Now I try to implement the AWS integration and here you are saying the code to init the FilesCollection needs to be put on the server. That means I can not import the instance of FilesCollection anymore in the component.

I hope you understand what I mean?

**Comment by tschneid** [comment]
I use a wrapper `MyCollection.js` that roughly looks like the following.

```js
// Add your config here.
export const commonCollectionConfig = { collectionName: 'MyCollection' };

let MyCollection;

if (Meteor.isServer) {
  MyCollection = require('./MyCollection.server');
}

if (Meteor.isClient) {
  MyCollection = new FilesCollection(commonCollectionConfig);
}

export default MyCollection;
```

In `MyCollection.server.js` you create the server-side collection (using `commonCollectionConfig` and the AWS extension). Then you can import the collection from `MyCollection.js` both on the client (which imports the client-side collection) and the server (which imports the server-side collection).

Hope this helps!

**Comment by radykal** [comment]
I already found another solution.

I put my FilesCollection into an own js file with the configs t

**Comment by radykal** [comment]
I did now a similar approach. I put my FilesCollection in an own file and export it.

Then I imported into my server JS for all the S3 stuff. I noticed you can apply the config params directly to the instance of FilesCollection.

**FilesCollection.js**:
```javascript
export default UserFiles = new FilesCollection({
	collectionName: 'user_files',
	storagePath: () => {
        return `${process.env.PWD}/uploads`;
    },
    downloadRoute: '/files/',
	permissions: 0o774,
	parentDirPermissions: 0o774,
	debug: false,
	public: true
});
```

**server/s3.js**:
```javascript
const s3 = new S3({
	secretAccessKey: s3Conf.secret,
	accessKeyId: s3Conf.key,
	region: s3Conf.region,
	sslEnabled: true, // optional
	httpOptions: {
	  timeout: 6000,
	  agent: false
	}
});

UserFiles.on('afterUpload', function (fileRef) {})
UserFiles.interceptDownld = () => {};
```
