### ISSUE TITLE
Always force download

### ISSUE THREAD

**Issue by gjdanskij** [VeliovGroup/Meteor-Files#721]
Hello. I have discovered this issue now too. In my applicaton the collection is used as storage, so user can upload any file really. Is there way to always force a download, ? something similar to this:

"So if I would click the link foo.bar/cdn/storage/badFild.html it would redirect you to foo.bar/cdn/storage/badFild.html?download=true, right?

If that always prevents an execution it should be sufficient."

This doesn't happen actually, do i need to force it trough router?

_Originally posted by @gjdanskij in https://github.com/VeliovGroup/Meteor-Files/issues/289#issuecomment-557804348_

I tried to force with FlowRouter by doing like this:

`FlowRouter.route('/cdn/storage/FilesData/:id/original/:fname',{
   action: function(params){
     FlowRouter.redirect('/cdn/storage/FilesData/' + params.id + '/original/' + params.fname + '?download=true') ;
  }`

No redirect happens for some reason, can you help how to do this
});

**Comment by dr-dimitru** [comment]
Hello @gjdanskij ,

I'd recommend to set `Content-Disposition: attachment` header using [`responseHeaders`](https://github.com/VeliovGroup/Meteor-Files/wiki/Custom-Response-Headers).

Or even easier solution would be to use [`interceptDownload`](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md) hook and set `http.params.query.download` to `true`, like:

```js
new FilesCollection({
  interceptDownload(http) {
    http.params.query.download = true;
    return false; // <-- returning false is important here
  }
})
```

**Comment by gjdanskij** [comment]
I tried your second solution, and what it does it always forces preview not download. So i removed that immediatly, i will try `responseHeaders`

**Comment by dr-dimitru** [comment]
>  it always forces preview not download

What exactly do you mean by "preview"?
It suppose to force the very same behavior as you would use `?download=true` — the rest is on browser. Different browsers act differently upon `Content-Disposition: attachment` header presence. The only 100% way to preserve "download" action is to add `download="file.name"` attribute to anchor `<a href="#" download="file.name">download file</a>` element.

I'm afraid using `responseHeaders` you will get the very same results.

Marked as [help wanted], feel free to add link and ask for more help at forums.meteor.com

**Comment by dr-dimitru** [comment]
@gjdanskij 

1. Any news on your end?
2. What exactly do you mean by "preview"?
3. Does user clicks on the link to download a file? If so, you should try to use `download="filename.pdf" target="_blank" type="application/octet-stream"` anchor element attributes. __Note:__ It works only on the same origin host.

Quick googling shows that using `application/octet-stream` as `Content-Type` header *may* force browser to download file instead of "preview".

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
//cc @gjdanskij
