### ISSUE TITLE
AWS S3 Integration (module import Error)

### ISSUE THREAD

**Issue by vasilisach** [VeliovGroup/Meteor-Files#723]
Got an error 'Error: Cannot find module 'emitter',' after npm install stream. Following this instruction https://github.com/VeliovGroup/Meteor-Files/wiki/AWS-S3-Integration. I tried to npm install emitter  and npm install component/emitter to eliminate the error  but it's not work

**Comment by dr-dimitru** [comment]
Please post error logs and reopen this issue following our [issue template](https://github.com/VeliovGroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE).
