### ISSUE TITLE
There is no route for the path

### ISSUE THREAD

**Issue by fmorgens** [VeliovGroup/Meteor-Files#725]
When I try to access the files I uploaded I get an error message from flow router: ```There is no route for the path: /cdn/storage/GePtfkgEv3jj5JAHH.pdf```. When I set ```public: true``` in the constructor everything works fine. Since I want only people who are logged in to be able to access the files I can't use public.

**Comment by fmorgens** [comment]
I don't know what happen but it somehow started working.
Before the ```.link()``` function would output ```localhost:3000/cdn/storage/GePtfkgEv3jj5JAHH.pdf```.
Now it outputs ```http://localhost:3000/cdn/storage/files/GePtfkgEv3jj5JAHH/original/GePtfkgEv3jj5JAHH.pdf``` which is working,

**Comment by dr-dimitru** [comment]
@fmorgens make sure `ROOT_URL` env.var is properly set

I'm glad it's solved

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
