### ISSUE TITLE
Issue in uploading files

### ISSUE THREAD

**Issue by eramitpatel** [VeliovGroup/Meteor-Files#726]
Versions are as follows 
meteor 1.8.3
ostrio:files@1.13.0

If i use " transport: 'http' " network tab response return "JavaScript is required to use this app" and if use " transport: 'ddp' " no network tab response but console error "Error invoking Method '_FilesCollectionAbort_Images'", anyone please help 

--------------------------server code----------------------
import { Meteor }   from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  storagePath : '/public',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) { 
    console.log("fileRef before",  file)
    return true;
  },
  onAfterUpload(fileRef) {
   }
}); 
export default Images;
------------------------------------server -ends------------------------------

--------------client ----------------------------------
 var logo = event.target.files[0]; 
   
    const upload = Images.insert({
      file: logo,
      streams: 'dynamic',
      chunkSize: 'dynamic',
      transport: 'http',    
    }, false);

  upload.on('start', function() {
    console.log('Upload started');
  });
  

  upload.on('end', function (error, fileObj) {
    if (error) {
      console.log('Error during upload: ' + error);
    } else {
      console.log('File "' + fileObj.name + '" successfully uploaded');
    }
    
  });

  upload.start();

**Comment by eramitpatel** [comment]
Images not getting upload at all, removing the line  '''storagePath : '/public',''' still same issue as stated above.

**Comment by dr-dimitru** [comment]
Hello @eramitpatel ,

1. You need to initiate `const Images = new FilesCollection({/*...*/})` on the *Client* as well
2. What browser you're on? Version?
3. What OS you're on? Version?
4. You have debug enabled, any debug logs to share?
5. Message about `JavaScript is required to use this app` do you have JS enabled in a browser?

**Comment by eramitpatel** [comment]
solved with your given instructions

**Comment by dr-dimitru** [comment]
@eramitpatel I'm glad it's solved so quickly

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
