### ISSUE TITLE
Image not served on backup server with same condition and data

### ISSUE THREAD

**Issue by kakadais** [VeliovGroup/Meteor-Files#728]
I have backup server and even I copied all files & data to right position and setup all things same,
the backup server cannot serve images properly.

The thing that I believe I copied all files & configured backup server properly is,
- all the other mongodb data is fine on the backup server
- all of images is placed on right position
- if I added a new image on the backup server, that image served well,
And the new image file is just placed on the same directory with the other copied images.

So I think the copied image is not served but new image is ok..

One of the following 'ls -al' result is copied and not served file,
and another is new and served file,
and all the permission is same on the file system as well as MongoDB.

```
-rw-r--r-- 1 mStartup mStartup 306675  3월  3 01:34 E575WohWuq6banLQH.png
-rw-r--r-- 1 mStartup mStartup 438293  3월  2 06:15 hphNBvsAieMnoNJF2.png
```

And only new inserted image on the backup server is served with following screenshot,
https://www.dropbox.com/s/9avgolxyx477by1/Screenshot%202020-03-03%2001.58.45.png?dl=0
https://www.dropbox.com/s/thnujos6y87cu9n/Screenshot%202020-03-03%2001.57.48.png?dl=0

And the following is screenshot for access the link() address directly on the browser.
https://www.dropbox.com/s/q6y5429yhtxg3p2/Screenshot%202020-03-03%2002.01.14.png?dl=0

Two server is just same with all settings as I mentioned,
so I assume that I missed something important working on changing service server.

Please help.

Thanks.

  - Version of `Meteor-Files` you're experiencing this issue
ostrio:cookies@2.5.0
ostrio:files@1.13.0
  - Version of `Meteor` you're experiencing this issue
Meteor@1.9
  - Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
Linux / Chrome(Version 80.0.3987.122 (Official Build) (64-bit))
  - Is it *Client* or *Server* issue?
Server
  - Post *Client* and/or *Server* logs with enabled `debug` option, you can enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)
```
[FilesCollection] [find({"_id":{"$in":["T9upSL9oFEZbKFn3i","97ygDRWmbHEdfuFuw","NEXbAZwfmrDBwc7Tz","zfbs6rmdMLvrZ2574","FpyWj5sW9XunueLqM","E575WohWuq6banLQH","2ze3yYWs3JjC6NjSt","4TC5HjyHCQqZ8ZCbt","ZiNPjFzbp3onnNhKN"]}}, undefined)]
I20200303-01:45:12.259(9)? [FilesCollection] [download(/cdn/storage/db_files/ZLt5z42Qn9EB7Dz3S/original/ZLt5z42Qn9EB7Dz3S.png, original)]
I20200303-01:45:12.260(9)? [FilesCollection] [download(/cdn/storage/db_files/ZLt5z42Qn9EB7Dz3S/original/ZLt5z42Qn9EB7Dz3S.png)] [_404] File not found
I20200303-01:45:12.366(9)? [FilesCollection] [download(/cdn/storage/db_files/T9upSL9oFEZbKFn3i/original/T9upSL9oFEZbKFn3i.png, original)]
I20200303-01:45:12.366(9)? [FilesCollection] [download(/cdn/storage/db_files/T9upSL9oFEZbKFn3i/original/T9upSL9oFEZbKFn3i.png)] [_404] File not found
I20200303-01:45:12.371(9)? [FilesCollection] [download(/cdn/storage/db_files/4TC5HjyHCQqZ8ZCbt/original/4TC5HjyHCQqZ8ZCbt.png, original)]
I20200303-01:45:12.372(9)? [FilesCollection] [download(/cdn/storage/db_files/4TC5HjyHCQqZ8ZCbt/original/4TC5HjyHCQqZ8ZCbt.png)] [_404] File not found
I20200303-01:45:12.373(9)? [FilesCollection] [download(/cdn/storage/db_files/NEXbAZwfmrDBwc7Tz/original/NEXbAZwfmrDBwc7Tz.png, original)]
I20200303-01:45:12.374(9)? [FilesCollection] [download(/cdn/storage/db_files/NEXbAZwfmrDBwc7Tz/original/NEXbAZwfmrDBwc7Tz.png)] [_404] File not found
I20200303-01:45:12.383(9)? [FilesCollection] [download(/cdn/storage/db_files/ZiNPjFzbp3onnNhKN/original/ZiNPjFzbp3onnNhKN.png, original)]
I20200303-01:45:12.386(9)? [FilesCollection] [download(/cdn/storage/db_files/zfbs6rmdMLvrZ2574/original/zfbs6rmdMLvrZ2574.png, original)]
I20200303-01:45:12.387(9)? [FilesCollection] [download(/cdn/storage/db_files/ZiNPjFzbp3onnNhKN/original/ZiNPjFzbp3onnNhKN.png)] [_404] File not found
I20200303-01:45:12.388(9)? [FilesCollection] [download(/cdn/storage/db_files/zfbs6rmdMLvrZ2574/original/zfbs6rmdMLvrZ2574.png)] [_404] File not found
I20200303-01:45:12.389(9)? [FilesCollection] [download(/cdn/storage/db_files/FpyWj5sW9XunueLqM/original/FpyWj5sW9XunueLqM.png, original)]
I20200303-01:45:12.389(9)? [FilesCollection] [download(/cdn/storage/db_files/FpyWj5sW9XunueLqM/original/FpyWj5sW9XunueLqM.png)] [_404] File not found
I20200303-01:45:12.390(9)? [FilesCollection] [download(/cdn/storage/db_files/97ygDRWmbHEdfuFuw/original/97ygDRWmbHEdfuFuw.png, original)]
I20200303-01:45:12.391(9)? [FilesCollection] [download(/cdn/storage/db_files/97ygDRWmbHEdfuFuw/original/97ygDRWmbHEdfuFuw.png)] [_404] File not found
I20200303-01:45:12.392(9)? [FilesCollection] [download(/cdn/storage/db_files/2ze3yYWs3JjC6NjSt/original/2ze3yYWs3JjC6NjSt.png, original)]
I20200303-01:45:12.393(9)? [FilesCollection] [download(/cdn/storage/db_files/2ze3yYWs3JjC6NjSt/original/2ze3yYWs3JjC6NjSt.png)] [_404] File not found
```

**Comment by kakadais** [comment]
Additionally,

I set up storagePath like below so all server is watching same directory,
and I checked up a new image is placed on the same directory and DB.

  storagePath: process.env.HOME+'/data/publicationN',

Thanks in advance-

**Comment by dr-dimitru** [comment]
Hello @kakadais ,

Thank you for reaching out. I'd start with comparing two records from MongoDB new (which appears to be working) and old/migrated (which returns 404 error). Feel free to post two records here, so we can compare it together.

Thing to note: is your `ROOT_URL` env.var has changed upon migration?

**Comment by kakadais** [comment]
Thanks for fast reply-

Two MongoDB data is just same because I dumped it ans restore.
And the image files are just same with archiving.

https://www.dropbox.com/s/9jlkcr4ujm59pds/dump.tar.gz?dl=0
https://www.dropbox.com/s/uhzvduh1gf2uyrq/publicationN.tar.gz?dl=0

ROOT_URL environment is 
export ROOT_URL="http://publicationn.com"
And I changed my hosts file to use that dummy URL.

And I used NginX proxy in front of Meteor Server and the setting is,
location / { 
    proxy_pass http://localhost:7000;
    proxy_set_header      X-Real-IP       $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;  
  }
}

I believe these test environment is ok
because cause if I added new image then it works fine and new image saved same storage directory as well as I said.

Thanks for checking~

**Comment by kakadais** [comment]
Ok, 
first, I updated my first question to revoke screen shots link,

second, dump.tar.gz from my last comment link was primitive dump archive,
so there's no new image data inside,
so here's new dump file link containing new image case.
https://www.dropbox.com/s/q854y2v1s7zbkl6/dump.compare.tar.gz?dl=0

Thanks~

**Comment by dr-dimitru** [comment]
@kakadais 

> Two MongoDB data is just same because I dumped it and restore.

I got that, but want to compare migrated records with new

> because if I added new image then it works fine and new image saved same storage directory as well as I said.

Let's compare two records one from migrated DB and another after new image is uploaded

**Comment by kakadais** [comment]
Thanks and let me know if you need something-

**Comment by dr-dimitru** [comment]
@kakadais To provide you a further help I need to compare two records old (from migrated data) and new (from newly uploaded file)

**Comment by kakadais** [comment]
@dr-dimitru 
I found a problem-
the previous path has different name start at /Users cause it was made on Mac as a test data,
and new image has the path /home cause it is Ubuntu.

So I reallize the path is confirmed at the time of saving, and that was my mistake.

But I think if the saving path is confirmed at the first time with the absolute path,
there would be lot of considering for OS differencing and path problem.

Why don't you use a path with a given storagePath on configuration?

I think That would be much flexible- 

Thanks for your help-

**Comment by dr-dimitru** [comment]
Feel free to close it in case if the issue is solved on your end.

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).

**Comment by kakadais** [comment]
Thanks for help, 
and maybe I have to open another issue or PR for this absolute path-

**Comment by dr-dimitru** [comment]
@kakadais sorry for the late reply.

Regarding your question about storing path in MongoDB record — On server we need to know absolute path to the file to be able to locate it and read/write it. As an option you can use GridFS to store files in the MongoDB.

Let me know if you have further questions

**Comment by kakadais** [comment]
@dr-dimitru Thanks for answer-

On my test, I think relative path config was not working properly.
Should it be working? then I missed something.

So my question was applying relative path option from the project root directory something like that.

**Comment by dr-dimitru** [comment]
@kakadais yes, you can use relative path as well, since you haven't published here sample MongoDB records from old (from migrated data) and new (from newly uploaded file) dbs I can not tell you what was wrong. I assume absolute paths were used in both cases.

When setting relative paths make sure it starts with `./` or without leading slash.

Let me know if you have further questions

**Comment by kakadais** [comment]
@dr-dimitru Yeah, probably I missed something like your warning.
And actually I'm currently using GridFS version on my on-going service, and this path test was one of my server switch test so that compare the performance benchmark I have done before #703.
I just want to prove that GridFS file service is speedy enough to be used on normal service like Legacy file service on my thesis.

And I just send a PR #731 for new GridFS user.

**Comment by dr-dimitru** [comment]
#731 merged, docs and wikis updated, links added
