### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by palpinter** [VeliovGroup/Meteor-Files#73]
Hi,

when I tried upload with this:

```
      Images.insert
        file: file
        onUploaded: (error, fileObj) ->
          if error
            alert 'Error during upload: ' + error
          else
            alert 'File "' + fileObj.name + '" successfully uploaded'
          return
        streams: 'dynamic'
        chunkSize: 'dynamic'

```

```
TypeError: Cannot read property 'indexOf' of undefined
    at FilesCollection.getExt (files.coffee:550)
    at new UploadInstance (files.coffee:907)
    at FilesCollection.insert (files.coffee:851)
    at ViewModel.Template.SignUp.viewmodel.uploadPicture (sign-up.coffee:55)

```

Of course the 'file' is exist. Its name: 'img.png'

Thx
Pal

**Comment by dr-dimitru** [comment]
This means you file is *somehow* missing the name, see [L907](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L907)

Could you provide next info:
 0. Is this happens on particular file, or all files?
 1. If this happens on particular file, could you provide it for the tests?
 2. What version of Meteor,  Meteor-Files, Browser and OS you're on?
 3. Could you add `console.log(this)` into `onBeforeUpload` callback and post its output here?

**Comment by palpinter** [comment]
@dr-dimitru Thank you. The problem was on my side. I'm using materilaizecss and tehir file input control is a little bit weird.
