### ISSUE TITLE
link() with meteor useTracker()

### ISSUE THREAD

**Issue by msgfxeg** [VeliovGroup/Meteor-Files#734]
### I'm having an issue when using link() on a findOne() or even find() while inside useTracker()
  - here is my code that produces an error:
   const unitImageURL = useTracker(() => {
    let image = Images.findOne({
      _id: unit.images[0]
    }).link()
  - Version of `Meteor` you're experiencing this issue 1.10.1
  - Where this issue appears? OS (Linux)? Browser  chrome 
  - Is it *Client* or *Server* issue? I do not really know
  - Client logs :
Uncaught TypeError: Cannot read property 'link' of undefined
    at Object.reactiveFn (UnitListItem.jsx:21)
    at useTracker.js:49
    at tracked (useTracker.js:79)
    at useTracker.js:129
    at Computation._compute (tracker.js:308)
    at new Computation (tracker.js:206)
    at Object.Tracker.autorun (tracker.js:576)
    at useTracker.js:128
    at Object.Tracker.nonreactive (tracker.js:603)
    at useTracker.js:127

**Comment by dr-dimitru** [comment]
Hello @msgfxeg ,

For `.findOne()` method this is expected behaviour, you got to check if `.findOne()` has results. Feel free to open new (or more preferably PR) ticket to update [`FileCursor` documentation](https://github.com/VeliovGroup/Meteor-Files/wiki/FileCursor) and [`.find()` method documentation](https://github.com/VeliovGroup/Meteor-Files/wiki/findOne).

For `.find()` there is no `.link()` method as it return [`FilesCursor`](https://github.com/VeliovGroup/Meteor-Files/wiki/FilesCursor).

**Comment by msgfxeg** [comment]
Hello @dr-dimitru,
Thanks for you reply it helped me a lot.
As I am using react with meteor. the problem was that react component updates twice the first time before the mongo query succeeded! so I have to write it as follows:

useTracker(() => {
    if (
      Images.findOne({
        _id: unit.images[0]
      }) !== undefined
    ) {
      return Images.findOne({
        _id: unit.images[0]
      }).link();
    }
  }); 
P.S: a bit of redundant code but it does not heart :)

**Comment by dr-dimitru** [comment]
@msgfxeg I'm glad this was fixed quickly

Please support this project with:
 - Star this package on GitHub;
 - Take a look on our ongoing [▲ ostr.io](https://ostr.io) project;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
