### ISSUE TITLE
When downloading a file from Firefox, Meteor.server.sessions is empty

### ISSUE THREAD

**Issue by g-lapeyre** [VeliovGroup/Meteor-Files#738]
### I'm having an issue:
I'm facing an issue where this.userId is null on the protected function causing an `Access denied!` response from the server. This error only concern Firefox, everything is working well on the other browsers. On dev with one instance, and prod with a 3pods Kubernetes.
But unlike the other discussions I have been reading concerning the same issue, the cookie is well set.
![Screenshot 2020-04-19 at 18 45 31](https://user-images.githubusercontent.com/60349428/79693998-15ae9d80-826e-11ea-8f44-a040cee9476f.png) 

During my research I ended up in the `_getUserId(xmtok)` method where I have added some log to verify that the 'xmok' cookie is set, and to display the content of the `Meteor.server.sessions` :
``` 
console.log('token', xmtok);
console.log(Meteor.server.sessions);
if (Meteor.server.sessions instanceof Map && Meteor.server.sessions.has(xmtok) && 
  helpers.isObject(Meteor.server.sessions.get(xmtok))) {
   return Meteor.server.sessions.get(xmtok).userId;
```
Which output this:
```
token mFzCcBodtMNg2zmgn
Map {}
```

The `Meteor.server.sessions` never contains the session matching the token on Firefox, while on Chrome it is well populated and leads to no error.

Version of Meteor-Files: 1.11.2
Version of Meteor: METEOR@1.8.2

Thank you in advance.

**Comment by g-lapeyre** [comment]
Closed, apparently to have this working on Firefox you need to use` window.open(url);`

**Comment by dr-dimitru** [comment]
@g-lapeyre can you provide more insights into your solution?
In what part of the app you had this part of the code?
```js

window.location.href = url;

```
