### ISSUE TITLE
React Native upload image/video to meteor server

### ISSUE THREAD

**Issue by faavictoriano** [VeliovGroup/Meteor-Files#74]
Hello there, i try to upload image in from react-native to meteor using base64 encode for image and its working, but i would like to know if   you have idea how to upload from external like react-native to Meteor Server with file path. i know that in heruko they use ephemeral filesystem, so i can use my own server to upload video/audio? any codes in react-native to meteor? i use DDP Client

Thanks

**Comment by dr-dimitru** [comment]
I guess you can grab code of this lib, and copy/paste Client's part. As it's still JavaScript - it should work.
Deps (on client):
 - `underscore`
 - `reactive-var` (*can be removed*)
 - `tracker` (*can be removed*)
 - More info [here](https://github.com/VeliovGroup/Meteor-Files/blob/master/package.js)

Files:
 - `worker.js` - The main worker
 - `event-emitter.js` - NodeJS-like events on client
 - `files.coffee` - The main file, it's well-documented so you can easily identify if it's client or server part (see `@locus`)

Not easy task, but if you have enough experience it won't take a lot of time.

**Comment by dr-dimitru** [comment]
BTW why not use: https://github.com/hharnisc/react-native-meteor ?

**Comment by dr-dimitru** [comment]
@faavictoriano any news on your end?

**Comment by faavictoriano** [comment]
I will try this.. Thank you.. :) we are using ddp for connection.. And i
guess we can use react native for.meteor. actually we are using this before

**Comment by dr-dimitru** [comment]
@faavictoriano thank you for reply, let me know then.

**Comment by dr-dimitru** [comment]
@faavictoriano any news on your end?

**Comment by dr-dimitru** [comment]
This issue will be closed on next week, due to issue starter silence. *I expect it fixed.*

**Comment by faavictoriano** [comment]
I fixed i pass video and audio using DATA URI and BLOB.. thanks

**Comment by noris666** [comment]
@faavictoriano are you can send example to here ?

**Comment by gauravdhiman** [comment]
@faavictoriano, can you share your code to see how you achieved upoading files to Meteor from React-Native.

I am using `react-native-meteor` for integration between React-Native and Meteor but looks like it's `CollectionFS` capability is deprecated and is discouraged to be used.

A sample code of how you achieved file upload (both using base64 and and Data URI) will really be helpful.

**Comment by dr-dimitru** [comment]
> both using base64 and and Data URI

base64 and Data URI is the almost same thing, Data URI has mime-type prepended to the data.

@gauravdhiman can you get an event when user selects the file? Something like in `input[type="file"]`?? *Sorry not familiar with react-native*

**Comment by gauravdhiman** [comment]
@dr-dimitru, yes I can get `file` object whenever user selects file(s). I am planning to use, `react-native-image-crop-picker` react component for this.

Once I get the file object, how to upload it to Meteor or 3rd party cloud APIs ? I would prefer Meteor.

**Comment by dr-dimitru** [comment]
@gauravdhiman can `react-native-image-crop-picker` return Base64 encoded string?

**Comment by gauravdhiman** [comment]
@dr-dimitru, that I can convert on the fly.

Anyway more preferred way is to send binary data (image) and not converting it to base64. Send binary to Meteor and binary in Mongo GridFS. If that is not possible, I am ok with base64 in that case.

Please share the sample code, if possible.

**Comment by dr-dimitru** [comment]
@gauravdhiman you can find everything you need in wiki:
 - Upload as [base64](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#upload-base64-string)
 - Upload as [*File* Instance](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload)#upload-form) Blob (*or Uint Array*) can be easily converted to *File*
 - [GridFS Integration](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration)

Let me know if it helped you
