### ISSUE TITLE
206 Partial Content requests raise/crash ERR_HTTP_TRAILER_INVALID

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#742]
When piping audio files from S3 through Meteor-Files with `interceptDownload()` and `serve()` the server crashed on some files with `ERR_HTTP_TRAILER_INVALID` from https://github.com/nodejs/node/blob/d01a06a916efd30844e1e0a38e79dc0054fc4451/lib/_http_outgoing.js#L458-L460 (tested on node `12.6.1`).

I *think* the reason for this is that on Status code `206` both `Content-Range` and `Transfer-Encoding` are set, and if I am not mistaken they conflict. If I understand the specs correctly those are not allowed to be used together:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#Comparison_to_chunked_Transfer-Encoding
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer

```JS
        case '206':
          headers.Pragma               = 'private';
          headers.Trailer              = 'expires';
          headers['Transfer-Encoding'] = 'chunked';
          break;
```
https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L242-L246

```JS
if (!http.response.headersSent) {
        http.response.setHeader('Content-Range', `bytes ${reqRange.start}-${reqRange.end}/${vRef.size}`);
      }
```
https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1840

My knowledge of HTTP headers is limited, hopefully, this gives you some clues @dr-dimitru .

My current workaround is to pass my own `responseHeaders()` without the `case 206` part.

**Comment by jankapunkt** [comment]
That's interesting, we basically stream audio content from GridFS via 206 and the slightlycustomized `interceptDownload` example from the wiki (customized for GridFSBucket) and we never ran into any of these errors. Not downgrading your issue, rather I am aware that Murphy's law will hit us, too.

Any hint how to reproduce this?

**Comment by menelike** [comment]
You must have a request including `byte-ranges`. This can be tested with an mp3 file (tested with a 3MB one)

![image](https://user-images.githubusercontent.com/4238881/80307390-147af480-87c9-11ea-9167-1376f5ea5c67.png)
The flag `range` is important here.

This should then 

1. hit https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1729
2. and then https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1742
3. and in the end https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1840

The response should typically look like:

![image](https://user-images.githubusercontent.com/4238881/80307450-658ae880-87c9-11ea-8c81-06788b5e0072.png)

I observed this locally with [minio](https://min.io/) and did not test this against AWS S3, but I doubt that this should change the result.

The second and all upcoming requests look like this then, notice that the range increases:

![image](https://user-images.githubusercontent.com/4238881/80307556-0e394800-87ca-11ea-8326-838cb31f9d46.png)

Though you won't see this as the server crashes in the first request.

**Comment by menelike** [comment]
Hope this helps, I reproduced the crash with this:

`https://your.server/cdn/storage/ServiceFiles/kEXcy7pEbHw56v32E/stream/kEXcy7pEbHw56v32E.mp3 -i -H "Range: bytes=0-" --cookie "x_mtok=foo" --output foo.mp3`

**Comment by menelike** [comment]
@jankapunkt If you're not able to reproduce this, I'll make a repro by tomorrow.

**Comment by jankapunkt** [comment]
Thanks a lot I will check this out against our current builds

**Comment by menelike** [comment]
Small update, I am currently working on a reproduction, so far I could not get https://github.com/VeliovGroup/Meteor-Files-Demos/tree/master/demo-simplest-streaming to crash.

**Comment by menelike** [comment]
This seems to be caused in conjunction with Nginx, this comment helped a lot. I added `proxy_http_version 1.1;` to my location block like this:

```
    location /cdn/ {
        client_body_buffer_size 128k;

        proxy_pass http://app;
        proxy_redirect      off;
        proxy_set_header    Host              $host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }
```

and the crash is gone. Nginx uses `proxy_http_version 1.0;` per default.

I still try to figure out what exactly happens here.

**Comment by menelike** [comment]
@dr-dimitru @jankapunkt 

I am finally able to reproduce this with https://github.com/VeliovGroup/Meteor-Files/tree/master/demo-simplest-streaming. Run that project, grab the mp3 URL, and run the following (`--http1.0` is important here!):

`curl http://localhost:3001/cdn/storage/Sounds/foo/original/foo.mp3 -i -H "Range: bytes=0-500" -v --http1.0 > /dev/null`

while 

`curl http://localhost:3001/cdn/storage/Sounds/foo/original/foo.mp3 -i -H "Range: bytes=0-500" -v --http1.1 > /dev/null` does not fail.

This should mean that we can DOS Meteor-Files Servers now 🚨.

I think that https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L242-L246 needs to cover https://github.com/VeliovGroup/Meteor-Files/blob/master/server.js#L1840 as well and set one of those headers, depending on the request e.g. if range requested or not.

**Comment by jankapunkt** [comment]
Wow really great work @menelike

**Comment by dr-dimitru** [comment]
@menelike @jankapunkt thank you guys for investigation.
- Fixed in the latest release;
- Added memo into FAQ section
