### ISSUE TITLE
Is there a way to clone a file and record?

### ISSUE THREAD

**Issue by urakagi** [VeliovGroup/Meteor-Files#747]
As title, with a `FileCursor` is there something like `.clone()` to clone the file record and file itself, then return the new `FileCursor`?

I'm going to invent it but I want to make sure I'm not reinventing the feature. You can't just `Collection.insert(FileCursor)` just like `CollectionFS` right?

**Comment by dr-dimitru** [comment]
Hello @urakagi ,

No, there is no such feature as of today. But sounds like a good candidate.
`Collection.insert(FileCursor)` won't work neither. `.insert()` method is available only on the Client
Right now you got to read the file using `fs` on server, then you have next options:
1. `.write()` method to create new file out of Buffer;
2. Write file on FS using `fs` module, then using `.addFile()` method create new file using its path;

**Comment by urakagi** [comment]
@dr-dimitru Thank you, can you mention a method to get `ReadStream` or `File` object from a `FileCursor` rather than using `.link()`?

**Comment by dr-dimitru** [comment]
@urakagi `.link()` method won't help you; __This got to be done on server__.

Use `_storagePath` as per [*Schema*](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema):

```js
import fs from 'fs';

const path = FilesCollectionInstance.collection.findOne({_id: '_file_id_'})._storagePath;
FilesCollectionInstance.write(fs.readFileSync(path), {fileOpts});
```

See [`.write()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/Write) and [`fs` module docs](https://nodejs.org/docs/latest-v12.x/api/fs.html) for more details.

**Comment by dr-dimitru** [comment]
Feel free to open new ticket for `.copy()` or `.clone()` method

**Comment by urakagi** [comment]
I guess for this code it's `.path` rather than `_storagePath`? Thank you!

**Comment by dr-dimitru** [comment]
@urakagi I’m glad this one is solved, feel free to open feature request for `.copy()/.clone()` method

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
