### ISSUE TITLE
How to display files on meteor 1.3 + reactjs

### ISSUE THREAD

**Issue by justinFather** [VeliovGroup/Meteor-Files#75]
Hi,

I can use fileURL template helper on blaze. 
If i use meteor 1.3 + reactjs, how can I display files?

I tried like below
src=\`${image._downloadRoute}/${image._id}.${image.extension}\`

Thank you

**Comment by dr-dimitru** [comment]
Take a look on: [`.link()` method](https://github.com/VeliovGroup/Meteor-Files/wiki/link)

**Comment by justinFather** [comment]
.link() works fine!!

Thank you

**Comment by ankibalyan** [comment]
link is giving output like
`http://localhost:3000undefined/undefined/ap2LgFbeqa9gXDvTR/original/ap2LgFbeqa9gXDvTR`

Why undefined?

**Comment by dr-dimitru** [comment]
Hi @ankibalyan ,

Sorry for delayed response. Could you drop your FilesCollection Contractor definition? Looks like `_downloadRoute` and `_collectionName` is missing. And how you're calling `.link()` method? on FileCursor?
