### ISSUE TITLE
Demos are Briked - React Demo is total fubar

### ISSUE THREAD

**Issue by tomtom87** [veliovgroup/Meteor-Files#750]
Just tried to get this working by following the docs for React and it's a load of nonsense you guys didn't even write anything working here. Take a look yourself and try and get that heap of junk to work. Your docs are clearly out of date plus there are numerous spelling mistakes in your source code and references to collections never mentioned. In short its fubar'd  

From the starting point that references (as a fundamental requirement) two server side methods of which neither exist in any of your source code published here (RenameFile and RemoveFile) I can see the calls and UI interfaces, but no where are the actual methods published. So kinda in the dark on that one. If you can shed some light that would be great!!

It also specifically mentions a collection publication named Files.images.all but the example later goes on to use a UserFiles collection. Which leaves me asking only one thing "wtf?"

Before you ask, yes obviously I have read the docs from top to bottom and grepped all your source. Honestly guys it's briked. I wouldn't be posting here unless doing that first - I don't want to waste anyones time so sorry if I have overlooked something obvious but it just wasn't possible to get this working. I've looked all over and people recommend this package although maybe they are not using React / React was in its infancy when these docs were published? 

My suggestion is to provide a workable example that can be used by developers so we can use this awesome project.

Thanks for your help on this and I hope to be able to use this package one day as it does look really good and I hope I can help out in being a tester and providing you with feedback.

Cheers! 🍻

**Comment by jankapunkt** [comment]
Helpers > Ranters

**Comment by dr-dimitru** [comment]
@tomtom87 This project, repository, and its docs are community effort. It might be outdated or wrong, so far no one has reported such issues. We encourage to send a PR if you have a solution or post link to this thread in social media and forums.meteor.com to get expertise from other community members.

**Comment by tomtom87** [comment]
Please share your working example of react and I'll take it from there.

**Comment by tomtom87** [comment]
> Helpers > Ranters
> 
> Edit: before this provokes even more rant - it is great to see you have checked the source but I don't understand why you leave us with your anger and not immediately create a PR with a working example. I think the step from realizing that the code is wrong to providing a correct / working example is not that far. Why don't you give it a try and update the examples?

Bro I'd do that if there was any part of it that worked... the example doesnt work. So far I spent 20 hours debugging this and cannot get it working. Stackoverflow and meteor forums are full of same responses and told to roll our own or use a 3 year deprecated library. Maybe I have to go that route cos you guys wont help? I dunno seems kinda against the whole ethos but meh its 2020 wth do I know I've only been coding since assembly in the late 80s Im just a jack ass I guess the world changed. Glad to know this shit dont fly in C, GO or Kernel work... have a good one hope you get it working. Cheers

**Comment by tomtom87** [comment]
Update -I got this working in the end by using the deprecated package collectionFS and following their docs, within minutes I had working file upload and everything works as should. I got really excited and did a couple shots and ripped some big dank nugs to celebrate as this is the last bug on my todo list and it's nearly friday. 

Please update your docs so that I can use the new one and if you need a guinea pig to test it @ me

Hope you guys can figure it out soon

Cheers! 🥃🔥

**Comment by kakadais** [comment]
Greate job. But I also greatefully want you to have some respect for these guys are updating and answer this project wihtout any profit cause this is a open source project. 

I believe that you are already aware of how this project is great, cause you are already spend a lot of time into here. 

Let's make this better together without complaining.

**Comment by dr-dimitru** [comment]
Demos are bricked indeed, here are some insights: Demos, servers, and its maintenance aren't free for a long time it was funded by community support and donations. Last few years donations are covering only a fraction of codebase maintenance, so right now we limited in resources, while the rest of open source contributions is sponsored by [ostr.io service](https://ostr.io). And a little more details can be found [in this article](https://dev.to/smart_egg/open-source-crisis-54d5), which in fact attracted 2 new patrons 😅

We have big plans to release a major upgrade to this library, with complimentary demos.
Emotional and financial support is always welcome 👨‍💻😊

**Comment by tomtom87** [comment]
Github is free hosting, funny how everyone else does just fine but you need
money. The existing package which this allegedly supersedes is all hosted
on github, for 100% free and works perfectly. You guys just don't know
you're born. Get a grip! I aint donating jack

**Comment by dr-dimitru** [comment]
@tomtom87 can't wait to see how you host node.js/meteor.js app on github

**Comment by tomtom87** [comment]
localhost...

Are you trolling bro?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
