### ISSUE TITLE
Add support for async functions in FilesCollection

### ISSUE THREAD

**Issue by prevuelta** [VeliovGroup/Meteor-Files#754]
### I have a suggestion:

Add support for async functions in FilesCollection options 
eg.

```
async onAfterUpload(file) {
  if (Meteor.isServer) {
  const { mime } = await FileType.fromFile(file.path);
   if (!mime.includes("image/")) {
          console.log(
            "onAfterUpload, image is not a valid image type: ",
            file.path
          );
   throw new Meteor.Error("Image format invalid");
  }
}
```

**Comment by dr-dimitru** [comment]
Hello @prevuelta ,

Is there an issue with `async onAfterUpload`? Should work out of the box

**Comment by prevuelta** [comment]
Ah right, will play around my end - prob an error in my code but I was getting an UnhandledPromiseRejectionWarning - may be missing a try/catch

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
