### ISSUE TITLE
Image Uploads on GridFS spontaneously stopped working for larger images 

### ISSUE THREAD

**Issue by sabedinia** [VeliovGroup/Meteor-Files#762]
Client disconnects occasionally after upload start. Meteor.status().connected === false.
For some reason uploads spontaneously work. Before we had no trouble uploading larger ones but now all of a sudden uploads would stall. The state will go from active ---> paused. Then when i try to call continue() is still hangs.

 I'm wondering if anybody else is experiencing this?

1. using DDP to stream.
2. Here are the logs:

[FilesCollection.storagePath] Set to: assets/app/uploads/image
{"line":"80","file":"migrations_server.js","message":"Migrations: Not migrating, already at version 1.205","time":{"$date":1602458759904},"level":"info"}
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [File Start Method] IMG_3835.jpeg - nKNpxfLhvRJTmkMd2
[FilesCollection] [Upload] [DDP Start Method] Got #-1/2 chunks, dst: IMG_3835.jpeg
[FilesCollection] [Upload] [DDP] Got #2/2 chunks, dst: IMG_3835.jpeg
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]
[FilesCollection] [find({}, undefined)]

639b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [findOne({}, undefined)]
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [insert()]
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [FileUpload] [constructor]
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [insert] using WebWorkers
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [UploadInstance] [createStreams]
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 loadFile IMG_3835.jpeg: 95.85498046875 ms
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 [FilesCollection] [insert] [Tracker] [pause]
39b66562672d9e23f26b253b859d4bb3261915ea.js?meteor_js_resource=true:325 

<img width="974" alt="Screen Shot 2020-10-12 at 10 20 12 AM" src="https://user-images.githubusercontent.com/72748901/95763338-84484300-0c74-11eb-83a2-6789118eaa0f.png">

**Comment by dr-dimitru** [comment]
I recommend to switch to HTTP transport and reduce chunk size, in case if it's `dynamic` change it to constraint `8000`, and go up to around `256000`, you should find optimal value in between this range

**Comment by sabedinia** [comment]
@dr-dimitru thanks so much for responding. stayed up till 1am last night trying to debug this. The issue was related to the firewall.

In the future if anyone notices the web socket connection dropping after a minute or so on idle. Try restarting the firewall.
We were using pfSense.

**Comment by dr-dimitru** [comment]
Thank you for sharing insights into your solution. I'm glad you were able to fix it *relatively* quickly 😬

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru/dashboard) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
