### ISSUE TITLE
.link is not a function when retrieving multiple files

### ISSUE THREAD

**Issue by leprekon91** [veliovgroup/Meteor-Files#765]
I am having issues with using useTracker to retrieve a query of files:
when writing:
```javascript
const files = useTracker(() =>
    MedicalStorage.find({ meta: { tag } }).fetch()
  );
```
and later using inside a component:
```javascript
{files.map((file) => (
        <div>
          <a
            href={file.link()}
            download={file.name}
            key={file._id}
            target="_parent"
          >
            download {file.name}
          </a>
          <button type="button" onClick={remove(file._id)}>
            delete
          </button>
        </div>
      ))}
```
I am getting the error: `file.link is not a function`.
When using just `.findOne()` everything works as intended.
I tried using `forEach` and tried to generate the links into a static array in the tracker and then returning it but the same error occurred there.
I am receiving the file object as viewed by the console.log(file):
```javascript
{
ext: "pdf"
extension: "pdf"
extensionWithDot: ".pdf"
isAudio: false
isImage: false
isJSON: false
isPDF: true
isText: false
isVideo: false
meta: {tag: "past-diagnoses"}
mime: "application/pdf"
mime-type: "application/pdf"
name: "andrey.pdf"
path: "assets/app/uploads/medStorage/XXsrw47TxGvpSNgrf.pdf"
public: false
size: 11626
type: "application/pdf"
userId: "Lvp2fZG3suKGy3oHE"
versions: {original: {…}}
_collectionName: "medicalStorage"
_downloadRoute: "/files/medStorage"
_id: "XXsrw47TxGvpSNgrf"
_storagePath: "assets/app/uploads/medStorage"
}
```

**Comment by dr-dimitru** [comment]
Hello @leprekon91,

After you call `fetch()` method on a cursor it returns plain *Object*, so there's no `.link()` method.

Omit `.fetch()`:

```js
{MedicalStorage.find({ meta: { tag } }).map((file) => (
        <div>
          <a
            href={file.link()}
            download={file.name}
            key={file._id}
            target="_parent"
          >
            download {file.name}
          </a>
          <button type="button" onClick={remove(file._id)}>
            delete
          </button>
        </div>
      ))}
```

**Comment by dr-dimitru** [comment]
@leprekon91 Docs: https://github.com/VeliovGroup/Meteor-Files/wiki/FilesCursor

**Comment by leprekon91** [comment]
Did not work, unfortunatly:
```javascript
const files = useTracker(() =>
    MedicalStorage.find({ meta: { tag } }).map((f) => ({
      name: f.name,
      _id: f._id,
      link:f.link()
    }))
  );
```
Still getting `f.link is not a function` error.
Also tried the way you did inside a component without using `useTracker` and the same error comes up.

**Comment by dr-dimitru** [comment]
@leprekon91 read docs on `.map()` — Function to call. It will be called with three arguments: the file, a 0-based index, and cursor itself

I recommend to use `.each` or `.forEach`

```js
MedicalStorage.find({ meta: { tag } }).each().map((f) => ({
      name: f.name,
      _id: f._id,
      link:f.link()
    }))
```

**Comment by leprekon91** [comment]
Thanks! I used each in the end, everything is resolved!

**Comment by dr-dimitru** [comment]
@leprekon91 I'm glad you solved it 👍

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru/dashboard) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
