### ISSUE TITLE
How to add additional fields to collection.doc and not to collection.doc.meta

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#77]
I need to add additional data to the created document. Currently this is only possible trough `config.meta`. My collection is created like:

```
const FooFiles = new FilesCollection({
  collectionName: 'FooFiles',
});

const MetaSchema = new SimpleSchema({
  fooId: {
    type: String,
  },
});

const FooFilesSchema = new SimpleSchema({
  ...FooFiles.schema,
  meta: {
    type: MetaSchema,
  },
});

FooFiles.collection.attachSchema(FooFilesSchema);
```

*note: imho this is the proper way to attach schema to a collection, the current documentation does not follow collection2/simple schema guidelines*

What I really need is to be in full control of the document because I need to set the Index on `fooId` e.g. 

```
  fooId: {
    type: String,
    index: true,
  },
```

I love this lib, it has everything I need and it works very well. This is the only feature I miss a lot, would be quiet happy about a clean and straightforward solution.
Maybe a second object like `config.doc` could help here. Later on this could just be merged with existing data like `{...config.doc, ...currentInsertedObj}`, validation should be done trough `SimpleSchema`.

**Comment by dr-dimitru** [comment]
> note: imho this is the proper way to attach schema to a collection, the current documentation does not follow collection2/simple schema guidelines

Difference only between ES5 and ES6, right?

Answering on your question:
```js
// Isomorphic:
// Create a collection
this.FooFiles = new FilesCollection({collectionName: 'FooFiles'});

// Server:
// Work with doc. Move required fields to other places:
FooFiles.on('afterUpload', function (fileRef) {
  var _fooId = fileRef.meta.fooId;
  FooFiles.collection.update({
    _id: fileRef._id
  }, {
    '$set': {
      fooId: _fooId
    },
    '$unset': {
      'meta.fooId': ''
    }
  });
});

// Client:
// Pass `fooId` into meta
Images.insert({
  file: file,
  meta: {
    fooId: 'KLJdiawdhlsdLKJ'
  }
});
```

Main reason for this is *security*, it's easier to have only one *blackbox* object (which sent from client to server) and control it, after all - on server (trusted side) can do all queried operations with data.

Similar approach may be found in Meteor's [Accounts](http://docs.meteor.com/#/full/accounts_createuser) where you can pass custom data only via `profile`, and only later on server modify it in [`.onCreateUser()`](http://docs.meteor.com/#/full/accounts_oncreateuser) callback.

**Comment by dr-dimitru** [comment]
> note: imho this is the proper way to attach schema to a collection, the current documentation does not follow collection2/simple schema guidelines

I think I got it wrong first time, have you mean schema extending, right?

**Comment by menelike** [comment]
Taken from the [meteor-collection-2 readme](https://github.com/aldeed/meteor-collection2/blob/master/README.md) you always need to attach an instantiated schema with 

```
Schemas.Book = new SimpleSchema({
 ...
});
Books.attachSchema(Schemas.Book);
```

Notice the **new SimpleSchema()***

I may have missed the point, but I've never seen that a plain object should (or can?) be attached to a collection (though I haven't tested if this would also work).

Furthermore extending an existing schema can be done trough [picking](https://github.com/aldeed/meteor-simple-schema#extracting-simpleschemas) the appropriate fields or the whole obj._schema which holds the raw object.

As I need to add, omit and overload fields I use it actually like this:

````
const BarSchema = new SimpleSchema({
  ...FooSchema.pick(['fooField', 'barField'])._schema, // explicit fields
  ...FooSchema._schema, // or all fields
  newField: {
    type: String,
  },
});
```

Of course there might be better solution.

In terms of security, why not just enabling the schema per default? Security issues should be solved as additional fields need explicit schema enhancements.

**Comment by dr-dimitru** [comment]
Thank you for pointing to this, updated in https://github.com/VeliovGroup/Meteor-Files/commit/2c984c31bcae8fa5ba75ebea24c330a16e659ec3

> In terms of security, why not just enabling the schema per default? Security issues should be solved as additional fields need explicit schema enhancements.

It used to be enabled, but we're no longer use Schema in our projects, and we think other folks should have ability to choose whenever use it or not. For us Collection2 and SimpleSchema is too overwhelming

**Comment by menelike** [comment]
I understand your point, I can live with your advised solution. Thanks for the readme update, the docs make a lot more sense now. 

FYI: We started using [`validated methods`](https://github.com/meteor/validated-method) on our project and after a couple of days we started loving it, this is based heavily on `Simple Schema`.

I close this as this feature does not fit the roadmap, please reopen on if this will be reconsidered ;)

**Comment by dr-dimitru** [comment]
We hit high traffic on our end on some production stages. After removing some packages (*we can live without*) our performance twice boosted. Although waiting for Meteor 1.4 with Node 4, which should bring performance boost, some packages occasionally turned to be overwhelming. We always use [`audit-argument-checks`](http://docs.meteor.com/#/full/auditargumentchecks), for all object nested props, which is secure and fast.

Thank you for contribution and for using this package. Do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Meteor file upload - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)
