### ISSUE TITLE
(Question) How to handle aborted upload by browser close

### ISSUE THREAD

**Issue by kakadais** [veliovgroup/Meteor-Files#775]
Insert event has 'abort' but it couldn't emitted on the browser crash or force closed.

'afterUpload' event also has no error state in the callback,
so I don't know where to get the event for 'not finished upload' on server.

Thanks for your help-

**Comment by dr-dimitru** [comment]
All unfinished uploads will be removed and cleaned up upon [`continueUploadTTL`](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md) expiration, by default `10800` seconds (e.g. 3 hours)

Feel free to close it in case if the issue is solved on your end.

**Comment by kakadais** [comment]
I need to control such as upload abort or browser close or crash event for some reason. 

Is there no event for this on server side?

**Comment by dr-dimitru** [comment]
@kakadais there's no 100% way to do that in web development, this is well-known topic
I'd recommend to look on Beacon API, which is available in __almost__ all browsers

**Comment by kakadais** [comment]
Okay, I expected event such as using socket connection stauts things- (cause it's Meteor ;))
I know socke connection wouldn't be enough to determin the connection was stopped or hanging and so on.

Could you let me know what's the factor for your unfinished uploads process?
e.g. unexpected socket disconnection / check later completion of file status or file size things?

**Comment by dr-dimitru** [comment]
Unfinished uploads are defined by:
- EOF not received; and 
- TTL is expired

**Comment by kakadais** [comment]
Thanks!
