### ISSUE TITLE
Question about gridfs-stream -> GridFSBucket migration

### ISSUE THREAD

**Issue by aureooms** [veliovgroup/Meteor-Files#786]
Is there anything in particular to check for when migrating from `gridfs-stream` to `GridFSBucket`? Can one integration be swapped-in  without any `MongoDB` plumbing?

**Comment by dr-dimitru** [comment]
@aureooms is there something particular you worrying about?

Feel free to post your old and new implementations, we will help to find possible incompatibility points

**Comment by aureooms** [comment]
@dr-dimitru Underlying collection configuration changes?

I will attempt to do the migration assuming everything will work out and report back.

**Comment by dr-dimitru** [comment]
Hello @aureooms, did you manage to perform migration?

**Comment by aureooms** [comment]
Hi @dr-dimitru! I have not worked on it yet.

**Comment by make-github-pseudonymous-again** [comment]
Coming back to you. I successfully migrated! See https://github.com/infoderm/patients/issues/157. In particular, https://github.com/infoderm/patients/issues/157#issuecomment-864028987 is the answer to

> Underlying collection configuration changes?

Aside from this semi-non-issue, I had to be particularly focused when diffing the previous implementation with https://github.com/veliovgroup/Meteor-Files/blob/6a192b74537c705069ad60b21959ef2233b9f58b/docs/gridfs-bucket-integration.md. For instance `.on('end', ...)` becomes `.on('finish', ...)` in the upload handler.

**Comment by nuxeo-rameel** [comment]
> Closed due to silence at issue owner end. Feel free to reopen it in case if the issue still persists on your end.





https://framed-surveymonkey24.github.io/hug/
