### ISSUE TITLE
.link() with public collection with versions points to wrong file name

### ISSUE THREAD

**Issue by neopostmodern** [veliovgroup/Meteor-Files#788]
### I'm having an issue:
- Give an expressive description of what is went wrong

When generating versions for a public collection and then requesting a `.link()` for such a version the file name does not match the file name used on disk. Example: 
```versions: {
  "small-avif": {
    extension: "avif",
    path: "/home/.../data/images/nG69zE5Mr5X7KLvci_small.avif",
    size: 8038,
    sizeName: "small",
    type: "image/avif"
  }
}
```
  yields `https://.../images/small-avif-nG69zE5Mr5X7KLvci.avif` - which I have mapped to the correct folder, but the file name is off.
- Version of `Meteor-Files` you're experiencing this issue
  2.0.0
- Version of `Meteor` you're experiencing this issue
  1.11.1
- Where this issue appears? OS (Mac/Win/Linux)? Browser name and its version?
  Ubuntu Server 18.04
- Is it *Client* or *Server* issue?
  Server

**Comment by dr-dimitru** [comment]
@neopostmodern sorry for the late response.
Is this sill a case? Have you solved it? If not, let me know:
1. Server/Client `FilesCollection` definition

**Comment by neopostmodern** [comment]
Yeah, it's fixed. If I remember correctly, I had to set `public: true` on every inserted document manually (quite odd IMHO). Why is this managed at the collection level? But yes, consider it solved.

**Comment by neopostmodern** [comment]
```js
const Images = new FilesCollection({
  collectionName,
  downloadRoute: '/images',
  allowClientCode: false, // Disallow remove files from Client
  public: Meteor.isProduction,
  schema: imageSchema,
  storagePath: () => ImageStoragePath,
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (!(file.size <= 10485760 && /png|jpg|jpeg|gif/i.test(file.extension))) {
      return 'Please upload image, with size equal or less than 10MB'
    }
    if (!Roles.userIsInRole(this.userId, ROLE_NAMES.ADMIN_CONTENT)) {
      return 'User not allowed to upload images'
    }
    return true
  },
})
```

**Comment by dr-dimitru** [comment]
@neopostmodern thank you for an update

> Why is this managed at the collection level?

1. `FilesCollection#link{}` method is static and stateless
2. If you change storage method or location, old files would remain accessible following old behavior

I noticed in your example you refer to file's subversion. Does the same happen when generating link to the original file?
How subversion is created? Subversions are under your full control

**Comment by neopostmodern** [comment]
Original file works fine. (`https://.../images/nG69zE5Mr5X7KLvci.avif`)

I generate the versions with `sharp` and then add them with:
```js
Images.collection.update(fileRef._id, {
  $set: {
    [`versions.${sizeName}-${format}`]: {
      path: targetPath,
      size: fileSize,
      sizeName,
      type: `image/${format}`,
      extension: format,
    },
    [`meta.sizes.${sizeName}`]: {
      width,
      height,
    },
  },
})
```

**Comment by dr-dimitru** [comment]
@neopostmodern 
1. Could you post code-sample where you're calling `.link()` method?
2. After using `sharp` — you got to create a file following naming convention you've defined in `versions` object — `${sizeName}-${format}-${_id}.${extension}`

**Comment by neopostmodern** [comment]
1 – will do later.
2 – is that a hard-coded pattern I'm forced to follow? If yes, I guess I'll stick with my nginx-regex since I want all versions to have the same prefix (_id), otherwise it get's even more chaotic.

**Comment by dr-dimitru** [comment]
@neopostmodern 
1. 👍
2. Name taken from version key you've defined `versions.${sizeName}-${format}` === `${sizeName}-${format}-${_id}.${extension}`
3. Post how file written to FS after `sharp` is generated new version

**Comment by dr-dimitru** [comment]
Hello @neopostmodern, any updates on your end?

**Comment by neopostmodern** [comment]
I write the files straight to the FS with sharp `sharpHandle.toFile(targetPath)`

As for `.link)` calls, I'm using this snippet
```
const getImageLink = (image, size) => {
  if (image.link) {
    return image.link(size)
  }
  return Images.link(image, size)
}
```

But I guess you're explanation of how the expected filename is derived from the version key explains everything. I feel like the documentation could be more explicit about this and/or it would be nice to be able to customize this behabior – for now I'll stick to rewriting the requests with a RegEx in nginx!
