### ISSUE TITLE
Async Await is not working inside onBeforeUpload - even setTimeout is not working  

### ISSUE THREAD

**Issue by ganesh-swami** [veliovgroup/Meteor-Files#789]
I am trying to make a API call before returning `true `or `false `inside `onBeforeUpload`
But it is not working so i tried with a very simple example of `setTimeout ` to check if it does support or not.

I am trying from yesterday and still have no clue on how i can make api call inside on before upload. As for my use case i need to get the upload size limit on user id basis and stop uploading if limit crosses. Let me know if i should share more details

I am using meteor 2.0 and meteor-files 2.0 server OS is ubuntu 16

```
onBeforeUpload: function (file) {
   setTimeout(function(){
      return true;
    },1);
}
```

supposed to be return true after 1ms but i got error 

```
details: undefined
error: 403
errorType: "Meteor.Error"
isClientSafe: true
message: "collection.onBeforeUpload() returned false [403]"
reason: "collection.onBeforeUpload() returned false"
stack: "Error: collection.onBeforeUpload() returned false [403]↵    at UploadInstance.start....
```

server logs
`[FilesCollection] [Abort Method]: 5QpN6tRC6k94k5J5X -`

i don't know what wrong in this code or is there any other way to do this
I have tried to use `onInitiateUpload` and it works fine while calling API but I can't stop uploading as returning true or false doesn't make any difference . 
Any help will be appreciated.
Thanks

**Comment by dr-dimitru** [comment]
Hello @ganesh-swami,

1. `onBeforeUpload` is isomorphic and you can use it on sever
2. __Note__: `onBeforeUpload` called every time file-chunk sent/received
3. When using on server use synchronous collection API to retrieve data. Or block the thread for asynchronous calls using `Fibers#Future`

**Comment by dr-dimitru** [comment]
@ganesh-swami  Feel free to close it in case if the issue is solved on your end.

**Comment by ganesh-swami** [comment]
Thanks @dr-dimitru 
I have tried to use Fibers#Future but because of version issue it doesn't work so finally I have managed with `onBeforeUpload` by fetching data from database.
