### ISSUE TITLE
Can't continue upload, session expired. Please, start upload again. [403]

### ISSUE THREAD

**Issue by dokithonon** [veliovgroup/Meteor-Files#792]
I am having an issue when trying to upload files i receive a 403 : Can't continue upload, session expired. Please, start upload again. [403]

Meteor-files 2.0.1
Meteor 2.1

Cannot reproduce on localhost (working fine on development)

Server logs

```
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [File Start HTTP] file.pdf - xvbNMxEdkxymmuFWE
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [Upload] [HTTP Start Method] Got #-1/3 chunks, dst: file.pdf
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [Upload] [HTTP] Got #1/3 chunks, dst: file.pdf
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [Upload] [HTTP] Got #2/3 chunks, dst: file.pdf
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [Abort Method]: xvbNMxEdkxymmuFWE - /home/apps/demo/uploads/rKUploads/xvbNMxEdkxymmuFWE.pdf
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [remove({"_id":"xvbNMxEdkxymmuFWE"})]
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [unlink(xvbNMxEdkxymmuFWE, undefined)]
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [_preCollectionCursor.observe] [removed]: xvbNMxEdkxymmuFWE
3577|demo  | 2021-03-15 09:18 +01:00: [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: xvbNMxEdkxymmuFWE
````

Client logs

<img width="1357" alt="Screenshot 2021-03-15 at 09 20 12" src="https://user-images.githubusercontent.com/1856638/111123505-b2a5b380-856f-11eb-90d9-7ec83fc3b3b0.png">

The error occurs on different servers (Our application is deployed on different servers i.e. we have multiple independent apps on multiple servers and the error is the same)
This was working fine for a long time.
We recently changed some settings in cloudflare (I don't know if this is a hint)

Thanks for your help.

**Comment by dr-dimitru** [comment]
Hello @dokithonon ,

Could you post details on `403` error request from Network tab?
Also make sure you're on the latest release. As you should get `408` error, and seems like this issue was fixed in recent releases.

**Comment by dokithonon** [comment]
Hello,
Thanks for your prompt feedback
![Screenshot 2021-03-15 at 10 14 35](https://user-images.githubusercontent.com/1856638/111130259-4dee5700-8577-11eb-8f3e-1e429d383ddb.png)

**Comment by dr-dimitru** [comment]
@dokithonon 

1. You got to click on it, to show details
2. Make sure Server and Client are using the same version of Meteor-Files, on the latest release it should return `408` error code for expired session

**Comment by dokithonon** [comment]
Some additional details
![Screenshot 2021-03-15 at 10 23 59](https://user-images.githubusercontent.com/1856638/111131813-ea652900-8578-11eb-91e2-689ae48767d8.png)

On a running production server, is there a way to check the version of ostrio:files ?

**Comment by dr-dimitru** [comment]
@dokithonon 

1. Wrong tab, got to look on "Headers" and "Response" tabs
2. Yes, just inspect server files, usually over `ssh`
3. Could you elaborate on `Our application si deployed on different server`?

**Comment by dokithonon** [comment]
1. 
Headers tab

Part 1

![Screenshot 2021-03-15 at 10 35 39](https://user-images.githubusercontent.com/1856638/111132955-43818c80-857a-11eb-996c-d28b9ff22d3e.png)

Part 2 (scrolled down)

![Screenshot 2021-03-15 at 10 36 26](https://user-images.githubusercontent.com/1856638/111133038-598f4d00-857a-11eb-989b-edd2afac8168.png)

Response Tab is empty

![Screenshot 2021-03-15 at 10 37 20](https://user-images.githubusercontent.com/1856638/111133158-7b88cf80-857a-11eb-9093-8855c0c0edbc.png)

2. I will try this
3.  Sorry for the typo. Our application **is** deployed on different server i.e. we have multiple independent apps on multiple servers and the error is the same on all servers

**Comment by dokithonon** [comment]
I have been able to look at ostrio_files.js on the server, how do you see the version in the file ?

![Screenshot 2021-03-15 at 10 45 43](https://user-images.githubusercontent.com/1856638/111134204-ab84a280-857b-11eb-87b2-55c8adb9d208.png)

Thanks

**Comment by dr-dimitru** [comment]
@dokithonon there should be json or text file with all installed packages details

**Comment by dokithonon** [comment]
I see a 408 
<img width="1363" alt="Screenshot 2021-03-15 at 10 49 40" src="https://user-images.githubusercontent.com/1856638/111134726-2e0d6200-857c-11eb-92da-77c1fe901c5e.png">

**Comment by dokithonon** [comment]
Thanks for your help on the phone. We solved the problem by adding a cloudflare rule :

<img width="1094" alt="Screenshot 2021-03-15 at 13 30 52" src="https://user-images.githubusercontent.com/1856638/111157166-ddefc900-8596-11eb-8ed9-32cfa53b7808.png">
