### ISSUE TITLE
Is it possible to keep file on disk and remove it in mongo only?

### ISSUE THREAD

**Issue by e-gaulue** [veliovgroup/Meteor-Files#800]
### I have a suggestion:
  - When undo is not implemented, it can be a little bit tricky to delete the file on disk. Sometime devs will want file to be destroyed when requested by the user, and sometime they would just like it to be unlink from mongo. It depends on how much it costs to produce the file and how disk is archived.
  - As far as I've seen ```remove()``` remove both file and db data, ```unlink()``` remove just the file. How to just remove mongo data without triggering file removal?

**Comment by dr-dimitru** [comment]
Hello @e-gaulue ,

You can call `FilesCollection#collection.remove()` method which would remove only MongoDb record.

Here's an example:

```js
const images = new FilesCollection({collectionName: 'Images'});

images.collection.remove({_id: 'string'})
```

`images.collection` in this case is underlying MongoDB collection

**Comment by dr-dimitru** [comment]
@e-gaulue Feel free to close it in case if the issue is solved on your end.

**Comment by e-gaulue** [comment]
@dr-dimitru OK, I will need it if I (or anyone) have got the time to retry to migrate from CollectionFS to Meteor-Files in the wekan/wekan github project.

I can close it now and reopen it at this time, but as you pointed the answer, there shouldn't be any reason to reopen it.

Regards,
