### ISSUE TITLE
Get a list of files that are uploaded

### ISSUE THREAD

**Issue by Michael2109** [veliovgroup/Meteor-Files#801]
I would like to get all files that were uploaded using Meteor-Files so I can display a list to the user.
If I try using `find` it only brings back the last file I uploaded and there aren't any methods like `findAll` etc. 
  
I created a question [here](https://stackoverflow.com/questions/67547720/get-all-files-uploaded-using-meteor-files?noredirect=1#comment119393241_67547720)

**FilesCollection**

	import { FilesCollection } from 'meteor/ostrio:files';

	export const UnprocessedFilesCollection = new FilesCollection({
	  collectionName: 'UnprocessedFiles',
	  allowClientCode: true, // Required to let you remove uploaded file
	  onBeforeUpload(file) {
		// Allow upload files under 10MB, and only in png/jpg/jpeg formats
		if (file.size <= 10485760 && /csv|png|jpg|jpeg/i.test(file.ext)) {
		  return true;
		} else {
		  return 'Please upload image, with size equal or less than 10MB';
		}
	  }
	});

	if (Meteor.isClient) {
	  Meteor.subscribe('files.images.all');
	}

	if (Meteor.isServer) {
	  Meteor.publish('files.images.all', () => {
		return UnprocessedFilesCollection.find().cursor;
	  });
	}

**Client**

    UnprocessedFilesCollection.find();

**Response**

	{
	  "size": 127,
	  "type": "application/vnd.ms-excel",
	  "name": "test.csv",
	  "meta": {},
	  "ext": "csv",
	  "extension": "csv",
	  "extensionWithDot": ".csv",
	  "mime": "application/vnd.ms-excel",
	  "mime-type": "application/vnd.ms-excel",
	  "_id": "C2X9vPvFyu5aGi8jq",
	  "userId": "LFfySMkYjYkCqB3zQ",
	  "path": "assets\\app\\uploads\\UnprocessedFiles\\C2X9vPvFyu5aGi8jq.csv",
	  "versions": {
		"original": {
		  "path": "assets\\app\\uploads\\UnprocessedFiles\\C2X9vPvFyu5aGi8jq.csv",
		  "size": 127,
		  "type": "application/vnd.ms-excel",
		  "extension": "csv"
		}
	  },
	  "_downloadRoute": "/cdn/storage",
	  "_collectionName": "UnprocessedFiles",
	  "isVideo": false,
	  "isAudio": false,
	  "isImage": false,
	  "isText": false,
	  "isJSON": false,
	  "isPDF": false,
	  "_storagePath": "assets\\app\\uploads\\UnprocessedFiles",
	  "public": false
	}

What is the correct method of getting a list of all files that are uploaded?

**Comment by dr-dimitru** [comment]
Hello @Michael2109 ,

Could you double-check records in MongoDB? `meteor mongo` ?

**Comment by Michael2109** [comment]
I've had a look and can see the data looks as expected. I've been playing around trying to get the data and I've found a couple ways. The problem is that I've not used MongoDB a lot so it could be down to my understanding.

If I use `UnprocessedFilesCollection.collection.find({}).fetch();` it will give me a list of all files in the database. The reason I was getting the response before is that I was outputting the `cursor`. 

Is this the correct method of loading the list? Overall I just need a list of filenames and at the moment I'm getting all of the files and their data sent to the client?

**Comment by dr-dimitru** [comment]
@Michael2109 it depends on how you return from the server:
1. `Meteor.methods` you should return array/object
2. `Meteor.publish` you should return cursor, e.g. `UnprocessedFilesCollection.find().cursor`

Please refer to [demo app repo](https://github.com/veliovgroup/meteor-files-website):
- [Client](https://github.com/veliovgroup/meteor-files-website/blob/master/imports/client/index/index.js#L26)

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
