### ISSUE TITLE
".remove" sets the storagePath to null

### ISSUE THREAD

**Issue by n7trd** [VeliovGroup/Meteor-Files#81]
**If i remove a record with: `Images.collection.remove({_id:id});`**

Everything works as expected. (The record is removed from the "Images" Collection.)
If a insert new files after that, they are added to the Collection and FS at 'local\build\programs\server\assets\app\uploads' 
So, no problems here.

**If i want to remove the record AND the file from the FS with: `Images.remove({_id: id});` (same code expect this line)**

Also, everything works as expected. (record and file from FS gets removed, no errors)

**BUT, ALL FILES that i insert after that, are uploaded in an "undefined" folder at "local\build\programs\server\undefined" in opposite to the 'local\build\programs\server\assets\app\uploads' folder before.** 

If you get the output of the file records in `Images.find({}).fetch();` the storagePath is null ('assets/app/uploads' before the remove) and the "path" is something like "undefined/6PTvaQYHdHJe9n6bj.jpg". 

I have this problem on windows and on the ubuntu server that i host.

**Comment by dr-dimitru** [comment]
1. Could you please post your configuration and remove/upload code blocks
 2. Do you allow `allowClientCode`?
 3. Package and Meteor versions you're using?

*It's weird because* `storagePath` *exposed only on Server. No way to overwrite it somehow.*

**Comment by n7trd** [comment]
**Everything works now as expected !**

I was on version v1.5.0, didn't noticed that you updated to 1.5.3 already. I reworked the code with the event-driven API, otherwise didn't changed anything. 

I still wonder what caused the corruption (i had to restart the app to get rid of the behaviour if i removed a file), but it doesn't seem to matter anymore...

Thank you for your time and this awesome package. Coming from cfs, it's a joy to use !

**Comment by dr-dimitru** [comment]
> it's a joy to use 

My pleasure, glad you found it useful. Do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Meteor file upload - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

**Comment by dr-dimitru** [comment]
This issue persists on v1.5.0, fixed by upgrading to v1.5.3
