### ISSUE TITLE
How to use this in angular2 meteor?

### ISSUE THREAD

**Issue by akshath4u** [VeliovGroup/Meteor-Files#83]

**Comment by dr-dimitru** [comment]
I don't use angular, but if you will post your code here, I'll help you.
Or you may ask at [our Gitter](https://gitter.im/VeliovGroup/Meteor-Files)

**Comment by akshath4u** [comment]
Thanks for your response. I have changed the client code for angular2. Now its working fine for me. 
Is there any option to modify the collection as per our need. For example i need the below format,
`{
source : csv,
metadata: {
--all other fields goes here--
}`

**Comment by dr-dimitru** [comment]
Read this article: https://github.com/VeliovGroup/Meteor-Files/wiki/Schema
And this issue: https://github.com/VeliovGroup/Meteor-Files/issues/77

**Comment by akshath4u** [comment]
Thanks. Let me try this

**Comment by akshath4u** [comment]
As per the document i have added schema and attached to default schema. But while uploading file its showing some error
<img width="644" alt="screen shot 2016-05-23 at 4 02 21 pm" src="https://cloud.githubusercontent.com/assets/9428527/15468126/0bfd908a-2100-11e6-9383-2ab957b496af.png">

**Comment by menelike** [comment]
A code example would help a lot. All I can say is that I've successfully added `SimpleSchema` in a similar case. This is a `SimpleSchema` exception anyway and may not belong to this lib.

**Comment by akshath4u** [comment]
Thanks @menelike for the help. Actually i have forgotten to extend the default schema.That was the issue. Now its working fine.
