### ISSUE TITLE
How to validate the file link or check if the image actually exists?

### ISSUE THREAD

**Issue by m4cn4ir** [veliovgroup/Meteor-Files#831]
After redeploying the app, the images folder will be emptied if it is part of the project and not on an external drive.

My current issue is, that after redeploying, the image is obviously gone but I still have the image id in the database which can even generate a (seemingly valid) download link. Only when I actually try to display this image, I find that it doesn´t exist anymore. How can I check if the image actually exists, ideally when generating the download link?

`Images.find().fetch()`

- This returns a list of all the images. But this is just the data from the collection - the broken image would still be in this collection while not on the actual drive.

Trying to fetch the link would work. It does however seem rather tedious..

`                   fetch(downloadLink)
                      .then(response => {
                        if (!response.ok) {
                          console.log('could not find image')
                        } else .... image is ok
                      });
`

Is there any sort of best practice for this?

**Comment by dr-dimitru** [comment]
Hello @m4cn4ir ,

The best practice would be to configure your app the way images aren't overwritten upon deploy. Read no.1 from the [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq) and feel free to close issue in case if it is solved on your end.

**Comment by m4cn4ir** [comment]
Hello and thank you for your answer.

Yes, my plan is to fix the app so that images are saved on an external drive. This situation should then never occur. However it still got me thinking whether I can be absolutely sure that the image exists. For me, it´s critical, because I use these in a 3d context - its loaded as texture. In contrast to html´s <image /> which will default to alt if the image doesnt exist, my app will just crash.. :D Hence the need for validation.
I am however satisfied with the usage of fetch on the server for the validation. Thx :)

**Comment by dr-dimitru** [comment]
@m4cn4ir I recommend using [`fs.stat()`](https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsstatpath-options-callback) default method al library of the Node.js
