### ISSUE TITLE
React Native FilesCollection

### ISSUE THREAD

**Issue by mitsol** [veliovgroup/Meteor-Files#833]
Hi! I'm not sure how to use a FilesCollection with React Native (RN) and Meteor.

I used the official Meteor guide to set up a RN app: https://guide.meteor.com/react-native.html

So i have access to `@meteorrn/core` but how is it now possible for me to access a FileCollection. 

Usually you would do this with (on a non-RN-web app): 

```javascript

import { FilesCollection } from "meteor/ostrio:files";
export const ImageDB = new FilesCollection(chosenSettings);
```
where `chosenSettings` are some settings might be e.g.

```javascript
const chosenSettings = {
  collectionName: "Images",
  allowClientCode: false,
  onBeforeUpload(file) {
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    }
    return "Please upload image, with size equal or less than 10MB";
  },
  storagePath: `${process.env.PWD}/images`,
};
```

However, with RN it is not possible to access `FilesCollection` from `meteor/ostrio:files`

With other collections i can do this in my RN app, however not possible with FilesCollection:

```javascript
const collection = new Mongo.Collection("myCollection");
```

Any suggestions?

**Comment by mitsol** [comment]
I used a workaround that uses a Meteor.Method to get the links via a Method-Call, you'll find the solution here: https://stackoverflow.com/questions/71253191/meteor-and-react-native-filecollection-access

This worked for me

**Comment by dr-dimitru** [comment]
I think it's great, as publishing file's collection to the Client not suitable in 99% cases. I assume initial idea about mimicking Collection API isn't great and makes it difficult to understand. But Meteor-Files intended on replicating CollectionFS API

Feel free to reopen it in case if the issue is still persists on your end.
