### ISSUE TITLE
Event emmitter

### ISSUE THREAD

**Issue by hishamibrah** [veliovgroup/Meteor-Files#837]
I'm having an issue: 
returnMeta returning a event emmiter  on file server.js line 788 because of which the check is being failed.

**Comment by dr-dimitru** [comment]
@hishamibrah can you post an error or exception you experiencing ?

**Comment by dr-dimitru** [comment]
@hishamibrah 
Feel free to close it in case if the issue is solved on your end.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
