### ISSUE TITLE
How namingFunction was changed from 2.0.1 to 2.2.1 ? Uploading files does not work.

### ISSUE THREAD

**Issue by xet7** [veliovgroup/Meteor-Files#847]
Hi,
after upgrade, uploading files does not work:
```
ostrio:files    upgraded from 2.0.1 to 2.2.1
```
I'm getting this error:
```
W20220815-14:33:39.476(3)? (STDERR)     at packages/cfs_http-methods.js:631:30
I20220815-14:34:08.920(3)? Exception while invoking method '_FilesCollectionStart_attachments' TypeError: Cannot read property 'replace' of undefined
I20220815-14:34:08.921(3)?     at FilesCollection.namingFunction (models/attachments.js:44:48)
I20220815-14:34:08.921(3)?     at FilesCollection._prepareUpload (packages/ostrio:files/server.js:990:26)
I20220815-14:34:08.921(3)?     at MethodInvocation.FilesCollection._methods.<computed> (packages/ostrio:files/server.js:849:33)
I20220815-14:34:08.922(3)?     at packages/check/match.js:118:15
I20220815-14:34:08.922(3)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
```
How this namingFunction should be changed?

https://github.com/wekan/wekan/blob/master/models/attachments.js#L44

WeKan Open Source kanban https://wekan.github.io currently uses Meteor 2.7.3, Node 14.20.0 and MongoDB 5.x. WeKan has features to move attachments from MongoDB to filesystem and back.

**Comment by xet7** [comment]
Related https://github.com/veliovgroup/Meteor-Files/issues/842

**Comment by xet7** [comment]
Hmm, I read a little from [docs](https://github.com/veliovgroup/Meteor-Files/blob/master/docs/constructor.md) and tried just commenting out that custom namingFunction in WeKan code. Uploading seems to work now.

@mfilser could comment, did I do anything stupid here.

**Comment by xet7** [comment]
It seems that after that change existing files do not work, because filename does not include text `original`.

**Comment by dr-dimitru** [comment]
Hello @xet7,

- All changes in detail can be found here  — https://github.com/veliovgroup/Meteor-Files/releases
- [updated docs example](https://github.com/veliovgroup/Meteor-Files/commit/f5a335ecd40205a9ee3458ae28c21da9a30a3801#diff-67c5d1eeb5b9b5ab61491a85cbd64123095fd20725e2da172839b4eeae277754R993-R998)
- [Added `namingFunction` to the Client's code](https://github.com/veliovgroup/Meteor-Files/commit/f5a335ecd40205a9ee3458ae28c21da9a30a3801#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406fR988-R992)

**Comment by xet7** [comment]
From https://github.com/wekan/wekan/commit/7c619859fcb6a609581adc8f09c7937b7c2efcc4#commitcomment-81295578

> Hello @xet7  
I've seen https://github.com/veliovgroup/Meteor-Files/issues/847
And I'd like to jump in order to help resolving this one.
Could you explain initial purpose of custom `namingFunction()` hook? Since you have commented it out — it works without it in the expected way?

Commenting out only works for new attachments. Problem is, that this code, that tries to generate filename without extension, does not get filename from `opts.meta.name` anymore at all, replace function does not work to remove extension:
```
    const filenameWithoutExtension = opts.meta.name.replace(/(.+)\..+/, "$1");
```
I did try:
- opts.meta.filename
- opts.meta.fileName
- opts.filename
- etc

With this code, it tries to generate new filename with fileid-original-filenameWithoutExtension:
```
const ret = opts.meta.fileId + "-original-" + filenameWithoutExtension;
```
Problem is, when all that `namingFunction()` code is commented out, all old existing attachments have wrong URL, and are not visible at WeKan kanban board at all.

**Comment by dr-dimitru** [comment]
@xet7 
1. I don't see how `namingFunction` may affect files uploaded before lib update. It runs only in writing/uploading methods
2. Let me know output of `console.log(opts)` inside `namingFunction`

**Comment by xet7** [comment]
@dr-dimitru 

Error message of `namingFunction` is at top first of this issue. That error has come after upgrading Meteor-Files from 2.0.1 to 2.2.1.

**Comment by xet7** [comment]
Hmm, just a moment, I'll try adding `console.log(opts)`

**Comment by dr-dimitru** [comment]
From the [*constructor* docs](https://github.com/veliovgroup/Meteor-Files/blob/master/docs/constructor.md)

> Function which returns `String`. Use it to create nested directories in the storage folder. __Note: file extension appended to returned value__

meaning it will force to append and handle file's extension on its own. And you want uploaded files have no extension?

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4638
