### ISSUE TITLE
ROOT_URL and File Not Found :(

### ISSUE THREAD

**Issue by palpinter** [VeliovGroup/Meteor-Files#85]
Hi,

I'm afraid I don't understand using ROOT_URL in this package. Please help, what is the correct way.

Example:
When I upload images in my dev system locally with ordinary:
meteor --port 3000
everything works as expected.

But when I want to change path with ROOT_URL to access same system for testing external access with:
ROOT_URL=http://palpinter.dlinkddns.com:3000 meteor --port 3000
I receive 'File Not Found :(' error message for all uploaded images.

And if change the port only:
meteor --port 3030
the result is the same, ''File Not Found :('  for all uploaded images. 

How can I change ROOT_URL to access my uploaded images?

Thx
Pal

**Comment by dr-dimitru** [comment]
Have you checked the generated links by `fileURL` template helper?
It uses `__meteor_runtime_config__.ROOT_URL` which is set from `ROOT_URL` env.var, [see here](https://github.com/VeliovGroup/Meteor-Files/blob/master/files.coffee#L1519)

**Comment by palpinter** [comment]
1. Yes I generate links with fileURL, and I change the port only, so...
2. Of course, if I change back the port number, all image visible again.

**Comment by palpinter** [comment]
Maybe the collection definition wrong?

> Images = new FilesCollection(
>   collectionName: 'images'
>   allowClientCode: false
>   storagePath: 'ak/images'
>   onBeforeUpload: (file) ->
>     # Allow upload files under 10MB, and only in png/jpg/jpeg formats
>     if file.size <= 10485760 and /png|jpg|jpeg/i.test(file.ext)
>       true
>     else
>       'Please upload image, with size equal or less than 10MB'
> )

**Comment by dr-dimitru** [comment]
0. Definition looks ok
1. The link is changing? Port is not missed? Could you post the link?
2. What output you're getting when passing `__meteor_runtime_config__.ROOT_URL` to browser's console?
3. Have you tried to sed `debug` to true, could you post here Server's output with debug option?

**Comment by palpinter** [comment]
OK, this very strange.
I have two running system, the second rsynced from the first.
The first started with
ROOT_URL=http://palpinter.dlinkddns.com:3030 meteor --port 3030
The following (and all) picture is exist:
http://palpinter.dlinkddns.com:3030/cdn/storage/images/eAy8AJk5vYtmodWTi/original/eAy8AJk5vYtmodWTi.jpg
__meteor_runtime_config__.ROOT_URL is 'http://palpinter.dlinkddns.com:3030'

The second started with:
ROOT_URL=http://palpinter.dlinkddns.com:3060  meteor --port 3060
The same picture:
http://palpinter.dlinkddns.com:3060/cdn/storage/images/eAy8AJk5vYtmodWTi/original/eAy8AJk5vYtmodWTi.jpg
the result is: 'File Not Found :('
__meteor_runtime_config__.ROOT_URL is 'http://palpinter.dlinkddns.com:3060'

Both instance is absolutely identical. Everything works in the app except images.

**Comment by palpinter** [comment]
You can access both of them now. There is english language version. You can select with flags in upper right corner.

**Comment by dr-dimitru** [comment]
From my end both urls returns 404:
 1. http://palpinter.dlinkddns.com:3060/cdn/storage/images/eAy8AJk5vYtmodWTi/original/eAy8AJk5vYtmodWTi.jpg
 2. http://palpinter.dlinkddns.com:3030/cdn/storage/images/eAy8AJk5vYtmodWTi/original/eAy8AJk5vYtmodWTi.jpg

1. Are you sure those files is transferred via rsync?
2. Have you checked permissions after transferring files via rsync? Try to run `chmod -R 777 /path/to/uploaded/files`

**Comment by palpinter** [comment]
OK, thanks.

**Comment by palpinter** [comment]
OK, the problem not with FILE_URL at all. The real problem is when I restart meteor something delete all images in:
.meteor/local/build/programs/server/ak/images
directory.
The images came from cache by the way.

**Comment by palpinter** [comment]
The problem is bigger than I thought.

Steps to reproduce:
git clone https://github.com/VeliovGroup/Meteor-Files
cd Meteor-Files/demo-simplest-upload
meteor npm install
meteor

upload a file
check .meteor/local/build/programs/server/assets/app/uploads/Images directory - file exist
restart meteor
check .meteor/local/build/programs/server/assets/app/uploads/Images directory - file doesnt exist

Now what should I do. Every restart delete all uploaded files

**Comment by dr-dimitru** [comment]
It's expected behaviour, that's why I asked you multiple times to check physical file existence.
Meteor rebuilds itself on dev-stage, and removes everything what not belongs to it.
Place storage folder outside of the `.meteor` directory, like `/data/meteor/uploads/` and make sure it's writable for user used to run node/meteor command

**Comment by palpinter** [comment]
OK, thank you. I'll try.
