### ISSUE TITLE
Can't upload files on meteor `production`.

### ISSUE THREAD

**Issue by roeurbnavy** [veliovgroup/Meteor-Files#855]
I'm based on :
- Meteor : 2.7.1
- ostrio:files@2.3.0
Hi all, I tried to use upload files on my app. it works well on `development` but I have a problem after I build(deploy) to `production`. 
here is my code:
```js
// Server
const Files = new FilesCollection({
  storagePath: () => {
    return '/data/file_uploads'
  },
  debug: true,
  collectionName: 'app_files',
})


// Client code 
const it = fileList.value[0]
          FilesCollection.insert({
            file: it,
            fileName: it.name,
            chunkSize: 'dynamic',
            onUploaded(err, res) {
              if (err) {
                console.log('err', err)
                // reject(err)
              } else {
                console.log('uploadId', res)
                // resolve(res)
              }
            },
          })
```
here are my logs :  
- on `Development`
![image](https://user-images.githubusercontent.com/20157836/199399270-7ff4f07b-541e-4f4b-a7df-73dd98cfc0d8.png)
- on `Production`
![image](https://user-images.githubusercontent.com/20157836/199399670-2cb439d4-7277-4673-a4e5-ee07cacd146e.png)

Could you help me? I appreciate you.

**Comment by dr-dimitru** [comment]
Hello @roeurbnavy,

I don't see an error or exception on in your issue. Please, update your post following our [ISSUE_TEMPLATE](https://github.com/veliovgroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE)

**Comment by dr-dimitru** [comment]
From the quick look I assume `/data/file_uploads` doesn't exists or not writable on your server

**Comment by roeurbnavy** [comment]
@dr-dimitru Sorry my fault, Now it works fine. Thank you for your reply.
