### ISSUE TITLE
Trying to upload a blob as wav file and getting `Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by Leekao** [veliovgroup/Meteor-Files#856]
I'm trying to upload a blob which is a wav file I want to save on the server, this is my code:

On the client saving the blob:
```
const onComplete = (blob) => {
    const outputFile = new File([blob], "output.wav")
    console.log({outputFile})
    const id = Wavs.insert({
      file: outputFile,
      chunkSize: 'dynamic'
    }, true)
    Meteor.call('New File', id)
    Meteor.setTimeout(startRecording, 1000*60*10)
  };

```
and here is the collection definition file (Isomorphic):

```
import { Meteor } from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';

export const Wavs = new FilesCollection({
  collectionName: 'wavs',
  allowClientCode: true, // Allow remove files from Client
  onBeforeUpload(file) {
    return true;
  }
});

if (Meteor.isClient) {
  Meteor.subscribe('files.wavs.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.wavs.all', function () {
    return Wavs.find().cursor;
  });
}
```

When I run this code I get "Maximum call stack" error and I can't figure out why, can anyone help?

**Comment by dr-dimitru** [comment]
Hello @Leekao,

No idea, you provided so little detail about actual error you get, where? on server?
Please, update your issue following our [ISSUE_TEMPLATE](https://github.com/veliovgroup/Meteor-Files/blob/master/.github/ISSUE_TEMPLATE)

**Comment by Leekao** [comment]
Thank you for your time, I followed the simple upload example and managed to solve my issue, no idea how but it is now resolved.
