### ISSUE TITLE
How do I update a filesCollection after Server side Write created?

### ISSUE THREAD

**Issue by frankwo1** [veliovgroup/Meteor-Files#868]
Hi
I am using Meteor 2.8 and have 3 async steps to complete. I have created a filesCollection via write method on the server after async step 1 - Is it possible to update the filesCollection meta after completing each of the next 2 async steps with the promise buffer or do I need to fs.WriteFile() to config.Storage for each of 3 steps and then use the Write method to create the collection at the end and add them to meta? 
Thanks

**Comment by dr-dimitru** [comment]
Skipped your question as wasn't clear what it it about. Please add more details, show some core, errors, logs, or at least explain what are you trying to accomplish. And feel free to reopen after
