### ISSUE TITLE
Get user ip on upload

### ISSUE THREAD

**Issue by Kaczkazniszczenia** [veliovgroup/Meteor-Files#869]
I'm having difficulties in finding any info on how i can get connection info at server side (IP to be specific) on user who is sending file to server.
Can someone point me to right page or right way to do it  ? Big thanks in advance.

**Comment by jankapunkt** [comment]
I think the `Meteor._lastSessionId` value is stored in the `x-mtok` cookie, which you can use to get the connection from `Meteor.connection` or `Meteor.server` (I'm not 100% sure which one of both you have to look into).

**Comment by dr-dimitru** [comment]
> how i can get connection info at server side

@Kaczkazniszczenia please elaborate what hook/callback you're talking about, and what exactly are you trying to accomplish?

**Comment by dr-dimitru** [comment]
@Kaczkazniszczenia post your code as well, let's speak code please

**Comment by dr-dimitru** [comment]
@Kaczkazniszczenia `onAfterUpload` and `onAfterRemove` and other hooks/callbacks are state-less by nature. I recommend to:

1. use [`.onLogin`](https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-onLogin) to fetch user's current session and IP
2. Update user's object with up-do date details
3. Find user's object in Meteor-File's hooks/callback and use user's details as needed

**Comment by dr-dimitru** [comment]
@Kaczkazniszczenia have you figured it out?

**Comment by Kaczkazniszczenia** [comment]
Thanks for help.
