### ISSUE TITLE
onAfterUpload not throwing error in uploader.on('end')

### ISSUE THREAD

**Issue by guillaumemach** [veliovgroup/Meteor-Files#878]
Hi all, 

### I'm having an issue:
We are trying to perform checks in the settings.onAfterUpload callback (if I understood correctly it is only server side). 
If one check fails we want to return an error, and catch it in the "end" event (client side).

- If we throw an error in the settings.onAfterUpload callback, everything stops and the "end" event never triggers
- If we return an error in the settings.onAfterUpload callback, the "end" event is triggered but no error is received. And we can't find a way to return an error here.

Is there a way to do this ? Is this a bug ?

Meteor@2.12
ostrio:files@2.3.3

Thanks a lot for your help,

Guillaume

**Comment by dr-dimitru** [comment]
Hello @guillaumemach `onAfterUpload` is purely async and happens after upload fully recieved on the server. I'd suggest to look for other hooks in order to complete your goals, like `onBeforeUpload` which can get used on the client as well

**Comment by guillaumemach** [comment]
Hello @dr-dimitru ,

Thanks for your reply. Which hook would you recommend to perform checks on the uplaoded file ?

Bests

**Comment by dr-dimitru** [comment]
@guillaumemach for fully uploaded file the only option is `onAfterUpload`, just don't expect events on the client, I'm suggesting to:
1. Add `verified` or similar option to `meta`
2. subscribe on uploaded file for  changes in `meta.verified`
3. Check file in `onAfterUpload` and update `meta.verified`
4. Perform action based on changes in `meta.verified`

**Comment by guillaumemach** [comment]
@dr-dimitru ok thanks a lot.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
