### ISSUE TITLE
Make Meteor-Files compatible with meteor-desktop?

### ISSUE THREAD

**Issue by dd137** [veliovgroup/Meteor-Files#881]
Hi @dr-dimitru,

Thanks for the great package.

Would you be open to make Meteor-Files compatible with Meteor Community package [meteor-desktop](https://github.com/Meteor-Community-Packages/meteor-desktop)?

That would just require replacing `Meteor.isCordova` by `(Meteor.isCordova || Meteor.isDesktop)` in Meteor-Files and meteor-cookies, which appear once in each of the two repo.

**Comment by dr-dimitru** [comment]
Hello @dd137 , I'm open to accept/review PRs into both

**Comment by dd137** [comment]
Cool, will create the PRs 👍

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
