### ISSUE TITLE
How to get a file names?

### ISSUE THREAD

**Issue by MeDBejoHok** [VeliovGroup/Meteor-Files#89]
Hey. Anybody can tell, how to get the file name and simply insert it into the src? I read the documentation and I'm probably doing something wrong. Because in the collection, I see a lot of things, but I don't see the original file name. 
```
PhotosCollection.load(photoLink, {
      fileName: `${id}.png`,
});
```
but it did not help, files are still named differently.

When I tried to make `ImagesCollection.findOne ({_ id: id}) link ();` I got links to files without the extension. The path to the file at the same time look strange. Something like 
`http://localhost:3000/public/photos/photos/Gd99qerb3e4y6Ee3m/original/Gd99qerb3e4y6Ee3m`

My collection settings
```
PhotosCollection = new FilesCollection({
    storagePath: process.env.PWD + '/public/photos',
    downloadRoute: '/public/photos',
    collectionName: 'photos',
    allowClientCode: false,
    cacheControl: 'public, max-age=31536000',
    onBeforeUpload(file) {
        if (file.size <= 20971520 && /png|jpg|jpeg/i.test(file.ext)) {
            return true;
            } else {
            return 'Please upload image, with size equal or less than 20MB';
        }
    },
    downloadCallback(fileObj) {
        if (this.params.query.download == 'true') {
            // Increment downloads counter
            PhotosCollection.update(fileObj._id, {$inc: {'meta.downloads': 1}});
        }
        return true;
    }
});
```
I just want to get an array of names of files and display them on the client, it is possible even without a path. I write them by myself ;)

**Comment by dr-dimitru** [comment]
Hi @MeDBejoHok 

1. How you're getting URL to file? Are you using `fileURL` template helper or `.link()` method
2. Original file name is stored under `name` property, see [schema](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)
3. About file without extension, this is Client side? How do you publish records to the Client?
4. If you want to store different name for a file - you can pass it to the `meta` object
5. Files stored on the FS has randomly generated names. You can change this behaviour via `namingFunction` (*see [Constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)*), but this is not recommended
6. I guess you want to create "*public*" collection, if so - read about [public property on Constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor)

**Comment by MeDBejoHok** [comment]
Hi @dr-dimitru 

1. const photo = PhotosCollection.findOne({_id: photosIds[0]}).link();
2. Sorry, when I said original I was referring to a file stored in the FS.
3. 
```
Meteor.publish('Photos', function(id) {
  return PhotosCollection.collection.find({meta: {post: id }});
});
```
4. I'm not sure it's what I want.
5. This function is just for naming files, right? I still can't save this name in collection?
6. I don't know, if this is the only way, then probably yes :) I'll try this option.

**Comment by dr-dimitru** [comment]
1. The method call looks good to me, I just want you to make sure `photosIds[0]` is not falsy value
2. Got you, file name on FS is `_id + '.' + extension`
3. Looks good, also just make sure `id` is not empty, I suggest to always use [`audit-argument-checks`](http://docs.meteor.com/#/full/auditargumentchecks) package. Add `check(id, String);` to publish method
4. -
5. See 2
6. It's probably not what you're looking for, names on FS still will be random

**Comment by MeDBejoHok** [comment]
All data is received.
Wait, if I understood you correctly, the name of the file stored in the FS = _id + extension? But it's not.
The file name in the `public` folder is not mentioned anywhere into collection, expect `path`.

**Comment by dr-dimitru** [comment]
> Wait, if I understood you correctly, the name of the file stored in the FS = _id + extension? 

Right

> But it's not.

What do you got? Could you post output of `ls -la` and `PhotosCollection.collection.find().fetch()`?


> The file name in the public folder is not mentioned anywhere into collection, expect path.

`path` property is relative to running pointing right to file on FS

**Comment by MeDBejoHok** [comment]
It's magic, I just made a new entity with two photos and they display. So it was in the morning, but then I noticed that the photos are no longer displayed. Perhaps the problem will reappear. Anyway, at the moment the photo is displayed, but file names in `public` folder don't match with _id in collection.

Here is output of collection. The name of file in `public` folder is ZgqTA9deSug48moPz.png
<img width="726" alt="shot" src="https://cloud.githubusercontent.com/assets/5373823/15593329/d29e87ac-23b3-11e6-9c77-c0e5dc4b657f.png">

**Comment by dr-dimitru** [comment]
What driver version you're on?

**Comment by MeDBejoHok** [comment]
I'm sorry, what driver?

**Comment by dr-dimitru** [comment]
Meteor-Files, package

**Comment by MeDBejoHok** [comment]
ostrio:files@1.5.3

**Comment by dr-dimitru** [comment]
I've checked lib sources (*multiple times*) and I'm 100% `_id` used as filename on FS
Could you add `debug` property set to `true` into `FilesCollection` constructor, then upload the file and post Server's console output?

**Comment by MeDBejoHok** [comment]
Here it is
```
[FilesCollection] [load(https://api.telegram.org/file/bot/photo/file_506.jpg, {"fileName":"d034db0ee99df5b98a6d431e0.png","meta":{"post":"d034db0ee99df5b98a6d431e"}}, callback)]

[FilesCollection] [load(https://api.telegram.org/file/bot/photo/file_508.jpg, {"fileName":"d034db0ee99df5b98a6d431e1.png","meta":{"post":"d034db0ee99df5b98a6d431e"}}, callback)]

[FilesCollection] [load] Received: https://api.telegram.org/file/bot/photo/file_506.jpg
[FilesCollection] [load] [insert] d034db0ee99df5b98a6d431e0.png -> photos
[FilesCollection] [load] Received: https://api.telegram.org/file/bot/photo/file_508.jpg
[FilesCollection] [load] [insert] d034db0ee99df5b98a6d431e1.png -> photos
=> Client modified -- refreshing
```

**Comment by dr-dimitru** [comment]
Sorry, my bad. I've missed your first message. Ok, now I see, you're using `.load()` method.
Hold on while I'm checking it.

**Comment by dr-dimitru** [comment]
Hi @MeDBejoHok 

This is confirmed bug. Could you test v1.5.5 from dev branch?

**Comment by MeDBejoHok** [comment]
Hey @dr-dimitru it works. File names and id's are the same. Thank you for being able to quickly fix it.

**Comment by dr-dimitru** [comment]
@MeDBejoHok thank you for contribution. I'll publish this version in a few days.
Btw do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Files) and [Atmosphere](https://atmospherejs.com/ostrio/files). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Files&text=Meteor file upload - now it's easy!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Files)

**Comment by dr-dimitru** [comment]
@MeDBejoHok If you're still on dev branch, please update to latest commit, major issues were fixed

**Comment by MeDBejoHok** [comment]
Cool, already updated. Tell me, when do you plan to upgrade the master?

**Comment by dr-dimitru** [comment]
You you (*and other contributors*) will not report an issues on `dev` branch - I'll publish an update 1st of June.

Let me know how it works.

**Comment by MeDBejoHok** [comment]
Be sure. I'll stand here :)

**Comment by MeDBejoHok** [comment]
Hey @dr-dimitru what about the update?

**Comment by dr-dimitru** [comment]
Hi @MeDBejoHok ,
will be published in few hours, sorry for delay.

**Comment by dr-dimitru** [comment]
Published, thank you for patience.

**Comment by mgscreativa** [comment]
Hi! I suspect I'm having the same issue, could you please take a look at https://github.com/VeliovGroup/Meteor-Files/issues/364? I'm at ostrio:files v1.6.6
