### ISSUE TITLE
Get FilesCollection instance by name

### ISSUE THREAD

**Issue by TSDrrodriguez** [VeliovGroup/Meteor-Files#90]
I was wondering if this was possible. Right now I'm working to get this package working in full compatibility with AutoForm and I only need to get instantiated objects of FilesCollection by their name. I can get the mongo collection instance with a package from dburles, but when I trigger the remove on the mongo collection instance, the files don't get deleted. I need the remove method from FilesCollection.

Sure an snippet of what I want to do will help:

```
// FilesCollection instance
Files = new FilesCollection({
	collectionName: 'files', // name of the collection
	allowClientCode: true, // Allow or forbid remove files from Client
	onBeforeUpload: function (file) {
		if (file.size <= 10485760 ) {
		  return true;
		} else {
		  return 'El fichero excede el tamaño máximo permitido (10 MB)';
		}
	},
	permissions: 0777,
	storagePath: path,
	
});

// Current removal method:

Files.remove(...).

// What I want to do:

getFilesCollection({collectionName: 'files'}).remove(...)
```

Thank you for this awesome package!

**Comment by dr-dimitru** [comment]
Hi @TSDrrodriguez , sorry for delay.

As you already set the `collectionName` and `allowClientCode` it should work for you. 

1. Are you getting any errors?

**Comment by dr-dimitru** [comment]
@TSDrrodriguez any news?

**Comment by TSDrrodriguez** [comment]
I'm a bit confused right now. Sorry but I am a total noob in github. Do you mean there is already a getFilesCollection method in your package? If so, I am not able to find it in the API.

I asked if there is any method in the package that could allow me to get a FilesCollection instance by its name. Not that I have implemented the method. If you want to remove a file (in the snippet I posted) I should write Files.remove({_id: X}), but that would point statically to the Files instance, and I want to be able to access Files dynamically with its name, store the object in a variable and access that variable when I need it.

Regarding that, I have tried window["Files"] but it returns undefined and I would have to call the Files instance the same as collectionName, so not really a solution. 

I could try adding the the Files instance to an key-value array set up at startup and a method to access it, thought about this as I wrote the comment. I'll report you back next Monday!

**Comment by dr-dimitru** [comment]
>  Do you mean there is already a getFilesCollection method in your package?

No, there is no such method? Do I have to implement it? If, so give me a link to API docs

> I asked if there is any method in the package that could allow me to get a FilesCollection instance by its name.

I got you wrong. Why not use an Object?:
```js
var FSCollections = {};

FSCollections['Images'] = new FilesCollection({collectionName: 'Images'});
FSCollections['Videos'] = new FilesCollection({collectionName: 'Videos'});
FSCollections['Other'] = new FilesCollection({collectionName: 'Other'});

// Then use it somehow, for example by file-type on upload
Template.uploadForm.events({
  'change #fileInput': function (e, template) {
    if (e.currentTarget.files && e.currentTarget.files[0]) {
      var file = e.currentTarget.files[0];
      var collectionName = 'Other';

     if (!!~config.file.type.indexOf('video')) {
       collectionName = 'Videos';
     } else if (!!~config.file.type.indexOf('image')) {
       collectionName = 'Images';
     }

     var upload = FSCollections[collectionName].insert({
        file: file,
        streams: 'dynamic',
        chunkSize: 'dynamic'
     });
    }
  }
});
```

**Comment by dr-dimitru** [comment]
@TSDrrodriguez any news from your end?

**Comment by TSDrrodriguez** [comment]
Sorry but I am busy right now and some priorities have changed in the project :( I have this in mind and have to implement it anyway in the near future. I'll keep you updated.

**Comment by dr-dimitru** [comment]
May I assume it as solved issue for now? (*If so, - please close it*)
You may create a new one at any time, ok?

**Comment by TSDrrodriguez** [comment]
Right! Thank you for the support!
