### ISSUE TITLE
Match error: Expected plain object when linking fileRef on v1.5.6

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#92]
When linking `fileRef` (`Images.link(fileRef, 'thumbnail')`) like explained [here](https://github.com/VeliovGroup/Meteor-Files/blob/c7690067f67d2889fdd64f6f937c438a7aa7466d/docs/link.md)  I get `Match error: Expected plain object`.

This is working on 1.5.4 and breaks on 1.5.6. (could not test v.1.5.5)

**Comment by dr-dimitru** [comment]
Hi @menelike 
Could you post full error stack?
Thank you.

**Comment by dr-dimitru** [comment]
> could not test v.1.5.5

the 1.5.5 is same as 1.5.6, but published version on Atmosphere was somehow broken, and won't install.

**Comment by menelike** [comment]
@dr-dimitru this explains why I could not install v1.5.5, thx.

```
Error: Match error: Expected plain object
    at exports.check (http://127.0.0.1:3000/packages/check.js?hash=a5d98f05c3a7f0c79c37ccded1fc5281bc19c75c:67:15)
    at formatFleURL (http://127.0.0.1:3000/packages/ostrio_files.js?hash=9ab1bd408ff627890bf52e1d1bb39926e0d692ad:2760:3)
    at FilesCollection.link (http://127.0.0.1:3000/packages/ostrio_files.js?hash=9ab1bd408ff627890bf52e1d1bb39926e0d692ad:2735:12)
    at ImagefileItem.render (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:245:48)
    at ImagefileItem.proxiedMethod (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:44:30)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:815:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:841:32)
    at ReactCompositeComponentMixin.performInitialMount (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:351:30)
    at ReactCompositeComponentMixin.mountComponent (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:244:21)
    at Object.ReactReconciler.mountComponent (eval at <anonymous> (http://localhost:3500/assets/web.js:1:0), <anonymous>:46:35) undefined
```

The problem is this [check](https://github.com/VeliovGroup/Meteor-Files/blob/f770331c1181c2983b403b0ff5da2541730ec576/files.coffee#l1627)
I made sure that the fileRef is indeed a document (result of `findOne()`):

```
Document {
_id: "49ZQXxuuQpKvSX4Jh", 
name: "JPEG_20160526_231606_1890930201.jpg", 
extension: "jpg", 
path: "assets/app/uploads/FooFiles/49ZQXxuuQpKvSX4Jh.jpg", 
meta: Object…
}
```

**Comment by dr-dimitru** [comment]
It returns `Document` Object instance? Why?
The error is expected here, as you need to pass a plain Object there.

Try to wrap to `underscore`'s `_.clone()`

**Comment by menelike** [comment]
Well, usually you fetch the data and just use it. Why would you need to assign the data to a new Object?
In terms of the `link()` URL, it should behave like [collection helpers](https://github.com/dburles/meteor-collection-helpers) , and this is actually intended according to [the Readme](https://github.com/VeliovGroup/Meteor-Files/blob/c7690067f67d2889fdd64f6f937c438a7aa7466d/docs/link.md)

I'm not sure if I really understood your point.

**Comment by dr-dimitru** [comment]
I can't understand why `.findOne()` returns not plain Object on your end?

**Comment by menelike** [comment]
Found it, `collection helpers` seem to change `Object` to `Document`. Also this removes `doc.link()`, it seems that `collection helpers` seem to be the wrong way to add methods to resulsets. Any advise how this can be achieved another way?

**Comment by dr-dimitru** [comment]
Have you tried to wrap `fileRef`, into `_.clone()` ?

**Comment by menelike** [comment]
Sure, this will work, but should be the last choice with performance in mind.

**Comment by dr-dimitru** [comment]
I've never faced this package, sorry can't help you here.

**Comment by menelike** [comment]
I solved this with moving the `link()`code to the collection helper. This works better in my case. I addition to `findOne()` this also works with `find()`. Still a solution without repeating code would be better a lot.

Not tested, just to get the idea:

```
FooFiles.collection.helpers({
  link(version = 'original') {
    const { _id, _downloadRoute, _collectionName, extension } = this;
    const downloadRoute = _downloadRoute.substring(1);
    const ext = extension ? `.${extension}` : extension;

    let path = '';
    if (this.public) {
      path = (version === 'original') ? `${downloadRoute}/${_id}${ext}` : `${downloadRoute}/${version}-${_id}${ext}`;
    } else {
      path = `${downloadRoute}/${_collectionName}/${_id}/${version}/${_id}${ext}`;
    }

    return Meteor.absoluteUrl(path, { secure: true });
  },
});
```

Further informations about how to use it: https://github.com/dburles/meteor-collection-helpers

@dr-dimitru thanks for your support!

**Comment by doronrk** [comment]
@menelike running into this issue now myself. @dr-dimitru  Is there a reason for enforcing that _fileRef is a plain object as opposed to the Document that results when using dburles:helpers package?

**Comment by dr-dimitru** [comment]
Hello @doronrk 👋
Please, open new issue following our issue template, do not forget about debug mode.
Thank you 😊
