### ISSUE TITLE
UpdatedAt missing if not using SimpleSchema

### ISSUE THREAD

**Issue by menelike** [VeliovGroup/Meteor-Files#93]
SimpleSchema is not used per default now, this actually breaks `updatedAt` because it is an [autoValue](https://github.com/VeliovGroup/Meteor-Files/blob/f770331c1181c2983b403b0ff5da2541730ec576/files.coffee#l179). It might be better to set this field explicitly.

**Comment by dr-dimitru** [comment]
Do you mean to remove `autoValue`, right? Will you send PR? Or I'll change it in next release.

**Comment by menelike** [comment]
@dr-dimitru I taught of setting `updatedAt` somewhere short before `onAfterUpload`. This is actually just needed to make the data consistent with/without SimpleSchema. I do not intend to remove it, I advise to move this logic away from `SimpleSchema` into this libs core.

If you agree I'll make a PR.

**Comment by dr-dimitru** [comment]
I believe we should, just remove `updatedAt` from default schema and let devs to decide whenever they want or not to use this field

**Comment by menelike** [comment]
Understood, valid point. Do you need a PR for that?

**Comment by dr-dimitru** [comment]
No, I'll change it in `dev` branch right now

**Comment by menelike** [comment]
Thanks for clarification. This can be closed then.

**Comment by dr-dimitru** [comment]
@menelike as always, thank you for contribution and using this package
