### ISSUE TITLE
Error after update from 1.5.3 to 1.5.6

### ISSUE THREAD

**Issue by palpinter** [VeliovGroup/Meteor-Files#94]
HI,

after update from 1.5.3 to 1.5.6 the following code doesnt work.

Collection definition
```
Images = new FilesCollection(
  debug: false
  collectionName: 'images'
  allowClientCode: true
  storagePath: '/srv/http/images'
  onBeforeUpload: (file) ->
    # Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if file.size <= 10485760 and /png|jpg|jpeg/i.test(file.ext)
      true
    else
      'Please upload image, with size equal or less than 10MB'
)
```

and upload

```
  events: 'change input': (e, template) ->
    if e.currentTarget.files and e.currentTarget.files[0]
      file = e.currentTarget.files[0]
      result = Images.insert(
        file: file
        onUploaded: (error, fileObj) ->
          if error
            sAlert.error 'Error during upload: ' + error
          else
            sAlert.success 'A "' + fileObj.name + '" kép sikeresen feltöltve'
          return
        streams: 'dynamic'
        chunkSize: 'dynamic')
      @fileId result.config.fileId
    return
```

The error message is:
Error during upload: Error: Please upload image, with size equal or less than 10MB [403]

But of course the file less than 10MB.

Are there something new in backward compatibility? I've checked the History.md but I haven't found any.

Before update everything was OK.

Thanx
Pal

**Comment by dr-dimitru** [comment]
Yes, it was changed a while ago, from the [docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) (`config.onBeforeUpload` "*comment*" column):
> Because sending <code>meta</code> data as part of every chunk would hit the performance, <code>meta</code> is always empty ({}) except on the first chunk (chunkId=1) and on eof (eof=true)

**Comment by palpinter** [comment]
OK thank you very much.

**Comment by dr-dimitru** [comment]
You're welcome @palpinter
