### ISSUE TITLE
Integration with collection2 and autoform

### ISSUE THREAD

**Issue by felipesmendes** [VeliovGroup/Meteor-Files#96]
Is its possible to integrate with autoform and collection2?

How can we manualy do that?

**Comment by dr-dimitru** [comment]
No idea.
 1. Any special API for autoform?
 2. What about collection2? Could you give me more details?

**Comment by felipesmendes** [comment]
Here is autoform package
https://github.com/aldeed/meteor-autoform 

And collection2 is required to autoform 
https://github.com/aldeed/meteor-collection2

**Comment by dr-dimitru** [comment]
You can create [SimpleSchema](https://github.com/aldeed/meteor-simple-schema), see [Schema section](https://github.com/VeliovGroup/Meteor-Files/wiki/Schema)

**Comment by felipesmendes** [comment]
Cool, 

And what about the form in auto-form?
How can I attach the meteor-files to form generated by autoform?

**Comment by dr-dimitru** [comment]
You describe SimpleSchema as an Object, like in [example](https://github.com/aldeed/meteor-autoform#example). And I think you need to use `after` or `before` [hooks](https://github.com/aldeed/meteor-autoform#callbackshooks)

If you will describe more what you're actually trying to accomplish, then I can help you.

**Comment by dr-dimitru** [comment]
@felipesmendes any news on your end?

**Comment by felipesmendes** [comment]
@dr-dimitru 
Thank you for help, in my case I did like you said in README and don't conflict with autorform!

**Comment by dr-dimitru** [comment]
@felipesmendes so this issue is solved? Right?

**Comment by felipesmendes** [comment]
Right!

**Comment by Neobii** [comment]
I think a lot of people are looking for a replacement for https://atmospherejs.com/yogiben/autoform-file since collectionFS is deprecated now.

**Comment by dr-dimitru** [comment]
@Neobii could you create separate issue for this? I'll put it into milestone.

**Comment by Neobii** [comment]
Okay, however it probably belongs in a separate package.  Still want a good issue written?

**Comment by dr-dimitru** [comment]
yep, just to remember, I'll figure out how to solve it - later
