### ISSUE TITLE
Dynamic Config (storagePath)

### ISSUE THREAD

**Issue by manusharma1** [VeliovGroup/Meteor-Files#99]
Hi, 

How Can I add dynamic Storage Path : config.storagePath

`  var projectid = Router.current().params._id; (I am using Iron Router) `

  `storagePath: '/path/to/uploads/'+projectid,`

Could you Please Suggest something.

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
Hi @manusharma1 ,

Unfortunately it is not possible right now.
If you can explain main purpose for it, then maybe I can help you to find a right way.

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

I want to create a new folder with respect to the router path _id and store the corresponding file to that folder

I mean based on the router _id which is project _id I want to upload documents on the specific folder related to project ID and want every document associated to their corresponding project.

I would be grateful if you can give me some hint or solution to tackle this issue.

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
IDK why but this is common question. But I didn't found the previous one, so *I think you have 2 options*:
 - Every time create a new collection (*what is usually not Okay*)
 - Use `meta` property for association, see [insert method](https://github.com/VeliovGroup/Meteor-Files/wiki/Insert-(Upload))

P.S.: I hope I got your point

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

I agree that we can use meta to insert some values in the the Document in collection, but I wanted to create one directory on the disk and put the project files there so that these would be properly segregated according to the project id. Your Package is wonderful, but If I could create directory it would be perfect solution for me.

Thanks and Best Regards,
Manu

**Comment by manusharma1** [comment]
Is there any way to Generate Configuration Dynamically?, Any Other Way, As I said that your Package is wonderfully but only lacks creatiung the folders dynamically if we want to specify folder per file and upload file to that folder, BTW I tested that if I use some var like below:

```
var projectid = 'test';
storagePath: '/meteor/tops/tops_uploads/'+projectid,
```

Its creating a test directory but I want to have this variable dynamic value, Can you Suggest me something, Believe me that definitely this feature could be required by many other people and it will make your Package great.

Thanks and Regards,
Manu

**Comment by dr-dimitru** [comment]
@manusharma1 thank you, good suggestion. I'll think about how to implement this feature, probably I'll allow to set it as function which should return path as a *String*.

**Comment by manusharma1** [comment]
Thanks @dr-dimitru  for the Update, I will wait for this, I hope you will able to resolve this soon, Thank You So Much

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

Any Update on the feature, How much time you think it will take to get implemented, I mean when you will release this, any Timelines?

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
Still working... PR is welcome.
Next release date will be during next week.

**Comment by dr-dimitru** [comment]
Implemented in `dev` branch, see [16c6c19d40c307275a17274ca67693c50ea9c7ab](https://github.com/VeliovGroup/Meteor-Files/commit/16c6c19d40c307275a17274ca67693c50ea9c7ab)
Please, test it on your end. I'm still confused about this feature, as `storagePath` is server only (*and should be hidden from prying eyes, with security in mind*). IDK how you will pass `projectid`.
Waiting for your responce.

**Comment by dr-dimitru** [comment]
@manusharma1 
 - Have you tested it?
 - Does it work for you?

**Comment by manusharma1** [comment]
Hi @dr-dimitru ,

I have tried it but I am getting some error related to Meteor Accounts after using the dev branch, I will do some more tests and see if it works. I will update you soon.

Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
@manusharma1 waiting roof update from your end. BTW what error are you getting?

**Comment by dr-dimitru** [comment]
Hi @manusharma1 , I'm about to release v1.6.0, have you tested `storagePath()` on your end?

**Comment by manusharma1** [comment]
Hi @dr-dimitru 


Sorry for delay, I was busy with some work.


I am getting the following error:

=> Started proxy.
ostrio:files: updating npm dependencies -- fs-extra, request, throttle,
file-type...
=> Errors prevented startup:

   While building package ostrio:files:
   error: couldn't install npm packages from npm-shrinkwrap: Command
   failed: npm ERR! git submodule -q update --init --recursive: fatal:
   'submodule' appears to be a git command, but we were not
   npm ERR! git submodule -q update --init --recursive: able to execute
   it. Maybe git-submodule is broken?
   npm ERR! git submodule -q update --init --recursive:
   npm ERR! Windows_NT 6.1.7600
   npm ERR! argv "C:\\Users\\Manu
   2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86
_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\Manu
   2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86
_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "install"
   npm ERR! node v0.10.45
   npm ERR! npm  v3.9.6
   npm ERR! code 128

   npm ERR! Command failed: fatal: 'submodule' appears to be a git
   command, but we were not
   npm ERR! able to execute it. Maybe git-submodule is broken?
   npm ERR!
   npm ERR!
   npm ERR! If you need help, you may report this error at:
   npm ERR!     <https://github.com/npm/npm/issues>

   npm ERR! git submodule -q update --init --recursive: fatal: 'submodule'
   appears to be a git command, but we were not
   npm ERR! git submodule -q update --init --recursive: able to execute
   it. Maybe git-submodule is broken?
   npm ERR! git submodule -q update --init --recursive:
   npm ERR! Windows_NT 6.1.7600
   npm ERR! argv "C:\\Users\\Manu
   2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86
_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\Manu
   2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4_1\\mt-os.windows.x86
_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "install"
   npm ERR! node v0.10.45
   npm ERR! npm  v3.9.6
   npm ERR! code 128

   npm ERR! Command failed: fatal: 'submodule' appears to be a git
   command, but we were not
   npm ERR! able to execute it. Maybe git-submodule is broken?
   npm ERR!
   npm ERR!
   npm ERR! If you need help, you may report this error at:
   npm ERR!     <https://github.com/npm/npm/issues>



=> Your application has errors. Waiting for file change.



Thanks and Best Regards,
Manu

**Comment by manusharma1** [comment]
I also tried this on the older version of meteor and there Its started, but I am getting the following error in console and app is not loading in browser:

**TypeError: Accounts.onLogout is not a function**


**file : ostrio_files.js** 

        Accounts.onLogout(function() {                                                                                 // 488



Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
Hi @manusharma1 ,

1. First Error seems to be unrelated to MF package, (I guess it's related to [Meteor bug](https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460))
2. Do you have `accounts-base` installed? (*It's not required, but if you have it installed MF sets* `onLogout` *hook*)

**Comment by manusharma1** [comment]
Hi @dr-dimitru , I have tried it again after installing the accounts-base and with your latest dev code, I am getting the following error:

		=> Errors prevented startup:

		   While selecting package versions:
		   error: Conflict: Constraint webapp@1.2.9 is not satisfied by webapp
		   1.2.3.
		   Constraints on package "webapp":
		   * webapp@=1.2.3 <- top level
		   * webapp@1.2.2 <- meteor-base 1.0.1
		   * webapp@1.2.2 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * webapp@1.2.2 <- routepolicy 1.0.6 <- webapp 1.2.3 <- iron:router
		   1.0.12
		   * webapp@1.2.3 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * webapp@1.2.3 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * webapp@1.2.3 <- mongo 1.1.3
		   * webapp@1.1.1 <- iron:router 1.0.12
		   * webapp@1.2.9 <- ostrio:files 1.6.0
		   * webapp@1.1.4 <- ostrio:cookies 2.0.4 <- ostrio:files 1.6.0

		   Conflict: Constraint underscore@1.0.9 is not satisfied by underscore
		   1.0.4.
		   Constraints on package "underscore":
		   * underscore@=1.0.4 <- top level
		   * underscore@1.0.4 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- meteor 1.1.10 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- webapp 1.2.3 <- autoupdate 1.2.4 <- hot-code-push
		   1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- webapp 1.2.3 <- iron:router 1.0.12
		   * underscore@1.0.4 <- logging 1.0.8 <- webapp 1.2.3 <- autoupdate 1.2.4
		   <- hot-code-push 1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- logging 1.0.8 <- webapp 1.2.3 <- iron:router
		   1.0.12
		   * underscore@1.0.4 <- ejson 1.0.7 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- routepolicy 1.0.6 <- ddp-server 1.2.2 <- ddp
		   1.2.2 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- routepolicy 1.0.6 <- webapp 1.2.3 <- iron:router
		   1.0.12
		   * underscore@1.0.4 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
		   autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- boilerplate-generator 1.0.4 <- webapp 1.2.3 <-
		   iron:router 1.0.12
		   * underscore@1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator
		   1.0.4 <- webapp 1.2.3 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * underscore@1.0.4 <- spacebars-compiler 1.0.7 <- boilerplate-generator
		   1.0.4 <- webapp 1.2.3 <- iron:router 1.0.12
		   * underscore@1.0.4 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <-
		   boilerplate-generator 1.0.4 <- webapp 1.2.3 <- autoupdate 1.2.4 <-
		   hot-code-push 1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- blaze-tools 1.0.4 <- spacebars-compiler 1.0.7 <-
		   boilerplate-generator 1.0.4 <- webapp 1.2.3 <- iron:router 1.0.12
		   * underscore@1.0.4 <- spacebars 1.0.7 <- blaze-html-templates 1.0.1
		   * underscore@1.0.4 <- blaze 2.1.3 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- check 1.1.0 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- observe-sequence 1.0.7 <- blaze 2.1.3 <-
		   accounts-base 1.2.2
		   * underscore@1.0.4 <- id-map 1.0.4 <- binary-heap 1.0.4 <- mongo 1.1.3
		   * underscore@1.0.4 <- random 1.0.5 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- diff-sequence 1.0.1 <- ddp-client 1.2.1 <- ddp
		   1.2.2 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- diff-sequence 1.0.1 <- minimongo 1.0.10 <- mongo
		   1.1.3
		   * underscore@1.0.4 <- diff-sequence 1.0.1 <- mongo 1.1.3
		   * underscore@1.0.4 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <-
		   autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- webapp-hashing 1.0.5 <- webapp 1.2.3 <-
		   iron:router 1.0.12
		   * underscore@1.0.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base
		   1.2.2
		   * underscore@1.0.4 <- retry 1.0.4 <- autoupdate 1.2.4 <- hot-code-push
		   1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2
		   <- accounts-base 1.2.2
		   * underscore@1.0.4 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base
		   1.2.2
		   * underscore@1.0.4 <- callback-hook 1.0.4 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- minimongo 1.0.10 <- ddp-server 1.2.2 <- ddp 1.2.2
		   <- accounts-base 1.2.2
		   * underscore@1.0.4 <- minimongo 1.0.10 <- mongo 1.1.3
		   * underscore@1.0.4 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <-
		   ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- ordered-dict 1.0.4 <- minimongo 1.0.10 <- mongo
		   1.1.3
		   * underscore@1.0.4 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * underscore@1.0.4 <- mongo 1.1.3
		   * underscore@1.0.4 <- binary-heap 1.0.4 <- mongo 1.1.3
		   * underscore@1.0.4 <- http 1.1.1
		   * underscore@1.0.4 <- url 1.0.5 <- http 1.1.1
		   * underscore@1.0.4 <- reload 1.1.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * underscore@1.0.4 <- reload 1.1.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * underscore@1.0.4 <- reload 1.1.4 <- session 1.1.1
		   * underscore@1.0.4 <- templating 1.1.5 <- blaze-html-templates 1.0.1
		   * underscore@1.0.4 <- caching-html-compiler 1.0.2 <- templating 1.1.5
		   <- blaze-html-templates 1.0.1
		   * underscore@1.0.4 <- templating-tools 1.0.0 <- caching-html-compiler
		   1.0.2 <- templating 1.1.5 <- blaze-html-templates 1.0.1
		   * underscore@1.0.4 <- templating-tools 1.0.0 <- templating 1.1.5 <-
		   blaze-html-templates 1.0.1
		   * underscore@1.0.4 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <-
		   boilerplate-generator 1.0.4 <- webapp 1.2.3 <- autoupdate 1.2.4 <-
		   hot-code-push 1.0.0 <- meteor-base 1.0.1
		   * underscore@1.0.4 <- minifiers 1.1.7 <- spacebars-compiler 1.0.7 <-
		   boilerplate-generator 1.0.4 <- webapp 1.2.3 <- iron:router 1.0.12
		   * underscore@1.0.4 <- minifiers 1.1.7 <- standard-minifiers 1.0.2
		   * underscore@1.0.4 <- session 1.1.1
		   * underscore@1.0.4 <- reactive-dict 1.1.3 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * underscore@1.0.4 <- reactive-dict 1.1.3 <- session 1.1.1
		   * underscore@1.0.0 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:layout 1.0.12 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * underscore@1.0.0 <- iron:layout 1.0.12 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:core 1.0.11 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * underscore@1.0.0 <- iron:core 1.0.11 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:dynamic-template 1.0.12 <- iron:controller
		   1.0.12 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:middleware-stack 1.0.11 <- iron:router
		   1.0.12
		   * underscore@1.0.0 <- iron:url 1.0.11 <- iron:location 1.0.11 <-
		   iron:router 1.0.12
		   * underscore@1.0.0 <- iron:url 1.0.11 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:location 1.0.11 <- iron:router 1.0.12
		   * underscore@1.0.0 <- iron:controller 1.0.12 <- iron:router 1.0.12
		   * underscore@1.0.4 <- accounts-password 1.1.4
		   * underscore@1.0.4 <- accounts-base 1.2.2
		   * underscore@1.0.4 <- rate-limit 1.0.0 <- ddp-rate-limiter 1.0.0 <-
		   accounts-base 1.2.2
		   * underscore@1.0.4 <- srp 1.0.4 <- accounts-password 1.1.4
		   * underscore@1.0.4 <- email 1.0.8
		   * underscore@1.0.1 <- ostrio:iron-router-title 1.0.2
		   * underscore@1.0.0 || 1.0.1 <- sacha:spin 2.3.1
		   * underscore@1.0.0 <- reywood:publish-composite 1.4.2
		   * underscore@1.0.9 <- ostrio:files 1.6.0
		   * underscore@1.0.1 <- ostrio:cookies 2.0.4 <- ostrio:files 1.6.0
		   * underscore@1.0.1 <- ostrio:templatehelpers 1.1.2

		   Conflict: Constraint check@1.2.3 is not satisfied by check 1.1.0.
		   Constraints on package "check":
		   * check@=1.1.0 <- top level
		   * check@1.0.6 <- blaze 2.1.3 <- accounts-base 1.2.2
		   * check@1.0.5 <- babel-compiler 5.8.24_1 <- ecmascript 0.1.6
		   * check@1.0.6 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * check@1.1.0 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * check@1.1.0 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * check@1.1.0 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base
		   1.0.1
		   * check@1.1.0 <- mongo 1.1.3
		   * check@1.1.0 <- accounts-password 1.1.4
		   * check@1.1.0 <- accounts-base 1.2.2
		   * check@1.0.6 <- srp 1.0.4 <- accounts-password 1.1.4
		   * check@1.2.3 <- ostrio:files 1.6.0

		   Conflict: Constraint random@1.0.10 is not satisfied by random 1.0.5.
		   Constraints on package "random":
		   * random@=1.0.5 <- top level
		   * random@1.0.4 <- observe-sequence 1.0.7 <- blaze 2.1.3 <-
		   accounts-base 1.2.2
		   * random@1.0.4 <- mongo-id 1.0.1 <- ddp-client 1.2.1 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * random@1.0.4 <- mongo-id 1.0.1 <- minimongo 1.0.10 <- mongo 1.1.3
		   * random@1.0.4 <- mongo-id 1.0.1 <- mongo 1.1.3
		   * random@1.0.4 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * random@1.0.4 <- retry 1.0.4 <- autoupdate 1.2.4 <- hot-code-push
		   1.0.0 <- meteor-base 1.0.1
		   * random@1.0.5 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * random@1.0.5 <- ddp-server 1.2.2 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * random@1.0.4 <- minimongo 1.0.10 <- ddp-server 1.2.2 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * random@1.0.4 <- minimongo 1.0.10 <- mongo 1.1.3
		   * random@1.0.5 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * random@1.0.5 <- mongo 1.1.3
		   * random@1.0.4 <- caching-compiler 1.0.0 <- caching-html-compiler 1.0.2
		   <- templating 1.1.5 <- blaze-html-templates 1.0.1
		   * random@1.0.4 <- caching-compiler 1.0.0 <- coffeescript 1.0.11 <-
		   ostrio:files 1.6.0
		   * random@1.0.0 <- iron:dynamic-template 1.0.12 <- iron:controller
		   1.0.12 <- iron:router 1.0.12
		   * random@1.0.5 <- accounts-password 1.1.4
		   * random@1.0.5 <- accounts-base 1.2.2
		   * random@1.0.4 <- rate-limit 1.0.0 <- ddp-rate-limiter 1.0.0 <-
		   accounts-base 1.2.2
		   * random@1.0.4 <- localstorage 1.0.5 <- accounts-base 1.2.2
		   * random@1.0.4 <- srp 1.0.4 <- accounts-password 1.1.4
		   * random@1.0.10 <- ostrio:files 1.6.0

		   Conflict: Constraint coffeescript@1.1.1 is not satisfied by
		   coffeescript 1.0.11.
		   Constraints on package "coffeescript":
		   * coffeescript@=1.0.11 <- top level
		   * coffeescript@1.0.4 <- ostrio:iron-router-title 1.0.2
		   * coffeescript@1.0.4 <- ostrio:iron-router-helper-class 1.0.0 <-
		   ostrio:iron-router-title 1.0.2
		   * coffeescript@1.1.1 <- ostrio:files 1.6.0
		   * coffeescript@1.0.4 <- ostrio:cookies 2.0.4 <- ostrio:files 1.6.0

		   Conflict: Constraint templating@1.1.11 is not satisfied by templating
		   1.1.5.
		   Constraints on package "templating":
		   * templating@=1.1.5 <- top level
		   * templating@1.1.3 <- launch-screen 1.0.4 <- mobile-experience 1.0.1
		   * templating@1.1.2 <- blaze-html-templates 1.0.1
		   * templating@1.0.6 <- iron:router 1.0.12
		   * templating@1.0.6 <- iron:layout 1.0.12 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * templating@1.0.6 <- iron:layout 1.0.12 <- iron:router 1.0.12
		   * templating@1.0.6 <- iron:dynamic-template 1.0.12 <- iron:controller
		   1.0.12 <- iron:router 1.0.12
		   * templating@1.0.6 <- iron:controller 1.0.12 <- iron:router 1.0.12
		   * templating@1.0.4 || 1.0.9 <- sacha:spin 2.3.1
		   * templating@1.0.4 <- ephemer:reactive-datatables 1.1.0
		   * templating@1.1.11 <- ostrio:files 1.6.0
		   * templating@1.0.9 <- ostrio:templatehelpers 1.1.2

		   Conflict: Constraint reactive-var@1.0.10 is not satisfied by
		   reactive-var 1.0.6.
		   Constraints on package "reactive-var":
		   * reactive-var@=1.0.6 <- top level
		   * reactive-var@1.0.6 <- blaze 2.1.3 <- accounts-base 1.2.2
		   * reactive-var@1.0.1 <- iron:dynamic-template 1.0.12 <- iron:controller
		   1.0.12 <- iron:router 1.0.12
		   * reactive-var@1.0.3 <- ostrio:iron-router-title 1.0.2
		   * reactive-var@1.0.10 <- ostrio:files 1.6.0

		   Conflict: Constraint tracker@1.0.14 is not satisfied by tracker 1.0.9.
		   Constraints on package "tracker":
		   * tracker@=1.0.9 <- top level
		   * tracker@1.0.8 <- deps 1.0.9 <- htmljs 1.0.5 <- blaze 2.1.3 <-
		   accounts-base 1.2.2
		   * tracker@1.0.8 <- deps 1.0.9 <- iron:router 1.0.12
		   * tracker@1.0.8 <- spacebars 1.0.7 <- blaze-html-templates 1.0.1
		   * tracker@1.0.8 <- blaze 2.1.3 <- accounts-base 1.2.2
		   * tracker@1.0.8 <- observe-sequence 1.0.7 <- blaze 2.1.3 <-
		   accounts-base 1.2.2
		   * tracker@1.0.8 <- reactive-var 1.0.6
		   * tracker@1.0.8 <- ddp-client 1.2.1 <- ddp 1.2.2 <- accounts-base 1.2.2
		   * tracker@1.0.9 <- ddp-common 1.2.2 <- ddp-client 1.2.1 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * tracker@1.0.9 <- minimongo 1.0.10 <- ddp-server 1.2.2 <- ddp 1.2.2 <-
		   accounts-base 1.2.2
		   * tracker@1.0.9 <- minimongo 1.0.10 <- mongo 1.1.3
		   * tracker@1.0.9 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <-
		   meteor-base 1.0.1
		   * tracker@1.0.9 <- mongo 1.1.3
		   * tracker@1.0.9 <- reactive-dict 1.1.3 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * tracker@1.0.9 <- reactive-dict 1.1.3 <- session 1.1.1
		   * tracker@1.0.2 <- iron:layout 1.0.12 <- iron:controller 1.0.12 <-
		   iron:router 1.0.12
		   * tracker@1.0.2 <- iron:layout 1.0.12 <- iron:router 1.0.12
		   * tracker@1.0.2 <- iron:dynamic-template 1.0.12 <- iron:controller
		   1.0.12 <- iron:router 1.0.12
		   * tracker@1.0.2 <- iron:location 1.0.11 <- iron:router 1.0.12
		   * tracker@1.0.2 <- iron:controller 1.0.12 <- iron:router 1.0.12
		   * tracker@1.0.9 <- accounts-base 1.2.2
		   * tracker@1.0.5 <- simple:reactive-method 1.0.2
		   * tracker@1.0.14 <- ostrio:files 1.6.0

		   Conflict: Constraint http@1.1.6 is not satisfied by http 1.1.1.
		   Constraints on package "http":
		   * http@=1.1.1 <- top level
		   * http@1.1.1 <- autoupdate 1.2.4 <- hot-code-push 1.0.0 <- meteor-base
		   1.0.1
		   * http@1.1.6 <- ostrio:files 1.6.0
		   * http@1.0.8 <- ostrio:cookies 2.0.4 <- ostrio:files 1.6.0

		=> Your application has errors. Waiting for file change.



Thanks and Best Regards,
Manu

**Comment by dr-dimitru** [comment]
@manusharma1 ,

Make sure Meteor version is equal or higher to `1.3.3.1`
